import 'package:flutter/material.dart';

import '../../model/question.dart';
import '../../model/test_list_homepage_model.dart';

class CevreIklimQuesViewModel extends ChangeNotifier{
  ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),

  List<TestListHomepageModel> _cevreIklimList=[
    TestListHomepageModel("Çevre İklim-Karışık Test Çöz",[
      Question("cevreiklim_ques_Q1","", "Tüm canlıların hayat boyu ilişkilerini sürdürdükleri ortama aşağıdakilerden hangisi denir?","Çevre",["Sosyal alan","Korunan alan","Orman","Çevre","Milli Park"]),
      Question("cevreiklim_ques_Q2","", "Aşağıdakilerden hangisi çevrenin önemleri arasında sayılamaz?","İnsan yetkisiyle değiştirilir ve geliştirilir",["Hayatın sürdürülmesi için temel unsurdur","Tüm kaynakların yer aldığı merkezdir","İnsan yetkisiyle değiştirilir ve geliştirilir","Ortak kullanım alanıdır","Canlıların etkileşimlerine ev sahipliği yapar"]),
      Question("cevreiklim_ques_Q3","Toplumun, tüm canlılara hitap eden ortak kullanım alanlarında, doğru etkileşimi kurması için gerekli temel kuralları öğrenmesi esastır.", "Yukarıdaki bilgiye göre aşağıdakilerden hangisi bireyin gelişiminde önemli bir yere sahiptir?","Çevre eğitimi",["Çevre eğitimi","Sosyal alan becerisi","Sorun çözme bilgisi","Temel eğitim","Aile eğitimi"]),
      Question("cevreiklim_ques_Q4","I-Aktif katılım\nII-Kalıcı öğrenme\nIII-Bilinçlenme", "Yukarıdakilerden hangisi veya hangileri çevre eğitiminin amaçları arasında yer alır?","II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q5","Yaşanılabilir çevre oluşturma sürecinde olumlu davranış değişiklikleri gerçekleştirmek temel gayelerimizden birisi olmalıdır.", "Buna göre aşağıdakilerden hangisine ağırlık verilmesi gerekmektedir?","Çevre eğitimi",["Çevre tanıma","Çevre eğitimi","Çevre düzenleme","Çevre yargılama","Çevre hassasiyeti"]),
      Question("cevreiklim_ques_Q6","", "Aşağıdakilerden hangisi çevre eğitimi kapsamında yapılabileceklerden biri olarak gösterilemez?","Çevre bilincinin aile eğitimleri ile oluşmasını beklemek",["Okul öncesi gruba etkinlikler düzenlemek","İlkokul düzeyindeki öğrencilere çevre eğitimi ile ilgili oyunlar oynatmak","Çevre bilincinin aile eğitimleri ile oluşmasını beklemek","Ortaöğretim düzeyi öğrencilerine seminerler vermek","Yaş grubuna göre sorumluluklar yüklemek"]),
      Question("cevreiklim_ques_Q7","I-Okul öncesi\nII-İlköğretim\nIII-Ortaöğretim", "Yukarıdakilerden hangisi veya hangileri çevre eğitimi verilebilecek yaş grupları arasında sayılabilir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
      Question("cevreiklim_ques_Q8","", "Çevre eğitimlerin başlayabileceği en erken yaş düzeyi aşağıdakilerden hangisinde doğru olarak verilmiştir?","Okul öncesi",["Okul öncesi","İlköğretim","Ortaokul","Ortaöğretim","Yükseköğretim"]),
      Question("cevreiklim_ques_Q9","", "Doğal çevreye dikkat ederek, saygı duyarak ve olumlu tutum ve davranışlar geliştirerek faydalı davranışlarda bulunmaya aşağıdakilerden hangisi denir?","Çevre bilinci",["Çevre bilgisi","Çevre eğitimi","Çevre düzeni","Çevre bilinci","Çevresel farkındalık"]),
      Question("cevreiklim_ques_Q10","", "Aşağıdakilerden hangisi çevre bilincine sahip bireylerde görülmesi gereken davranışlardan biridir?","Çevreye uyum sağlamak",["Çevreyi etkileyen olaylara kayıtsız kalmak","Çevre ile etkileşimini azaltmak","Çevreye uyum sağlamak","Çevreyi etkileyecek durumlarda çekimser duruş sergilemek","Çevre bilincini oluşturacak etkinliklerden uzak durmak"]),
      Question("cevreiklim_ques_Q11","5. sınıf kademesinde sınıfı olan Semra öğretmen, sınıfına çevre bilinci konusunda faydalı bilgiler vermek istemiş ancak yapacağı etkinlikler konusunda kararsız kalmıştır.", "Aşağıdakilerden hangisi Semra öğretmene verilebilecek tavsiyelerden biri olamaz?","Öğrencilerine eğitimlerini ailelerinin tamamlamasını bildirmeli",["Öğrencilerinin çevre ile etkileşimlerini arttırmalı","Öğrencilerine eğitimlerini ailelerinin tamamlamasını bildirmeli","Görsel materyaller ile anlatımlarını desteklemeli","Farkındalık oluşturacak etkinlikler düzenleyerek öğrencilerine görevler vermeli","Küçük yarışmalar düzenleyerek ödüllendirmeler yapmalı"]),
      Question("cevreiklim_ques_Q12","I-Çevre analizi\nII-Çevreyi tanıma\nIII-Nüfus hareketliliği", "Okul öncesi eğitim kademesinde öğrencilerin yukarıdaki sorumluluklardan hangisine sahip olmaları beklenir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q13","", "Aşağıdakilerden hangisi ortaokul kademesindeki öğrencilerin çevre ile ilgili yapması beklenen davranışlardan biri değildir?","Bilimsel araştırmalar yapma",["Bilimsel araştırmalar yapma","Çevresel konularda sentez düzeyinde tutum geliştirme","Çevre ile ilgili analizler gerçekleştirme","Çevre bilgisini tamamlamış olma","Çevrede olup bitenleri kavrama"]),
      Question("cevreiklim_ques_Q14","", "Aşağıdakilerden hangisi doğal dengelerin bozulması ile ilgili değildir?","Yanardağ hareketliliğinin artması",["Asit yağmurlarının yağması","Yanardağ hareketliliğinin artması","Hava kirliliğinin artması","Topraktaki zararlıların artması","Karbon salınımının artması"]),
      Question("cevreiklim_ques_Q15","", "Hangisi ekolojik ayak izlerinden biri değildir?", "Hava Sahası Ayak İzi", ["Otlak Alanı Ayak İzi","Tarım Arazisi Ayak İzi","Hava Sahası Ayak İzi","Yapılaşmış Alan Ayak İzi","Otlak Alanı Ayak İzi"]),
      Question("cevreiklim_ques_Q16","", "Ekolojik ayak izi bileşenlerini altı başlık atında toplayan uluslararası kuruluş aşağıdakilerden hangisidir?", "Dünya Doğayı Koruma Vakfı", ["Birleşmiş Milletler Çevre Örgütü","Dünya Sağlık Örgütü","Ekonomik İşbirliği ve Kalkınma Örgütü","Dünya Doğayı Koruma Vakfı","Doğa İşbirliği Teşkilatı"]),
      Question("cevreiklim_ques_Q17","", "Yapılaşmış Alan Ayak İzi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Konut, ulaşım ve endüstriye ayrılmış alanlar", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal otlaklar","Ormanlar","Tarım Alanları"]),
      Question("cevreiklim_ques_Q18","", "Otlak alanı ayak İzi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Doğal ve yarı doğal meralar", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal meralar","Ormanlar","Tarım Alanları"]),
      Question("cevreiklim_ques_Q19","", "Tarım arazisi ayak izi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Ekim Dikim Alanları", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal meralar","Ormanlar","Ekim Dikim Alanları"]),
      Question("cevreiklim_ques_Q20","", "Karbon ayak izi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Sera gazı miktarı", ["Okyanus","Sera gazı miktarı","Doğal otlaklar","Ormanlar","Ekim Dikim Alanları"]),
      Question("cevreiklim_ques_Q21","I-Depremler\nII-Seller\nIII-Volkanik Patlamalar", "Yukarıdaki ifadelerden hangileri çevre kirliliğinin doğal sebepleri arasındadır?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q22","I-Nüfus Artışı\nII-Fosil Yakıtlar\nIII-Volkanik Patlamalar", "Yukarıdaki ifadelerden hangileri çevre kirliliğinin doğal sebeplerinden değildir?", "I-II", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q23","", "Çevre kirliliği sebepleri hangi şıkta doğru olarak verilmiştir?", "İnsan Faaliyetleri ve Doğal Sebepler", ["İnsan Faaliyetleri ve Doğal Sebepler","Doğal ve Yapay Sebepler","İnsan Faaliyetleri ve Yapay Sebepler","Varoluşsal ve Evrimsel Sebepler","Devinimsel ve Doğal Sebepler"]),
      Question("cevreiklim_ques_Q24","", "İnsanların ………… üzerindeki yükünü ve sürdürülebilirlik seviyelerini ölçmek için …………………….. yöntemi kullanılır, ifadesinde noktalı yerlere gelmesi gereken ifade aşağıdakilerden hangisidir?", "Ekosistemler-Ekolojik Ayak İzi", ["Ekolojik Ayak İzi-Ekosistemler","Ekosistemler-Kruger21","Doğa-Orman Alanı Ayak İzi","Ekosistemler-Ekolojik Ayak İzi","Dünya-Ayak İzi"]),
      Question("cevreiklim_ques_Q25","I-Plansız Şehirleşme\nII-Hızlı Nüfus Artışı\nIII-Fosil Yakıtların Kullanımı", "Yukarıda verilen ifadelerden hangileri çevre kirliliğinin insan kaynaklı sebeplerindendir?", "Hepsi", ["Yalnız I","II-III","I-III","I-II","Hepsi"]),
      Question("cevreiklim_ques_Q26","I-Seller\nII-Depremler\nIII-Endüstriyel Atıklar", "Yukarıda verilen ifadelerden hangileri çevre kirliliğinin insan kaynaklı sebeplerinden değildir?", "I-II", ["Yalnız I","II-III","I-III","I-II","I-II-III"]),
      Question("cevreiklim_ques_Q27","", "İnsanların ekosistem üzerindeki yükünü hesaplamak için kullanılan yöntem aşağıdakilerden hangisidir?", "Ekolojik Ayak İzi", ["Ekolojik Ayak İzi","Orman Alanı Ayak İzi","Otlak Alanı Ayak İzi","Tarım Arazisi Ayak İzi",""]),
      Question("cevreiklim_ques_Q28","I-Çevre sorunları farkındalığı\nII-Çevre ile İlgili Tutum\nIII-Çevre ile İlgili Davranışlar", "Okullarda verilen ekolojik ayak izi eğitimleri yukarıdaki kavramlardan hangilerini olumlu etkiler?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q29","I-Azot Döngüsü\nII-Flor Döngüsü\nIII-Fosfor Döngüsü", "Yukarıda verilen madde döngülerinden hangileri doğru olarak verilmiştir?", "I-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q30","I- Karbon Döngüsü\nII-Oksijen Döngüsü\nIII-Azot Döngüsü", "Yukarıda verilen döngülerden hangilerinin bir bölümü atmosferde gerçekleşir?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),

    ]),
    TestListHomepageModel("Çevre İklim-Test 1",[
      Question("cevreiklim_ques_Q1","", "Tüm canlıların hayat boyu ilişkilerini sürdürdükleri ortama aşağıdakilerden hangisi denir?","Çevre",["Sosyal alan","Korunan alan","Orman","Çevre","Milli Park"]),
      Question("cevreiklim_ques_Q2","", "Aşağıdakilerden hangisi çevrenin önemleri arasında sayılamaz?","İnsan yetkisiyle değiştirilir ve geliştirilir",["Hayatın sürdürülmesi için temel unsurdur","Tüm kaynakların yer aldığı merkezdir","İnsan yetkisiyle değiştirilir ve geliştirilir","Ortak kullanım alanıdır","Canlıların etkileşimlerine ev sahipliği yapar"]),
      Question("cevreiklim_ques_Q3","Toplumun, tüm canlılara hitap eden ortak kullanım alanlarında, doğru etkileşimi kurması için gerekli temel kuralları öğrenmesi esastır.", "Yukarıdaki bilgiye göre aşağıdakilerden hangisi bireyin gelişiminde önemli bir yere sahiptir?","Çevre eğitimi",["Çevre eğitimi","Sosyal alan becerisi","Sorun çözme bilgisi","Temel eğitim","Aile eğitimi"]),
      Question("cevreiklim_ques_Q4","I-Aktif katılım\nII-Kalıcı öğrenme\nIII-Bilinçlenme", "Yukarıdakilerden hangisi veya hangileri çevre eğitiminin amaçları arasında yer alır?","II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q5","Yaşanılabilir çevre oluşturma sürecinde olumlu davranış değişiklikleri gerçekleştirmek temel gayelerimizden birisi olmalıdır.", "Buna göre aşağıdakilerden hangisine ağırlık verilmesi gerekmektedir?","Çevre eğitimi",["Çevre tanıma","Çevre eğitimi","Çevre düzenleme","Çevre yargılama","Çevre hassasiyeti"]),
      Question("cevreiklim_ques_Q6","", "Aşağıdakilerden hangisi çevre eğitimi kapsamında yapılabileceklerden biri olarak gösterilemez?","Çevre bilincinin aile eğitimleri ile oluşmasını beklemek",["Okul öncesi gruba etkinlikler düzenlemek","İlkokul düzeyindeki öğrencilere çevre eğitimi ile ilgili oyunlar oynatmak","Çevre bilincinin aile eğitimleri ile oluşmasını beklemek","Ortaöğretim düzeyi öğrencilerine seminerler vermek","Yaş grubuna göre sorumluluklar yüklemek"]),
      Question("cevreiklim_ques_Q7","I-Okul öncesi\nII-İlköğretim\nIII-Ortaöğretim", "Yukarıdakilerden hangisi veya hangileri çevre eğitimi verilebilecek yaş grupları arasında sayılabilir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
      Question("cevreiklim_ques_Q8","", "Çevre eğitimlerin başlayabileceği en erken yaş düzeyi aşağıdakilerden hangisinde doğru olarak verilmiştir?","Okul öncesi",["Okul öncesi","İlköğretim","Ortaokul","Ortaöğretim","Yükseköğretim"]),
      Question("cevreiklim_ques_Q9","", "Doğal çevreye dikkat ederek, saygı duyarak ve olumlu tutum ve davranışlar geliştirerek faydalı davranışlarda bulunmaya aşağıdakilerden hangisi denir?","Çevre bilinci",["Çevre bilgisi","Çevre eğitimi","Çevre düzeni","Çevre bilinci","Çevresel farkındalık"]),
      Question("cevreiklim_ques_Q10","", "Aşağıdakilerden hangisi çevre bilincine sahip bireylerde görülmesi gereken davranışlardan biridir?","Çevreye uyum sağlamak",["Çevreyi etkileyen olaylara kayıtsız kalmak","Çevre ile etkileşimini azaltmak","Çevreye uyum sağlamak","Çevreyi etkileyecek durumlarda çekimser duruş sergilemek","Çevre bilincini oluşturacak etkinliklerden uzak durmak"]),

    ]),
    TestListHomepageModel("Çevre İklim-Test 2 (Yeni)",[
      Question("cevreiklim_ques_Q11","5. sınıf kademesinde sınıfı olan Semra öğretmen, sınıfına çevre bilinci konusunda faydalı bilgiler vermek istemiş ancak yapacağı etkinlikler konusunda kararsız kalmıştır.", "Aşağıdakilerden hangisi Semra öğretmene verilebilecek tavsiyelerden biri olamaz?","Öğrencilerine eğitimlerini ailelerinin tamamlamasını bildirmeli",["Öğrencilerinin çevre ile etkileşimlerini arttırmalı","Öğrencilerine eğitimlerini ailelerinin tamamlamasını bildirmeli","Görsel materyaller ile anlatımlarını desteklemeli","Farkındalık oluşturacak etkinlikler düzenleyerek öğrencilerine görevler vermeli","Küçük yarışmalar düzenleyerek ödüllendirmeler yapmalı"]),
      Question("cevreiklim_ques_Q12","I-Çevre analizi\nII-Çevreyi tanıma\nIII-Nüfus hareketliliği", "Okul öncesi eğitim kademesinde öğrencilerin yukarıdaki sorumluluklardan hangisine sahip olmaları beklenir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
      Question("cevreiklim_ques_Q13","", "Aşağıdakilerden hangisi ortaokul kademesindeki öğrencilerin çevre ile ilgili yapması beklenen davranışlardan biri değildir?","Bilimsel araştırmalar yapma",["Bilimsel araştırmalar yapma","Çevresel konularda sentez düzeyinde tutum geliştirme","Çevre ile ilgili analizler gerçekleştirme","Çevre bilgisini tamamlamış olma","Çevrede olup bitenleri kavrama"]),
      Question("cevreiklim_ques_Q14","", "Aşağıdakilerden hangisi doğal dengelerin bozulması ile ilgili değildir?","Yanardağ hareketliliğinin artması",["Asit yağmurlarının yağması","Yanardağ hareketliliğinin artması","Hava kirliliğinin artması","Topraktaki zararlıların artması","Karbon salınımının artması"]),
      Question("cevreiklim_ques_Q15","", "Hangisi ekolojik ayak izlerinden biri değildir?", "Hava Sahası Ayak İzi", ["Otlak Alanı Ayak İzi","Tarım Arazisi Ayak İzi","Hava Sahası Ayak İzi","Yapılaşmış Alan Ayak İzi","Otlak Alanı Ayak İzi"]),
      Question("cevreiklim_ques_Q16","", "Ekolojik ayak izi bileşenlerini altı başlık atında toplayan uluslararası kuruluş aşağıdakilerden hangisidir?", "Dünya Doğayı Koruma Vakfı", ["Birleşmiş Milletler Çevre Örgütü","Dünya Sağlık Örgütü","Ekonomik İşbirliği ve Kalkınma Örgütü","Dünya Doğayı Koruma Vakfı","Doğa İşbirliği Teşkilatı"]),
      Question("cevreiklim_ques_Q17","", "Yapılaşmış Alan Ayak İzi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Konut, ulaşım ve endüstriye ayrılmış alanlar", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal otlaklar","Ormanlar","Tarım Alanları"]),
      Question("cevreiklim_ques_Q18","", "Otlak alanı ayak İzi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Doğal ve yarı doğal meralar", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal meralar","Ormanlar","Tarım Alanları"]),
      Question("cevreiklim_ques_Q19","", "Tarım arazisi ayak izi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Ekim Dikim Alanları", ["Konut, ulaşım ve endüstriye ayrılmış alanlar","Okyanus ve karasular","Doğal ve yarı doğal meralar","Ormanlar","Ekim Dikim Alanları"]),
      Question("cevreiklim_ques_Q20","", "Karbon ayak izi bileşeni aşağıdaki kavramlardan hangisi ile ilgilidir?", "Sera gazı miktarı", ["Okyanus","Sera gazı miktarı","Doğal otlaklar","Ormanlar","Ekim Dikim Alanları"]),
    ]),TestListHomepageModel("Çevre İklim-Test 3 (Yeni)",[
       Question("cevreiklim_ques_Q21","I-Depremler\nII-Seller\nIII-Volkanik Patlamalar", "Yukarıdaki ifadelerden hangileri çevre kirliliğinin doğal sebepleri arasındadır?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
       Question("cevreiklim_ques_Q22","I-Nüfus Artışı\nII-Fosil Yakıtlar\nIII-Volkanik Patlamalar", "Yukarıdaki ifadelerden hangileri çevre kirliliğinin doğal sebeplerinden değildir?", "I-II", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
       Question("cevreiklim_ques_Q23","", "Çevre kirliliği sebepleri hangi şıkta doğru olarak verilmiştir?", "İnsan Faaliyetleri ve Doğal Sebepler", ["İnsan Faaliyetleri ve Doğal Sebepler","Doğal ve Yapay Sebepler","İnsan Faaliyetleri ve Yapay Sebepler","Varoluşsal ve Evrimsel Sebepler","Devinimsel ve Doğal Sebepler"]),
       Question("cevreiklim_ques_Q24","", "İnsanların ………… üzerindeki yükünü ve sürdürülebilirlik seviyelerini ölçmek için …………………….. yöntemi kullanılır, ifadesinde noktalı yerlere gelmesi gereken ifade aşağıdakilerden hangisidir?", "Ekosistemler-Ekolojik Ayak İzi", ["Ekolojik Ayak İzi-Ekosistemler","Ekosistemler-Kruger21","Doğa-Orman Alanı Ayak İzi","Ekosistemler-Ekolojik Ayak İzi","Dünya-Ayak İzi"]),
       Question("cevreiklim_ques_Q25","I-Plansız Şehirleşme\nII-Hızlı Nüfus Artışı\nIII-Fosil Yakıtların Kullanımı", "Yukarıda verilen ifadelerden hangileri çevre kirliliğinin insan kaynaklı sebeplerindendir?", "Hepsi", ["Yalnız I","II-III","I-III","I-II","Hepsi"]),
       Question("cevreiklim_ques_Q26","I-Seller\nII-Depremler\nIII-Endüstriyel Atıklar", "Yukarıda verilen ifadelerden hangileri çevre kirliliğinin insan kaynaklı sebeplerinden değildir?", "I-II", ["Yalnız I","II-III","I-III","I-II","I-II-III"]),
       Question("cevreiklim_ques_Q27","", "İnsanların ekosistem üzerindeki yükünü hesaplamak için kullanılan yöntem aşağıdakilerden hangisidir?", "Ekolojik Ayak İzi", ["Ekolojik Ayak İzi","Orman Alanı Ayak İzi","Otlak Alanı Ayak İzi","Tarım Arazisi Ayak İzi",""]),
       Question("cevreiklim_ques_Q28","I-Çevre sorunları farkındalığı\nII-Çevre ile İlgili Tutum\nIII-Çevre ile İlgili Davranışlar", "Okullarda verilen ekolojik ayak izi eğitimleri yukarıdaki kavramlardan hangilerini olumlu etkiler?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
       Question("cevreiklim_ques_Q29","I-Azot Döngüsü\nII-Flor Döngüsü\nIII-Fosfor Döngüsü", "Yukarıda verilen madde döngülerinden hangileri doğru olarak verilmiştir?", "I-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
       Question("cevreiklim_ques_Q30","I- Karbon Döngüsü\nII-Oksijen Döngüsü\nIII-Azot Döngüsü", "Yukarıda verilen döngülerden hangilerinin bir bölümü atmosferde gerçekleşir?", "I-II-III", ["Yalnız I","I-II","I-III","II-III","I-II-III"]),
    ]),


    TestListHomepageModel("Hazırlanıyor",[
      Question("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", ["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"])
    ]),
  ];
     // Question("cevreiklim_ques_Q31","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q32","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q33","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q34","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q35","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q36","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q37","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q38","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q39","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q40","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q41","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q42","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q43","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q44","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q45","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q46","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q47","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q48","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q49","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q50","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q51","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q52","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q53","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q54","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q55","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q56","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q57","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q58","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q59","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q60","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q61","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q62","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q63","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q64","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q65","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q66","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q67","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q68","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q69","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q70","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q71","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q72","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q73","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q74","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q75","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q76","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q77","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q78","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q79","", "", "", ["","","","",""]),
   // Question("cevreiklim_ques_Q8","", "", "", ["","","","",""]),

  List<TestListHomepageModel> get cevreIklim=>_cevreIklimList;
}