import 'package:flutter/material.dart';

import '../../model/question.dart';

class DijitalYetkinlikQuesViewModel extends ChangeNotifier{
  ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
  List<Question> _dijitalYetkinlikList=[
    Question("dijitalyetkinlik_ques_Q1","", "Bilgi, beceri ve tutumların gerekli tüm davranışlar ile birlikte kullanılabilmesine aşağıdakilerden hangisi denir?","Yetkinlik",["Kazanım","Alışkanlık","Yetkinlik","Strateji","Erişilebilirlik"]),
    Question("dijitalyetkinlik_ques_Q2","I-Beceri\nII-Öğrenme\nIII-Davranış","Yukarıdakilerden hangisi veya hangileri dijital yetkinliğin temel unsurlarındandır?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    Question("dijitalyetkinlik_ques_Q3","I-Beceri gerektirir\nII-Bilgi gerektirir\nIII-Sonradan kazanılamaz", "Yukarıdakilerden hangisi veya hangileri Dijital Yetkinlik kapsamında düşünüldüğünde doğrudur?","I-II", ["Yalnız I","Yalnız II","Yalnız III","I-II","I-II-III"]),
    Question("dijitalyetkinlik_ques_Q4","", "Soyut olarak sanal ortamlarda varolan tüm doküman ve belgeler aşağıdaki terimlerden hangisi ile ifade edilir?","Dijital",["Donanım","Dijital","Teknoloji","Ağ","Sanallaştırma"]),
    Question("dijitalyetkinlik_ques_Q5","", "Bilginin araştırılma, ulaşılma ve elde edilen bilgi ile fikir yürütebilme süreçlerinde dijital cihazların kullanılması sürecine aşağıdakilerden hangisi denir?","Dijital Yetkinlik",["Dijital Yetkinlik","Dijital Sorgulama","Dijital Arama","Dijital Kullanım","Dijital Fayda"]),
    Question("dijitalyetkinlik_ques_Q6","Öğrencilerine hayatta karşılaşabilecekleri sorunlarla baş edebilme kabiliyeti kazandırmaya çalışan Bahar Öğretmen, onların sanal ortamda bilgiyi araştırma, bilgiye ulaşabilme ve ulaştıkları bilgiler ile fikir yürütebilme kaabiliyetlerini geliştirmeyi amaçlamaktadır.", "Bahar Öğretmen bu kapsamda, öğrencilerinin aşağıdaki özelliklerinden hangisini geliştirmeyi hedeflemektedir?","Dijital Yetkinlik",["Dijital Okuryazarlık","Teknolojik Üretim","Üretim ve Denetim","Dijital Yetkinlik","Yaşamsal Olgunluk"]),
    Question("dijitalyetkinlik_ques_Q7","I-Eğitim \nII-Sosyal Medya\nIII-Eğlence ", "Dijital yetkinlik yukarıdaki alanlardan hangisi veya hangilerini kapsamaktadır?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    Question("dijitalyetkinlik_ques_Q8","", "Aşağıdakilerden hangisi dijital yetkinlik kapsamında sahip olunması gereken özelliklerden değildir?","Bildiği teknolojinin dışına asla çıkmaz",["Doğru bilgiye ulaşır","Sanal ortamda bilgi üretebilir","Bildiği teknolojinin dışına asla çıkmaz","Gerçek dünya ile sanal dünyayı ayırt edebilir","Bilgilerini yeni öğrenmeler ile birleştirebilir"]),
    Question("dijitalyetkinlik_ques_Q9","", "Aşağıdakilerden hangisi dijital yetkinlik kapsamında sahip olunması gereken özelliklerdendir?","Varolan bilgilerini yeni öğrenmelerinde kullanarak sentez yapar",["Yeni öğrenmelere karşı mesafelidir","Bilginin üretilmesi sürecinde pasiftir","Gerçek dünyadaki tecrübelerini sanal dünyaya taşımaz","Dijital ilkelere göre değil kendi tasarruflarına göre hareket eder","Varolan bilgilerini yeni öğrenmelerinde kullanarak sentez yapar"]),
    Question("dijitalyetkinlik_ques_Q10","Öğrencilerin araştırma ödevlerini yaparken zorlandıklarını fark eden Kazım öğretmen, öğrencilerinin bu alanda teknolojiyi doğru kullanamadıklarını farketmiştir.", "Öğrencilerine doğru teknoloji kullanımını öğretmek isteyen Kazım öğretmenin, aşağıdaki yeterliliklerden hangisini öğrencilerine kazandırması gerekmektedir?","Dijital Yetkinlik",["Dijital Yetkinlik","Ödev Sorumluluğu","Araştırma Becerileri","Farkındalık Eğitimi","Sosyal Sorumluluk"]),
    Question("dijitalyetkinlik_ques_Q11","I-Beceri\nII-Tutum\nIII-Bilgi", "Yukarıdakilerden hangisi veya hangileri dijital yetkinliğin temel unsurları arasında yer alır?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
   // Question("dijitalyetkinlik_ques_Q12","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q13","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q14","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q15","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q16","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q17","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q18","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q19","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q20","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q21","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q22","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q23","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q24","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q25","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q26","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q27","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q28","", "","",["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q29","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q30","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q31","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q32","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q33","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q34","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q35","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q36","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q37","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q38","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q39","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q40","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q41","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q42","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q43","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q44","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q45","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q46","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q47","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q48","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q49","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q50","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q51","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q52","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q53","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q54","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q55","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q56","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q57","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q58","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q59","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q60","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q61","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q62","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q63","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q64","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q65","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q66","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q67","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q68","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q69","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q70","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q71","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q72","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q73","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q74","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q75","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q76","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q77","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q78","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q79","", "", "", ["","","","",""]),
   // Question("dijitalyetkinlik_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get dijitalYetkinlik=>_dijitalYetkinlikList;
}