import 'package:flutter/material.dart';

import '../../model/question.dart';

class EgitimKapsayicilikQuesViewModel extends ChangeNotifier{
  List<Question> _egitimKapsayicilikList=[
    //Question("olcmedeger_ques_11111111","Hazırlanıyor", "Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),

     Question("egitimkapsayicilik_ques_Q1","I-Dışlanma\nII-Eşitsizlik\nIII-Ayrımcılık", "Kapsayıcı eğitim ihtiyacı olan çocukların yaşadığı olumsuz davranışlar hangi şıkta doğru verilmiştir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-II","I-II-III"]),
     Question("egitimkapsayicilik_ques_Q2","", "Aşağıdakilerden hangisinde UNESCO’ya göre kapsayıcı eğitimin odaklandığı temel alanlar doğru verilmiştir?", "Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık", ["Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık","Eğitim Kapsayıcılığı, Eşitlik Kapsayıcılığı, Sistem Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı, Pozitif Ayrımcılık Kapsayıcılığı, Sosyal Kapsayıcılık","Adalet Kapsayıcılığı, Eşitlik Kapsayıcılığı, Eğitim Kapsayıcılığı","Eğitim Kapsayıcılığı, Sosyal Kapsayıcılık, Fırsat Eşitliği Kapsayıcılığı"]),
     Question("egitimkapsayicilik_ques_Q3","", "Kapsayıcı eğitimin gerekçeleri hangi şıkta doğru verilmiştir?", "Sosyal, Ekonomik, Eğitimsel Gerekçe", ["Toplumsal, Bireysel, Ulusal Gerekçe","Sosyal, Ekonomik, Eğitimsel Gerekçe","Bireysel, Eğitimsel, Sosyal Gerekçe","Ekonomik, Toplumsal, Ulusal Gerekçe","Eğitimsel, Sosyal, Bireysel Gerekçe"]),
     Question("egitimkapsayicilik_ques_Q4","", "Aşağıdaki unsurlardan hangisi öğrencilerin okulda ayrımcılığa uğrama sebeplerden birisi değildir?", "Siyasi Görüşleri", ["Siyasi Görüşleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Sosyoekonomik Düzeyleri"]),
     Question("egitimkapsayicilik_ques_Q5","", "Mülteci, göçmen ya da sığınmacı öğrencilerin okulda yaşayabilecekleri ayrımcılığın sebebi aşağıdakilerden hangisidir?", "Etnik Kökenleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Etnik Kökenleri","Cinsiyetleri"]),
     Question("egitimkapsayicilik_ques_Q6","", "Öğrencilerin özel durumundan dolayı olumsuz davranışlara maruz kalmaları aşağıdakilerden hangisi sebebiyledir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Cinsiyetleri"]),
     Question("egitimkapsayicilik_ques_Q7","", "Öğrencinin mezhebi dolayısıyla okulda uğradığı olumsuz davranışların sebebi hangisi olabilir?", "Dini İnançları", ["Etnik Kökenleri","Dini İnançları","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri"]),
     Question("egitimkapsayicilik_ques_Q8","", "Kız öğrencilerin okula gönderilmemeleri ya da okuldan erken yaşta alınmaları, aşağıdakilerden hangisi sebebiyledir?", "Cinsiyetleri", ["Dini İnançları"," Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri","Sosyoekonomik Düzeyleri"]),
     Question("egitimkapsayicilik_ques_Q9","I-İbadetleri\nII-Mezhepleri\nIII- İnançları", "Öğrencilerin yaşadığı yukarıdaki durumlardan hangileri dini inanç kategorisine girer?", "I-II-III", ["I-III","Yalnız II","II-III","I-II","I-II-III"]),
     Question("egitimkapsayicilik_ques_Q10","", "Aile yapısı sebebiyle ayrımcılığa uğrayan öğrencinin durumu aşağıdakilerden hangisi sebebiyledir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Cinsiyetleri"]),
     Question("egitimkapsayicilik_ques_Q11","", "Eğitim sistemlerinin, okulların, öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duymaları hangi tür kapsayıcılığa girer?", "Sistem Kapsayıcılığı", ["Toplumsal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Pozitif Kapsayıcılık"]),
     Question("egitimkapsayicilik_ques_Q12","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması hangi tür kapsayıcılığa girer?", "Eğitime Erişim Kapsayıcılığı", ["Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
     Question("egitimkapsayicilik_ques_Q13","", "Tüm paydaşların beklentilerini kapsayacak şekilde eğitim süreçlerinin geliştirilmesi hangi tür kapsayıcılığa girer?", "Sosyal Kapsayıcılık", ["Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
     Question("egitimkapsayicilik_ques_Q14","", "Öğrencilerin öğrenme potansiyellerini, bireysel özellik ve ihtiyaçlarına hitap eden eğitim programları ile geliştirmek kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Eğitimsel Gerekçe", ["Bireysel Gerekçe","Sosyal Gerekçe","Toplumsal Gerekçe","Eğitimsel Gerekçe","Ekonomik Gerekçe"]),
     Question("egitimkapsayicilik_ques_Q15","", "Öğrencilerin adaletli ve fırsat eşitsizliklerinden arınmış bir ortamda eğitim görmesi kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Sosyal Gerekçe", ["Eğitimsel Gerekçe","Sosyal Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe","Ekonomik Gerekçe"]),
     Question("egitimkapsayicilik_ques_Q16","", "Öğrencilerin bir çatı altında eğitim görmesi farklı türde okullara olan ihtiyacı azaltacaktır. Bu ifade kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Ekonomik Gerekçe", ["Ekonomik Gerekçe","Sosyal Gerekçe","Eğitimsel Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe"]),
     Question("egitimkapsayicilik_ques_Q17","I-Eğitimde adalet ve fırsat eşitliği sağlanmalıdır.\nII-Eğitim sürecine aile ve toplumun katılımı sağlanmalıdır.\nIII-Öğrencilerin istihdamı için altyapı hazırlanmalıdır.", "Yukarıda verilen kapsayıcı eğitimin temel ilkelerinden hangileri doğrudur?", "I-II-III", ["I-III","II-III","Yalnız III","I-II","I-II-III"]),
     Question("egitimkapsayicilik_ques_Q18","", "Okulda ayrımcılığa uğrayan çocuklarda aşağıdaki davranışlardan hangisi görülmez?", "Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.", ["Okulu sevmediğini söyler.","Eve geldiği zaman huysuz, aksi ve yorgundur.","Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.","Okul ile ilgili hiçbir şey yapmak istemez.","Okul ile ilgili heyecan verici ya da mutlu olduğu durumları anlatmayı bırakır."]),
     Question("egitimkapsayicilik_ques_Q19","I-Tüm çocukların fırsat eşitliği elde etmesi\nII-Öğrencilerin okula ilgilerinin ve derslere katılımlarının artması\nIII- Öğrencilerin okul ve toplum yaşamlarının ilişkilendirilmesi ve bütünleştirmesi", "Yukarıdaki ifadelerden hangileri kapsayıcı eğitim faydaları kapsamında değerlendirilebilir?", "I-II-III", ["Yalnız I","II-III","I-III","I-II","I-II-III"]),
     Question("egitimkapsayicilik_ques_Q20","", "Öğrenme güçlüğü çeken çocukların okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Dini İnançları","Cinsiyetleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Sosyo-ekonomik Düzeyleri"]),
    Question("egitimkapsayicilik_ques_Q21","", "Yüksek gelir düzeyine sahip ailelerin çocuklarının okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Etnik Kökenleri","Dini İnançları","Cinsiyetleri"]),
    Question("egitimkapsayicilik_ques_Q22","", "Kapsayıcı eğitim konusunda yoğun çalışmaları bulunan uluslararası kuruluşlar hangisinde doğru olarak verilmiştir?", "UNICEF - UNESCO", ["WHO - ILO","UNESCO - OECD","UNICEF - UNESCO","UNICEF - G20"," WHO-OECD"]),
    Question("egitimkapsayicilik_ques_Q23","", "Kapsayıcı eğitim, tüm çocukların aynı okulda birlikte öğrenmeleridir şeklinde kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNICEF", ["OECD","WHO","G20","UNICEF","UNESCO"]),
    Question("egitimkapsayicilik_ques_Q24","", "Öğrencilerin farklı ihtiyaçlarına, onların eğitime, kültüre ve sosyal hayata katılımlarını arttırarak ve ayrımcılığı en aza indirerek cevap verme süreci olarak kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNESCO", ["OECD","UNESCO","G20","UNICEF","WHO"]),
    Question("egitimkapsayicilik_ques_Q25","", "Yabancı uyruklu farklı dine mensup bir öğrencinin okulda yaşayabileceği ayrımcılık sebepleri hangisinde doğru olarak verilmiştir?", "Etnik Kökenleri - Dini İnançları", ["Sosyoekonomik Düzeyleri – Dini İnançları","Dini İnançları – Fiziksel Yetersizlikleri","Özel Gereksinimleri - Dini İnançları","Etnik Kökenleri – Sosyoekonomik Durumları","Etnik Kökenleri - Dini İnançları"]),
   // Question("egitimkapsayicilik_ques_Q26","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q27","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q28","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q29","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q30","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q31","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q32","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q33","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q34","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q35","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q36","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q37","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q38","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q39","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q40","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q41","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q42","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q43","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q44","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q45","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q46","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q47","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q48","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q49","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q50","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q51","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q52","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q53","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q54","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q55","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q56","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q57","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q58","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q59","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q60","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q61","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q62","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q63","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q64","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q65","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q66","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q67","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q68","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q69","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q70","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q71","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q72","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q73","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q74","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q75","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q76","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q77","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q78","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q79","", "", "", ["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get egitimKapsayicilik=>_egitimKapsayicilikList;
}