import 'package:flutter/material.dart';
import 'package:uzman_ogretmen/model/info_card_item.dart';

import '../../model/question.dart';
import '../../model/test_list_homepage_model.dart';

class EgitimKapsayicilikQuesViewModel extends ChangeNotifier{
  List<TestListHomepageModel> _egitimKapsayicilikList=[
    TestListHomepageModel("Eğitimde Kapsayıcılık-Karışık Test Çöz",[
      Question("egitimkapsayicilik_ques_Q1","I-Dışlanma\nII-Eşitsizlik\nIII-Ayrımcılık", "Kapsayıcı eğitim ihtiyacı olan çocukların yaşadığı olumsuz davranışlar hangi şıkta doğru verilmiştir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q2","", "Aşağıdakilerden hangisinde UNESCO’ya göre kapsayıcı eğitimin odaklandığı temel alanlar doğru verilmiştir?", "Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık", ["Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık","Eğitim Kapsayıcılığı, Eşitlik Kapsayıcılığı, Sistem Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı, Pozitif Ayrımcılık Kapsayıcılığı, Sosyal Kapsayıcılık","Adalet Kapsayıcılığı, Eşitlik Kapsayıcılığı, Eğitim Kapsayıcılığı","Eğitim Kapsayıcılığı, Sosyal Kapsayıcılık, Fırsat Eşitliği Kapsayıcılığı"]),
      Question("egitimkapsayicilik_ques_Q3","", "Kapsayıcı eğitimin gerekçeleri hangi şıkta doğru verilmiştir?", "Sosyal, Ekonomik, Eğitimsel Gerekçe", ["Toplumsal, Bireysel, Ulusal Gerekçe","Sosyal, Ekonomik, Eğitimsel Gerekçe","Bireysel, Eğitimsel, Sosyal Gerekçe","Ekonomik, Toplumsal, Ulusal Gerekçe","Eğitimsel, Sosyal, Bireysel Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q4","", "Aşağıdaki unsurlardan hangisi öğrencilerin okulda ayrımcılığa uğrama sebeplerden birisi değildir?", "Siyasi Görüşleri", ["Siyasi Görüşleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Sosyoekonomik Düzeyleri"]),
      Question("egitimkapsayicilik_ques_Q5","", "Mülteci, göçmen ya da sığınmacı öğrencilerin okulda yaşayabilecekleri ayrımcılığın sebebi aşağıdakilerden hangisidir?", "Etnik Kökenleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Etnik Kökenleri","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q6","", "Öğrencilerin özel durumundan dolayı olumsuz davranışlara maruz kalmaları aşağıdakilerden hangisi sebebiyledir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q7","", "Öğrencinin mezhebi dolayısıyla okulda uğradığı olumsuz davranışların sebebi hangisi olabilir?", "Dini İnançları", ["Etnik Kökenleri","Dini İnançları","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q8","", "Kız öğrencilerin okula gönderilmemeleri ya da okuldan erken yaşta alınmaları, aşağıdakilerden hangisi sebebiyledir?", "Cinsiyetleri", ["Dini İnançları"," Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri","Sosyoekonomik Düzeyleri"]),
      Question("egitimkapsayicilik_ques_Q9","I-İbadetleri\nII-Mezhepleri\nIII- İnançları", "Öğrencilerin yaşadığı yukarıdaki durumlardan hangileri dini inanç kategorisine girer?", "I-II-III", ["I-III","Yalnız II","II-III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q10","", "Aile yapısı sebebiyle ayrımcılığa uğrayan öğrencinin durumu aşağıdakilerden hangisi sebebiyledir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q11","", "Eğitim sistemlerinin, okulların, öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duymaları hangi tür kapsayıcılığa girer?", "Sistem Kapsayıcılığı", ["Toplumsal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Pozitif Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q12","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması hangi tür kapsayıcılığa girer?", "Eğitime Erişim Kapsayıcılığı", ["Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q13","", "Tüm paydaşların beklentilerini kapsayacak şekilde eğitim süreçlerinin geliştirilmesi hangi tür kapsayıcılığa girer?", "Sosyal Kapsayıcılık", ["Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q14","", "Öğrencilerin öğrenme potansiyellerini, bireysel özellik ve ihtiyaçlarına hitap eden eğitim programları ile geliştirmek kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Eğitimsel Gerekçe", ["Bireysel Gerekçe","Sosyal Gerekçe","Toplumsal Gerekçe","Eğitimsel Gerekçe","Ekonomik Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q15","", "Öğrencilerin adaletli ve fırsat eşitsizliklerinden arınmış bir ortamda eğitim görmesi kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Sosyal Gerekçe", ["Eğitimsel Gerekçe","Sosyal Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe","Ekonomik Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q16","", "Öğrencilerin bir çatı altında eğitim görmesi farklı türde okullara olan ihtiyacı azaltacaktır. Bu ifade kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Ekonomik Gerekçe", ["Ekonomik Gerekçe","Sosyal Gerekçe","Eğitimsel Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q17","I-Eğitimde adalet ve fırsat eşitliği sağlanmalıdır.\nII-Eğitim sürecine aile ve toplumun katılımı sağlanmalıdır.\nIII-Öğrencilerin istihdamı için altyapı hazırlanmalıdır.", "Yukarıda verilen kapsayıcı eğitimin temel ilkelerinden hangileri doğrudur?", "I-II-III", ["I-III","II-III","Yalnız III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q18","", "Okulda ayrımcılığa uğrayan çocuklarda aşağıdaki davranışlardan hangisi görülmez?", "Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.", ["Okulu sevmediğini söyler.","Eve geldiği zaman huysuz, aksi ve yorgundur.","Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.","Okul ile ilgili hiçbir şey yapmak istemez.","Okul ile ilgili heyecan verici ya da mutlu olduğu durumları anlatmayı bırakır."]),
      Question("egitimkapsayicilik_ques_Q19","I-Tüm çocukların fırsat eşitliği elde etmesi\nII-Öğrencilerin okula ilgilerinin ve derslere katılımlarının artması\nIII- Öğrencilerin okul ve toplum yaşamlarının ilişkilendirilmesi ve bütünleştirmesi", "Yukarıdaki ifadelerden hangileri kapsayıcı eğitim faydaları kapsamında değerlendirilebilir?", "I-II-III", ["Yalnız I","II-III","I-III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q20","", "Öğrenme güçlüğü çeken çocukların okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Dini İnançları","Cinsiyetleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Sosyo-ekonomik Düzeyleri"]),
      Question("egitimkapsayicilik_ques_Q21","", "Yüksek gelir düzeyine sahip ailelerin çocuklarının okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Etnik Kökenleri","Dini İnançları","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q22","", "Kapsayıcı eğitim konusunda yoğun çalışmaları bulunan uluslararası kuruluşlar hangisinde doğru olarak verilmiştir?", "UNICEF - UNESCO", ["WHO - ILO","UNESCO - OECD","UNICEF - UNESCO","UNICEF - G20"," WHO-OECD"]),
      Question("egitimkapsayicilik_ques_Q23","", "Kapsayıcı eğitim, tüm çocukların aynı okulda birlikte öğrenmeleridir şeklinde kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNICEF", ["OECD","WHO","G20","UNICEF","UNESCO"]),
      Question("egitimkapsayicilik_ques_Q24","", "Öğrencilerin farklı ihtiyaçlarına, onların eğitime, kültüre ve sosyal hayata katılımlarını arttırarak ve ayrımcılığı en aza indirerek cevap verme süreci olarak kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNESCO", ["OECD","UNESCO","G20","UNICEF","WHO"]),
      Question("egitimkapsayicilik_ques_Q25","", "Yabancı uyruklu farklı dine mensup bir öğrencinin okulda yaşayabileceği ayrımcılık sebepleri hangisinde doğru olarak verilmiştir?", "Etnik Kökenleri - Dini İnançları", ["Sosyoekonomik Düzeyleri – Dini İnançları","Dini İnançları – Fiziksel Yetersizlikleri","Özel Gereksinimleri - Dini İnançları","Etnik Kökenleri – Sosyoekonomik Durumları","Etnik Kökenleri - Dini İnançları"]),
      // Question("egitimkapsayicilik_ques_Q26","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q27","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q28","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q29","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q30","", "","",["","","","",""]),

      ///Çözümlü sorular
      Question("egitimkapsayicilik_ques_Q31","I-Ayrımcılık\nII-Görmezden gelme\nIII-Eşitsizlik", "Yukarıdakilerden hangisi veya hangileri eğitim süreci içerisinde görülen olumsuz davranışlardan birisidir?","I-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
      Question("egitimkapsayicilik_ques_Q32","", "UNICEF’e göre, kapsayıcı eğitim kavramının karşılığı aşağıdakilerden  hangisidir?","Tüm çocukların aynı okulda birlikte öğrenmesi",["Özel eğitime muhtaç öğrencilerin ayrı ortamda ders işlemesi","Özel yetenekli öğrencilerin kendi kendilerine öğrenmesi","Kız çocuklarının kendi gruplarıyla eğitim alması","Yaşamın belli döneminde özel öğrencinin okulsuz eğitimi","Tüm çocukların aynı okulda birlikte öğrenmesi"], answSolve:InfoCardItem("ee_egitimkapsayici_info_2", "Tanım-2", "-UNICEF’e göre kapsayıcı eğitim ise tüm çocukların aynı okulda birlikte öğrenmeleridir."), ),
      Question("egitimkapsayicilik_ques_Q33","", "Aşağıdaki ifadelerden hangisi kapsayıcı eğitim anlayışı ile ilgili yanlış bir ifadedir?","Aynılaşmayı destekler",["Ayrımcılığı yok sayar","Aynılaşmayı destekler","Eşitliği savunur","Farklılıklara saygı duyar","Sosyal adaleti destekler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."),),
      Question("egitimkapsayicilik_ques_Q34","I-Toplumsallık,\nII-Aynılaşma\nIII-Sosyal Adalet", "Yukarıdakilerden hangisi veya hangileri kapsayıcı eğitim tarafından desteklenmektedir?","I-III", ["Yalnız I","Yalnız II","I-III","II-III","I-II-III"],answSolve:InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."), ),
      Question("egitimkapsayicilik_ques_Q35","Kapsayıcı eğitim, planlı bir eğitim sürecidir.", "Aşağıdakilerden hangisi kapsayıcı eğitim sürecinin niteliğini arttıran faktörlerden biri değildir?","Sonuç odaklı yaklaşım sergilenmesi",["Sonuç odaklı yaklaşım sergilenmesi","İhtiyaçların analiz edilmesi","Kişisel özelliklerin belirlenmesi","Tercihlerin tespiti","Gereksinimlerin karşılanması"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4", "Tanım-4", "Kapsayıcı eğitim; öğrencilerin gereksinim, ihtiyaç, tercih ve kişisel özellikleri analiz edilerek hazırlanmış planlı bir eğitim sürecidir. Böylece eğitim sürecinin niteliği ve öğrencilerin derse katılım ve ilgileri artar."),),
      Question("egitimkapsayicilik_ques_Q36","", "Aşağıdaki seçeneklerden hangisinde kapsayıcı eğitim ortamına sahip okul özelliği doğru olarak verilmiştir?","Tüm öğrencilerin koşulsuz kabulünü destekler",["Eğitim ihtiyaçlarının okul dışında karşılanmasını savunur","Toplumsal farklılıkları azaltma amacındadır","Tüm öğrencilerin koşulsuz kabulünü destekler","Akademik başarı için öğrencilerin sosyal hayattaki varlıklarını azaltır","Koruyucu anlayışı ile fiziksel engelli bireylerin eğitimlerini erteler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_11", "Tanım-5", "-Kapsayıcı eğitim ortamına sahip okullar tüm öğrencilerin koşulsuz bir şekilde kabul edilmesini ve eğitim ihtiyaçlarının okulda karşılanması gerektiğini savunurlar."),),
      Question("egitimkapsayicilik_ques_Q37","I-Eşitlik\nII-Ayrımcılık\nIII-Öğrencinin koşulsuz kabulü", "Yukarıdakilerden hangisi veya hangileri eğitim sürecini olumsuz olarak etkileyen davranışlardan biridir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
      Question("egitimkapsayicilik_ques_Q38","Kapsayıcı eğitim, dışlanmayı ve ayrımcılığı yok ederek herkese eşit eğitim anlayışını destekler.", "Aşağıdaki uygulamalardan hangisi bu görüş ile çelişmektedir?","Koruyucu ailedeki çocukların özel sınıflarda eğitimi",["Kız çocuklarının okullaşmasının arttırılması","Gelir düzeyi farklılıklarının yok sayılması","Mülteci öğrencilerin devlet okullarına kabulü","Özel eğitime muhtaç öğrencilerin sınıfla kaynaştırılması","Koruyucu ailedeki çocukların özel sınıflarda eğitimi"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışını destekler.\n-Bu anlayışa göre, koruyucu ailedeki çocukların özel sınıflarda eğitimi değil okullarda kaynaştırılması hedeflenmelidir."),),
      Question("egitimkapsayicilik_ques_Q39","", "Aşağıdakilerden hangisi kapsayıcı eğitimin özellikle üzerinde durduğu öğrenci profilleri arasında yer almaz?","Gelir düzeyi yüksek ailelerin çocukları",["Kültürel geçmişleri farklı olan bireyler","Kırsal bölgede yaşayan çocuklar","Gelir düzeyi yüksek ailelerin çocukları","Kız çocukları","Mülteci çocukları"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13", "Tanım-8", "-Kültürel geçmişleri farklı olan bireyler, kırsal bölgede yaşayan çocuklar, kız çocukları, göçmen ve mülteci çocuklar gibi birçok grubun eğitim hakkı, kapsayıcı eğitim bünyesinde yer alır.\n-Farklı grupların, eğitimde fırsat eşitliği kapsamında aynı eğitimi görmeleri mümkün kılınmalıdır."),),
      Question("egitimkapsayicilik_ques_Q40","I-Farklılıklar değerlidir\nII-Sosyal statü önemlidir\nIII-Öğrenciler aynılaştırılmalıdır", "Kapsayıcı eğitimin tanımı düşünüldüğünde, yukarıdakilerden hangisi veya hangileri doğrudur?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12", "Tanım-7", "-Kapsayıcı eğitim, bireysel farklılıklara odaklanır ve farklılıklar değerlidir.\n-Sosyal statü, kapsayıcı eğitimin ilgi alanında değildir.\n-Öğrencilerin aynılaştırılması değil farklılıklarının kabulü esastır."),),
      Question("egitimkapsayicilik_ques_Q41","", "Aşağıdakilerden hangisi eğitimde kapsayıcılığın temel unsurlarından biri değildir?","Korumacılık",["Entegrasyon","Kapsayıcılık","Dışlanma","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q42","I-Ayrımcılık\nII-Dışlanma\nIII-Kapsayıcılık", "Yukarıdakilerden hangisi veya hangileri eğitimde kapsayıcılığın temel unsurlarındandır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q43","", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri aşağıdakilerden hangisi ile ilgilidir?","Entegrasyon",["Korumacılık","Dışlanma","Entegrasyon","Ayrımcılık","Kapsayıcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
      Question("egitimkapsayicilik_ques_Q44","Mülteci bir öğrencisinin ailesi ile görüşen okul müdürü, öğrencilerinin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri gerektiğini ifade etmiştir.", "Buna göre, okul müdürünün ifadesi kapsayıcı eğitimin temel unsurlarından hangisi ile ilgilidir?","Entegrasyon",["Entegrasyon","Ayrımcılık","Kapsayıcılık","Dışlanma","Koşulluluk"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
      Question("egitimkapsayicilik_ques_Q45","Kapsayıcı eğitim, öğrencilerin fiziki yetersizlik, sosyo-ekonomik durum, din, ırk vs. sebeplerle eğitim alma haklarının kesintiye uğratılmasının karşısındadır.", "Yukarıdaki ifade aşağıdaki verilen kapsayıcılığın temel unsurlarından hangisi ile ilgilidir?","Dışlanma",["Kapsayıcılık","Dışlanma","Ayrımcılık","Entegrasyon","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q46","Necmettin öğretmen'in yürüme engelli öğrencisi okula devam etmemektedir. Necmettin Öğretmen, öğrencisinin okula devam süreci ile ilgili çok büyük çaba sarf etmiştir.", "Buna göre, Necmettin Öğretmen'in sarf ettiği çaba kapsayıcılık ile ilgili kavramlardan hangisini ortadan kaldırmaya yöneliktir?","Dışlanma",["Kapsayıcılık","Entegrasyon","Ayrımcılık","Dışlanma","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q47","", "Dezavantajlı öğrencilerin akranlarından farklı bir sınıfta öğrenim görmeleri aşağıdaki kavramlardan hangisi ile ilgilidir?","Ayrımcılık",["Dışlanma","Kapsayıcılık","Entegrasyon","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_15","Ayrımcılık", "-Dezavantajlı öğrencilerin kendilerine özel hazırlanmış sınıflarda eğitim görmeleri durumudur.\n-Bu ortam farklı bir kurum olabileceği gibi, aynı okulda farklı bir sınıfta olabilir.\n-Akranları ile birlikte değillerdir, ayrıştırılmışlardır."),),
      Question("egitimkapsayicilik_ques_Q48","", "Tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunma amacını ifade eden kapsayıcılık kavramı aşağıdakilerden hangisidir?","Kapsayıcılık",["Ayrımcılık","Dışlanma","Kapsayıcılık","Entegrasyon","Eşitlik"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
      Question("egitimkapsayicilik_ques_Q49","", "Dezavantajlı öğrencilerin, fırsat eşitliği kapsamında eğitim haklarından faydalanmarı için reformist yapı ile gerekli düzenlemelerin yapılması aşağıdaki kavramlardan hangisi ile ilgilidir?","Kapsayıcılık",["Kapsayıcılık","Eşitlik","Entegrasyon","Dışlanma","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q50","Öğretmenler Kurulunda söz hakkı isteyen Pınar Öğretmen, okuldaki göçmen öğrencilerin eğitim-öğretim sürecine katılımlarını sağlamak için öğretim stratejilerinde bazı değişiklikler yapılması gerektiğini ifade etmiştir.", "Pınar öğretmen Öğretmenler Kurulu'nda aşağıdaki kavramlardan hangisinin açıklamasını yapmıştır? ","Kapsayıcılık",["Eğitim Reformu","Ayrımcılık","Kapsayıcılık","Dışlanma","Entegrasyon"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır.\n-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
      Question("egitimkapsayicilik_ques_Q51","", "Aşağıdakilerden hangisi UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlardan biridir?","Sistem Kapsayıcılığı",["Hizmet Kapsayıcılığı","Yenilik Kapsayıcılığı","Öğretim Kapsayıcılığı","Sistem Kapsayıcılığı","Faaliyet Kapsayıcılığı"], answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q52","I-Sosyal Kapsayıcılık\nII-Sistem Kapsayıcılığı\nIII-Eğitime Erişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q53","", "Eğitim sistemlerinin, okulların ve öğretmenlerin bireysel çeşitliliğe saygı duyması kapsayıcı eğitimin odak noktalarından hangisi ile ilgilidir?","Sistem Kapsayıcılığı",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır."),),
      Question("egitimkapsayicilik_ques_Q54","Büşra Öğretmen, okuldaki dezavantajlı bireylerin ihtiyaç ve beklentilerini karşılamak adına eğitim sistemlerinin düzenlenmesi gerektiğini savunmaktadır.", "Buna göre Büşra Öğretmen'in savunduğu fikir, kapsayıcı eğitimin odaklarından hangisidir?","Sistem Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır.\n-Sorunun çözümündeki anahtar durum, sistemin öğrenciye odaklı değiştirilmesidir."),),
      Question("egitimkapsayicilik_ques_Q55","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanan kapsayıcı eğitimin odağı aşağıdakilerden hangisidir?","Eğitime Erişim Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani eğitim almak, isteyen herkes eğitim alsın anlayışı bulunur."),),
      Question("egitimkapsayicilik_ques_Q56","Her birey değerlidir. Bireylerdeki farklılıklar toplumun zenginliği olarak karşımıza çıkar. Eğitim sistemleri, bireysel farklılıkları ve olası dezavantajları içine alan nitelikli eğitim anlayışıyla ulaşılabilir bir eğitim sunmak zorundadır.", "Yukarıdaki paragrafta kapsayıcı eğitimin hangi odağından bahsedilmiştir?","Eğitime Erişim Kapsayıcılığı",["Faaliyet Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani, eğitim almak isteyen herkes eğitim alsın anlayışı bulunur."),),
      Question("egitimkapsayicilik_ques_Q57","", "Toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmaları aşağıdaki tanımlardan hangisi ile ilgilidir?","Sosyal Kapsayıcılık",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q58","Benim hayat felsefem, her zaman toplumu kucaklamak olmuştur. Bu durum, iyi insan olmanın da ön şartıdır. Toplumun her kesimi, içerisinde bulunduğu duruma bakmadan hayatın içinde olmalıdır.", "Yukarıda verilen cümlede 'içerisinde bulunduğu duruma bakmadan hayatın içinde olmak' ifadesinin kapsayıcı eğitimdeki karşılığı aşağıdakilerden hangisidir?","Sosyal Kapsayıcılık",["Faaliyet Kapsayıcılığı","Aktif Kapsayıcılık","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q59","I-Hizmet Kapsayıcılığı\nII-Sosyal Kapsayıcılık\nIII-Gelişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q60","I-Eğitim Erişim Kapsayıcılığı\nII-Koruyucu Kapsayıcılık\nIII-Yöneltme Kapsayıcılığı","Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
    ]),


    TestListHomepageModel("Tanımlar - (ÇÖZÜMLÜ) Test",[
      Question("egitimkapsayicilik_ques_Q31","I-Ayrımcılık\nII-Görmezden gelme\nIII-Eşitsizlik", "Yukarıdakilerden hangisi veya hangileri eğitim süreci içerisinde görülen olumsuz davranışlardan birisidir?","I-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
      Question("egitimkapsayicilik_ques_Q32","", "UNICEF’e göre, kapsayıcı eğitim kavramının karşılığı aşağıdakilerden  hangisidir?","Tüm çocukların aynı okulda birlikte öğrenmesi",["Özel eğitime muhtaç öğrencilerin ayrı ortamda ders işlemesi","Özel yetenekli öğrencilerin kendi kendilerine öğrenmesi","Kız çocuklarının kendi gruplarıyla eğitim alması","Yaşamın belli döneminde özel öğrencinin okulsuz eğitimi","Tüm çocukların aynı okulda birlikte öğrenmesi"], answSolve:InfoCardItem("ee_egitimkapsayici_info_2", "Tanım-2", "-UNICEF’e göre kapsayıcı eğitim ise tüm çocukların aynı okulda birlikte öğrenmeleridir."), ),
      Question("egitimkapsayicilik_ques_Q33","", "Aşağıdaki ifadelerden hangisi kapsayıcı eğitim anlayışı ile ilgili yanlış bir ifadedir?","Aynılaşmayı destekler",["Ayrımcılığı yok sayar","Aynılaşmayı destekler","Eşitliği savunur","Farklılıklara saygı duyar","Sosyal adaleti destekler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."),),
      Question("egitimkapsayicilik_ques_Q34","I-Toplumsallık,\nII-Aynılaşma\nIII-Sosyal Adalet", "Yukarıdakilerden hangisi veya hangileri kapsayıcı eğitim tarafından desteklenmektedir?","I-III", ["Yalnız I","Yalnız II","I-III","II-III","I-II-III"],answSolve:InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."), ),
      Question("egitimkapsayicilik_ques_Q35","Kapsayıcı eğitim, planlı bir eğitim sürecidir.", "Aşağıdakilerden hangisi kapsayıcı eğitim sürecinin niteliğini arttıran faktörlerden biri değildir?","Sonuç odaklı yaklaşım sergilenmesi",["Sonuç odaklı yaklaşım sergilenmesi","İhtiyaçların analiz edilmesi","Kişisel özelliklerin belirlenmesi","Tercihlerin tespiti","Gereksinimlerin karşılanması"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4", "Tanım-4", "Kapsayıcı eğitim; öğrencilerin gereksinim, ihtiyaç, tercih ve kişisel özellikleri analiz edilerek hazırlanmış planlı bir eğitim sürecidir. Böylece eğitim sürecinin niteliği ve öğrencilerin derse katılım ve ilgileri artar."),),
      Question("egitimkapsayicilik_ques_Q36","", "Aşağıdaki seçeneklerden hangisinde kapsayıcı eğitim ortamına sahip okul özelliği doğru olarak verilmiştir?","Tüm öğrencilerin koşulsuz kabulünü destekler",["Eğitim ihtiyaçlarının okul dışında karşılanmasını savunur","Toplumsal farklılıkları azaltma amacındadır","Tüm öğrencilerin koşulsuz kabulünü destekler","Akademik başarı için öğrencilerin sosyal hayattaki varlıklarını azaltır","Koruyucu anlayışı ile fiziksel engelli bireylerin eğitimlerini erteler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_11", "Tanım-5", "-Kapsayıcı eğitim ortamına sahip okullar tüm öğrencilerin koşulsuz bir şekilde kabul edilmesini ve eğitim ihtiyaçlarının okulda karşılanması gerektiğini savunurlar."),),
      Question("egitimkapsayicilik_ques_Q37","I-Eşitlik\nII-Ayrımcılık\nIII-Öğrencinin koşulsuz kabulü", "Yukarıdakilerden hangisi veya hangileri eğitim sürecini olumsuz olarak etkileyen davranışlardan biridir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
      Question("egitimkapsayicilik_ques_Q38","Kapsayıcı eğitim, dışlanmayı ve ayrımcılığı yok ederek herkese eşit eğitim anlayışını destekler.", "Aşağıdaki uygulamalardan hangisi bu görüş ile çelişmektedir?","Koruyucu ailedeki çocukların özel sınıflarda eğitimi",["Kız çocuklarının okullaşmasının arttırılması","Gelir düzeyi farklılıklarının yok sayılması","Mülteci öğrencilerin devlet okullarına kabulü","Özel eğitime muhtaç öğrencilerin sınıfla kaynaştırılması","Koruyucu ailedeki çocukların özel sınıflarda eğitimi"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışını destekler.\n-Bu anlayışa göre, koruyucu ailedeki çocukların özel sınıflarda eğitimi değil okullarda kaynaştırılması hedeflenmelidir."),),
      Question("egitimkapsayicilik_ques_Q39","", "Aşağıdakilerden hangisi kapsayıcı eğitimin özellikle üzerinde durduğu öğrenci profilleri arasında yer almaz?","Gelir düzeyi yüksek ailelerin çocukları",["Kültürel geçmişleri farklı olan bireyler","Kırsal bölgede yaşayan çocuklar","Gelir düzeyi yüksek ailelerin çocukları","Kız çocukları","Mülteci çocukları"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13", "Tanım-8", "-Kültürel geçmişleri farklı olan bireyler, kırsal bölgede yaşayan çocuklar, kız çocukları, göçmen ve mülteci çocuklar gibi birçok grubun eğitim hakkı, kapsayıcı eğitim bünyesinde yer alır.\n-Farklı grupların, eğitimde fırsat eşitliği kapsamında aynı eğitimi görmeleri mümkün kılınmalıdır."),),
      Question("egitimkapsayicilik_ques_Q40","I-Farklılıklar değerlidir\nII-Sosyal statü önemlidir\nIII-Öğrenciler aynılaştırılmalıdır", "Kapsayıcı eğitimin tanımı düşünüldüğünde, yukarıdakilerden hangisi veya hangileri doğrudur?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12", "Tanım-7", "-Kapsayıcı eğitim, bireysel farklılıklara odaklanır ve farklılıklar değerlidir.\n-Sosyal statü, kapsayıcı eğitimin ilgi alanında değildir.\n-Öğrencilerin aynılaştırılması değil farklılıklarının kabulü esastır."),),
    ]),
    TestListHomepageModel("Kapsayıcılık ile İlgili Temel Unsurlar - (ÇÖZÜMLÜ) Test",[
      Question("egitimkapsayicilik_ques_Q41","", "Aşağıdakilerden hangisi eğitimde kapsayıcılığın temel unsurlarından biri değildir?","Korumacılık",["Entegrasyon","Kapsayıcılık","Dışlanma","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q42","I-Ayrımcılık\nII-Dışlanma\nIII-Kapsayıcılık", "Yukarıdakilerden hangisi veya hangileri eğitimde kapsayıcılığın temel unsurlarındandır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q43","", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri aşağıdakilerden hangisi ile ilgilidir?","Entegrasyon",["Korumacılık","Dışlanma","Entegrasyon","Ayrımcılık","Kapsayıcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
      Question("egitimkapsayicilik_ques_Q44","Mülteci bir öğrencisinin ailesi ile görüşen okul müdürü, öğrencilerinin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri gerektiğini ifade etmiştir.", "Buna göre, okul müdürünün ifadesi kapsayıcı eğitimin temel unsurlarından hangisi ile ilgilidir?","Entegrasyon",["Entegrasyon","Ayrımcılık","Kapsayıcılık","Dışlanma","Koşulluluk"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
      Question("egitimkapsayicilik_ques_Q45","Kapsayıcı eğitim, öğrencilerin fiziki yetersizlik, sosyo-ekonomik durum, din, ırk vs. sebeplerle eğitim alma haklarının kesintiye uğratılmasının karşısındadır.", "Yukarıdaki ifade aşağıdaki verilen kapsayıcılığın temel unsurlarından hangisi ile ilgilidir?","Dışlanma",["Kapsayıcılık","Dışlanma","Ayrımcılık","Entegrasyon","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q46","Necmettin öğretmen'in yürüme engelli öğrencisi okula devam etmemektedir. Necmettin Öğretmen, öğrencisinin okula devam süreci ile ilgili çok büyük çaba sarf etmiştir.", "Buna göre, Necmettin Öğretmen'in sarf ettiği çaba kapsayıcılık ile ilgili kavramlardan hangisini ortadan kaldırmaya yöneliktir?","Dışlanma",["Kapsayıcılık","Entegrasyon","Ayrımcılık","Dışlanma","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q47","", "Dezavantajlı öğrencilerin akranlarından farklı bir sınıfta öğrenim görmeleri aşağıdaki kavramlardan hangisi ile ilgilidir?","Ayrımcılık",["Dışlanma","Kapsayıcılık","Entegrasyon","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_15","Ayrımcılık", "-Dezavantajlı öğrencilerin kendilerine özel hazırlanmış sınıflarda eğitim görmeleri durumudur.\n-Bu ortam farklı bir kurum olabileceği gibi, aynı okulda farklı bir sınıfta olabilir.\n-Akranları ile birlikte değillerdir, ayrıştırılmışlardır."),),
      Question("egitimkapsayicilik_ques_Q48","", "Tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunma amacını ifade eden kapsayıcılık kavramı aşağıdakilerden hangisidir?","Kapsayıcılık",["Ayrımcılık","Dışlanma","Kapsayıcılık","Entegrasyon","Eşitlik"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
      Question("egitimkapsayicilik_ques_Q49","", "Dezavantajlı öğrencilerin, fırsat eşitliği kapsamında eğitim haklarından faydalanmarı için reformist yapı ile gerekli düzenlemelerin yapılması aşağıdaki kavramlardan hangisi ile ilgilidir?","Kapsayıcılık",["Kapsayıcılık","Eşitlik","Entegrasyon","Dışlanma","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q50","Öğretmenler Kurulunda söz hakkı isteyen Pınar Öğretmen, okuldaki göçmen öğrencilerin eğitim-öğretim sürecine katılımlarını sağlamak için öğretim stratejilerinde bazı değişiklikler yapılması gerektiğini ifade etmiştir.", "Pınar öğretmen Öğretmenler Kurulu'nda aşağıdaki kavramlardan hangisinin açıklamasını yapmıştır? ","Kapsayıcılık",["Eğitim Reformu","Ayrımcılık","Kapsayıcılık","Dışlanma","Entegrasyon"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır.\n-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
         ]),
    TestListHomepageModel("Kapsayıcı Eğitimin Odakları - (ÇÖZÜMLÜ) Test",[
      Question("egitimkapsayicilik_ques_Q51","", "Aşağıdakilerden hangisi UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlardan biridir?","Sistem Kapsayıcılığı",["Hizmet Kapsayıcılığı","Yenilik Kapsayıcılığı","Öğretim Kapsayıcılığı","Sistem Kapsayıcılığı","Faaliyet Kapsayıcılığı"], answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q52","I-Sosyal Kapsayıcılık\nII-Sistem Kapsayıcılığı\nIII-Eğitime Erişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q53","", "Eğitim sistemlerinin, okulların ve öğretmenlerin bireysel çeşitliliğe saygı duyması kapsayıcı eğitimin odak noktalarından hangisi ile ilgilidir?","Sistem Kapsayıcılığı",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır."),),
      Question("egitimkapsayicilik_ques_Q54","Büşra Öğretmen, okuldaki dezavantajlı bireylerin ihtiyaç ve beklentilerini karşılamak adına eğitim sistemlerinin düzenlenmesi gerektiğini savunmaktadır.", "Buna göre Büşra Öğretmen'in savunduğu fikir, kapsayıcı eğitimin odaklarından hangisidir?","Sistem Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır.\n-Sorunun çözümündeki anahtar durum, sistemin öğrenciye odaklı değiştirilmesidir."),),
      Question("egitimkapsayicilik_ques_Q55","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanan kapsayıcı eğitimin odağı aşağıdakilerden hangisidir?","Eğitime Erişim Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani eğitim almak, isteyen herkes eğitim alsın anlayışı bulunur."),),
      Question("egitimkapsayicilik_ques_Q56","Her birey değerlidir. Bireylerdeki farklılıklar toplumun zenginliği olarak karşımıza çıkar. Eğitim sistemleri, bireysel farklılıkları ve olası dezavantajları içine alan nitelikli eğitim anlayışıyla ulaşılabilir bir eğitim sunmak zorundadır.", "Yukarıdaki paragrafta kapsayıcı eğitimin hangi odağından bahsedilmiştir?","Eğitime Erişim Kapsayıcılığı",["Faaliyet Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani, eğitim almak isteyen herkes eğitim alsın anlayışı bulunur."),),
      Question("egitimkapsayicilik_ques_Q57","", "Toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmaları aşağıdaki tanımlardan hangisi ile ilgilidir?","Sosyal Kapsayıcılık",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q58","Benim hayat felsefem, her zaman toplumu kucaklamak olmuştur. Bu durum, iyi insan olmanın da ön şartıdır. Toplumun her kesimi, içerisinde bulunduğu duruma bakmadan hayatın içinde olmalıdır.", "Yukarıda verilen cümlede 'içerisinde bulunduğu duruma bakmadan hayatın içinde olmak' ifadesinin kapsayıcı eğitimdeki karşılığı aşağıdakilerden hangisidir?","Sosyal Kapsayıcılık",["Faaliyet Kapsayıcılığı","Aktif Kapsayıcılık","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q59","I-Hizmet Kapsayıcılığı\nII-Sosyal Kapsayıcılık\nIII-Gelişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q60","I-Eğitim Erişim Kapsayıcılığı\nII-Koruyucu Kapsayıcılık\nIII-Yöneltme Kapsayıcılığı","Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
    ]),



     TestListHomepageModel("Tanımlar, Temel Unsurlar, Odaklar Pekiştirme Testi - (ÇÖZÜMLÜ) ",[
       Question("egitimkapsayicilik_ques_Q31","I-Ayrımcılık\nII-Görmezden gelme\nIII-Eşitsizlik", "Yukarıdakilerden hangisi veya hangileri eğitim süreci içerisinde görülen olumsuz davranışlardan birisidir?","I-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
       Question("egitimkapsayicilik_ques_Q32","", "UNICEF’e göre, kapsayıcı eğitim kavramının karşılığı aşağıdakilerden  hangisidir?","Tüm çocukların aynı okulda birlikte öğrenmesi",["Özel eğitime muhtaç öğrencilerin ayrı ortamda ders işlemesi","Özel yetenekli öğrencilerin kendi kendilerine öğrenmesi","Kız çocuklarının kendi gruplarıyla eğitim alması","Yaşamın belli döneminde özel öğrencinin okulsuz eğitimi","Tüm çocukların aynı okulda birlikte öğrenmesi"], answSolve:InfoCardItem("ee_egitimkapsayici_info_2", "Tanım-2", "-UNICEF’e göre kapsayıcı eğitim ise tüm çocukların aynı okulda birlikte öğrenmeleridir."), ),
       Question("egitimkapsayicilik_ques_Q33","", "Aşağıdaki ifadelerden hangisi kapsayıcı eğitim anlayışı ile ilgili yanlış bir ifadedir?","Aynılaşmayı destekler",["Ayrımcılığı yok sayar","Aynılaşmayı destekler","Eşitliği savunur","Farklılıklara saygı duyar","Sosyal adaleti destekler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."),),
       Question("egitimkapsayicilik_ques_Q34","I-Toplumsallık,\nII-Aynılaşma\nIII-Sosyal Adalet", "Yukarıdakilerden hangisi veya hangileri kapsayıcı eğitim tarafından desteklenmektedir?","I-III", ["Yalnız I","Yalnız II","I-III","II-III","I-II-III"],answSolve:InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışıdır.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."), ),
       Question("egitimkapsayicilik_ques_Q41","", "Aşağıdakilerden hangisi eğitimde kapsayıcılığın temel unsurlarından biri değildir?","Korumacılık",["Entegrasyon","Kapsayıcılık","Dışlanma","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
       Question("egitimkapsayicilik_ques_Q42","I-Ayrımcılık\nII-Dışlanma\nIII-Kapsayıcılık", "Yukarıdakilerden hangisi veya hangileri eğitimde kapsayıcılığın temel unsurlarındandır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),),
       Question("egitimkapsayicilik_ques_Q43","", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri aşağıdakilerden hangisi ile ilgilidir?","Entegrasyon",["Korumacılık","Dışlanma","Entegrasyon","Ayrımcılık","Kapsayıcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
       Question("egitimkapsayicilik_ques_Q51","", "Aşağıdakilerden hangisi UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlardan biridir?","Sistem Kapsayıcılığı",["Hizmet Kapsayıcılığı","Yenilik Kapsayıcılığı","Öğretim Kapsayıcılığı","Sistem Kapsayıcılığı","Faaliyet Kapsayıcılığı"], answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
       Question("egitimkapsayicilik_ques_Q52","I-Sosyal Kapsayıcılık\nII-Sistem Kapsayıcılığı\nIII-Eğitime Erişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
       Question("egitimkapsayicilik_ques_Q53","", "Eğitim sistemlerinin, okulların ve öğretmenlerin bireysel çeşitliliğe saygı duyması kapsayıcı eğitimin odak noktalarından hangisi ile ilgilidir?","Sistem Kapsayıcılığı",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır."),),

     ]),
    TestListHomepageModel("Tanımlar, Temel Unsurlar, Odaklar Pekiştirme Testi-2- (ÇÖZÜMLÜ) ",[
      Question("egitimkapsayicilik_ques_Q35","Kapsayıcı eğitim, planlı bir eğitim sürecidir.", "Aşağıdakilerden hangisi kapsayıcı eğitim sürecinin niteliğini arttıran faktörlerden biri değildir?","Sonuç odaklı yaklaşım sergilenmesi",["Sonuç odaklı yaklaşım sergilenmesi","İhtiyaçların analiz edilmesi","Kişisel özelliklerin belirlenmesi","Tercihlerin tespiti","Gereksinimlerin karşılanması"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4", "Tanım-4", "Kapsayıcı eğitim; öğrencilerin gereksinim, ihtiyaç, tercih ve kişisel özellikleri analiz edilerek hazırlanmış planlı bir eğitim sürecidir. Böylece eğitim sürecinin niteliği ve öğrencilerin derse katılım ve ilgileri artar."),),
      Question("egitimkapsayicilik_ques_Q36","", "Aşağıdaki seçeneklerden hangisinde kapsayıcı eğitim ortamına sahip okul özelliği doğru olarak verilmiştir?","Tüm öğrencilerin koşulsuz kabulünü destekler",["Eğitim ihtiyaçlarının okul dışında karşılanmasını savunur","Toplumsal farklılıkları azaltma amacındadır","Tüm öğrencilerin koşulsuz kabulünü destekler","Akademik başarı için öğrencilerin sosyal hayattaki varlıklarını azaltır","Koruyucu anlayışı ile fiziksel engelli bireylerin eğitimlerini erteler"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_11", "Tanım-5", "-Kapsayıcı eğitim ortamına sahip okullar tüm öğrencilerin koşulsuz bir şekilde kabul edilmesini ve eğitim ihtiyaçlarının okulda karşılanması gerektiğini savunurlar."),),
      Question("egitimkapsayicilik_ques_Q37","I-Eşitlik\nII-Ayrımcılık\nIII-Öğrencinin koşulsuz kabulü", "Yukarıdakilerden hangisi veya hangileri eğitim sürecini olumsuz olarak etkileyen davranışlardan biridir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır."),),
      Question("egitimkapsayicilik_ques_Q44","Mülteci bir öğrencisinin ailesi ile görüşen okul müdürü, öğrencilerinin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleri gerektiğini ifade etmiştir.", "Buna göre, okul müdürünün ifadesi kapsayıcı eğitimin temel unsurlarından hangisi ile ilgilidir?","Entegrasyon",["Entegrasyon","Ayrımcılık","Kapsayıcılık","Dışlanma","Koşulluluk"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir."),),
      Question("egitimkapsayicilik_ques_Q45","Kapsayıcı eğitim, öğrencilerin fiziki yetersizlik, sosyo-ekonomik durum, din, ırk vs. sebeplerle eğitim alma haklarının kesintiye uğratılmasının karşısındadır.", "Yukarıdaki ifade aşağıdaki verilen kapsayıcılığın temel unsurlarından hangisi ile ilgilidir?","Dışlanma",["Kapsayıcılık","Dışlanma","Ayrımcılık","Entegrasyon","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q46","Necmettin öğretmen'in yürüme engelli öğrencisi okula devam etmemektedir. Necmettin Öğretmen, öğrencisinin okula devam süreci ile ilgili çok büyük çaba sarf etmiştir.", "Buna göre, Necmettin Öğretmen'in sarf ettiği çaba kapsayıcılık ile ilgili kavramlardan hangisini ortadan kaldırmaya yöneliktir?","Dışlanma",["Kapsayıcılık","Entegrasyon","Ayrımcılık","Dışlanma","Hak Savunuculuğu"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q47","", "Dezavantajlı öğrencilerin akranlarından farklı bir sınıfta öğrenim görmeleri aşağıdaki kavramlardan hangisi ile ilgilidir?","Ayrımcılık",["Dışlanma","Kapsayıcılık","Entegrasyon","Korumacılık","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_15","Ayrımcılık", "-Dezavantajlı öğrencilerin kendilerine özel hazırlanmış sınıflarda eğitim görmeleri durumudur.\n-Bu ortam farklı bir kurum olabileceği gibi, aynı okulda farklı bir sınıfta olabilir.\n-Akranları ile birlikte değillerdir, ayrıştırılmışlardır."),),
      Question("egitimkapsayicilik_ques_Q54","Büşra Öğretmen, okuldaki dezavantajlı bireylerin ihtiyaç ve beklentilerini karşılamak adına eğitim sistemlerinin düzenlenmesi gerektiğini savunmaktadır.", "Buna göre Büşra Öğretmen'in savunduğu fikir, kapsayıcı eğitimin odaklarından hangisidir?","Sistem Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır.\n-Sorunun çözümündeki anahtar durum, sistemin öğrenciye odaklı değiştirilmesidir."),),
      Question("egitimkapsayicilik_ques_Q55","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanan kapsayıcı eğitimin odağı aşağıdakilerden hangisidir?","Eğitime Erişim Kapsayıcılığı",["Öğretim Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Hizmet Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani eğitim almak, isteyen herkes eğitim alsın anlayışı bulunur."),),
      Question("egitimkapsayicilik_ques_Q56","Her birey değerlidir. Bireylerdeki farklılıklar toplumun zenginliği olarak karşımıza çıkar. Eğitim sistemleri, bireysel farklılıkları ve olası dezavantajları içine alan nitelikli eğitim anlayışıyla ulaşılabilir bir eğitim sunmak zorundadır.", "Yukarıdaki paragrafta kapsayıcı eğitimin hangi odağından bahsedilmiştir?","Eğitime Erişim Kapsayıcılığı",["Faaliyet Kapsayıcılığı","Hizmet Kapsayıcılığı","Sosyal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve: InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani, eğitim almak isteyen herkes eğitim alsın anlayışı bulunur."),),

    ]),
    TestListHomepageModel("Tanımlar, Temel Unsurlar, Odaklar Pekiştirme Testi-3- (ÇÖZÜMLÜ) ",[
      Question("egitimkapsayicilik_ques_Q38","Kapsayıcı eğitim, dışlanmayı ve ayrımcılığı yok ederek herkese eşit eğitim anlayışını destekler.", "Aşağıdaki uygulamalardan hangisi bu görüş ile çelişmektedir?","Koruyucu ailedeki çocukların özel sınıflarda eğitimi",["Kız çocuklarının okullaşmasının arttırılması","Gelir düzeyi farklılıklarının yok sayılması","Mülteci öğrencilerin devlet okullarına kabulü","Özel eğitime muhtaç öğrencilerin sınıfla kaynaştırılması","Koruyucu ailedeki çocukların özel sınıflarda eğitimi"], answSolve: InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışını destekler.\n-Bu anlayışa göre, koruyucu ailedeki çocukların özel sınıflarda eğitimi değil okullarda kaynaştırılması hedeflenmelidir."),),
      Question("egitimkapsayicilik_ques_Q39","", "Aşağıdakilerden hangisi kapsayıcı eğitimin özellikle üzerinde durduğu öğrenci profilleri arasında yer almaz?","Gelir düzeyi yüksek ailelerin çocukları",["Kültürel geçmişleri farklı olan bireyler","Kırsal bölgede yaşayan çocuklar","Gelir düzeyi yüksek ailelerin çocukları","Kız çocukları","Mülteci çocukları"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_13", "Tanım-8", "-Kültürel geçmişleri farklı olan bireyler, kırsal bölgede yaşayan çocuklar, kız çocukları, göçmen ve mülteci çocuklar gibi birçok grubun eğitim hakkı, kapsayıcı eğitim bünyesinde yer alır.\n-Farklı grupların, eğitimde fırsat eşitliği kapsamında aynı eğitimi görmeleri mümkün kılınmalıdır."),),
      Question("egitimkapsayicilik_ques_Q40","I-Farklılıklar değerlidir\nII-Sosyal statü önemlidir\nIII-Öğrenciler aynılaştırılmalıdır", "Kapsayıcı eğitimin tanımı düşünüldüğünde, yukarıdakilerden hangisi veya hangileri doğrudur?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_12", "Tanım-7", "-Kapsayıcı eğitim, bireysel farklılıklara odaklanır ve farklılıklar değerlidir.\n-Sosyal statü, kapsayıcı eğitimin ilgi alanında değildir.\n-Öğrencilerin aynılaştırılması değil farklılıklarının kabulü esastır."),),
      Question("egitimkapsayicilik_ques_Q48","", "Tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunma amacını ifade eden kapsayıcılık kavramı aşağıdakilerden hangisidir?","Kapsayıcılık",["Ayrımcılık","Dışlanma","Kapsayıcılık","Entegrasyon","Eşitlik"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
      Question("egitimkapsayicilik_ques_Q49","", "Dezavantajlı öğrencilerin, fırsat eşitliği kapsamında eğitim haklarından faydalanmarı için reformist yapı ile gerekli düzenlemelerin yapılması aşağıdaki kavramlardan hangisi ile ilgilidir?","Kapsayıcılık",["Kapsayıcılık","Eşitlik","Entegrasyon","Dışlanma","Ayrımcılık"], answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır."),),
      Question("egitimkapsayicilik_ques_Q50","Öğretmenler Kurulunda söz hakkı isteyen Pınar Öğretmen, okuldaki göçmen öğrencilerin eğitim-öğretim sürecine katılımlarını sağlamak için öğretim stratejilerinde bazı değişiklikler yapılması gerektiğini ifade etmiştir.", "Pınar öğretmen Öğretmenler Kurulu'nda aşağıdaki kavramlardan hangisinin açıklamasını yapmıştır? ","Kapsayıcılık",["Eğitim Reformu","Ayrımcılık","Kapsayıcılık","Dışlanma","Entegrasyon"],answSolve: InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır.\n-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),),
      Question("egitimkapsayicilik_ques_Q57","", "Toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmaları aşağıdaki tanımlardan hangisi ile ilgilidir?","Sosyal Kapsayıcılık",["Sistem Kapsayıcılığı","Öğretim Kapsayıcılığı","Sosyal Kapsayıcılık","Hizmet Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q58","Benim hayat felsefem, her zaman toplumu kucaklamak olmuştur. Bu durum, iyi insan olmanın da ön şartıdır. Toplumun her kesimi, içerisinde bulunduğu duruma bakmadan hayatın içinde olmalıdır.", "Yukarıda verilen cümlede 'içerisinde bulunduğu duruma bakmadan hayatın içinde olmak' ifadesinin kapsayıcı eğitimdeki karşılığı aşağıdakilerden hangisidir?","Sosyal Kapsayıcılık",["Faaliyet Kapsayıcılığı","Aktif Kapsayıcılık","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı"],answSolve:InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),),
      Question("egitimkapsayicilik_ques_Q59","I-Hizmet Kapsayıcılığı\nII-Sosyal Kapsayıcılık\nIII-Gelişim Kapsayıcılığı", "Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),
      Question("egitimkapsayicilik_ques_Q60","I-Eğitim Erişim Kapsayıcılığı\nII-Koruyucu Kapsayıcılık\nIII-Yöneltme Kapsayıcılığı","Yukarıdakilerden hangisi veya hangileri UNESCO tarafından belirlenen kapsayıcı eğitimin odaklandığı temel alanlar arasında yer alır?","Yalnız I",["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"],answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),),

    ]),






    /*TestListHomepageModel("Kapsayıcı Eğitimin Gerekçeleri- (ÇÖZÜMLÜ) Test",[
 Question("egitimkapsayicilik_ques_Q61","", "Aşağıdakilerden hangisi kapsayıcı eğitimin gerekçelerinden biri değildir?","Bireysel gerekçe",["Eğitimsel gerekçe","Hukuki gerekçe","Sosyal gerekçe","Bireysel gerekçe","Eğitimsel gerekçe"], answSolve: InfoCardItem("ee_egitimkapsayici_info_5", "Kapsayıcı Eğitimin Gerekçeleri", "Kapsayıcı eğitimin gerekçeleri temel olarak 4 başlıkta toplanır. Bu başlıklar;\n-Eğitimsel gerekçe\n-Sosyal gerekçe\n-Ekonomik gerekçe\n-Hukuki gerekçe"),),
Question("egitimkapsayicilik_ques_Q62","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q63","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q64","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q65","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q66","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q67","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q68","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q69","", "","",["","","","",""]),
Question("egitimkapsayicilik_ques_Q70","", "","",["","","","",""]),

      ]),*/
    TestListHomepageModel("Eğitimde Kapsayıcılık-Test 1",[
      Question("egitimkapsayicilik_ques_Q1","I-Dışlanma\nII-Eşitsizlik\nIII-Ayrımcılık", "Kapsayıcı eğitim ihtiyacı olan çocukların yaşadığı olumsuz davranışlar hangi şıkta doğru verilmiştir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q2","", "Aşağıdakilerden hangisinde UNESCO’ya göre kapsayıcı eğitimin odaklandığı temel alanlar doğru verilmiştir?", "Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık", ["Sistem Kapsayıcılığı, Eğitime Erişim Kapsayıcılığı, Sosyal Kapsayıcılık","Eğitim Kapsayıcılığı, Eşitlik Kapsayıcılığı, Sistem Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı, Pozitif Ayrımcılık Kapsayıcılığı, Sosyal Kapsayıcılık","Adalet Kapsayıcılığı, Eşitlik Kapsayıcılığı, Eğitim Kapsayıcılığı","Eğitim Kapsayıcılığı, Sosyal Kapsayıcılık, Fırsat Eşitliği Kapsayıcılığı"]),
      Question("egitimkapsayicilik_ques_Q3","", "Kapsayıcı eğitimin gerekçeleri hangi şıkta doğru verilmiştir?", "Sosyal, Ekonomik, Eğitimsel Gerekçe", ["Toplumsal, Bireysel, Ulusal Gerekçe","Sosyal, Ekonomik, Eğitimsel Gerekçe","Bireysel, Eğitimsel, Sosyal Gerekçe","Ekonomik, Toplumsal, Ulusal Gerekçe","Eğitimsel, Sosyal, Bireysel Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q4","", "Aşağıdaki unsurlardan hangisi öğrencilerin okulda ayrımcılığa uğrama sebeplerden birisi değildir?", "Siyasi Görüşleri", ["Siyasi Görüşleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Sosyoekonomik Düzeyleri"]),
      Question("egitimkapsayicilik_ques_Q5","", "Mülteci, göçmen ya da sığınmacı öğrencilerin okulda yaşayabilecekleri ayrımcılığın sebebi aşağıdakilerden hangisidir?", "Etnik Kökenleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Etnik Kökenleri","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q6","", "Öğrencilerin özel durumundan dolayı olumsuz davranışlara maruz kalmaları aşağıdakilerden hangisi sebebiyledir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Dini İnançları","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q7","", "Öğrencinin mezhebi dolayısıyla okulda uğradığı olumsuz davranışların sebebi hangisi olabilir?", "Dini İnançları", ["Etnik Kökenleri","Dini İnançları","Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q8","", "Kız öğrencilerin okula gönderilmemeleri ya da okuldan erken yaşta alınmaları, aşağıdakilerden hangisi sebebiyledir?", "Cinsiyetleri", ["Dini İnançları"," Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Cinsiyetleri","Sosyoekonomik Düzeyleri"]),
      Question("egitimkapsayicilik_ques_Q9","I-İbadetleri\nII-Mezhepleri\nIII- İnançları", "Öğrencilerin yaşadığı yukarıdaki durumlardan hangileri dini inanç kategorisine girer?", "I-II-III", ["I-III","Yalnız II","II-III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q10","", "Aile yapısı sebebiyle ayrımcılığa uğrayan öğrencinin durumu aşağıdakilerden hangisi sebebiyledir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Etnik Kökenleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Din İnanç ve Yaşayışları","Cinsiyetleri"]),
    ]),
    TestListHomepageModel("Eğitimde Kapsayıcılık-Test 2",[
      Question("egitimkapsayicilik_ques_Q11","", "Eğitim sistemlerinin, okulların, öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duymaları hangi tür kapsayıcılığa girer?", "Sistem Kapsayıcılığı", ["Toplumsal Kapsayıcılık","Sistem Kapsayıcılığı","Eğitime Erişim Kapsayıcılığı","Sosyal Kapsayıcılık","Pozitif Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q12","", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması hangi tür kapsayıcılığa girer?", "Eğitime Erişim Kapsayıcılığı", ["Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Eğitime Erişim Kapsayıcılığı","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q13","", "Tüm paydaşların beklentilerini kapsayacak şekilde eğitim süreçlerinin geliştirilmesi hangi tür kapsayıcılığa girer?", "Sosyal Kapsayıcılık", ["Eğitime Erişim Kapsayıcılığı","Sistem Kapsayıcılığı","Sosyal Kapsayıcılık","Fırsat Eşitliği Kapsayıcılığı","Toplumsal Kapsayıcılık"]),
      Question("egitimkapsayicilik_ques_Q14","", "Öğrencilerin öğrenme potansiyellerini, bireysel özellik ve ihtiyaçlarına hitap eden eğitim programları ile geliştirmek kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Eğitimsel Gerekçe", ["Bireysel Gerekçe","Sosyal Gerekçe","Toplumsal Gerekçe","Eğitimsel Gerekçe","Ekonomik Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q15","", "Öğrencilerin adaletli ve fırsat eşitsizliklerinden arınmış bir ortamda eğitim görmesi kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Sosyal Gerekçe", ["Eğitimsel Gerekçe","Sosyal Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe","Ekonomik Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q16","", "Öğrencilerin bir çatı altında eğitim görmesi farklı türde okullara olan ihtiyacı azaltacaktır. Bu ifade kapsayıcılığın hangi gerekçesi ile ilişkilidir?", "Ekonomik Gerekçe", ["Ekonomik Gerekçe","Sosyal Gerekçe","Eğitimsel Gerekçe","Bireysel Gerekçe","Ulusal Gerekçe"]),
      Question("egitimkapsayicilik_ques_Q17","I-Eğitimde adalet ve fırsat eşitliği sağlanmalıdır.\nII-Eğitim sürecine aile ve toplumun katılımı sağlanmalıdır.\nIII-Öğrencilerin istihdamı için altyapı hazırlanmalıdır.", "Yukarıda verilen kapsayıcı eğitimin temel ilkelerinden hangileri doğrudur?", "I-II-III", ["I-III","II-III","Yalnız III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q18","", "Okulda ayrımcılığa uğrayan çocuklarda aşağıdaki davranışlardan hangisi görülmez?", "Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.", ["Okulu sevmediğini söyler.","Eve geldiği zaman huysuz, aksi ve yorgundur.","Devamsızlık yapar ancak sınıf arkadaşlarıyla görüşmeye devam etmek ister.","Okul ile ilgili hiçbir şey yapmak istemez.","Okul ile ilgili heyecan verici ya da mutlu olduğu durumları anlatmayı bırakır."]),
      Question("egitimkapsayicilik_ques_Q19","I-Tüm çocukların fırsat eşitliği elde etmesi\nII-Öğrencilerin okula ilgilerinin ve derslere katılımlarının artması\nIII- Öğrencilerin okul ve toplum yaşamlarının ilişkilendirilmesi ve bütünleştirmesi", "Yukarıdaki ifadelerden hangileri kapsayıcı eğitim faydaları kapsamında değerlendirilebilir?", "I-II-III", ["Yalnız I","II-III","I-III","I-II","I-II-III"]),
      Question("egitimkapsayicilik_ques_Q20","", "Öğrenme güçlüğü çeken çocukların okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Fiziksel Yetersizlik ve Özel Gereksinimleri", ["Etnik Kökenleri","Dini İnançları","Cinsiyetleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Sosyo-ekonomik Düzeyleri"]),
    ]),
    TestListHomepageModel("Eğitimde Kapsayıcılık-Test 3",[
      Question("egitimkapsayicilik_ques_Q21","", "Yüksek gelir düzeyine sahip ailelerin çocuklarının okulda olumsuz davranışlara maruz kalmalarının sebebi aşağıdakilerden hangisidir?", "Sosyoekonomik Düzeyleri", ["Sosyoekonomik Düzeyleri","Fiziksel Yetersizlik ve Özel Gereksinimleri","Etnik Kökenleri","Dini İnançları","Cinsiyetleri"]),
      Question("egitimkapsayicilik_ques_Q22","", "Kapsayıcı eğitim konusunda yoğun çalışmaları bulunan uluslararası kuruluşlar hangisinde doğru olarak verilmiştir?", "UNICEF - UNESCO", ["WHO - ILO","UNESCO - OECD","UNICEF - UNESCO","UNICEF - G20"," WHO-OECD"]),
      Question("egitimkapsayicilik_ques_Q23","", "Kapsayıcı eğitim, tüm çocukların aynı okulda birlikte öğrenmeleridir şeklinde kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNICEF", ["OECD","WHO","G20","UNICEF","UNESCO"]),
      Question("egitimkapsayicilik_ques_Q24","", "Öğrencilerin farklı ihtiyaçlarına, onların eğitime, kültüre ve sosyal hayata katılımlarını arttırarak ve ayrımcılığı en aza indirerek cevap verme süreci olarak kapsayıcı eğitim tanımı yapan uluslararası kuruluş aşağıdakilerden hangisidir?", "UNESCO", ["OECD","UNESCO","G20","UNICEF","WHO"]),
      Question("egitimkapsayicilik_ques_Q25","", "Yabancı uyruklu farklı dine mensup bir öğrencinin okulda yaşayabileceği ayrımcılık sebepleri hangisinde doğru olarak verilmiştir?", "Etnik Kökenleri - Dini İnançları", ["Sosyoekonomik Düzeyleri – Dini İnançları","Dini İnançları – Fiziksel Yetersizlikleri","Özel Gereksinimleri - Dini İnançları","Etnik Kökenleri – Sosyoekonomik Durumları","Etnik Kökenleri - Dini İnançları"]),
      // Question("egitimkapsayicilik_ques_Q26","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q27","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q28","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q29","", "","",["","","","",""]),
      // Question("egitimkapsayicilik_ques_Q30","", "","",["","","","",""]),

    ]),
    TestListHomepageModel("Hazırlanıyor",[
      Question("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", ["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"])
    ]),
  ];

    //Question("olcmedeger_ques_11111111","Hazırlanıyor", "Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),

   // Question("egitimkapsayicilik_ques_Q71","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q72","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q73","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q74","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q75","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q76","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q77","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q78","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q79","", "","",["","","","",""]),
   // Question("egitimkapsayicilik_ques_Q8","", "", "", ["","","","",""]),

  List<TestListHomepageModel> get egitimKapsayicilik=>_egitimKapsayicilikList;
}