import 'package:flutter/material.dart';

import '../../model/question.dart';

class EgitimKapsayicilikQuesViewModel extends ChangeNotifier{
  List<Question> _egitimKapsayicilikList=[
    Question("egitimkapsayicilik_ques_Q1","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q2","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q3","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q4","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q5","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q6","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q7","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q8","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q9","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q10","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q11","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q12","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q13","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q14","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q15","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q16","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q17","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q18","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q19","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q20","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q21","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q22","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q23","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q24","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q25","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q26","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q27","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q28","", "","",["","","","",""]),
    Question("egitimkapsayicilik_ques_Q29","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q30","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q31","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q32","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q33","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q34","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q35","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q36","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q37","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q38","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q39","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q40","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q41","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q42","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q43","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q44","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q45","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q46","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q47","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q48","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q49","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q50","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q51","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q52","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q53","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q54","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q55","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q56","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q57","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q58","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q59","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q60","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q61","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q62","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q63","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q64","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q65","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q66","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q67","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q68","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q69","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q70","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q71","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q72","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q73","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q74","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q75","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q76","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q77","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q78","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q79","", "", "", ["","","","",""]),
    Question("egitimkapsayicilik_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get egitimKapsayicilik=>_egitimKapsayicilikList;
}