import 'package:flutter/material.dart';

import '../../model/question.dart';

class EgitimArastirmaQuesViewModel extends ChangeNotifier{
  List<Question> _egitimArastirmaList=[
    ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),

   Question("egitimarastirma_ques_Q1","", "Bir konuda öğrenilen veya öğretilen şeylere aşağıdakilerden hangisi denir?","Bilgi",["Eğitim","Konu","Bilgi","Öğretim","Veri"]),
   Question("egitimarastirma_ques_Q2","I-Öğrenilir\nII-Öğretilir\nIII-Zihinsel süreçleri kapsar", "Bilgi ile ilgili yukarıdakilerden hangisi veya hangileri doğru olarak verilmiştir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
   Question("egitimarastirma_ques_Q3","", "Geçerliliği birçok kişi tarafından kabul edilmiş sistemli bilgilere aşağıdakiilerden hangisi denir?","Bilim",["Bilgi","Bilim","Araştırma","Hipotez","Fikir"]),
   Question("egitimarastirma_ques_Q4","Öğretmeninin sorduğu soruyu cevaplamak için parmak kaldırarak söz isteyen Fatih,\n-'Geçerliliği birçok kişi tarafından kabul edilmiş sistemli bilgilere denir.' demiştir.", "Buna göre Fatih'in öğretmeni aşağıdaki sorulardan hangisini sormuştur?","Bilim nedir?",["Fayda nedir?","Kültür nedir?","Araştırma nedir?","Bilim nedir?","Ar-ge nedir?"]),
   Question("egitimarastirma_ques_Q5","I-Gerçeğe aykırıdır\n-Sistemlidir\nIII-Deneysel çalışılabilir", "Yukarıdakilerden hangisi veya hangileri bilim ile ilgili olarak doğru verilmiştir?","II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
   Question("egitimarastirma_ques_Q6","", "Öğretmeninin sorusuna, 'Bir konuda öğrenilen veya öğretilen şeydir' diye cevap veren Esra'nın öğretmeni aşağıdakilerden hangisini sormuştur?","Bilgi nedir?",["Fayda nedir?","Bilgi nedir?","Araştırma nedir?","Bilim nedir?","Ar-ge nedir?"]),
   Question("egitimarastirma_ques_Q7","", "Açığa çıkartılmak istenen gerçeğin veya olgunun bilimsel yöntemlerle ortaya konmasına aşağıdakilerden hangisi denir?","Araştırma",["Bilgi","Bilim","Araştırma","Hipotez","Envanter"]),
   Question("egitimarastirma_ques_Q8","", "Aşağıdakilerden hangisi araştırmanın en önemli ön koşuludur?","Sorunun olması",["Fikrin olması","Merakın olması","Faaliyet alanının olması","Koşulun olması","Sorunun olması"]),
   Question("egitimarastirma_ques_Q9","4. sınıf öğrencisi Burak, araştırma konusunda deneyler yapmak istemektedir.", "Buna göre Burak aşağıdakilerden hangi araştırmaa yöntemini kullanacaktır?","Nicel araştıma",["Nicel araştıma","Betimsel araştırma","Temel araştırma","Nitel araştırma","Konu araştırması"]),
   Question("egitimarastirma_ques_Q10","I-Nikel araştırma\nII-Nicel araştırma\nIII-Temel araştırma", "Yukarıdakilerden hangisi veya hangileri araştırma türlerindendir?","Yalnız II", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
  // Question("egitimarastirma_ques_Q11","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q12","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q13","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q14","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q15","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q16","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q17","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q18","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q19","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q20","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q21","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q22","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q23","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q24","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q25","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q26","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q27","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q28","", "","",["","","","",""]),
  // Question("egitimarastirma_ques_Q29","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q30","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q31","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q32","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q33","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q34","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q35","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q36","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q37","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q38","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q39","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q40","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q41","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q42","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q43","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q44","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q45","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q46","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q47","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q48","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q49","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q50","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q51","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q52","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q53","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q54","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q55","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q56","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q57","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q58","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q59","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q60","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q61","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q62","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q63","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q64","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q65","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q66","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q67","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q68","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q69","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q70","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q71","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q72","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q73","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q74","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q75","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q76","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q77","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q78","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q79","", "", "", ["","","","",""]),
  // Question("egitimarastirma_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get egitimArastirma=>_egitimArastirmaList;
}