import 'package:flutter/material.dart';

import '../../model/question.dart';

class OgrenOgretQuesViewModel extends ChangeNotifier{
  ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
  List<Question> _ogrenOgretList=[
    Question("eo_Q119","", "Aşağıdakilerden hangisi öğrenme ile ilgili doğru bir ifade değildir?", "Kalıcı olması gerekmez", ["Davranış değişikliği gerektirir","Olumlu ve olumsuz yönde olabilir","Kalıcı olması gerekmez","Refleksif hareketler öğrenme kabul edilmez","Çevresel faktörler etkendir"]),
    Question("eo_Q120","I-Refleksif\nII-Kalıcı\nIII-Olumlu", "Öğrenme sürecinin gerçekleştirğinden söz edebilmek için yukarıdakilerden hangisi kesinlikle gereklidir?", "Yalnız II", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("eo_Q121","I-Gözlenebilir\nII-Yaşansısal\nIII-Kalıcı", "Öğrenmenin gerçekleştiğinden söz edilebilmesi için yukarıdakilerden hangisi veya hangilerinin bulunması gerekir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("eo_Q122","", "Aşağıdakilerden hangisi davranış türlerinden değildir?", "Kusursuz davranış", ["Bilişsel davranış","Duyuşsal davranış","Psikomotor davranış","İstendik davranış","Kusursuz davranış"]),
    Question("eo_Q123","", "Eylemin yapılmasında sebep sonuç ilişkisi kurma, dikkat etme, hatırlama, yorum çıkartma ve hayalgücünü kullanma gibi süreçlerin etkili olduğu öğrenme süreci aşağıdakilerden hangisidir?", "Bilişsel davranış", ["Psikomotor davranış","İstendik davranış","Duyuşsal davranış","Bilişsel davranış","Doğuştan gelen davranış"]),
    Question("eo_Q124","", "Sevinç, üzüntü, korku, heyecan gibi duyguların beyin süzgecinden geçerek davranışa dönüşme süreci aşağıdakilerden hangisidir?", "Duyuşsal davranış", ["Doğuştan gelen davranış","Öğrenilmiş davranış","İstendik davranış","Bilişsel davranış","Duyuşsal davranış"]),
    Question("eo_Q125","", "Yürüme, koşma, zıplama, kaldırma gibi fiziksel aktiviteler içeren davranış türü aşağıdakilerden hangisidir?", "Psikomotor davranış", ["Psikomotor davranış","Doğuştan gelen davranış","Öğrenilmiş davranış","Bilişsel davranış","İstendik davranış"]),
    Question("eo_Q126","", "Planlı bir süreç sonundaki ortaya çıkan öğrenmeler aşağıdaki davranış türlerinden hangisine girer?", "İstendik davranış", ["Bilişsel davranış","İstendik davranış","Öğrenilmiş davranış","Psikomotor davranış","Duyuşsal davranış"]),
    Question("eo_Q127","", "Gelişigüzel kültürlenme sonucu ortaya çıkan öğrenmeler aşağıdaki davranış türlerinden hangisine girer?", "İstendik davranış", ["Bilişsel davranış","İstendik davranış","Öğrenilmiş davranış","Psikomotor davranış","Duyuşsal davranış"]),
    Question("eo_Q129","", "Hatalı eğitim süreçleri sonunda ortaya çıkan öğrenmeler aşağıdaki davranış türlerinden hangisine girer?", "İstenmedik davranış", ["Bilişsel davranış","İstendik davranış","Öğrenilmiş davranış","İstenmedik davranış","Duyuşsal davranış"]),
    Question("eo_Q130","", "Kötü kültürlenme sonucu ortaya çıkan öğrenmeler aşağıdaki davranış türlerinden hangisine girer?", "İstenmedik davranış", ["Bilişsel davranış","İstendik davranış","Öğrenilmiş davranış","İstenmedik davranış","Duyuşsal davranış"]),
    Question("eo_Q131","", "İlaç kullanımı ve alkol gibi durumlar sebebiyle ortaya çıkan davranışlar aşağıdakilerden hangisidir?", "Geçici davranış", ["Geçici davranış","İstendik davranış","Öğrenilmiş davranış","İstenmedik davranış","Duyuşsal davranış"]),
    Question("eo_Q132","", "Refleksif, içgüdüsel ve kontrol dışı ortaya çıkan davranışlar aşağıdakilerden hangisidir?", "Doğuştan gelen davranış", ["Geçici davranış","İstendik davranış","Öğrenilmiş davranış","İstenmedik davranış","Doğuştan gelen davranış"]),
    Question("eo_Q133","", "Aşağıdakilerden hangisi öğrenmeyi etkileyen faktörlerin öğrenenle ilgili olanlarından değildir?", "Algısal ayırt edilebilirlik", ["Türe özgü hazıroluş","Olgunlaşma","Algısal ayırt edilebilirlik","Eski yaşantılar","Güdü"]),
    Question("eo_Q134","", "Aşağıdakilerden hangisi öğrenmeyi etkileyen faktörlerin öğrenenle ilgili olanlarından değildir?", "Anlamsal çağrışım", ["Eski yaşantılar","Dikkat","Genel uyarılmışlık düzeyi","Anlamsal çağrışım","Güdü"]),
    Question("eo_Q135","Bazı davranışların öğrenilebilmesi için organizmanın sahip olması gereken yeterlilikler bulunur.", "Yukarıda verilen ifade öğrenen ile ilgli faktörlerden hangisine girer?", "Türe özgü hazıroluş", ["Olgunlaşma","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi","Eski yaşantılar","Dikkat"]),
    Question("eo_Q136","Bazı davranışların gerçekleştirilebilmesi için fiziksel ve zihinsel yeterliliğin olması gerekir.", "Yukarıda verilen ifade öğrenen ile ilgli faktörlerden hangisine girer?", "Olgunlaşma", ["Olgunlaşma","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi","Eski yaşantılar","Dikkat"]),
    Question("eo_Q137","Çevresel uyarıcılar, belirli bir düzeye kadar bireyin öğrenmelerine olumlu katıkıda bulunur.", "Yukarıda verilen ifade öğrenen ile ilgli faktörlerden hangisine girer?", "Genel uyarılmışlık düzeyi", ["Olgunlaşma","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi","Eski yaşantılar","Dikkat"]),
    Question("eo_Q138","", "İhtiyaçtan dolayı organizmayı davranışa iten güç aşağıdakilerden hangisidir?", "Güdü", ["Olgunlaşma","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi","Eski yaşantılar","Güdü"]),
    Question("eo_Q139","", "Bireyin veya organizmanın, önceki öğrenmelerinin yeni öğrenmelerine etki etmesi aşağıdakilerden hangisi ile ifade edilir?", "Eski yaşantılar",["Eski yaşantılar","Dikkat","Güdü","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi"]),
    Question("eo_Q140","", "Aşağıdakilerden hangisi öğrenmeyi etkileyen faktörlerden öğrenme yöntemi ile ilgili değildir?", "Dikkat", ["Konunun yapısı","Dikkat","Zaman kullanımı","Etkin katılım","Dönüt"]),
    Question("eo_Q141","I-Güdü\nII-Etkin katılım\nIII-Dikkat", "Aşağıdakilerden hangisi öğrenmeyi etkileyen faktörlerden öğrenme yöntemi ile ilgilidir?", "Yalnız II", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("eo_Q142","I-Bütün-Bütün-Parça\nII-Bütün-Parça-Parça\nIII-Parça-Bütün-Parça", "Yukarıdakilerden hangisi veya hangileri etkili öğrenme yöntemlerinden biri değildir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("eo_Q143","", "Konunun toplu olarak veya zamansal aralıklarla çalışılması aşağıdakilerden hangisi ile ilgilidir?", "Zaman kullanımı", ["Konunun yapısı","Dikkat","Zaman kullanımı","Etkin katılım","Dönüt"]),
    Question("eo_Q145","", "Öğrenmenin gerçekleşme durumunun tespiti için aşağıdakilerden hangisi kullanılır?", "Dönüt",["Konunun yapısı","Dikkat","Zaman kullanımı","Etkin katılım","Dönüt"]),
    Question("eo_Q146","", "Aşağıdakilerden hangisi öğrenme malzemesi ile ilgili faktörlerden biridir?", "Algısal ayırt edilebilirlik", ["Etkin katılım","Türe özgü hazıroluş","Genel uyarılmışlık düzeyi","Dikkat","Olgunlaşma"]),
    Question("eo_Q147","", "Aşağıdakilerden hangisi öğrenme malzemesi ile ilgili faktörlerdendir?", "Anlamsal çağrışım", ["Etkin katılım","Anlamsal çağrışım","Genel uyarılmışlık düzeyi","Dikkat","Algısal ayırt edilebilirlik"]),
    Question("eo_Q148","", "Aşağıdakilerden hangisi öğrenme malzemesi ile ilgili faktörlerden biridir?", "Çağrışımsal gruplandırma", ["Çağrışımsal gruplandırma","Güdü","Genel uyarılmışlık düzeyi","Dikkat","Eski yaşantılar"]),
    Question("eo_Q149","", "Aşağıdakilerden hangisi öğrenme malzemesi ile ilgili faktörlerden biridir?", "Kavramsal gruplandırma", ["Etkin katılım","Türe özgü hazıroluş","Kavramsal gruplandırma","Dikkat","Eski yaşantılar"]),
    Question("eo_Q150","I-Telaffuz edilebilirlik\nII-Kavramsal gruplandırma\nIII-Anlamsal çağrışım", "Yukarıdakilerden hangisi veya hangileri öğrenme malzemesi ile ilgili faktörlerdendir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("eo_Q151","", "Uyarıcının o an çevrede varolan tüm uyarıcılardan daha güçlü olması durumu öğrenme malzemesi ile ilgili faktörlerden hangisi ile ilgilidir?", "Algısal ayırt edilebilirlik", ["Anlamsal çağrışım","Kavramsal gruplandırma","Algısal ayırt edilebilirlik","Çağrışımsal gruplandırma","Telaffuz edilebilirlik"]),
    Question("eo_Q152","", "Yeni öğrenmelerin eski öğrenmelerden esinlenilerek gerçekleşmesi durumu öğrenme malzemesi ile ilgili faktörlerden hangisi ile ilgilidir?", "Anlamsal çağrışım", ["Anlamsal çağrışım","Kavramsal gruplandırma","Algısal ayırt edilebilirlik","Çağrışımsal gruplandırma","Telaffuz edilebilirlik"]),
    Question("eo_Q153","", "Konuların iki boyutlu çizelge ile hiyerarşik olarak ilişkilerinin gösterilmesi öğrenme mazlemesi ile iligili faktörlerden hangisi ile ilgilidir?", "Kavramsal gruplandırma", ["Anlamsal çağrışım","Kavramsal gruplandırma","Algısal ayırt edilebilirlik","Çağrışımsal gruplandırma","Telaffuz edilebilirlik"]),
    Question("eo_Q154","", "İçeriğin deneyimlerle ve bilgilerle ilişkilendirilmesi öğrenme mazlemesi ile iligili faktörlerden hangisi ile ilgilidir?", "Çağrışımsal gruplandırma", ["Anlamsal çağrışım","Kavramsal gruplandırma","Algısal ayırt edilebilirlik","Çağrışımsal gruplandırma","Telaffuz edilebilirlik"]),
    Question("eo_Q155","", "İçeriğin dilsel gelişime uygun olarak verilmesi aşağıdaki öğrenme malzemesi ile ilgili faktrlerden hangisi ile ilgilidir?", "Telaffuz edilebilirlik", ["Anlamsal çağrışım","Kavramsal gruplandırma","Algısal ayırt edilebilirlik","Çağrışımsal gruplandırma","Telaffuz edilebilirlik"]),

    Question("ogrenogret_ques_Q1","", "Aşağıdakilerden hangisi öğrenme ile ilgili doğru bir ifade değildir?", "Kalıcı olması gerekmez", ["Davranış değişikliği gerektirir","Olumlu ve olumsuz yönde olabilir","Kalıcı olması gerekmez","Refleksif hareketler öğrenme kabul edilmez","Çevresel faktörler etkendir"]),
    Question("ogrenogret_ques_Q2","I-Refleksif\nII-Kalıcı\nIII-Olumlu", "Öğrenme sürecinin gerçekleştirğinden söz edebilmek için yukarıdakilerden hangisi kesinlikle gereklidir?", "Yalnız II", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("ogrenogret_ques_Q3","I-Gözlenebilir\nII-Yaşansısal\nIII-Kalıcı", "Öğrenmenin gerçekleştiğinden söz edilebilmesi için yukarıdakilerden hangisi veya hangilerinin bulunması gerekir?", "I-II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("ogrenogret_ques_Q4","", "Aşağıdakilerden hangisi öğrenme ortamı ile ilgili doğru bir ifade değildir?","Öğretenin rahat hareket etmesi esas alınmalıdır",["Öğrenme isteğini arttırmalıdır","Farklı öğrenmelerin gerçekleştirilmesine uygun olmalıdır","Öğretenin rahat hareket etmesi esas alınmalıdır","Öğrenci için en uygun ortam hazırlanmalıdır","Öğrenmeyi destekleyici materyallerle zenginleştirilmelidir"]),
    Question("ogrenogret_ques_Q5","", "Aşağıdakilerden hangisi doğru öğretme süreci ile ilgili doğru bir ifade değildir?","Öğreten merkezde olmalıdır",["Öğreten merkezde olmalıdır","Öğrenende davranış değişikliği ortaya çıkartır","Öğrenene rehberlik edilmesi esastır","Öğrenenin ilgi ve talepleri göz önünde bulundurulmalıdır","Öğrenme ortamının uygun olması, öğretenin işini kolaylaştıracak bir unsurdur"]),
    Question("ogrenogret_ques_Q6","", "Aşağıdakilerden hangisi öğretmenin görevlerinden biridir?","Uygun öğrenme ortamı sağlar",["Öğrenmeyi gerçekleştirir","Uygun öğrenme ortamı sağlar","Öğrenme sürecine müdahale etmez","Öğrencinin kendi yöntemini geliştirebilmesi için istek ve taleplerine karşılık vermez","Öğrenen için zorlaştırıcı unsurlar geliştirerek öğrenmeyi kalıcı hale getirir"]),
    Question("ogrenogret_ques_Q7","", "Aşağıdakilerden hangisi eğitim programının özelliklerinden biri değildir?","Yalnızca okul içi süreçleri kapsar",["Öğretime yön verir","Öğretim sürecini kolaylaştırır","Yalnızca okul içi süreçleri kapsar","Öğretim sürecinin kontrolünü sağlar","Öğretim süreci planlamasının düzenli olmasını sağlar"]),
    Question("ogrenogret_ques_Q8","I-Düzenlidir\nII-Planlıdır\nIII-Sonuç odaklıdır", "Yukarıdakilerden hangisi veya hangileri eğitim programının özelliklerinden biri değildir?","Yalnız III", ["Yalnız I","Yalnız II","Yalnız III","I-II","I-II-III"]),
    Question("ogrenogret_ques_Q9","", "Aşağıdakilerden hangisi öğretim programının özelliklerinden biri değildir?","Ders içi ve ders dışı etkinlikleri kapsar",["Ders içi ve ders dışı etkinlikleri kapsar","Eleştirel düşünme becerilerini geliştirmeyi hedefler","Yaratıcı düşünme kabiliyetlerini geliştirmeyi hedefler","Planların nasıl uygulanacağı hakkında bilgi verir","İletişim becerilerini geliştirmeyi hedefler"]),
    Question("ogrenogret_ques_Q10","I-Eleştirel düşünme\nII-Yaratıcı düşünme\nIII-İletişim becerileri", "Yukarıdakilerden hangisini veya hangilerini öğretim programının olumlu yönde etkilemesi beklenir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("ogrenogret_ques_Q11","", "Aşağıdakilerden hangisi okul içi ve okul dışı etkinliklerini kapsayan programdır?","Eğitim Programı",["Öğretim Programı","Eğitim Programı","Örtük Program","Kapsayıcı Program","Genişletilmiş Program"]),
    Question("ogrenogret_ques_Q12","", "Aşağıdakilerden hangisi eğitimin özelliklerinden biri değildir?","Okul sürecini kapsar",["Geniş kapsamlıdır","Kültürlenme sürecinin parçasıdır","Okul sürecini kapsar","Bireye olumlu yönde katkı sağlar","Topluma uyum sağlanmasında etkilidir"]),


    // Question("ogrenogret_ques_Q13","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q14","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q15","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q16","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q17","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q18","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q19","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q20","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q21","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q22","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q23","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q24","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q25","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q26","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q27","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q28","", "","",["","","","",""]),
   // Question("ogrenogret_ques_Q29","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q30","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q31","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q32","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q33","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q34","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q35","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q36","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q37","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q38","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q39","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q40","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q41","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q42","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q43","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q44","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q45","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q46","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q47","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q48","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q49","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q50","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q51","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q52","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q53","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q54","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q55","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q56","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q57","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q58","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q59","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q60","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q61","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q62","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q63","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q64","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q65","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q66","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q67","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q68","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q69","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q70","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q71","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q72","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q73","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q74","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q75","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q76","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q77","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q78","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q79","", "", "", ["","","","",""]),
   // Question("ogrenogret_ques_Q8","", "", "", ["","","","",""]),



  ];
  List<Question> get ogrenOgret=>_ogrenOgretList;
}