import 'package:flutter/material.dart';

import '../../model/question.dart';
import '../../model/test_list_homepage_model.dart';

class OkulGelistirmeQuesViewModel extends ChangeNotifier{
  ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),

  List<TestListHomepageModel> _okulGelistirmeList=[
    TestListHomepageModel("Okul Geliştirme-Karışık Test Çöz",[
      Question("okulgelistirme_ques_Q1","", "Okuldaki mevcut yapıların ve eğitim durumlarının daha da iyiye götürülme sürecine verilen isim aşağıdakilerden hangisidir?","Okul geliştirme",["Okul deneyimi","Okul geliştirme","Okul durumu","Okul yöetimi","Okul yapısı"]),
      Question("okulgelistirme_ques_Q2","", "Okul geliştirme ile ilgili aşaıdakilerden hangisi doğru bir ifade değildir?","Eski durumlar hesaba katılmaz",["Mevcut durumu daha iyiye götürme sürecidir","Eski durumlar hesaba katılmaz","Okulun fiziksel yapısı ve donanımı önemlidir","Veli beklentilerine önem verilir","Hedefler öğrenci yapısına uygun olmalıdır"]),
      Question("okulgelistirme_ques_Q3","", "Aşağıdakilerden hangisi okul geliştirme alanlarına verilebilecek örneklerden değildir?","Okullaştırma oranının arttırılması",["Ders materyali iyileştirmeleri","Eğitim öğretim süreci","Fiziksel yapı iyileştirmeleri","Veliye sunulan hizmetler","Okullaştırma oranının arttırılması"]),
      Question("okulgelistirme_ques_Q4","I-Nitelikli eğitim\nII-Çevrenin okula katılımı\nIII-Başarı düzeyinin arttırılması", "Yukarıdakilerden hangisi veya hangileri okul geliştirme düzeyi ile ilgilidir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
      Question("okulgelistirme_ques_Q5","", "Aşağıdakilerden hangisi okul geliştirmenin konusu değildir?","Erken yaşta evliliğin önüne geçilmesi",["Erken yaşta evliliğin önüne geçilmesi","Akademik başarının arttırılması","Öğretmen gelişiminin sağlanması","Veli-okul işbirliğinin güçlenmesi","Yönetici deneyiminin arttırılması"]),
      Question("okulgelistirme_ques_Q6","Etkili okula ulaşmak için dikkat edilmesi gereken bazı temel noktalar bulunur.", "Aşağıdakilerden hangisi bu temel noktalardan biri değildir?","MEB'e bağlı olması",["Okuldaki öğrenci sayısı","Okulun yönetim yapısı","MEB'e bağlı olması","Okulun gelir/gider durumu","Öğretmen deneyimi"]),
      Question("okulgelistirme_ques_Q7","Bazı okullar mevcut koşulları sebebiyle etkili okul kapsamında sayılmaz.", "Aşağıdakilerden hangisi okulu etkili okul haline getirmek için öğretmenin yapabilecekleri arasında sayılamaz?","Okulun yönetim yapısını değiştirmek",["Aile katılımını sağlamak","Derse katılım oranını arttırmak","Okulun yönetim yapısını değiştirmek","Sosyal etkinlikler ile okulu zenginleştirmek","Öğrenme-öğretme stillerinde çeşitlilik sunmak"]),
      Question("okulgelistirme_ques_Q8","", "Etkili okul yapısının oluşturulmasında aşağıdakilerden hangisi gerekli değildir?","Öğrenci sayısının fazla olması",["Öğretmen yeterliliklerinin fazla olması","Yönetici deneyiminin fazla olması","Okul imkanlarının fazla olması","Öğrenci sayısının fazla olması","Aile katılımının fazla olması"]),
      Question("okulgelistirme_ques_Q9","", "Aşağıdakilerden hangisi okul geliştirme sürecine olumlu katkı sağlamaz?","Ulaşım imkanlarının az olması",["Okul binasının yeterli olması","Velilerin okul ile işbirliği içinde olması","Öğretmen ilgisinin fazla olması","İdareci deneyiminin fazla olması","Ulaşım imkanlarının az olması"]),
      Question("okulgelistirme_ques_Q10","", "Okuldaki ihtiyaçların belirlenerek bunlara ilişkin yapılacak faaliyetlerin planlanması aşağıdakilerden hangisi ile ifade edilir?","Okul geliştirme",["Okul etkinliği","Okul geliştirme","Okul deneyimi","Okul önceliği","Okul görünürlüğü"]),
      Question("okulgelistirme_ques_Q11","", "Aşağıdakilerden hangisi okul geliştirme alanlarına verilebilecek bir örnek olamaz?","Tüm Türkiye'de ders giriş zillerinin aynı olması",["Veliye sunulan hizmetler","Tüm Türkiye'de ders giriş zillerinin aynı olması","Öğretmen-öğrenci imkanlarının iyileştirilmesi","Fiziksel yapı iyileştirmeleri","Ders materyali iyileştirmeleri"]),
      Question("okulgelistirme_ques_Q12","I-Değerlendirme raporunun hazırlanması\nII-Okul geliştirme planının hazırlanması\nIII-İhtiyaçların belirlenmesi\nIV-Verilerin toplanması", "Okul geliştirmesi ile ilgili yapılacak çalışmanın doğru sıralaması aşağıdakilerden hangisidir?","III-IV-II-I",["II-III-IV-I","IV-III-II-I","III-IV-II-I","II-IV-III-I","I-III-IV-II"]),
      Question("okulgelistirme_ques_Q13","I-Tespit yapılır\nII-İhtiyaçlar belirlenir\nIII-Geliştirme planı hazırlanır\nIV-Veriler toplanır", "Yukarıda verilen okul geliştirme planı hazırlama sürecinin adımları hangisinde doğru verilmiştir?","II-IV-I-III",["I-IV-III-II","I-III-IV-II","II-I-IV-III","II-IV-I-III","I-II-IV-III"]),
      Question("okulgelistirme_ques_Q14","", "Aşağıdakilerden hangisi okul geliştirme sürecini etkileyen faktörlerden biri değildir?","İlçe Milli Eğitim Müdürlüğü sosyal etkinlikleri",["Öğrencilerin kültürel birikimleri","Velilerin tutum ve davranışları","Okulun ve binanın fiziksel yeterlilikleri","Öğretmen kadrosu","İlçe Milli Eğitim Müdürlüğü sosyal etkinlikleri"]),
      Question("okulgelistirme_ques_Q15","", "Okul geliştirme planı hazırlarken ihtiyaç belirleme aşamasında aşağıdakilerden hangisi yapılabilir?","Okul, öğretmen, öğrenci ve velilerin beklentileri dikkate alınır",["Okuldaki duruma ilişkin veriler toplanır","Toplanan verilerle ilgili tespitler yapılır","Okul, öğretmen, öğrenci ve velilerin beklentileri dikkate alınır","Planın değerlendirmesi yapılır","Faaliyetler titizlikle yerine getirilir"]),

    ]),
    TestListHomepageModel("Okul Geliştirme-Test 1",[
      Question("okulgelistirme_ques_Q1","", "Okuldaki mevcut yapıların ve eğitim durumlarının daha da iyiye götürülme sürecine verilen isim aşağıdakilerden hangisidir?","Okul geliştirme",["Okul deneyimi","Okul geliştirme","Okul durumu","Okul yöetimi","Okul yapısı"]),
      Question("okulgelistirme_ques_Q2","", "Okul geliştirme ile ilgili aşaıdakilerden hangisi doğru bir ifade değildir?","Eski durumlar hesaba katılmaz",["Mevcut durumu daha iyiye götürme sürecidir","Eski durumlar hesaba katılmaz","Okulun fiziksel yapısı ve donanımı önemlidir","Veli beklentilerine önem verilir","Hedefler öğrenci yapısına uygun olmalıdır"]),
      Question("okulgelistirme_ques_Q3","", "Aşağıdakilerden hangisi okul geliştirme alanlarına verilebilecek örneklerden değildir?","Okullaştırma oranının arttırılması",["Ders materyali iyileştirmeleri","Eğitim öğretim süreci","Fiziksel yapı iyileştirmeleri","Veliye sunulan hizmetler","Okullaştırma oranının arttırılması"]),
      Question("okulgelistirme_ques_Q4","I-Nitelikli eğitim\nII-Çevrenin okula katılımı\nIII-Başarı düzeyinin arttırılması", "Yukarıdakilerden hangisi veya hangileri okul geliştirme düzeyi ile ilgilidir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
      Question("okulgelistirme_ques_Q5","", "Aşağıdakilerden hangisi okul geliştirmenin konusu değildir?","Erken yaşta evliliğin önüne geçilmesi",["Erken yaşta evliliğin önüne geçilmesi","Akademik başarının arttırılması","Öğretmen gelişiminin sağlanması","Veli-okul işbirliğinin güçlenmesi","Yönetici deneyiminin arttırılması"]),
      Question("okulgelistirme_ques_Q6","Etkili okula ulaşmak için dikkat edilmesi gereken bazı temel noktalar bulunur.", "Aşağıdakilerden hangisi bu temel noktalardan biri değildir?","MEB'e bağlı olması",["Okuldaki öğrenci sayısı","Okulun yönetim yapısı","MEB'e bağlı olması","Okulun gelir/gider durumu","Öğretmen deneyimi"]),
      Question("okulgelistirme_ques_Q7","Bazı okullar mevcut koşulları sebebiyle etkili okul kapsamında sayılmaz.", "Aşağıdakilerden hangisi okulu etkili okul haline getirmek için öğretmenin yapabilecekleri arasında sayılamaz?","Okulun yönetim yapısını değiştirmek",["Aile katılımını sağlamak","Derse katılım oranını arttırmak","Okulun yönetim yapısını değiştirmek","Sosyal etkinlikler ile okulu zenginleştirmek","Öğrenme-öğretme stillerinde çeşitlilik sunmak"]),
      Question("okulgelistirme_ques_Q8","", "Etkili okul yapısının oluşturulmasında aşağıdakilerden hangisi gerekli değildir?","Öğrenci sayısının fazla olması",["Öğretmen yeterliliklerinin fazla olması","Yönetici deneyiminin fazla olması","Okul imkanlarının fazla olması","Öğrenci sayısının fazla olması","Aile katılımının fazla olması"]),
      Question("okulgelistirme_ques_Q9","", "Aşağıdakilerden hangisi okul geliştirme sürecine olumlu katkı sağlamaz?","Ulaşım imkanlarının az olması",["Okul binasının yeterli olması","Velilerin okul ile işbirliği içinde olması","Öğretmen ilgisinin fazla olması","İdareci deneyiminin fazla olması","Ulaşım imkanlarının az olması"]),
      Question("okulgelistirme_ques_Q10","", "Okuldaki ihtiyaçların belirlenerek bunlara ilişkin yapılacak faaliyetlerin planlanması aşağıdakilerden hangisi ile ifade edilir?","Okul geliştirme",["Okul etkinliği","Okul geliştirme","Okul deneyimi","Okul önceliği","Okul görünürlüğü"]),
    ]),
    TestListHomepageModel("Okul Geliştirme-Test 2",[
      Question("okulgelistirme_ques_Q11","", "Aşağıdakilerden hangisi okul geliştirme alanlarına verilebilecek bir örnek olamaz?","Tüm Türkiye'de ders giriş zillerinin aynı olması",["Veliye sunulan hizmetler","Tüm Türkiye'de ders giriş zillerinin aynı olması","Öğretmen-öğrenci imkanlarının iyileştirilmesi","Fiziksel yapı iyileştirmeleri","Ders materyali iyileştirmeleri"]),
      Question("okulgelistirme_ques_Q12","I-Değerlendirme raporunun hazırlanması\nII-Okul geliştirme planının hazırlanması\nIII-İhtiyaçların belirlenmesi\nIV-Verilerin toplanması", "Okul geliştirmesi ile ilgili yapılacak çalışmanın doğru sıralaması aşağıdakilerden hangisidir?","III-IV-II-I",["II-III-IV-I","IV-III-II-I","III-IV-II-I","II-IV-III-I","I-III-IV-II"]),
      Question("okulgelistirme_ques_Q13","I-Tespit yapılır\nII-İhtiyaçlar belirlenir\nIII-Geliştirme planı hazırlanır\nIV-Veriler toplanır", "Yukarıda verilen okul geliştirme planı hazırlama sürecinin adımları hangisinde doğru verilmiştir?","II-IV-I-III",["I-IV-III-II","I-III-IV-II","II-I-IV-III","II-IV-I-III","I-II-IV-III"]),
      Question("okulgelistirme_ques_Q14","", "Aşağıdakilerden hangisi okul geliştirme sürecini etkileyen faktörlerden biri değildir?","İlçe Milli Eğitim Müdürlüğü sosyal etkinlikleri",["Öğrencilerin kültürel birikimleri","Velilerin tutum ve davranışları","Okulun ve binanın fiziksel yeterlilikleri","Öğretmen kadrosu","İlçe Milli Eğitim Müdürlüğü sosyal etkinlikleri"]),
      Question("okulgelistirme_ques_Q15","", "Okul geliştirme planı hazırlarken ihtiyaç belirleme aşamasında aşağıdakilerden hangisi yapılabilir?","Okul, öğretmen, öğrenci ve velilerin beklentileri dikkate alınır",["Okuldaki duruma ilişkin veriler toplanır","Toplanan verilerle ilgili tespitler yapılır","Okul, öğretmen, öğrenci ve velilerin beklentileri dikkate alınır","Planın değerlendirmesi yapılır","Faaliyetler titizlikle yerine getirilir"]),

    ]),
    TestListHomepageModel("Hazırlanıyor",[
      Question("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor", ["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"])
    ]),

       // Question("okulgelistirme_ques_Q16","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q17","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q18","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q19","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q20","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q21","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q22","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q23","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q24","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q25","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q26","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q27","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q28","", "","",["","","","",""]),
    // Question("okulgelistirme_ques_Q29","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q30","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q31","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q32","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q33","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q34","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q35","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q36","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q37","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q38","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q39","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q40","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q41","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q42","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q43","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q44","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q45","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q46","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q47","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q48","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q49","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q50","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q51","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q52","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q53","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q54","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q55","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q56","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q57","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q58","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q59","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q60","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q61","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q62","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q63","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q64","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q65","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q66","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q67","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q68","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q69","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q70","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q71","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q72","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q73","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q74","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q75","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q76","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q77","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q78","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q79","", "", "", ["","","","",""]),
    // Question("okulgelistirme_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<TestListHomepageModel> get okulGelistirme=>_okulGelistirmeList;
}