import 'package:flutter/material.dart';

import '../../model/question.dart';

class OlcmeDegerQuesViewModel extends ChangeNotifier{
  ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
  List<Question> _olcmeDegerList=[
   // Question("olcmedeger_ques_11111111","Hazırlanıyor", "Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("olcmedeger_ques_Q1","I-Türetilmiş Ölçme\nII-Doğrudan Ölçme\nIII-Dolaylı Ölçme", "Yukarıdakilerden hangileri ölçmenin türlerindendir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    Question("olcmedeger_ques_Q2","", "Ölçülmek istenen değişkenin yapısı, doğrudan gözleme uygun olmadığı için başka bir değişken ya da özellik yardımıyla ölçülmesine ne ad verilir?","Dolaylı Ölçme",["Model ile Ölçme","Doğrudan Ölçme","Türetilmiş Ölçme","Dolaylı Ölçme","Yapısal Ölçme"]),
    Question("olcmedeger_ques_Q3","Ölçme sonuç ifadesi herkesin üzerinde uzlaştığı ….. ile yapılır. Ölçme de …… kullanılması ile kişiler arası iletişim ve yorumlama işlemleri kolaylaşır. Ölçme ile ilgili objektiflik sağlanmış olur.", "Noktalı yerlere gelmesi gereken ifade aşağıdakilerden hangisidir?","Birim",["Ölçek","Ölçüm","Birim","İzomorf","Homomorf"]),
    Question("olcmedeger_ques_Q4","", "Aşağıdakilerden hangisi bir ölçek türü değlidir?","Geri Dönüt Ölçeği",["Sıralama Ölçeği","Eşit Aralıklı Ölçek","Oranlı Ölçek","Sınıflama Ölçeği","Geri Dönüt Ölçeği"]),
    Question("olcmedeger_ques_Q5","", "Zeka, tutum ve ilgili gibi kavramların ölçülmesinde hangi ölçme yöntemi kullanılabilir?","Dolaylı Ölçme",["Dolaylı Ölçme","Doğrudan Ölçme","Objektif Ölçme","Türetilmiş Ölçme","Dolaylı Ölçme"]),
    Question("olcmedeger_ques_Q6","'Atatürk ortaokulundan Ahmet LGS sınavında üçüncü oldu.'", "Bu ifade hangi tür ölçek kullanılarak belirlenmiştir?","Sıralama Ölçeği",["Eşit Aralıklı Ölçek","Sıralama Ölçeği","Oranlı Ölçek","Sınıflama Ölçeği","Akran Başarı Ölçeği"]),
    Question("olcmedeger_ques_Q7","Ayşe 80 adet oyun figürüne sahip olduğunu belirtiyor.", "Bu durumda Ayşe ne tür bir ölçme işlemi yapmıştır?","Doğrudan Ölçme",["Model ile Ölçme","Sayısal Ölçme","Doğrudan Ölçme","Dolaylı Ölçme","Yapısal Ölçme"]),
    Question("olcmedeger_ques_Q8","", "Sınıfımızda 13 kişi kahverengi gözlü, 11 kişi siyah gözlü ve 3 kişi mavi gözlüdür.’ diyen bir öğrenci ölçme işleminde hangi tür ölçek kullanmıştır?","",["Sıralama Ölçeği","Eşit Aralıklı Ölçek","Oranlı Ölçek","Sınıflama Ölçeği","Eşit Aralıklı Ölçeği"]),
    Question("olcmedeger_ques_Q9","", "Aşağıdaki hangi ölçek türü ikilisinde sıfır değerinin bir anlamı yoktur?","Sınıflama-Sıralama",["Sınıflama-Sıralama","Eşit Aralıklı-Sıralama","Sınıflama-Oranlı","Oranlı-Eşit Aralıklı","Sıralama-Oranlı"]),
    Question("olcmedeger_ques_Q10","", "Aşağıdakilerden hangisi doğrudan (temel) ölçmedir?","",["Pazarda terazi ile elma ağırlıklarının ölçülmesi","Hava sıcaklığının termometre ile ölçülmesi","İş yerindeki kişilerin mesleki tükenmişlik seviyelerinin ölçülmesi","Manavın reyondaki karpuzları sayması","İle ait nüfus yoğunluğunun ölçülmesi"]),
   // Question("olcmedeger_ques_Q11","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q12","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q13","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q14","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q15","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q16","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q17","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q18","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q19","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q20","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q21","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q22","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q23","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q24","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q25","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q26","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q27","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q28","", "","",["","","","",""]),
   // Question("olcmedeger_ques_Q29","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q30","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q31","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q32","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q33","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q34","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q35","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q36","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q37","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q38","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q39","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q40","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q41","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q42","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q43","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q44","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q45","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q46","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q47","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q48","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q49","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q50","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q51","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q52","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q53","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q54","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q55","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q56","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q57","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q58","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q59","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q60","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q61","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q62","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q63","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q64","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q65","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q66","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q67","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q68","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q69","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q70","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q71","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q72","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q73","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q74","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q75","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q76","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q77","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q78","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q79","", "", "", ["","","","",""]),
   // Question("olcmedeger_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get ogrenOgretSurec=>_olcmeDegerList;
}