import 'package:flutter/material.dart';

import '../../model/question.dart';

class OzelEgitimQuesViewModel extends ChangeNotifier{
  List<Question> _ozelEgitimList=[
    Question("eo_Q45","", "Aşağıdakilerden hangisi rehberlik hizmetinin ilkelerinden değildir?", "Sorunlu öğrencilere yöneliktir", ["Gönüllülük esastır","İnsana saygı esastır","İşbirliği gerektirir","Sorunlu öğrencilere yöneliktir","Eğitimin ayrılmaz parçasıdır"]),
    Question("eo_Q46","", "Aşağıdakilerden hangisi rehberlik hizmeti ilkelerinden değildir?", "Her okulda rehberlik hizmeti olmamalıdır", ["Koruyucudur","Okul, aile ve çevreyi ilgilendirir","Her okulda rehberlik hizmeti olmamalıdır","Yaşam boyu yararlanılabilinir","Örgütlenmiştir"]),
    Question("eo_Q47","", "Aşağıdakilerden hangisi Rehberlik ve Psikolojik Danışmalıkta yaralanılan bilim dallarından değildir?", "Uzay bilimi", ["Psikoloji","Sosyoloji","Eğitim Bilimi","Ekonomi","Uzay bilimi"]),
    Question("eo_Q48","", "Aşağıdakilerden hangisi rehberliğin temel taşlarından değildir?", "Her öğrenci geliştirilemez", ["Bireye yardım etme sürecidir","Her öğrenci geliştirilemez","Bilimseldir","Profesyoneldir","Bireyin kendini gerçekleştirmesini sağlar"]),
    Question("eo_Q49","", "Çocukların uyum sorunlarının nedenini bilmek için yapılan rehberlik türü aşağıdakilerden hangisidir?", "Uyum Sağlayıcı Rehberlik", ["Önleyici Rehberlik","Geliştirici Rehberlik","Ayarlayıcı Rehberlik","Yöneltici Rehberlik","Uyum Sağlayıcı Rehberlik"]),
    Question("eo_Q50","", "Öğrencileri ilgi duyduğu alana yönlendiren rehberlik aşaıdakilerden hangisidir?", "Yöneltici Rehberlik", ["Önleyici Rehberlik","Geliştirici Rehberlik","Ayarlayıcı Rehberlik","Yöneltici Rehberlik","Uyum Sağlayıcı Rehberlik"]),
    Question("eo_Q52","", "Olumsuz durumları ortaya çıkmadan gerekli tedbirleriin alındığı rehberlik türü aşağıdakilerden hangisidir?", "Önleyici Rehberlik", ["Önleyici Rehberlik","Geliştirici Rehberlik","Ayarlayıcı Rehberlik","Yöneltici Rehberlik","Uyum Sağlayıcı Rehberlik"]),
    Question("eo_Q53","", "Eğitsel Rehberlikte aşağıdakilerden hangisi ile ilgili öğrenciye yardımcı olunmaz?", "Meslek seçimi", ["Okul seçme","Okula uyum","Zamanı iyi kullanma","Verimli ders çalışma","Meslek seçimi"]),
    Question("eo_Q54","", "Öğrencinin ilgi ve yeteneğine uygun mesleğe yöneldiği mesleki seçim devresi aşağıdakilerden hangisidir?", "Gerçekçi Devre", ["Fantezi Devre","Geçici Devre","Gerçekçi Devre","Hayali Devre","Gelişen Devre"]),
    Question("eo_Q55","", "Çocukların meslekleri taklit ettiği mesleki seçim devresi aşağıdakilerden hangisidir?", "Fantezi Devre", ["Fantezi Devre","Geçici Devre","Gerçekçi Devre","Hayali Devre","Gelişen Devre"]),
    Question("eo_Q56","", "Aşağıdakilerden hangisi meslek seçiminde birey hakkında dikkat edileceklerden değildir?", "Kardeş sayısı", ["Fiziksel özellikler","İlgisi","Yetenekleri","Kardeş sayısı","Yaşantıları"]),
    Question("eo_Q57","", "Grup rehberliği ile ilgili aşağıdakilerden hangisi yanlıştır?", "Danışman kendi fikrini gruba açıklamalı", ["Belli bir grupla yürütülür","Her öğrenciye saygı duyulmalıdır","Her öğrencinin katılımı sağlanmalıdır","Meslek tannıma, ders çalışma gibi konularda yardıcı olunur","Danışman kendi fikrini gruba açıklamalı"]),
    Question("eo_Q58","", "Yüksek öğretimde verilen rehberlik hizmetinin amaçları aşağıdakilerden hangisinde yanlış verilmiştir?", "Okuma-yazma", ["Barınma","Okuma-yazma","Başarı","Beslenme","Mesleğe hazırlama"]),
    Question("eo_Q59","", "Aşağıdakilerden hangisi rehberlik hizmetinin amaçlarından değildir?", "Yazı yazmayı öğrenme", ["Öğrencinin kendini tanıması","Öğrencinin meslekleri tanıması","Problem çözme becerilerinin gelişmesi","Yazı yazmayı öğrenme","Doğru karar verme"]),
    Question("eo_Q60","", "Okullarda öğrenci yerleştirmeyi sağlayan rehberlik servisi aşağıdakilerden hangisidir?", "Yerleştirme ve izleme", ["Öğrenci tanıma servisi","Psikolojik danışma servisi","Grup rehberliği servisi","Mesleki bilgilendirme servisi","Yerleştirme ve izleme"]),
    Question("eo_Q61","", "Öğrencilerin gizil güçlerini ortaya çıkaran rehberlik servisi aşağıdakilerden hangisidir?", "Öğrenci tanıma servisi", ["Öğrenci tanıma servisi","Psikolojik danışma servisi","Grup rehberliği servisi","Mesleki bilgilendirme servisi","Yerleştirme ve izleme"]),
    Question("eo_Q62","", "Okula uyum konularında öğrenciye destek olunan rehberlik servisi aşağıdakilerden hangisidir?", "Psikolojik danışma servisi", ["Öğrenci tanıma servisi","Psikolojik danışma servisi","Grup rehberliği servisi","Mesleki bilgilendirme servisi","Yerleştirme ve izleme"]),
    Question("eo_Q63","", "Aşağıdakilerden hangisi rehberlik servisinin görevlerinden değildir?", "Boş dersi doldurmak", ["Rehberlik hizmetlerini yürütmek","İhtiyaç duyulan araç-gereci sağlamak","Boş dersi doldurmak","Yapılacak etkinlikler için önerilerde bulunmak","Mesleki değerlendirmelerde bulunmak"]),
    Question("eo_Q64","", "Aşağıdakilerden hangisi Rehberlik ve Psikolojik Danışma yürütme komisyonunda bulunmaz?", "Sınıf başkanları", ["Sınıf başkanları","Psikolojik danışman","Disiplin Kurulundan bir kişi","Okul öncesi öğrenci temsilcisi","Okul aile birliğinden bir kişi"]),
    Question("eo_Q65","", "Aşağıdakilerden hangisi Rehberlik ve Psikolojik Danışma yürütme komisyonunun görevlerinden birisi değildir?", "Sınıf rehber öğretmenlerini belirleme", ["Yıllık rehberlik planlarının uygulanmasını sağlama","Mesleki rehberlik çalışmalarını uygulama","Eğitim ortamındaki kişilerin işbirliğini sağlama","Sınıf rehber öğretmenlerini belirleme","Rehberlik hizmetlerinde ortaya çıkan sorunları inceleme"]),
    Question("eo_Q66","", "Aşağıdakilerden hangisi rehberlik çalışmalarında okul müdürünün görevlerinden biri değildir?", "Rehberlik etkinliklerine fiilen katılma", ["Sınıf rehber öğretmenlerini görevlendirme","Rehberlik yürütme komisyonunu kurma","Yıllık rehberlik planlarının uygulanmasını sağlama","Yeni gelen öğrencinin gelişim dosyasını rehberlik servisine iletme","Rehberlik etkinliklerine fiilen katılma"]),
    Question("eo_Q67","", "Aşağıdakilerden hangisi rehberlik çalışmalarında okul müdür yardımcısının görevlerinden biri değildir", "Yürütme komisyonunu kurar", ["Yürütme komisyonu toplantısına katılır","Yürütme komisyonunu kurar","Okul müdürünün vereceği görevleri yapar","Sorumlu olduğu sınıftaki öğrenci sorunlarını rehberlik servisine iletir","Sorumlu olduğu sınıftaki öğrencilerin bilgi ve belgelerini rehberlik servisine iletir"]),
    Question("eo_Q68","", "Aşağıdakilerden hangisi Rehberlik çalışmalarında koordinatör psikolojik danışmanın görevlerinden biri değildir?", "Rehberlik yürütme komisonunu kurar", ["Rehberlik programlarını okul müdürüne iletir","Rehberlik programları hakkında öğretmenler kuruluna bilgi verir","Rehberlik hizmetleri etkinliklerine fiilen katılır","Rehberlik yürütme komisonunu kurar","Okul yönetimi ile rehberlik servisi arasında iletişim sağlar"]),
    Question("eo_Q69","", "Aşağıdakilerden hangisi psikolojik danışmanın görevlerinden biri değildir?", "Sınıf rehber öğretmenleri görevlendirir", ["Uzmanlık gerektiren rehberlik etkinliklerini sınıflarda uygular","Rehberlik hizmetlerine ilişkin komisyonlara katılır","Sınıf rehber öğretmenleri görevlendirir","Sınıf rehber öğretmenleri görevlendirir","Bireysel rehberlik hizmetlerini yürütür"]),
    Question("eo_Q70","", "Aşağıdakilerden hangisi sınıf rehber öğretmeninin görevlerinden biri değildir?", "Yıllık rehberlik planını hazırlar", ["Yıllık rehberlik planını hazırlar","Sınıfın yıllık rehberlik programını uygular","Okul müdürünün sınıf rehberliği ile ilgili vereceği görevleri yapar","Öğrencilerin özel bilgilerinin gizliliğini korur","Rehberlik raporlarını ders yılı sonunda rehberlik servisine iletir"]),
    Question("eo_Q71","", "Aşağıdakilerden hangisi öğrenciyi tanıma tekniği olan testlerin iyi olduğunu gösteren özelliklerden değildir?", "Sebjektiflik", ["Güvenirlik","Geçerlilik","Kullanışlılık","Sebjektiflik","Ekonomiklik"]),
    Question("eo_Q72","", "Aşağıdakilerden hangisi öğrenciyi tanımaya yarayan test dışı tekniklerden değildir?", "İlgi envanterleri", ["Görüşme","Anket","İlgi envanterleri","Gözlem","Anekdot"]),
    Question("eo_Q73","", "Aşağıdakilerden hangisi Öğrencilerin özgeçmişlerini rapor eden tes dışı tekniktir?", "Otobiyografi", ["Gözlem","Anekdot","Otobiyografi","Anket","Görüşme"]),
    Question("eo_Q74","", "Aşağıdakilerden hangisi öğrencinin diğer kişiler tarafından nasıl görüldüğünü gösteren tekniktir?", "Kimdir bu", ["Anket","Otobiyografi","Kimdir bu","Veli toplantısı","Anekdot"]),

  //Question("ozelegitim_ques_Q1","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q2","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q3","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q4","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q5","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q6","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q7","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q8","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q9","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q10","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q11","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q12","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q13","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q14","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q15","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q16","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q17","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q18","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q19","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q20","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q21","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q22","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q23","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q24","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q25","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q26","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q27","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q28","", "","",["","","","",""]),
  //Question("ozelegitim_ques_Q29","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q30","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q31","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q32","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q33","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q34","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q35","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q36","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q37","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q38","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q39","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q40","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q41","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q42","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q43","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q44","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q45","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q46","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q47","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q48","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q49","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q50","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q51","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q52","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q53","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q54","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q55","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q56","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q57","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q58","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q59","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q60","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q61","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q62","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q63","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q64","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q65","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q66","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q67","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q68","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q69","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q70","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q71","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q72","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q73","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q74","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q75","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q76","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q77","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q78","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q79","", "", "", ["","","","",""]),
  //Question("ozelegitim_ques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get ozelEgitim=>_ozelEgitimList;
}