import 'package:flutter/material.dart';

import '../../model/question.dart';

class SosyalDuygusalQuesViewModel extends ChangeNotifier{
  List<Question> _sosyalDuygusalList=[
    ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),

    Question("sosyalduygusalques_Q1","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q2","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q3","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q4","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q5","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q6","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q7","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q8","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q9","", "","",["","","","",""]),
    Question("sosyalduygusalques_Q10","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q11","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q12","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q13","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q14","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q15","", "","",["","","","",""]),

    // Question("sosyalduygusalques_Q16","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q17","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q18","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q19","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q20","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q21","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q22","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q23","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q24","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q25","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q26","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q27","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q28","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q29","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q30","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q31","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q32","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q33","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q34","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q35","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q36","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q37","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q38","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q39","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q40","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q41","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q42","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q43","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q44","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q45","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q46","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q47","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q48","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q49","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q50","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q51","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q52","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q53","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q54","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q55","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q56","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q57","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q58","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q59","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q60","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q61","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q62","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q63","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q64","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q65","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q66","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q67","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q68","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q69","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q70","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q71","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q72","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q73","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q74","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q75","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q76","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q77","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q78","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q79","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get sosyalDuygusal=>_sosyalDuygusalList;
}