import 'package:flutter/material.dart';

import '../../model/question.dart';

class SosyalDuygusalQuesViewModel extends ChangeNotifier{
  List<Question> _sosyalDuygusalList=[
    ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),

    Question("sosyalduygusalques_Q1","", "Aşağıdaki kavramlardan hangisi sosyal duygusal becerilerle ilgilidir?", "Eğitim", ["Öğretim","Bilişsel Stil","Sosyal Olgunluk","Sosyal Uyum","Eğitim"]),
    Question("sosyalduygusalques_Q2","I-Sosyal Duygusal Beceriler Akademik Başarıyı Artırır\nII-Sosyal Duygusal Beceriler Öğrenilebilir\nIII-Araştırmacılar Tarafından Sosyal Duygusal Gelişim Akademik Başarıdan Daha Ön Planda Tutulmaktadır", "Sosyal Duygusal Beceriler ile ilgili verilen cümlelerden hangisi ya da hangileri doğrudur?", "I-II", ["II-III","Yalnız II","I-III","I-II","I-II-III"]),
    Question("sosyalduygusalques_Q3","", "Sosyal duygusal öğrenme farkındalığı yaratan ve okul tabanlı uygulamalar geliştiren Sosyal Duygusal Öğrenme Gelişimi İş Birliği’nin kısaltması hangi şıkta doğru olarak verilmiştir?", "CASEL", ["CASEL","CASTEL","CASTLE","CALES","CELAS"]),
    Question("sosyalduygusalques_Q4","", "CASEL sosyal duygusal öğrenme gelişimi iş birliği paydaşlarından hangisi yanlış verilmiştir?", "Okul Zümreleri", ["Veliler","Eğitmenler","Öğrenciler","Okul Zümreleri","Eğitim Politikacıları"]),
    Question("sosyalduygusalques_Q5","", "Sosyal duygusal öğrenme temel yeterliliklerinden hangisi yanlış verilmiştir?", "Öz Otorite", ["Öz Fakındalık","Öz Yönetim","Öz Otorite","Sosyal Farkındalık","İlişki Becerileri"]),
    Question("sosyalduygusalques_Q6","", "Değerlendirme, dönüt alma ve izleme, durumları analiz etme hangi sosyal duygusal öğrenme yeterliliğinin alt başlıklarıdır? ", "Sorumlu Karar Verme", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q7","", "Bireyin kendi duygularını, düşüncelerini, güçlü ve zayıf yönlerini fark etmesi hangi sosyal duygusal öğrenme yeterliliğidir? ", "Öz Farkındalık", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q8","", "Bireyin kendi eylemlerini düzenleme, kontrol etme ve dengeleme yeteneği hangi sosyal duygusal öğrenme yeterliliği kapsamında değerlendirilir? ", "Öz Yönetim", ["Öz Yönetim","Sorumlu Karar Verme","Sosyal Farkındalık","İletişim Becerileri","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q9","", "Farklı bakış açılarını anlama ve duygudaşlık kurabilme becerisi hangi sosyal duygusal öğrenme yeterliliği kapsamında değerlendirilir? ", "Sosyal Farkındalık", ["Öz Yönetim","Sosyal Farkındalık","Sorumlu Karar Verme","İletişim Becerileri","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q10","", "Farklı kültürlerden insanlarla sağlıklı ilişkiler kurma ve bu ilişkileri sürdürebilme becerisi hangi sosyal duygusal öğrenme yeterliliği kapsamında değerlendirilir?", "İlişki Becerileri", ["Öz Yönetim","Sosyal Farkındalık","İlişki Becerileri","İletişim Becerileri","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q11","", "Bireyin kendi düşünce ve normlarını dikkate alarak seçimler yapması hangi sosyal duygusal öğrenme yeterliliği kapsamında değerlendirilir? ", "Sorumlu Karar Verme", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q12","", "Takım çalışması, sosyal etkileşim ve katılım hangi sosyal duygusal öğrenme yeterliliği ile ilgilidir?", "İlişki Becerileri", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q13","", "Duygudaşlık, başkalarına saygı, farklılıkları kucaklama hangi sosyal duygusal öğrenme yeterliliği ile ilgilidir?", "Sosyal Farkındalık", ["İlişki Becerileri","Sorumlu Karar Verme"," Öz Yönetim","Sosyal Farkındalık","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q14","", "Dürtülerin kontrolü, öz motivasyon, stres yönetimi hangi sosyal duygusal öğrenme yeterliliği ile ilgilidir? ", "Öz Yönetim", ["İlişki Becerileri","Sorumlu Karar Verme","Öz Yönetim","Sosyal Farkındalık","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q15","", "Duygularını isimlendirme, güçlü yönlerini bilme hangi sosyal duygusal öğrenme yeterliliği ile ilgilidir? ", "Öz Farkındalık", ["İlişki Becerileri","Sorumlu Karar Verme","Öz Yönetim","Sosyal Farkındalık","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q16","", "Sosyal Duygusal Öğrenme kavramının ortaya çıkmasını sağlayan gelişme aşağıdakilerden hangisidir?", "Duygusal zeka çalışmalarının olumlu sonuçlar vermesi", ["İşbirliğine dayalı öğrenme çalışmalarının olumlu sonuçlar vermesi","Duygusal zeka çalışmalarının olumlu sonuçlar vermesi","Bilişsel stiller ile ilgili çalışmaların olumlu sonuçlar vermesi","Gelişim psikolojisi çalışmalarının olumlu sonuçlar vermesi","Öğrenme psikolojisi çalışmalarının olumlu sonuçlar vermesi"]),
    Question("sosyalduygusalques_Q17","", "Bireyin doğumuyla başlayıp ölümüyle sonlanan, başkaları ile ilişkiler kurduğu ve topluma uyum sağladığı sürece ne ad verilir?", "Sosyalleşme", ["Sosyal Duygusal Öğrenme","Sosyal Gelişme","Sosyalleşme","Sosyal Beceri","İletişim"]),
    Question("sosyalduygusalques_Q18","", "Bireyin stres durumunun farkında olması, bu durumun davranışlarını nasıl etkilediğini anlaması hangi sosyal duygusal öğrenme yeterliliği ile açıklanabilir?", "Öz Farkındalık", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q19","", "Bireyin iş hayatında resmi ve özel hayatında duygusal ilişkilerde başarılı olması hangi sosyal duygusal öğrenme yeterliliği ile açıklanabilir?", "İlişki Becerileri", ["İlişki Becerileri","Sorumlu Karar Verme","Sosyal Farkındalık","Öz Yönetim","Öz Farkındalık"]),
    Question("sosyalduygusalques_Q20","", "Sosyal duygusal öğrenme temel yeterliliklerinden hangisi yanlış verilmiştir?", "Sosyal Uyumsama", ["Öz Fakındalık","Öz Yönetim","Sosyal Farkındalık","Sosyal Uyumsama","İlişki Becerileri"]),
    // Question("sosyalduygusalques_Q21","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q22","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q23","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q24","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q25","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q26","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q27","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q28","", "","",["","","","",""]),
    // Question("sosyalduygusalques_Q29","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q30","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q31","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q32","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q33","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q34","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q35","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q36","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q37","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q38","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q39","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q40","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q41","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q42","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q43","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q44","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q45","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q46","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q47","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q48","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q49","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q50","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q51","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q52","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q53","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q54","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q55","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q56","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q57","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q58","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q59","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q60","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q61","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q62","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q63","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q64","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q65","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q66","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q67","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q68","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q69","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q70","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q71","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q72","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q73","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q74","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q75","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q76","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q77","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q78","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q79","", "", "", ["","","","",""]),
    // Question("sosyalduygusalques_Q8","", "", "", ["","","","",""]),
  ];
  List<Question> get sosyalDuygusal=>_sosyalDuygusalList;
}