import '../../../model/info_card_item.dart';
import '../../../model/info_card_model.dart';


class CografyaInfoViewModel {
  List<InfoCardModel> _cografyaInfoCard = [
    InfoCardModel("Türkiye'nin Konumu", [
      InfoCardItem("cografya_Info_1","Coğrafi Konum-1","-Dünya üzerindeki konuma Coğrafi Konum denir.\n-Türkiye; Avrupa, Asya ve Afrika arasında köprüdür.\n-Doğu, batı arasında bağlantı yeridir.\n-İpek, Baharat yolu buradan geçer.\n-Eski uygarlıkların izlerini taşır.",),
      InfoCardItem("cografya_Info_2","Coğrafi Konum-2","-Üç tarafı denizlerle çevrilidir.\n-İklim çeşitliliği vardır.\n-Tarihi ve doğal güzellikleri mevcuttur.\n-İstanbul ve Çanakkale Boğazları bulunur.\n-Yeraltı ve yer üstü kaynakları bakımından zengindir.\n-Batıdan doğuya yükseklik artar.",),
      InfoCardItem("cografya_Info_3","Matematik Konum-1","-Enlem ve boylama göre bulunduğumuz yere denir.\n-Türkiye; başlangıç meridyeninin doğusunda, ekvatorun kuzeyindedir.\n-26°-45° doğu meriyeni, 36°-42° kuzey paralelleri arasındadır.\n-Meridyenler arası zaman farkı 4 dakikadır.",),
      InfoCardItem("cografya_Info_4","Matematik Konum-2","-En batı ile en doğu arası 76 dakikadır.\n-En batısı Gökçeada, \n-En doğusu Türkiye Ermenistan İran ve Nahcivan sınırlarının kavşak noktası\n-En kuzeyi Sinop İnce Burun,\n-En güneyi Hatay Beysen köyü",),
      InfoCardItem("cografya_Info_5","Matematik Konum-3","-Kuzey-Güney arasında 6 eylem vardır.\n-Kuzey-güney arası 600 km iken doğu-batı arası 1500 km'dir.",),
      InfoCardItem("cografya_Info_6","Türkiye'nin Sınırları","Komşu ülkeler;\n-Yunanistan, Bulgaristan, Ermenistan, Irak, Gürcistan, Suriye, Nahçivan.\n\nGümrük Kapıları;\n-Yunanistan-> İpsala\n-Bulgaristan-> Kapıkule\n-İran-> Gürbulak, Esendere\n-Suriye-> Cilvegözü, Öncüpınar\n-Ermenistan-> Akkaya",),
    ]),
    InfoCardModel("Türkiye'nin Dağları", [
      InfoCardItem("cografya_Info_7","Kuzey Anadolu Dağları","-Sarp ve yüksektir.\n-En yüksek dağlar burada bulunur.\n-Kaçkar Dağı, Doğu Karadeniz'in en yüksek dağıdır.\n-Küre, Giresun, Canik, Kalkanlı, Gümüşhane, Rize, Trabzon, Köroğlu, Ilgaz, Yıldız, Deveci, Mescid, Çamlıbel dağları bulunur.",),
      InfoCardItem("cografya_Info_8","Güney Anadolu Dağları","Batı Toroslar;\n-Dedegöl, Geyik, Sultan, Ak ve Boz Dağlar.\nOrta Toroslar;\n-Binboğa, Tahtalı, Bolkar, Aladağ",),
      InfoCardItem("cografya_Info_9","Güneydoğu Anadolu Dağları","Malatya, Bitlis, Hakkari, Güneydağlar, Cilo",),
      InfoCardItem("cografya_Info_10","Doğu Anadolu Dağları","Tahtalı, Aras, Karasu, Mercan, Allahuekber, Bingöl, Şakşak, Kargopazarı, Ağrı, Süphan, Tendürek, Neptün, Şerafettin",),
      InfoCardItem("cografya_Info_11","İç Anadolu Dağları","Sundiken, Sultan, İdris, Elmadağ, Ayaş, Çamlıbel, Akdağlar, Hınzır, Erciyes, Hasan, Karacadağ, Karadağ, Melendiz",),
      InfoCardItem("cografya_Info_12","Batı Anadolu Dağları","Madra, Bozdağlar, Aydın, Yunt, Menteşe, Kazdağlar, Biga, Eğrigöz, Sandıklı, Murat, Uludağ",),
      InfoCardItem("cografya_Info_13","Oluş Şekillerine Göre Dağlar","-Orojenik Hareketlerle Meydana Gelenler,\n-Volkanik Dağlar",),
      InfoCardItem("cografya_Info_14","Orojenik Hareketlerle Meydana Gelenler-1","KIVRIM DAĞLARI\n-Esnek tabakaların kıvrılarak yükselmesiyle oluşur.\n-Doğu Anadolu Dağları, Toroslar, Karadeniz Dağları örnek gösterilebilir.",),
      InfoCardItem("cografya_Info_15","Orojenik Hareketlerle Meydana Gelenler-2","KIRIK DAĞLAR\n-Kıvrılma özelliğinin kaybedilip kırılmasıyla oluşan fayların çöken kısımlarına GRABEN, yükselen kısımlarına HORST denir.\n\nHORST DAĞLARI\n-Menteşe, Aydın, Kaz, Madra, Nur, Boz, Yunt",),
      InfoCardItem("cografya_Info_16","Volkanik Dağlar","Yer altındaki mağmanın yeryüzüne çıkmasıyla oluşur.\n-Erciyes, Hasan, Karacadağ, Karadağ, Melendiz, Ağrı, Kula, Uludağ\n\nNOT: Krateri olmayan tek volkanik dağ ULUDAĞ'dır.",),
    ]),
    InfoCardModel("Türkiye'nin Ovaları", [
      InfoCardItem("cografya_Info_17","Ovaların Tanımı ve Çeşitleri","-Vadilerler parçalanmamış geniş düzlüklere denir.\n\nOvalar;\n-Yüksekliklerine göre(Kıyı, iç)\n-Oluşumuna göre(Tektonik, Delta, Karstik, Volkanik) olarak gruplandırılabilir.",),
      InfoCardItem("cografya_Info_18","Kıyı Ovaları","-İç oavalara göre daha verimlidir.\n-Ürün çeşitliliği iç ovalardan fazladır.\n-Çarşamba, Bafra, Çukurova, Silifke, Menderes, Amik, Gediz, Bakırçay oavaları kıyı ovadır.",),
      InfoCardItem("cografya_Info_19","İç Ovalar","Konya, Kayseri, Ereğli, Harran, Çivril, Develi, Bozova ovaları örnektir.",),
      InfoCardItem("cografya_Info_20","Tektonik Ovalar","-Çöküntü ovalarıdır.\n-Fay hatları üzer,nde bulunur.\n-Erbaa, Zile, Erzurum, Iğdır, Ağrı, Aydın, Tire örnektir.\n-En çok tektonik ova bulunur.",),
      InfoCardItem("cografya_Info_21","Delta Ovaları","-Akarsu alüvyonu çok taşımalıdır.\n-Kıyı derinliği azdır.\n-Kıyıda dalga, akıntı, gelgit olmamalıdır.\n-Bafra, Çarşamba, Küçük Menderes, Büyük Menderes, Bakırçay, Gediz, Çukurova, Silifke örnektir.",),
      InfoCardItem("cografya_Info_22","Karstik Ovalar","Kireç taşı, alçı taşı gibi su ile kolay eriyen kayaçların bulunduğu yerdeki ovalardır.\n-Akdeniz'de Tefenni, Kestel, Korkuteli, Acıpayam, Elmalı\n-Ege'de Tavas, Çivril, Muğla ovaları bulunur.",),
      InfoCardItem("cografya_Info_23","Volkanik Ovalar","-Tektonik çukurların lavlarla dolmasıyla oluşur.\n-Develi, Kayseri ovaları örnektir.",),
    ]),
    InfoCardModel("Türkiye'nin Platoları", [
      InfoCardItem("cografya_Info_24","Platonun Tanımı","-Akarsular tarafından derince yarılmış, çevresine göre yğksek, hafif engebeli geniş düzlüklere denir.\n-En çok İç Anadolu Bölgesinde görülür.\n-Kuru tarım yapılır.",),
      InfoCardItem("cografya_Info_25","İç Anadolu Platoları","Haymana, Cihanbeyli, Obruk, Uzunyayla, Bozok platoları bulunur.",),
      InfoCardItem("cografya_Info_26","Doğu Anadolu Platoları","Kars, Ardahan, Erzurum platoları bulunur.",),
      InfoCardItem("cografya_Info_27","Akdeniz Platoları","Taşeli ve Teke platoları bulunur.",),
      InfoCardItem("cografya_Info_28","Marmara Platoları","Çatalca-Kocaeli, Biga ve Gelibolu platoları bulunur.",),
      InfoCardItem("cografya_Info_29","Doğu Anadolu Platoları","Gaziantep, Adıyaman, Şanlıurfa ve Diyarbakır platoları bulunur.",),
      InfoCardItem("cografya_Info_30","Ege Platoları","Yazlıkaya ve Uşak platoları bulunur.",),
      InfoCardItem("cografya_Info_31","Karadeniz Platoları","Giresun dağları üzerindeki platolar, Perşembe yaylası bulunur.",),
    ]),
    InfoCardModel("Akarsular-1", [
      InfoCardItem("cografya_Info_32","Akarsu Nedir?","Kaynaklardan çıkan veya kar ve buzulların erimesiyle belirli bir yatakta akan, sonra denize veya göle dökülen sulara denir.",),
      InfoCardItem("cografya_Info_33","Akarsu Kaynağı","Akarsuyun doğduğu yere denir.",),
      InfoCardItem("cografya_Info_34","Akarsu Ağzı","Akarsuyun denize döküldüğü yere denir.",),
      InfoCardItem("cografya_Info_35","Akarsu Yatağı","Kaynak ağız arasında, suyun içinden aktığı çukurluktur.",),
      InfoCardItem("cografya_Info_36","Akarsu Debisi","Akarsuyun herhangi bir yerinden saniyede geçen suyun metreküp cinsinden değeridir.",),
      InfoCardItem("cografya_Info_37","Akarsu Rejimi","Yıl içinde akarsu debisinde görülen değişikliktir.",),
      InfoCardItem("cografya_Info_38","Akarsuların Aşındırma Şekilleri","-Vadi\n-Menderes\n-Dev Kazanı\n-Kırgıbayır\n-Peribacaları\n-Platolar\n-Peneplen",),

    ]),InfoCardModel("Akarsular-2", [
         InfoCardItem("cografya_Info_39","Vadi","-Çentik Vadi\n-Geniş Tabanlı Vadi\n-Geniş Tabanlı Vadi\n-Kanyon Vadi\n-Boğaz Vadi\n-Yastık Yamaçlı Vadi",),
      InfoCardItem("cografya_Info_40","Çentik Vadi","-Doğu Anadolu-Doğu Karadeniz\n-Derine aşındırma fazladır.\n-En sık görülen vadidir.\n-Engebenin çok olduğu yerlerde görülür.",),
      InfoCardItem("cografya_Info_41","Geniş Tabanlı Vadi","-Eğim azdır.\n-Yan aşındırma çoktur.\n-Akarsuyun denize yakın yerinde oluşur.\n-Marmara-Kıyı Ege en çok görülen yerlerdin.",),
      InfoCardItem("cografya_Info_42","Kanyon Vadi","Karstik arazizde görünür.\n-Akdeniz Bölgesinde görülür.\n-Yamaçların farklı aşınmasıyla oluşur.",),
      InfoCardItem("cografya_Info_43","Boğaz Vadi","-Sıradağların üzerinde enine yarılarak oluşur.\n-Akdeniz ve Karadeniz bölgelerinde görülür.",),
      InfoCardItem("cografya_Info_44","Yatık Yamaçlı Vadi","Menderesler örnek olarak verilebilir.",),
      InfoCardItem("cografya_Info_45","Menderes","Menderes yapan akarsuda;\n-Yatak eğimi azdır.\n-Akış hızı düşüktür.\n-Enerji potansiyeli dazdır.\n-Büyük ve Küçük Menderes örnektir.\n-Akarsuların yan aşındırma yaparak oluşturduğu kıvrımlardır.",),
      InfoCardItem("cografya_Info_46","Dev Kazanı","-Şelalelerin oluşturduğu derin çukurlardır.\n-Doğu Anadolu'da görülür.",),
      InfoCardItem("cografya_Info_47","Kırgıbayır","Dağ yüzeyinin aşınmasıyla oluşur.\n-Arazi girintili-çıkıntılı görünür.\n-Oluşması için şiddetli yağmur, cılız bitki örtüsü gerekir.\n-İç Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_48","Peribacaları","Sel sularının farklı dirençteki tabakaları aşındırmasıyla oluşur.\n-Volkanik arazilerde görülür.\n-İç Anadolu'da bulunur.\n-Nevşehir, Ürgüp, Göreme, Avanos örnektir.",),
      InfoCardItem("cografya_Info_49","Platolar","-Akarsuların derine yardığı geniş düzlüklere denir.\n-İç Anadolu'da bulunur.",),
      InfoCardItem("cografya_Info_50","Peneplen(Yontuk Düz)","-Akarsu aşındırmasını son kısmında, deniz seviyesindeki düzlüklerdir.\n-Ülkemizde görülmez.",),

    ]),
    InfoCardModel("Akarsular-3", [
      InfoCardItem("cografya_Info_51","Akarsu Biriktirme Şekilleri","-Delta\n-Birikinti konisi\n-Dağ eteği ovası\n-Dağ içi ovası\n-Taban seviyesi ovası\n-Irmak adası",),
      InfoCardItem("cografya_Info_52","Delta","-Alüvonların denize döküldükleri yerlerde birikerek oluşan ovalardır.\n\nDelta oluşumu için;\n-Kıyı derinliği az olmalıdır.\n-Kıta sahanlığı geniş olmalıdır.\n-Alüvyon bol olmalıdır.\n-Denizde akıntı ve gel-git olmamalıdır.",),
      InfoCardItem("cografya_Info_53","Birikinti Konisi","Yamaçlardan düzlük alana inen akarsuların taşıdığı malzemeleri biriktirmeleriyle oluşur.",),
      InfoCardItem("cografya_Info_54","Dağ Eteği Ovası","Birikinti konilerinin dağın eteklerinde birleşmesiyle oluşur.",),
      InfoCardItem("cografya_Info_55","Dağ İçi Ovası","-Akarsuyla taşınan malzemelerin eğimin az olduğu yerlerde birikmesiyle oluşur.\n-Doğu Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_56","Taban Seviyesi Ovası","-Akarsuyun taşıdığı malzemelerin denize döküldüğü yerlerde birikmesiyle oluşur.\n-Kıyının hemen gerisindedir.\n-Ege ovaları ve Adapazarı Ovası örnek gösterilebilir.",),
      InfoCardItem("cografya_Info_57","Irmak Adası","Akarsu taşıdığı alüvyonları eimin iyice azaldığı yerlerde yatak üzerinde biriktirmesiyle oluşur.",),
      ]), InfoCardModel("Akarsular-4", [
      InfoCardItem("cografya_Info_58","Türkiye'nin Akarsularının Özellikleri","-Akış hızı yüksektir.\n-Debidi düşüktür.\n-Rejimi düzensizdir.",),
      InfoCardItem("cografya_Info_59","Karadenize Dökülen Akarsularımız","Kızılrmak, Yeşilırmak, Bartın Çayı ve Sakarya",),
      InfoCardItem("cografya_Info_60","Marmara Denizine Dökülen Akarsularımız","Susurluk",),
      InfoCardItem("cografya_Info_61","Ege Denizine Dökülen Akarsularımız","Meriç, Bakırçay, Küçük Menderes, Büyük Menderes ve Gediz",),
      InfoCardItem("cografya_Info_62","Akdenize Dökülen Akarsularımız","Manavgat, Aksu, Seyhan, Ceyhan, Göksu",),
      InfoCardItem("cografya_Info_63","Basra Körfezine Dökülen Akarsularımız","Fırat, Dicle",),
      InfoCardItem("cografya_Info_64","Hazar Denizine Dökülen Akarsularımız","Aras, Kura",),
      InfoCardItem("cografya_Info_65","Akarsu Notları","-Kaynağını dışarıdan alan akarsularımız ASİ-MERİÇ\n-Türkiye'de doğup dışarıda denize dökülen akarsularımız FIRAT, DİCLE, ÇORUH, KURA, ARAS",),
      InfoCardItem("cografya_Info_66","Havza","Akarsuyun kollarıyla beraber suyunu topladığı yere denir.\n\n2 çeşittir.\n-Açık Havza (Denize Dökülür)\n-Kapalı Havza (Denize Dökülmez)",),
      InfoCardItem("cografya_Info_67","Kapalı Havzalarımız","-Van Gölü Kapalı Havzası,\n-Tuz Gölü Kapalı Havzası\n-Konya Kapalı Havzası\n-Göller Yöresi Kapalı Havzası\n-Afyon Akarçay Kapalı Havzası",),
      InfoCardItem("cografya_Info_68","Akarsular Not","Türkiye'nin kendi sınırları içinde doğup kendi sınırları içinde denize dökülen en uzun akarsuyu KIZILIRMAK'tır.",),
    ]),
    InfoCardModel("Türkiye'de Göller-1", [
      InfoCardItem("cografya_Info_69","Türkiye'deki Göl Çeşitleri","-Tektonik Göller\n-Volkanik Göller\n-Set Gölleri\n-Buzul Gölleri\n-Baraj Gölleri\n-Karstik Göller",),
      InfoCardItem("cografya_Info_70","Tektonik Göller","-Tektonik hareketlerle çanaklaşan yerlerde suların birikmesiyle oluşur.\n-Ulubak, İznik, Sapanca, Kış (Marmara)\n-Beyşehir, Eğirdir, Burdur, Acıgöl, Tuz Gölü, Akşehir, Seyfe, Eber (İç Anadolu)\n-Van Gölü, Hazar Gölü (Doğu Anadolu)\n\nNOT: Türkiye'nin en büuük tatlı su gölü BEYŞEHİR GÖLÜ'dür.",),
      InfoCardItem("cografya_Info_71","Volkanik Göller","-Volkanik göller çukurlarda oluşur.\n-Meke Tuzlası, Nemrut Gölü, Gölcük Gölü",),
      InfoCardItem("cografya_Info_72","Set Gölleri-1","-Volkanik Set Gölleri\n-Kıyı Set Gölleri\n-Alüvyol Set Gölleri\n-Heyelan Set Gölleri",),
      InfoCardItem("cografya_Info_73","Volkanik Set Gölleri","-Suları sodalıdır.\n-Doğu Anadolu'da bulunur.\n-Balık, Haçlı, Çıldır, Erçek, Van, Nazik gölleri",),
      InfoCardItem("cografya_Info_74","Kıyı Set Gölleri","-Koy veya körfezin nünü dalgaların biriktirdiği kumların kapatmasıyla oluşur.\n-Marmara'da bulunur.\n-Küçük Çekmece, Büyük Çekmece ve Terkoz(Durusu) örnektir.",),
      InfoCardItem("cografya_Info_75","Alüvyol Set Gölleri","Vadi kenarlarında akarsuların alüvyol biriktirmesiyle oluşur.\n-Marmara, Bafra(Çamiçi), Eymir, Uzungöl, Köyceğiz, Mogan",),
      ]),InfoCardModel("Türkiye'de Göller-2", [
       InfoCardItem("cografya_Info_76","Heyelan Set Gölleri","-Heyelan ile akarsu vadisinin kapanmasıyla oluşur.\n-Abant, Yedigöller, Tortum, Sera, Zınav, Sürük örnektir.",),
      InfoCardItem("cografya_Info_77","Buzul Gölleri","Ağrı, Nemrut, Süphan, Tendürek, Kaçkar Dağları, Cilo, Uludağ, Erciyes, Aladağlar",),
      InfoCardItem("cografya_Info_78","Baraj Gölleri","-Akarsuların üzerinde set çekerek oluşturulan göllerdir.\n-İçme suyu, kullanma suyu, tarım arazilerini sulama, elektrik üretme, su taşkınlarını önleme amaçlarıyla kurulabilir.",),
      InfoCardItem("cografya_Info_79","Karstik Göller","-Kirecin erimesiyle oluşur.\n-Elmalı, Kastel, Salda, Suğla, Kızılören, Avlan örnektir.",),
      InfoCardItem("cografya_Info_80","Barajlarımız-1","Fırat üzerinde\n-Atatürk, Karakaya, Keban, Birecik, Karkamış\n\nDicle üzerinde\n-Kralkızı, Dicle, Ilısu, Cizre, Devegeçidi\n\nKızılırmak üzerinde\n-Hirfanlı, Altınkaya, Kapukkaya, Kesikköprü",),
      InfoCardItem("cografya_Info_81","Barajlarımız-2","Yeşilırmak üzerinde\n-Almus, Kılışkaya, Suat Uğurlu, Hasan Uğurlu\n\nGediz üzerinde\n-Demirköprü\n\nBüyük Menderes üzerinde\n-Kemer ve Adıgüzel",),
      InfoCardItem("cografya_Info_82","Barajlarımız-3","Seyhan üzerinde\n-Seyhan, Çatalan\n\nCeyhan üzerinde\n-Ceyhan, Aslantaş, Menzelet\n\nManavgat üzerinde\n-Manavgat, Oymapınar",),
      InfoCardItem("cografya_Info_83","Barajlarımız Not","Türkiye'nin en büyük barajı Atatürk'tür.",),
    ]),
    InfoCardModel("İklim ve Sıcaklık", [
      InfoCardItem("cografya_Info_84","Türkiye'de İklim-1","İklimi etkileyen faktörler\n-Matematik konum,\n-Dağların uzanışı ve bakı\n-Yükselti,\n-Etraftaki denizlerin, kara kütlelerinin ve basınç maddelerinin etkisi.",),
      InfoCardItem("cografya_Info_85","Türkiye'de İklim-2","Ülkemizde görülen iklim türleri\n-Karadeniz iklimi\n-Akdeniz iklimi\n-Karasal İklim",),
      InfoCardItem("cografya_Info_86","Karadeniz İklimi","-Yazlar serin, kışlar ılıktır.\n-Yağış her mevsimde görülür.\n-Sıcaklık farkı azdır.\n-Doğu Karadeniz Bölümü'nde yağış daha fazladır.\n-Yamaç yağışları görülür.\n-Karadeniz'in kıyı kesimleri ile Marmara'nın Karadeniz'e bakan kısmında görülür.",),
      InfoCardItem("cografya_Info_87","Akdeniz İklimi","-Yazlar sıcak ve kuraktır.\n-Kışlar ılık ve yağışlıdır.\n-Cephe yağışları şeklinde yağışlar görülür.\n-Yağışlar en çok kış mevsiminde oluşur.\n-Akdeniz, Ege, Güney Marmara ve Güney Doğu Anadolu'nun batısında görülür.",),
      InfoCardItem("cografya_Info_88","Karasal İklim","-Yazlar sıcak ve kuraktır.\n-Kışlar sert ve uzundur.\n-Buharlaşma çoktur.\n-Kuraklık görülür.\n-İç Anadolu, Güney Doğu Anadolu, İç Batı Anadolu'da görülür.",),
      InfoCardItem("cografya_Info_89","Türkiye'de Sıcaklık-1","Enlem, yükseklik, karasallık, mevsim, eğim ve güneş ışınlarının gelme açısına bağlı olarak sıcaklık değişir.\n-Güneş ışınlarının dik geldiği yerler daha çok ısınır.\n-Yükseklik arttıkça sıcaklık azalır.",),
      InfoCardItem("cografya_Info_90","Türkiye'de Sıcaklık-2","-Karalar çabuk, denizler geç ısınır.\n-Ekvatordan gelen rüzgarlar sıcaklığı arttırır.\n-Dağların uzanışı sıcaklığı etkiler.\n-Kuzeye bakan kısımlar daha az ısınır.",),
      ]), InfoCardModel("Rüzgar ve Yağış", [
     InfoCardItem("cografya_Info_91","Türkiye'de Rüzgarlar","-Yerel Rüzgarlar\n-Meltem Rüzgarları\n-Fön Rüzgarları",),
      InfoCardItem("cografya_Info_92","Yerel Rüzgarlar","-Poyraz: Kuzeydoğudan eser, yazın sıcak kışın soğuktur.\n-Karayel: Kuzeybatıdan eser, kışın soğuktur.\n-Lodos: Güneybatıdan eser, ılıktır.\n-Samyeli: Güneydoğudan eser, sıcaktır.",),
      InfoCardItem("cografya_Info_93","Meltem Rüzgarları","-Deniz Meltemi: Ege'de imbat denir. Gündüz deniden karaya eser.\n-Kara Meltemi: Gece karadan denize eser.\n-Vadi Meltemi: Gündüze vadiden dağa eser.\n-Dağ Meltemi: Gece dağdan vadiye eser.",),
      InfoCardItem("cografya_Info_94","Fön Rüzgarları","Dağ yamaçları boyunca alçalan hava hareketleriyle oluşan rüzgardır.\n-Sıcaklığı arttırır.\n-Karları eritir.\n-Yağışa engel olur.",),
      InfoCardItem("cografya_Info_95","Türkiye'de Yağış","-Yamaç Yağışları\n-Konveksiyonel Yağış\n-Cephe Yağışları",),
      InfoCardItem("cografya_Info_96","Yamaç Yağışları","-Yamaç boyunca nemli havanın yükselerek soğumasıyla oluşur.\n-Dağların denize bakan yamaçlarında oluşur.\n-Akdeniz, Karadeniz ve Ege'de görülür.",),
      InfoCardItem("cografya_Info_97","Konveksiyonel Yağışlar","-Isınan havanın yükselip soğumasıyla oluşur.\n-İlkbahar başlarında sık görülür.\n-İç Anadolu ve Doğu Anadolu'da görülür.\n-Kırkikindi yağışları da denir.",),
      InfoCardItem("cografya_Info_98","Cephe Yağışları","Sıcak ve soğuk hava kütlelerinin karşılaşıp, sıcak havanın soğuyup yoğunlaşmasıyla  oluşur.\n-Akdeniz, Güney Doğu Anadolu'da sık görülür.\n-Kış mevsiminde görülür.",),
    ]),
    InfoCardModel("Nüfus ve Yerleşme", [
      InfoCardItem("cografya_Info_99","Türkiye'de Nüfus","-İlk nüfus sayımı 1927'de yapılmıştır.\n-Devlet İstatistik Enstitüsü gerçekleştirir.",),
      InfoCardItem("cografya_Info_100","Nüfus Artışının Nedenleri","-Dıştan gelen  göçler,\n-Doğum oranının artması,\n-Bebek ölümlerinin azalması,\n-Beslenme koşullarının daha iyi olması.",),
      InfoCardItem("cografya_Info_101","Nüfusun Dağılışını Etkileyen Faktörler","-İklim\n-Yer şekilleri\n-Tarım, ulaşım ve sanayi\n-Turizm\n-Su imkanı\n-Bitki örtüsü\n-Yer altı kaynakları\n\nNOT: En çok nüfus Marmara Bölgesi, en az nüfus Doğu Anadolu Bölgesi'ndedir.",),
      InfoCardItem("cografya_Info_102","Türkiye'de Yerleşme","-Kırsal yerleşme\n-Kentsel Yerleşme",),
      InfoCardItem("cografya_Info_103","Kırsal Yerleşmeler","Köy:\n-Geçim kaynağı tarım ve hayvancılıktır.\n-Nüfus 2000'den azdır.\n\nKöyaltı Yerleşim\n-Mahalle, mezra, çiftlik, yayla, oba, dam vb. yerleşimlerdir.",),
      InfoCardItem("cografya_Info_104","Kentsel Yerleşmeler-1","Ticaret Kentleri: İstanbul, Ankara, İzmir, Bursa, Kayseri, Gaziantep vb.\nTarım Kentleri: Tarsus, Söke, İnegöl, Rize, Karaman vb.\nSanayi Kentleri: İstanbul, İzmir, Bursa, Ankara, Batman",),
      InfoCardItem("cografya_Info_105","Kentsel Yerleşmeler-2","Liman Kentleri: İstanbul, İzmir, Antalya, Samsun, Trabzon\nTurizm Kentleri: Antalya, Muğla, İzmir, Aydın vb.\nÜniversite Kentleri: İstanbul, Ankara, İzmir, Eskişehir vb.",),
      InfoCardItem("cografya_Info_106","Türkiye'de Mesken Tipleri-1","Betonerme: Demir, beton, tuğla kullanılır. Ege ve Marmara bölgesinde sık görülür.\n\nTaş: Dağlık yerlerde görülür. Doğu Anadolu, Nevşehir çevresi ve Toros Dağlarında görülür.",),
      InfoCardItem("cografya_Info_107","Türkiye'de Mesken Tipleri-2","Ahşap: Malzeme ağaçtır. Ormanın sık olduğu yerlerde görülür. Karadeniz'de sık görülür.\n\nKerpiç: Malzeme killi topraktır. Kurak iklimde sık görülür. İç Anadolu ve Doğu Anadolu'da sık görülür. ",),
       ]), InfoCardModel("Endüstri", [
     InfoCardItem("cografya_Info_108","Türkiye'de Endüstri","-Dokuma ve giyim.\n-Besin\n-Maden\n-Otomotiv\n-Kimya\n-Çimento, seramik ve cam",),
      InfoCardItem("cografya_Info_109","Dokuma ve Giyim","Pamuk: Nazilli, Mersin, Adana, Antalya, Manisa, Denizli, Hatay, Kahramanmaraş, İzmir, Şanlıurfa, Iğdır, Bursa...\nYün: Hereke\nİpek: Bursa, İstanbul, Eskişehir, Bilecik\nHalı-Kilim: Uşak, Kayseri, Sivas, Bursa...",),
      InfoCardItem("cografya_Info_110","Besin","Şeker: İç kesimler\nÇay: Rize-Trabzon\nUn: İç kesimler, Trakya\nZeytinyağı: Ege, Güney Marmara\nAyçiçek yağı: Trakya, Ege, İç Anadolu\nSüt: İzmir, Erzurum, Kars",),
      InfoCardItem("cografya_Info_111","Maden","Demir-çelik: Sivas, İskenderun, Karabük, Ereğli, İzmir\nAliminyum: Seydişehir(tek)\nKurşun-Çinko: Kayseri, Giresun, Elazığ(Keban), Yozgat(Akdağmadeni)\nBakır: Murgul, Küre, Samsun, Çayeli, Siirt",),
      InfoCardItem("cografya_Info_112","Otomotiv","Otomobil Fabrikası: İstanbul, İzmir, Bursa, İzmit\nKamyon Fabrikası: İstanbul, İzmir, Adana, Eskişehir\n\nNot: Ankara'da uçak fabrikası var.\n\nEskişehir'de lokomotif fabrikası var.",),
      InfoCardItem("cografya_Info_113","Kimya","İlaç: İstanbul, Ankara, İzmir\nBoya: İstanbul, İzmir\nLastik: Adapazarı, İzmit\nPetrol-kimya: İzmir, Mersin, İzmit, Batman",),
      InfoCardItem("cografya_Info_114","Çimento, Seramik, Cam","Çimento: İstanbul, Ankara, İzmir, Mersin, Adana, Eskişehir\nSeramik: Kütahya, Bilecik, Çanakkale, Uşak, Aydın\nCam: İstanbul, Sivas, Kırklareli, Mersin, Bursa",),
    ]),
    InfoCardModel("Türkiye'de Madencilik", [
      InfoCardItem("cografya_Info_115","Demir","-Ereğli, Karabük ve İskenderun'da demir-çelik fabrikaları vardır.(işlendiği yerler)\n-Demirin çıkarıldığı yerler; Divriği, Hekimhan, Edremit, Dikili, Adana, Hatay, Simav, Torbalı",),
      InfoCardItem("cografya_Info_116","Bakır","-Elektrik, elektronik sanayisinde kullanılır.(iletkenliği yüksek)\n-Çıkarıldığı yerler: Murgul (Artvin), Küre (Kastamonu), Elazığ (Ergani), Rize (Çayeli)\n-İşlendiği yerler: Samsun, Murgul (Artvin), Ergani (Elazığ), Maden (Elazığ)",),
      InfoCardItem("cografya_Info_117","Krom","-Paslanmaz çelik yapımında ve demir sertleştirmede kullanılır.\n-Çıkarıldığı yerler: Elazığ (Guleman), Muğla, Kayseri, Adana, Kütahya, Bursa, Denizli, Mersin, İskenderun, Kahramanmaraş\n-İşlendiği yerler: Antalya, Elazığ (Guleman)",),
      InfoCardItem("cografya_Info_118","Aliminyum","-Kullanıldığı yerler: Otomobil, uçak sanayi, ev eşyası yapımı, inşaat sektörü, elektrikli araçlar\n-Çıkarıldığı yerler: Konya (Seydişehir), Muğla (Milas), Antalya (Akseki), Gaziantep (Islahiye)\n-İşlendiği yerler: Seydişehir Aliminyum Tesisleri",),
      InfoCardItem("cografya_Info_119","Bor","-Dünyada azdır.\n-Dünyanın en zengin bor rezervi Türkiye'dedir.(%75)\n-Kullanıldığı yerler: Nükleer alan, jet ve roket yakıtı, sabun, cam, fotoğrafçılık, kağıt sanayi\n-Çıkarıldığı yerler: Balıkesir (Susurluk, Bigadiç), Kütahya (Emet), Bursa (Kestelek), Eskişehir (Kırka)\n-İşlendiği yerler: Bandırma Boroks ve Asitborik Fabrikası, Eti Maden Kırka Bor İşletme",),
      InfoCardItem("cografya_Info_120","Altın","-Kullanıldığı yerler: Ziynet eşyası, para\n-Çıkarıldığı yerler :Balıkesir (İvrindi, Çoraklık, Kızıltepe), İzmir (Ovacık, Çukuralan, Seferihisar), Uşak (Kızıldağ), Erzincan (Çöpler)",),
      InfoCardItem("cografya_Info_121","Kurşun-Çinko","-İkisi karışıktır.\n-Kullanım alanları: Silah sanayi, Paslanmaz metal üretim, Akü imalatı, Ses yalıtımı\n-Çıkarıldığı yerler: Elazığ (Keban), Giresun, Sivas, Kayseri, İzmir",),
      InfoCardItem("cografya_Info_122","Kükürt","-Kullanım alanları: Sülfirik asit üretiminde, kimya sanayi, zirai ilaç yapımı, havai fişek\n-Çıkarıldığı yerler: Isparta (Keçiborlu), Denizli (Sarayköy), Kütahya (Simav), Muğla (Milas)",),
      InfoCardItem("cografya_Info_123","Civa","-Tek sıvı madendir.\n-Kullanıldığı yerler: Zirai ilaç yapımı, suni gübre üretimi, boya sanayi, kağıt sanayi\n-Çıkarıldığı yerler: İzmir (Ödemiş), Manisa (Alaşehir), Konya (Sarayönü)",),
      InfoCardItem("cografya_Info_124","Lüle Taşı","-Süs eşyası yapımında kullanılır.\n-Eskişehir'de çıkarılır.",),
      InfoCardItem("cografya_Info_125","Oltu Taşı","-Süs eşyası yapımında kullanılır.\n-Erzurum'da çıkarılır.",),
      InfoCardItem("cografya_Info_126","Mermer","Kullanıldığı Alanlar\n-İnşaat sektörü, heykel yapımı, süsleme\n-Çıkarıldığı yerler\n-Afyon, Marmara adası, Kütahya, Kırşehir",),
      InfoCardItem("cografya_Info_127","Tuz","Çıkarıldığı yerler\n-İzmir (Çamaltı) ve Tuz Gölü en çok çıkarıldığı yerlerdir. Ayrıca Çankırı, Kars, Iğdır ve Nevşehir'de bulunur.",),
    ]),
    InfoCardModel("Enerji Kaynaklarımız", [
      InfoCardItem("cografya_Info_128","Taş Kömürü","-Zonguldak, Ereğli, Amasra'da çıkarılır.\n-Demir-çelik sanayisinde enerji kaynağı olarak tüketilir.",),
      InfoCardItem("cografya_Info_129","Linyit-1","-Esmer kömür olarak bilinir.\n-Kalorisi azdır.\n-En zengin enerji kaynaklarındandır.\n-Bütün bölgelerde bulunur.\n-Afşin, Esbistan, Tunçbilek, Tavşanlı, Seyitömer, Değirmisaz, Yatağan, Soma, Mengen, Saray başlıca çıkarıldığı yerlerdir.",),
      InfoCardItem("cografya_Info_130","Linyit-2","-Elektrik enerjisi linyitten elde edilir. Bu santraller termik santrallerdir.\n\nTermik Santrallerimiz\n-Kütahya (Seyitömer, Tunçbilek), Manisa (Soma), Muğla (Yatağan), Kahramanmaraş (Afşin, Elbistan), Orhaneli, Zonguldak (Çatalağzı)",),
      InfoCardItem("cografya_Info_131","Doğalgaz","-Rusya, İran'dan ithal edilir.\n-Kırklareli, Lüleburgaz, Babaeski'de bulunur.",),
      InfoCardItem("cografya_Info_132","Petrol","-İlk kez Raman Dağı'nda (Batman) bulundu.\n-Mardin, Adıyaman, Diyarbakır, Batman, Siirt'de çıkarılır.",),
      InfoCardItem("cografya_Info_133","Jeotermal Enerji","-Buhardan elde edilir.\n-Afyon, Aydın (Germencik) ve Denizli'de (Sarayköy) bulunur.",),
      InfoCardItem("cografya_Info_134","Hidroelektrik Enerji","-Barajlardan elde edilen enerjidir.\n-En yüksek enerji potansiyeli Doğu Anadolu'dadır.",),
    ]),
    InfoCardModel("Türkiye'de Tarım-1", [
      InfoCardItem("cografya_Info_135","Tarım İhracı","İhraçta 1. sırada olduğumuz ürünler\n-Fındık %67\n-İncir %27\n-Kiraz %26\n-Kayısı %23",),
      InfoCardItem("cografya_Info_136","Tarım Ürünleri","-Tahıllar\n-Sebzeler\n-Endüstri Bitkileri\n-Yağlı Bitkiler\n-Meyvecilik",),
      InfoCardItem("cografya_Info_137","Tahıllar","-Buğday\n-Arpa\n-Çavdar\n-Mısır\n-Pirinç",),
      InfoCardItem("cografya_Info_138","Buğday","-En geniş ekim alanına sahiptir.\n-En fazla İç Anadolu'da yetişir.\n-Karadeniz'de yetişmez.\n-İlkbaharda yağış, yazın kuraklık ister.",),
      InfoCardItem("cografya_Info_139","Arpa","-Buğdaydan sonra en fazla üretilen tahıldır.\n-Soğuğa, sıcağa dayanaklıdır.\n-En fazla iç Anadolu'da yetişir.\n-Bira yapımında ve hayvan yeminde kullanılır.",),
      InfoCardItem("cografya_Info_140","Çavdar","-Düşük ısıya dayanıklıdır.\n-Arpa ve buğdayın yetişemediği yerlerde yetişir.\n-İç Anadolu ve Doğu Anadolu'da yetişir.\n-Un yapımında ve hayvan yemi olarak kullanılır.",),
      InfoCardItem("cografya_Info_141","Mısır","-Bol su, sıcaklık ister.\n-Karadeniz ikliminde uyumludur.\n-Karadeniz, Akdeniz, Marmara da sık üretilir.",),
      InfoCardItem("cografya_Info_142","Pirinç","Bol su, sıcaklık, emek ister.\n-Vadi tabanları, akarsu boylarında üretilir.\n-Yerleşim yerlerinin yakınında ekimi yasaktır. (Sivrisineğe ve sıtmaya neden olduğu için)\n-En çok Edirne, Samsun, Çorum, Sinop'ta üretilir.",),
      ]), InfoCardModel("Türkiye'de Tarım-2", [
      InfoCardItem("cografya_Info_143","Sebzeler","-Mercimek\n-Nohut\n-Fasulye\n-Patates",),
      InfoCardItem("cografya_Info_144","Mercimek","-Yetişirken yağış ister.\n-Olgunlaşırken sıcaklık ister.\n-Kırmızı mercimek en çok Güneydoğu Anadolu'da yetişir.\n-Yeşil mercimek en çok İç Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_145","Nohut","-Yarı kurak iklimi sever.\n-En çok iç Anadolu, İç Ege, Güneydoğu Anadolu da yetişir.",),
      InfoCardItem("cografya_Info_146","Fasulye","-Yazın sulama olan her yerde yetişir.\n-Çukurova, Marmara'nın güney ovaları, iç kısımlarda akarsu boylarında üretilir.",),
      InfoCardItem("cografya_Info_147","Patates","-Buğdaydan sonra en çok tüketilir.\n-Değişik iklim koşullarına uygundur.\n-En çok İç Anadolu (Niğde, Nevşehir, Kayseri) ve Sakarya'da yetişir.",),
     ]),InfoCardModel("Türkiye'de Tarım-3", [
      InfoCardItem("cografya_Info_148","Endüstri Bitkileri","-Tütün\n-Pamuk\n-Şeker pancarı\n-Çay",),
      InfoCardItem("cografya_Info_149","Tütün","-Çimlenmede bol su ister.\n-Büyürken güneş, sıcaklık ister.\n-Kumlu, kıraç toprakları sever.\n-En fazla Denizli, Manisa, Kütahya, Samsun, Bolu, Amasya, Trabzon, Balıkesir, Adıyaman'da yetişir.",),
      InfoCardItem("cografya_Info_150","Pamuk","-Büyürken su, olgunlaşırken kuraklık ister.\n-En çok Güneydoğu Anadolu, Ege, Akdeniz'de yetişir.\n-Malatya, Iğdır, Elazığ'da yetişir.\n-Karadeniz'de yetiştirilmez. (Yazın kurak olmadığı için)",),
      InfoCardItem("cografya_Info_151","Şekerpancarı","Ilıman iklim sever.\n-Soğuğa dayanıklıdır.\n-İlkbaharda ekilir.\n-Güzün hasad edilir.\n-En çok İç Anadolu'da yetişir.\n-Şeker, Yem, İspirto sanayisinde kullanılır.",),
      InfoCardItem("cografya_Info_152","Çay","-Sürekli yağış ve nem ister.\n-Eğimli ve gölgeli arazilerde yetişir.\n-Karadeniz'de (Ordu, Rize) yetişir.",),
            ]),InfoCardModel("Türkiye'de Tarım-4", [
        InfoCardItem("cografya_Info_153","Yağlı Bitkiler","-Zeytin\n-Ayçiçeği\n-Yer fıstığı\n-Susam\n-Haşhaş\n-Keten, Kenevir",),
      InfoCardItem("cografya_Info_154","Zeytin","-Akdeniz ikliminde yetişir.\n-Bir arayla ürün verir.\n-En çok Ege, Marmara, Akdeniz, Güneydoğu Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_155","Ayçiçeği","-En çok Marmara'da yetişir.\n-Büyüme döneminde yağış ister.\n-Olgunlaşma döneminde sıcaklık ister.\n-İç Anadolu ve Orta Karadeniz'de yetişir.",),
      InfoCardItem("cografya_Info_156","Yer Fıstığı","-Güneydoğu Anadolu, Akdeniz, Ege, Marmara'da üretilir.\n-Sıcaklık ve nemli iklimi sever.\n-Kuruyemiş ve yağ şeklinde tüketilir.",),
      InfoCardItem("cografya_Info_157","Susam","-Ilıman iklimde yetişir.\n-Akdeniz, Ege, Marmara'da yetişir.\n-Yağı çıkartılır.",),
      InfoCardItem("cografya_Info_158","Haşhaş","-Yazların sıcak ve orta derece yağışlı olduğu yerlerde yetişir.\n-Yağ, ilaç, uyuşturucu yapımında kullanılır.\n-En çok Afyon'da yetişir.",),
      InfoCardItem("cografya_Info_159","Keten, Kenevir","-Ilıman iklim ve nemli toprak sever.\n-Dokuma sanayisinde kullanılır.\n-Tohumdan elde edilen Bezir yağı boya yapımında kullanılır.\n-En çok Sinop, Kastamonu, Zonguldak ve Kocaeli'de yetişir.",),
       ]),InfoCardModel("Türkiye'de Tarım-4", [
 InfoCardItem("cografya_Info_160","Meyvecilik","-Fındık\n-Antep Fıstığı\n-İncir\n-Üzüm\n-Elma\n-Turunçgiller\n-Muz",),
      InfoCardItem("cografya_Info_161","Fındık","-Serin, nemli iklim sever.\n-En çok Karadeniz'de yetişir.\n-En çok fındık üreten ülke Türkiye'dir.",),
      InfoCardItem("cografya_Info_162","Antep Fıstığı","-Sıcak ve kurak iklim sever.\n-Tatlı yağımında kullanılır ve kuruyemiş olarak tüketilir.",),
      InfoCardItem("cografya_Info_163","İncir","-Akdeniz iklimini sever.\n-Soğuğa karşı dayanıksızdır.\n-En çok Ege ve Akdeniz'de yetişir.\n-Dünyada en çok incir üreten ülke Türkiye'dir.",),
      InfoCardItem("cografya_Info_164","Üzüm","-Her bölgemizde yetişebilir.\n-Yemeklik, pekmez, şarap ve kuru şekllerde tüketilir.\n-En çok Ege, Marmara, Güneydoğu Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_165","Elma","Ilıman iklim sever.\n-En çok İç Anadolu'da yetişir.\n-Çoğu bölgemizde yetişir.",),
      InfoCardItem("cografya_Info_166","Turunçgiller","-Ilıman iklimi sever.\n-En çok Akdeniz, Ege ve Rize'de yetişir.",),
      InfoCardItem("cografya_Info_167","Muz","-Yüksek seıcaklık, nem sever.\n-Antalya-Mersin arasında yetişir.",),
    ]),
    InfoCardModel("Hayvancılık-1", [
      InfoCardItem("cografya_Info_168","Hayvancılık","-Küçükbaş Hayvancılık\n-Büyükbaş Hayvancılık\n-Kümes Hayvancılığı\n-Balıkçılık\n-İpek Böcekçiliği\n-Arıcılık",),
      InfoCardItem("cografya_Info_169","Küçükbaş Hayvancılık","-Koyun\n-Keçi",),
      InfoCardItem("cografya_Info_170","Koyun","-Bozkırlarda yetiştirilir.\n-En çok İç Anadolu, Güneydoğu Anadolu ve Doğu Anadolu'da yetişir.\n-Soyları Kıvırcık, Dağlıç, Merinos, Karaman, Sakız olarak ayrılır.",),
      InfoCardItem("cografya_Info_171","Kıvırcık Koyun","-Et verimi yüksektir.\n-Trakya ve Marmara'nın güneyinde yetişir.",),
      InfoCardItem("cografya_Info_172","Dağlıç Koyun","-Et verimi yüksektir.\n-Dağlık olmayan yerlerde yetişir.\n-Ege, İç Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_173","Merinos Koyun","-Yünü kalitelidir, et verimi düşüktür.\n-Marmara'da yetişir.",),
      InfoCardItem("cografya_Info_174","Karaman Koyunu","-İç Anadolu, Ege, Güneydoğu Anadolu'da yetişir.\n-Uzun kuyrukludur.",),
      InfoCardItem("cografya_Info_175","Sakız Koyunu","-Ege, İç Anadolu'da yetişir.\n-İnce kuyrukludur.",),
      InfoCardItem("cografya_Info_176","Keçi","-Kıl keçisi\n-Tiftik(Ankara) keçisi",),
      InfoCardItem("cografya_Info_177","Kıl Keçisi","-Koyuna göre daha dayanıklıdır.\n-Sütü, eti, kılı için bakılır.\n-Dağlık, dik yerlerde yetiştirilir.\n-Akdeniz, Doğu Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_178","Tiftik (Ankara) Keçisi","-Tüyleri uzun, ince ve parlaktır.\n-En çok İç Anadolu, Güneydoğu Anadolu'da yetiştirilir.",),
      ]),InfoCardModel("Hayvancılık-1", [
     InfoCardItem("cografya_Info_179","Büyükbaş Hayvancılık","-Türkiye'nin her bölgesinde yetiştirilir.\n-Eti, sütü ve gücü için yetiştirilir.\n-Erzurum-Kars bölgesinde iyi cinsleri yetişir.\n-Soğır, at, eşek, katır, manda büyükbaş hayvanlara örnektir.",),
      InfoCardItem("cografya_Info_180","Kümes Hayvancılığı","-Et, yumurta için beslenir.\n-Tavuk, kaz, ördek ve hindi örnektir.\n-En çok Marmara, Ege, İç Anadolu'da yetiştirilir.",),
      InfoCardItem("cografya_Info_181","Balıkçılık","-En çok Karadeniz'de yapılır. (%80)\n-En çok hamsi tutulur.\n\nNOT: Karadeniz'de balıkçılığın çok olma sebepleri\n-Tuzluluk oranının düşük olması\n-Çok sayıda akarsuyun bol planktonu denize dökmesi\n-Tarım arazisini az olması.",),
      InfoCardItem("cografya_Info_182","İpek Böcekçiliği","-Besin kaynağı dut yaprağıdır.\n-Salgısının katılaşmasıyla ipek oluşur.\n-En çok Marmara, Denizli, Elazığ'da görülür.",),
      InfoCardItem("cografya_Info_183","Arıcılık","-En çok Karadeniz'de yapılır.\n-Hakkari, Kars, Bitlis, Erzurum, Muğla, Manisa, İzmir ve Aydın balı ile ünlüdür.",),
    ]),
  ];

  //Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği
  InfoCardModel("Başlık", [
      InfoCardItem("ALTBAŞLIK","",),
    ]),
    */
  List<InfoCardModel> get cografyaInfoCard => _cografyaInfoCard;
}
