import '../model/info_card_item.dart';
import '../model/info_card_model.dart';

class GenelKulturInfoViewModel {
  List<InfoCardModel> _genelKulturInfoCard = [
    InfoCardModel("Tarih-Osmanlı Devleti Siyasi Dönemler", [
      InfoCardItem("tarih_Info_1","","-Kuruluş Dönemi(1299-1453)\n-Yükselme Dönemi(1453-1579)\n-Duraklama Dönemi(1579-1699)\n-Gerileme Dönemi(1699-1792)\n-Dağılma Dönemi(1792-1918)",),
      InfoCardItem("tarih_Info_2","Kuruluş Dönemi","1453 İstanbul'un fethine kadar olan dönemdir.",),
      InfoCardItem("tarih_Info_3","Yükselme Dönemi","Sokullu Mehmet Paşa'nın ölümüne kadarki dönemdir.",),
      InfoCardItem("tarih_Info_4","Duraklama Dönemi","-Karlofça Antlaşmasına kadarki dönemdir.\n\nDuraklamanın Nedenleri\n-Merkezi yönetimin bozulması\n-Ordu ve donanmanın bozulması\n-Eğitimin bozulması\n-Maliyenin bozulması",),
      InfoCardItem("tarih_Info_5","Merkezi Yönetimin Bozulma Nedenleri","-Şehzadelerin Devlet başına geçmesinde sancak sistemi kullanılması.\n-Önemli makamlara gelecek kişilerin rüşvet ve iltimasla getirilmesi.\n-Kadınların yönetimde etkin olması",),
      InfoCardItem("tarih_Info_6","Ordu ve Donanmanın Bozulması Nedenleri","-Kapıkulu Ocaklarına askerin çok alınması.\n-Tımar sisteminin bozulması.\n-Yeniçerilerin askerlik dışındaki işlerle uğraşmaları.\n-Harp alanında Avrupa'yı takip edememesi",),
      InfoCardItem("tarih_Info_7","Eğitim Sisteminin Bozulması Nedenleri","-Beşik ulemalığı sisteminin ugulanması.\n-Medreselerden pozitif bilimin kaldırılması.\n-Medrese eğitimi görmeyenlerin iltimasla atanması\n-Medreselerin, Avrupa'daki yenilikleri takip edememesi",),
      InfoCardItem("tarih_Info_8","Maliyenin Bozulması Nedenleri","-Cülus bahşişinin arttırılması.\n-Vergilerin artmasıyla köylülerin üretimi bırakması\n-Savaşların uzaması\n-Gümrüklerden elde edilen gelirlerin azalması",),
      InfoCardItem("tarih_Info_9","Duraklamanın Dış Nedenleri","-Avrupadaki gelişmelerin takip edilememesi\n-Devletin doğal sınırlara ulaşması\n-Güçlü devletlerle sınır olunması",),

    ]),InfoCardModel("Tarih-Osmanlı Devleti Gerilme Dönemi", [
      InfoCardItem("tarih_Info_10","Siyasi Olaylar","-Osmanlı-Rus ilişkileri(Prut Antlaşması 1711)\n-Osmanlı Venedik Avusturya ilişkileri(Pasarofça Antlaşması 1718)\n-Osmanlı Rusya Avusturya Savaşları(Belgrad Antlaşması 1739)\n-Osmanlı Rus Avusturya Savaşları(Ziştovi-Yaş Antlaşması)\n-Osmanlı Fransa ilişkileri",),
      InfoCardItem("tarih_Info_11","Lale Devri-1","-1718 Pasarofça Antlaşması ile başlandı.\n-1730 Patrona Halil isyanı ile sona erdi.\n-Zevk, sefa dönemi\n-Padişah II. Ahmet\n-Sadrazam Damat İbrahim Paşa\n-Avrupada ilk kez geçici elçilikler kuruldu.",),
      InfoCardItem("tarih_Info_12","Lale Devri-2","-İbrahim Müreferrika ve Sait Efendi ile Türk Matbaasını kurdu.\n-İtfaiye örgütü(Tulumbacılar) kuruldu.\n-Çiçek aşısı geliştirildi.\n-Doğu Klasiklerinde eserler Türkçeye çevrildi.\n-Kağıt, çini fabrikası açıldı.\n-Askeri alanda yenilikler yapılmadı.",),
      InfoCardItem("tarih_Info_13","I. Mahmut","-1730-1754 tarihleri arasındadır.\n-Humbaracı Ocağı Batı tarzında teşkilatlandırılmıştır.\n-Humbaracı Ahmet Paşa Topçu Ocağını modernleştirdi.\n-Subay Yetiştirmek için mühendishane kurulmuştur.\n-Yabancı subaylarla ordu modernize edilmeye çalışıldı.",),
      InfoCardItem("tarih_Info_14","III. Mahmut","1756-1774 tarihleri arasını kapsar.\n-Maliye alanında ıslahatlar yapıldı.\n-Sürat Topçu Ocağı kuruldu.\n-Deniz Mühendishanesi kuruldu.\n-İç borçlanmaya gidildi.",),
      InfoCardItem("tarih_Info_15","I. Abdülhamit","-1774-1789 tarihleri arasını kapsar.\n-Sürat topçuları geliştirilerek sayısı arttırıldı.\n-Yeniçeri sayımı yapıldı.\n-Lağımcı ve Humbaracı ocakları geliştirildi.",),
      InfoCardItem("tarih_Info_16","III. Selim","-1789-1807 tarihleri arasını kapsar.\n-İlk kez köklü değişiklikler yapıldı.\n-Nizam-ı Cedit ordusu kuruldu.\n-İrado Cedit hazinesi oluşturuldu.\n-Kara Mühendishanesi kuruldu.\n-Avrapada daimi elçilikler açılmıştır.\n-Devlet Matbaası ilk kez kuruldu.\n-Kabakçı Mustafa Paşa isyanı ile tahttan indirildi.",),
      InfoCardItem("tarih_Info_17","Islahatların Genel Özellikleri-1","-Askeri alanda yapılmıştır.\n-Halk isteksizdir.\n-Padişah ve devlet adamları gerçekleştirmiştir.\n-Yüzeysel çözümler üretilmiştir.\n-İstenilen sonuca ulaşılmamıştır.\n-Batıdaki gelişmelerden faydalanılmamıştır.",),
      InfoCardItem("tarih_Info_18","Islahatların Faydalı Olmama Nedenleri","-Padişahların sık değişimi\n-Yenilik karşıtı yeniçeriler\n-Ulemanın tepkisi",),
    ]), InfoCardModel("Tarih-Dağılma Dönemi", [
      InfoCardItem("tarih_Info_19","II. Mahmut Dönemi-1","-1808-1839 tarihleri arasındadır.\n-Ayanlar ile II. Mahmut arasında Sened-i İttifak imzalandı.\n-Sekban-ı Cedid kuruldu.\n-Eşkinci Ocakları kuruldı.\n-Yeniçeri ocağı kaldırıldı(Vaka-i Hayriye)\n-Asakir-i Mansure-i Muhammediye ordusu kuruldu.",),
      InfoCardItem("tarih_Info_20","II. Mahmut Dönemi-2","-Takvim-i Vekayi adlı ilk resmi gazete çıkarıldı.\n-Tımar sistemi kaldırıldı.\n-Devlet memurları maaşa bağlandı.\n-Köy ve mahalle muhtarlıkları oluşturuldu.\n-Posta ve karantina hizmetleri açıldı.\n-Pasaport şartı getirildi.",),
      InfoCardItem("tarih_Info_21","II. Mahmut Dönemi-3","-İlköğretim İstanbul'da zorunlu hale getirildi.\n-Orta dereceli okullar açıldı.\n-Avrupa'ya ilk defa öğrenci gönderildi.\n-Divan kaldırıldı, Nazırlar(Bakanlıklar) kuruldu.",),
      InfoCardItem("tarih_Info_22","II. Mahmut Dönemi-4","-Kendi resmini devlet dairelerine astırdı.\n-Meclis-i Vala-yı Ahkam-ı Adliyye kuruldu.\n-Dar-ı Şura-yı Babıali(Danıştay) kuruldu.\n-Din ve mezhep özgürlüğü getirildi.",),
      InfoCardItem("tarih_Info_23","Sened-i İttifak-1","-1808 tarihinde imzalanmıştır.\n-Alemdar Mustafa Paşa hazırladı.\n-Ayanlar ve II. Mahmut imzaladı.",),
      InfoCardItem("tarih_Info_24","Sened-i İttifak-2","\nBuna göre;\n\n-Ayanlar padişahın emirlerine uyacak.\n-Ayanlar bulunduğu yerlerde vergi ve asker toplayacak.\n-Buna karşın Ayanlar devlet otoritesini tanıyarak yapılacak yeniliklere destek olacak. \n\n-Bununla birlikte padişahın sınırları ilk kez sınırlandırıldı.",),
    ]),
    InfoCardModel("Tarih-Avrupanın Osmanlı Görüşleri", [
      InfoCardItem("tarih_Info_25","", "Avrupanın hasta adamı konumundaydı."),
      InfoCardItem("tarih_Info_26","","Haklarını savunamaz haldeydi.",),
      InfoCardItem("tarih_Info_27","","18 nci yüzyılda denge politikası izlemişti.",),
      InfoCardItem("tarih_Info_28","","Rusya sıcak denizlere  inebilmek için Osmanlı Devleti'ni hedef almıştı.",),
      InfoCardItem("tarih_Info_29","","Fransa bir süre Osmanlı Devleti'ne arayı düzgün tutsa da daha sonra Cezayir ve Tunus'u işgal etmiştir.",),
      InfoCardItem("tarih_Info_30","","İngiltere Osmanlı Devleti'nin parçalanmasını istemiyordu. Çünkü Osmanlı Devleti sömürgelerine giden ticaret yolu üzerindeydi. Ancak 19.yy'da fikir değiştirdi. Bunda petrolün etkisi büyüktü.",),
      InfoCardItem("tarih_Info_31","","Almanya İngiltere ile rakipti. İngiltere Osmanlının parçalanması tarafına geçince Osmanlı Devleti Almanya ile yakınlaştı. Almanya bu durumdan yararlandı.",),
      InfoCardItem("tarih_Info_32","","Avrupalı devletlerin Osmanlı Devleti üzerinden pay alma çekişmelerine Şark Meselesi dendi.",),
      InfoCardItem("tarih_Info_33","","Şark Meselesi ilk defa Ruslar tarafından Viyana Kongresinde dile getirilmiştir. ",),
      InfoCardItem("tarih_Info_34","","Şark Meselesi Fransa'nın Mısır'a asker çıkarmasıyla başlamıştır.",),
    ]),
    InfoCardModel("Tarih-Tanzimat Fermanı", [
     InfoCardItem("tarih_Info_35","Özellikleri","-Abdülmecit döneminde ilan edildi.\n-Mustafa Reşit Paşa ilan etti.\n-3 Kasım 1939'da Gülhane Parkında okundu.\n-Batılı devletler Osmanlı Devleti'ne hukuk kurallarını benimsetmeye çalışmıştır."),
     InfoCardItem("tarih_Info_36","Yenilikleri","-Tüm halkın can, mal ve namus güvenliği devlet garantisindedir.\n-Vergiler herkesin gücüne göre toplanacaktır.\n-Askerlik vatani görevdir.\n-Hiçkimse yargılanmadan ceza yiyemez.\n-Rüşvet önlenecek.\n-Padişah dahil herkes uyacak."),
     InfoCardItem("tarih_Info_37","Önemi","-Anayasacılık fikri gelişmiştir.\n-Padişah hukuk üstünlüğünü kabul etmiştir.\n-Eşitlik benimsenmiştir."),
    ]),
    InfoCardModel("Tarih-Islahat Fermanı", [
    InfoCardItem("tarih_Info_38","Özellikleri","-Dönemin Padişahı Abdülmecit'tir.\n-1856'da Bab-ı Ali ilan etmiştir.\n-Osmanlı Devleti'nin dağılmasını önlemeyi amaçlamıştır."),
    InfoCardItem("tarih_Info_39","Yenilikleri","-Azınlıklara bedelli askerlik hakkı verildi.\n-Azınlıklar okul, hastane, kilise açabilecek.\n-Azınlıklar memur olarak alınabilecek.\n-Azınlıklar özel mahkeme kurabilecek."),
    InfoCardItem("tarih_Info_40","Önemi","-Azınlıklara en kapsamlı haklar verilmiştir.\n-Eşitlik benimsenmiştir."),
    ]),
    InfoCardModel("Tarih-1. ve 2. Meşrutiyet", [
    InfoCardItem("tarih_Info_41","1. Meşrutiyet Özellikleri-1","-Fikir çalışmasını Jön Türkler(Genç Osmanlılar) yürütmüştür.\n-23 Aralık 1976'da 2.Abdulhamit tarafından ilan edildi.\n-Kanun-i Esasi yürürlüğe kondu.(İlk Osmanlı Anayasası)"),
    InfoCardItem("tarih_Info_42","1. Meşrutiyet Özellikleri-2","-İlk kez meclis açıldı.\n-Amaç Osmanlı'nın çöküşünü engellemek.\n-Osmanlı halkına ilk kez seçme ve seçilme hakkı verildi.\n-93 Harbi yüzünden 2. Abdülhamit meclisi kapattı."),
    InfoCardItem("tarih_Info_43","1. Meşrutiyet Maddeleri-1","-Saltanat Osmanlı Ailesinden en büyük çocuğa geçer.\n-Yasama Ayan ve Mebusan Meclisi'ndedir.\n-Yürütme Heyet-i Vüküla(Bakanlar Kurulu).\n-Yargı mahkemelere devredilmiştir."),
    InfoCardItem("tarih_Info_44","1. Meşrutiyet Maddeleri-2","-Hükümet padişaha karşı sorumludur.\n-Kanun teklifini sadece hükümet yapar.\n-Padişah meclis açıp, kapatabilir.\n-Padişah istediğini görevden alabilir.\n-Halk padişahın yanında yönetime ortak olabilir."),
    InfoCardItem("tarih_Info_45","2. Meşrutiyet","-Padişah 2. Abdülhamit'tir.\n-İttihat ve Terakki Cemiyetinin faaliyetleri sonucunda ilan edildi.\n-23 Temmuz 1908'de Kanun-i Esasi tekrar yürürlüğe kondu.\n-İlk kez çok partili hayata geçildi."),
    ]),
    InfoCardModel("Tarih-Dağılma Dönemi Düşünce Akımları", [
    InfoCardItem("tarih_Info_46","Akımlar","-Osmanlıcılık\n-İslamcılık\n-Türkçülük\n-Batıcılık"),
    InfoCardItem("tarih_Info_47","Osmanlıcılık","-Devlet içindeki tüm ulusları din, dil, ırk farkı gözetmeden birleştirmeyi amaçlar.\n-Tanzimat fermanından itibaren benimsenmiştir.\n-Devletin dağılmasına engel olamamıştır."),
    InfoCardItem("tarih_Info_48","İslamcılık","-Bütün müslümanların birleştirilmesini savunur.\n-2. Abdülhamit uygulamaya çalışmıştır."),
    InfoCardItem("tarih_Info_49","Türkçülük","-Milli kültüre dayalı devlet kurmayı benimsemiştir.\n-Ziya Gökalp destek olmuştur.\n-Cumhuriyetin kurulmasında etkilidir.\n-2.Meşrutiyet döneminde güç kazanmıştır."),
    InfoCardItem("tarih_Info_50","Batıcılık","-Batıyı örnek olarak devlet kurmayı destekler.\n-Lale devri ile başlamıştır.\n-Nizam-ı Cedid ilk ciddi batılılaşma hareketidir."),
    ]),
    InfoCardModel("Tarih-1.Dünya Savaşı Öncesi Siyasi Olaylar", [
    InfoCardItem("tarih_Info_51","Trablusgarp Savaşı-1","-1911-1912 yıllarında gerçekleşmiştir.\n-Osmanlı-İtalya arasında oldu.\n-Nedeni İtalya'nın sömürge arayışıdır.\n-Balkan Savaşları başlayınca kaybedildi.\n-18 Ekim 1912'de UŞİ ANTLAŞMASI ile Trablusgarp ve Bingazi İtalya'ya verildi."),
    InfoCardItem("tarih_Info_52","Trablusgarp Savaşı-2","-Mustafa Kemal Kolağası rütbesinde idi.\n-Mustafa Kemal'in ilk askeri başarısıdır.\n-Mustafa Kemal Derne ve Tobruk'ta başarılar kazandı.\n-Uşi Antlaşması ile oniki ada geçici olarak İtalya'ya verildi."),
    InfoCardItem("tarih_Info_53","1.Balkan Savaşı Nedenleri","-1912-1913 arasında gerçekleşmiştir.\n-Osmanlı Devleti'nin Balkanlardaki varlığına son vermek.\n-Rusya'nın Panslavizm politikası.\n-Osmanlı Devleti'nin güçsüzlüğü.\n-Milliyetçilik akımı"),
    InfoCardItem("tarih_Info_54","1.Balkan Savaşı Gelişimi","-Osmanlı Devleti Karadağ, Sırbistan, Bulgaristan ve Yunanistan ile savaşmıştır.\n-Karadağ'ın Osmanlı Devleti'ne saldırmasıyla başladı.\n-Osmanlı Devleti ağır yenilgi aldı."),
    InfoCardItem("tarih_Info_55","1.Balkan Savaşı Yenilgi Nedenleri","-Osmanlı Devleti'nin 4 cephede savaşması.\n-Ordunun siyasetle ilgilenmesi.\n-Komutanlar arasındaki alaylı-mektepli çatışması.\n-Ordunun aynı dönemde kendi içindeki siyasi olaylarla uğraşması."),
    InfoCardItem("tarih_Info_56","1.Balkan Savaşı Sonuçları","-Savaşı Londra Antlaşması bitirmiştir.\n-Batı Trakya, Arnavutluk, Doğu Trakya, Ege Adaları ve Makedonya'yı kaybettik.(BADEM)\n-Osmanlıdan son ayrılan Balkan Devleti Arnavutluk'tur.\n-İttihatçılar Bab-ı Ali Baskını ile yönetimi ele geçirdi."),
    ]),
    InfoCardModel("Tarih-1.Dünya Savaşı Öncesi Siyasi Olaylar-2", [
    InfoCardItem("tarih_Info_57","2.Balkan Savaşı","-1913 yılında gerçekleşmiştir.\n-Bulgaristan; Romanya, Sırbistan, Yunanistan ile savaşmıştır."),
    InfoCardItem("tarih_Info_58","2.Balkan Savaşı Nedenleri","-1.Balkan Savaşında Bulgaristan'ın en büyük payının olması.\n-Osmanlı Devleti'nin Balkanlardan çekilmesiyle oluşan otorite boşluğudur."),
    InfoCardItem("tarih_Info_59","2.Balkan Savaşı Sonuçları","-10 Ağuston 1913 Bükreş Antlaşması imzalandı.\n-Savaşı Bulgaristan kaybetti.\n-İstanbul Antlaşması imzalandı.(1913 Bulgaristan ile imzalandı)\n-Meriç Nehri Bulgaristan ile sınır oldu.\n-Yunanistan ile Atina Antlaşması imzalandı.\n-Kavala-Girit adası Yunanistan'a verildi."),
    InfoCardItem("tarih_Info_60","1. Dünya Savaşı-1","GENEL NEDENLER\n-Sömürge yarışı,\n-Silahlanma yarışı,\n-Milliyetçilik akımı etkileri,\n-Devletler arası bloklaşma,\n-Ham madde-pazar arayışı"),
    InfoCardItem("tarih_Info_61","1. Dünya Savaşı-2","ÖZEL NEDENLER\n-İngiltere-Almanya arasındaki sömürge rekabeti.\n-Almanya-Fransa arasındaki Alsos-Loren sorunu.\n-Rusya ile Avusturya-Macaristan arasındaki Balkanlar sorunu.\n-İtalya'nun Ege denizi ve Balkanlara hakim olmak istemesi."),
    InfoCardItem("tarih_Info_62","1. Dünya Savaşı-3","İTTİFAK DEVLETLERİ\n-Almanya, Avusturya-Macaristan, Osmanlı, Bulgaristan, İtalya(Sonra itilafa geçti)\n\nİTİLAF DEVLETLERİ\n-İngiltere, Fransa, Rusya, İtalya, ABD ve Japonya"),
    InfoCardItem("tarih_Info_63","1. Dünya Savaşı-4","CEPHELER\n-Taaruz: Kanal, Kafkas\n-Savunma: Suriye-Filistin, Çanakkale, Irak-Basra, Hicaz-Yemen\n-Yardım: Makedonya, Galiçya, Romanya\n-NOT: Mustafa Kemal Çanakkale, Kafkas ve Suriye-Filistin cephelerine katıldı."),
    InfoCardItem("tarih_Info_64","Kafkas Cephesi-1","-Osmanlı-Rusya arasında\n-Osmanlı açmıştır.\n-Savaşı kaybedip toprak kazanılan tek cephe"),
    InfoCardItem("tarih_Info_65","Kafkas Cephesi-1","NEDENLERİ\n-Almanya'nın Bakü petrollerini ele geçirmek için Osmanlıyı kışkırtması.\n-Enver Paşa'nın kafkaslara ulaşıp Büyük Türk Devleti kurmak istemesi,\n-Kars, Ardahan, Batum'u Ruslardan geri almak."),
    InfoCardItem("tarih_Info_66","Kafkas Cephesi-1","SONUÇLARI\n-1914 Sarıkamış Harekatı ile 90bin askerimiz donarak şehit oldu.\n-Ruslar Erzurum, Muş, Bitlis ve Erzincan'ı aldılar.\n-Brest Litowsk Antlaşması(3 Mart 1918) ile Ruslar çekildi, cephe kapandı.\n-Kars, Ardahan, Batum Rusya'dan Osmanlı'ya geçti."),
    InfoCardItem("tarih_Info_67","Kanal Cephesi-1","-Osmanlı ile ingilizler arasındadır.\nNEDENLERİ\n-Mısır'ı ingilzlerden geri almak,\n-İngiltere'nin sömürge yolunu kesmek için Almanya'nın talebi"),
    InfoCardItem("tarih_Info_68","Kanal Cephesi-2","SONUÇLARI\n-Osmanlı Devleti kaybetti.\n-Devamında Filistin-Suriye cephesi açıldı."),
    InfoCardItem("tarih_Info_69","Suriye Cephesi","-İngilizler Kudüs'ü ele geçirmiyor.\n-Mustafa Kemal İngilizlerin Halep'in kuzeyinde durdurmuştur."),
    InfoCardItem("tarih_Info_70","Çanakkale Cephesi-1","-İtilaf devletleri savaşı başlattı.\n-19 Şubat 1915'te savaş başladı.\n-18 Mart 1915'te Osmanlı Devleti zafer ilan etti.\n\nNEDENLERİ\n-Rusya'ya yardım etmek.\n-Osmanlı Devleti'ni savaştan çıkartmak."),
    InfoCardItem("tarih_Info_71","Çanakkale Cephesi-2","SONUÇLARI\n-1. Dünya savaşı uzamıştır.\n-Rusya'ya yardım önlenmiştir.\n-Almanya'nın yükü azalmıştır.\n-Rusya savaştan çekilmiştir.\n-Mustafa Kemal tanınmıştır."),
    InfoCardItem("tarih_Info_72","Irak Cephesi-1","-İngilizler açmıştır.\n\nNEDENLERİ\n-Musul petrollerini ele geçirmek.\n-Ruslara yardım etmek\n\nSONUÇLARI\n-Osmanlu Kutül Emare'yi kazandı.\n-İngilizler 1917'de Irak'ı ele geçirdi."),
    InfoCardItem("tarih_Info_73","Hicaz-Yemen Cephesi","-Kutsal yerleri korumak için Osmanlı Devleti açmıştır fakat başarılı olamamıştır."),
    ]),
    InfoCardModel("Tarih-Antlaşmalar", [
    InfoCardItem("tarih_Info_74","Londra Antlaşması","-Rusya-İngiltere-Fransa-İtalya arasında.\n-On iki ada-Antalya ve çevresi İtalya'ya verildi.\n-İtalya, İtilaf devletleri tarafına geçti."),
    InfoCardItem("tarih_Info_75","İstanbul Antlaşması","-Fransa-Rusya-İngiltere arasında imzalandı.\n-Boğazlar Rusya'ya verildi.\n-İngiltere ve Fransa'nın Osmanlı üzerindeki haklarını Rusya tanıyacak."),
    InfoCardItem("tarih_Info_76","Sykes-Picot Antlaşması","-İngiltere-Fransa Osmanlı topraklarını paylaştı."),
    InfoCardItem("tarih_Info_77","Petingrad Protokolü","-Fransa, İngiltere, Rusya arasında imzalandı.\n-Sykes-Picot Antlaşmasını Rusya kabul edecek.\n-Boğazlar bölgesi, Doğu Anadolunun bazı yerleri ve Trabzon Rusya'ya verilecek."),
    InfoCardItem("tarih_Info_78","Saint Jean De Maurienne Antlaşması","-İngiltere-Fransa-İtalya arasında imzalanmıştır.\n-Konya, Antalya, İzmir ve Aydın İtalya'ya verildi."),
    InfoCardItem("tarih_Info_79","Wilson İlkeleri-1","-8 Ocak 1918 de ABD ilan etti.\n-Yenenler, yenilenlerden savaş tazminatı ve toğrak almayacak.\n-Devletler arası anlaşmazlıkları çözmek için örgüt kurulacak."),
    InfoCardItem("tarih_Info_80","Wilson İlkeleri-2","-Osmanlı'da Türkler yoğun oldukları yerlerde devlet kurabilir.\n-Osmanlı'da azınlıklar devlet kurabilir.\nNOT: Wilson İlkeleri savaşın bitişini hızlandırmıştır."),
    InfoCardItem("tarih_Info_81","Mondros Ateşkes Antlaşması-1","-Osmanlı Devleti ile İtilaf Devletleri arasında imzalandı.\n-30 Ekim 1918 tarihlidir.\n-Osmanlı Devletinden Rauf Orbay, İtilaf Devletlerinden İngiliz Amiral Calthorpe imzalamıştır.\n-Çanakkale ve İstanbul Boğazı açılacak, itilaf Devletleri işgal edebilecek."),
    InfoCardItem("tarih_Info_82","Mondros Ateşkes Antlaşması-2","-İtilaf Devletleri güvenliklerini tehdit eden durum olursa stratejik yeri işgal edebilecek.(7. Madde işgallere yasal gerekçedir)\n-6 ilde(Erzurum, Bitlis, Van, Elazığ, Sivas, Diyarbakır) karışıklık çıkarsa işgal edilebilecek.(24. madde amaç Ermeni devleti kurmak)\n-Telsiz, telgraf, kablolar İtilaf Devletleri kontrolünde olacak."),
    InfoCardItem("tarih_Info_83","Mondros Ateşkes Antlaşması-3","-Donanma teslim edilecek.\n-Demiryolu, liman ve tersanelere el konulacak.\n\nNOT: Osmanlı Devleti fiilen sona ermiştir."),
    InfoCardItem("tarih_Info_84","Savaşı Bitiren Antlaşmalar","-Avusturya->Sen Jermen Antlaşması\n-Almanya->Versoy Antlaşması\n-Bulgaristan->Nöyyi Antlaşması\n-Macaristan->Trianon Antlaşması\n-Osmanlı->Sevr Antlaşması"),
    ]),
    InfoCardModel("Tarih-Paris Barış Konferansı", [
    InfoCardItem("tarih_Info_85","Amaç","-1.Dünya savaşında yenilen devletlerin durumlarını belirlemek.\n-Yapılacak antlaşmaların esaslarını belirlemek."),
    InfoCardItem("tarih_Info_86","Özellikleri-1","-32 Devlet katıldı.\n-İngiltere, Fransa, Yunanistan ve Japonya öncü devletler.\n-İzmir'in Yunanistan tarafından işgaline zemin hazırlamıştır."),
    InfoCardItem("tarih_Info_87","Özellikleri-2","-İtalya'ya verilen yerler İngiltere'nin isteğiyle Yunanistan'a verilmiştir.(İngiltere İtalya'yı güçlü gördüğü için)\n-Konferans, Osmanlı Devleti'nin topraklarının paylaşılmasına dönüşmüştür.\n\nNOT: Manda ve himaye fikri ilk kez ortaya atıldı."),
    InfoCardItem("tarih_Info_88","İzmir'in İşgali-1","-15 Mayıs 1919\n-Karar Paris Barış Konferansı'nda alındı.\n-Yunanistan'a İngiiltere destek oldu.\n-Yunanlılara ilk kurşunu İnsan Hakları Gazetesi yazarı Hasan Tahsin(gerçek adı->Osman Recep Nevres)\n-İzmir, İtalya'dan Yunanistan'a geçmiştir."),
    InfoCardItem("tarih_Info_89","İzmir'in İşgali-2","-İngiltere güçlü İtalya istemediği için Yunanistan'a destek olmuştur.\n-Bölgede Rumların çok olması ve Hristiyanların katledilmesi bahane edilmiştir.\n-Amiral Bistrol başkanlığında heyet gönderilmiştir."),
    InfoCardItem("tarih_Info_90","İzmir'in İşgali-3","Amiral Bistrol raporuna göre;\n-Bölgede Türkler çoğunluktadır.\n-Yunanlılar Türkleri katlediyor.\nNOT: Türklerin haklılığını gösteren uluslararası ilk belge Amiral Bistrol Raporudur.\n-Halk kendini savunmuştur ve Kuvayı Milliye ruhu doğmuştur."),
    ]),
    InfoCardModel("Tarih-Kurtuluş Savaşı", [
      InfoCardItem("tarih_Info_91","Cemiyetler-1","AZINLIKLARIN KURDUĞU ZARARLI CEMİYETLER \n-Mavi Mira: İstanbul ve Ege Bölgesini alarak Bizansı tekrar kurmayı amaçlar.\n-Etnik-i Eterya: Yunanistan bağımsızlığını amaçlar.\n-Taşnak-Hınçak: Doğu Anadolu'da Ermeni Devleti kurmayı amaçlamıştır.\n-Pontus Rum: Doğu Karadenizde Pontus Devleti kurmayı amaçlamıştır.",),
      InfoCardItem("tarih_Info_92","Cemiyetler-2","KUVAI MİLLİYE KARŞI ZARARLI CEMİYETLER\n-Sulh ve Selameti Osmaniye: Padişah yanında olunursa ülkenin kurtulacağını savunmuştur.\n-Kürt Teali: Güneydoğuda Kürt devleti kurmayı amaçlamıştır.\n-İslam Teali: Halifeye bağlılığı esas almış, mücadele istememiştir.\n-İngiliz Muhipleri: Kurtuluşu İngiliz himayesinde görmüştür.\n-Wilson Prensipleri: Kurtuluş Amerika himayesinde görmüştür.",),
      InfoCardItem("tarih_Info_93","Cemiyetler-3","YARARLI CEMİYETLER\n-Trakya Paşaeli: Yunan işgaline karşı Edirne'de kurulmuştur.\n-Şark Vilayetleri Müdafai Hukuk: Ermenilere karşı Erzrum'da kurulmuştur.\n-İzmir Müdafai Hukuk: Yunanlılara karşı İzmirde kurulmuştur.",),
      InfoCardItem("tarih_Info_94","Cemiyetler-4","-Kilikyalılar: Ermenilere karşı Adana'da kurulmuştur.\n-Milli Kongre: Tüm dünyaya yurdn işgalinin haksız olduğunu göstermek amaçlanmıştır.\n-İzmir Redd-i İlhak: Yunanlılara karşı İzmir'de kurulmuştur.",),
      InfoCardItem("tarih_Info_95","Kuvay-ı Milliye","Türk halkının İtilaf Devletlerinin işgallerine karşı kurduğu silahlı direniş örgütlerine denir.",),
      InfoCardItem("tarih_Info_96","Kurulma Nedenleri","-Mondros Ateşkes Antlaşmasının 7.maddesine dayanarak Osmanlı topraklarının işgal edilmesii\n-Osmanlı Devleti'nin işgallere sessiz kalması,\n-Azınlıkların olumsuz hareketleri.",),
      InfoCardItem("tarih_Info_97","İlk Direniş","Hatay Dörtyol'da Fransızlara karşı 19 Aralık 1918'de gerçekleşmiştir.",),
    ]),
    InfoCardModel("Tarih-Mustafa Kemal'in Samsun'a Çıkışı", [
      InfoCardItem("tarih_Info_98","","Mustafa Kemal'in Samsun'a çılış tarihi 19 Mayıs 1919'dur.",),
      InfoCardItem("tarih_Info_99","Gönderilme Sebepleri","-Bölgedeki direniş hareketlerini önlemek,\n-Halktaki silah ve cephaneleri toplamak,\n-Milli cemiyetlerin girişimlerine izin vermemektir.",),
      InfoCardItem("tarih_Info_100","Gidişi ve Önemi","-Mustafa Kemal 9.Ordu Müfettişi olarak gitmiştir.\n-Milli Mücadele fiilen başlamıştır.\n-Amaç Türk Devleti kurmaktır.",),
      InfoCardItem("tarih_Info_101","Havza Genelgesi","29 Mayıs 1919 da yayınlanmıştır.",),
      InfoCardItem("tarih_Info_102","Havza Genelgesi Amaç","-Milli bilincin oluşmasını sağlamaktır.\n-Türk halkının işgallere karşı durmasını sağlamaktır.",),
      InfoCardItem("tarih_Info_103","Havza Genelgesi'nde","-İşgallere karşı halkın protesto yapması,\n-Direniş cemiyetlerinin kurulması,\n-İstanbul Hükümeti'ne işgalleri kınayan telgraf çekilmesi,\n-Azınlıklara taşkınlık yapmamasının istenmes istenmiştir.\n-Mustafa Kemal İstanbul'a geri çağırılmış fakat gitmemiştir.",),
      InfoCardItem("tarih_Info_104","Amasya Genelgesi","22 Haziran 1919 da yayınlanmıştır.",),
      InfoCardItem("tarih_Info_105","Amasya Genelgesi Amaç","-Milli mücadeleyi kişisellikten çıkarıp halktaki etkisini arttırmaktır.\n-Mustafa Kemal'e Ali Fuat Cebesoy, Rauf Orbay, Refet Bele, Cemal Paşa(Konya) ve Kazım Karabekir (Erzurum) destek olmuştur.",),
      InfoCardItem("tarih_Info_106","Amasya Genegesi Maddeleri-1","-Vatanın bütünlüğü ve milletin bağımsızlığı tehlikededir.\n-İstanbul Hükümeti üzerine düşen görev ve sorumluluğu yerine getirmemektedir.\n-NOT: Bu maddeler Kurtuluş Savaşı'nın gerekçeleridir.",),
      InfoCardItem("tarih_Info_107","Amasya Genegesi Maddeleri-2","--Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır.(Ulusal Egemenlik vurgusu, Kurtuluş savaşı amaç ve yöntemi)\n-Milletin sesini duyurmak için her türlü denetimden uzak milli bir kurul oluşturulmalıdır.(Temsil Heyeti fikri)\n-NOT: Sivas Kongresi kararı verilmiştir.",),
      InfoCardItem("tarih_Info_108","Erzurum Kongresi","-23 Temmuz-7 Ağustos tarihleri arasında gerçekleşti.\n-Doğu Anadolu Müdafa-i Hukuk Cemiyeti topladı.\n-Mustafa Kemal kongre başkanıydı.\n-Toplanış şekli bölgesel, alınan kararlar ulusaldır.",),
      InfoCardItem("tarih_Info_109","Erzurum Kongresi Maddeleri-1","-Milli sınırlarımız içinde vatan bütündür, parçalanamaz.\n-Kuvay-i Milliye'yi etkin, Milli iradeyi hakim kılmak esastır.\n-Manda ve himaye kabul edilemez.\n-İstanbul Hükümeti görevini yapmazsa geçici hükümet kurulacaktır.",),
      InfoCardItem("tarih_Info_110","Erzurum Kongresi Maddeleri-2","-İşgaller karşısında Osmanlı Devleti dağılırsa millet kendini savunacaktır.\n-Mebusan Meclisi derhal toplanmalı, hükümet meclis denetiminde çalışmalıdır.",),
      InfoCardItem("tarih_Info_111","Erzurum Kongresinin Önemi","-Milli sınırdan ilk kez bahsedilmiştir.\n-Manda ve himaye ilk kez reddedilmiştir.\n-Amaç tam bağımsızlıktır vurgusu vardır.\n-Yeni devlet kurma düşüncesi ilk kez dile getirilmiştir.",),
      InfoCardItem("tarih_Info_112","Sivas Kongresi","-4-11 Eylül 1919 da gerçekleştirilmiştir.\n-Kongre başkanı Mustafa Kemal'dir.\n-Milli Kongredir.\n-Sivas işgal edilmediği için ve ulaşım imkanlarından dolayı tercih edilmiştir.",),
      InfoCardItem("tarih_Info_113","Sivas Kongresi Bilgileri-1","-Erzurum Kongresi kararları kabul edilmiştir.\n-Manda ve himaye KESİN olarak reddedilmiştir.\n-Yararlı cemiyetler, Anadolu ve Rumeli Müdafaai Hukuk Cemiyeti olarak birleştirilmiştir.\n-İrade-i Milliye gazetesi yayımlandı.",),
      InfoCardItem("tarih_Info_114","Sivas Kongresi Bilgileri-2","-İstanbul Hükümeti kongreyi dağıtmak için Mustafa Kemal'i tutuklama emri vermiştir, ancak engellenememiştir.\n-Emir Elazığ Valisi Ali Galip'e verilmiştir.\n-Temsil Heyeti Ali Fuat Cebesoy'u batı cephesine atadı.",),
      InfoCardItem("tarih_Info_115","Temsil Heyeti'nin Ankara'ya Gelişi","-27 Aralık 1919 tarihinde gerçekleşmiştir.\nAnkara'nın Seçilme Nedenleri\n-Merkezi olması,\n-Güvenlikli olması,\n-Anadolu ile ulaşım ve haberleşmenin iyi olması.\n-Yunanlılarla mücadelede Batı Cephesine yakın olması.",),
    ]), InfoCardModel("Tarih-Osmanlı Mebusan Meclisi ve Misak-ı Milli", [
      InfoCardItem("tarih_Info_116","","-İstanbul'da 12 Ocak 1920'de toplandı.\n-Felah-ı Vatan(vatanın kurtuluşu) grubu kuruldu.\n28 Ocak 1920'de Misak-ı Milli ilan edilmiştir.",),
      InfoCardItem("tarih_Info_117","Misak-ı Milli Kararları-1","-Mondros Ateşkes Antlaşması imzalandığında işgal edilmemiş topraklar ayrılmaz bir bütündür.\n-Marmara ve İstanbul'un güvenliği sağlanırsa Boğazlar uluslararası ticarete açılabilir.\n-Siyasi, ekonomik, milli gelişimimizi engelleyen sınırlamalar kabul edilemez.",),
      InfoCardItem("tarih_Info_118","Misak-ı Milli Kararları-2","-Azınlıklara, yabancı ülkelerdeki müslümanların hakları kadar hak tanınacak.\n-Trakya, Kars, Ardahan, Batum ve arapların bulunduğu yerlerde gerekirse halk oylaması yapılacak.",),
      InfoCardItem("tarih_Info_119","Misak-ı Milli Kararları-3","Kararlar ile ilgili ipuçları;\n-Ülke bütünlüğünden bahsedildi, Milli sınırlar kesin olarak belirlendir.\n-Askeri ve siyasi bağımsızlık vurgusu yapıldı.\n-Tam bağımsızlık vurgusu yapıldı.\n-Uluslararası eşitlik kabul edildi.\nMisak-ı Milli İstanbul'un 16 Mart 1920'de işgal edilmesine sebep oldu.",),
      InfoCardItem("tarih_Info_120","TBMM'nin Açılması","-23 Nisan 1920'de açıldı.\n-M.Kemal Ankara Milletvekili oldu.\n-M.Kemal meclis başkanı seçildi.\n-Yasama, yürütme ve yargı TBMM'ye aittir.(Güçler birliği)\n-Kurucu meclistir.\n-Meslis Hükümeti sistemi mevcuttur.\n-Mesli üstünde hiçbir güç ve makam yoktur.",),
      InfoCardItem("tarih_Info_121","TBMM'ye Karşı Ayaklanmalar-1","-İstanbul Hükümeti->Anzavur ve Kuvay-ı İnzibatiye\n-İstanbul Hükmeti ve İtilaf Devletlerinin Beraber Çıkarttıkları->Bolu-Düzce-Hendek-Adapazarı, Konya, Milli Aşireti, Afyon ve Yozgat isyanları",),
      InfoCardItem("tarih_Info_122","TBMM'ye Karşı Ayaklanmalar-2","-Azınlıkların Çıkardıkları->Pontus Rum ve Ermeni İsyanları\n-Kuvay-ı Milliyecilerin Çıkardıkları->Çerkez Ethem ve Demirci Mehmet Efe isyanları",),
      InfoCardItem("tarih_Info_123","TBMM'nin Ayaklanmalara Aldığı Tedbirler","-İstanbul Hükümeti ile bağlantılar kesildi.\n-Hıyanet-i Vataniye Kanunu çıkarıldı.\n-İstanbul'un fetvalarına karşı Ankara Müftüsü Rıfat Börekçi'ye karşı fetva hazırlatıldı.\n-İstiklal Mahkemeleri kuruldu.",),
    ]),InfoCardModel("Tarih-Sevr Antlaşması", [
      InfoCardItem("tarih_Info_124","","10 Ağustos 1920'de imzalanmıştır.\n-İtalya'nın San Remo kentinde yapıldı.\n-Damat Ferit imzaladı.",),
      InfoCardItem("tarih_Info_125","Sevr Notları","Osmanlı Devleti resmen sona ermiştir.\n-Osmanlı Devletinin imzaladığı son antlaşmadır.\n-TBMM tarafından onaylanmamıştır.\n-Hukiki geçerliliği yoktur.",),
      InfoCardItem("tarih_Info_126","Sevr-Siyasi Maddeleri","-Boğazları uluslararası komisyon yönetecek.(Bağımsızlığa aykırı)\n-Azınlıklara geniş haklar verilecek.(Bağımsızlığa aykırı)\n-Doğu Anadolu'da yeni iki devlet kurulacak.(Misak-ı Milliye aykırı)",),
      InfoCardItem("tarih_Info_127","Sevr-Askeri Maddeler","-Askerlik zorunlu olmayacak.\n-Osmanlı ordusu sınırlandırılacak, ordunun ağır silahı olmayacak.",),
      InfoCardItem("tarih_Info_128","Sevr-Ekonomik Maddeler","Kapitülasyonlardan bütün devletler yararlanacak.\n-Osmanlı Devleti savaş tazminatı ödeyecek.",),
    ]),InfoCardModel("Tarih-Cepheler ve Antlaşmalar", [
      InfoCardItem("tarih_Info_129","Doğu Cephesi","-Ermenilerle savaşıldı.\n-15.Kolordu Komutanı Kazım Karabekir Paşa yönetti.\n-Ermeniler yenilgiye uğratıldı.\n-TBMM ve Ermeniler arasında Gümrü Antlaşması imzalandı.",),
      InfoCardItem("tarih_Info_130","Gümrü Antlaşması","-3 Aralık 1920'de imzalandı.\n-1878'de Rusya'ya verilen Kars ve çevresi geri alındı.\n-Ermeni devleti kurma fikri yıkıldı.\n-TBMM'nin uluslararası alandaki ilk siyasi başarısıdır.\n-Gürcistan ile sınır komşusu olduk.\n-Ermeniler, Sevr Antlaşmasını tanımadı.",),
      InfoCardItem("tarih_Info_131","Güney Cephesi","-Kuvay-ı Milliye ve Fransızlar-Ermeniler arasında yapıldı.\n-Fransızlar 11 Şubat 1920'de Maraştan, 10 Nisan 1920'de Urfa'dan kovuldu.\n-Ankara Antlaşması ile cephe kapandı.",),
      InfoCardItem("tarih_Info_132","Ankara Antlaşması","-20 Ekim 1920'de imzalandı.\n-TBMM ile Fransızlar arasında imzalandı.\n-Hatay dışında Suriye sınırımız çizildi.\n-İki taraf arasındaki savaş sona erecek.\n-Fransızlar geri çekilecek.\n-Güney cephesi kapandı.\n-Hatay'ın Fransa'ya verilmesi 2.tavizdir.",),
      InfoCardItem("tarih_Info_133","Batı Cephesi","-Açılma sebebi İzmir'in işgalidir.\n-Yunanlılarla savaşılmıştır.\n-Yunanlıların amacı Sevr'i kabul ettirmektir.\n-En uzun süren cephedir.\n-Mudanya Ateşkes Antlaşmasıyla kapanmıştır.",),
      InfoCardItem("tarih_Info_134","I. İnönü Savaşı-1","-6-10 Ocak 1921 tarihleri arsında yapıldı.\n-Düzenli Türk Ordusu ile Yunanlılar arsında yapıldı.\n-Kazanan Türk Ordusudur.\n-Düzenli Ordunun ilk zaferidir.\n-TBMM'ye güven arttı.",),
      InfoCardItem("tarih_Info_135","I. İnönü Savaşı-2","-1921 Anayasası ilan edildi.(Teşkilat-ı Esasiye)\n-İstiklal Marşı kabul edildi.(12 Mart 1921)\n-Çerkez Ethem ayaklanması bastırıldı.\n-Sovyet Rusya ile Moskova Antlaşması imzalandı.\n-İtilaf Devletleri ile Londra Konferansı yapıldı.\n-Afganistan ile Dostluk Antlaşması yapıldı.",),
      InfoCardItem("tarih_Info_136","II. İnönü Savaşı","-26 Mart-1 Nisan 1921 arasında yapıldı.\n-Düzenli Türk Ordusu ile Yunanistan arasında yapıldı.\n-Kazanan Türk Ordusudur.\n-TBMM'ye güven daha da artmıştır.\n-İtalya işgal ettiği bölgelerden çekildi.",),
      InfoCardItem("tarih_Info_137","Eskişehir-Kütahya Savaşları-1","-10-24 Temmuz 1921 tarihlerinde yapıldı.\n-Türk Ordusu ile Yunanistan arasında yapıldı.\n-Kütahya, Eskişehir ve Afyon Yunanlılara geçti.\n-Türkler Sakarya ırmağının doğusuna çekildi.",),
      InfoCardItem("tarih_Info_138","Eskişehir-Kütahya Savaşları-2","-Meclisin tüm yetkileri ve başkomutanlık 3 aylığına Mustafa Kemal'e verildi.(5 Ağustos 1921)\n-Ordunun ihtiyaçları için Tekalif-i Milliye emri verildi.\n-Batı Cephesindeki ilk ve tek yenilgidir.",),
      InfoCardItem("tarih_Info_139","Sakarya Savaşı-1","-23 Ağustos-12 Eylül 1921 tarihleri arasında yapıldı.\n-Türk Ordusu ile Yunanlılar arasında yapıldı.\n-Türk Ordusu kazandı.\n-Taaruza geçildi.\n-Mustafa Kemal'e Gazilik ve Mareşallik verildi.",),
      InfoCardItem("tarih_Info_140","Sakarya Savaşı-2","-30 Ekim 1921'de Fransa ile Ankara Antlaşması imzalandı.\n-13 Ekim 1921'de Gürcistan, Azerbaycan ile Kars Antlaşması imzalandı.\n-İtalyanlar Anadoludan tamamen çekildi.\n-Doğu sınırlarımız kesin olarak Kars Antlaşması ile çizildi.",),
      InfoCardItem("tarih_Info_141","Büyük Taaruz ve Başkomutanlık Meydan Muhaberesi","-26-30 Ağustos 1922 tarihleri arasında yapıldı.\n-Başkomutan M.Kemal yönetti.\n-Yunanlılar yok edildi.\n-Yunan işgali sonlandı.\n-9 Eylül 1922!swe Türk Ordusu İzmir'e girdi.\n-Mudanya Ateşkes Antlaşması yapıldı.",),
      InfoCardItem("tarih_Info_142","Mudanya Ateşkes Antlaşması","-11 Ekim 1922'de imzalandı.\n-TBMM (İsmet Paşa) ile Fransa, İngiltere ve İtalya arasında imzalandı.\n-Yunanistan'ı İngiltere temsil etti.\n-İstanbul, Boğazlar ve Doğu Trakya TBMM'ye geçti.\n-Milli Mücadelede askeri dönem bitti.\n-Mondros Ateşkes Antlaşmasının hükmü sona erdi.",),
      InfoCardItem("tarih_Info_143","Lozan Barış Antlaşması-1","-24 Temmuz 1923'de imzalandı.\n-Katılan Devletler-> Türkiye, Fransa, İngiltere, Yunanistan, İtalya, Japonya, Yugoslavya, Romanya, Portekiz ve Belçika.\n-Boğazlar sorunu görüşülürken Sovyet Rusya ve Bulgaristan katıldı.\n-ABD gözlemciydi.\n-TBMM adına İsmet Paşa katıldı.",),
      InfoCardItem("tarih_Info_144","Lozan Barış Antlaşması-2","SINIRLAR\n-Suriye Sınırı-> Hatay Misak-ı Milli dışında Ankara Antlaşması esas alındı.\n-Irak Sınırı-> Çözülmedi. Türkiye-İngiltere daha sonra görüşecek.\n-Batı Sınırı-> Meriç Nehri",),
      InfoCardItem("tarih_Info_145","Lozan Barış Antlaşması-3","ADALAR\n-Bozcaada ve Gökçeada Türkiye'ye verildi.\n-Onikiada İtalya'ya verildi.\n-Diğer Ege adaları Yunanistan'a verildi.",),
      InfoCardItem("tarih_Info_146","Lozan Barış Antlaşması-4","-Türkiye'deki tüm azınlıklar Türk vatandaşı sayıldı.\n-Kapitülasyonlar tamamen kaldırıldı.\n-Boğazlar Başkanı Türk olan uluslararası komisyona bırakıldı.(Egemenliğe aykırı)\n-Dış borçlar Osmanlı Devleti'nden ayrılan devletlere paylaştırıldı.",),
      InfoCardItem("tarih_Info_147","Lozan Barış Antlaşması-5","-Yabancı okullar Türk kanunlarına göre eğitim verecek.\n-Savaş tazminatı olarak Yunanistan Karaağaç'ı Türkiye'ye verecek.\n-Patrikhane Türkiye aleyhinde faaliyetlerde bulunmamak kaydıyla açık kalacak.",),
      InfoCardItem("tarih_Info_148","Lozan Barış Antlaşması-6","-Musul Sorunu çözülemeyen tek sorundur.\n-M. Kemal'in taviz verilmemesini istediği iki konu Misak'ı Milli ve kapitülasyonlardır.\n-Türkiye adına çözülemeyen konular Musul, Ege Adaları, Boğazlar ve Hatay'dır.\n-Günümüze kadar yürürlükte kalmıştır.",),

    ]),
    InfoCardModel("Tarih-İnkilaplar", [
      InfoCardItem("tarih_Info_149","İzmir İktisat Kongresi-1","-17 Şubat 1923'de yapılmıştır.\n-Türk Devletinin ekonomi politikasını belirler.\n-Küçük işletmeler yerine fabrikalar oluşturulmalı.\n-Ulaşımda demiryolu tercih edilmeli.\n-Sanayi ürünlerinin hammaddesi yurtiçinden alınmalı.\n-Milli bankalar oluşturulmalı.",),
      InfoCardItem("tarih_Info_150","İzmir İktisat Kongresi-2","-Yabancılardaki işletmeler millileştirilmeli.\n-Kapitülasyonlar kaldırılmalı.\n-Misak-ı İktisadi(Ekonomi Andı) kabul edildi.\n-Halkçılık, milliyetçilik, devletçilik ilkeleri benimsenmiştir.",),
      InfoCardItem("tarih_Info_151","Cumhuriyet'in İlanı","-Kabine sistemine geçildi.\n-M.Kemal ilk Cumhurbaşkanı oldu.\n-İsmet İnönü ilk Başbakan oldu.\n-İlk Meclis Başkanı Fethi Okyar oldu.",),
      InfoCardItem("tarih_Info_152","Siyasi Alanda Yapılan İnkilaplar-1","-TBMM'nin açılışı 23 Nisan 1920\n-Saltanatın kaldırılması 1 Kasım 1922\n-Ankara'nın başkent olması 13 Ekim 1923\n-Cumhuriyet'in ilanı 29 Ekim 1923\n-Halifeliğin kaldırılması 3 Mart 1924",),
      InfoCardItem("tarih_Info_153","Siyasi Alanda Yapılan İnkilaplar-2","-Çok partili hayata geçiş denemeleri\n-Terakkiperver Cumhuriyet Fırkası 3 Haziran 1925\n-Serbest Cumhuriyet Fırkası 12 Ağustos 1930\n-Kadınlara seçme-seçilme hakkının verilmesi.",),
      InfoCardItem("tarih_Info_154","Hukuk Alanında Yapılan İnkilaplar","-1921 Anayasası 20 Ocak 1921\n-1924 Anayasası 20 Nisan 1924\n-Medeni Kanun 17 Şubat 1926\n-Türk Ceza Kanunu 1 Mart 1926\n-Borçlar Kanunu 22 Nisan 1926\n-Ticaret Kanunu 29 Nisan 1926",),
      InfoCardItem("tarih_Info_155","Eğitim Alanında Yapılan İnkilaplar","-Tevhid-i Tedrisat Kanunu 3 Mart 1924\n-Latin harflerinin kabulü 1 Kasım 1928\n-Türk Tarih Kurumu ve Türk Dil Kurumu'nun kurulması 15 Nisan 1931",),
      InfoCardItem("tarih_Info_156","Sosyal Alanda Yapılan İnkilaplar","-Şapka Kanunu 25 Kasım 1925\n-Tekke, zaviye ve türbelerin kapatılması 30 Kasım 1925\n-Miladi Takvimin kullanılması\n-Kadınların belediye(1930), muhtarlık(1933), milletvekili(1934) seçimlerine katılması\n-Soyadı Kanunu(1934)",),
      InfoCardItem("tarih_Info_157","Ticaret Alanında Yapılan İnkilaplar","-Kabotaj Kanunu'nun çıkarılması(1926)\n-Türkiye İş Bankası'nın kurulması(1934)",),
      InfoCardItem("tarih_Info_158","Ekonomik Alanda Yapılan İnkilaplar","-İzmir iktisat Kongresi\n-Misak-ı İktisadi",),
      InfoCardItem("tarih_Info_159","Tarım Alanında Yapılan İnkilaplar","-Aşar Vergisinin kaldırılması(1925)\n-Tarım Kredi Kooperatiflerinin kurulması\n-Ziraat Bankası'nın imkanlarının arttırılması\n-Yüksek Ziraat Enstitüsü kurulması(1933)\n-Toprak Mahsülleri Ofisinin kurulmsı(1938)\n-Atatürk Orman Çiftliği'nin kurulması",),
      InfoCardItem("tarih_Info_160","Sanayi Alanında Yapılan İnkilaplar","-Teşvik-i Sanayi Kanunu'nun çıkarılması(1926)\n-Beş yıllık kalkınma planının yapılması\n-Karabük Demircilik İşletmesi'nin açılması\n-Maden Tetkik ve Arama Enstitüsü'nün Kurulması",),
      ]),
    InfoCardModel("Tarih-Atatürk İlkeleri", [
      InfoCardItem("tarih_Info_161","İlkeler","-Cumhuriyetçilik\n-Milliyetçilik\n-Halkçılık\n-Laiklik\n-Devletçilik\n-İnkilapçılık",),
      InfoCardItem("tarih_Info_162","Cumhuriyetçilik","-Egemenlik millete aittir.\n-Halk oyuyla seçim yapılır.\n\nİLGİLİ İNKİLAPLAR\n-Saltanatın ve halifeliğin kaldırılması\n-Cumhuriyetin ilanı\n-TBMM'nin açılması\n-Çok partili hayat\n-Anayasaların kabulü\n-Kadınlara verilen seçme-seçilme hakkı",),
      InfoCardItem("tarih_Info_163","Milliyetçilik","-Ulusal birlik, beraberlik amaçlanır.\n\nİLGİLİ İNKİLAPLAR\n-Türk Dil Kurumunun açılması\n-Türk Tarih Kurumunun açılması\n-Kapitülasyonların kaldırılması\n-Kabotaj Kanunun kabulü",),
      InfoCardItem("tarih_Info_164","Halkçılık-1","-Herkes kanun önünde eşittir.\n-Halk kendi kendine yönetir.\n-Devletin halkına hizmet etmesi esastır.\n-Devletin halkına hizmet etmesi esastır.",),
      InfoCardItem("tarih_Info_165","Halkçılık-2","\n\nİLGİLİ İNKİLAPLAR\n-Soyadı Kanunu\n-Kadınlara verilen siyasal haklar\n-Medeni Kanunun kabulü\n-Aşar Vergisinin kaldırılması\n-Kılık Kıyafet Kanunun kabulü\n-Millet Mekteplerinin açılması\n-Toplumda ayrıcalık belrtilen ünvanların kaldırılması",),
      InfoCardItem("tarih_Info_166","Devletçilik","-Ekonomi politikası\n-Hizmetlerin devlet eliyle yapılması\n\nİLGİLİ İNKİLAPLAR\n-İzmir İktisat Kongresi\n-I.Beş Yıllık Kalkınma Planı\n-Teşvik-i Sanayi Kanunu\n-Devlet Bankalarının kurulması",),
      InfoCardItem("tarih_Info_167","Laiklik-1","Din ve Devlet işlerinin birbirinden ayrılması.\n-Din, vicdan özgürlüğü",),
      InfoCardItem("tarih_Info_168","Laiklik-2","İLGİLİ İNKİLAPLAR\n-Saltanatın ve halifeliğin kaldırılması\n-Medreselerin kapatılması\n-Tevhid-i Tedrisat Kanunu\n-Tekke ve Zaviyelerin kapatılması\n-Evkaf ve Şer'iyye Vekaletinin kaldırılması\n-Medeni Kanununun kabulü\n-Anayasa'dan 'Devletin Dini İslamdır' maddesinin kaldırılması",),
      InfoCardItem("tarih_Info_169","İnkilapçılık","-Toplum yapısında yapılan köklü değişimlere denir.\n-Bütün inkilaplar bu ilke ile ilgilidir.\n-Sürekli çağdaşlaşmayı ve değişmeyi amaçlar.",),
    ]),
    InfoCardModel("Tarih-Mustafa Kemal Atatürk'ün Hayatı", [
      InfoCardItem("tarih_Info_170","","-1881'de Selanik'te doğdu.\n-Annesi Zübeyde Hanum, babası Ali Rıza Bey'dir.",),
      InfoCardItem("tarih_Info_171","Okuduğu Okullar","-Mahalle mektebi\n-Şemsi Efendi İlkokulu\n-Selanik Mülkiye Rüştiyesi\n-Selanik Askeri Rüştiyesi(Kemal adını aldı)\n-Manastır Askeri İdadisi\n-İstanbul Harp Okulu\n-İstanbul Harp Akademisi\n-Akademiden Kurmay Yüzbaşı olarak mezun oldu\n-İlk görev yeri Şam'dır",),
      InfoCardItem("tarih_Info_172","Eserleri","-Nutuk\n-Geometri Kitabı\n-Vatandaş İçin Medeni Bilgiler\n-Cumalı Ordugahı\n-Zabit ve Kumandan ile Hasbihal\n-Tabiye ve Tatbikat Seyahati\n-Bölüğün Muharebe Talimi\n-Takımın Muharebe Talimi",),
      InfoCardItem("tarih_Info_173","Görevleri-1","-Şam-> 5. Ordu\n-31 Mart Olayını bastırmak için Hareket Ordusu\n-Trablusgarb Savaşı(Binbaşı)\n-Balkan Savaşları->Sofya Ataşemiliterliği\n-I. Dünya Savaşı 19. Tümen Komutanlığı\n-Çanakkale Cephesi->Albay",),
      InfoCardItem("tarih_Info_174","Görevleri-2","-Kafkas Cephesinde->Tuğgeneral\n-Suriye-Filistin Cep->Yıldırım Orduları Grup Komutanı\n-Sakarya Savaşı->Başkomutan\n-İlk TBMM Başkanı\n-İlk Cumhurbaşkanı",),
      InfoCardItem("tarih_Info_175","Etkilendiği Yazarlar","-Ziya Gökalp\n-Namık Kemal\n-Memet Emin Yurdakul\n-Tevfik Fikret",),
      InfoCardItem("tarih_Info_176","Söylediği Sözler-1","Çanakkale Savaşı\n-'Ben size taaruzu değil, ölmeyi emrediyorum'",),
      InfoCardItem("tarih_Info_177","Söylediği Sözler-2","Başkomutanlık Meydan Muharebesi\n-'Ordular' İlk hedefiniz Akdeniz'dir, ileri'",),
      InfoCardItem("tarih_Info_178","Söylediği Sözler-3","Sakarya Savaşı\n-'Hattı müdafaa yoktur, sathı müdafaa vardır. O satıh bütün vatandır. Vatanın her karış toprağı vatandaşın kanıyla sulanmadıkça terk edilemez.'",),
      InfoCardItem("tarih_Info_179","Söylediği Sözler-4","II. İnönü Savaşı\n-'Siz orada yalnız düşman değil, milletin makus tarihini de yediniz'",),
      InfoCardItem("tarih_Info_180","Türkiye Cumhuriyeti Cumhurbaşkanları-1","-Mustafa Kemal Atatürk\n-İsmet İnönü\n-Celal Bayar\n-Cemal Gürsel\n-Cevdet Sunay\n-Fahri Korutürk",),
      InfoCardItem("tarih_Info_181","Türkiye Cumhuriyeti Cumhurbaşkanları-2","-Kenan Evren\n-Turgut Özal\n-Süleyman Demirel\n-Ahmet Necdet Sezer\n-Abdullah Gül\n-Recep Tayyip Erdoğan",),
    ]),
    InfoCardModel("Tarih-Dış Politikadaki Gelişmeler", [
      InfoCardItem("tarih_Info_182","Yabancı Okullar Meselesi-1","Yabancı okullarla ilgili kararlar Lozan'da alınmıştır. Buna göre\n\n-Türk kanunlarına bağlı olacak\n-Maarif Vekaleti denetleyecek\n-Türk Dili, Tarihi ve Coğrafyası okutulacak",),
      InfoCardItem("tarih_Info_183","Yabancı Okullar Meselesi-2","-Bu kararları bazı yabancı okullar istemedi.\n-Türkiye bu sorunu iç mesele olarak gördü ve geri adım atmadı.\n-Kurallara uymayan okullar kapatıldı.",),
      InfoCardItem("tarih_Info_184","Musul Meselesi-1","NOT-Musul'un kaybedilme sebebi Şeyh Sait ayaklanmasıdır.\n-İngiltere Mondros Ateşkes Antlaşmasına dayanarak işgal etti.\n-Lozan'da anlaşma sağlanamadı.\n-Sorun Milletler Cemiyetine götürüldü.",),
      InfoCardItem("tarih_Info_185","Musul Meselesi-2","-Sonra Lahey Adalet Divanına götürüldü ancak sonuç çıkmadı.\n-1926'da Ankara Antlaşması imzalandı. Buna göre\n\n-Musul Irak'a bırakılacak.\n-Irak, Musulda'ki petrol gelirlerinin %10'unu 25 yıl Türkiye'ye verecek.\n-Türkiye Irak sınırı çizildi.",),
      InfoCardItem("tarih_Info_186","Milletler Cemiyetine Giriş","-1932'de girildi.\n-İspanya temsilcisi teklif etti.\n-Yunanistan destek oldu.",),
      InfoCardItem("tarih_Info_187","Balkan Atantı","-İtalya ve Almanya dünya barışını silahlanarak tehdit ettiler.\n-Bu sebeple Türkiye, Yunanistan, Yugoslavya ve Romanya 9 Şubat 1934'te imzaladı.",),
      InfoCardItem("tarih_Info_188","Montrö Sözleşmesi-1","-20 Temmuz 1936'da imzalandı.\n-Boğazlar komisyonu kaldırılacak, bütün yetkiler Türklerde olacak.\n-Ticaret gemileri serbest gezebilecek.",),
      InfoCardItem("tarih_Info_189","Montrö Sözleşmesi-2","-Türkiye Boğazlarda asker bulunduracak.\n-Harp gemilerinin geçişi sınırlandıracak.\n-Olası savaş durumunda, Boğazları istediğine açıp kapatabilecek.\n-Boğazların kontrolü kesin olarak Türkiye'ye geçmiştir.",),
      InfoCardItem("tarih_Info_190","Hatay'ın Anavatana Katılması-1","-1921'de Ankara Antlaşması ile Fransa mandasındaki Suriye'ye verilmiştir.\n-Fransa, Suriye'deki manda yönetimini 1936'da sonlandırdı.\n-Türkiye, Hatay sorununun çözümü için Milletler Cemiyetine başvurdu.\n-Bu görüşmelerde Hatay'ın geleceğini halkın belirlemesi ilkesi kabul edildi.",),
      InfoCardItem("tarih_Info_191","Hatay'ın Anavatana Katılması-2","-1938'de Hatay Bağımsız Cumhuriyeti kuruldu.\n-29 Haziran 1939'da Türkiye'ye oy birliği ile bağlandı.\n-Misak-ı Milliye son katılan topraktır.\n-Hatay Bağımsız Cumhuriyeti'nin ilk başkanı Tayfun Sökmen'dir.\n-Atatürk hasta olmasına rağmen şahsi meselem demiştir.",),
    ]),
    ///COĞRAFYA
    InfoCardModel("Coğrafya-Türkiye'nin Konumu", [
      InfoCardItem("cografya_Info_1","Coğrafi Konum-1","-Dünya üzerindeki konuma Coğrafi Konum denir.\n-Türkiye; Avrupa, Asya ve Afrika arasında köprüdür.\n-Doğu, batı arasında bağlantı yeridir.\n-İpek, Baharat yolu buradan geçer.\n-Eski uygarlıkların izlerini taşır.",),
      InfoCardItem("cografya_Info_2","Coğrafi Konum-2","-Üç tarafı denizlerle çevrilidir.\n-İklim çeşitliliği vardır.\n-Tarihi ve doğal güzellikleri mevcuttur.\n-İstanbul ve Çanakkale Boğazları bulunur.\n-Yeraltı ve yer üstü kaynakları bakımından zengindir.\n-Batıdan doğuya yükseklik artar.",),
      InfoCardItem("cografya_Info_3","Matematik Konum-1","-Enlem ve boylama göre bulunduğumuz yere denir.\n-Türkiye; başlangıç meridyeninin doğusunda, ekvatorun kuzeyindedir.\n-26°-45° doğu meriyeni, 36°-42° kuzey paralelleri arasındadır.\n-Meridyenler arası zaman farkı 4 dakikadır.",),
      InfoCardItem("cografya_Info_4","Matematik Konum-2","-En batı ile en doğu arası 76 dakikadır.\n-En batısı Gökçeada, \n-En doğusu Türkiye Ermenistan İran ve Nahcivan sınırlarının kavşak noktası\n-En kuzeyi Sinop İnce Burun,\n-En güneyi Hatay Beysen köyü",),
      InfoCardItem("cografya_Info_5","Matematik Konum-3","-Kuzey-Güney arasında 6 eylem vardır.\n-Kuzey-güney arası 600 km iken doğu-batı arası 1500 km'dir.",),
      InfoCardItem("cografya_Info_6","Türkiye'nin Sınırları","Komşu ülkeler;\n-Yunanistan, Bulgaristan, Ermenistan, Irak, Gürcistan, Suriye, Nahçivan.\n\nGümrük Kapıları;\n-Yunanistan-> İpsala\n-Bulgaristan-> Kapıkule\n-İran-> Gürbulak, Esendere\n-Suriye-> Cilvegözü, Öncüpınar\n-Ermenistan-> Akkaya",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'nin Dağları", [
      InfoCardItem("cografya_Info_7","Kuzey Anadolu Dağları","-Sarp ve yüksektir.\n-En yüksek dağlar burada bulunur.\n-Kaçkar Dağı, Doğu Karadeniz'in en yüksek dağıdır.\n-Küre, Giresun, Canik, Kalkanlı, Gümüşhane, Rize, Trabzon, Köroğlu, Ilgaz, Yıldız, Deveci, Mescid, Çamlıbel dağları bulunur.",),
      InfoCardItem("cografya_Info_8","Güney Anadolu Dağları","Batı Toroslar;\n-Dedegöl, Geyik, Sultan, Ak ve Boz Dağlar.\nOrta Toroslar;\n-Binboğa, Tahtalı, Bolkar, Aladağ",),
      InfoCardItem("cografya_Info_9","Güneydoğu Anadolu Dağları","Malatya, Bitlis, Hakkari, Güneydağlar, Cilo",),
      InfoCardItem("cografya_Info_10","Doğu Anadolu Dağları","Tahtalı, Aras, Karasu, Mercan, Allahuekber, Bingöl, Şakşak, Kargopazarı, Ağrı, Süphan, Tendürek, Neptün, Şerafettin",),
      InfoCardItem("cografya_Info_11","İç Anadolu Dağları","Sundiken, Sultan, İdris, Elmadağ, Ayaş, Çamlıbel, Akdağlar, Hınzır, Erciyes, Hasan, Karacadağ, Karadağ, Melendiz",),
      InfoCardItem("cografya_Info_12","Batı Anadolu Dağları","Madra, Bozdağlar, Aydın, Yunt, Menteşe, Kazdağlar, Biga, Eğrigöz, Sandıklı, Murat, Uludağ",),
      InfoCardItem("cografya_Info_13","Oluş Şekillerine Göre Dağlar","-Orojenik Hareketlerle Meydana Gelenler,\n-Volkanik Dağlar",),
      InfoCardItem("cografya_Info_14","Orojenik Hareketlerle Meydana Gelenler-1","KIVRIM DAĞLARI\n-Esnek tabakaların kıvrılarak yükselmesiyle oluşur.\n-Doğu Anadolu Dağları, Toroslar, Karadeniz Dağları örnek gösterilebilir.",),
      InfoCardItem("cografya_Info_15","Orojenik Hareketlerle Meydana Gelenler-2","KIRIK DAĞLAR\n-Kıvrılma özelliğinin kaybedilip kırılmasıyla oluşan fayların çöken kısımlarına GRABEN, yükselen kısımlarına HORST denir.\n\nHORST DAĞLARI\n-Menteşe, Aydın, Kaz, Madra, Nur, Boz, Yunt",),
      InfoCardItem("cografya_Info_16","Volkanik Dağlar","Yer altındaki mağmanın yeryüzüne çıkmasıyla oluşur.\n-Erciyes, Hasan, Karacadağ, Karadağ, Melendiz, Ağrı, Kula, Uludağ\n\nNOT: Krateri olmayan tek volkanik dağ ULUDAĞ'dır.",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'nin Ovaları", [
      InfoCardItem("cografya_Info_17","Ovaların Tanımı ve Çeşitleri","-Vadilerler parçalanmamış geniş düzlüklere denir.\n\nOvalar;\n-Yüksekliklerine göre(Kıyı, iç)\n-Oluşumuna göre(Tektonik, Delta, Karstik, Volkanik) olarak gruplandırılabilir.",),
      InfoCardItem("cografya_Info_18","Kıyı Ovaları","-İç ovalara göre daha verimlidir.\n-Ürün çeşitliliği iç ovalardan fazladır.\n-Çarşamba, Bafra, Çukurova, Silifke, Menderes, Amik, Gediz, Bakırçay ovaları kıyı ovadır.",),
      InfoCardItem("cografya_Info_19","İç Ovalar","Konya, Kayseri, Ereğli, Harran, Çivril, Develi, Bozova ovaları örnektir.",),
      InfoCardItem("cografya_Info_20","Tektonik Ovalar","-Çöküntü ovalarıdır.\n-Fay hatları üzerinde bulunur.\n-Erbaa, Zile, Erzurum, Iğdır, Ağrı, Aydın, Tire örnektir.\n-En çok tektonik ova bulunur.",),
      InfoCardItem("cografya_Info_21","Delta Ovaları","-Akarsu alüvyonu çok taşımalıdır.\n-Kıyı derinliği azdır.\n-Kıyıda dalga, akıntı, gelgit olmamalıdır.\n-Bafra, Çarşamba, Küçük Menderes, Büyük Menderes, Bakırçay, Gediz, Çukurova, Silifke örnektir.",),
      InfoCardItem("cografya_Info_22","Karstik Ovalar","-Kireç taşı, alçı taşı gibi su ile kolay eriyen kayaçların bulunduğu yerdeki ovalardır.\n-Akdeniz'de Tefenni, Kestel, Korkuteli, Acıpayam, Elmalı\n-Ege'de Tavas, Çivril, Muğla ovaları bulunur.",),
      InfoCardItem("cografya_Info_23","Volkanik Ovalar","-Tektonik çukurların lavlarla dolmasıyla oluşur.\n-Develi, Kayseri ovaları örnektir.",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'nin Platoları", [
      InfoCardItem("cografya_Info_24","Platonun Tanımı","-Akarsular tarafından derince yarılmış, çevresine göre yüksek, hafif engebeli geniş düzlüklere denir.\n-En çok İç Anadolu Bölgesinde görülür.\n-Kuru tarım yapılır.",),
      InfoCardItem("cografya_Info_25","İç Anadolu Platoları","Haymana, Cihanbeyli, Obruk, Uzunyayla, Bozok platoları bulunur.",),
      InfoCardItem("cografya_Info_26","Doğu Anadolu Platoları","Kars, Ardahan, Erzurum platoları bulunur.",),
      InfoCardItem("cografya_Info_27","Akdeniz Platoları","Taşeli ve Teke platoları bulunur.",),
      InfoCardItem("cografya_Info_28","Marmara Platoları","Çatalca-Kocaeli, Biga ve Gelibolu platoları bulunur.",),
      InfoCardItem("cografya_Info_29","Doğu Anadolu Platoları","Gaziantep, Adıyaman, Şanlıurfa ve Diyarbakır platoları bulunur.",),
      InfoCardItem("cografya_Info_30","Ege Platoları","Yazlıkaya ve Uşak platoları bulunur.",),
      InfoCardItem("cografya_Info_31","Karadeniz Platoları","Giresun dağları üzerindeki platolar, Perşembe yaylası bulunur.",),
    ]),
    InfoCardModel("Coğrafya-Akarsular-1", [
      InfoCardItem("cografya_Info_32","Akarsu Nedir?","Kaynaklardan çıkan veya kar ve buzulların erimesiyle belirli bir yatakta akan, sonra denize veya göle dökülen sulara denir.",),
      InfoCardItem("cografya_Info_33","Akarsu Kaynağı","Akarsuyun doğduğu yere denir.",),
      InfoCardItem("cografya_Info_34","Akarsu Ağzı","Akarsuyun denize döküldüğü yere denir.",),
      InfoCardItem("cografya_Info_35","Akarsu Yatağı","Kaynak ağız arasında, suyun içinden aktığı çukurluktur.",),
      InfoCardItem("cografya_Info_36","Akarsu Debisi","Akarsuyun herhangi bir yerinden saniyede geçen suyun metreküp cinsinden değeridir.",),
      InfoCardItem("cografya_Info_37","Akarsu Rejimi","Yıl içinde akarsu debisinde görülen değişikliktir.",),
      InfoCardItem("cografya_Info_38","Akarsuların Aşındırma Şekilleri","-Vadi\n-Menderes\n-Dev Kazanı\n-Kırgıbayır\n-Peribacaları\n-Platolar\n-Peneplen",),
      InfoCardItem("cografya_Info_39","Vadi","-Çentik Vadi\n-Geniş Tabanlı Vadi\n-Geniş Tabanlı Vadi\n-Kanyon Vadi\n-Boğaz Vadi\n-Yastık Yamaçlı Vadi",),
      InfoCardItem("cografya_Info_40","Çentik Vadi","-Doğu Anadolu-Doğu Karadeniz\n-Derine aşındırma fazladır.\n-En sık görülen vadidir.\n-Engebenin çok olduğu yerlerde görülür.",),
      InfoCardItem("cografya_Info_41","Geniş Tabanlı Vadi","-Eğim azdır.\n-Yan aşındırma çoktur.\n-Akarsuyun denize yakın yerinde oluşur.\n-Marmara-Kıyı Ege en çok görülen yerlerdir.",),
      InfoCardItem("cografya_Info_42","Kanyon Vadi","-Karstik arazide görünür.\n-Akdeniz Bölgesinde görülür.\n-Yamaçların farklı aşınmasıyla oluşur.",),
      InfoCardItem("cografya_Info_43","Boğaz Vadi","-Sıradağların üzerinde enine yarılarak oluşur.\n-Akdeniz ve Karadeniz bölgelerinde görülür.",),
      InfoCardItem("cografya_Info_44","Yatık Yamaçlı Vadi","Menderesler örnek olarak verilebilir.",),
      InfoCardItem("cografya_Info_45","Menderes","Menderes yapan akarsuda;\n-Yatak eğimi azdır.\n-Akış hızı düşüktür.\n-Enerji potansiyeli dazdır.\n-Büyük ve Küçük Menderes örnektir.\n-Akarsuların yan aşındırma yaparak oluşturduğu kıvrımlardır.",),
      InfoCardItem("cografya_Info_46","Dev Kazanı","-Şelalelerin oluşturduğu derin çukurlardır.\n-Doğu Anadolu'da görülür.",),
      InfoCardItem("cografya_Info_47","Kırgıbayır","Dağ yüzeyinin aşınmasıyla oluşur.\n-Arazi girintili-çıkıntılı görünür.\n-Oluşması için şiddetli yağmur, cılız bitki örtüsü gerekir.\n-İç Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_48","Peribacaları","Sel sularının farklı dirençteki tabakaları aşındırmasıyla oluşur.\n-Volkanik arazilerde görülür.\n-İç Anadolu'da bulunur.\n-Nevşehir, Ürgüp, Göreme, Avanos örnektir.",),
      InfoCardItem("cografya_Info_49","Platolar","-Akarsuların derine yardığı geniş düzlüklere denir.\n-İç Anadolu'da bulunur.",),
      InfoCardItem("cografya_Info_50","Peneplen(Yontuk Düz)","-Akarsu aşındırmasını son kısmında, deniz seviyesindeki düzlüklerdir.\n-Ülkemizde görülmez.",),

    ]),
    InfoCardModel("Coğrafya-Akarsular-2", [
      InfoCardItem("cografya_Info_51","Akarsu Biriktirme Şekilleri","-Delta\n-Birikinti konisi\n-Dağ eteği ovası\n-Dağ içi ovası\n-Taban seviyesi ovası\n-Irmak adası",),
      InfoCardItem("cografya_Info_52","Delta","-Alüvonların denize döküldükleri yerlerde birikerek oluşan ovalardır.\n\nDelta oluşumu için;\n-Kıyı derinliği az olmalıdır.\n-Kıta sahanlığı geniş olmalıdır.\n-Alüvyon bol olmalıdır.\n-Denizde akıntı ve gel-git olmamalıdır.",),
      InfoCardItem("cografya_Info_53","Birikinti Konisi","Yamaçlardan düzlük alana inen akarsuların taşıdığı malzemeleri biriktirmeleriyle oluşur.",),
      InfoCardItem("cografya_Info_54","Dağ Eteği Ovası","Birikinti konilerinin dağın eteklerinde birleşmesiyle oluşur.",),
      InfoCardItem("cografya_Info_55","Dağ İçi Ovası","-Akarsuyla taşınan malzemelerin eğimin az olduğu yerlerde birikmesiyle oluşur.\n-Doğu Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_56","Taban Seviyesi Ovası","-Akarsuyun taşıdığı malzemelerin denize döküldüğü yerlerde birikmesiyle oluşur.\n-Kıyının hemen gerisindedir.\n-Ege ovaları ve Adapazarı Ovası örnek gösterilebilir.",),
      InfoCardItem("cografya_Info_57","Irmak Adası","Akarsu taşıdığı alüvyonları eimin iyice azaldığı yerlerde yatak üzerinde biriktirmesiyle oluşur.",),
      InfoCardItem("cografya_Info_58","Türkiye'nin Akarsularının Özellikleri","-Akış hızı yüksektir.\n-Debidi düşüktür.\n-Rejimi düzensizdir.",),
      InfoCardItem("cografya_Info_59","Karadenize Dökülen Akarsularımız","Kızılrmak, Yeşilırmak, Bartın Çayı ve Sakarya",),
      InfoCardItem("cografya_Info_60","Marmara Denizine Dökülen Akarsularımız","Susurluk",),
      InfoCardItem("cografya_Info_61","Ege Denizine Dökülen Akarsularımız","Meriç, Bakırçay, Küçük Menderes, Büyük Menderes ve Gediz",),
      InfoCardItem("cografya_Info_62","Akdenize Dökülen Akarsularımız","Manavgat, Aksu, Seyhan, Ceyhan, Göksu",),
      InfoCardItem("cografya_Info_63","Basra Körfezine Dökülen Akarsularımız","Fırat, Dicle",),
      InfoCardItem("cografya_Info_64","Hazar Denizine Dökülen Akarsularımız","Aras, Kura",),
      InfoCardItem("cografya_Info_65","Akarsu Notları","-Kaynağını dışarıdan alan akarsularımız ASİ-MERİÇ\n-Türkiye'de doğup dışarıda denize dökülen akarsularımız FIRAT, DİCLE, ÇORUH, KURA, ARAS",),
      InfoCardItem("cografya_Info_66","Havza","Akarsuyun kollarıyla beraber suyunu topladığı yere denir.\n\n2 çeşittir.\n-Açık Havza (Denize Dökülür)\n-Kapalı Havza (Denize Dökülmez)",),
      InfoCardItem("cografya_Info_67","Kapalı Havzalarımız","-Van Gölü Kapalı Havzası,\n-Tuz Gölü Kapalı Havzası\n-Konya Kapalı Havzası\n-Göller Yöresi Kapalı Havzası\n-Afyon Akarçay Kapalı Havzası",),
      InfoCardItem("cografya_Info_68","Akarsular Not","Türkiye'nin kendi sınırları içinde doğup kendi sınırları içinde denize dökülen en uzun akarsuyu KIZILIRMAK'tır.",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'de Göller", [
      InfoCardItem("cografya_Info_69","Türkiye'deki Göl Çeşitleri","-Tektonik Göller\n-Volkanik Göller\n-Set Gölleri\n-Buzul Gölleri\n-Baraj Gölleri\n-Karstik Göller",),
      InfoCardItem("cografya_Info_70","Tektonik Göller","-Tektonik hareketlerle çanaklaşan yerlerde suların birikmesiyle oluşur.\n-Uluabat, İznik, Sapanca, Kuş (Marmara)\n-Beyşehir, Eğirdir, Burdur, Acıgöl, Tuz Gölü, Akşehir, Seyfe, Eber (İç Anadolu)\n-Van Gölü, Hazar Gölü (Doğu Anadolu)\n\nNOT: Türkiye'nin en büyük tatlı su gölü BEYŞEHİR GÖLÜ'dür.",),
      InfoCardItem("cografya_Info_71","Volkanik Göller","-Volkanik göller çukurlarda oluşur.\n-Meke Tuzlası, Nemrut Gölü, Gölcük Gölü",),
      InfoCardItem("cografya_Info_72","Set Gölleri-1","-Volkanik Set Gölleri\n-Kıyı Set Gölleri\n-Alüvyol Set Gölleri\n-Heyelan Set Gölleri",),
      InfoCardItem("cografya_Info_73","Volkanik Set Gölleri","-Suları sodalıdır.\n-Doğu Anadolu'da bulunur.\n-Balık, Haçlı, Çıldır, Erçek, Van, Nazik gölleri",),
      InfoCardItem("cografya_Info_74","Kıyı Set Gölleri","-Koy veya körfezin nünü dalgaların biriktirdiği kumların kapatmasıyla oluşur.\n-Marmara'da bulunur.\n-Küçük Çekmece, Büyük Çekmece ve Terkoz(Durusu) örnektir.",),
      InfoCardItem("cografya_Info_75","Alüvyol Set Gölleri","Vadi kenarlarında akarsuların alüvyol biriktirmesiyle oluşur.\n-Marmara, Bafra(Çamiçi), Eymir, Uzungöl, Köyceğiz, Mogan",),
      InfoCardItem("cografya_Info_76","Heyelan Set Gölleri","-Heyelan ile akarsu vadisinin kapanmasıyla oluşur.\n-Abant, Yedigöller, Tortum, Sera, Zınav, Sürük örnektir.",),
      InfoCardItem("cografya_Info_77","Buzul Gölleri","Ağrı, Nemrut, Süphan, Tendürek, Kaçkar Dağları, Cilo, Uludağ, Erciyes, Aladağlar",),
      InfoCardItem("cografya_Info_78","Baraj Gölleri","-Akarsuların üzerinde set çekerek oluşturulan göllerdir.\n-İçme suyu, kullanma suyu, tarım arazilerini sulama, elektrik üretme, su taşkınlarını önleme amaçlarıyla kurulabilir.",),
      InfoCardItem("cografya_Info_79","Karstik Göller","-Kirecin erimesiyle oluşur.\n-Elmalı, Kastel, Salda, Suğla, Kızılören, Avlan örnektir.",),
      InfoCardItem("cografya_Info_80","Barajlarımız-1","Fırat üzerinde\n-Atatürk, Karakaya, Keban, Birecik, Karkamış\n\nDicle üzerinde\n-Kralkızı, Dicle, Ilısu, Cizre, Devegeçidi\n\nKızılırmak üzerinde\n-Hirfanlı, Altınkaya, Kapukkaya, Kesikköprü",),
      InfoCardItem("cografya_Info_81","Barajlarımız-2","Yeşilırmak üzerinde\n-Almus, Kılışkaya, Suat Uğurlu, Hasan Uğurlu\n\nGediz üzerinde\n-Demirköprü\n\nBüyük Menderes üzerinde\n-Kemer ve Adıgüzel",),
      InfoCardItem("cografya_Info_82","Barajlarımız-3","Seyhan üzerinde\n-Seyhan, Çatalan\n\nCeyhan üzerinde\n-Ceyhan, Aslantaş, Menzelet\n\nManavgat üzerinde\n-Manavgat, Oymapınar",),
      InfoCardItem("cografya_Info_83","Barajlarımız Not","Türkiye'nin en büyük barajı Atatürk'tür.",),
    ]),
    InfoCardModel("Coğrafya-İklim, Sıcaklık, Rüzgar, Yağış", [
      InfoCardItem("cografya_Info_84","Türkiye'de İklim-1","İklimi etkileyen faktörler\n-Matematik konum,\n-Dağların uzanışı ve bakı\n-Yükselti,\n-Etraftaki denizlerin, kara kütlelerinin ve basınç maddelerinin etkisi.",),
      InfoCardItem("cografya_Info_85","Türkiye'de İklim-2","Ülkemizde görülen iklim türleri\n-Karadeniz iklimi\n-Akdeniz iklimi\n-Karasal İklim",),
      InfoCardItem("cografya_Info_86","Karadeniz İklimi","-Yazlar serin, kışlar ılıktır.\n-Yağış her mevsimde görülür.\n-Sıcaklık farkı azdır.\n-Doğu Karadeniz Bölümü'nde yağış daha fazladır.\n-Yamaç yağışları görülür.\n-Karadeniz'in kıyı kesimleri ile Marmara'nın Karadeniz'e bakan kısmında görülür.",),
      InfoCardItem("cografya_Info_87","Akdeniz İklimi","-Yazlar sıcak ve kuraktır.\n-Kışlar ılık ve yağışlıdır.\n-Cephe yağışları şeklinde yağışlar görülür.\n-Yağışlar en çok kış mevsiminde oluşur.\n-Akdeniz, Ege, Güney Marmara ve Güney Doğu Anadolu'nun batısında görülür.",),
      InfoCardItem("cografya_Info_88","Karasal İklim","-Yazlar sıcak ve kuraktır.\n-Kışlar sert ve uzundur.\n-Buharlaşma çoktur.\n-Kuraklık görülür.\n-İç Anadolu, Güney Doğu Anadolu, İç Batı Anadolu'da görülür.",),
      InfoCardItem("cografya_Info_89","Türkiye'de Sıcaklık-1","Enlem, yükseklik, karasallık, mevsim, eğim ve güneş ışınlarının gelme açısına bağlı olarak sıcaklık değişir.\n-Güneş ışınlarının dik geldiği yerler daha çok ısınır.\n-Yükseklik arttıkça sıcaklık azalır.",),
      InfoCardItem("cografya_Info_90","Türkiye'de Sıcaklık-2","-Karalar çabuk, denizler geç ısınır.\n-Ekvatordan gelen rüzgarlar sıcaklığı arttırır.\n-Dağların uzanışı sıcaklığı etkiler.\n-Kuzeye bakan kısımlar daha az ısınır.",),
      InfoCardItem("cografya_Info_91","Türkiye'de Rüzgarlar-1","-Yerel Rüzgarlar\n-Meltem Rüzgarları\n-Fön Rüzgarları",),
      InfoCardItem("cografya_Info_92","Yerel Rüzgarlar","-Poyraz: Kuzeydoğudan eser, yazın sıcak kışın soğuktur.\n-Karayel: Kuzeybatıdan eser, kışın soğuktur.\n-Lodos: Güneybatıdan eser, ılıktır.\n-Samyeli: Güneydoğudan eser, sıcaktır.",),
      InfoCardItem("cografya_Info_93","Meltem Rüzgarları","-Deniz Meltemi: Ege'de imbat denir. Gündüz deniden karaya eser.\n-Kara Meltemi: Gece karadan denize eser.\n-Vadi Meltemi: Gündüze vadiden dağa eser.\n-Dağ Meltemi: Gece dağdan vadiye eser.",),
      InfoCardItem("cografya_Info_94","Fön Rüzgarları","Dağ yamaçları boyunca alçalan hava hareketleriyle oluşan rüzgardır.\n-Sıcaklığı arttırır.\n-Karları eritir.\n-Yağışa engel olur.",),
      InfoCardItem("cografya_Info_95","Türkiye'de Yağış","-Yamaç Yağışları\n-Konveksiyonel Yağış\n-Cephe Yağışları",),
      InfoCardItem("cografya_Info_96","Yamaç Yağışları","-Yamaç boyunca nemli havanın yükselerek soğumasıyla oluşur.\n-Dağların denize bakan yamaçlarında oluşur.\n-Akdeniz, Karadeniz ve Ege'de görülür.",),
      InfoCardItem("cografya_Info_97","Konveksiyonel Yağışlar","-Isınan havanın yükselip soğumasıyla oluşur.\n-İlkbahar başlarında sık görülür.\n-İç Anadolu ve Doğu Anadolu'da görülür.\n-Kırkikindi yağışları da denir.",),
      InfoCardItem("cografya_Info_98","Cephe Yağışları","Sıcak ve soğuk hava kütlelerinin karşılaşıp, sıcak havanın soğuyup yoğunlaşmasıyla  oluşur.\n-Akdeniz, Güney Doğu Anadolu'da sık görülür.\n-Kış mevsiminde görülür.",),
    ]),
    InfoCardModel("Coğrafya-Nüfus, Yerleşme, Endüstri", [
      InfoCardItem("cografya_Info_99","Türkiye'de Nüfus","-İlk nüfus sayımı 1927'de yapılmıştır.\n-Devlet İstatistik Enstitüsü gerçekleştirir.",),
      InfoCardItem("cografya_Info_100","Nüfus Artışının Nedenleri","-Dıştan gelen  göçler,\n-Doğum oranının artması,\n-Bebek ölümlerinin azalması,\n-Beslenme koşullarının daha iyi olması.",),
      InfoCardItem("cografya_Info_101","Nüfusun Dağılışını Etkileyen Faktörler","-İklim\n-Yer şekilleri\n-Tarım, ulaşım ve sanayi\n-Turizm\n-Su imkanı\n-Bitki örtüsü\n-Yer altı kaynakları\n\nNOT: En çok nüfus Marmara Bölgesi, en az nüfus Doğu Anadolu Bölgesi'ndedir.",),
      InfoCardItem("cografya_Info_102","Türkiye'de Yerleşme","-Kırsal yerleşme\n-Kentsel Yerleşme",),
      InfoCardItem("cografya_Info_103","Kırsal Yerleşmeler","Köy:\n-Geçim kaynağı tarım ve hayvancılıktır.\n-Nüfus 2000'den azdır.\n\nKöyaltı Yerleşim\n-Mahalle, mezra, çiftlik, yayla, oba, dam vb. yerleşimlerdir.",),
      InfoCardItem("cografya_Info_104","Kentsel Yerleşmeler-1","Ticaret Kentleri: İstanbul, Ankara, İzmir, Bursa, Kayseri, Gaziantep vb.\nTarım Kentleri: Tarsus, Söke, İnegöl, Rize, Karaman vb.\nSanayi Kentleri: İstanbul, İzmir, Bursa, Ankara, Batman",),
      InfoCardItem("cografya_Info_105","Kentsel Yerleşmeler-2","Liman Kentleri: İstanbul, İzmir, Antalya, Samsun, Trabzon\nTurizm Kentleri: Antalya, Muğla, İzmir, Aydın vb.\nÜniversite Kentleri: İstanbul, Ankara, İzmir, Eskişehir vb.",),
      InfoCardItem("cografya_Info_106","Türkiye'de Mesken Tipleri-1","Betonerme: Demir, beton, tuğla kullanılır. Ege ve Marmara bölgesinde sık görülür.\n\nTaş: Dağlık yerlerde görülür. Doğu Anadolu, Nevşehir çevresi ve Toros Dağlarında görülür.",),
      InfoCardItem("cografya_Info_107","Türkiye'de Mesken Tipleri-2","Ahşap: Malzeme ağaçtır. Ormanın sık olduğu yerlerde görülür. Karadeniz'de sık görülür.\n\nKerpiç: Malzeme killi topraktır. Kurak iklimde sık görülür. İç Anadolu ve Doğu Anadolu'da sık görülür. ",),
      InfoCardItem("cografya_Info_108","Türkiye'de Endüstri","-Dokuma ve giyim.\n-Besin\n-Maden\n-Otomotiv\n-Kimya\n-Çimento, seramik ve cam",),
      InfoCardItem("cografya_Info_109","Dokuma ve Giyim","Pamuk: Nazilli, Mersin, Adana, Antalya, Manisa, Denizli, Hatay, Kahramanmaraş, İzmir, Şanlıurfa, Iğdır, Bursa...\nYün: Hereke\nİpek: Bursa, İstanbul, Eskişehir, Bilecik\nHalı-Kilim: Uşak, Kayseri, Sivas, Bursa...",),
      InfoCardItem("cografya_Info_110","Besin","Şeker: İç kesimler\nÇay: Rize-Trabzon\nUn: İç kesimler, Trakya\nZeytinyağı: Ege, Güney Marmara\nAyçiçek yağı: Trakya, Ege, İç Anadolu\nSüt: İzmir, Erzurum, Kars",),
      InfoCardItem("cografya_Info_111","Maden","Demir-çelik: Sivas, İskenderun, Karabük, Ereğli, İzmir\nAliminyum: Seydişehir(tek)\nKurşun-Çinko: Kayseri, Giresun, Elazığ(Keban), Yozgat(Akdağmadeni)\nBakır: Murgul, Küre, Samsun, Çayeli, Siirt",),
      InfoCardItem("cografya_Info_112","Otomotiv","Otomobil Fabrikası: İstanbul, İzmir, Bursa, İzmit\nKamyon Fabrikası: İstanbul, İzmir, Adana, Eskişehir\n\nNot: Ankara'da uçak fabrikası var.\n\nEskişehir'de lokomotif fabrikası var.",),
      InfoCardItem("cografya_Info_113","Kimya","İlaç: İstanbul, Ankara, İzmir\nBoya: İstanbul, İzmir\nLastik: Adapazarı, İzmit\nPetrol-kimya: İzmir, Mersin, İzmit, Batman",),
      InfoCardItem("cografya_Info_114","Çimento, Seramik, Cam","Çimento: İstanbul, Ankara, İzmir, Mersin, Adana, Eskişehir\nSeramik: Kütahya, Bilecik, Çanakkale, Uşak, Aydın\nCam: İstanbul, Sivas, Kırklareli, Mersin, Bursa",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'de Madencilik", [
      InfoCardItem("cografya_Info_115","Demir","-Ereğli, Karabük ve İskenderun'da demir-çelik fabrikaları vardır.(işlendiği yerler)\n-Demirin çıkarıldığı yerler; Divriği, Hekimhan, Edremit, Dikili, Adana, Hatay, Simav, Torbalı",),
      InfoCardItem("cografya_Info_116","Bakır","-Elektrik, elektronik sanayisinde kullanılır.(iletkenliği yüksek)\n-Çıkarıldığı yerler: Murgul (Artvin), Küre (Kastamonu), Elazığ (Ergani), Rize (Çayeli)\n-İşlendiği yerler: Samsun, Murgul (Artvin), Ergani (Elazığ), Maden (Elazığ)",),
      InfoCardItem("cografya_Info_117","Krom","-Paslanmaz çelik yapımında ve demir sertleştirmede kullanılır.\n-Çıkarıldığı yerler: Elazığ (Guleman), Muğla, Kayseri, Adana, Kütahya, Bursa, Denizli, Mersin, İskenderun, Kahramanmaraş\n-İşlendiği yerler: Antalya, Elazığ (Guleman)",),
      InfoCardItem("cografya_Info_118","Aliminyum","-Kullanıldığı yerler: Otomobil, uçak sanayi, ev eşyası yapımı, inşaat sektörü, elektrikli araçlar\n-Çıkarıldığı yerler: Konya (Seydişehir), Muğla (Milas), Antalya (Akseki), Gaziantep (Islahiye)\n-İşlendiği yerler: Seydişehir Aliminyum Tesisleri",),
      InfoCardItem("cografya_Info_119","Bor","-Dünyada azdır.\n-Dünyanın en zengin bor rezervi Türkiye'dedir.(%75)\n-Kullanıldığı yerler: Nükleer alan, jet ve roket yakıtı, sabun, cam, fotoğrafçılık, kağıt sanayi\n-Çıkarıldığı yerler: Balıkesir (Susurluk, Bigadiç), Kütahya (Emet), Bursa (Kestelek), Eskişehir (Kırka)\n-İşlendiği yerler: Bandırma Boroks ve Asitborik Fabrikası, Eti Maden Kırka Bor İşletme",),
      InfoCardItem("cografya_Info_120","Altın","-Kullanıldığı yerler: Ziynet eşyası, para\n-Çıkarıldığı yerler :Balıkesir (İvrindi, Çoraklık, Kızıltepe), İzmir (Ovacık, Çukuralan, Seferihisar), Uşak (Kızıldağ), Erzincan (Çöpler)",),
      InfoCardItem("cografya_Info_121","Kurşun-Çinko","-İkisi karışıktır.\n-Kullanım alanları: Silah sanayi, Paslanmaz metal üretim, Akü imalatı, Ses yalıtımı\n-Çıkarıldığı yerler: Elazığ (Keban), Giresun, Sivas, Kayseri, İzmir",),
      InfoCardItem("cografya_Info_122","Kükürt","-Kullanım alanları: Sülfirik asit üretiminde, kimya sanayi, zirai ilaç yapımı, havai fişek\n-Çıkarıldığı yerler: Isparta (Keçiborlu), Denizli (Sarayköy), Kütahya (Simav), Muğla (Milas)",),
      InfoCardItem("cografya_Info_123","Civa","-Tek sıvı madendir.\n-Kullanıldığı yerler: Zirai ilaç yapımı, suni gübre üretimi, boya sanayi, kağıt sanayi\n-Çıkarıldığı yerler: İzmir (Ödemiş), Manisa (Alaşehir), Konya (Sarayönü)",),
      InfoCardItem("cografya_Info_124","Lüle Taşı","-Süs eşyası yapımında kullanılır.\n-Eskişehir'de çıkarılır.",),
      InfoCardItem("cografya_Info_125","Oltu Taşı","-Süs eşyası yapımında kullanılır.\n-Erzurum'da çıkarılır.",),
      InfoCardItem("cografya_Info_126","Mermer","Kullanıldığı Alanlar\n-İnşaat sektörü, heykel yapımı, süsleme\n-Çıkarıldığı yerler\n-Afyon, Marmara adası, Kütahya, Kırşehir",),
      InfoCardItem("cografya_Info_127","Tuz","Çıkarıldığı yerler\n-İzmir (Çamaltı) ve Tuz Gölü en çok çıkarıldığı yerlerdir. Ayrıca Çankırı, Kars, Iğdır ve Nevşehir'de bulunur.",),
    ]),
    InfoCardModel("Coğrafya-Enerji Kaynaklarımız", [
      InfoCardItem("cografya_Info_128","Taş Kömürü","-Zonguldak, Ereğli, Amasra'da çıkarılır.\n-Demir-çelik sanayisinde enerji kaynağı olarak tüketilir.",),
      InfoCardItem("cografya_Info_129","Linyit-1","-Esmer kömür olarak bilinir.\n-Kalorisi azdır.\n-En zengin enerji kaynaklarındandır.\n-Bütün bölgelerde bulunur.\n-Afşin, Esbistan, Tunçbilek, Tavşanlı, Seyitömer, Değirmisaz, Yatağan, Soma, Mengen, Saray başlıca çıkarıldığı yerlerdir.",),
      InfoCardItem("cografya_Info_130","Linyit-2","-Elektrik enerjisi linyitten elde edilir. Bu santraller termik santrallerdir.\n\nTermik Santrallerimiz\n-Kütahya (Seyitömer, Tunçbilek), Manisa (Soma), Muğla (Yatağan), Kahramanmaraş (Afşin, Elbistan), Orhaneli, Zonguldak (Çatalağzı)",),
      InfoCardItem("cografya_Info_131","Doğalgaz","-Rusya, İran'dan ithal edilir.\n-Kırklareli, Lüleburgaz, Babaeski'de bulunur.",),
      InfoCardItem("cografya_Info_132","Petrol","-İlk kez Raman Dağı'nda (Batman) bulundu.\n-Mardin, Adıyaman, Diyarbakır, Batman, Siirt'de çıkarılır.",),
      InfoCardItem("cografya_Info_133","Jeotermal Enerji","-Buhardan elde edilir.\n-Afyon, Aydın (Germencik) ve Denizli'de (Sarayköy) bulunur.",),
      InfoCardItem("cografya_Info_134","Hidroelektrik Enerji","-Barajlardan elde edilen enerjidir.\n-En yüksek enerji potansiyeli Doğu Anadolu'dadır.",),
    ]),
    InfoCardModel("Coğrafya-Türkiye'de Tarım", [
      InfoCardItem("cografya_Info_135","Tarım İhracı","İhraçta 1. sırada olduğumuz ürünler\n-Fındık %67\n-İncir %27\n-Kiraz %26\n-Kayısı %23",),
      InfoCardItem("cografya_Info_136","Tarım Ürünleri","-Tahıllar\n-Sebzeler\n-Endüstri Bitkileri\n-Yağlı Bitkiler\n-Meyvecilik",),
      InfoCardItem("cografya_Info_137","Tahıllar","-Buğday\n-Arpa\n-Çavdar\n-Mısır\n-Pirinç",),
      InfoCardItem("cografya_Info_138","Buğday","-En geniş ekim alanına sahiptir.\n-En fazla İç Anadolu'da yetişir.\n-Karadeniz'de yetişmez.\n-İlkbaharda yağış, yazın kuraklık ister.",),
      InfoCardItem("cografya_Info_139","Arpa","-Buğdaydan sonra en fazla üretilen tahıldır.\n-Soğuğa, sıcağa dayanaklıdır.\n-En fazla iç Anadolu'da yetişir.\n-Bira yapımında ve hayvan yeminde kullanılır.",),
      InfoCardItem("cografya_Info_140","Çavdar","-Düşük ısıya dayanıklıdır.\n-Arpa ve buğdayın yetişemediği yerlerde yetişir.\n-İç Anadolu ve Doğu Anadolu'da yetişir.\n-Un yapımında ve hayvan yemi olarak kullanılır.",),
      InfoCardItem("cografya_Info_141","Mısır","-Bol su, sıcaklık ister.\n-Karadeniz ikliminde uyumludur.\n-Karadeniz, Akdeniz, Marmara da sık üretilir.",),
      InfoCardItem("cografya_Info_142","Pirinç","Bol su, sıcaklık, emek ister.\n-Vadi tabanları, akarsu boylarında üretilir.\n-Yerleşim yerlerinin yakınında ekimi yasaktır. (Sivrisineğe ve sıtmaya neden olduğu için)\n-En çok Edirne, Samsun, Çorum, Sinop'ta üretilir.",),
      InfoCardItem("cografya_Info_143","Sebzeler","-Mercimek\n-Nohut\n-Fasulye\n-Patates",),
      InfoCardItem("cografya_Info_144","Mercimek","-Yetişirken yağış ister.\n-Olgunlaşırken sıcaklık ister.\n-Kırmızı mercimek en çok Güneydoğu Anadolu'da yetişir.\n-Yeşil mercimek en çok İç Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_145","Nohut","-Yarı kurak iklimi sever.\n-En çok iç Anadolu, İç Ege, Güneydoğu Anadolu da yetişir.",),
      InfoCardItem("cografya_Info_146","Fasulye","-Yazın sulama olan her yerde yetişir.\n-Çukurova, Marmara'nın güney ovaları, iç kısımlarda akarsu boylarında üretilir.",),
      InfoCardItem("cografya_Info_147","Patates","-Buğdaydan sonra en çok tüketilir.\n-Değişik iklim koşullarına uygundur.\n-En çok İç Anadolu (Niğde, Nevşehir, Kayseri) ve Sakarya'da yetişir.",),
      InfoCardItem("cografya_Info_148","Endüstri Bitkileri","-Tütün\n-Pamuk\n-Şeker pancarı\n-Çay",),
      InfoCardItem("cografya_Info_149","Tütün","-Çimlenmede bol su ister.\n-Büyürken güneş, sıcaklık ister.\n-Kumlu, kıraç toprakları sever.\n-En fazla Denizli, Manisa, Kütahya, Samsun, Bolu, Amasya, Trabzon, Balıkesir, Adıyaman'da yetişir.",),
      InfoCardItem("cografya_Info_150","Pamuk","-Büyürken su, olgunlaşırken kuraklık ister.\n-En çok Güneydoğu Anadolu, Ege, Akdeniz'de yetişir.\n-Malatya, Iğdır, Elazığ'da yetişir.\n-Karadeniz'de yetiştirilmez. (Yazın kurak olmadığı için)",),
      InfoCardItem("cografya_Info_151","Şekerpancarı","Ilıman iklim sever.\n-Soğuğa dayanıklıdır.\n-İlkbaharda ekilir.\n-Güzün hasad edilir.\n-En çok İç Anadolu'da yetişir.\n-Şeker, Yem, İspirto sanayisinde kullanılır.",),
      InfoCardItem("cografya_Info_152","Çay","-Sürekli yağış ve nem ister.\n-Eğimli ve gölgeli arazilerde yetişir.\n-Karadeniz'de (Ordu, Rize) yetişir.",),
      InfoCardItem("cografya_Info_153","Yağlı Bitkiler","-Zeytin\n-Ayçiçeği\n-Yer fıstığı\n-Susam\n-Haşhaş\n-Keten, Kenevir",),
      InfoCardItem("cografya_Info_154","Zeytin","-Akdeniz ikliminde yetişir.\n-Bir arayla ürün verir.\n-En çok Ege, Marmara, Akdeniz, Güneydoğu Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_155","Ayçiçeği","-En çok Marmara'da yetişir.\n-Büyüme döneminde yağış ister.\n-Olgunlaşma döneminde sıcaklık ister.\n-İç Anadolu ve Orta Karadeniz'de yetişir.",),
      InfoCardItem("cografya_Info_156","Yer Fıstığı","-Güneydoğu Anadolu, Akdeniz, Ege, Marmara'da üretilir.\n-Sıcaklık ve nemli iklimi sever.\n-Kuruyemiş ve yağ şeklinde tüketilir.",),
      InfoCardItem("cografya_Info_157","Susam","-Ilıman iklimde yetişir.\n-Akdeniz, Ege, Marmara'da yetişir.\n-Yağı çıkartılır.",),
      InfoCardItem("cografya_Info_158","Haşhaş","-Yazların sıcak ve orta derece yağışlı olduğu yerlerde yetişir.\n-Yağ, ilaç, uyuşturucu yapımında kullanılır.\n-En çok Afyon'da yetişir.",),
      InfoCardItem("cografya_Info_159","Keten, Kenevir","-Ilıman iklim ve nemli toprak sever.\n-Dokuma sanayisinde kullanılır.\n-Tohumdan elde edilen Bezir yağı boya yapımında kullanılır.\n-En çok Sinop, Kastamonu, Zonguldak ve Kocaeli'de yetişir.",),
      InfoCardItem("cografya_Info_160","Meyvecilik","-Fındık\n-Antep Fıstığı\n-İncir\n-Üzüm\n-Elma\n-Turunçgiller\n-Muz",),
      InfoCardItem("cografya_Info_161","Fındık","-Serin, nemli iklim sever.\n-En çok Karadeniz'de yetişir.\n-En çok fındık üreten ülke Türkiye'dir.",),
      InfoCardItem("cografya_Info_162","Antep Fıstığı","-Sıcak ve kurak iklim sever.\n-Tatlı yağımında kullanılır ve kuruyemiş olarak tüketilir.",),
      InfoCardItem("cografya_Info_163","İncir","-Akdeniz iklimini sever.\n-Soğuğa karşı dayanıksızdır.\n-En çok Ege ve Akdeniz'de yetişir.\n-Dünyada en çok incir üreten ülke Türkiye'dir.",),
      InfoCardItem("cografya_Info_164","Üzüm","-Her bölgemizde yetişebilir.\n-Yemeklik, pekmez, şarap ve kuru şekllerde tüketilir.\n-En çok Ege, Marmara, Güneydoğu Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_165","Elma","Ilıman iklim sever.\n-En çok İç Anadolu'da yetişir.\n-Çoğu bölgemizde yetişir.",),
      InfoCardItem("cografya_Info_166","Turunçgiller","-Ilıman iklimi sever.\n-En çok Akdeniz, Ege ve Rize'de yetişir.",),
      InfoCardItem("cografya_Info_167","Muz","-Yüksek seıcaklık, nem sever.\n-Antalya-Mersin arasında yetişir.",),
    ]),
    InfoCardModel("Coğrafya-Hayvancılık", [
      InfoCardItem("cografya_Info_168","Hayvancılık","-Küçükbaş Hayvancılık\n-Büyükbaş Hayvancılık\n-Kümes Hayvancılığı\n-Balıkçılık\n-İpek Böcekçiliği\n-Arıcılık",),
      InfoCardItem("cografya_Info_169","Küçükbaş Hayvancılık","-Koyun\n-Keçi",),
      InfoCardItem("cografya_Info_170","Koyun","-Bozkırlarda yetiştirilir.\n-En çok İç Anadolu, Güneydoğu Anadolu ve Doğu Anadolu'da yetişir.\n-Soyları Kıvırcık, Dağlıç, Merinos, Karaman, Sakız olarak ayrılır.",),
      InfoCardItem("cografya_Info_171","Kıvırcık Koyun","-Et verimi yüksektir.\n-Trakya ve Marmara'nın güneyinde yetişir.",),
      InfoCardItem("cografya_Info_172","Dağlıç Koyun","-Et verimi yüksektir.\n-Dağlık olmayan yerlerde yetişir.\n-Ege, İç Anadolu'da yetişir.",),
      InfoCardItem("cografya_Info_173","Merinos Koyun","-Yünü kalitelidir, et verimi düşüktür.\n-Marmara'da yetişir.",),
      InfoCardItem("cografya_Info_174","Karaman Koyunu","-İç Anadolu, Ege, Güneydoğu Anadolu'da yetişir.\n-Uzun kuyrukludur.",),
      InfoCardItem("cografya_Info_175","Sakız Koyunu","-Ege, İç Anadolu'da yetişir.\n-İnce kuyrukludur.",),
      InfoCardItem("cografya_Info_176","Keçi","-Kıl keçisi\n-Tiftik(Ankara) keçisi",),
      InfoCardItem("cografya_Info_177","Kıl Keçisi","-Koyuna göre daha dayanıklıdır.\n-Sütü, eti, kılı için bakılır.\n-Dağlık, dik yerlerde yetiştirilir.\n-Akdeniz, Doğu Anadolu'da sık görülür.",),
      InfoCardItem("cografya_Info_178","Tiftik (Ankara) Keçisi","-Tüyleri uzun, ince ve parlaktır.\n-En çok İç Anadolu, Güneydoğu Anadolu'da yetiştirilir.",),
      InfoCardItem("cografya_Info_179","Büyükbaş Hayvancılık","-Türkiye'nin her bölgesinde yetiştirilir.\n-Eti, sütü ve gücü için yetiştirilir.\n-Erzurum-Kars bölgesinde iyi cinsleri yetişir.\n-Soğır, at, eşek, katır, manda büyükbaş hayvanlara örnektir.",),
      InfoCardItem("cografya_Info_180","Kümes Hayvancılığı","-Et, yumurta için beslenir.\n-Tavuk, kaz, ördek ve hindi örnektir.\n-En çok Marmara, Ege, İç Anadolu'da yetiştirilir.",),
      InfoCardItem("cografya_Info_181","Balıkçılık","-En çok Karadeniz'de yapılır. (%80)\n-En çok hamsi tutulur.\n\nNOT: Karadeniz'de balıkçılığın çok olma sebepleri\n-Tuzluluk oranının düşük olması\n-Çok sayıda akarsuyun bol planktonu denize dökmesi\n-Tarım arazisini az olması.",),
      InfoCardItem("cografya_Info_182","İpek Böcekçiliği","-Besin kaynağı dut yaprağıdır.\n-Salgısının katılaşmasıyla ipek oluşur.\n-En çok Marmara, Denizli, Elazığ'da görülür.",),
      InfoCardItem("cografya_Info_183","Arıcılık","-En çok Karadeniz'de yapılır.\n-Hakkari, Kars, Bitlis, Erzurum, Muğla, Manisa, İzmir ve Aydın balı ile ünlüdür.",),
    ]),

  ];
//Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği
  InfoCardModel("Başlık", [
      InfoCardItem("","ALTBAŞLIK","",),
    ]),
    */
  List<InfoCardModel> get genelKulturInfoCard => _genelKulturInfoCard;
}
