import 'package:flutter/material.dart';

import '../../../model/question.dart';

class MebTemelKanunuQuesViewModel extends ChangeNotifier {
  List<Question> _mebTemelKanunuQuesList = [
    ///Meb temel kanunu
    ///"I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    ///1739 sayılı Milli Eğitim Temel Kanunu
    Question("mebtemelkanunu_Q_1","","Aşağıdakilerden hangisi 739 sayılı Milli Eğitim Temel Kanununun genel amaçları arasında yer almaz?","Her konuda fikir sahibi bireyler yetiştirmek",["Atatürk İlke ve İnkilaplarına bağlı bireyler yetiştirmek","Beden sağlığı gelişmiş bireyler yetiştirmek","Her konuda fikir sahibi bireyler yetiştirmek","Sorumluluk duygusu gelişmiş bireyler yetiştirmek","Geniş dünya görüşüne sahip bireyler yetiştirmek"]),
    Question("mebtemelkanunu_Q_2","I-Bilimsel düşünme gücü\nII-Gelişmiş kişilik özellikleri\nIII-Yapıcı ve yaratıcı düşünme","Yukarıdakilerden hangisi veya hangileri Türk Milli Eğitimi'nin öğrencilere kazandırmak istediklerindendir?","I-II-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    Question("mebtemelkanunu_Q_3","","Aşağıdakilerden hangisi 1739 sayılı Milli Eğitim Temel Kanununa göre Milli Eğitimin temel ilkelerinden değildir?","Korunma",["Genellik ve eşitlik","Süreklilik","Yöneltme","Korunma","Fırsat eşitliği"]),
    Question("mebtemelkanunu_Q_4","","Aşağıdakilerden hangisi 1739 sayılı Milli Eğitim Temel Kanununa göre Milli Eğitimin temel ilkelerinden değildir?","Rıza gösterme",["Eğitim hakkı","Rıza gösterme","İmkan eşitliği","Bilimsellik","Laiklik"]),
    Question("mebtemelkanunu_Q_5","Eğitim kurumları dil, ırk, cinsiyet, engellilik ve din ayırımı gözetilmeksizin herkese açıktır. ","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Genellik ve eşitlik",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_6","Milli eğitim hizmeti, Türk vatandaşlarının istek ve kabiliyetleri ile Türk toplumunun ihtiyaçlarına göre düzenlenir.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Ferdin ve toplumun ihtiyaçları",["Eğitim hakkı","Ferdin ve toplumun ihtiyaçları","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_7","Fertler, eğitimleri süresince, ilgi, istidat ve kabiliyetleri ölçüsünde ve doğrultusunda çeşitli programlara veya okullara yöneltilerek yetiştirilirler?","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Yöneltme",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Yöneltme","Süreklilik"]),
    Question("mebtemelkanunu_Q_8","İlköğretim görmek her Türk vatandaşının hakkıdır","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Eğitim hakkı",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_9","Eğitimde kadın, erkek herkese fırsat ve imkan eşitliği sağlanır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Fırsat ve imkan eşitliği",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_10","Fertlerin genel ve mesleki eğitimlerinin hayat boyunca devam etmesi esastır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Süreklilik",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_11","Eğitim sistemimizin her derece ve türü ile ilgili ders programlarının hazırlanıp uygulanmasında ve her türlü eğitim faaliyetlerinde Atatürk inkılap ve ilkeleri ve Anayasada ifadesini bulmuş olan Atatürk milliyetçiliği temel olarak alınır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Atatürk İnkılap ve İlkeleri ve Atatürk Milliyetçiliği",["Atatürk İnkılap ve İlkeleri ve Atatürk Milliyetçiliği","Eğitim hakkı","Planlılık","Yöneltme","Süreklilik"]),
    Question("mebtemelkanunu_Q_12","Güçlü ve istikrarlı, hür ve demokratik bir toplum düzeninin gerçekleşmesi ve devamı için yurttaşların sahip olmaları gereken demokrasi bilincinin kazandırılıp geliştirilmesine çalışılır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Demokrasi eğitimi",["Genellik ve eşitlik","Eğitim hakkı","Demokrasi eğitimi","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_13","Din kültürü ve ahlak öğretimi ilköğretim okulları ile lise ve dengi okullarda okutulan zorunlu dersler arasında yer alır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Laiklik",["Demokrasi eğitimi","Eğitim hakkı","Planlılık","Laiklik","Bilimsellik"]),
    Question("mebtemelkanunu_Q_14","Her derece ve türdeki ders programları ve eğitim metotlarıyle ders araç ve gereçleri, teknolojik esaslara ve yeniliklere, çevre ve ülke ihtiyaçlarına göre sürekli olarak geliştirilir.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Bilimsellik",["Demokrasi eğitimi","Eğitim hakkı","Planlılık","Laiklik","Bilimsellik"]),
    Question("mebtemelkanunu_Q_15","Milli eğitimin gelişmesi iktisadi, sosyal ve kültürel kalkınma hedeflerine uygun olarak eğitim-insangücü - istihdam ilişkileri dikkate alınmak suretiyle, sanayileşme ve tarımda modernleşmede gerekli teknolojik gelişmeyi sağlayacak mesleki ve teknik eğitime ağırlık verecek biçimde planlanır ve gerçekleştirilir.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Planlılık",["Genellik ve eşitlik","Eğitim hakkı","Planlılık","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_16","Okullarda kız ve erkek karma eğitim yapılması esastır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Karma eğitim",["Genellik ve eşitlik","Eğitim hakkı","Karma eğitim","Fırsat ve imkan eşitliği","Süreklilik"]),
    Question("mebtemelkanunu_Q_17","Milli eğitimin amaçları yalnız resmi ve özel eğitim kurumlarında değil, aynı zamanda evde, çevrede, işyerlerinde, her yerde ve her fırsatta gerçekleştirilmeye çalışılır.","Yukarıdaki ifade Türk Milli Eğitimin Temel ilkelerinden hangisine karşılık gelir?","Her yerde eğitim",["Süreklilik","Eğitim hakkı","Karma eğitim","Fırsat ve imkan eşitliği","Her yerde eğitim"]),
    Question("mebtemelkanunu_Q_18","I-Genel eğitim\nII-Örgün eğitim\nIII-Yaygın eğitim","Yukarıdakilerden hangisi veya hangileri Türk milli eğitim sisteminin ana bölümlerindendir?","II-III", ["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_19","","Mecburi ilköğrenim çağına gelmemiş çocukların eğitimini kapsayan eğitim türü aşağıdakilerden hangisidir?","Okul Öncesi Eğitim",["Yaygın Eğitim","Okul Öncesi Eğitim","Örgün Eğitim","İlköğretim","Temel Eğitim"]),
    Question("mebtemelkanunu_Q_20","I-Türkçeyi doğru ve güzel konuşmalarını sağlamak\nII-Ortak bir yetişme ortamı yaratmak\nIII-Ortaöğretime hazırlamak","Yukarıdakilerden hangisi veya hangileri okul öncesi eğitimin amaçlarından biri değildir?","Yalnız III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_21","","Okul öncesi eğitim kurumlarının nerelerde ve hangi önceliklere göre açılacağı aşağıdaki kurumlardan hangisi tarafından belirlenir?","Milli Eğitim Bakanlığı",["İçişleri Bakanlığı","Adalet Bakanlığı","Milli Eğitim Bakanlığı","Çevre ve Şehircilik Bakanlığı","Cumhurbaşkanlığı"]),
    Question("mebtemelkanunu_Q_22","","Mecburi ilköğretim çağı aşağıdaki yaş gruplarından hangisini kapsar?","6-14",["6-12","6-14","6-18","7-12","7-16"]),
    Question("mebtemelkanunu_Q_23","","İlkokulların birinci sınıflarına o yılın 31 Aralık tarihinde kaç ayını dolduranların kayıtlar yapılır?","72",["48","52","62","72","76"]),
    Question("mebtemelkanunu_Q_24","I-Üst öğretime hazırlamak\nII-Temel bilgi ve becerileri kazandırmak\nIII-Mesleklerle ilgili rehberlik etmek","Yukarıdakilerden hangisi veya hangileri ilköğretimin amaç ve görevlerindendir?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_25","I-Toplum sorunlarını tanıma gücü kazandırmak\nII-Yükseköğretime hazırlamak\nIII-İş alanlarına hazırlamak","Yukarıdakilerden hangisi veya hangileri ortaöğretimin amaç ve görevlerindendir?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_26","","Türk Milli Eğitim sisteminde yöneltme aşağıdakilerden hangisinde başlar?","İlköğretim",["Aile","Okul öncesi","İlköğretim","Ortaöğretim","Yükseköğretim"]),
    Question("mebtemelkanunu_Q_27","","Aşağıdakilerden hangisi yükseköğretimin kapsamı ile ilgili doğru bir ifadedir?","En az iki yıllık yüksek öğrenim veren eğitim kurumlarının tümünü kapsar",["En az iki yıllık yüksek öğrenim veren eğitim kurumlarının tümünü kapsar","En az dört yıllık yüksek öğrenim veren eğitim kurumlarının tümünü kapsar","En az iki yıllık yüksek öğrenim verip iki yıllık lisans tamamlama eğitimi veren kurumların tümünü kapsar","En az dört yıllık yüksek öğrenim verip iki yıllık lisans tamamlama eğitimi veren kurumların tümünü kapsar","En az beş yıllık yüksek öğrenim veren kurumların tümünü kapsar"]),
    Question("mebtemelkanunu_Q_28","I-Bilimsel çalışma yapmak\nII-Bilim verilerini halka açıklamak\nIII-İnsan gücü ihtiyaçlarına göre öğrenci yetiştirmek","Yukarıdakilerden hangisi veya hangileri yükseköğretimin amaçlarındandır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_29","I-Uygulama ve araştırma merkezleri\nII-Meslek yüksekokulları\nIII-Enstitüler","Yukarıdakilerden hangisi veya hangileri yükseköğretim kurumları arasında sayılır?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_30","I-Okuma yazma öğretmek\nII-Bilimsel araştırma yaptırmak\nIII-Sağlıklı yaşama şekillerini benimsetmek","Yukarıdakilerden hangisi veya hangileri yaygın eğitim kurumlarının amaçlarından değildir?","Yalnız II",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_31","I-Milli kültürü korumak\nII-Dayanışma alışkanlığı kazandırmak\nIII-Boş zamanları değerlendirme alışkanlığı kazandırmak","Yukarıdakilerden hangisi veya hangileri yaygın eğitim kurumlarının amaçlarından değildir?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_32","I-Yaz okulları\nII-Akşam okulları\nIII-Hizmet içi kurslar","Yukarıdakilerden hangisi veya hangileri öğretmenlerin daha üst eğitim görmelerini sağlamak için düzenlenebilir?","I-II-III",["Yalnız I","Yalnız II","Yalnız III","II-III","I-II-III"]),
    Question("mebtemelkanunu_Q_33","","Öğretmenlerin izin ve yaz tatilleri ile ilgili olarak aşağıdakilerden hangisi yanlıştır?","Rehber öğretmenlerin izinleri öğrenci ders ve alan seçimleri için 1 aydan az olabilir",["Aralıksız olarak 2 aydır","İzin sürelerine dokunulmadan mesleki çalışma yapmakla yükümlüdürler","Rehber öğretmenlerin izinleri öğrenci ders ve alan seçimleri için 1 aydan az olabilir","Salgın hastalık, afet vb sebeplerle 2 hafta eğitime ara verilirse yaz tatilinde telafi yapılabilir","Yaz tatilinde telafi eğitimi verilmesi durumunda izinler 1 aydan az olamaz"]),
    Question("mebtemelkanunu_Q_34","Ders araç gereçlerini;\nI-Hazırlama\nII-İmal etme\nIII-Satın alma","Görevleri aşağıdakilerden hangisinindir?","Milli Eğitim Bakanlığı",["Milli Eğitim Bakanlığı","İçişleri Bakanlığı","Çalışma ve Sosyal Güvenlik Bakanlığı","Maliye Bakanlığı","Sanayi ve Teknoloji Bakanlığı"]),
    Question("mebtemelkanunu_Q_35","","Aşağıdakilerden hangisi okullarda okutulacak kitaplar ile ilgili doğru bir ifade değildir?","Kitap redaksiyonuna ücret ödenmez",["Kitap hazırlayanlara ücret ödenir","Kitap redaksiyonuna ücret ödenmez","Özel kesimlerin hazırladığı kitaplar Bakanlığa ücret karşılığı inceletilebilir","Yarışma düzenleyerek kitap hazırlatılabilir","Kitap inceleme görevlilerine ücret ödenir"]),
    Question("mebtemelkanunu_Q_36","","Askeri eğitim kurumlarının dereceleri ve müfredatı Milli Eğitim Bakanlığı ile ortaklaşa aşağıdakilerden hangisi tarafından hazırlanır?","Milli Savunma Bakanlığı",["İçişleri Bakanlığı","Yükseköğretim Kurulu","Cumhurbaşkanlığı","TBMM komisyonu","Milli Savunma Bakanlığı"]),
    Question("mebtemelkanunu_Q_37","","Türk vatandaşlarının yurt dışında eğitim, öğrenim ve ihtisas görmeleri ile ilgili Devlet hizmetlerinin düzenlenmesinde Milli Eğitim Bakanlığınının sorumluluğunun olmadığı alan aşağıdakilerden hangisidir?","Askeri alan",["Politika alanı","Ekonomi alanı","Eğitim alanı","Askeri alan","İktisat alanı"]),
   //Question("mebtemelkanunu_Q_38","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_39","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_40","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_41","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_42","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_43","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_44","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_45","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_46","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_47","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_48","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_49","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_50","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_51","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_52","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_53","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_54","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_55","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_56","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_57","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_58","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_59","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_60","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_61","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_62","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_63","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_64","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_65","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_66","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_67","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_68","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_69","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_70","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_71","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_72","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_73","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_74","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_75","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_76","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_77","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_78","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_79","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_80","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_81","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_82","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_83","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_84","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_85","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_86","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_87","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_88","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_89","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_90","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_91","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_92","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_93","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_94","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_95","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_96","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_97","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_98","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_99","","","",["","","","",""]),
   //Question("mebtemelkanunu_Q_10","","","",["","","","",""]),
  ];
//Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği
  InfoCardModel("Başlık", [
      InfoCardItem("ALTBAŞLIK","",),
    ]),
    */
  List<Question> get mebTemelKanunuQuesList => _mebTemelKanunuQuesList;
//List<String> answKeyList=[];

}