import 'package:flutter/material.dart';

import '../../../model/question.dart';

class CografyaQuesViewModel extends ChangeNotifier{
  List<Question> _cografyaQuesList=[
    Question("cografya_Q_1","", "Türkiye'nin en doğusu ile en batısı arasındaki saat farkı kaç dakikadır?", "76", ["70","72","76","78","82"]),
    Question("cografya_Q_2","", "Türkiye'nin doğusu ile batısı arasındaki boylam farkı kaçtır?", "19", ["16","17","18","19","20"]),
    Question("cografya_Q_3","", "Türkiye'nin doğu meridyenleri hangileridir?", "26°-45°", ["26°-45°","26°-42°","36°-42°","36°-45°","26°-36°"]),
    Question("cografya_Q_4","", "Türkiye'nin kuzey paralelleri hangileridir?", "36°-42°", ["26°-36°","26°-42°","26°-45°","36°-42°","36°-45°"]),
    Question("cografya_Q_5","", "Aşağıdakilerden hangisi komşu ülkelerimizden değildir?", "Almanya", ["Yunanistan","Ermenistan","İran","Irak","Almanya"]),
    Question("cografya_Q_6","", "Yunanistan sınırındaki gümrük kapımız aşağıdakilerden hangisidir?", "İpsala", ["Kapıkule","İpsala","Esendere","Cilvegözü","Öncüpınar"]),
    Question("cografya_Q_7","", "Bulgaristan sınırındaki gümrük kapımız aşağıdakilerden hangisidir?", "Kapıkule", ["İpsala","Akkaya","Kapıkule","Cilvegözü","Öncüpınar"]),
    Question("cografya_Q_8","", "Suriye sınırındaki gümrük kapımız aşağıdakilerden hangisidir?", "Cilvegözü", ["Cilvegözü","İpsala","Kapıkule","Gürbulak","Esendere"]),
    Question("cografya_Q_9","", "İran sınırındaki gümrük kapımız aşağıdakilerden hangisidir?", "Esendere", ["Cilvegözü","İpsala","Kapıkule","Gürbulak","Esendere"]),
    Question("cografya_Q_10","", "Ermenistan sınırındaki gümrük kapımız aşağıdakilerden hangisidir?", "Akkaya", ["Akkaya","İpsala","Kapıkule","Gürbulak","Esendere"]),
    Question("cografya_Q_11","", "Türkiye'nin kuzeyi ile güneyi arasında kaç enlem vardır?", "6", ["5","6","7","8","9"]),
    Question("cografya_Q_12","", "Doğu Karadeniz'in en yüksek dağı aşağıdakilerden hangisidir?", "Kaçkar", ["Küre","Giresun","Kaçkar","Canik","Yıldız"]),
    Question("cografya_Q_13","", "Aşağıdakilerden hangisi Horst değildir?", "Kaz Dağları", ["Hasan Dağı","Erciyes Dağı","Küre Dağı","Kaz Dağları","Uludağ"]),
    Question("cografya_Q_14","", "Aşağıdakilerden hangisi İç Anadolu Bölgesi'ndeki dağımızdır?", "Erciyes", ["Erciyes","Menteşe","Uludağ","Küre","Tendürek"]),
    Question("cografya_Q_15","", "Aşağıdakilerden hangisi kıvrım dağıdır?", "Küre Dağları", ["Aydın Dağları","Küre Dağları","Nur Dağı","Bozdağ","Yunt Dağları"]),
    Question("cografya_Q_16","", "Aşağıdakilerden hangisi volkanik dağ değildir?", "Allahüekber", ["Karacadağ","Melendiz","Ağrı","Tendürek","Allahüekber"]),
    Question("cografya_Q_17","", "Aşağıdakilerden hangisi kıyı ovası değildir?", "Ereğli", ["Silifke","Gediz","Ereğli","Çarşamba","Bafra"]),
    Question("cografya_Q_18","", "Aşağıdakilerden hangisi kıyı ovasıdır?", "Menderes", ["Konya","Menderes","Kayseri","Develi","Harran"]),
    Question("cografya_Q_19","", "Aşağıdakilerden hangisi iç ovadır?", "Çivril", ["Çivril","Bafra","Menderes","Çukurova","Bakırçay"]),
    Question("cografya_Q_20","", "Aşağıdakilerden hangisi iç ova değildir?", "Çarşamba", ["Konya","Kayseri","Ereğli","Harran","Çarşamba"]),
    Question("cografya_Q_21","", "Aşağıdakilerden hangisi karstik ova değldir?", "Develi", ["Tefenni","Kestel","Korkuteli","Acıpayam","Develi"]),
    Question("cografya_Q_22","", "Aşağıdakilerden hangisi karstik ovadır?", "Elmalı", ["Elmalı","Amik","Merzifon","Menderes","Bafra"]),
    Question("cografya_Q_23","", "Aşağıdakilerden hangisi volkanik ovadır?", "Develi", ["Kertel","Gediz","Muş","Develi","Çukurova"]),
    Question("cografya_Q_24","", "Türkiye'de platolar en çok hangi bölgede bulunur?", "İç Anadolu", ["Ege","Marmara","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_25","", "Aşağıdakilerden hangisi İç Anadolu Bölgesi'ndeki platolardan değildir?", "Taşeli", ["Haymana","Cihanbeyli","Bozok","Taşeli","Obruk"]),
    Question("cografya_Q_26","", "Aşağıdakilerden hangisi Marmara Bölgesi'ndeki platolardandır?", "Biga", ["Teke","Obruk","Kars","Bozok","Biga"]),
    Question("cografya_Q_27","", "Akarsuyun doğduğu yere verilen isim aşağıdakilerden hangisidir?", "Akarsu Kaynağı", ["Akarsu Kaynağı","Akarsu Ağzı","Akarsu Yatağı","Akarsu Debisi","Akarsu Rejimi"]),
    Question("cografya_Q_28","", "Akarsuyun döküldüğü yere verilen isim aşağıdakilerden hangisidir?", "Akarsu Ağzı", ["Akarsu Kaynağı","Akarsu Ağzı","Akarsu Yatağı","Akarsu Debisi","Akarsu Rejimi"]),
    Question("cografya_Q_29","", "Akarsuyun herhangi bir yerinden saniyede geçen suyun metreküp cinsinden değerine ne denir?", "Akarsu Debisi", ["Akarsu Rejimi","Akarsu Ritmi","Akarsu Debisi","Akarsu Akış Hızı","Akarsu Miktarı"]),
    Question("cografya_Q_30","", "Akarsuyun yıl içinde görülen değişikliğe ne denir?", "Akarsu Rejimi", ["Akarsu Rejimi","Akarsu Ritmi","Akarsu Debisi","Akarsu Akış Hızı","Akarsu Miktarı"]),
    Question("cografya_Q_31","", "Aşağıdakilerden hangisi akarsuların aşındırma şekillerinden değldir?", "Delta", ["Vadi","Dev Kazanı","Kırgıbayır","Plato","Delta"]),
    Question("cografya_Q_32","", "Aşağıdakilerden hangisi çentik vadilerin özelliklerinden değildir?", "Eğim azdır.", ["Engebenin çok olduğu yerlerde görülür.","Derin aşındırma fazladır.","Doğu Anadalu ve Doğu Karadeniz'de sıktır.","Eğim azdır.","En sık görülen vadidir."]),
    Question("cografya_Q_33","", "Sıradağların üzerinde enine yarılarak oluşan vadi aşağıdakilerden hangisidir?", "Boğaz Vadi", ["Çentik Vadi","Kanyon Vadi","Geniş Tabanlı Vadi","Boğaz Vadi","Yatık Yamaçlı Vadi"]),
    Question("cografya_Q_34","", "Karstik arazide görünen vadi aşağıdakilerden hangisidir?", "Kanyon Vadi", ["Kanyon Vadi","Boğaz Vadi","Çentik Vadi","Geniş Tabanlı Vadi","Yatık Yamaçlı Vadi"]),
    Question("cografya_Q_35","", "Aşağıdakilerden hangisi mendereslerin özelliklerinden değildir?", "Volkanik arazilerde görülür.", ["Yatak eğimi azdır.","Alkış hızı düşüktür.","Volkanik arazilerde görülür.","Enerji potansiyeli azdır.","Akarsular yan aşındırma yaparak oluşturur."]),
    Question("cografya_Q_36","", "Şelalelerin oluşturduğu derin çukurlara ne denir?", "Dev Kazanı", ["Kırgıbayır","Dev Kazanı","Peri Bacaları","Plato","Menderes"]),
    Question("cografya_Q_37","Kırgıbayır akarsuların aşındırma şekillerindendir.", "Aşağıdakilerden hangisi kırgıbayırın özelliklerinden değildir?", "Ege'de sık görülür.", ["Dağ yüzeyinin aşınmasıyla oluşur.","Arazi girintili-çıkıntılı görünür.","Oluşması için şiddetli yağmur gerekir.","Oluşması için cılız bitki örtüsü gerekir.","Ege'de sık görülür."]),
    Question("cografya_Q_38","", "Aşağıdakilerden hangisi peribacalarının bulunduğu yerlerden değildir?", "Niğde", ["Nevşehir","Niğde","Avanos","Ürgüp","Göreme"]),
    Question("cografya_Q_39","", "Delta oluşması için aşağıdakilerden hangisine gerek yoktur?", "Akarsu rejimi düzensiz olmalı.", ["Kıyı derinliği az olmalı.","Kıta sahanlığı geniş olmalı.","Alüvyon bol olmalı.","Denizde akıntı olmamalı.","Akarsu rejimi düzensiz olmalı."]),
    Question("cografya_Q_40","", "Aşağıdakilerden hangisi Karadeniz'e dökülen akarsularımızdan değildir?", "Susurluk", ["Kızılırmak","Yeşilırmak","Susurluk","Bartın Çayı","Sakarya"]),
    Question("cografya_Q_41","", "Aşağıdakilerden hangisi Akdeniz'e dökülen akarsuyumuzdur?", "Aksu", ["Aksu","Meriç","Susurluk","Sakarya","Fırat"]),
    Question("cografya_Q_42","", "Aşağıdakilerden hangiis Akdeniz'e dökülen akarsularımızdan değildir?", "Dicle", ["Manavgat","Seyhan","Ceyhan","Dicle","Göksu"]),
    Question("cografya_Q_43","", "Aşağıdakilerden hangisi Karadeniz'e dökülen akarsularımızdandır?", "Kızılırmak", ["Bakırçay","Kızılırmak","Aksu","Aras","Dicle"]),
    Question("cografya_Q_44","", "Aşağıdakilerden hangisi Ege Denizi'ne dökülen akarsularımızdandır?", "Gediz", ["Bakırçay","Seyhan","Gediz","Çoruh","Manavgat"]),
    Question("cografya_Q_45","", "Aşağıdakilerden hangisi Ege Denizi'ne dökülen akarsularımızdan değildir?", "Aksu", ["Küçük Menderes","Büyük Menderes","Meriç","Gediz","Aksu"]),
    Question("cografya_Q_46","", "Aşağıdakilerden hangisi Basra Körfezi'ne dökülen akarsularımızdandır?", "Fırat", ["Fırat","Aras","Kura","Meriç","Asi"]),
    Question("cografya_Q_47","", "Aşağıdakilerden akarsularımızdan hangisi Basra Körfezi'ne dökülür?", "Dicle", ["Çoruh","Dicle","Kura","Göksu","Aras"]),
    Question("cografya_Q_48","", "Aşağıdakilerden hangisi Hazar Denizi'ne dökülen akarsularımızdandır?", "Aras", ["Aras","Fırat","Dicle","Asi","Meriç"]),
    Question("cografya_Q_49","", "Aşağıdakilerden akarsularımızdan hangisi Hazar Denizi'ne dökülür?", "Kura", ["Meriç","Asi","Kura","Fırat","Dicle"]),
    Question("cografya_Q_50","", "Kaynağını dışarıdan alan akarsuyumuz aşağıdakilerden hangisidir?", "Meriç", ["Çoruh","Kura","Aras","Meriç","Fırat"]),
    Question("cografya_Q_51","", "Aşağıdakilerden hangisi kaynağını dışarıdan alan akarsularımızdandır?", "Asi", ["Aras","Asi","Kura","Fırat","Dicle"]),
    Question("cografya_Q_52","", "Aşağıdakilerden hangisi Türkiye'de doğup dışarıya dökülen akarsularımızdan değildir?", "Meriç", ["Aras","Dicle","Kura","Fırat","Meriç"]),
    Question("cografya_Q_53","", "Aşağıdakilerden hangisi Türkiye'de doğup dışarıya dökülen akarsularımızdandır?", "Fırat", ["Aksu","Fırat","Asi","Göksu","Meriç"]),
    Question("cografya_Q_54","Türkiye'de doğup dışarıya dökülen akarsular bulunmaktadır.", "Aşağıdakilerden hangisi bu kapsamda yer alır?", "Dicle", ["Aksu","Dicle","Asi","Göksu","Meriç"]),
    Question("cografya_Q_55","Ülkemiz sınırları içinde doğup sınır dışına dökülen akarsular bulunmaktadır.", "Aşağıdakilerden hangisi bu kapsamda yer alır?", "Aras", ["Aksu","Asi","Aras","Sakarya","Susurluk"]),
    Question("cografya_Q_56","", "Aşağıdakilerden hangisi ülkemiz sınırları içinde doğup sınır dışına dökülen akarsulardandır?", "Kura", ["Ceyhan","Seyhan","Asi","Kura","Meriç"]),
    Question("cografya_Q_57","", "Aşağıdakilerden hangisi kapalı havza değildir?", "Sakarya Havzası", ["Van Gölü Havzası","Tuz Gölü Havzası","Göller Yöresi Havzası","Konya Havzası","Sakarya Havzası"]),
    Question("cografya_Q_58","", "Türkiye'nin en büyük tatlı su gölü aşağıdakilerden hangisidir?", "Beyşehir", ["Beyşehir","Eğirdir","Burdur","Tuz Gölü","Akşehir"]),
    Question("cografya_Q_59","", "Aşağıdakilerden hangisi tektonik göl değildir?", "Nemrut Gölü", ["Van Gölü","Nemrut Gölü","Hazar Gölü","Çıldır Gölü","Uzungöl"]),
    Question("cografya_Q_60","", "Aşağıdakilerden hangisi set göllerimizden değildir?", "Salda", ["Abant","Yedigöller","Tortum","Salda","Sera"]),
    Question("cografya_Q_61","", "Aşağıdakilerden hangisi heyelan set gölüdür?", "Tortum Gölü", ["Tuz Gölü","Van Gölü","Tortum Gölü","Gölcük Gölü","Kestel Gölü"]),
    Question("cografya_Q_62","", "Aşağıdakilerden hangisi volkanik göldür?", "Meke Tuzlası", ["Terkoz","Eymir","Sülük","Elmalı","Meke Tuzlası"]),
    Question("cografya_Q_63","", "Aşağıdakilerden hangisi karstik göl değildir?", "Çıldır", ["Elmalı","Çıldır","Kestel","Salda","Avlan"]),
    Question("cografya_Q_64","", "Aşağıdakilerden hangisi karstik göldür?", "Kızılören", ["Kızılören","Tuz Gölü","Van Gölü","Uzungöl","Çıldır"]),
    Question("cografya_Q_65","", "Aşağıdakilerden hangisi baraj göllerinin oluşturulma nedenlerinden değildir?", "Turizme katkı sağlamak", ["İçme suyu elde etmek","Kullanma suyu elde etmek","Turizme katkı sağlamak","Tarım arazilerini sulamak","Su taşkınlarını önlemek"]),
    Question("cografya_Q_66","", "Aşağıdakilerden hangisi Fırat Nehri üzerindeki barajlarımızdan değildir?", "Altınkaya", ["Atatürk","Keban","Karakaya","Karkamış","Altınkaya"]),
    Question("cografya_Q_67","", "Aşağıdakilerden hangisi Fırat Nehri üzerindeki barajlarımızdandır?", "Keban", ["Keban","Almus","Demirköprü","Kılıçkaya","Seyhan"]),
    Question("cografya_Q_68","", "Aşağıdakilerden hangisi Dicle Nehri üzerindeki barajlarımızdan değildir?", "Kılıçkaya", ["Dicle","Kılıçkaya","Ilısu","Cizre","Kralkızı"]),
    Question("cografya_Q_69","", "Aşağıdakilerden hangisi Dicle Nehri üzerindeki barajlarımızdandır?", "Ilısu", ["Adıgüzel","Oymapınar","Menzelet","Ilısu","Hasan Uğurlu"]),
    Question("cografya_Q_70","", "Aşağıdakilerden hangisi Kızılırmak Nehri üzerindeki barajlarımızdan değildir?", "Sarıyar", ["Hirfanlı","Altınkaya","Kapulukaya","Kesikköprü","Sarıyar"]),
    Question("cografya_Q_71","", "Aşağıdakilerden hangisi Kızılırmak Nehri üzerindeki barajlarımızdandır?", "Hirfanlı", ["Çatalan","Hirfanlı","Adıgüzel","Manavgat","Almus"]),
    Question("cografya_Q_72","", "Aşağıdakilerden hangisi Yeşilırmak Nehri üzerindeki barajlarımızdan değildir?", "Hasan Polatkan", ["Almus","Kılıçkaya","Suat Uğurlu","Hasan Uğurlu","Hasan Polatkan"]),
    Question("cografya_Q_73","", "Aşağıdakilerden hangisi Yeşilırmak Nehri üzerindeki barajlarımızdandır?", "Kılıçkaya", ["Adıgüzel","Kılıçkaya","Çatalan","Hasan Polatkan","Hirfanlı"]),
    Question("cografya_Q_74","", "Sakarya Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Sarıyar", ["Kralkızı","Almus","Oymapınar","Sarıyar","Kemer"]),
    Question("cografya_Q_75","", "Gediz Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Demirköprü", ["Demirköprü","Seyhan","Ceyhan","Manavgat","Menzelet"]),
    Question("cografya_Q_76","", "Büyük Menderes Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Adıgüzel", ["Aslantaş","Demirköprü","Adıgüzel","Kesikköprü","Çatalan"]),
    Question("cografya_Q_77","", "Seyhan Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Çatalan", ["Ceyhan","Aslantaş","Menzelet","Çatalan","Manavgat"]),
    Question("cografya_Q_78","", "Ceyhan Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Aslantaş", ["Ceyhan","Hirfanlı","Menzelet","Çatalan","Aslantaş"]),
    Question("cografya_Q_79","", "Manavgat Nehri üzerindeki barajlar aşağıdakilerden hangisidir?", "Oymapınar", ["Keban","Oymapınar","Karakaya","Kılıçkaya","Kapulukaya"]),
    Question("cografya_Q_80","", "Aşağıdakilerden hangisi iklimi etkileyen faktörlerden değildir?", "Nüfus", ["Yükselti","Dağların uzanışı","Matematik konum","Etraftaki kara kütlelerinin etkisi","Nüfus"]),
    Question("cografya_Q_81","", "Türkiye'nin en büyük barajı aşağıdakilerden hangisidir?", "Atatürk", ["Atatürk","Keban","Dicle","Seyhan","Ceyhan"]),
    Question("cografya_Q_82","", "Kendi sınırlarımız içinde doğan ve denize dökülen en uzun akarsu aşağıdakilerden hangisidir?", "Kızılırmak", ["Fırat","Yeşilırmak","Kızılırmak","Dicle","Seyhan"]),
    Question("cografya_Q_83","", "Aşağıdakilerden hangisi Türkiye'de sıcaklığı etkileyen faktörlerden değildir?", "Nüfus", ["Enlem","Nüfus","Yükseklik","Eğim","Mevsim"]),
    Question("cografya_Q_84","", "Sıcaklık ile ilgili bilgilerden hangisi yanlıştır?", "Ekvatordan gelen rüzgarlar sıcaklığı azaltır.", ["Güneş ışınlarının dik geldiği yerler daha sıcaktır.","Yükseklik arttıkça sıcaklık azalır.","Karalar çabuk, denizler geç ısınır.","Ekvatordan gelen rüzgarlar sıcaklığı azaltır.","Kuzeye bakan kısımlar daha az ısınır."]),
    Question("cografya_Q_85","", "Aşağıdakilerden hangisi yerel rüzgar değildir?", "Deniz meltemi", ["Yıldız","Deniz meltemi","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_86","", "Kuzeydoğudan esen yerel rüzgar aşağıdakilerden hangisidir?", "Poyraz", ["Yıldız","Deniz meltemi","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_87","", "Kuzeybatıdan esen yerel rüzgar aşağıdakilerden hangisidir?", "Karayel", ["Yıldız","Deniz meltemi","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_88","", "Güneybatıdan esen yerel rüzgar aşağıdakilerden hangisidir?", "Lodos", ["Yıldız","Deniz meltemi","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_89","", "Güneydoğudan esen yerel rüzgar aşağıdakilerden hangisidir?", "Samyeli", ["Samyeli","Deniz meltemi","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_90","", "Kuzeyden esen yerel rüzgar aşağıdakilerden hangisidir?", "Yıldız", ["Yıldız","Kıble","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_91","", "Güneyden esen yerel rüzgar aşağıdakilerden hangisidir?", "Kıble", ["Yıldız","Kıble","Poyraz","Lodos","Karayel"]),
    Question("cografya_Q_92","", "Denizden karaya doğru esen rüzgarın adı aşağıdakilerden hangisidir?", "Deniz meltemi", ["Deniz meltemi","Karayel meltemi","Kara meltemi","Vadi meltemi","Dağ meltemi"]),
    Question("cografya_Q_93","", "Karadan denize doğru esen rüzgarın adı aşağıdakilerden hangisidir?", "Kara meltemi", ["Deniz meltemi","Karayel meltemi","Kara meltemi","Vadi meltemi","Dağ meltemi"]),
    Question("cografya_Q_94","", "Vadiden dağa doğru esen rüzgarın adı aşağıdakilerden hangisidir?", "Vadi meltemi", ["Deniz meltemi","Karayel meltemi","Kara meltemi","Vadi meltemi","Dağ meltemi"]),
    Question("cografya_Q_95","", "Dağdan vadiye doğru esen rüzgarın adı aşağıdakilerden hangisidir?", "Dağ meltemi", ["Deniz meltemi","Karayel meltemi","Kara meltemi","Vadi meltemi","Dağ meltemi"]),
    Question("cografya_Q_96","", "Ege'de esen imbat rüzgarının diğer adı aşağıdakilerden hangisidir?", "Deniz meltemi", ["Deniz meltemi","Karayel meltemi","Kara meltemi","Vadi meltemi","Dağ meltemi"]),
    Question("cografya_Q_97","", "Dağ yamaçları boyunca alçalan hava hareketleri nedeniyle oluşan rüzgar aşağıdakilerden hangisidir?", "Fön rüzgarları", ["Fön rüzgarları","Deniz meltemi","Dağ meltemi","Vadi meltemi","Kara meltemi"]),
    Question("cografya_Q_98","", "Sıcak ve soğuk hava kütlelerinin karşılaşıp, sıcak havanın yoğunlaşmasıyla oluşan yağış şekli aşağıdakilerden hangisidir?", "Cephe yağışları", ["Yamaç yağışları","Konveksiyonel yağışlar","Yaz yağışları","Kıyı yağışları","Cephe yağışları"]),
    Question("cografya_Q_99","", "Isınan havanın yükselip soğumasıyla oluşan yağış şekli aşağıdakilerden hangisidir?", "Konveksiyonel yağışlar", ["Yamaç yağışları","Konveksiyonel yağışlar","Yaz yağışları","Kıyı yağışları","Cephe yağışları"]),
    Question("cografya_Q_100","", "Nemli havanın yamaç boyunca yükselip soğumasıyla oluşan yağış şekli aşağıdakilerden hangisidir?", "Yamaç yağışları", ["Yamaç yağışları","Konveksiyonel yağışlar","Yaz yağışları","Kıyı yağışları","Cephe yağışları"]),
    Question("cografya_Q_101","", "Kırkikindi yağmurları olarak bilinen yağış aşağıdakilerden hangisidir?", "Konveksiyonel yağışlar", ["Yamaç yağışları","Konveksiyonel yağışlar","Yaz yağışları","Kıyı yağışları","Cephe yağışları"]),
    Question("cografya_Q_102","", "Aşağıdakilerden hangisi Karadeniz ikliminin özelliklerinden değildir?", "Sıcaklık farkı çoktur.", ["Yazlar serin, kışlar ılıktır.","Her mevsim yağışlıdır.","Yamaç yağışları görülür.","Sıcaklık farkı çoktur.","Karadeniz'in kıyı kesimlerinde görülür."]),
    Question("cografya_Q_103","", "Aşağıdakilerden hangisi Akdeniz ikliminin özelliklerinden değildir?", "Yağış en çok yazın olur.", ["Yazlar sıcak ve kuraktır.","Kışlar ılık ve yağışlıdır.","Yağış en çok yazın olur.","Cephe yağışları görülür.","Akdeniz ve Ege'de görülür."]),
    Question("cografya_Q_104","", "Aşağıdakilerden hangisi Karasal iklimin özelliklerinden değildir?", "En çok yağış yazın görülür.", ["Yazlar sıcak ve kuraktır.","En çok yağış yazın görülür.","Kışlar sert ve uzundur.","Buharlaşma çoktur.","İç Anadolu'da görülür."]),
    Question("cografya_Q_105","", "Türkiye'nin ilk nüfus sayımı ne zaman yapılmıştır?", "1927", ["1923","1924","1927","1930","1934"]),
    Question("cografya_Q_106","", "Nüfus sayımını gerçekleştiren kurum aşağıdakilerden hangisidir?", "Devlet İstatistik Enstitüsü", ["Devlet Sayım Kurumu","Nüfus Dairesi Başkanlığı","Merkezi Koordinasyon Başkanlığı","Devlet İstatistik Enstitüsü","Devlet Planlama Teşkilatı"]),
    Question("cografya_Q_107","", "Aşağıdakilerden hangisi nüfusun artma nedenlerinden değildir?", "Tarım faaliyetlerinin artması", ["Tarım faaliyetlerinin artması","Dıştan gelen göçler","Doğumların artması","Bebek ölümlerinin azalması","Beslenme koşullarının iyileşmesi"]),
    Question("cografya_Q_108","", "Aşağıdakilerden hangisi nüfusun dağılışını etkileyen faktörlerden değildir?", "Gelir düzeyi", ["İklim","Yerşekilleri","Ulaşım","Sanayi","Gelir düzeyi"]),
    Question("cografya_Q_109","", "Aşağıdakilerden hangisi nüfusun en kalabalık olduğu bölgedir?", "Marmara", ["Ege","Marmara","İç Anadolu","Karadeniz","Akdeniz"]),
    Question("cografya_Q_110","", "Aşağıdakilerden hangisi nüfusun en az olduğu bölgedir?", "Doğu Anadolu", ["İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu","Akdeniz","Karadeniz"]),
    Question("cografya_Q_111","", "Aşağıdakilerden hangisinde pamuk yetişmez?", "Ardahan", ["Aydın","Mersin","Adana","Iğdır","Ardahan"]),
    Question("cografya_Q_112","", "Ülkemizde ipekböcekciliği yoğun olarak nerelerde yapılır?", "Bursa-Bilecik-Eskişehir", ["Aydın-Muğla-Denizli","Ağrı-Van-Muş","Bursa-Bilecik-Eskişehir","Hatay-Adana-Mersin","Konya-Kayseri-Sivas"]),
    Question("cografya_Q_113","I-Bursa\nII-Muğla\nIII-Bilecik", "Yukarıdakilerden hangisi veya hangilerinde ipekböcekciliği yoğun olarak yapılır?", "I-III", ["Yalnız I","Yalnız II","Yalnız III","I-III","I-II-III"]),
    Question("cografya_Q_114","", "Çayın en çok üretildiği il aşağıdakilerden hangisidir?", "Rize", ["Adana","Ağrı","İzmir","Rize","Çanakkale"]),
    Question("cografya_Q_115","", "Aşağıdaki bölgelerimizden hangisinde zeytin üretilmez?", "Doğu Anadolu", ["Ege","Doğu Anadolu","Marmara","Akdeniz","Güneydoğu Anadolu"]),
    Question("cografya_Q_116","", "Ayçiçek üretimi en çok aşağıdaki bölgelerden hangisinde olur?", "Marmara", ["Marmara","Ege","İç Anadolu","Akdeniz","Karadeniz"]),
    Question("cografya_Q_117","", "Aşağıdakilerden hangisi demir madeninin çıkarıldığı yerlerden biri değildir?", "Menteşe", ["Divriği","Hekimhan","Edremit","Dikili","Menteşe"]),
    Question("cografya_Q_118","", "Aşağıdakilerden hangisinde demir-Çelik fabrikası bulunur?", "Karabük", ["Ağrı","Hakkari","Karabük","Trabzon","Adıyaman"]),
    Question("cografya_Q_119","", "Bakır madeni aşağıdaki amaçlardan hangisi için kullanılır?", "Elektronik sanayi", ["Cam sanayi","Seramik sanayi","Dokuma sanayi","Elektronik sanayi","Gıda sanayi"]),
    Question("cografya_Q_120","", "Aşağıdakilerden hangisi bakır madeninin çıkarıldığı yerlerden değildir?", "Divriği", ["Murgul","Küre","Maden","Divriği","Ergani"]),
    Question("cografya_Q_121","", "Demir sertleştirmede kullanılan maden aşağıdakilerden hangisinde verilmiştir?", "Krom", ["Bakır","Krom","Bor","Civa","Aliminyum"]),
    Question("cografya_Q_122","", "Aşağıdakilerden hangisi krom madeninin çıkarıldığı yerlerden değildir?", "Aydın", ["Elazığ","Muğla","Aydın","Kayseri","Kütahya"]),
    Question("cografya_Q_123","", "Krom madeni hangi illerimizde işlenir?", "Antalya-Elazığ", ["Muğla-Denizli","Adana-Kayseri","Mersin-İskenderun","Antalya-Elazığ","Bursa-Maraş"]),
    Question("cografya_Q_124","", "Aşağıdakilerden hangisi aliminyumun kullanım alanlarından değildir?", "Nükleer alan", ["Otomobil sanayisi","Ev eşyası yapımı","İnşaat sektörü","Elektrikli araçlar","Nükleer alan"]),
    Question("cografya_Q_125","", "Aşağıdakilerden hangisi aliminyumun çıkarıldığı yerlerden değildir?", "Divriği", ["Divriği","Seydişehir","Milas","Akseki","Islahiye"]),
    Question("cografya_Q_126","", "Aşağıdakilerden hangisi aliminyum madeninin işlendiği yerlerdendir?", "Seydişehir", ["Bandırma","Seydişehir","Eğirdir","Torbalı","Akhisar"]),
    Question("cografya_Q_127","", "Dünyanın en zengin bor rezervi aşağıdaki ülkelerden hangisindedir?", "Türkiye", ["Almanya","Türkiye","İtalya","Fransa","İngiltere"]),
    Question("cografya_Q_128","", "Aşağıdakilerden hangisi bor madeninin kullanım alanlarından değildir?", "Boya", ["Nükleer alan","Jet ve roket yakıtı","Boya","Cam","Sabun"]),
    Question("cografya_Q_129","", "Aşağıdakilerden hangisi bor madeninin çıkarıldığı yerlerden değildir?", "Uşak", ["Balıkesir","Kütahya","Bursa","Uşak","Eskişehir"]),
    Question("cografya_Q_130","", "Aşağıdakilerden hangisi bor madeninin işlendiği yerlerdendir?", "Bandırma", ["Kula","Manavgat","Seydişehir","Küre","Bandırma"]),
    Question("cografya_Q_131","", "Aşağıdakilerden hangisi kurşun-çinko madenlerinin kullanım alanlarından değildir?", "Süs eşyası", ["Silah sanayi","Süs eşyası","Paslanmaz metal üretimi","Akü imalatı","Ses yalıtımı"]),
    Question("cografya_Q_132","", "Kurşun-çinko madeninin en çok çıkarıldığı yer aşağıdakilerden hangisidir?", "Elazığ-Keban", ["Muğla-Marmaris","Denizli-Tavas","Elazığ-Keban","Sivas-Divriği","Rize-Çayeli"]),
    Question("cografya_Q_133","", "Aşağıdakilerden hangisi kükürdün kullanım alanlarından değildir?", "Akü imalatı", ["Sülfirik asit","Kimya sanayi","Hava-i fişek","Akü imalatı","Zirai ilaç yapımı"]),
    Question("cografya_Q_134","", "Kükürt madeni en çok aşağıdakilerden hangisinde çıkarılır?", "Isparta (Keçiborlu)", ["Isparta (Keçiborlu)","Ankara (Polatlı)","Afyon (Elmadağ)","Kütahya (Emet)","Muğla (Fethiye)"]),
    Question("cografya_Q_135","", "Aşağıdaki madenlerden hangisi sıvı şeklinde bulunur?", "Civa", ["Bor","Civa","Kükürt","Demir","Bakır"]),
    Question("cografya_Q_136","", "Aşağıdakilerden hangisi civa madeninin kullanım alanlarından değildir?", "Süs eşyası yapımı", ["Zirai ilaç yapımı","Suni gübre üretimi","Süs eşyası yapımı","Boya sanayi","Kağıt sanayi"]),
    Question("cografya_Q_137","", "Aşağıdakilerden hangisi civa madeninin çıkarıldığı yerlerdendir?", "İzmir-Ödemiş", ["Samsun-Canik","Balıkesir-Edremit","Eskişehir-Osmangazi","Afyon-Çay","İzmir-Ödemiş"]),
    Question("cografya_Q_138","", "Aşağıdakilerden hangisi lületaşının çıkarıldığı illerdendir?", "Eskişehir", ["Denizli","Tekirdağ","Çanakkale","Eskişehir","Balıkesir"]),
    Question("cografya_Q_139","", "Aşağıdakilerden hangisi lületaşının kullanım amaçlarındandır?", "Süs eşyası yapımı", ["İnşaat sektörü","Boya sanayi","Suni gübre","Zirai ilaç yapımı","Süs eşyası yapımı"]),
    Question("cografya_Q_140","", "Oltu taşının çıkarıldığı ilimiz aşağıdakilerden hangisidir?", "Erzurum", ["Erzurum","Erzincan","Trabzon","Ardahan","Malatya"]),
    Question("cografya_Q_141","", "Aşağıdakilerden hangisi mermer madeninin çıkarıldığı yerlerden biri değildir?", "Niğde", ["Afyon","Niğde","Kütahya","Kırşehir","Tokat"]),
    Question("cografya_Q_142","", "Tuzun en çok çıkarıldığı ilimiz aşağıdakilerden hangisidir?", "İzmir", ["İzmir","Çankırı","Kars","Iğdır","Nevşehir"]),
    Question("cografya_Q_143","", "Taş kömürünün en çok çıkarıldığı ilimiz aşağıdakilerden hangisidir?", "Zonguldak", ["Edirne","Zonguldak","Samsun","Sinop","Yozgat"]),
    Question("cografya_Q_144","", "Demir-çelik sanayisinde tüketilen enerji kaynağı aşağıdakilerden hangisidir?", "Taş kömürü", ["Linyit","Petrol","Doğalgaz","Taş kömürü","Jeotermal enerji"]),
    Question("cografya_Q_145","", "Esmer kömür olarak bilinen enerji kaynağımız aşağıdakilerden hangisidir?", "Linyit", ["Taş kömürü","Linyit","Petrol","Doğalgaz","Jeotermal enerji"]),
    Question("cografya_Q_146","", "En zengin enerji kaynağımız aşağıdakilerden hangisidir?", "Linyit", ["Taş kömürü","Linyit","Petrol","Doğalgaz","Jeotermal enerji"]),
    Question("cografya_Q_147","", "Aşağıdakilerden hangisi termik santrallerimizin bulunduğu yerlerden değildir?", "Sivas-Hafik", ["Kütahya-Seyitömer","Muğla-Yatağan","Manisa-Soma","Sivas-Hafik","Zonguldak-Çatalağzı"]),
    Question("cografya_Q_148","", "Aşağıdakilerden hangisi linyitin çıkarıldığı yerlerden değildir?", "Bitlis-Tatvan", ["Muğla-Yatağan","Manisa-Soma","Kütahya-Seyitömer","Kahramanmaraş-Afşin","Bitlis-Tatvan"]),
    Question("cografya_Q_149","", "Petrolün ilk kez bulunduğu yer aşağıdakilerden hangisidir?", "Raman", ["Raman","İkiköprü","Beşiri","Alaca","Balpınar"]),
    Question("cografya_Q_150","", "Aşağıdakilerden hangisi petrol çıkarılan yerlerden değildir?", "Ordu", ["Mardin","Adıyaman","Ordu","Diyarbakır","Siirt"]),
    Question("cografya_Q_151","", "Petrol ilk kez hangi yılda bulunmuştur?", "1940", ["1939","1940","1941","1945","1948"]),
    Question("cografya_Q_152","", "Buhardan elde edilen enerji türü aşağıdakilerden hangisidir?", "Jeotermal enerji", ["Jeotermal enerji","Hidroelektirik enerji","Elektrik enerjisi","Manyetik enerji","Ses enerjisi"]),
    Question("cografya_Q_153","", "Jeotermal enerji bulunan ilimiz aşağıdakilerden hangisidir?", "Afyon", ["Kayseri","Niğde","Konya","Afyon","Adana"]),
    Question("cografya_Q_154","", "Barajlardan elde edilen enerji türü aşağıdakilerden hangisidir?", "Hidroelektrik enerji", ["Hidroelektrik enerji","Jeotermal enerji","Kimyasal enerji","Manyetik enerji","Nükleer enerji"]),
    Question("cografya_Q_155","", "Hidroelektrik enerji potansiyelinin en yüksek olduğu bölgemiz aşağıdakilerden hangisidir?", "Doğu Anadolu", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_156","", "Aşağıdakilerden hangisi Türkiye'nin ihraçta birinci olduğu ürünlerden değildir?", "Çay", ["Fındık","Çay","Kiraz","İncir","Kayısı"]),
    Question("cografya_Q_157","", "Buğdayın en fazla yetiştiği bölgemiz aşağıdakilerden hangisidir?", "İç Anadolu", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_158","", "Buğday hangi bölgemizde yetişmez?", "Karadeniz", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_159","", "Buğday ile ilgili verilenlerden hangisi yanlıştır?", "Yazın yağmur ister", ["En geniş ekim alanına sahiptir","En fazla İç Anadolu'da yetişir","Yazın yağmur ister","Karadeniz'de yetişmez","İlkbahar'da yağış, yazın sıcaklık ister"]),
    Question("cografya_Q_160","", "Arpa ile ilgili aşağıda verilenlerden hangisi yanlıştır?", "Sıcağa dayanıklı değildir.", ["Buğdaydan sonra en fazla üretilen tahıldır","Soğuğa dayanıklıdır","En fazla İç Anadolu'da yetişir","Hayvan yemi yapımında kullanılır","Sıcağa dayanıklı değildir."]),
    Question("cografya_Q_161","", "Çavdar ile ilgili aşağıda verilenlerden hangisi yanlıştır?", "Doğu Anadolu'da yetişmez", ["Düşük ısıya dayanıklıdır","Un yapımında kullanılır","Doğu Anadolu'da yetişmez","Hayvan yemi olarak kullanılır","İç Anadolu'da yetişir"]),
    Question("cografya_Q_162","", "Musur hangi bölgede daha çok yetişir?", "Karadeniz", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_163","", "Aşağıdaki illerden hangisinde pirinç üretilmez?", "Niğde", ["Edirne","Samsun","Çorum","Niğde","Sinop"]),
    Question("cografya_Q_164","", "Pirincin yerleşim yerlerine yakın ekimi neden yasaklanmıştır?", "Sivrisineğe neden olması", ["Halkın istememesi","Sivrisineğe neden olması","Su taşkınlarına sebep olması","Fazla yer kaplaması","Maliyetinin fazla olması"]),
    Question("cografya_Q_165","", "Pirinç ile ilgili aşağıdakilerden hangisi yanlıştır?", "Sıcaklığı sevmez", ["Bol su ister","Vadi tabanlarında üretilir","Yerleşim yerlerine yakın yerlere ekimi yasaktır","","Sıcaklığı sevmez"]),
    Question("cografya_Q_166","", "Mercimek için verilenlerden hangisi yanlıştır?", "Kırmızı mercimek en çok Gaziantep'te yetişir", ["Kırmızı mercimek en çok Gaziantep'te yetişir","Yetişirken yağış ister","Olgunlaşırken sıcaklık ister","Kırmızı mercimek en çok Güneydoğu'da yetişir","Yeşil mercimek en çok İç Anadolu'da yetişir."]),
    Question("cografya_Q_167","", "Nohutun en çok yetiştiği bölgemiz aşağıdakilerden hangisidir?", "İç Anadolu", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_168","", "Patates en çok hangi bölgemizde yetişir?", "İç Anadolu", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_169","", "Tütün aşağıdaki toprak türlerinden hangisini sever?", "Kumlu Toprak", ["Kumlu Toprak","Taşlı Toprak","Humuslu Toprak","Tınlı Toprak","Marnlı Toprak"]),
    Question("cografya_Q_170","", "Tütün ile ilgili aşağıdakilerden hangisi yanlıştır?", "Bir yıl arayla ürün verir", ["Çimlenmede bol su ister","Bir yıl arayla ürün verir","Büyürken sıcaklık ister","Kumlu toprakları sever","En fazla Denizli ve Manisa'da yetişir."]),
    Question("cografya_Q_171","", "Pamuk aşağıdakiki bölgelerimizden hangisinde yetişmez?", "Karadeniz", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_172","", "Şeker pancarı ile ilgili verilenlerden hangisi yanlıştır?", "En çok Ege'de yetişir.", ["Soğuğa karşı dayanıklıdır.","İlkbaharda ekilir.","Güzün hasad edilir.","En çok Ege'de yetişir.","Yem ve ispirto sanayisinde kullanılır."]),
    Question("cografya_Q_173","", "Çay ile ilgili verilen bilgilerden hangisi yanlıştır?", "Nemi sevmez.", ["Sürekli yağış ister.","Eğimli arazide yetişir.","Gölgeli araziyi sever.","Ordu, Rize'de yetişir.","Nemi sevmez."]),
    Question("cografya_Q_174","", "Bir yıl arayla ürün veren bitki seçeneklerden hangisinde doğru verilmiştir?", "Zeytin", ["Çay","Zeytin","Pirinç","Tütün","Şekerpancarı"]),
    Question("cografya_Q_175","", "Ayçiçeği en çok aşağıdaki bölgelerden hangisinde yetişir?", "Marmara", ["Marmara","Ege","İç Anadolu","Akdeniz","Karadeniz"]),
    Question("cografya_Q_176","", "İlaç ve uyuşturucu yapımında kullanılan bitki aşağıdakilerden hangisidir?", "Haşhaş", ["Susam","Ketem","Haşhaş","Kenevir","Yer Fıstığı"]),
    Question("cografya_Q_177","", "Tohumundan bezir yağı elde edilen bitki aşağıdakilerden hangisinde verilmiştir?", "Keten, Kenevir", ["Susam","Haşhaş","Yer Fıstığı","Ayçiçeği","Keten, Kenevir"]),
    Question("cografya_Q_178","", "Aşağıdakilerden hangisi keten, kenevir'in çok yetiştirildiği illerimizden değildir?", "Ardahan", ["Sinop","Zonguldak","Ardahan","Kastamonu","Kocaeli"]),
    Question("cografya_Q_179","", "En çok fındık üreten ülke aşağıdakilerden hangisidir?", "Türkiye", ["Türkiye","Yunanistan","Bulgaristan","Rusya","Ermenistan"]),
    Question("cografya_Q_180","", "Fındık en çok aşağıdaki bölgelerimizden hangisinde yetişir?", "Karadeniz", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_181","", "En çok incir üreten ülke aşağıdakilerden hangisidir?", "Türkiye", ["Türkiye","Yunanistan","Bulgaristan","Rusya","Ermenistan"]),
    Question("cografya_Q_182","", "İncir ile ilgili verilen bilgilerden hangisi yanlıştır?", "Soğuğa dayanıklıdır.", ["En çok Ege'de ve Akdeniz'de yetişir.","Akdeniz iklimini sever.","En çok Türkiye'de yetişir.","Kurutularak satılabilir.","Soğuğa dayanıklıdır."]),
    Question("cografya_Q_183","", "Aşağıdakilerden hangisi üzümün tüketilme şekillerinden değildir?", "Yağ", ["Pekmez","Yağ","Kuruyemiş","Yemeklik","Şarap"]),
    Question("cografya_Q_184","", "Her bölgede yetişebilen meyve aşağıdakilerden hangisidir?", "Üzüm", ["Fındık","Antep Fıstığı","Üzüm","Muz","Kayısı"]),
    Question("cografya_Q_185","", "Muz aşağıdakilerden hangisinde yetişir?", "Mersin", ["Mersin","Zonguldak","Çanakkale","Balıkesir","Kütahya"]),
    Question("cografya_Q_186","", "Aşağıdakilerden hangisi koyun soylarından değildir?", "Tiftik koyun", ["Merinos koyun","Tiftik koyun","Sakız koyun","Karaman koyun","Dağlıç koyun"]),
    Question("cografya_Q_187","", "Dağlık olmayan yerlerde yetişen ve et verimi yüksek olan koyun türü aşağıdakilerden hangisidir?", "Dağlıç koyun", ["Sakız koyun","Merinos koyun","Dağlıç koyun","Karaman koyun","Kıvırcık koyun"]),
    Question("cografya_Q_188","", "Et verimi düşük, yünü kaliteli olan koyun türü aşağıdakilerden hangisidir?", "Merinos koyun", ["Sakız koyun","Merinos koyun","Dağlıç koyun","Karaman koyun","Kıvırcık koyun"]),
    Question("cografya_Q_189","", "Kıl keçisi için aşağıdakilerden hangisi yanlıştır?", "Dik yamaçlarda görülmez.", ["Koyuna göre daha dayanıklıdır.","Doğu Anadolu'da sık görülür.","Eti, kılı ve sütü için bakılır","Dik yamaçlarda görülmez.","Dağlık yerlerde yetiştirilir."]),
    Question("cografya_Q_190","", "Büyükbaş hayvancılık için aşağıdakilerden hangisi yanlıştır?", "İyi cinsleri Edirne-Tekirdağ'da yetiştirilir.", ["Her bölgede yetiştirilir.","Sığır, at, manda büyükbaşa örnektir.","Eti, sütü için yetiştirilir.","Gücünden yararlanılır.","İyi cinsleri Edirne-Tekirdağ'da yetiştirilir."]),
    Question("cografya_Q_191","", "Aşağıdakilerden hangisi kümes hayvanı değildir?", "Köpek", ["Tavuk","Köpek","Kaz","Ördek","Hindi"]),
    Question("cografya_Q_192","", "Balıkçılığın en çok yapıldığı bölgemiz aşağıdakilerden hangisidir?", "Karadeniz", ["Akdeniz","Karadeniz","İç Anadolu","Doğu Anadolu","Güneydoğu Anadolu"]),
    Question("cografya_Q_193","", "Aşağıdakilerden hangisi Karadeniz'de balıkçılığın çok olma sebeplerinden değildir?", "Oksijenin az olması", ["Tuzluluk oranının düşük olması","Çok sayıda akarsuyun planktonun bol olması","Oksijenin az olması","Tarım arazisinin az olması","Deniz suyunun soğuk olması"]),
    Question("cografya_Q_194","", "İpek böceklerinin besin kaynağı aşağıdakilerden hangisidir?", "Dut yaprağı", ["Dut yaprağı","Elma yaprağı","Ayva yaprağı","Portakal yaprağı","Turunç yaprağı"]),
    Question("cografya_Q_195","", "Arıcılık en çok aşağıdaki bölgelerden hangisinde yapılır?", "Karadeniz", ["Akdeniz","Doğu Anadolu","İç Anadolu","Karadeniz","Güneydoğu Anadolu"]),

  ];
  List<Question> get cografyaQuesList=>_cografyaQuesList;
}