import 'package:flutter/material.dart';

import '../../../model/question.dart';

class GuncelBilgilerQuesViewModel extends ChangeNotifier{
  List<Question> _guncelBilgilerQuesList=[
    Question("cografya_Q_1","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_2","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_3","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_4","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_5","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_6","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_7","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_8","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_9","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
    Question("cografya_Q_10","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor",["Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor","Hazırlanıyor"]),
   // Question("cografya_Q_11","","","",["","","","",""]),
   // Question("cografya_Q_12","","","",["","","","",""]),
   // Question("cografya_Q_13","","","",["","","","",""]),
   // Question("cografya_Q_14","","","",["","","","",""]),
   // Question("cografya_Q_15","","","",["","","","",""]),
   // Question("cografya_Q_16","","","",["","","","",""]),
   // Question("cografya_Q_17","","","",["","","","",""]),
   // Question("cografya_Q_18","","","",["","","","",""]),
   // Question("cografya_Q_19","","","",["","","","",""]),
   // Question("cografya_Q_20","","","",["","","","",""]),
   // Question("cografya_Q_21","","","",["","","","",""]),
   // Question("cografya_Q_22","","","",["","","","",""]),
   // Question("cografya_Q_23","","","",["","","","",""]),
   // Question("cografya_Q_24","","","",["","","","",""]),
   // Question("cografya_Q_25","","","",["","","","",""]),
   // Question("cografya_Q_26","","","",["","","","",""]),
   // Question("cografya_Q_27","","","",["","","","",""]),
   // Question("cografya_Q_28","","","",["","","","",""]),
   // Question("cografya_Q_29","","","",["","","","",""]),
   // Question("cografya_Q_30","","","",["","","","",""]),
   // Question("cografya_Q_31","","","",["","","","",""]),
   // Question("cografya_Q_32","","","",["","","","",""]),
   // Question("cografya_Q_33","","","",["","","","",""]),
   // Question("cografya_Q_34","","","",["","","","",""]),
   // Question("cografya_Q_35","","","",["","","","",""]),
   // Question("cografya_Q_36","","","",["","","","",""]),
   // Question("cografya_Q_37","","","",["","","","",""]),
   // Question("cografya_Q_38","","","",["","","","",""]),
   // Question("cografya_Q_39","","","",["","","","",""]),
   // Question("cografya_Q_40","","","",["","","","",""]),
   // Question("cografya_Q_41","","","",["","","","",""]),
   // Question("cografya_Q_42","","","",["","","","",""]),
   // Question("cografya_Q_43","","","",["","","","",""]),
   // Question("cografya_Q_44","","","",["","","","",""]),
   // Question("cografya_Q_45","","","",["","","","",""]),
   // Question("cografya_Q_46","","","",["","","","",""]),
   // Question("cografya_Q_47","","","",["","","","",""]),
   // Question("cografya_Q_48","","","",["","","","",""]),
   // Question("cografya_Q_49","","","",["","","","",""]),
   // Question("cografya_Q_50","","","",["","","","",""]),
   // Question("cografya_Q_51","","","",["","","","",""]),
   // Question("cografya_Q_52","","","",["","","","",""]),
   // Question("cografya_Q_53","","","",["","","","",""]),
   // Question("cografya_Q_54","","","",["","","","",""]),
   // Question("cografya_Q_55","","","",["","","","",""]),
   // Question("cografya_Q_56","","","",["","","","",""]),
   // Question("cografya_Q_57","","","",["","","","",""]),
   // Question("cografya_Q_58","","","",["","","","",""]),
   // Question("cografya_Q_59","","","",["","","","",""]),
   // Question("cografya_Q_60","","","",["","","","",""]),
   // Question("cografya_Q_61","","","",["","","","",""]),
   // Question("cografya_Q_62","","","",["","","","",""]),
   // Question("cografya_Q_63","","","",["","","","",""]),
   // Question("cografya_Q_64","","","",["","","","",""]),
   // Question("cografya_Q_65","","","",["","","","",""]),
   // Question("cografya_Q_66","","","",["","","","",""]),
   // Question("cografya_Q_67","","","",["","","","",""]),
   // Question("cografya_Q_68","","","",["","","","",""]),
   // Question("cografya_Q_69","","","",["","","","",""]),
   // Question("cografya_Q_70","","","",["","","","",""]),
   // Question("cografya_Q_71","","","",["","","","",""]),
   // Question("cografya_Q_72","","","",["","","","",""]),
   // Question("cografya_Q_73","","","",["","","","",""]),
   // Question("cografya_Q_74","","","",["","","","",""]),
   // Question("cografya_Q_75","","","",["","","","",""]),
   // Question("cografya_Q_76","","","",["","","","",""]),
   // Question("cografya_Q_77","","","",["","","","",""]),
   // Question("cografya_Q_78","","","",["","","","",""]),
   // Question("cografya_Q_79","","","",["","","","",""]),
   // Question("cografya_Q_80","","","",["","","","",""]),
   // Question("cografya_Q_81","","","",["","","","",""]),
   // Question("cografya_Q_82","","","",["","","","",""]),
   // Question("cografya_Q_83","","","",["","","","",""]),
   // Question("cografya_Q_84","","","",["","","","",""]),
   // Question("cografya_Q_85","","","",["","","","",""]),
   // Question("cografya_Q_86","","","",["","","","",""]),
   // Question("cografya_Q_87","","","",["","","","",""]),
   // Question("cografya_Q_88","","","",["","","","",""]),
   // Question("cografya_Q_89","","","",["","","","",""]),
   // Question("cografya_Q_90","","","",["","","","",""]),
   // Question("cografya_Q_91","","","",["","","","",""]),
   // Question("cografya_Q_92","","","",["","","","",""]),
   // Question("cografya_Q_93","","","",["","","","",""]),
   // Question("cografya_Q_94","","","",["","","","",""]),
   // Question("cografya_Q_95","","","",["","","","",""]),
   // Question("cografya_Q_96","","","",["","","","",""]),
   // Question("cografya_Q_97","","","",["","","","",""]),
   // Question("cografya_Q_98","","","",["","","","",""]),
   // Question("cografya_Q_99","","","",["","","","",""]),
     ];
  List<Question> get guncelBilgilerQuesList=>_guncelBilgilerQuesList;
}