import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class CevreIklimInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _cevreIklimList = [
    InfoCardModel("Çevre Eğitimi Genel Bakış", [
      InfoCardItem("ff_info_1", "Çevre Nedir?", "-Tüm canlıların hayat boyu ilişkilerini sürdürdükleri ortamlardır.\n-Canlılar çevre içerisinde etkileşim halindedir.\n-Etkileşimler, biyolojik, sosyal, ekonomik ve fiziki olabilir."),
      InfoCardItem("ff_info_2", "Çevre Neden Önemlidir?", "-Hayatın sürdürülmesi için temel unsurdur.\n-Tüm kaynakların yer aldığı merkezdir.\n-Canlıların etkileşimlerine ev sahipliği yapar.\n-Ortak kullanım alanıdır.\n-Tüm canlılara hitap eder."),
      InfoCardItem("ff_info_3", "Çevre Eğitimi", "-Toplumun çevre konusunda bilinçlenmesidir.\n-Çevre eğitimi alan bireylerin, çevre konusunda olumlu tutum ve davranışlar sergilemesi beklenir.\n-Olumlu davranışların ve davranış değişikliklerinin kalıcı olması beklenir.\n-Bu davranışların kazanılması için çaba gerekir.\n-Çevresel sorunların çözülmesinde, eğitimle, bireyin aktif katılımı beklenir."),
      InfoCardItem("ff_info_4", "Çevre Eğitiminin Amaçları", "-Bireylerin çevreyi tanımalarını sağlamak.\n-Bireylere çevre bilinci kazandırmak.\n-Çevremizdeki var olan sorunların tespitinin yapılmasını sağlamak.\n-Ortaya çıkabilecek çevresel sorunların önceden tespitini sağlamak.\n-Çevresel sorunların çözümünde bireylerin aktif katılımlarını sağlamak.\n-Toplumda çevre bilincini yerleştirmek.\n-Yaşanılabilir çevre oluşturma sürecinde olumlu davranış değişiklikleri gerçekleştirmek"),
      InfoCardItem("ff_info_5", "Ne zaman başlar?", "-Çevre eğitiminin erken yaşlarda başlaması esastır.\n-Bu sebeple henüz okul öncesine devam etmekte olan bireylerin bu eğitimlerden faydalanması esastır.\n-Çevre eğitimi okul öncesi eğitim kurumlarının faaliyetleri arasında yer almaktadır.\n-Bireylerin erken yaşta gerekli bilinci ve tutumları kazanmaları ülkemizin ve dünyanın geleceği için önem arz etmektedir."),
      InfoCardItem("ff_info_6","Neler yapılabilir?", "-Çevre eğitimleri kapsamında erken dönemde başlayacak faaliyetlerde oyun ile öğrenme temel alınabilir.\n-Geri dönüşüm kutuları, çöp kutuları, atık kutuları gibi basit tasarımlar bu yaş grubuna tasarlatılabilir.\n-İlkokul ve ortaokul çağındaki çocuklar için animasyonlar daha ilgi çekici olacaktır.\n-Ortaöğretim ve üzeri yaşlarda eğitimler verilmek suretiyle çevre bilincini oluşturmak mümkündür."),
      InfoCardItem("ff_info_6_1","Geniş Anlatım", "-Çevre Eğitiminin temeli Tiflis Konferansı'nda atılmıştır.\n-Bu kapsamda daha geniş hedef, amaç ve esasların anlatımları ilerleyen bilgi kartlarında tekrar gelecektir. Bunun için 'Çevre Eğitiminin Temelleri' konu başlıklarına göz atabilirsiniz."),

    ]), InfoCardModel("Okul Kademelerinde Çevre Eğitimi", [
       InfoCardItem("ff_info_7", "Çevre bilinci", "-Doğal çevreye dikkat ederek, saygı duyarak ve olumlu tutum ve davranışlar geliştirerek faydalı davranışlarda bulunmaktır.\n-Çevreye karşı olumlu ve olumsuz tutum ve davranışlar sergilenebilir.\n-Olumsuz olan davranışların çevre bilinci sayesinde olumlu yöne dönüşmesi beklenir."),
      InfoCardItem("ff_info_8", "Çevre bilincine olumlu katkılar", "-Çevre bilinci çok küçük yaşlarda kazandırılmalıdır.\n-Okul öncesi çağlarda bu amaçlarla etkinlikler düzenlenmelidir.\n-Çocukların çevre ile etkileşimleri arttırılmalıdır.\n-Çevre ile etkileşimi çok olan bireylerin bilinci kazanmaları daha kolay olacaktır.\n-İlkokul ve ortaokul çağlarında materyal destekli eğitimler verilmeli, geziler düzenlenmelidir."),
      InfoCardItem("ff_info_9", "Farkındalık örnekleri", "-Yerdeki çöplerden rahatsız olan bireyler,\n-Çöp atma davranışına karşı duruş sergileyen bireyler,\n-Yaşadığı çevreyi koruma konusunda hassasiyet gösteren bireyler,\n-Ülkenin ve dünyanın çevresel sorunlarına karşı olumlu tutum sergileyebilen bireyler bu alanda farkındalık sahibi bireyler olarak gösterilebilir."),
      InfoCardItem("ff_info_10", "Okulda eğitim-1", "-Çevre eğitimi okulda verilirken öğrencilerde davranış değişikliklerinin gerçekleştirilmesi amaçlanmalıdır.\n-Öğrencilerin bilgi düzeyleri arttırılmalıdır.\n-Bilgi düzeyi arttırılan öğrencilerin gerekli tutum ve becerileri göstermeleri beklenmelidir.\n-Beklenen tutum ve becerileri kazandığına inanılan öğrenciler, diğer öğrencileri teşvik etmek amacıyla ödüllendirilmelidir."),
      InfoCardItem("ff_info_11", "Okulda eğitim-2", "-Öğrencilerin gerekli bilince sahip olabilmesi ancak bu alanda doğru yaklaşımlar kullanılarak eğitilmeleriyle mümkündür.\n-Bu sebeple Milli Eğitimin Temel Amaçları göz önünde bulundurularak eğitim planları gerçekleştirilmelidir.\n-Tüm öğrencilerin sürece aktif katılımları sağlanmalıdır.\n-Öğrencilerin ilgilerini canlı tutmak amacıyla süreç yarışma ve ödüllendirmeler ile desteklenmelidir."),
      InfoCardItem("ff_info_12", "Yaş gruplarına göre eğitim", "Çevre eğitimi yaş gruplarına göre;\n-Okul öncesi dönem,\n-İlköğretim dönemi\n-Ortaokul dönemi\n-Ortaöğretim dönemi\n-Yükseköğretim dönemi şeklinde ayrılır."),
      InfoCardItem("ff_info_13", "Okul öncesi dönem", "-Çevre eğitiminin başlaması gereken yaş grubudur.\n-Öğrenmeye açık, meraklı ve istekli bireylerle çalışılır.\n-Çevreyi tanıma etkinlikleri yapılmalıdır.\n-Bitkilere, hayvanlara ve yeni keşiflere açık olan yaş gurubuna ayrıca çevreyi koruma etkinlikleri yapılmalıdır."),
      InfoCardItem("ff_info_14", "İlkokul dönemi", "-Okul öncesi dönemden çevreyi tanıyan ve çevreyi korumayı öğrenmiş bireyler ile program işlenir.\n-Bu bireylerin temel düzeyde bilgiler ile daha geniş çerçevede yeterlilik sahibi olmaları sağlanır.\n-Sınıf etkinlikleri, geziler ve okul etkinlikleri ile çevre bilincinin arttırılması hedeflenir."),
      InfoCardItem("ff_info_15", "Ortaokul dönemi", "-Bu yaş düzeyine gelen bireylerin varolan bilgileri analiz etmeleri ve yeni öğrenmelerini ortaya çıkartmaları beklenir.\n-Çevreye karşı olumlu tutum ve davranışlar geliştirmiş olamaları gerekmektedir.\n-Çevre bilinci ile yaşanan olaylara yorum getirebilir ve iyi yönde gelişmeler için fikirler üretebilirler."),
      InfoCardItem("ff_info_16", "Ortaöğretim dönemi", "-Çevre bilinci oluşmuş, beklenen tutum ve davranışları gösteren bireyler yetişmiştir.\n-Okul dersleri ile varolan öğrenmeleri desteklenerek geliştirilir."),
      InfoCardItem("ff_info_17", "Yükseköğretim dönemi", "-Alanda uzmanlaşma dönemidir.\n-Çevre bilimleri ile ilgili bölümlerde öğrenciler eğitim alabilir.\n-Bilimsel araştırmalar yapılır.\n-Alt yaş gruplarına ilişkin çalışmalar düzenlenir.\n-Sadece yaşadığı çevreye ilişkin değil daha genel çerçevede fikir üretmesi beklenir."),

    ]),InfoCardModel("Çevre Kirliliği-1", [
      InfoCardItem("ff_info_49", "Doğal dengelerin bozulması-1", "-İnsanoğlunun doğayı kontrol altına almaya başlaması ateşin bulunmasına kadar dayanmaktadır.\n-Gelişen uygarlıklar, hızlı sanayileşme hem doğadaki insan kontrolünü arttırmış hem de insan kaynaklı zararların doğada görünmesini arttırmıştır.\n-Zararların büyümesi ile birlikte doğal dengeler bozulmaya başlamıştır.\n-Bu başta insan olmak üzere tüm canlıları olumsuz olarak etkilemiştir."),
      InfoCardItem("ff_info_50", "Doğal dengelerin bozulması-2", "-Sanayileşmenin ve makineleşmenin artması enerji ihtiyaçlarını arttırmıştır.\n-Uzun yıllar boyunca alternatif ve doğal enerji kaynakları kullanmak yerine, günün sonunda doğaya zarar verecek enerji kaynakları kullanılmıştır.\n-Bu durum doğal dengenin bozulmasını hızlandıran bir faktör olmuştur."),
      InfoCardItem("ff_info_51", "Çevre Kirliliği", "-Genel bir kavram olan çevre kirliliği özelde 3 temel unsurun kirlenmesi ile ilgilenir.\nBunlar;\n-Toprak,\n-Hava\n-Sudur."),
      InfoCardItem("ff_info_52", "Toprak Kirliliği-1", "-Toprağın tehlikeli kimyasallar içermesi durumudur.\n-Temel besin kaynaklarımızın besleyicisi olan toprağın kirlenmesi tüm yaşantıyı olumsuz etkilemektedir.\n-Toprağın kirlenmesi yer üstü kaynaklarını tehdit ettiği kadar yer altı kaynaklarını da tehdit eder.\n-Toprak kirliliğini oluşturan bileşenlerde organik ve inorganik bileşenler etkilidir."),
      InfoCardItem("ff_info_53", "Toprak Kirliliği-2", "-Toprak kirliliğinin temel unsurlarından birisi yanlış tarımdır.\n-Tarım ürünlerinin gelişimi için kullanılan kimyasal maddeler ürünlerin orantısız gelişmesine sebep olmakla kalmayıp toprağın kirlenmesine de sebep olur.\n-Toprağın kirlenmesi, topraktan beslenen bitki ve hayvanlar başta olmak üzere tüm çevreye olumsuz etki etmektedir."),
      InfoCardItem("ff_info_54", "Toprak Kirliliği-3", "-Kirlenen toprağın temizlenmesi için farklı çalışmalar yürütülmektedir.\n-Bu çalışmalar yerinde yürütüldüğü gibi toprağın taşınması yöntemi ile de gerçekleştirilebilir.\n-Bu yöntemlerin hiçbirisi toprağı gerçek anlamda temizlememektedir.\n-Toprağın temizlenmesinde kullanılan bir diğer yöntem de toprağın yakılmasıdır.\n-Bu yöntem de hava kirliliğine sebep olmaktadır."),
      InfoCardItem("ff_info_55", "Hava Kirliliği-1", "-Temiz bir havada yaklaşık %78 oranında azot, %21 oranında oksijen ve kalan %1 oranında diğer gazlardan bulunur.\n-Kalan %1'lik oranda toz ve su buharı da bulunmaktadır.\n-Hava kirliliği olması gereken bu oranların bozularak farklı kimyasal ve doğaya zararlı gazlar ile gerçekleşmektedir.\n-Hava kirliliği insan sağlığına, doğadaki canlılara ve tüm ekolojik dengeye olumsuz etki etmektedir."),
      InfoCardItem("ff_info_56", "Hava Kirliliği-2", "-Hava kirliliği başta insan olmak üzere tüm canlıları olumsuz olarak etkilemektedir.\n-Bu nedenle yerel ve küresel birçok zarar gözlemlenmektedir.\n-Ozon tabakasında oluşan zararlar, asit yağmurlarının görülme sıklığının artması, akciğer hastalıklarındaki artış, özellikle çocuklarda görülen astım hastalığındaki artış hava kirliliğinin görünen zararlarındandır."),
      InfoCardItem("ff_info_57", "Su Kirliliği-1", "-Herhangi bir sebeple suyun kalitesindeki düşmeye su kirliliği denir.\n-Su içerisindeki zararlı organizmaların artışı ile gözlemlenir.\n-Su kirliliği, biyolojik maddeler, kimyasal maddeler, metal, zararlı elementler, endüstriyel, tarımsal ve evsel atıklar gibi nedenlerle ortaya çıkabilir.\n-"),
      InfoCardItem("ff_info_58", "Su Kirliliği-2", "-İçme suları genellikle doğal veya yapay göl veya nehirlerden karşılanmaktadır.\n-Su artıma sistemlerinin yeterli olmadığı durumlarda, hala dünyada birçok insan çeşitli hastalıklara yakalanmaktadır.\n-Arıtma sistemleri için fiziksel, kimyasal, biyolojik ve ileri arıtma yöntemleri kullanılmaktadır."),
      InfoCardItem("ff_info_59", "Su Kirliliği-3", "-Su kirliliği sebebiyle birçok farklı alan zarar görmektedir.\n\nBunlar;\n-Temiz suya erişimi olmayan yüz binlerce insan her yıl çeşitli hastalıklara yakalanmaktadır.\n-Sulardaki canlıların ölümlerine sebep olmaktadır.\n-Hastalıkların tedavisi, suların temizlenmesi ve çevreye verilen zararların giderilmesi için ekonomik harcamalar yapılmaktadır."),
    ]),
    InfoCardModel("Çevre Kirliliği-2", [
      InfoCardItem("ff_info_18", "Çevre Kirliliği Sebepleri", "Çevre Kirliliği insan faaliyetleri sonucu ya da doğal sebeplerle gerçekleşir."),
      InfoCardItem("ff_info_19", "İnsan Faaliyetleri", "-Endüstriyel ve Evsel Atıklar|\n-Hızlı Nüfus Artışı ve Plansız Şehirleşme|\n-Fosil Yakıtların Aşırı Kullanımı|\n-Orman Yangınları ve Ağaçların Kesilmesi\n-Tarım İlaçlarının Aşırı Kullanımı\n-Nükleer ve Radyoaktif Atıklar"),
      InfoCardItem("ff_info_20", "Doğal Sebepler", "-Depremler\n-Seller\n-Volkanik Patlamalar"),
      InfoCardItem("ff_info_21", "Madde Döngüleri-1", "-Bir ekosistemin kendisini koruyup, varlığını sürdürebilmesi için tüketilen maddelerin (organik, inorganik) ekosisteme geri dönmesi gerekir.\n-Ekosistemdeki canlılığın devamı için organik ve inorganik maddelerin kullanıldığı kadarının üretilmesi gereklidir.\n-Maddelerin ekosistemdeki üretim-tüketim dolaşım süreçlerine madde döngüsü adı verilir."),
      InfoCardItem("ff_info_22", "Madde Döngüleri-2", "Temel madde döngüleri şunlardır\n-Karbon Döngüsü\n-Oksijen Döngüsü\n-Azot Döngüsü\n-Su Döngüsü\n-Azot Döngüsü\n-Fosfor Döngüsü\n-Kükürt Döngüsü "),
      InfoCardItem("ff_info_23", "Ekolojik Ayak İzi", "İnsanların ekosistemler üzerindeki yükünü ve sürdürülebilirlik seviyelerini ölçmek için ekolojik ayak izi yöntemi kullanılır. En kısa tanımıyla ekolojik ayak izi insanın doğaya olan yükünü hesaplamak için kullanılır.\n-Ekolojik ayak izi hesabı kaynakların nasıl kullanılması gerektiği konusunda insanlığa rehberlik yapmaktadır.\n-Okullarda öğretilecek ekolojik ayak izi kavramı ile öğretmenlerin ve öğrencilerinin, çevre sorunları farkındalığı, tutum ve davranışlarında olumlu etkiler olacaktır."),
      InfoCardItem("ff_info_24", "Ekolojik Ayak İzinin Temel Bileşenleri", "-Dünya Doğayı Koruma Vakfı (WWF) ekolojik ayak izi hesaplamalarını temel 6 başlık altında incelenmektedir. Bunlar;\n\n-Otlak Alanı Ayak İzi\n-Orman Alanı Ayak İzi\n-Balıkçılık Sahası Ayak İzi\n-Tarım Arazisi Ayak İzi\n-Yapılaşmış Alan Ayak İzi\n-Karbon Ayak İzi’dir."),

    ]),
    InfoCardModel("Çevre Eğitiminin Temelleri-1 (Yeni)", [
      InfoCardItem("ff_info_25", "Giriş", "-Günümüzdeki çevre sorunlarının sebebi, bozulan doğal dengedir.\n-Bu durumun ortaya çıkmasında farklı sebepler bulunmaktadır.\n\nBunlar\n-Üretim-tüketim dengesinin sağlanamaması,\n-Kaynakların sınırsız algılanması,\n-Üretim-tüketim faaliyetleri sonucu oluşan doğal dengedeki bozulmalar gösterilebilir."),
      InfoCardItem("ff_info_26", "Eğitimin Önemi", "-Doğanın dengesinin korunabilmesi için sürdürülebilir kalkınma programlarına ihtiyaç vardır.\n-Bu kalkınma süreci tek bir ülkeyi ilgilendiren bir süreç değildir.\n-Dünyadaki tüm ülkelerin çevre bilincine sahip bireyler yetiştirerek bu kalkınmaya katkı sağlaması gerekmektedir.\n-Çevre bilincinin aşılanmasında eğitimin rolü çok büyüktür.\n-Bu eğitimin okullarda küçük yaşlardan itibaren verilmesi toplumların kalkınmasında önemli rol oynayacaktır."),
      InfoCardItem("ff_info_27", "Tarihsel Bakış", "-Çevre eğitimi konuşulmaya başlandıktan sonra ilk kez 1970 yılında düzenlenen Dünya Günü'nde planlanmıştır.\n-Çevrenin korunması için, uluslaararası düzeyde, geniş çerçevede sergilenen ilk tutum Birleşmiş Milletler'e aittir.\n-Birleşmiş Milletler, çevre ile ilgili 'İnsan Çevresi' isimli ilk toplantısını 1972 yılında Stockholm'de gerçekleştirmiştir.\n-5 Haziran tarihinde başlayan toplantı, her yıl Dünya Çevre Günü olarak kutlanmaktadır. "),
      InfoCardItem("ff_info_28", "Dünya Günü (1970)", "-Dünya Günü'nün yapılmasının sebebi 1968'de ABD Santa Barbara kıyısına 12 milyon litre petrol dökülmesidir.\n-22 Nisan 1970'te yapılmıştır.\n-John McConnell'in önerisi ve Denis Hayes'in organizatörlüğünde gerçekleştirilmiştir.\n-Amerika Birleşik Devletleri'nde gerçekleştirilen organizasyona 20 milyondan fazla kişi katıldı.\n-Bu etkinlik sonrasında, Temiz Hava Yasası ve Temiz Su Yasası hazırlandı.\n-1990 yılından itibaren tüm dünyada kutlanan uluslararası bir organizasyon haline geldi."),
      InfoCardItem("ff_info_29", "UNEP-1", "-Birleşmiş Milletler Çevre Programı'dır.\n\nProgramın amaçları;\n-Birleşmiş Milletler bünyesinde, çevresel eşgüdümü sağlamak,\n-Çevresel sorunların sürekli gözden geçirilmesini sağlamak,\n-Çevresel sorunlara uluslararası toplumun dikkatini çekmek,\n-Ulusal çevre politika ve hukukunun gelişimine katkı sağlamaktır."),
      InfoCardItem("ff_info_29_11", "UNEP-2", "-Türkiye, UNEP programının üyesi değildir.\n-UNEP'e ilave olarak Uluslararası Çevre Eğitimi Programı (IEEP) başlatılmıştır.\n-IEEP'nin çalışmalarına 1975 yılında başlanmıştır.\n-IEEP'nin düzenlediği bölgesel konferans ve seminerlerin devamında Tiflis Konferansı toplanmıştır.\n-Bu konferans, 1977 yılında bakanlar seviyesinde gerçekleştirilmiştir."),
      ]),
    InfoCardModel("Çevre Eğitiminin Temelleri-2 (Yeni)", [
      InfoCardItem("ff_info_30", "Tiflis Konferansı", "-UNESCO-UNEP işbirliği ile gerçekleştirilmiştir.\n-1977 yılında toplanmıştır.\n-Çevre eğitiminin, eğitim sistemlerinde yer almasını sağlamıştır.\n-Öğretmen ve uzmanların eğitim olanaklarını kullanarak çevre eğitimi vermeleri gerektiği ifade edilmiştir.\n-Eğitim yetkililerinin, çevre eğitimi alanında araştırma, düşünce geliştirme ve yenilikler üretmesi gerektiğini ifade eder.\n-Tiflis Bildirgesi'ne göre Çevre Eğitiminin hedef, amaç ve esasları için kartları okumaya devam edin."),
      InfoCardItem("ff_info_31", "Çevre Eğitiminin Hedefleri", "-Kentsel ve kırsal kesimlerdeki olayların çevresel olaylarla etkileşimi hakkında farkındalık oluşturulmasını sağlamak,\n-Çevrenin korunması ve iyileştirilmesi için bireylerin gerekli donanıma sahip olmalarını sağlamak,\n-Toplumda ve bireylerde, çevreye dair yeni ve doğru davranış biçimleri oluşturmak şeklinde sıralanabilir."),
      InfoCardItem("ff_info_32", "Çevre Eğitiminin Amaçları", "Tiflis Bildirgesi'ne göre Çevre Eğitiminin amaçları 5 başlıkta toplanabilir. Bunlar\n-Bilinç,\n-Bilgi,\n-Tutum,\n-Beceri,\n-Katılım olarak sıralanabilir."),
      InfoCardItem("ff_info_33", "Bilinç", "-Birey ve toplumların, çevre, çevresel sorunlar, çevre gelişimi, çevre duyarlılığı ve çevreye karşı kazanılması gereken yeni bakış açıları ile ilgili yeterli bilince ve duyarlılığa sahip olmalarını sağlamaktır.\n-Bu bilince ve duyarlılığa sahip bireyler, temel bilgi seviyelerini arttırmak için yüksek hazır bulunuşluk düzeyine sahip hale gelir."),
      InfoCardItem("ff_info_34", "Bilgi", "-Birey ve toplumların, çevre ile ilgili temel bilgi ve deneyimlerinin arttırılmasını sağlamaktır.\n-Bireyler, çevre ile ilgili konularda bilgi düzeylerini arttırırsa bilinç düzeyleri artacak ve bu durum tutumlarına yansıyacaktır.\n-Bu sayede daha yaşanılır bir çevreye ulaşmak mümkün olacaktır."),
      InfoCardItem("ff_info_35", "Tutum", "-Bireylerin ve toplumların çevresel olaylar için belirli değer yargılarını ve duyarlılıklarını, çevreyi koruma ve iyileştirme yönünde etkin katılım isteğini kazanmalarını sağlamaktır.\n-Bilgi ve bilinç düzeyinde çevre eğitimini tamamlamış bireylerin ve toplumların tutumlarında olumlu gelişmelerin gözlemlenmesi beklenir."),
      InfoCardItem("ff_info_36", "Beceri", "-Bireylerin ve toplumların çevresel sorunları daha iyi tanımlamalarına ve çözümlemeler geliştirebilmeleri için beceri kazanmalarını sağlamaktır.\n-Bu beceriyi kazanan bireylerin çevresel sorunlara katkı sağlamaları beklenecektir."),
      InfoCardItem("ff_info_37", "Katılım", "-Bireylerin ve toplumların, çevre sorunlarına çözüm getirmek amacıyla yapılan çalışmalara, her seviyeden aktif olarak katılmalarını sağlamaktır.\n-Çevresel sorunlara çözüm üretmeye çalışan bireylerin, çevre için bir tehdit olması düşünülemez.\n-Bu sayede toplumda, çevreye tehdit unsuru bireyler değil, çevre için tehdit unsuru olan sorunlara çözüm üreten bireylerin varlığı desteklenmiş olur."),
    ]),
    InfoCardModel("Çevre Eğitiminin Temelleri-3 (Yeni)", [
      InfoCardItem("ff_info_38", "", "Önceki bölümde Tiflis Konferansı sonucunda yayınlanan Tiflis Bildirgesinin hedeflerini ve amaçlarını özetlemiştik. Bildirgenin esaslarını detaylıca incelemek için kartları okumaya devam edebilirsiniz."),
      InfoCardItem("ff_info_39", "Çevre Eğitiminin Esasları-1", "-Çevreyi tüm yönleri ile bir bütün olarak ele alır.\n-Eğitim, okul öncesi kademesinden başlayarak tüm hayat boyunca devam ettirilmelidir.\n-Diğer disiplinlerde varolan tüm ilgili kısımlar sürece dahil edilmeli ve disiplinler arası bir yaklaşımla yürütülmelidir.\n-Mevcut çevre şartları, yerel, ulusal, bölgesel ve uluslararası açılardan ele alınarak öğrencilerin öngörü sahibi olmaları sağlanmalıdır."),
      InfoCardItem("ff_info_40", "Çevre Eğitiminin Esasları-2", "-Mevcut ve potansiyel çevre şartları, tarihi ve kültürel boyutları ile ele alınmalıdır.\n-Çevre sorunlarına karşı alınacak önlemler ve geliştirilecek çözümlerde yerel, ulusal ve uluslararası işbirliğinin değerini ve gerekliliğini ön planda tutulmalıdır.\n-Çevre boyutu, kalkınma ve büyüme için yapılan planların tamamında göz önünde tutmalıdır."),
      InfoCardItem("ff_info_41", "Çevre Eğitiminin Esasları-3", "-Öğrenme yaşantılarının programlanmasında öğrenciler söz sahibi olmalıdır.\n-Öğrencilerin karar almaları sağlanmalı ve aldıkları kararların sonuçlarını değerlendirmeleri için fırsat tanınmalıdır.\n-Erken yaşlardan başlayarak kendi toplumlarına karşı çevre duyarlılığı olan bireyler yetiştirilmelidir.\n-Çevre bilgisi, çevresel problemleri çözme becerisi her yaş grubuna hitap etmelidir."),
      InfoCardItem("ff_info_42", "Çevre Eğitiminin Esasları-4", "-Çevre sorunlarını kendileri bulabilen öğrencilerin yetişmesine yardımcı olunmalıdır.\n-Çevre sorunlarının karmaşıklığına çözümler üretebilmek için eleştirel düşünce ve problem çözme becerilerinin gereğine vurgu yapılmalıdır.\n-Çevre ile ilgili öğrenmeleri sağlamak için değişik eğitim yaklaşımlarından ve öğrenme ortamlarından faydalanılmalıdır."),
      InfoCardItem("ff_info_43", "Tiflis Bildirgesi Çerçevesinde Özel Hedefler", "-Öğrencilerin, çevre ile ilgili doğru karar alabilmelerini desteklemek amacıyla ekoloji hakkında bilgilendirilmeleri hedeflenmiştir.\n-İnsanların çevreye dönük davranışlarında değişme olması hedeflenmiştir.\n-Araştırma, inceleme ve değerlendirme becerilerinin geliştirilmesiyle birlikte değer yargılarının biçimlendirilmesini hedefler.\n-Çevre sorunlarının çözümüne ilişkin katılımı hedefler."),
      InfoCardItem("ff_info_44", "Özel Hedeflerin Detaylandırılması","-Çevre Eğitiminin amaçlarının bilinç, bilgi, tutum, beceri ve katılım olduğundan önceki özetlerimizde bahsetmiştik.\n-Tiflis Bildirgesi'nin özel hedeflerinde, süreç sonunda öğrencilerde görülmesi beklenen davranışların amaçlar düzeyinde örneklendirilmesi için diğer kartlarımıza göz atınız."),
      InfoCardItem("ff_info_45", "Bilgi Düzeyinde Özel Hedefler", "-Ekolojik ilkeleri tanıma,\n-Çevre sorunlarının incelenmesi, değerlendirilmesi ve çözümlenmesinde bilimsel verilerden faydalanma,\n-Çevre sorunlarının analizini yaparken ekolojik kavram bilgilerini kullanabilme,\n-Temel ekolojik kavramları kullanabilme gibi hedefleri (I. seviye) bulunmaktadır."),
      InfoCardItem("ff_info_46", "Bilgi, Bilinç ve Tutum Düzeyinde Özel Hedefler", "-Birey davranışlarının çevre üzerindeki etkilerini anlayabilme ve başkalarına anlatabilmeli,\n-Çevre sorunları ile bu sorunların ortaya çıkardığı ekolojik sonuçları tanıyabilmeli,\n-İnceleme, araştırma ve değerlendirmenin gerekliliğini anlayabilmeli,\n-Farklı inanç ve değer yargılarının çevre konularındaki rolünü anlayabilmeli,\n-Çevre problemleri çözülürken sorumlu vatandaş girişimlerinin gereklerini anlayabilme hedefleri (II. seviye) bulunmaktadır."),
      InfoCardItem("ff_info_47", "Beceri Düzeyinde Özel Hedefler", "-Çevre sorunlarını tanıma, inceleme ve araştırma sonucunda toplanan verilerden sonuçlar çıkarabilme,\n-Çevre sorunlarına getirdiği çözümleri gösterebilme,\n-Çevre sorunlarına getirdiği çözümleri değerlendirebilme yetkinliğini gösterebilme,\n-Yeni sahip olduğu bilgiler ile değer yargılarını değiştirebilme,\n-Başarılı çevre projeleri ile ilgili analizlerini gösterebilme hedefleri (III. seviye) bulunmaktadır."),
      InfoCardItem("ff_info_48", "Katılım Düzeyinde Özel Hedefler", "-Çevre sorunlarının çözümünde girişim becerilerini kullanabilmeli,\n-Yurttaş girişimlerinde yeterlilik düzeylerini sergileyebilmeli,\n-Sürdürülebilir kalkınma senaryosu geliştirilirken yurttaş girişim becerilerini kullanabilme yetisini gösterebilme gibi hedefleri (IV. seviye) bulunmaktadır."),
           ]),
    ///ff_info_49 yukarıda çevre kirliliği 1 bölümüne eklendi
    InfoCardModel("İklim (Yeni)", [
      InfoCardItem("ff_info_60", "İklim", "-Yeryüzünde herhangi bir alanda yer alan hava olaylarının uzun süre devam etmesi ile gerçekleşen etkilerine İklim denir.\n-Geniş bir bölge içerisinde ve yıllarca değişmeyen ortalama hava koşulu olarak da tanımlanabilir.\n-İklim elde edilen sonuçtur.\n-Hava durumu ile karıştırılabilir.\n-Hava durumu kısa zaman döngüsünde atmosfer koşulu iken iklim uzun zaman aralığındaki hava koşullarının toplamı veya ortalaması olarak anlaşılmalıdır."),
      InfoCardItem("ff_info_61", "İklim Değişikliği-1", "-Bir bölge devam etmekte olan iklim koşullarının gözlemlenerek on yıl ve üzeri yıllar boyunca meydana gelen değişikliklerine denir.\n-Nedeni ne olursa olsun iklimde uzun süre boyunca yaşanan değişiklikler sonucunda iklimin ortalama durmlarının değişmesi olarak da tanımlanabilir.\n-İklim değişikliği volkanik patlamalar, dış zorlamalar, güneş değişiklikleri vb. sebeplerle ortaya çıkabilir."),
      InfoCardItem("ff_info_62", "İklim Değişikliği-2","-İklim değişikliği, uzun yılları kapsayan bir süreç olduğu için birçok farklı sebeple meydana gelmektedir.\n-Bu sebeplerin tespit edilmesi, üzerinde çalışmalar yapılması ve düzeltilmesi, küresel değişikliklere katkı sağlayacaktır.\n-Bu sebeple dünyada küresel iklim değişikliğinin sebeplerinin yapıldığı birçok araştırma yapılmakta ve yapılmaya devam edilmektedir.\n-Şimdi nedenlere göz atalım."),
      InfoCardItem("ff_info_63", "İklim Değişikliğinin Nedenleri-1", "İklim değişikliğinin nedenlerinden bazıları aşağıdaki gibi sıralanabilir;\n\n-Havadaki buharlaşma miktarı \n-Yağmur miktarındaki artış\n-Buzulların küçülmesi\n-Deniz su seviyesinin yükselmesi\n-Orman yangınlarının hızla artması\n\ndevamı diğer kartta..."),
      InfoCardItem("ff_info_64", "İklim Değişikliğinin Nedenleri-2", "-Doğa olaylarının daha fazla gözlenmesi.\n-İnsani nedenler,\n-Atmosfer yer alan sera gazı\n-Ozon tabakasında meydana gelen tahribatlar\n-Çevrenin bilinçsizce kullanımı"),
      InfoCardItem("ff_info_65", "İklim Değişikliğinin Çevresel Etkileri", "Buzulların erimesi\n-Canlı türlerinin yok olması\n-Nüfusu fazla olan bazı canlıların yok olma tehlikesi altına girmesi\n-Mevsimlerde gözlenen sıcaklık değişiklikleri\n-Su kaynaklı rahatsızlıklar\n-Doğal Afetlerin artışı ( Sel, Erozyon, vb.)"),
      InfoCardItem("ff_info_66", "İklim Değişikliği", "-Görüldüğü üzere iklim değişikliği küresel anlamda birçok olaydan etkilendiği gibi birçok olumsuz sonuçları da ortaya çıkartmaktadır.\n-Etkilerin en aza indirilebilmesi için küresel iklim değişikliğine sebep olan faktörlerin öncelikle düzeltilmesi şarttır.\n-Bu eğitimler dünya çapında farkındalık oluşturmak için ilkokul seviyelerine kadar indirgenmiştir."),
    ]),
    InfoCardModel("İnsan Sağlığı Üzerindeki Etkiler (Yeni)", [
        InfoCardItem("ff_info_67", "İklim Sistemindeki Değişimler-1", "-İklim sistemlerinin bozulması sanayi devrimi ile ortaya çıkan çevre sorunlarına kadar dayanmaktadır.\n-Gün geçtikçe iklimsel değişikliğin insan sağlığına etkileri daha fazla görülmektedir.\n-Bu etkilerin azaltılması için birçok ülke ulusal ve uluslararası düzeyde adaptasyon politikaları düzenlemektedir. "),
        InfoCardItem("ff_info_68", "İklim Sistemindeki Değişimler-2", "-Ülkelerin bu politikaların belirlenmesi ve uygulanmasında birlikte hareket etmeleri en önemli gerekliliklerdendir.\n-Politika gereği alınan kararların acilen fiiliyata dökülmesi gerekmektedir.\n-En önemli değişikliklerden birinin üretim politikalarında yapılması gerekmektedir.\n-Çünkü dünyada çevreye en çok zarar veren yapılar, üretim yapan yapılardır."),
        InfoCardItem("ff_info_69", "İnsan Sağlığına Etkileri", "-Küresel iklim değişikliğinin insan sağlığına etkileri iki ana başlıkta toplanabilir.\n-Bunlar\n\n-Doğrudan etkiler,\n-Dolaylı etkilerdir."),
        InfoCardItem("ff_info_70", "Doğrudan Etkiler-1", "-Sıcaklık değişiklikleri (Sıcak hava dalgarlarının kalp, beyin ve solunumsal ölümleri tetiklediği bilinmektedir. 2100 yılına kadar hava sıcaklığının 3 derece artması beklenmektedir. Uzmanlar buna bağlı olarak her yıl 86.000 kişinin daha fazla öleceğini öngörmektedir.)"),
        InfoCardItem("ff_info_71", "Doğrudan Etkiler-2", "-Sel, fırtına, yangın ve kuraklık gibi doğa kaynaklı yaralanma (Bu olaylar ekstrem hava olayları olarak tanımlanmaktadır. Tsunami felaketinin yaşandığı Sri Lanka'da sahildeki çocukların  çoğunluğunda stres bozukluğu ortaya çıkmıştır. Bu bize etkilerin yalnızca ölümlerle sınırlı kalmadığını ve etkilerinin yaşam boyu devam edeceğini göstermektedir.)"),
        InfoCardItem("ff_info_72", "Dolaylı Etkileri-1", "-Su Kaynaklarında meydana gelen sıkıntılar (İklim değişiklikleri ile yaşanan sorunlar sebebiyle su kaynaklarındaki azalma ciddi seviyelere ulaşmıştır. Bu olumsuz etki gün geçtikçe artmaktadır. Özellikle tarım öncelikli geçim kaynağına sahip ülkeler bu durumdan anında etkilenmektedir.)"),
        InfoCardItem("ff_info_73", "Dolaylı Etkileri-2", "-Bulaşıcı hastalıkların artışı (Dünya Sağlık Örgütü kuş gribi, ebola, veba, veremi kızıl humma gibi hastalıkların iklim değişikliklerinden etkileneceğini belirtmektedir. Birçok araştırma, enfeksiyona bağlı hastalıkların artış gösterme sebeplerini de iklim değişiklikleri olarak göstermektedir.)"),
        InfoCardItem("ff_info_74", "Dolaylı Etkileri-3", "-Tarım alanlarına olan etkileri,\n-Tarım alanları üzerine etkileri,\n-İshalli hastalıkların artışı,\n-Göçlerin artması,\n-Ozon seviyesindeki değişikliklerin hastalıklara sebep olması,\n-Çocuk gelişiminde yetersiz beslenmenin ortaya çıkması da diğer dolaylı etkiler olarak sıralanabilir."),
    ]),
    InfoCardModel("Sağlığa Etkilerin Azaltılması İçin Öneriler (Yeni)", [
        InfoCardItem("ff_info_75", "Ne Yapılmalı?", "-İklim değişikliklerinin topyekün ortadan kaldırılması bir anda gerçekleşebilecek bir süreç değildir.\n-Bu sebeple hem iklim değişikliklerinin önüne geçecek politikalar yürütülmeli hem de bu değişikliklerin etkilerini en aza indirmek için çalışmalar yapılmalıdır.\n-Şimdi etkileri en aza indirmek için neler yapılabilir göz atalım."),
        InfoCardItem("ff_info_76", "Öneriler-1", "-İklim değişikliği kapsamında araştırma ve geliştirme çalışmalarına destek verilmelidir.\n-Bilimsel altyapılar desteklenmeli ve her öğretim kademesinde çevre ve iklim konularında farkındalık oluşturulması sağlanmalıdır.\n-Yapılacak çalışmalar desteklenmeli ve sonuçlar iyi analiz edilerek politikalar geliştirilmelidir."),
        InfoCardItem("ff_info_77", "Öneriler-2", "-Bölgesel risk analizleri yapılarak olası değişikliklerden en fazla etkilenecek bölgeler tespit edilmelidir.\n-İklim değişikliklerine yapılan hazırlıklar arttırılmalıdır.\n-Ani gelişecek salgın hastalıkların ortaya çıkma ihtimaline karşılık tedavi amaçlı ilaçlar stoklanmalıdır.\n-Ani ortaya çıkabilecek sorunlara karşı acil eylem planları oluşturulmalıdır."),
        InfoCardItem("ff_info_78", "Öneriler-3", "-Teknolojik imkanlar kullanılarak (özellikle yapay zeka) erken uyarı sistemleri oluşturulmalı ve sonuçları yakından takip edilmelidir.\n-Oluşabilecek ani sorunlarda ortaya çıkabilecek bilgi kirliliğinin önlenmesi için haberleşme altyapısı desteklenmeli ve teknolojik imkanlar kullanılmalıdır."),
        InfoCardItem("ff_info_79", "Öneriler-4", "-Hastanedeki teknolojik donanımlar ve yatak kapasiteleri arttırılmalıdır.\n-Sağlık personeline ihtiyaçlar artabileceği için yeteri kadar personel desteği sağlanmış olmalıdır.\n-Mevcut sağlık personllerinin bilgilerini sürekli güncel tutmaları bilgilendirme faaliyetleri ile sağlanmalıdır.\n-Ülkelerin belirlemiş olduğu mevzuatlar gözden geçirilmelidir."),
        InfoCardItem("ff_info_80", "Öneriler-5", "-Ülkelerin yapacakları faaliyetlerle ilgili birbiri ile koordinasyonu sağlanmalıdır.\n-Yatırımların yapılması ve geliştirilmesi noktasında ülkeler paydaşları ile ortak hareket etmelidir.\n-Üretim ve tüketim sistemleri yeniden gözden geçirilerek revize edilmelidir. Çünkü iklim değişikliğinin temel sebeplerinden bir tanesi üretim ve tüketim sistemleridir."),

    ]),
InfoCardModel("İklim Değişikliğinin Sosyo-Ekonomik Etkileri (Yeni)", [
        InfoCardItem("ff_info_81", "Sorunun Sebebi-1", "-İklim değişikliği ve küresel ısınma çevresel sorun olmasının yanında tüm dünyayı etkileyecek bir kaos ortaya çıkartmaktadır.\n-Bunun sebepleri iklim değişikliklerinin yol açacağı sel, kuraklık gibi doğal afetlerin yanında tarım verimliliğinin azalması ve çevre kirliliği ile artan hastalıklar olarak sayılabilir.\n-Ortaya çıkan her sorun sosyal ve ekonomik hayata olumsuz olarak yansır."),
        InfoCardItem("ff_info_82", "Sorunun Sebebi-2", "-Konuyu örnekler üzerinde detaylandırmadan önce genel çerçeve çizmeye devam edelim.\n-İklim değişikliği ile devletlerin ithalat ve ihracat dengeleri değişecektir.\n-Bu noktada devletler doğru politikalar yürütmezse toplum refah düzeyleri direkt olarak etkilencektir.\n-Bu dengeler içerideki üretimlerin ve üretimlere ait pazarların durumlarında da değişkenlik göstereceği için üreticileri yani çalışanları olumsuz etkileyebilir."),
        InfoCardItem("ff_info_83", "Olumsuz Etkiler", "-İklim değişikliğinin sosyo ekonomik etkileri sektörel, emek verimliliği ve istihdam üzerine gerçekleşebilir.\n-Sektörel etkiler;\n-Tarım,\n-Turizm,\n-Enerji üzerine olabilir."),
        InfoCardItem("ff_info_84", "Tarıma Etkileri-1", "-Tarımsal üretim direkt iklime bağlıdır.\n-Hava koşullarındaki ani değişimler, iklimlerin değişmesi tarım ürünlerinin üretimi ve verimi noktasında olumsuz sonuçlar ortaya çıkartır.\n-Sıcaklık, yağış, atmosferdeki gazların dengesi ve deniz suyu hareketleri tarım için önemlidir.\n-Aşırı kuraklık ve bölgenin normalden çok daha fazla yağış alması, bölgede üretilen mahsülün o yıl alınamamasına sebep olur.\n-Mahsül fiyatları aşırı yükselir."),
        InfoCardItem("ff_info_85", "Tarıma Etkileri-2", "-İklim değişikliğinin tarıma etkileri sadece bunlarla sınırlı değildir.\n-Tarım, topraktaki ve havadaki değişimler sebebiyle etkilenir.\n-Aynı değişimler meralardaki otlatma verimlerini de düşürür.\n-Meraların veriminin düşürülmesi hayvancılık faaliyetlerine de olumsuz etki yapar.\n-Hayvanların yem ile beslenmek zorunda kalması maliyetleri arttırır ve bu durum et ürünlerinin market fiyatlarına kadar yansır."),
        InfoCardItem("ff_info_86", "Tarıma Etkileri-3", "-Yaşanacak sıcaklık artışları, yağış verimlerini de olumsuz yönde etkiler.\n-Yağış veriminin düşmesi tarımsal alanlardaki sulama ihtiyacını arttıracaktır.\n-Ülkemizde son yıllarda yapılan barajların sayısının fazla olması sulama maliyetlerini düşürse de küresel bazda yaşanacak yağış değişimlerinden etkilenmememiz mümkün değildir.\n-Ayrıca kuraklık erozyonlara ve ani ve şiddetli yağışlarla sel felaketlerine sebep olur."),
        InfoCardItem("ff_info_87", "Tarıma Etkileri-4", "-Tarımsal üretimdeki azalmalar, işlenmiş gıda maliyetlerini de arttırarak fiyatların yükselmesine sebep olur.\n-Market ürünlerinin çoğunluğunun işlenmiş gıdalarda oluşması ani fiyat değişimleri sebebiyle vatandaşın alım gücünü düşürecek bir unsur olarak karşımıza çıkar.\n-Ülkemizin de tarımsal üretiminin fazla olması sebebiyle olası kötü senaryolardan etkilenmemesi için iklim değişikliği politikaları önem arz etmektedir."),
        InfoCardItem("ff_info_88", "Turizme Etkileri-1", "-Turizm sektörü de iklim değişikliklerinden etkilenecektir.\n-Faaliyet itibariyle turizm için temiz çevre ve elverişli hava koşullarının olması önemlidir.\n-Tatil beldelerinde yaşanacak sel, yangın gibi durumlar turizmin birkaç yıl boyunca bölgede olumsuz etkilenmesine sebep olacaktır."),
        InfoCardItem("ff_info_89", "Turizme Etkileri-2", "-Doğa turizmi de direkt olarak iklim değişikliklerinden etkilenecektir.\n-Örneğin kış turizm faaliyetlerinin fazla olduğu Uludağ'ı ele alalım.\n-Yıllık kar miktarının azalması kayakçılık gibi faaliyetlerin geç başlamasına, azalmasına veya erken bitirilmesine sebep olacaktır.\n-Bu da ekonomik olarak olumsuz etkiler ortaya çıkartacaktır."),
        InfoCardItem("ff_info_90", "Enerjiye Etkileri-1", "-Ülkeler, gelişen teknolojiler ve çevre kirlilikleri sebebiyle alternatif enerji kaynaklarına yönelmektedir.\n-Elektirik üretiminde barajların kullanılması buna bir örnektir.\n-İklim değişikliği ile yağış veriminin düşmesi barajların elektirik üretim kapasitelerini düşürecektir.\n-Bu sebeple enerji üretimi ve dağıtımında sorunlar ortaya çıkacaktır."),
        InfoCardItem("ff_info_91", "Enerjiye Etkileri-2", "-Sahil kesimlerinde kurulan enerji tesisleri deniz seviyesinin yükselmesi sebebiyle ve artan fırtına vb. durumlar sebebiyle maddi zararlarla karşılaşmaktadır.\n-Bu durum, yıllık enerji üretim kapasitelerini düşürürken şirketlere ek mali yükler getirmektedir.\n-Bu sebeple de birim enerji fiyatlarının etkilenmesi söz konusudur."),
        InfoCardItem("ff_info_92", "Enerjiye Etkileri-3", "-Nükleer enerji santralleri soğutma işlemlerinde çok fazla su kullanmaktadır.\n-Kuraklık sebebiyle azalan su miktarların, bu enerji faaliyetlerinde aksamalara sebep olacaktır.\n-Mekan ısıtma ve soğutma dengeleri iklim değişikliği ile değişeceği için mevcut maliyet hesaplamalarına ek masrafların çıkma olasılığı artacaktır.\n-Bu noktada, risk analizlerinin iyi yapılmaması ekonomik yönetimi zorlaştıracaktır."),
        InfoCardItem("ff_info_93", "Emek ve İstihdam", "-İklim değişikliği ile etkilenecek sektörler, mali dengelerini kurmak için işçi çıkarmak durumunda kalacaktır.\n-Geçinmek için çalışmak zorunda olan insanoğlu ya fazla emek ile az ücret karşılığı çalışacak veya işten çıkarmalar artacağı için istihdam sorunu yaşayacaktır.\n-Dolayısıyla toplumların sosyo-ekonomik durumları fazlasıyla etkilenecektir."),
        InfoCardItem("ff_info_94", "Sonuç", "-İklim değişikliğinin sosyo-ekonomik hayatta sebep olabileceği olumsuz senaryolardan bahsettik.\n-Bu senaryolar gerçekleşmeden önce gerekli tedbirlerin alınması önem arz etmektedir.\n-İklim değişikliklerin önüne geçmek için toplumsal bilinç en önemli güçtür."),
           ]),
InfoCardModel("Kyoto Protokolü (Yeni)", [
        InfoCardItem("ff_info_95", "Kyoto Protokolü", "-1997 yılında imzalanmıştır.\n-2005 yılında yürürlüğe girmiştir.\n-Bunun sebebi, onaylayan ülkelerin 1990 yılındaki emisyonlarının yeryüzündeki toplam emisyonun %55'ini bulma gerekliliğiydi.\n-Dünya üzerinde gözlenen iklimsel değişiklik ve küresel ısınmaya karşı mücadele sağlamak amacıyla Birleşmiş Milletler İklim Değişikliği Çerçeve Sözleşmesi içinde uluslararası alanda imzalanmış olan bir anlaşmadır."),
        InfoCardItem("ff_info_96", "Kyoto Protokolünün Prensipleri", "-Devletler tarafından desteklenir.\n-Birleşmiş Milletler'in öncülüğünde küresel kurallar belirlenir.\n-Devletler, gelişmiş ülkeler ve gelişmekte olan ülkeler olarak ikiye ayrılmıştır.\n-Gelişmiş ülkeler, gelişmekte olan ülkelerin masraflarını ödemekle yükümlüdürler.\n-Protokol kapsamında her yıl sera gazı envanteri raporu verilmektedir.\n-Bu raporlara göre sera gazı salımlarını yıllara göre azaltma hedefleri verilir ve ülkeler buna bağlı kalır."),
        InfoCardItem("ff_info_97", "Amaç", "-Protokolün amacı, atmosferdeki sera gazı yoğunluğunun, iklime tehlikeli etki yapmayacak seviyelerde dengede kalmasını sağlamaktır.\n-Kyoto Protokolü'nün amaçlarına ulaşması durumunda sıcaklık artışlarının azalması beklenmektedir."),
        InfoCardItem("ff_info_98", "Sözleşme Koşulları-1", "-Atmosfere salınan sera gazının miktarı %5'e indirilecektir.\n-Sanayi, araç ve ısıtmadan kaynaklı sera gazı miktarı azaltılacaktır.\n-Enerji tüketimi ve ısınması az olan araçların ulaşıma kazandırılmasına çalışılacaktır.\n-Ulaşımda ve çöp depolamada çevrecilik temel ilke olarak kabul edilecektir.\n-Metan gazı ve karbon dioksit oranının düşürülmesi amacıyla alternatif enerji kaynaklarına yönelinecektir."),
        InfoCardItem("ff_info_99", "Sözleşme Koşulları-2", "-Fosil yakıtların yerine alternatif kaynaklar kullanılacaktır.(Bio dizel)\n-Demir-çelik, çimento ve kireç fabrikalarının atık işlemleri yeniden düzenlenecektir.\n-Karbon salınımı az teknojiler özellikle termik santrallerde devreye sokulacaktır.\n-Güneş enerjisi ve nükleer enerjide karbon oranı sıfır olduğu için ön plana çıkartılacaktır.\n-Fazla yakıt tüketen ve fazla karbon üreten birimlerin vergileri arttırılacaktır."),
           ]),
            InfoCardModel("Diğer Sözleşme ve Protokoller (Yeni)", [
        InfoCardItem("ff_info_100", "Paris Anlaşması-1", "-5 Ekim 2016 itibariyle kabul edilip 4 Kasım 2016 yılında yürürlüğe girmiştir.\n-Ülkemiz ise 22 Nisan 2016 yılında New Yortk'da düzenlenen Yüksek Düzeyli İmza Töreni’nde 175 ülke temsilcisiyle birlikte imzalamıştır.\n-Anlaşmanın hedefi, sürdürülebilir kalkınma ve yoksulluğun ortadan kaldırılması bağlamında Birleşmiş Milletler İklim Değişikliği Çevre Sözleşmesi’nin uygulamasını geliştirmektir.  "),
        InfoCardItem("ff_info_101", "Paris Anlaşması-2", "-Paris Anlaşmasının uzun dönem hedefi, küresel ortalama sıcaklık artışının sanayi öcesi döneme göre 2 derecenin altında tutmaktır.\n-Buna ek olarak bu artışın 1.5 derece altta tutulması için de çaba sarf edilecektir.\n-Bu kapsamda her ülke kendi politikalarını belirlemeli ve uygulamaya koymalıdır.\n-Ayrıca yapılan her faaliyet raporlanmalıdır."),
        InfoCardItem("ff_info_102", "Viyana Sözleşmesi", "-Ozon tabakasının korunması için Mart 1985'te imzalanmıştır.\n-Ozon tabakasının sitematik olarak gözlemlenmesini ve bilgi paylaşımı noktasında hükümetler arası işbirliğinin sağlanmasını teşvik etmiştir.\n-Ozon tabakasının yapısını değiştiren her faaliyete karşı genel önlem alma görevi ülkelere verilmiştir.\n-Yasal bağlayıcılığı olan kontrolleri veya hedefleri bulunmamaktadır."),
        InfoCardItem("ff_info_103", "Montreal Protokolü-1", "-196 ülke taraf olmuştur.\n-1987 yılının Eylül ayında kabul edilmiştir.\n-Türkiye; protokole 19 Aralık 1991 yılında taraf olarak tüm değişiklikleri kabul etmiştir.\n-Ülkemiz Montreal Protokolünün uygulanmasında en başarılı ülkeler arasında yer almaktadır.\n-Montreal Protokolünün uygulamaları kapsamında 12 Kasım 2008 tarihinde Ozon Tabakasını İncelten Maddelerin Azaltılmasına İlişkin Yönetmelik yayımlanmıştır."),
        InfoCardItem("ff_info_104", "Montreal Protokolü-2", "-Protokol, ozon tabakasını incelten maddelere ilişkin kullanım düzenlemeleri içermektedir.\n-Kloroflorokarbon (CFC)’ların ve bazı halonların üretimini ve tüketimini azaltacak katı önlemler için ülkeler arasında işbirliği imzalanmıştır.\n-Bu azaltımların hızlandırılması için devamında birçok toplantı düzenlenmiştir.\n-Çevre konusunda oluşturulmuş en başarılı çok taraflı anlaşma olarak tanımlanmaktadır."),
        InfoCardItem("ff_info_105", "Türkiye'deki Yansımaları", "-Türkiye'de kloroflorokarbon (CFC) kullanımı 2006 itibarı ile sıfırlanmış ve zorunlu kullanım alanları dahil olmak üzere ithalatı yasaklanmıştır.\n-Tarım alanlarında yaygın olarak kullanılan geniş etkili bir pestisit olan metil bromür için alımlar Bakanlık tarafından yapılmaktadır.\n-Halon gazlarının ithalatı 2008 yılında yasaklanmıştır.\n-Ayrıca hidrokloroflorokarbon (HCFC) grubu gazlarının kullanımı ve ithalatları sınırlandırılmıştır."),
        InfoCardItem("ff_info_106", "İklim Değişikliği Paneli", "Birleşmiş Milletlerin iki örgütü “Dünya Meteoroloji Örgütü” ve “Birleşmiş Milletler Çevre Programı” tarafından 1988 yılında insan faaliyetlerinin neden olduğu iklim değişikliğinin risklerini değerlendirmek üzere kurulmuştur."),
                        ]),
    InfoCardModel("Sıfır Atık Projesi (Yeni)", [
      InfoCardItem("ff_info_108", "Hedef", "İsrafın önlenmesini, kaynakların daha verimli kullanılmasını, atık oluşum sebeplerinin gözden geçirilerek atık oluşumunun engellenmesi veya minimize edilmesi, atığın oluşması durumunda ise kaynağında ayrı toplanması ve geri kazanımının sağlanmasını kapsayan atık yönetim felsefesi olarak tanımlanan bir hedeftir."),
      InfoCardItem("ff_info_109", "Avantajları", "-Verimliliğin artması,\n-Temiz ortam kaynaklı olarak performansın artması,\n-İsrafın önüne geçildiğinden maliyetlerin azaltılması,\n-Çevresel risklerin azalmasının sağlanması,\n-Çevre koruma bilincinin oluşturulması,\n-Ulusal ve uluslararsı pazarlada kurumun 'Çevreci' sıfatına sahip olmasının sağlanması ve saygınlığının artması sayılabilir."),
      InfoCardItem("ff_info_110", "Gereken adımlar", "Sıfır Atık Sistemine dahil olabilmek için gereken adımlar aşağıdaki gibidir.\n\n-Odak noktalarının belirlenmesi,\n-Mevcut durumların tespit edilmesi,\n-Planlamanın yapılması,\n-İhtiyaçların belirlenmesi ve temin edilmesi,\n-Eğitim ve bilinçlendirme,\n-Uygulama\n-Raporlama"),
      InfoCardItem("ff_info_111", "Atık Türleri", "-Kağıt Atıklar,\n-Ahşap Atıklar,\n-Plastik Atıklar,\n-Cam Atıklar\n-Kompozit Atıklar,\n-Metal Atıklar,\n-Bitkisel Atık Yağ,\n-Organik Atık,\n-Elektronik Atık,\n-Atık Pil "),
      InfoCardItem("ff_info_112", "Kağıt Atıklar", "Kağıt ambalajlar, defterler, yazışma kağıtları, gazeteler, kese kağıtları, kitaplar, karton koliler vb bu kapsamda yer alır.\n-Kağıt atıkların çevreye atılması ve yakılması yanlıştır."),
      InfoCardItem("ff_info_113", "Ahşap Atıklar-Plastik Atıklar", "-Mobilya ve küçük ev eşyaları, palet ve kasalar, talaş, kırpıntı ve parçalar ahşap atık olarak geçer.\n\nPlastik Atıklar;\n-Pet şişeler, şişe kapakları, damacanalar, ambalajlar, naylon poşetler, plastik kutular, pet bardaklar vs. bu kapsamdadır.  "),
      InfoCardItem("ff_info_114", "Cam Atıklar-Kompozit Atıklar", "-İçecek şişeleri, konserve kavanozları, reçel kavanozları cam atıklar olarak geçer.\n\nKompozit Atıklar;\n-Hazır çorba ambalajları,\n-Karton süt ve meyve suyu kutuları,\n-Çikolata ambalajları kompozit atıklardandır."),
      InfoCardItem("ff_info_115", "Metal Atıklar-Bitkisel Atık Yağ", "-Aliminyum içecek kutuları, yağ ve salça tenekeleri, konserve kutuları metal atıklardandır.\n\nBitkisel Atık Yağ;\n-Kullanılmış kızartmalık yaplar ve son kullanma tarihi geçmiş katı ve sıvı yağlar bu kapsamda ele alınabilir."),
      InfoCardItem("ff_info_116", "Organik Atık-Elektronik Atık", "-Meyve ve sebze atıkları ile buğday, arpa ve çavdar samanı organik atık kapsamında yer alır.\n\nElektronik Atık;\n-Bilgisayar, telefon, tablet, beyaz eşyalar, tost makinesi ve elektrik süpürgesi bu kapsamda yer alır.\n\nAtık Pil;\n-Çinko piller, alkalin piller, lithium ion piller bu kapsamda yer alır."),
    ]),

   /* InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),*/
   /* InfoCardModel("", [


 InfoCardItem("ff_info_107", "", ""),


        InfoCardItem("ff_info_117", "", ""),
        InfoCardItem("ff_info_118", "", ""),
        InfoCardItem("ff_info_119", "", ""),
*/
  ];

  List<InfoCardModel> get cevreIklim => _cevreIklimList;}