import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class CevreIklimInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _cevreIklimList = [
    InfoCardModel("Çevre Eğitimi", [
      InfoCardItem("cevreiklim_info_1", "Nedir?", "-Tüm canlıların hayat boyu ilişkilerini sürdürdükleri ortamlardır.\n-Canlılar çevre içerisinde etkileşim halindedir.\n-Etkileşimler, biyolojik, sosyal, ekonomik ve fiziki olabilir."),
      InfoCardItem("cevreiklim_info_2", "Neden Önemli?", "-Hayatın sürdürülmesi için temel unsurdur.\n-Tüm kaynakların yer aldığı merkezdir.\n-Canlıların etkileşimlerine ev sahipliği yapar.\n-Ortak kullanım alanıdır.\n-Tüm canlılara hitap eder."),
      InfoCardItem("cevreiklim_info_3", "Çevre Eğitimi", "-Toplumun çevre konusunda bilinçlenmesidir.\n-Çevre eğitimi alan bireylerin, çevre konusunda olumlu tutum ve davranışlar sergilemesi beklenir.\n-Olumlu davranışların ve davranış değişikliklerinin kalıcı olması beklenir.\n-Bu davranışların kazanılması için çaba gerekir.\n-Çevresel sorunların çözülmesinde, eğitimle, bireyin aktif katılımı beklenir."),
      InfoCardItem("cevreiklim_info_4", "Çevre Eğitiminin Amaçları", "-Bireylerin çevreyi tanımalarını sağlamak.\n-Bireylere çevre bilinci kazandırmak.\n-Çevremizdeki varolan sorunların tespitinin yapılmasını sağlamak.\n-Ortaya çıkabilecek çevresel sorunların önceden tespitini sağlamak.\n-Çevresel sorunların çözümünde bireylerin aktif katılımlarını sağlamak.\n-Toplumda çevre bilincini yerleştirmek.\n-Yaşanılabilir çevre oluşturma sürecinde olumlu davranış değişiklikleri gerçekleştirmek"),
      InfoCardItem("cevreiklim_info_5", "Ne zaman başlar?", "-Çevre eğitiminin erken yaşlarda başlaması esastır.\n-Bu sebeple henüz okul öncesine devam etmekte olan bireylerin bu eğitimlerden faydalanması esastır.\n-Çevre eğitimi okul öncesi eğitim kurumlarının faaliyetleri arasında yer almaktadır.\n-Bireylerin erken yaşta gerekli bilinci ve tutumları kazanmaları ülkemizin ve dünyanın geleceği için önem arz etmektedir."),
      InfoCardItem("cevreiklim_info_6","Neler yapılabilir?", "-Çevre eğitimleri kapsamında erken dönemde başlayacak faaliyetlerde oyun ile öğrenme temel alınabilir.\n-Geri dönüşüm kutuları, çöp kutuları, atık kutuları gibi basit tasarımlar bu yaş grubuna tasarlatılabilir.\n-İlkokul ve ortaokul çağındak çocuklar için animasyonlar daha ilgi çekici olacaktır.\n-Ortaöğretim ve üzeri yaşlarda eğitimler verilmek suretiyle çevre bilincini oluşturmak mümkündür."),
      InfoCardItem("cevreiklim_info_7", "Çevre bilinci", "-Doğal çevreye dikkat ederek, saygı duyarak ve olumlu tutum ve davranışlar geliştirerek faydalı davranışlarda bulunmaktır."),
      InfoCardItem("cevreiklim_info_8", "", ""),
      InfoCardItem("cevreiklim_info_9", "", ""),
      InfoCardItem("cevreiklim_info_10", "", ""),
      InfoCardItem("cevreiklim_info_11", "", ""),
      InfoCardItem("cevreiklim_info_12", "", ""),
      InfoCardItem("cevreiklim_info_13", "", ""),
      InfoCardItem("cevreiklim_info_14", "", ""),
      InfoCardItem("cevreiklim_info_15", "", ""),
      InfoCardItem("cevreiklim_info_16", "", ""),
      InfoCardItem("cevreiklim_info_17", "", ""),
      InfoCardItem("cevreiklim_info_18", "", ""),
      InfoCardItem("cevreiklim_info_19", "", ""),
      InfoCardItem("cevreiklim_info_20", "", ""),
    ]),InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
   /* InfoCardModel("", [

      InfoCardItem("cevreiklim_info_21", "", ""),
      InfoCardItem("cevreiklim_info_22", "", ""),
      InfoCardItem("cevreiklim_info_23", "", ""),
      InfoCardItem("cevreiklim_info_24", "", ""),
      InfoCardItem("cevreiklim_info_25", "", ""),
      InfoCardItem("cevreiklim_info_26", "", ""),
      InfoCardItem("cevreiklim_info_27", "", ""),
      InfoCardItem("cevreiklim_info_28", "", ""),
      InfoCardItem("cevreiklim_info_29", "", ""),
      InfoCardItem("cevreiklim_info_30", "", ""),
      InfoCardItem("cevreiklim_info_31", "", ""),
      InfoCardItem("cevreiklim_info_32", "", ""),
      InfoCardItem("cevreiklim_info_33", "", ""),
      InfoCardItem("cevreiklim_info_34", "", ""),
      InfoCardItem("cevreiklim_info_35", "", ""),
      InfoCardItem("cevreiklim_info_36", "", ""),
      InfoCardItem("cevreiklim_info_37", "", ""),
      InfoCardItem("cevreiklim_info_38", "", ""),
      InfoCardItem("cevreiklim_info_39", "", ""),
      InfoCardItem("cevreiklim_info_40", "", ""),
      InfoCardItem("cevreiklim_info_41", "", ""),
      InfoCardItem("cevreiklim_info_42", "", ""),
      InfoCardItem("cevreiklim_info_43", "", ""),
      InfoCardItem("cevreiklim_info_44", "", ""),
      InfoCardItem("cevreiklim_info_45", "", ""),
      InfoCardItem("cevreiklim_info_46", "", ""),
      InfoCardItem("cevreiklim_info_47", "", ""),
      InfoCardItem("cevreiklim_info_48", "", ""),
      InfoCardItem("cevreiklim_info_49", "", ""),
      InfoCardItem("cevreiklim_info_50", "", ""),
      InfoCardItem("cevreiklim_info_51", "", ""),
      InfoCardItem("cevreiklim_info_52", "", ""),
      InfoCardItem("cevreiklim_info_53", "", ""),
      InfoCardItem("cevreiklim_info_54", "", ""),
      InfoCardItem("cevreiklim_info_55", "", ""),
      InfoCardItem("cevreiklim_info_56", "", ""),
      InfoCardItem("cevreiklim_info_57", "", ""),
      InfoCardItem("cevreiklim_info_58", "", ""),
      InfoCardItem("cevreiklim_info_59", "", ""),
      InfoCardItem("cevreiklim_info_60", "", ""),
      InfoCardItem("cevreiklim_info_61", "", ""),
      InfoCardItem("cevreiklim_info_62", "", ""),
      InfoCardItem("cevreiklim_info_63", "", ""),
      InfoCardItem("cevreiklim_info_64", "", ""),
      InfoCardItem("cevreiklim_info_65", "", ""),
      InfoCardItem("cevreiklim_info_66", "", ""),
      InfoCardItem("cevreiklim_info_67", "", ""),
      InfoCardItem("cevreiklim_info_68", "", ""),
      InfoCardItem("cevreiklim_info_69", "", ""),
      InfoCardItem("cevreiklim_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get cevreIklim => _cevreIklimList;}