import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class DijitalYetkinlikInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _dijitalYetkinlikList = [
    InfoCardModel("Temel Kavramlar", [
      InfoCardItem("dijitalyetkinlik_info_1", "Yetkinlik", "-Bilgi, beceri ve tutumların gerekli tüm davranışlar ile birlikte kullanılabilmesine denir.\n-Bir konuda yetkin olmak, o konuda bilgi verebilmeyi, yorum yapabilmeyi ve bilgiyi kullanarak yeni ve özgün fikirler ortaya çıkartabilmeyi gerektirir."),
      InfoCardItem("dijitalyetkinlik_info_2", "Dijital", "-Soyut olarak sanal ortamlarda varolan tüm doküman ve belgelere dijital denilmektedir.\n-Varolan bir belge veya doküman, elektronik araçlar kullanılarak dijitalleştirilebilir.\n-Örneğin kağıda yazılmış bir kompozisyon, Word programı ile bilgisayara yazıldığında dijitalleştirilmiş olur."),
      InfoCardItem("dijitalyetkinlik_info_3", "Dijital Yetkinlik", "-Bilginin araştırılma, ulaşılma ve elde edilen bilgi ile fikir yürütebilme süreçlerinde dijital cihazların kullanılmasına denir.\n-Ayrıca herhangi bir bilgiye ulaşma gayesi olmadan, sosyalleşmek, vakit geçirmek gibi gayeler ile de diijtal yetkinliğe sahip olunabilir.\n-Örneğin kişinin sosyal medyayı aktif kullanarak eğlenceli videolar izlemesi dijital yetkinlik kapsamında ele alınır."),
      InfoCardItem("dijitalyetkinlik_info_4", "Kapsamı", "-Dijital yetkinlik eğitim, öğretim, sosyal katılım, eğlence ve çalışma alanlarında yer alır.\n-Günümüzün gelişen teknolojileri ele alındığında dijital yetkinlik bireyin her yerde ihtiyaç duyduğu bir kazanım olarak karşımıza çıkmaktadır."),
      InfoCardItem("dijitalyetkinlik_info_5", "Dijital Yetkinlik Sahibi Bireylerin Özellikleri", "-Bilgiye sanal ortamdan ulaşabilir.\n-Bilgiyi sanal ortamda üretebilir.\n-Bilgileri işleyebilir.\n-Gerçek dünya ile sanal dünya arasındaki farklılıkları net bir şekilde ayırt edebilir.\n-İnternet teknolojilerine hakimdir.\n-Yeni çıkan teknolojilere ayak uydurmakta zorluk çekmez.\n-Doğru bilgiye ulaşabilme yeterliliğine sahiptir.\n-Yeni öğrenmelerinde topluluklara katılmaya ilgilidir."),
      InfoCardItem("dijitalyetkinlik_info_6", "Dijital Yetkinlik Sahibi Bireylerin Özellikleri", "-Dijital dünyanın gerektirdiği ilkeleri bilir ve buna uygun davranışlar sergileyebilir.\n-Varolan bilgilerini yeni öğrenmelerinde kullanabilir.\n-Dijital dünyadaki bilgilerin doğruluğunu teyit edebilir.\n-Çalışma alanını ilgilendiren konularda yeni öğrenmelerini dijital ortamlarda gerçekleştirebilir.\n-Eleştirel, yaratıcı ve yenilikçi düşünme yeterliliklerine sahiptir."),
      ///Bilişim Teknolojisi Araçları
      InfoCardItem("dijitalyetkinlik_info_7", "Bilgi", "-Bir konuda öğrenilen veya öğretilen şeye bilgi denir.\n-Öğrenme, araştırma veya gözlem yolu ile elde edilebilir.\n-Sosyal varlıkların birbirleri ile iletişimleri sonucunda da ortaya çıkabilir.\n-Yaşadığımız dünyayı yorumlamak ve yönetmek için bilgi kullanılır."),
      InfoCardItem("dijitalyetkinlik_info_8", "Teknoloji", "-İnsan hayatını kolaylaştıran yenilikçi araç ve gereçlerdir.\n-Teknoloji bilgi edinmenin yanı sıra bilgiyi üretmek için de kullanılabilir.\n-Aynı zamanda hizmet üretmek için de teknoloji kullanılır.\n-İnsan ihtiyaçlarının giderilmesini hedefler.\n-"),
      InfoCardItem("dijitalyetkinlik_info_9", "Teknolojinin Faydaları", "-İnsan hayatını kolaylaştırır.\n-Bir işe harcanan süreyi kısaltır.\n-Yaşam kalitesini yükseltir.\n-Kişisel gelişime olanak sağlar.\n-Bilgiye ulaşma yollarını kolaylaştırır."),
    ]),
    InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),

    //InfoCardItem("dijitalyetkinlik_info_10", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_11", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_12", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_13", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_14", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_15", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_16", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_17", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_18", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_19", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_20", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_21", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_22", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_23", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_24", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_25", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_26", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_27", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_28", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_29", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_30", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_31", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_32", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_33", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_34", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_35", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_36", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_37", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_38", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_39", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_40", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_41", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_42", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_43", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_44", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_45", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_46", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_47", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_48", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_49", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_50", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_51", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_52", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_53", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_54", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_55", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_56", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_57", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_58", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_59", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_60", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_61", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_62", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_63", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_64", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_65", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_66", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_67", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_68", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_69", "", ""),
    //InfoCardItem("dijitalyetkinlik_info_7", "", ""),
  ];

  List<InfoCardModel> get dijitalYetkinlik => _dijitalYetkinlikList;}