import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class EgitimArastirmaInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _egitimArastirmaList = [
    InfoCardModel("Eğitim Araştırmaları-1", [
    InfoCardItem("egitimarastirma_info_1", "Bilgi", "-Bir konuda öğrenilen veya öğretilen şeylere bilgi denir.\n-Zihinsel faaliyetler sonucunda elde edilmektedir."),
    InfoCardItem("egitimarastirma_info_2", "Bilim", "-Geçerliliği birçok kişi tarafından kabul edilmiş sistemli bilgilere denilmektedir.\n-Bilimde çeşitli yöntem ve deney yolları kullanılabilir.\n-Gerçekliğe dayandırılmalıdır."),
    InfoCardItem("egitimarastirma_info_3", "Araştırma", "-Açığa çıkartılmak istenen gerçeğin veya olgunun bilimsel yöntemlerle ortaya konmasına denir.\n-Araştırmanın ön koşulu çözüme ihtiyaç duyulan sorunun olmasıdır.\n-Kaygılar da araştırmaya yönelten sebepler arasında yer alır."),
    InfoCardItem("egitimarastirma_info_4", "Araştırma Yöntemleri", "-Nitel ve nicel araştırma yöntemleri bulunur.\n-Nitel araştırmalar, metin analizi, örnek olay araştırması ve birebir görüşme gibi yöntemlerle yapılabilir.\n-Nicel araştırmalar, deney, gözlem ve test yoluyla gerçekleştirilebilir."),
    InfoCardItem("egitimarastirma_info_5", "Bilimsel Araştırma", "-Amaç bilimsel gelişimi sağlamaktır.\n-Planlı ve sistematik şekilde gerçekleştirlir.\n-Veriler toplanır ve yorumlanır.\n-Temel unsur, araştırmanın sistematik yapıda gerçekleşmesidir."),
    InfoCardItem("egitimarastirma_info_6", "Araştırma Yöntemleri", "-Olay araştırması,\n-Aksiyon araştırması,\n-Etnografik araştırma,\n-Gelişimci araştırma,\n-Fenomografik araştırma"),
    InfoCardItem("egitimarastirma_info_7", "", "-Problemin tespit edilmesi,\n-Problemin tanımlanması,\n-Hipotezin kurulması,\n-"),

    ]),
    InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
   /* InfoCardModel("", [
 InfoCardItem("egitimarastirma_info_8", "", ""),
      InfoCardItem("egitimarastirma_info_9", "", ""),
      InfoCardItem("egitimarastirma_info_10", "", ""),
      InfoCardItem("egitimarastirma_info_11", "", ""),
      InfoCardItem("egitimarastirma_info_12", "", ""),
      InfoCardItem("egitimarastirma_info_12", "", ""),
      InfoCardItem("egitimarastirma_info_12", "", ""),
      InfoCardItem("egitimarastirma_info_13", "", ""),
      InfoCardItem("egitimarastirma_info_14", "", ""),
      InfoCardItem("egitimarastirma_info_15", "", ""),
      InfoCardItem("egitimarastirma_info_16", "", ""),
      InfoCardItem("egitimarastirma_info_17", "", ""),
      InfoCardItem("egitimarastirma_info_18", "", ""),
      InfoCardItem("egitimarastirma_info_19", "", ""),
      InfoCardItem("egitimarastirma_info_20", "", ""),
      InfoCardItem("egitimarastirma_info_21", "", ""),
      InfoCardItem("egitimarastirma_info_22", "", ""),
      InfoCardItem("egitimarastirma_info_23", "", ""),
      InfoCardItem("egitimarastirma_info_24", "", ""),
      InfoCardItem("egitimarastirma_info_25", "", ""),
      InfoCardItem("egitimarastirma_info_26", "", ""),
      InfoCardItem("egitimarastirma_info_27", "", ""),
      InfoCardItem("egitimarastirma_info_28", "", ""),
      InfoCardItem("egitimarastirma_info_29", "", ""),
      InfoCardItem("egitimarastirma_info_30", "", ""),
      InfoCardItem("egitimarastirma_info_31", "", ""),
      InfoCardItem("egitimarastirma_info_32", "", ""),
      InfoCardItem("egitimarastirma_info_33", "", ""),
      InfoCardItem("egitimarastirma_info_34", "", ""),
      InfoCardItem("egitimarastirma_info_35", "", ""),
      InfoCardItem("egitimarastirma_info_36", "", ""),
      InfoCardItem("egitimarastirma_info_37", "", ""),
      InfoCardItem("egitimarastirma_info_38", "", ""),
      InfoCardItem("egitimarastirma_info_39", "", ""),
      InfoCardItem("egitimarastirma_info_40", "", ""),
      InfoCardItem("egitimarastirma_info_41", "", ""),
      InfoCardItem("egitimarastirma_info_42", "", ""),
      InfoCardItem("egitimarastirma_info_43", "", ""),
      InfoCardItem("egitimarastirma_info_44", "", ""),
      InfoCardItem("egitimarastirma_info_45", "", ""),
      InfoCardItem("egitimarastirma_info_46", "", ""),
      InfoCardItem("egitimarastirma_info_47", "", ""),
      InfoCardItem("egitimarastirma_info_48", "", ""),
      InfoCardItem("egitimarastirma_info_49", "", ""),
      InfoCardItem("egitimarastirma_info_50", "", ""),
      InfoCardItem("egitimarastirma_info_51", "", ""),
      InfoCardItem("egitimarastirma_info_52", "", ""),
      InfoCardItem("egitimarastirma_info_53", "", ""),
      InfoCardItem("egitimarastirma_info_54", "", ""),
      InfoCardItem("egitimarastirma_info_55", "", ""),
      InfoCardItem("egitimarastirma_info_56", "", ""),
      InfoCardItem("egitimarastirma_info_57", "", ""),
      InfoCardItem("egitimarastirma_info_58", "", ""),
      InfoCardItem("egitimarastirma_info_59", "", ""),
      InfoCardItem("egitimarastirma_info_60", "", ""),
      InfoCardItem("egitimarastirma_info_61", "", ""),
      InfoCardItem("egitimarastirma_info_62", "", ""),
      InfoCardItem("egitimarastirma_info_63", "", ""),
      InfoCardItem("egitimarastirma_info_64", "", ""),
      InfoCardItem("egitimarastirma_info_65", "", ""),
      InfoCardItem("egitimarastirma_info_66", "", ""),
      InfoCardItem("egitimarastirma_info_67", "", ""),
      InfoCardItem("egitimarastirma_info_68", "", ""),
      InfoCardItem("egitimarastirma_info_69", "", ""),
      InfoCardItem("egitimarastirma_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get egitimArastirma => _egitimArastirmaList;}