import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class EgitimKapsayiciInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> get egitimKapsayici => _egitimKapsayiciList;}

  List<InfoCardModel> _egitimKapsayiciList = [
    InfoCardModel("Eğitimde Kapsayıcılık Tanımları", [
      InfoCardItem("ee_egitimkapsayici_info_1", "Tanım-1", "-Dışlanma, eşitsizlik ve ayrımcılık eğitim süreçleri içerisinde görülen olumsuz davranışlardandır.\n-Eğitim sistemleri ile bütünleştirilmeye çalışan kapsayıcı eğitim bu olumsuz davranışları ortadan kaldırmayı hedeflemektedir. "),
      InfoCardItem("ee_egitimkapsayici_info_2", "Tanım-2", "-UNESCO tarafından kapsayıcı eğitim “öğrencilerin farklı ihtiyaçlarına, onların eğitime, kültüre ve sosyal hayata katılımlarını arttırarak ve ayrımcılığı en aza indirerek cevap verme süreci” olarak tanımlanmaktadır.\n-UNICEF’e göre kapsayıcı eğitim ise tüm çocukların aynı okulda birlikte öğrenmeleridir."),
      InfoCardItem("ee_egitimkapsayici_info_3", "Tanım-3", "-Kapsayıcı eğitim dışlanmayı ve ayrımcılığı yok ederek herkese eşit, sosyal adaleti benimseyen, toplumsal değerlere ve toplumsal farklılıklara saygı duyan önemli değerleri vurgulayan bir eğitim anlayışını destekler.\n-Bu anlayışın temelinde farklılıkların ortadan kaldırılarak aynılaştırma değil, farklılıkları olduğu gibi kabul edip saygı duyma olgusu yatar."),
      InfoCardItem("ee_egitimkapsayici_info_4", "Tanım-4", "Kapsayıcı eğitim; öğrencilerin gereksinim, ihtiyaç, tercih ve kişisel özellikleri analiz edilerek hazırlanmış planlı bir eğitim sürecidir. Böylece eğitim sürecinin niteliği ve öğrencilerin derse katılım ve ilgileri artar."),
      InfoCardItem("ee_egitimkapsayici_info_4_11", "Tanım-5", "-Kapsayıcı eğitim, özü itibariyle eğitimden dışlanma riski bulunan tüm bireylerin eğitim süreçlerine dâhil edilmesi gerektiğini savunan bir yaklaşımdı.\n-Ancak, zaman içinde güçlü kuramsal ve pratik yönlerinden dolayı, tüm bireylere nitelikli eğitim sunma potansiyeline sahip bir eğitim modeli olarak tanımlanmaya başlamıştır.\n-Kapsayıcı eğitim ortamına sahip okullar tüm öğrencilerin koşulsuz bir şekilde kabul edilmesini ve eğitim ihtiyaçlarının okulda karşılanması gerektiğini savunurlar."),
      InfoCardItem("ee_egitimkapsayici_info_4_12", "Tanım-7", "-Kapsayıcı eğitim, bireysel farklılıklara odaklanır.\n-Farklılıklar değerlidir.\n-Hiçbir birey, varolan farklılıkları sebebiyle eğitim hakkından mahrum bırakılamaz.\n-Eğitim hakkı, her birey için kazanılmış haktır ve engellenemez."),
      InfoCardItem("ee_egitimkapsayici_info_4_13", "Tanım-8", "-Kültürel geçmişleri farklı olan bireyler, kırsal bölgede yaşayan çocuklar, kız çocukları, göçmen ve mülteci çocuklar gibi birçok grubun eğitim hakkı, kapsayıcı eğitim bünyesinde yer alır.\n-Farklı grupların, eğitimde fırsat eşitliği kapsamında aynı eğitimi görmeleri mümkün kılınmalıdır."),
    ]),

    InfoCardModel("Kapsayıcılık ile İlgili Temel Unsurlar", [
      InfoCardItem("ee_egitimkapsayici_info_4_12","Temel Unsurlar", "Kapsayılıcılık ile ilgili temel unsurlar aşağıdaki gibi sıralanabilir;\n\n-Entegrasyon,\n-Dışlanma\n-Ayrımcılık\n-Kapsayıcılık"),
      InfoCardItem("ee_egitimkapsayici_info_4_13","Entegrasyon", "Dezavantajlı öğrencilerin eğitim-öğretim sürecinin temel gerekliliklerini karşıladıkları sürece akranlarıyla beraber aynı çatı altında eğitim görmeleridir.\n-Öğrencilerin bireysel farklılıkları göz ardı edildiğinde, özellikle dezavantajlı öğrenciler diğer öğrencilerle aynı haklardan faydalanamazlar."),
      InfoCardItem("ee_egitimkapsayici_info_4_14","Dışlanma", "-Öğrencilerin farklılıkları (dil, din, ırk, fiziki yetersizlik, sosyo-ekonomik durum vb…) sebebiyle eğitim haklarının kesintiye uğratılmasıdır.\n-Öğrencilerin akademik başarıları ve psikolojileri -dolaylı olarak ya da doğrudan- dışlanma sebebiyle olumsuz etkilenmektedir.\n-Eğitim hakkının yok sayılması doğrudan veya dolaylı gerçekleştirilebilir."),
      InfoCardItem("ee_egitimkapsayici_info_4_15","Ayrımcılık", "-Dezavantajlı öğrencilerin kendilerine özel hazırlanmış sınıflarda eğitim görmeleri durumudur.\n-Bu ortam farklı bir kurum olabileceği gibi, aynı okulda farklı bir sınıfta olabilir.\n-Akranları ile birlikte değillerdir, ayrıştırılmışlardır."),
      InfoCardItem("ee_egitimkapsayici_info_4_16","Kapsayıcılık", "-Dezavantajlı öğrenciler için fırsat eşitliği sunan, adaletli ve çoğulcu bir eğitim hayatı oluşturabilmek için reformist bir anlayışla gerekli düzenlenmelerin yapılmasıdır.\n-Öğrencilerin engellerinin kaldırılması için öğretim teknik ve stratejileri dahil tüm engellerin kaldırılması için yapılan reformdur.\n-Amaç, tüm öğrencilere eşit, adaletli ve katılımcı öğrenme deneyimi sunmaktır."),
      InfoCardItem("ee_egitimkapsayici_info_4_17","Dışlanma-Ayrımcılık", "-Dışlanma ile ayrımcılık kavramları birbiri ile karıştırılabilir.\n-Dışlanma kavramında eğitim hakkından mahrum kalma varken, ayrımcılık kavramında eğitim hakkı devam ederken normal öğrencilerden ayrışma vardır.\n-Öğrenci eğitim alamıyorsa dışlanma, dezavantajlı öğrenciler ile normal öğrenci ayrı ortama alınıyorsa ayrımcılıktır.\n-Sorularda çeldirici olarak gelebilir."),
      InfoCardItem("ee_egitimkapsayici_info_4_17","Hepsi Kısaca", "Entegrasyon;\n-Eğitim koşulu sağlanırsa eğitime entegre etme\n\nDışlanma;\n-Eğtim hakkından mahrum kalma\n\nAyrımcılık;\n-Aynı ortamda farklı muamele\n\nKapsayıcılık;\n-Hepimiz kardeşiz, ne olursan ol gel"),
    ]),InfoCardModel("Kapsayıcı Eğitimin Odakları", [
      InfoCardItem("ee_egitimkapsayici_info_5", "Odaklandığı Temel Alanlar", "UNESCO 2009 yılında kapsayıcı eğitimin odaklandığı temel alanları şu şekilde belirlemiştir;\n-Sistem Kapsayıcılığı\n-Eğitime Erişim Kapsayıcılığı\n-Sosyal Kapsayıcılık"),
      InfoCardItem("ee_egitimkapsayici_info_6", "Sistem Kapsayıcılığı", "Eğitim sistemlerinin, okulların ve öğretmenlerin sosyal, kültürel ve bireysel çeşitliliğe saygı duyması, tüm öğrencilerin ihtiyaç ve beklentilerine cevap vermesi olarak tanımlanır."),
      InfoCardItem("ee_egitimkapsayici_info_7", "Eğitime Erişim Kapsayıcılığı", "Tüm bireyler için nitelikli eğitime eşit erişim olanağının sağlanması olarak tanımlanır.\n-Yani, eğitim almak isteyen herkes eğitim alsın anlayışı bulunur."),
      InfoCardItem("ee_egitimkapsayici_info_8", "Sosyal Kapsayıcılık", "Sosyal politikalar ile tüm paydaşların beklentilerini de kapsayacak şekilde eğitim süreçleri dahilinde yakın koordinasyon içinde olunması olarak tanımlanır.\n-Kısaca, toplumun tüm kesimlerinin din, dil, ırk, engel durumu, mültecilik vs. gibi durumları gözetilmeden sosyal hayatta aktif şekilde varolmalarıdır."),
      InfoCardItem("ee_egitimkapsayici_info_8_1", "Hepsi Beraber", "-Sistem Kapsayıcılığı: Eğitim sistemi, okul ve öğretmen\n\n-Eğitim Erişim Kapsayıcılığı: Eğitim olanaklarına ulaşma\n\n-Sosyal Kapsayıcılık: Tüm farklılıklara rağmen sosyal hayatta aktif şekilde varolmak"),
    ]),InfoCardModel("Kapsayıcı Eğitimin Gerekçeleri", [
      InfoCardItem("ee_egitimkapsayici_info_5", "Kapsayıcı Eğitimin Gerekçeleri", "-Gerekçe, bir durumun dayandığı nedendir veya varolma sebebi olarak açıklanabilir.\n-Kapsayıcı eğitimin gerekçeleri temel olarak 4 başlıkta toplanır. Bu başlıklar;\n-Eğitimsel gerekçe\n-Sosyal gerekçe\n-Ekonomik gerekçe\n-Hukuki gerekçe"),
      InfoCardItem("ee_egitimkapsayici_info_6", "Eğitimsel gerekçe-1", "-Kapsayıcı eğitimin yararlarından birinin de öğrencilerin akademik performansını geliştirmek olduğu öngörülmektedir.\n-Çeşitli farklılıkları olan öğrencilere, birlikte ve nitelikli bir eğitim sağlama gayretinde bulunan okullar, bireysel ihtiyaçlara cevap verebilecek öğretim yöntemleri geliştirmek zorunda olacaktır.\n-Böylece bütün öğrencilerin öğrenmeleri olumlu yönde etkilenecektir."),
      InfoCardItem("ee_egitimkapsayici_info_6_1", "Eğitimsel gerekçe-2", "-Genellikle PISA gibi sınavlarda iyi derecede başarı gösteren ülkelerde okullar arasındaki eşitsizliğin en az düzeyde olduğu görülmektedir.\n-Ayrıca bireylere sosyoekonomik statülerinden bağımsız olarak eşit eğitim/öğrenme ortamlarından faydalanma imkânı verildiği gözlenmektedir."),
      InfoCardItem("ee_egitimkapsayici_info_6_2", "Eğitimsel gerekçe-3", "-Öğrencilerin kişisel özellik ve ihtiyaçlarına hitap eden eğitim programlarının geliştirilmesi gereklidir.\n-Bu şekilde geliştirilen eğitim programları ile öğrencilerin öğrenme potansiyelleri desteklenirken özgüvenleri de artacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_7_1", "Sosyal gerekçe-1", "-Kapsayıcı eğitimin önemli sosyal faydaları da olduğu bir öngörülmektedir.\n-Kapsayıcı eğitim kapsamında tüm öğrenciler aynı ortamda eğitim alırlar.\n-Bu sayede bir öğrenci, toplumda varolan farklılıkları görme şansı yakalar.\n-Farklılık ile birlikte aynı ortamı paylaşan çocuklar bu farklılıklara ilişkin tutumlar da geliştirirler. "),
      InfoCardItem("ee_egitimkapsayici_info_7_2", "Sosyal gerekçe-2", "-Kapsayıcı eğitim, toplum içindeki kaynaşma, beraber yaşama ve farklılıkların zenginlik oluşturduğu yönündeki duyguları ortaya çıkarmada etkilidir.\n-Salamanca Bildiriminde; 'Kapsayıcı eğitim oryantasyonuna sahip okulların ayrımcılıkla mücadele edilmesi, herkesi hoş karşılayan ve kabul eden bir toplumun oluşturulması ve herkesin eğitim alma hakkına erişebilmesi' yönünde etkili olduğu bildirilmiştir."),
      InfoCardItem("ee_egitimkapsayici_info_7", "Sosyal gerekçe-3", "Öğrencilerin adaletli ve fırsat eşitsizliklerinden arınmış bir ortamda eğitim görmesi toplumsal bir değişikliğin temelini oluşturacaktır.\n-Farklılıkların farkında, onlarla yaşamayı bilen bireyler, toplumda saygı kültürünün de yerleşmesini sağlayacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_8_1", "Ekonomik gerekçe-1", "-Geçmişte farklı dezavantajlı gruplara yönelik özel programlar geliştirilmiştir.Ancak bu çabalar genellikle daha fazla dışlanmaya sebep olmuş ve başarısızlıkla sonuçlanmıştır.\n-Bu yüzden günümüzde kültürel, dil, din, etnik ve sosyoekonomik açıdan farklılıkları olan tüm bireyleri kapsayıcı eğitim anlayışı çerçevesinde bir arada eğitmenin en etkili yol olacağı düşünülmektedir."),
      InfoCardItem("ee_egitimkapsayici_info_8_2", "Ekonomik gerekçe-2", "-Farklı özelliklere sahip öğrenci gruplarının her birisine yönelik ayrı ayrı program geliştirilemez.\n-Geliştirilse bile bu çok maliyetli olacaktır.\n-Bu yüzden, kapsayıcı eğitimin tüm öğrencilere daha az maliyet ile eğitim sağlaması beklenmektedir."),
      InfoCardItem("ee_egitimkapsayici_info_8", "Ekonomik gerekçe-3", "-Tüm öğrencilerin bir çatı altında eğitim görmesi farklı türde okullara olan ihtiyacı azaltacağı için düşük maliyetli olacaktır.\n-Ekonomik gerekçe öğrencilerin okula değil okulların öğrenciye uygun olması ilkesine dayanır."),
      InfoCardItem("ee_egitimkapsayici_info_8_3", "Hukuki gerekçe", "-Birleşmiş Milletler, 18 yaşına kadar her insanı çocuk olarak tanımlar.\n-Bu tanım, Birleşmiş Milletler Çocuk Haklarına Dair Sözleşmesi’nin (1989) I. kısım 1. maddesinde yer almaktadır.\n-Bu dönem, kendinden sonra gelecek gençlik ve yetişkinlik dönemlerinin başlangıcıdır.\n-Bundan dolayı Çocuk Hakları Sözleşmesinin 28. maddesinde ve 23. maddesinde çocukların eğitime erişmeleri gerektiği ifade edilmektedir."),
      InfoCardItem("ee_egitimkapsayici_info_9", "Temel İlkeler-1", "-Öğrencilerin ihtiyaç ve gereksinimlerine uygun bir eğitim imkanı sunulmalıdır.\n-Eğitimde adalet ve fırsat eşitliği sağlanmalıdır.\n-Eğitim sürecine aile ve toplumun katılımı sağlanmalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_10", "Temel İlkeler-2", "-Öğrencilerin istihdamı için altyapı hazırlanmalıdır.\n-Öğrencilerin bilişsel, duyuşsal ve toplumsal becerilerinin geliştirilmesi amaçlanmalıdır.\n-Kapsayıcı eğitimin iyileştirilmesi için bilimsel çalışmalar yapılmalı, çalışmaların sonuçlarına uygun etkinlik ve uygulamalar hazırlanmalıdır."),
    ]),InfoCardModel("Kapsayıcı Eğitimin Faydaları", [
      InfoCardItem("ee_egitimkapsayici_info_11", "Kapsayıcı Eğitimin Faydaları-1", "Kapsayıcı eğitimin, eğitim sitemine ve öğretim sürecine olan katkıları şu şekilde özetlenebilir;\n-Tüm çocukların öğrenmesini ve fırsat eşitliği elde etmesini hedefler.\n-Bireysel farklılıkların dikkate alındığı eğitim programı ile öğrencilerin öğrenme potansiyelleri desteklenir. Böylece öğrenciler özgüven kazanırlar."),
      InfoCardItem("ee_egitimkapsayici_info_12", "Kapsayıcı Eğitimin Faydaları-2", "-Bireysel farklılıkları dikkate alarak her öğrenci için uygun ders içeriği sunulur, her öğrenci kendini değerli ve özel hisseder.\n-Öğrencilerin ev, okul ve toplum yaşamını ilişkilendirir ve bütünleştirir."),
      InfoCardItem("ee_egitimkapsayici_info_13", "Kapsayıcı Eğitimin Faydaları-3", "-Öğrenciler tek yönlü bakış açılarını geliştirerek farklılıklara değer vermeye başlarlar.\n-Öğrencilerin okula ilgilisi, derslere katılımı artar ve devamsızlıkları azalır.\n-Öğrencilerin farklı gördükleri bireylere karşı önyargılarını azaltır, toplumsal barışa katkı sağlar ve toplumsal ortak duyguları geliştirir."),
      InfoCardItem("ee_egitimkapsayici_info_14", "Kapsayıcı Eğitimin Faydaları-4", "-Öğrenciler kendilerini daha geniş bir topluluğun parçası olarak görürler, sosyal ilişki kurmaları kolaylaşır ve empati yetenekleri gelişir.\n-Öğrencilerin, ait oldukları küçük grubun ötesinde, kendilerini daha geniş toplumun bir parçası olarak görmelerini sağlamak ve o toplumdaki diğer gruplardan bireyler ile empati ve ilişki kurmalarını sağlamak."),
    ]),InfoCardModel("Kapsayıcı Eğitim Grupları", [
      InfoCardItem("ee_egitimkapsayici_info_15", "Kapsayıcı Eğitim Kapsamındaki Gruplar", "-Kapsayıcı eğitim ilk olarak sadece engelli öğrencilere yönelik ortaya çıkmıştır.\n-Daha sonraları ise tüm dezavantajlı grupları içine alacak şekilde genişlemiştir.\n-Bu dezavantajlı gruplar;\n-Etnik Köken\n-Fiziksel Yetersizlik ve Özel Gereksinim\n-Sosyoekonomik Düzey\n-Dini İnanç\n-Cinsiyet"),
      InfoCardItem("ee_egitimkapsayici_info_16", "Etnik Köken", "-Öğrencilerin mülteci, göçmen, sığınmacı olmaları ya da etnik kökenleri sebebiyle okulda ve okul dışında olumsuz davranış (dışlama, aşağılama vb.) yaşamalarıdır."),
      InfoCardItem("ee_egitimkapsayici_info_17", "Fiziksel Yetersizlik ve Özel Gereksinim", "-Öğrencilerin özel durumları sebebiyle olumsuz davranışlara maruz kalma durumudur.\n-Bu öğrencileri sınıfta dışlanması, aşağılanması bu duruma örnek olarak verilebilir."),
      InfoCardItem("ee_egitimkapsayici_info_18", "Sosyoekonomik Düzey", "-Düşük ya da yüksek gelir durumu, aile yapısı vb. konulardan dolayı öğrencilerin olumsuz davranışlara maruz kalma durumudur."),
      InfoCardItem("ee_egitimkapsayici_info_19", "Dini İnanç", "Öğrencilerin inancı, ibadeti ya da mezhebi sebebiyle dışlanması durumudur."),
      InfoCardItem("ee_egitimkapsayici_info_20", "Cinsiyet", "Öğrencilerin cinsiyetleri sebebiyle yaşadığı ayrımcılık durumlarıdır. Kız öğrencilerin okuldan alınamaması ya da gönderilmemesi örnek olarak verilebilir."),
    ]),InfoCardModel("Kapsayıcı Eğitimde Sık Görülen Davranışlar", [
      InfoCardItem("ee_egitimkapsayici_info_21", "Sık Görülen Davranışlar-1", "Bu bölümde yer alan davranışlar, kapsayıcı eğitim ihtiyacı olan(Dışlanan, ayrımcılığa uğrayan vb.) çocuklarda sıklıkla görülen davranışlardır."),
      InfoCardItem("ee_egitimkapsayici_info_22", "Sık Görülen Davranışlar-2", "-Öğrenci okulu sevmediğini söyler. Okula karşı ilgisizlik duyar ve okula gitmek istemeyebilir. \n-Öğrenci akranlarıyla, kendinden büyük ya da küçük çocuklarla göz teması ve iletişim kurmakta zorlanabilir."),
      InfoCardItem("ee_egitimkapsayici_info_23", "Sık Görülen Davranışlar-3", "-Öğrenci okuldan eve geldiğinde yorgun, huysuz ve aksi davranışlarda bulunabilir.\n-Okuldan eve geldiği zaman okulda yaşadığı problemlerden bahsedebilir.\n-Öğrenci sanat, müzik, dans gibi güzel sanatlara olan ilgisini zamanla kaybedebilir.\n-Boş zaman aktivitelerini bırakabilir."),
      InfoCardItem("ee_egitimkapsayici_info_24", "Sık Görülen Davranışlar-4", "-Okulla ilgili hiçbir şey yapmak istemeyebilir. Okul dışı etkinliklere yönelebilir. \n-Okul ile ilgili yapması gerekenleri (Ödev, proje vb.) son ana bırakır ya da yapmaz.\n-Okulla ilgili heyecan verici ya da mutlu olduğu durumları anlatmayı bırakabilir.\n-Okul rehberlik servisi ya da öğrencinin sınıf öğretmeni öğrencinin yaşadığı-yaşattığı problemlerle ilgili sizinle görüşmek isteyebilir."),    ]),
  InfoCardModel("Kapsayıcı Eğitimin Önündeki Engeller-1 (Yeni)", [
    InfoCardItem("ee_egitimkapsayici_info_45","Engeller-1","-Kapsayıcı eğitim, öğrencilerin değiştirilmesinin değil eğiim süreçlerinin değiştirilmesine odaklanır.\n-Bu sebeple kapsayıcı eğitim sistemi kapsamında, okul ve sınıf ortamlarında çeşitli değişiklikler yapılabilir.\n-Bu değişim sırasında veya kapsayıcı eğitim sürecinde ortaya çıkacak birçok engel bulunabilir.\n-Bunlar, diğer kartta sıralanmıştır."),
    InfoCardItem("ee_egitimkapsayici_info_46","Engeller-2","-Kapsayıcı eğitim sırasında ortaya çıkabilecek engeller aşağıdaki gibi sıralanmıştır.\n\n-Öğretmen Kaynaklı Engeller,\n-İdareci Kaynaklı Engeller\n-Müfredat ve Ders Kitabı Kaynaklı Engeller\n-Öğrenci Kaynaklı Engeller\n-Veli ve Çevre Kaynaklı Engeller\n-Fiziki Ortam Kaynaklı Engeller\n-Okul Kültürü Kaynaklı Engeller"),
    InfoCardItem("ee_egitimkapsayici_info_47","Öğretmen Kaynaklı Engeller-1","-Öğretim sürecinin planlanması, uygulanması ve değerlendirilmesinde en büyük sorumluluk öğretmene aittir.\n-Öğretmenlerin mesleki yeterlilikleri bu anlamda büyük önem taşımaktadır.\n-Bu durumlar göz önünde bulundurulduğunda, kapsayıcı eğitim ortamı düzenlenmek isteniyorsa, öğretmen yeterlilikleri ve öğretmenlerin kapsayıcı eğitime uygun şekilde yetiştirilmeleri önem arz etmektedir."),
    InfoCardItem("ee_egitimkapsayici_info_48","Öğretmen Kaynaklı Engeller-2","-Eğitim sürecinin en önemli parçası olan öğretmenlerin, kendilerini yetiştirmeleri önemlidir.\n-UNESCO'ya göre, kapsayıcı eğitim kapsamında görev yapan bir öğretmenin sahip olması gereken önemli özellikler aşağıda verilmiştir.\n\n-Çeşitlilikleri takdir etmeli,\n-Farklı öğretim yöntem ve tekniklerini kullanabilmeli,\n-Bireysel öğrenme ihtiyaçları ile başa çıkabilmelidir."),
    InfoCardItem("ee_egitimkapsayici_info_49","Öğretmen Kaynaklı Engeller-3","-Tüm öğrencilerin öğrenebileceğine inanmama,\n-Öğrenme ortamını fiziksel olarak düzenleyememe,\n-Bireysel farklılıkları göz ardı etme,\n-Bireysel ihtiyaçlara cevap verememe,\n-Alternatif ölçme araçlarını kullanamama,\n-Öğrencileri soru sormaya teşvik edememe,\n-Okul etkinliklerine yeterli katılım sağlamama gibi konular öğretmen kaynakllı engeller kabul edilir."),
    InfoCardItem("ee_egitimkapsayici_info_50","İdareci Kaynaklı Engeller-1", "-Okul yönetimi, eğitim-öğretim faaliyetlerinde yer alan tüm süreçten sorumludur.\n-Okul yönetimi, eğitim-öğretim sürecindeki eskiklikleri tespit etmeli, ihtiyaçları karşılamak için gerekli tedbirleri almalıdrı.\n-Kapsayıcı eğitim faaliyetlerinin okul içerisinde ve dışarısında yürütülmesine katkı sağlamalıdır.\n-Kapsayıcı eğitim açısından engel teşkil edebilecek bazı idareci kaynaklı engeller sonraki kartta verilmiştir."),
    InfoCardItem("ee_egitimkapsayici_info_51","İdareci Kaynaklı Engeller-2", "-Okulun ve sınıfların fiziki ortamının kapsayıcı eğitime uygun şekilde düzenlemesini sağlamamak,\n-Kapsayıcı eğitim faaliyeti yürüten öğretmenlerinin motivasyonlarına katkı sağlamamak,\n-Okul-veli işbirliğine katkı sağlamamak,\n-Öğrencilerin kapsayıcı eğitim sürecine dahil olmalarını sağlayacak faaliyetlere katkı sağlamamak,\n-Eğitim sürecine katkı sağlayacak personel desteğinin okulda hazır bulunmasına yardımcı olmamak gibi örnekler verilebilir."),
    InfoCardItem("ee_egitimkapsayici_info_52","Müfredat ve Ders Kitabı Kaynaklı Engeller-1", "Kapsayıcı eğitim, tüm öğrencilerin, ayırt edilmeden aynı ortamda eğitim görmelerini hedefler.\n-Bu durum, öğrencilerin birbirinden farklı öğrenme yöntemlerine göre ders materyalleri ve kitapları hazırlanma zorunluluğunu ortaya çıkartır.\n-Öğrenme güçlüğü çeken bir öğrencinin, öğrenme seviyesi normal bir öğrenci ile aynı sınıfı paylaştığı düşünüldüğünde, aynı müfredatın, kitabın ve materyalin aynı düzeyde öğrenmeyi sağlaması beklenemez. "),
    InfoCardItem("ee_egitimkapsayici_info_53","Müfredat ve Ders Kitabı Kaynaklı Engeller-2", "-Tek bir gruba yönelik içerikler hazırlanması,\n-Algılanabilirliğin düşük olması,\n-Ders içi etkinlikleri zenginleştirmekten uzak olması,\n-Farklı öğrenme gruplarının ihtiyaçlarını karşılayabilecek düzeyde olmaması,\n-Kapsayıcı eğitim gören öğrencileri eğitim-öğretim sürecine dahil edebilecek yeterlilikte, zenginleştirilmiş yapı içermemesi müfredat ve ders kitabı engeline örnek olarak verilebilir."),
      ]),
    InfoCardModel("Kapsayıcı Eğitimin Önündeki Engeller-2 (Yeni)", [
    //Fiziki Ortam Kaynaklı Engeller\n-Fiziksel Ortam Kaynaklı Engeller\n-Okul Kültürü Kaynaklı Engeller"),
      InfoCardItem("ee_egitimkapsayici_info_54", "Öğrenci Kaynaklı Engeller", "-Öğrenci, eğitim-öğretim sürecinin temel unsurlarından biridir.\n-Öğrencinin, kapsayıcı eğitim sürecine hazır olmaması ve sürece aktif şekilde dahil olmaması, hedeflere ulaşmayı zorlaştıracaktır.\n-Öğrenci kaynaklı engeller yalnızca kapsayıcı eğitim gören öğrencileri için düşünülmemelidir.\n-Aynı zamanda süreçin doğal üyesi diğer öğrencilerden kaynaklanacak engeller de bu kapsamdadır.\n-Öğrencinin eğitim sürecine istekli olmaması örnek olarak verilebilir."),
      InfoCardItem("ee_egitimkapsayici_info_55", "Veli ve Çevre Kaynaklı Engeller-1", "-Eğitim öğretim faaliyetlerinde veli desteği önemli bir yer kaplamaktadır.\n-Veli-okul işbirliğinin öğrenci üzerindeki etkisi çok büyüktür.\n-Velinin, kapsayıcı eğitim sürecinde yürütülen faaliyetleri destekleyici bir unsur olması, eğitimin hedefine ulaşması noktasında büyük bir öneme sahiptir.\n-Şimdi eğitim sürecine veli ve çevre kaynaklı engellere bazı örnekler verelim."),
      InfoCardItem("ee_egitimkapsayici_info_56", "Veli ve Çevre Kaynaklı Engeller-2", "-Velinin okul ile işbirliğinde isteksiz veya yetersiz olması,\n-Öğrencinin eğitim-öğretim sürecini evde desteklemiyor olması,\n-Eğitim-öğretim sürecine fazla müdahale ederek programın uygulanmasına engel olması,\n-Aşırı sert kış sebebeiyle tekerlekli sandalye kullanan çocuğun okula gelmekte zorlanması gibi durumlar velii ve çevre kaynaklı engellere örnek olarak verilebilir."),
      InfoCardItem("ee_egitimkapsayici_info_57", "Fiziki Ortam Kaynaklı Engeller-1", "-Tüm farklılıklara hitap eden kapsayıcı eğitimde, eğitim ortamının öğrencilerinin tamamının ihtiyaçlarına uygun şekilde tasarlanması gerekmektedir.\n-Bunun sağlanamaması eğitim-öğretim sürecine ciddi zararlar verecek hatta sekteye uğratacaktır.\n-Öğrenciler için ideal fiziki yapının oluşturulması, öğrencilerin hazırbulunuşluk düzeylerini arttıracaktır.\n-Fiziki ortam kaynaklı engellere bazı örnekler verelim."),
      InfoCardItem("ee_egitimkapsayici_info_58", "Fiziki Ortam Kaynaklı Engeller-2", "-İşitme problemi olan bir öğrencinin metrekare olarak büyük bir sınıf ortamında bulunması,\n-Tekerlekli sandalye kullanan öğrencinin sınıfının zemin katta olmaması,\n-Bir cinsiyete odaklanarak hazırlanmış eğitim ortamı,\n-Gelir düzeyine göre farklılıkları ortaya çıkararak öğrenmeyi etkileyecek unsurlar barındıran bir öğrenme ortamı örnek olarak verilebilir."),
      InfoCardItem("ee_egitimkapsayici_info_59", "Okul Kültürü Kaynaklı Engeller-1", "-Okul Kültürü, yönetici, öğretmen, personel ve öğrencilerin katkılarıyla oluşan, okulda bütünleşmeyi sağlayan ve okul kalitesini arttıran, süregelen değer, inanç, gelenek ve hikayeler bütünüdür.\n-Okul kültürü olan okulların hedefleri, nasıl hareket edeceği ve öğretmen, öğrenci, idare ve veliden neler beklediği bellidir.\n-Ancak bazen kapsayıcı eğitime engel de olabilir.\n-Şimdi bazı örnekler verelim."),
      InfoCardItem("ee_egitimkapsayici_info_60", "Okul Kültürü Kaynaklı Engeller-2", "-Akademik başarı düzeyi çok yüksek olan okulda, Türkçe'yi tam öğrenemediği için derslerinde zorlanan göçmen bir öğrencinin kendini yetersiz hissetmesi,\n-Sportif başarıları ile tanınan bir okulda, yürüme engelli bir öğrencinin okul takımı çalışmalarına dahil edilmemesi örnekleri verilebilir."),

    ]),
    InfoCardModel("Kapsayıcı Öğrenme Ortamı (Yeni)", [
    InfoCardItem("ee_egitimkapsayici_info_25", "Ortamın Düzenlenmesi-1", "-Kapsayıcı eğitim kapsamında eğitim öğretim faaliyeti yürütülen kurumlarda, eğitim içeriği kadar ortamın düzenlenmesi de önem arz etmektedir.\n-Öğrenme ortamlarının tüm öğrencilerin ihtiyaçlarını karşılayabilecek düzeyde olması kapsayıcı eğitimin en çok üzerinde durduğu hususlardandır.\n-Şimdi öğrenme ortamları ile ilgili detaylı maddelere göz atalım."),
    InfoCardItem("ee_egitimkapsayici_info_26", "Ortamın Düzenlenmesi-2", "-Öğretmen her durumda taviz vermeden demokratik bir tutum sergilemelidir.\n-Sınıfın her ferdinin kabul gördüğü bir eğitim-öğretim ortamı sağlanmalıdır.\n-Sınıftaki öğrencilerin kendilerini rahatça ifade etmelerime imkan tanınmalıdır."),
    InfoCardItem("ee_egitimkapsayici_info_27", "Ortamın Düzenlenmesi-3", "-Her birey farklılıklara saygı göstermeli ve onları kabul etmelidir.\n-Öğrencilerin güdülenmeleri sağlanmalı ve içsel motivasyonları arttırılmalıdır.\n-Sınıfın fiziksel özellikleri bireylerin gereksinimleri göz önünde bulundurularak iyileştirilmelidir."),
    InfoCardItem("ee_egitimkapsayici_info_28", "Ortamın Düzenlenmesi-4", "-İlgi çeken ancak dikkat dağınıklığına da sebep olmayan bir sınıf ortamı oluşturulmalıdır.\n-Öğrencilerde sınıf birliği ve aidiyet duygusu oluşmalıdır.\n-Öğretmen-öğrenci, öğrenci-öğrenci arasında etkili bir iletişim sağlanmalıdır."),
    InfoCardItem("ee_egitimkapsayici_info_29", "Ortamın Düzenlenmesi-5", "-Güvenli bir sınıf ortamı oluşturulmalıdır.\n-Eğitim öğretim sürecinde farklı, zenginleştirilmiş yöntem ve teknikler kullanılmalıdır.\n-Aktif ve etkin bir öğrenme ortamı oluşturulmalıdır. "),
  ]),
    InfoCardModel("Kapsayıcı Öğretmen Yeterlilikleri (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_61", "Öğretmen", "-Öğretmen, eğitim-öğretim sürecinin en temel unsurudur.\n-Kapsayıcı eğitim, tüm öğrencilerin eğitim öğretim sürecinden faydalanmalarını hedefler.\n-Bu iki tanım birlikte düşünüldüğünde, eğitim öğretim sürecinin temel unsuru olan öğretmenin çok yönlü olma zorunluluğu ortaya çıkar.\n-Çok yönlülük, hem mesleki yeterlilik hem de mesleki bilgilerini ve deneyimlerini aktarabilme olarak düşünülebilir."),
      InfoCardItem("ee_egitimkapsayici_info_62", "Öğretmen Yeterlilikleri-1", "Kapsayıcı eğitimin öğretmenden beklentileri açıklamaları ile verilmiştir.\n\n-Sınıfın fiziksel ortamında öğrenci ihtiyaçlarına uygun olacak şekilde gerekli düzenlemeleri yapabilmelidir. (Tekerlekli sandalye ile derse gelen öğrencisine göre sınıf düzeni ayarlanmalıdır.) \n-Öğretmen, tüm öğrencilerin öğrenebileceğine inanmalıdır. (Sınıfında öğrenme güçlüğü olan bir öğrencisi bulunan öğretmenin, öğrenciye faydalı olabilmesi ancak buna inanması ile gerçekleşebilir.)"),
      InfoCardItem("ee_egitimkapsayici_info_63", "Öğretmen Yeterlilikleri-2", "-Dezavantajlı öğrenci gruplarına ulaşabilmek için özel gayret sarf etmelidir. (Maddi imkansızlıklardan dolayı okula hiç devam etmemiş öğrencisinin olduğunu tespit eden bir öğretmen, bu öğrenciye ulaşıp okula devamlılığı noktasında öğrenci ve ailesiyle görüşmelidir.)\n-Öğretim yöntemi belirlenirken öğrencilerin bireysel farklılıkları göz önünde bulundurulmalıdır. (Düz anlatım, problem çözme ve örnek olay yöntemlerinin beraber kullanılması örnektir.)"),
      InfoCardItem("ee_egitimkapsayici_info_64", "Öğretmen Yeterlilikleri-3", "-Derslerde, öğrenci ihtiyaçlarına göre farklı materyaller kullanabilmelidir. (Konu anlatımında görsel materyal kullanırken görme zorluğu yaşayan öğrencisi için dinleme etkinliği düzenlenebilmelidir.) \n-Bireysel ihtiyaçlara cevap verebilmek için teknolojiden etkin bir şekilde faydalanabilmelidir. (Akıllı tahtayı kullanarak, animasyon, etkileşimli uygulamalar ve slaytlar ile ders anlatımını zenginleştirmelidir.)"),
      InfoCardItem("ee_egitimkapsayici_info_65", "Öğretmen Yeterlilikleri-4", "-Alternatif ölçme-değerlendirme yöntemlerini kullanabilmelidir. (Öğrencilerine performans görevleri verebilmeli, ürün dosyası oluşturmalarını sağlayabilmeli veya akran değerlendirme vs. yaptırabilmelidir.) \n-Öğrencilerine isim ile hitap etmelidir. (İsim ile hitap etmek kişinin kendini değerli hissetmesini sağlar. Bu duygusu pekişen öğrencinin eğitim-öğretim sürecine dahil olması daha kolaydır.)"),
      InfoCardItem("ee_egitimkapsayici_info_66", "Öğretmen Yeterlilikleri-5", "-Öğrencilerin fikirlerine saygı duymalı ve onlara değer verdiğini hissettirmelidir. (Öğrencilerin kendini ifade etme becerileri gelişir. Değerli olduğunu hisseden öğrenci derse ve öğretmenine ilgilidir.) \n-Öğrencileri soru sormaya teşvik etmelidir. (Soru soran öğrencinin konuya ilgili olması ve öğrenme isteğinin fazla olması beklenir. Ayrıca soru soran öğrencinin bulunması, konuya dikkatin çekildiğini gösterir. )"),
      InfoCardItem("ee_egitimkapsayici_info_67", "Öğretmen Yeterlilikleri-6", "-Tüm öğrenci velileri ile olumlu iletişim kurmalıdır. (Özel eğitim gören öğrencilerde, okul etkinliklerinin evde pekiştirilebilmesi için okul-veli işbirliği şarttır.)\n-Okuldaki destek kurslarında aktif görev almalıdır ve okulun diğer tüm etkinliklerine aktif olarak katılmalıdır."),

   ]),
    InfoCardModel("Kapsayıcı Eğitimde Öğretmen-Öğrenci İlişkisi (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_74", "Neler Yapılmalı?", "-Eğitimde başarı sağlanması için öğretmen öğrenci ilişkisinin iyi düzeyde olması gerekir.\n-Bunun için öğretmen tarafından yapılması gerekenler aşağıda verilmiştir.\n\n-Bağ kurmak,\n-İçsel motivasyon sağlamak,\n-Süreç değerlendirmesine ağırlık vermek,\n-Yapıcı geri bildirim vermek,\n-Sevgi ve saygı çerçevesinde iletişim kurmak. "),
      InfoCardItem("ee_egitimkapsayici_info_75", "Bağ kurmak-1", "-Öğrencinin okula karşı olumlu bir tutum sergileyebilmesi için bağ kurması gerekir.\n-Bu aşamada en büyük görev öğretmene düşmektedir.\n-Bağ kurma, her öğrenci ile gerçekleştirilmesi gereken bir süreçtir.\n-Ancak, kapsayıcı eğitim kapsamında bulunan öğrencilerin bağ kurmaya daha fazla ihtiyacı olacaktır.\n-Şimdi öğretmenlerin bağ kurmak için yapabileceklerine bazı örnekler verelim."),
      InfoCardItem("ee_egitimkapsayici_info_76", "Bağ kurmak-2", "-Öğrenicnin ihtiyaçlarını fark etmelidir.\n-Öğrencinin kendini güvende hissetmesini sağlamalıdır.\n-Öğrenciden gelebilecek farklı fikirleri pekiştirmelidir.\n-Mizah yönünü kullanarak öğrenciyi kendisine çekmelidir.\n-Öğrenciyi cesaretlendirmelidir.\n-Sevgi dilini kullanmalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_77", "İçsel motivasyon sağlamak-1", "-Motivasyon, öğrenme sürecine aktif katılacak bir öğrencide mutlaka bulunması gereken bir özelliktir.\n-Motivasyonu olan bir öğrenci çaba gösterir.\n-Motivasyonu yüksek bir öğrenci öğrenmeye karşı istekli bir tutum sergiler.\n-Derse hazırlıklı gelir ve bilemediği veya anlayamadığı konular ile ilgili öğrenme yaklaşımları sergiler.\n-Şimdi öğretmenlerin içsel motivasyonu sağlamak için yapabileceklerine bazı örnekler verelim."),
      InfoCardItem("ee_egitimkapsayici_info_78", "İçsel motivasyon sağlamak-2", "-Sınıf içi iletişim ağı açık olmalıdır.\n-Öğrenciye karşı dürüst olunmalıdır.\n-Derste öğrenilecek bilgilerin, sosyal hayatta ne işe yarayacağı açıkça ifade edilmelidir.\n-Öğrencinin varolan bilgileri kullanılarak anlayacağı örnekler verilmelidir.\n-Dersi destekleyici materyaller kullanılmalıdır.\n-Öğrenciye yapabileceği sorumluluklar verilmelidir.\n-Sözlü veya yazılı övgü kullanılmalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_79", "Süreç değerlendirmesine ağırlık vermek", "-Kapsayıcı eğitimin odak noktası, öğrenmeyi öğrenmiş bireyler değildir.\n-Bu yüzden, bu öğrencilerin öğrenmelerinin değerlendirilmesinde acele edilmemelidir.\n-İçsel motivasyonları canlı tutularak süreç içerisinde öğrenmeleri desteklenmelidir.\n-Özellikle öğrenme güçlüğü çeken, anadili Türkçe'den başka bir dil olan veya ağır travmalar geçirdiği için okula adapte olma süreci içinde olan öğrencilerin hemen öğrenmesi beklenemez."),
      InfoCardItem("ee_egitimkapsayici_info_80", "Yapıcı geri bildirim vermek-1", "-Öğrencinin süreç sonunda elde ettiklerinin değerlendirilmesidir.\n-Geri bildirim vermek için sonucun veya davranışın olumlu veya olumsuz olmasına bakılmaz.\n-Geri bildirim sayesinde olumlu öğrenmeler için varolan öğrenme pekiştirilirken olumsuz öğrenmeler için yeni öğrenme sağlanır.\n-Yani öğrenci olumsuz bir öğrenme gerçekleştirdiysei geri bildirim sayesinde doğrusunu öğrenme şansı yakalar.\n-Şimdi öğretmenlerin yapıcı geri bildirim için yapabileceklerine bazı örnekler verelim"),
      InfoCardItem("ee_egitimkapsayici_info_81", "Yapıcı geri bildirim vermek-2", "-Değerlendirilen durumda varolan olumlu yanlara odaklanılmalıdır.\n-Süreç olumsuz da sonuçlanmış olsa gayret takdir edilmelidir.\n-Öğrencinin kişiliği ile ilgili değil, davranışları veya somut olanlar ile ilgili geri bildirim verilmelidir.\n-Geri bildirim teşvik edici olmalıdır.\n-Performansı arttırıcı ve başarıya ulaştırmaya yardımcı bir dil kullanılmalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_82", "Sevgi ve saygı çerçevesinde iletişim kurmak", "-Eğitim, sevgisiz düşünülemez.\n-Eğitimde verimliliği en çok arttıracak faktörlerden bir tanesidir.\n-Öğrenci başarısını olumlu yönde etkileyen unsur ceza değil sevgidir.\n-Özellikle aile içi şiddete maruz kalmış veya göçmen, mülteci veya sığınmacı öğrencilerde okul ve öğretmen ile iyi bir ilişki kurulmasının önkoşulu sevgidir.  "),
   ]),
    InfoCardModel("Öğrenmeye Karşı Güdülenme (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_83", "Psikolojik İhtiyaçlar", "-Öğrencilerin öğrenmeye karşı güdülenebilmesi için 5 temel psikolojik ihtiyacın karşılanmış olması gerekmektedir.\n-Bunlar\n\n-Ait olma,\n-Güç,\n-Eğlence,\n-Hayatta kalma/güvenlik,\n-Özgürlük olarak sıralanabilir. "),
      InfoCardItem("ee_egitimkapsayici_info_84", "Ait olma-1", "-Öğrencinin içinde bulunduğu aile, akran, sosyal çevre ve toplum ile uyumlu bir biçimde yaşaması için gerekli olan sevgiyi alması ve gösterebilmesi olarak tanımlanabilir.\n-Öğrenci, içinde bulunduğu sosyal sistemdeki ilişki ve iletişim ağının bir parçası olduğunu hissetmelidir.\n-Ancak bu yolla ait olma duygusunu giderebilir.\n-Ait olma ihtiyacı karşılanırsa veya karşılanmazsa neler olabileceğine bir sonraki kartta bakalım. "),
      InfoCardItem("ee_egitimkapsayici_info_85", "Ait olma-2", "Karşılanırsa\n\n-Sınıf ortamında kabul gördüğü için okula aidiyeti gelişir. Arkadaşlık ilişkileri olumludur. Okula devamlılığına olumlu katkı yapar.\n\n\nKarşılanmadığında\n-Problemli davranışlarında artış görülür. Kavgacı bir yapıya bürünebilir. Ait olma duygusu gelişmediği için grupla hareket etmez."),
      InfoCardItem("ee_egitimkapsayici_info_86", "Güç-1", "-Bireyin kişisel gelişimine karşılık gelir. Bu gelişimini tamamlayan unsurlar;\n-Bireyin bilgi ve beceri kazanması,\n-Yaşam kalitesini arttırmaya çalışması,\n-Başarıya yönelmesi\n-Kendini değerli hissetmesi olarak tanımlanabilir.\n\n-Güç ihtiyacı karşılanırsa veya karşılanmazsa neler olabileceğine bir sonraki kartta bakalım. "),
      InfoCardItem("ee_egitimkapsayici_info_87", "Güç-2", "Karşılanırsa\n\n-Aile ve öğretmenlerinden destek gören çocuklar kendini güçlü hissederler.\n\n\nKarşılanmazsa\n\n-Akademik başarısında düşüklük beklenir. Bu durum sınıf içi sosyal iletişimini etkiler. Başarı duygusu tetiklenemez."),
      InfoCardItem("ee_egitimkapsayici_info_88", "Eğlence-1", "-Oyun bir çocuğun kendini ifade biçimidir.\n-Eğlence ihtiyacı oyun ve eğlenme ile birlikte öğrenmeyi içermektedir.\n-Çocuklara işbirliğini ve diğerleriyle geçinmeyi öğretir.\n-Stresi azaltır, yaratıcılı ortaya çıkartır ve kişiler arası doğru ilişkilerin kurulmasını sağlar."),
      InfoCardItem("ee_egitimkapsayici_info_89", "Eğlence-2", "Karşılanırsa\n\n-Oyun ve eğlence ile iyi arkadaşlıklar kurulur ve akademik başarı artar.\n\n\nKarşılanmazsa\n\n-Akranları tarafından dışlanabilir. Bu da onu yalnızlaştırır. Sanatsal ve sportif etkinliklere katılımı azaltır."),
      InfoCardItem("ee_egitimkapsayici_info_90", "Hayatta kalma/güvenlik-1", "-İnsanların temel yaşam gereksinimleri barınma, beslenme ve güvenliği içerisinde barındırır.\n-İnsanların bu gereksinimlerinin muhakkak karşılanması gerekir.\n-Okulda öğrencinin kendini güvende hissetmesi öğrenmelerini kolaylaştırıcı bir unsur olarak karşımıza çıkar.\n-Ayrıca güvenli okul, öğrenme isteğini arttırır."),
      InfoCardItem("ee_egitimkapsayici_info_91", "Hayatta kalma/güvenlik-2", "Karşılanırsa\n\n-Okula güven duyan çocuk okula istekli gelir. Bu durum okul içi motivasyonunu arttırır. Akranları ile iyi ilişkiler kurmasını sağlar.\n\n\nKarşılanmazsa\n\n-İçe kapanık, tedirgin ve kuşkulu tavırlar sergiler. Öğrenmeye olan ilgisi, motivasyonu düşer. Bu durum başarısını olumsuz etkiler."),
      InfoCardItem("ee_egitimkapsayici_info_92", "Özgürlük-1", "-Bireyin sağlıklı karar vermesini sağlar.\n-Hareket sahasını genişleterek bireyin karar mekanizmasına olumlu yönde katkı sağlar.\n-Özgürlük duygusunu elinde bulunduran bireyler, içinden geldiği gibi davranır ve hayatın kontrolünü elinde bulundurur.\n-Bu durum onları mutlu eder."),
      InfoCardItem("ee_egitimkapsayici_info_93", "Özgürlük-2", "Karşılanırsa\n\n-Sınıf içerisinde verilecek kararlarda öğrencileri serbest bırakmak, özgürlük duygusuna olumlu katkı sağlar. \n\n\nKarşılanmazsa\n\n-Karşılaştığı problemlerle başetme duygularını olumsuz etkiler. Öğrenmeye olan ilgisi ve motivasyonu düşer."),

        ]),
    InfoCardModel("Kaynaştırma Ortamında Görülen Engeller (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_93", "Engeller-1", "-Hareketlilik\n-Dürtüsellik\n-Öz bakım ihtiyaçlarını karşılamada gerekli motor becerilerde zayıflık\n-Denge-koordinasyonda zayıflık\n-Sabırsızlık\n-Kolay sinirlenme"),
      InfoCardItem("ee_egitimkapsayici_info_94", "Engeller-2", "-Motor gelişiminde gerilik\n-Sosyal ilişkilerde güçlük\n-Dil gelişiminde zayıflık\n-Biliş ötesi becerilerde zayıflık\n-Kısa ve uzun süreli bellekte,\n-bilgi toplamada güçlük"),
      InfoCardItem("ee_egitimkapsayici_info_95", "Engeller-3", "-Sosyal etkileşim ve uyum becerilerinde yetersizlik \n-Öz bakım ve iletişim becerilerinde destek gereksinimi\n-Hareketlilik, psiko-motor beceriler ve bunlara ait davranışlarda güçlük \n-İki eli koordineli kullanma becerilerinde akranlarına göre düşük performans"),
      InfoCardItem("ee_egitimkapsayici_info_96", "Engeller-4", "-Duyusal girdi olmamasından kaynaklı bilişsel olarak şema oluşturmakta güçlük yaşarlar. \n-Konuşma hızları düşüktür. \n-Alan hâkimiyetlerinin düşük olmasından dolayı, davranışlar sınırlıdır."),
      InfoCardItem("ee_egitimkapsayici_info_97", "Engeller-5", "-İhtiyaçlarını sözel olarak ifade etmede yetersiz kalırlar. \n-Duyu organının kaybı nedeniyle konuşma ve bilişsel süreçlerde zayıflık görülmektedir. \n-Kimi insanlar düşüncelerini sözcüklerle anlatamadıkları için ya da duyduklarından anlam çıkaramadıkları için sözlü iletişimde zorluk çekerler."),
      InfoCardItem("ee_egitimkapsayici_info_98", "Engeller-6", "-Kelime ve heceleri tekrar edebilirler. Örneğin: “O-ol-maz”. \n-İsteklerini anlatmak yerine jest, mimik ya da başka türlü işaretleri kullanabilirler.\n-Disleksi (okuma güçlüğü), Disgrafi (yazma güçlüğü) yaşanabilir."),
      InfoCardItem("ee_egitimkapsayici_info_99", "Engeller-7", "Yazılı ya da sözlü dili anlamak ya da kullanabilmek için gerekli olan bilgi alma süreçlerinin birinde ya da birkaçında ortaya çıkan ve dinleme, konuşma, okuma, yazma, heceleme, dikkat yoğunlaştırma ya da matematiksel işlemleri yapmada yetersizlik nedeniyle, bireyin eğitim performansının ya da sosyal uyumunun olumsuz yönde etkilenmesi durumudur."),

        ]),
    InfoCardModel("Öğretimsel Engeller (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_100", "Öğretimsel Engeller", "Öğretmenin öğretimsel yöntemlerini olumsuz etkileyecek öğrenciler aşağıda verilmiştir.\n-Zihinsel Yetersizliği olan öğrenci\n-İşitme Yetersizliği olan öğrenci\n-Bedensel Yetersizliği olan öğrenci\n-Özel Öğrenme Güçlüğü olan öğrenci\n-Görme Yetersizliği olan öğrenci"),
      InfoCardItem("ee_egitimkapsayici_info_101", "Kaynaştırma Uygulaması İlkeleri", "Kaynaştırma/bütünleştirme uygulamaları temel olarak şu üç ilkeye dayanmaktadır. Bunlar\n-Müfredata erişim (bireysel farklılıklar temel alınarak), \n-Tam katılım, \n-Süreç temelli değerlendirme\n-Geleneksel öğretim yöntemlerinin kullanılması\n-Materyallerin uyarlanmaması\n-Uygun ortam düzenlemesinin yapılmaması"),
      InfoCardItem("ee_egitimkapsayici_info_102", "Müfredata erişim", "-Müfredatın amaçlarının ve içeriğinin engeli olan öğrencinin ihtiyaçlarına göre uyarlanması olarak tanımlanmaktadır.\n-Öğrencinin bireysel ihtiyaçlarına göre yapılacak bu düzenlemeler öğrencinin okul ile bağ kurmasını kolaylaştıracaktır.\n-Bu sayede öğrenci, öğrenmeleri için gerekli motivasyona sahip olacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_103", "Tam katılım", "-: Öğrencilerin ders içi etkinliklere diğer sınıf üyeleri gibi aktif şekilde katılımının sağlanması olarak tanımlanbilir.\n-Öğrenci sınıftan ayrıştırılmamalıdır.\n-Ayrıştırma, kendini değersiz hisseden bir öğrenci profili inşa edecektir.\n-Bu kapsayıcı eğitim anlayışında başarısız olmaya sebep olur.\n-Öğrencinin topluma kazandırılması ve diğer öğrencilerin özel eğitimli bireylerle birlikte yaşamaya alışmaları için birlikte hareket etmeleri sınıf için tam katılım ile başlar."),
      InfoCardItem("ee_egitimkapsayici_info_104", "Süreç temelli değerlendirme", "-Başarı ölçütü olarak standart öğrenme çıktılarına ulaşmak yerine, başlanılan yer ile ulaşılan yer arasındaki mesafenin esas alınması olarak tanımlanabilir.\n-Öğrencinin öğrenmeleri hemen gerçekleştirmesi beklenemez.\n-Öğrenmesini gerçekleştiremeyen öğrenci süreç içinde desteklenmezse sonuca ulaşamayacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_105", "Geleneksel öğretim yöntemlerinin kullanılması", "-Geleneksel öğretim yöntemleri, öğretim süreci içerisinde kullanılabilir.\n-Ancak, kalıplaşmış yöntemlerin dışına çıkmama gibi bir kararlılık gösterilmesi durumunda eğitimde yeni yaklaşımlar yakalanamaz.\n-Günümüz eğitim modellerinde, kapsayıcı eğitimi içine alan farklı birçok yöntemin kullanılmaması, onun yerine geleneksel yöntemlerinin uygulanması, öğretim sürecinin öğrenciye olan katkısını azaltacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_106", "Materyallerin uyarlanmaması", "-Sınıf ortamında öğrenmeleri gerçekleştirirken yardımcı materyallerin kullanılması öğrenmeyi direkt olarak etkileyen faktörlerdendir.\n-Kullanılacak materyallerin yalnızca belirli öğrenme düzeyinde bulunan öğrenciler için kullanılması diğer öğrencilerin öğrenmelerine katkı sağlamayacağı gibi öğrencilerin öğrencilerin yetersizlik duygularını pekiştirecektir."),
      InfoCardItem("ee_egitimkapsayici_info_107", "Uygun ortam düzenlemesinin yapılmaması", "-Öğrenme ortamı, öğrencilerin öğrenmelerini gerçekleştirdikleri mekan ve ortamlardır.\n-Etkili bir öğrenme ortamı düzenlemesi için tüm öğrencilerin özellikleri dikkate alınmalıdır.\n-Öğrenme ve öğretme hedefleri tespit edilmeli, öğrenmeyi destekleyici etkinlikler için uygun ortam sağlanmalıdır."),
        ]),
    InfoCardModel("Özel Eğitim Öğrencisinin Tespiti (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_108", "Süreç", "Özel eğitime ihtiyacı olan öğrencinin izlenmesi, değerlendirilmesi ve yönlendirmesi süreci aşağıdaki aşamaları kapsamaktadır.\n-İlk belirleme\n-Gönderme öncesi süreç\n-Gönderme süreci\n-Ayrıntılı değerlendirme\n-Karar verme\n-BEP hazırlama\n-Değerlendirme "),
      InfoCardItem("ee_egitimkapsayici_info_109", "İlk belirleme", "-Sınıf rehber öğretmeni öğrencinin okul süreci içerisinde engel türlerinden birisini karşıladığını düşünüyorsa öncelikle öğrenciyi takip etmesi gerekir.\n-Bu süreç içerisinde öğrenci davranışlarının ve performansının sınıf düzeyine olan uygunluğu izlenir.\n-Bilgi edinme süreci informal yollarla yapılır."),
      InfoCardItem("ee_egitimkapsayici_info_110", "Gönderme öncesi süreç", "-Öncelikle öğrenciye uygun sınıf içi düzenlemeler yapılmalıdır.\n-Öğrencinin bir ilerleme kaydedip kaydetmeme durumuna bakılmalıdır.\n-Örneğin, öğrenme etkinliklerinde öğrenciye uygun düzenlemeler yapılmasına rağmen öğrenme düzeyinde ilerleme kaydedilmezse bir sonraki aşamaya geçilmelidir."),
      InfoCardItem("ee_egitimkapsayici_info_111", "Gönderme süreci", " Eğer problemin sistematik olduğu gözlemlenmiş veya karar verilmişse hazırlanan gözlem raporu ile birlikte okul rehber öğretmenine başvuru yapılır.\n-Aile bilgilendirilerek onayı alınır.\n-Rehber öğretmen, okul idaresi ve öğrenci ailesi ile birlikte hareket eder.\n-Eğitsel Değerlendirme İsteği Formu hazırlanarak RAM’a gönderme kararı alınır."),
      InfoCardItem("ee_egitimkapsayici_info_112", "Ayrıntılı değerlendirme", "RAM'de öğrenci ayrıntılı incelemeye alınır.\n-Bu aşamada sadece varolan performans değerlendirilir.\n-Zihinsel performansı ölçülür.\n-Eğer işitme, görme engeli veya otizm, kronik hastalık gibi problemler tespit edilirse muayenesi için öğrenci hastaneye sevk edilir."),
      InfoCardItem("ee_egitimkapsayici_info_113", "Karar verme", "-Öğrencinin değerlendirilmesi tamamlandıktan sonra özel eğitime ihtiyacı olduğuna karar verilmişse, kaynaştırma öğrencisi olarak yerleştirilir.\n-Süreç en az kısıtlayıcı ortam ile sürdürülmelidir.\n-Bu kavram önemli olduğu için bir sonraki kartta bu kavram açıklanacaktır."),
      InfoCardItem("ee_egitimkapsayici_info_114", "En Az Kısıtlayıcı Ortam", "-Öğrencinin eğitim ve diğer alanlardaki gereksinimlerinin karşılanmasına yönelik düzenlemelerin yapıldığı, gelişiminin desteklendiği ve gerektiğinde özel eğitim destek hizmetlerinin de sağlandığı ortamlara denir.\n-Önemli olan özel eğitim gereksinimi olan bireyin mümkün olduğunca akranları ile eğitim görmesini sağlamaktır.\n-Bu sağlanırken eğitsel özellikler dikkate alınmalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_115", "BEP hazırlama", "-Öğrencinin yerleştirildiği okulda, ihtiyaçlarına yönelik olarak hazırlanan programdır.\n-Plan hazırlanırken varolan performansı göz önünde bulundurulur.\n-Programın hazırlanmasındaki amaç öğrencinin eğitim öğretim sürecinden en üst düzeyde faydalanmasını sağlamaktır."),
      InfoCardItem("ee_egitimkapsayici_info_116", "Değerlendirme", "-Öğrencinin özel eğitim almasına karar verildikten sonraki süreçten itibaren değerlendirme mutlaka yapılmalıdır.\n-Değerlendirme sonuç odaklı değil süreç odaklı yapılmalıdır.\n-Değerlendirme döngüsel olarak tekrarlanmalıdır.\n-Bu sayede BEP ne derece etkili olduğu tespit edilirken yanlış tanı ve uygulamalar da tespit edilmiş olur."),
      InfoCardItem("ee_egitimkapsayici_info_117", "BEP öncesi itiraz", "-Eğitsel değerlendirme sonucunda yerleştirme kararı alınan öğrencinin ailesinin itiraz hakkı saklıdır.\n-Öğretmenlerin de karara itiraz hakları bulunmaktadır.\n-İtiraz öğrencinin velisi, okul veya kurumdaki rehberlik psikolojik danışma komisyonu tarafından, öğrencinin kuruma kayıt tarihinden itibaren en 30 iş günü izleme süreci sonunda yapılabilir."),
    ]),
    InfoCardModel("Kaba Değerlendirme (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_118", "Kaba Değerlendirme Nedir?", "-Öğrencilerin eksik olduğu alanları tespit etmek için kullanılır.\n-Yaşına uygun olan becerilerden hangilerini yerine getirebildiği ölçülür.\n-Ayrıca öğrencinin programı takip düzeyi ile ilgili de bilgiler verir.\n-Uygulama zamanı öğretim öncesi süreçtedir."),
      InfoCardItem("ee_egitimkapsayici_info_119", "Kaba Değerlendirmenin Amacı", "-Öğrencilerin becerilerinin tespiti amacıyla yapılır.\n-Tespit edilen beceriler, sosyal beceriler, taklit becerileri, oyun becerileri, dil becerileri vb. çoğaltılabilir.\n-Öğretim öncesi süreçte yapılır.\n-Eğitsel değerlendirmenin yapılması amaçlardan bir tanesidir.\n-Ayrıca BEP planının hazırlanmasına katkı sağlar.\n-Süreç öncesinde yapıldığı için öğrencilerin ihtiyaçlarının tespiti amacıya da yapılabilir."),
      InfoCardItem("ee_egitimkapsayici_info_120", "Kullanılan Form-1", "-Bir tablo hazırlanır.\n-Hazırlanan tablonun bir bölümünde bildirimler, diğer bölümünde kazanımlar bulunur.\n-Bildirim harfleri yazar, sesleri tanır, noktalama işaretlerini kullanır gibi ifadeler içerir.\n-Buradaki tespitler bilip bilmemesi veya yapıp yapmaması gibi net sonuçlar verir.\n-Heceleri tanıma düzeyi, sesleri tanıma yüzdesi gibi bir duruma ne kadar hakim olduğunun tespiti yapılmaz."),
      InfoCardItem("ee_egitimkapsayici_info_121", "Kullanılan Form-2", "-Sütunda Evet/Hayır bölümü bulunur.\n-Gözlemlenen davranış eğer var ise + işareti konur, yok ise - işareti konur.\n-Ayrıca formda açıklamalar bölümü bulunur.\n-Gözlenen ek bir durum veya aileden gelecek bilgi paylaşımı vs. gibi durumlar buraya eklenir.\n-Değerlendirme yapılan durumun ses, ışık vs. gibi ortam düzeni de ayrıca not alınır."),
      InfoCardItem("ee_egitimkapsayici_info_122", "Değerlendirmede Dikkat Edilmesi Gerekenler-1", "-Sorgulanan veya gözlemlenen beceri bireyde var ise +, yok ise - işareti konur.\n-Değerlendirme sırasında bireye müdahale edilmemelidir.\n-Sorulara veya bildirimlere cevap verilirken bireye herhangi bir yardım yapılmamalı, herhangi bir cevaba yönlendirme yapılmamalıdır.\n-Verilen tepki veya cevaplara ilişkin pekiştireç kullanılmamalıdır."),
      InfoCardItem("ee_egitimkapsayici_info_123", "Değerlendirmede Dikkat Edilmesi Gerekenler-2", "-Değerlendirme, farklı zamanlarda en az 3 kez yapılmalıdır.\n-Özel eğitim alanında hazırlanan engeli olan çocuklara yönelik modüller genel eğitim okullarında görevli öğretmenler için de kullanılabilir.\n-Değerlendirmede aile görüşleri çok çok önem arz etmektedir.\n-Aile görüşlerine yer vermek çok önemlidir.\n-Öğretmende form yoksa kendi alanındaki öğretimsel amaçları zora doğru sıralayarak form hazırlayabilir."),
       ]),
    InfoCardModel("BEP Geliştirme Birimi (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_124", "Birim üyeleri", "-Birim başkanı (okul müdürü ya da görevlendireceği müdür yardımcısıdır)\n-Öğrencinin sınıf öğretmeni\n-Okul rehberlik öğretmeni\n-Özel eğitime ihtiyacı olan öğrenci\n-Öğrencinin velisi\n-Öğrencinin dersini okutan alan öğretmenleri\n-Gerektiğinde görüşlerine başvurmak üzere Özel Eğitim Değerlendirme Kurulu’ndan bir üye"),
      InfoCardItem("ee_egitimkapsayici_info_125", "Açıklamalar-1", "-Öğrencinin dersine giren tüm öğretmenler BEP geliştirme biriminin doğal üyesidir.\n-Performansı belirlenen öğrenci için hangi derslerden BEP hazırlanacağı BEP birimi tarafından karara bağlanır.\n-BEP planının öğrencinin ihtiyaç duyduğu alanda hazırlanması gerekir.\n-BEP ekibi başkanı ve Sınıf Öğretmeni/Sınıf Rehber Öğretmeni BEP raporunun saklanmasından sorumludur."),
      InfoCardItem("ee_egitimkapsayici_info_126", "Açıklamalar-2", "-Öğrencinin dersine giren tüm öğretmenler, kendi alanları veya dersleri ile ilgili performans almalıdırlar.\n-Öğrencinin dersine giren tüm öğretmenlere Eğitsel Değerlendirme Formu verilmelidir.\n-Form doldurularak bir nüshası saklanıp diğeri sorumlu kişiye verilmelidir.\n-BEP düzenlenen derslerde Bireyselleştirilmiş Eğitim Programı Formu düzenlenir.\n-Ders öğretmeni tarafından form doldurulup bir nüshası saklanarak sorumlu kişiye verilir."),
      InfoCardItem("ee_egitimkapsayici_info_127", "Etkili BEP Hazırlama-1", "-BEP hazırlarken kullanımı kolay bir format belirlenmelidir.\n-Birey ve ailesinin mümkün olduğunca sürecin içinde olduğundan emin olun. (Bireyin kendi amaçları ve hedefleri konusunda karar verme sürecine katılmak gerekir.)\n-BEP hazırlanırken BEP uygulamasına katılacak olanların BEP hazırlama sürecine aktif olarak katılmalarını sağlayın. (Uygulayıcının süreç başından sonuna kadar aktif olması önemlidir.)"),
      InfoCardItem("ee_egitimkapsayici_info_128", "Etkili BEP Hazırlama-2", "-BEP yazılırken açık ve anlaşılır bir dil kullanımına özen gösterin. (Bireyin durumu ve süreç açık ve anlaşılır şekilde ifade edilmelidir.) \n-BEP hazırlarken kısa ve öz ifadeler kullanmaya gayret edin. (Her detay ayrıntılı şekilde bulunmak zorunda değildir.) \n-Gerçekçi bir yaklaşım sergileyin. (Yıllarca sürecek bir planlama yapmak yerine 1 yılı kapsayan bir plan yapın)\n-BEP dosyası hazırlayın ve evrakları düzenli şekilde saklayın"),


            ]),
    InfoCardModel("Salamanca Bildirisi (Yeni)", [
    InfoCardItem("ee_egitimkapsayici_info_30", "Bilgiler", "-7-10 Haziran 1994 yılında İspanya'nın Salamanca kentinde bir araya gelinmiştir.\n-Toplantıya 92 devlet ile 25 uluslararası kuruluşun temsilcileri katıldı.\n-Toplantı, UNESCO ve İspanya Hükümeti işbirliği ile gerçekleşti.\n-Amaç, özellikle özel eğitim gerektiren çocuklar için okulları tüm çocuklara hizmet verecek şekilde düzenleyerek kapsayıcı eğitim yaklaşımı ile herkes için eğitim hedefine ulaşmaktı."),
    InfoCardItem("ee_egitimkapsayici_info_31", "Salamanca Bildirisi-1", "-Her çocuk, eğitim görme temel hakkına sahiptir.\n-Eğitim fırsatı verilmelidir.\n-Her çocuk, kendine özgü özelliklere, ilgi, yetenek ve öğrenme ihtiyaçlarına sahiptir\n-İhtiyaç çeşitliliği dikkate alınarak eğitim sistemleri düzenlenmeli ve eğitim programları gerçekleştirilmelidir.\n-Özel eğitim gereksinimli çocuklar eğitim öğretime devam edebilmelidir."),
    InfoCardItem("ee_egitimkapsayici_info_32", "Salamanca Bildirisi-2", "-Özel eğitim gereksinimi olan çocuklar, diğer çocuklardan ayırt edilmemelidir.\n-Normal okullar bu çocukların ihtiaçlarını karşılayan, çocuğu merkeze alan eğitim sistemini kullanmalıdır.\n-Ayırıcı tutumla mücadele edilmelidir.\n-Normal okullar, herkesi hoş karşılayan toplumun oluşturulmasında ve herkes için eğitimin başarılmasında en etkili araçtır.\n-Normal okullar çocukların çoğuna etkili bir eğitim sağlamaktadır."),
    InfoCardItem("ee_egitimkapsayici_info_33", "Hükümetlere Öneriler-1", "Bildiriye katılan hükümetlere öneriler;\n\n-Tüm çocukları kapsayacak eğitim sistemlerini geliştirmek amacıyla en üst politik ve bütçe önceliğini vermeleri gerekmektedir.\n-Zorlayıcı sebepler dışında tüm çocukların normal okullarda eğitim görmeleri sağlanmalıdır.\n-Kapsayıcı eğitimde ilerlemiş olan ülkelerin, kapsayıcı okullar ile ilgili bilgi alış verişinde bulunmaları teşvik edilmelidir."),
    InfoCardItem("ee_egitimkapsayici_info_34", "Hükümetlere Öneriler-2", "-Özel eğitim gereksinimi olan çocukların ve yetişkinlerin eğitim imkanları, planlama, kontrol ve değerlendirme için yerelleşmiş ve katılımcı mekanizmalar kurmaları desteklenmelidir.\n-Özel eğitim ihtiyaçlarının hazırlıklarının planlama ve karar verme süreçlerinde kuruluşlara katılımın sağlanmalıdır.\n-Mesleki yöndeki çalışmalara verilen desteklerin yanında erken tanı ve müdahalelerde de gayret sarfedilmelidir.\n-Bu kapsamda öğretmen yetiştirme programları hazırlanmalıdır."),
    InfoCardItem("ee_egitimkapsayici_info_35", "Tüm Kuruluşlara Çağrı", "-Toplantıya katılan tüm kurum ve kuruluşların kapsayıcı eğitim yaklaşımını onaylamalarını ve tüm eğitim programlarının tamamlayıcı bir parçası olmaları talep edilmiştir.\n-Kapsayıcı eğitimin imkanlarının planlanması, uygulanması ve değerlendirilmesinde katılımların güçlendirilmesi ve ulusal resmi organlarla işbirliğinin arttırılmasını talep etmiştir.\n-Öğretmenlerin ve öğretmenlik kuruluşlarının çalışmalarını arttırmaları istenmiştir."),

     ]),
    InfoCardModel("Eğitim Hakkına Dair Sözleşmeler (Yeni)", [
      InfoCardItem("ee_egitimkapsayici_info_68", "Hangileridir?", "Eğitim Hakkı ile ilgili uluslararası düzenlemeler aşağıda verilmiştir.\n\n-İnsan Hakları Evrensel Beyannamesi,\n-Avrupa İnsan Hakları Sözleşmesi,\n-Çocuk Haklarına Dair Sözleşme,\n-Eğitimde Ayrımcılığa Karşı Sözleşme"),
      InfoCardItem("ee_egitimkapsayici_info_69", "İnsan Hakları Evrensel Beyannamesi-1", "Eğitim hakkının geçtiği madde 26. maddedir. Bu madde aşağıda verilmiştir.\n\n-Herkes, eğitim hakkına sahiptir. Eğitim, en azından ilk ve temel öğrenim aşamalarında parasızdır. İlköğretim zorunludur. Teknik ve mesleki eğitim herkese açıktır. Yüksek öğrenim, yeteneğe göre herkese eşit olarak sağlanır.\n-Ana-babalar, çocuklarına verilecek eğitimi seçmede öncelikli hak sahibidir."),
      InfoCardItem("ee_egitimkapsayici_info_70", "İnsan Hakları Evrensel Beyannamesi-2", "-Eğitim, insan kişiliğinin tam geliştirilmesine, insan haklarına ve temel özgürlüklere saygıyı güçlendirmeye yönelik olmalıdır. Eğitim, bütün uluslar, ırklar ve dinsel gruplar arasında anlayış, hoşgörü ve dostluğu yerleştirmeli ve Birleşmiş Milletlerin barışı koruma yolundaki etkinliklerini güçlendirmelidir."),
      InfoCardItem("ee_egitimkapsayici_info_71", "Avrupa İnsan Hakları Sözleşmesi", "Eğitim hakkının geçtiği madde 2. maddedir. Bu madde aşağdıda verilmiştir.\n\n-Hiç kimse eğitim hakkından yoksun bırakılamaz. Devlet, eğitim ve öğretim alanında yükleneceği görevlerin yerine getirilmesinde, ana ve babanın bu eğitim ve öğretimin kendi dini ve felsefi inançlarına göre yapılmasını sağlama haklarına saygı gösterir."),
      InfoCardItem("ee_egitimkapsayici_info_72", "Çocuk Haklarına Dair Sözleşme", "Eğitim hakkının geçtiği madde 29-30. maddelerdir. Bu maddeler aşağdıda verilmiştir.\n\n-Çocuklara verilen eğitim onların gelişimlerini en fazla ölçüde sağlayacak düzeyde olmalıdır. Eğitim, çocukların hoşgörüsünü, kendi kültürüne ve farklı kültürlere saygısını, ayrımcılığa karşıtlığını, doğaya saygısını arttıracak biçimde düzenlenir. Çocuğun kendi kültürü, bulunduğu ülkedekinden farklıysa gelişim ve eğitim hakkının her aşamasında buna gereken özen gösterilir."),
      InfoCardItem("ee_egitimkapsayici_info_73", "Eğitimde Ayrımcılığa Karşı Sözleşme", "-Bu sözleşmede eğitim hakkı ile ilgili birçok madde bulunmaktadır.\n-Bu yüzden daha ayrıntılı olarak bir sonraki bölümde işlenmiştir."),

    ]),InfoCardModel("Eğitimde Ayrımcılığa Karşı Sözleşme (Yeni)", [
    InfoCardItem("ee_egitimkapsayici_info_37", "Genel Bilgiler", "-UNESCO tarafından 14 Aralık 1960 tarihinde kabul edilmiştir.\n-Toplantı Paris'te yapılmıştır.\n-Temelde İnsan Hakları Evrensel Beyannamesi’nin ayrımcılık yasağı ilkesini esas alır.\n-UNESCO Kurucu Belgesi'ndeki , uluslar arasında eğitimde fırsat eşitliği ve insan haklarına evrensel saygının geliştirilmesi konusunda işbirliği yapılması amacını taşır.\n-Herkes için eğitimde fırsat ve muamele eşitliğini teşvik etme görevini kabul eder."),
    InfoCardItem("ee_egitimkapsayici_info_38", "Madde 1", "-Bu Sözleşme’nin amacı bakımından “ayrımcılık” terimi; ırk, renk, cinsiyet, dil, din, siyasi veya başka bir görüş, ulusal veya toplumsal köken, ekonomik koşul ya da doğum temeline dayanan, eğitimde muamele eşitliğini engelleyen veya ortadan kaldıran veya bunu amaçlayan ve özellikle;\n-Herhangi bir kişiyi ya da grubu her düzeyde ya da herhangi bir türde eğitime erişimden mahrum bırakmak\n-Herhangi bir kişiyi ya da grubu, daha düşük standartta bir eğitime sınırlamak,"),
    InfoCardItem("ee_egitimkapsayici_info_39", "Madde 1 Devamı", "-Bu Sözleşme’nin 2. maddesinin hükümleri saklı kalmak üzere kişiler ya da gruplar için ayrı eğitim sistemleri veya kurumları kurmak ya da sürdürmek; ya da\n-Herhangi bir kişi ya da grubu, insan onuruyla bağdaşmayan koşullara maruz bırakmak üzere yapılan herhangi bir dışlama, dışarıda bırakma, sınırlama veya tercihi içerir.\n-“eğitim” terimi eğitimin tüm tür ve seviyelerini kasteder ve eğitime erişimi, eğitimin kalitesini ve standartlarını ve hangi koşullar altında verilmesi gerektiğini içerir."),
    InfoCardItem("ee_egitimkapsayici_info_40", "Madde 2", "Bir Devlet tarafından izin verilmesi halinde, aşağıdaki durumlar bu Sözleşme’nin 1. maddesi anlamında ayrımcılık oluşturmayacaktır:\n-Eğitim, materyal ve diğer tüm koşullarda eşit imkanlar sunmak şartıyla her iki cinsiyetten öğrenciler için ayrı eğitim kurumları tasarlamak,\n-Veli iznine bağlı olarak din ve dil gerekçeleriyle ayrı kurumlarda eğitim verilmesi,\n-Özel eğitim kurumlarının kurulması veya sürdürülmesi."),
    InfoCardItem("ee_egitimkapsayici_info_41", "Madde 3", "Taraf Devletler;\n-Ayrımcılık içeren her yasa ve idari talimat kaldırılmayı,\n-Eğitim kurumlarında alımlarda ayrım yapmamayı,\n-Okul ücretleri, burs veya diğer yardımlarda uyruklar arası ayrım yapmamayı,\n-Öğrencilere belli bir gruba dahil olmaları sebebiyle olumlu veya olumsuz ayrım yapmamayı,\n-Yabancı uyruklulara da aynı eğitim hakkını sağlamayı taahhüt eder."),
    InfoCardItem("ee_egitimkapsayici_info_42", "Madde 4", "-İlköğretimin ücretsiz ve zorunlu, ortaöğretimin genellikle herkesin yararlanabileceği, yükseköğrenimin ise bireysel yetenek temelli ve herkesin eşit olarak erişebileceği şekilde düzenlemeyi,\n-Aynı düzeydeki tüm kamu eğitim kurumlarının eşdeğer olmasını,\n-İlköğretim görmeyen kişilerin eğitm görmesini ve eğitimlerini devam ettirmesini,\n-Ayrımcılık gözetmeksizin öğretim mesleği için ulusal politika belirlemeyi, geliştirmeyi ve uygulamayı taahhüt eder."),
    InfoCardItem("ee_egitimkapsayici_info_43", "Madde 5", "Sözleşmede Taraf Devletlerin anlaştıkları konular\n-Tüm ulus, din ve kültürleri desteklemeli, Birleşmiş Milletler’in barışın korunması yolundaki etkinliklerini daha da ileri götürmelidir.\n-Devlet kurallarına uymak şartıya aileler, velisi bulundukları çocuğu inançlarına uygun şekilde din ve ahlam eğitimi almasını sağlamalıdır.\n-Kişinin kendi inancıyla bağdaşmayan din eğitimini almaya mecbur bırakılmaması temel ilkedir.\n-Ancak bu durum ulusal egemenliğe zarar verecek biçimde kullanılamaz."),
    InfoCardItem("ee_egitimkapsayici_info_44", "Madde 6", "Taraf Devletler, bu Sözleşme’yi uygularken, bundan böyle eğitimde ayrımcılığın farklı biçimlerine karşı ve eğitimde fırsat ve muamele eşitliğini güvence altına almaya yönelik alınacak önlemleri saptamak amacıyla Birleşmiş Milletler Eğitim, Bilim ve Kültür Kurumu Genel Konferansı tarafından benimsenen tavsiyelere en büyük özeni göstermeyi taahhüt ederler."),

    ]),
    /*InfoCardModel("Eğitimde Ayrımcılığa Karşı Sözleşme (Yeni)", [
       //"Konular", "-Kapsayıcı eğitim, din, dil, ırk, yerleşim yeri, sağlık durumu, ekonomik yeterlilikler, cinsiyet vs. gibi birçok durumun eğitim hakkına engel olmaması için düzenlenen bir süreçtir.\n-Çocuk haklarının gereği ve toplumsal kalkınmanın en önemli koşullarından birisidir.\n-Kapsayıcı eğitimin ele aldığı temel konulara ayrıntılı olarak göz atalım."),



    ]),*/
    /*InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),*/

    /*InfoCardModel("", [
 InfoCardItem("ee_egitimkapsayici_info_5", "", ""),








 InfoCardItem("ee_egitimkapsayici_info_129", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_130", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_131", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_132", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_133", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_134", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_135", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_136", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_137", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_138", "", ""),
      InfoCardItem("ee_egitimkapsayici_info_139", "", ""),


    ])*/
  ];
