import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';


class EgitimInfoViewModel {
  List<InfoCardModel> _egitimOgretimInfoCard = [
    InfoCardModel("Eğitim Psikolojisi", [
      InfoCardItem("eo_Info_1","Eğitim","-İnsan davranışlarının bir plan çerçevesinde değiştirilmesi ve geliştirilmesi çalışmasına eğitim denir.\n-Eğtim süreç gerektirir.\n-Eğitim alan bireylerden topluma ve insanlığa faydalı davranışlar sergilemeleri beklenir."),
      InfoCardItem("eo_Info_2","Psikoloji","-İnsan davranışlarını ve davranışlarının altında yatan sebepleri inceler.\n-Davranışlar bilinç dışı süreçlerde kayıtlı bazı olay ve olgular sebebiyle sergileniyor olabilir.\n-Bu olay ve olgular tespit edilerek bireyin olumlu yönde gelişmesi sağlanabilir."),
      InfoCardItem("eo_Info_3","Eğitim Psikolojisi","-Eğitim ve psikoloji davranış odaklıdır.\n-Psikoji biliminin eğitim odaklı uygulanması olarak da tanımlanabilir.\n-Gelişim ve öğrenme psikoloji ile ortak noktaları bulunur.\n-Öğrenme süreci, öğrenmeyi etkileyen faktörler, sınıf yönetimi, değerlendirme ve okul-veli-öğrenci ilişkileri gibi alanları inceler."),
      InfoCardItem("eo_Info_4","Eğitim Bilimi","Eğitim kavramını inceleyen bilim dallarının genelini kapsar.\n-Birçok disiplini içinde barındırır.\n-Ölçme ve Değerlendirme, Eğitim Programları ve Öğretim, Eğitim Felsefesi, Öğretim Teknolojisi, Eğitim Psikolojisi, Rehberlik gibi alanlar Eğitim Bilimleri içerisinde değerlendirilir."),
      InfoCardItem("eo_Info_5","ZEKA KURAMLARI-1","Matematiksel Zeka: Neden sonuç ilişkisi kurar.", ),
      InfoCardItem("eo_Info_6","ZEKA KURAMLARI-2","Uzamsal Zeka: Boşluğu zihinde canlandırma yeteneğine sahiptir.", ),
      InfoCardItem("eo_Info_7","ZEKA KURAMLAR-3","Bedensel Zeka: Bedeni duyarlı ve etkili kullanır.", ),
      InfoCardItem("eo_Info_8","ZEKA KURAMLARI-4","Müzik Zekası: Ritim algılama ve tekrar yaratmada ustadır. ", ),
      InfoCardItem("eo_Info_9","ZEKA KURAMLARI","Sosyal Zeka: Diğer insanları anlama yeteneği vardır. ", ),
      InfoCardItem("eo_Info_10","ZEKA KURAMLARI","Benlik Zekası: Kendi duygu ve düşüncelerinin farkındadır. ", ),
      InfoCardItem("eo_Info_11","ZEKA KURAMLARI","Doğa Zekası: Doğayı yakalama yeteneği vardır. ", ),
      InfoCardItem("eo_Info_12","ZEKA KURAMLARI","Sözel-Dilsel Zeka: Sözel becerileri güçlüdür. ", ),
      InfoCardItem("eo_Info_13","ÖĞRENME STİLLERİ","Görsel Öğrenme \n İşitsel Öğrenme \n Dokunsal Öğrenme ", ),
    ]),

    InfoCardModel("Öğretim Yöntem ve Teknikleri", [
      InfoCardItem("eo_Info_14","Yeni Programın Temel Becerileri","-Eleştirel, yaratıcı düşünme\n-İletişim Becerileri\n-Araştırma-sorgulama\n-Problem çözme\n-Bilgi teknolojilerini kullanma\n-Girişimcilik, \n-Türkçeyi doğru ve etkili kullanma", ),
      InfoCardItem("eo_Info_15","Yapılandırmacı Yaklaşım","-Öğrenme zihinde gerçekleşen içsel süreçtir.\n-Edilgen değil etkendir.\n-Öğrenci merkezlidir.\n-Bilgiyi kendisi anlamlandırır.\n-Bilgi öğrenen tarafından olduğu gibi alınmaz yeniden keşfedilir.", ),
      InfoCardItem("eo_Info_16","Disiplinler Arası Yaklaşım","-Öğrenci etkinliklerde aktiftir.\n-Diğer derslerle etkileşim içindedir.", ),
      InfoCardItem("eo_Info_17","Buluş Yoluyla Öğretim","-Bruner geliştirdi.\n-Yaparak, yaşayarak öğrenmeyi esas alır.\n-Öğrenci merkezlidir.\n-Öğrenme merak uyandıran problem ile başlar.\n-Tartışma, örnek olay, soru-cevap, münazara teknikleri vardır.", ),
      InfoCardItem("eo_Info_18","Araştırma ve İncelemeye Dayalı Öğretim","-Araştırma ve inceleme yapan öğrencidir.\n-Öğretmen ilgi çeken soru bulur.\n-Öğrenci araştırma ve problem çözmeyi öğrenir.", ),
      InfoCardItem("eo_Info_19","Yaparak Yaşayarak Öğrenme","-Öğrenci etkindir.\n-Problem çözer.\n-Analiz-sentez yapar.\n-Sorumluluk alır.", ),
      InfoCardItem("eo_Info_21","Çoklu Zeka Kuramı","-Grander ortaya koydu.\n-Zeka çok yönlüdür.\n-Doğuştan gelne zeka geliştirilebilir.", ),
      InfoCardItem("eo_Info_22","İşbirliğine Dayalı Öğrenme","-Öğrencilerin küçük gruplar halinde çalışır.\n-Öğrenmede birbirlerine yardım eder.\n-Öğretmen yönlendirir, öğrenci materyal hazırlar.\n-Başarı gruba aittir.", ),
      InfoCardItem("eo_Info_23","Proje Tabanlı Öğrenme","-Öğrenci merkezli.\n-Tasarı geliştirme, hayal etme ve kurgulamaya dayalı öğrenme.\n-Portfölye değerlendirmesi.", ),
      InfoCardItem("eo_Info_24","Probleme Dayalı Öğrenme","-İçerik merkezlidir.\n-Gerçek yaşam olaylarını içerir.\n-Öğretmen öğrenci gereksinimlerini karşılar.\n-Öğrenciler 3-7 kişilik gruplarla çalışır.\n-Öğrenciler düşünmeye yönlendirilir.\n-Hata ve eksikleri öğrenci belirler.", ),
      InfoCardItem("eo_Info_25","Beyin Temelli Öğrenme","-Öğrenci neden-nasıl öğrendiğini bilir.\n-Bireyler bilgilerini yapılandırır.\n-Öğrenci problem belirleyebilir ve çözüme odaklanır.", ),
      InfoCardItem("eo_Info_26","Etkin Öğrenme","-Öğrenme sürecinin sorumluluğu öğrencidedir.\n-Bireysel farklılıklara duyarlıdır.\n-İşbirlikçi öğrenme, çoklu zeka ve probleme dayalı öğrenme kullanılır.", ),
      InfoCardItem("eo_Info_27","Beyin Fırtınası","-Tartışılacak konu seçilir.\n-Herkes söz alır, tek fikir söyler.\n-Fikri olmayan pas der.\n-Fikirler yargılanmaz, çok düşünce üretmeye çalışılır.\n-Oylama yapılarak uygun fikir seçilir.", ),
      InfoCardItem("eo_Info_28","Özel Eğitim Gerektiren Bireyin \nNormal Sınıflarda Eğitimi","-Diğer bireylerle eğitsel performansları değerlendirilerek eğitilir.\n-Destek eğitimleri verilir.\n-Öğrencinin sınıf tarafından kabulü sağlanır.\n-Bireysel program uygulanır ve bireysel sınav yapılır.", ),
    ]),
    InfoCardModel("Sınıf Yönetimi", [
      InfoCardItem("eo_Info_29","Sınıf Yönetim Modelleri","-Geleneksel Model.\n-Tepkisel Model.\n-Önlemsel Model.\n-Gelişimsel Model.\n-Bütünsel Model",),
      InfoCardItem("eo_Info_30","Geleneksel Model","-Öğretmen merkezlidir.\n-Kuralı öğretmen belirler.\n-Öğrenci sorgusuz uygular.\n-Öğretmen bilgiyi aktarır öğrenci uygular.",),
      InfoCardItem("eo_Info_31","Tepkisel Model","-Hedef, istenmeyen davranışı değiştirmektir..\n-Ödül ceza içerir.\n-Öğretmen bireyin davranışına yönelir.",),
      InfoCardItem("eo_Info_32","Önlemsel Model","-İstenmeyen davranış ortaya çıkmadan önlemeyi hedefler.\n-Gruba yöneliktir.",),
      InfoCardItem("eo_Info_33","Gelişimsel Model","-Öğrencinin gelilşim özelliklerini dikkate alır.",),
      InfoCardItem("eo_Info_34","Bütünsel Model","-Sınıf yönetimine öncelik verir.\n-Gruba olduğu kadar bireye de yönelir.\n-Olaylar karşısında diğer modelleri de kullanabilir.",),
    ]),
    InfoCardModel("Davranış Problemlerinin Nedenleri", [
      InfoCardItem("eo_Info_35","Öğretmen Kaynaklı","-Pekiştireç kullanmaması.\n-Öğrencilerin bireysel farklılıklarını dikkate almaması.\n-Cezayöntemi kullanması.\n-Gelişim özelliklerini dikkate almaması.\n-Derse hazırlıksız gelmesi.\n-Kuralları öğrencilerle birlikte koymaması",),
      InfoCardItem("eo_Info_36","Sınıf Kaynaklı","-Oturma biçimi.\n-Isı, ışık.\n-Temizlik.\n-Öğrenci sayısı",),
      InfoCardItem("eo_Info_37","Öğrenci Kaynaklı","-Kişilik yapısı.\n-Psikolojik özellikler.\n-Başarı algısı.\n-Okula, sınıfa, derse ve öğretmene karşı tutumu",),
      InfoCardItem("eo_Info_38","Okuldan Kaynaklı","-Okula kurallarının baskıcı olması.\n-Fiziksel alanın yetersizliği.\n-Oyun alanının olmaması.\n-Okuldaki bireylerin öğrencilerle iletişimi",),
      InfoCardItem("eo_Info_39","Aileden Kaynaklı","-İlgi ve sevgi eksikliği.\n-Geçimsizlik.\n-Ekonomik ve sosyal sorunlar.\n-Baskıcı tutum.\n-Kalabalık olması",),
      InfoCardItem("eo_Info_40","Çevreden Kaynaklı","-Tv, internet, akıllı telefon.\n-Akranlarının davranışları.\n-Çevre kültürü",),
      InfoCardItem("eo_Info_41","Sınıftaki Davranış Problemleri","-Derse gelmeme veya geç gelme.\n-Derse hazırsıksız gelme.\n-Derste konuşma.\n-Kurallara uymama.\n-Hreketlilik.\n-Yalan söyleme.\n-Arkadaş veya eşyalara zarar verme",),
      InfoCardItem("eo_Info_42","Davranış Problemlerine Çözümler","-Öğretim etkinliğinde değişiklik.\n-Öğrencilere yardımcı olma.\n-Sınıf düzenini değiştirme.\n-Dikkat dağıtan unsurları kaldırma.\n-Umursamama.\n-Doğru davranışları takdir etme.\n-Öğrencilerin yerlerini düzenleme",),

    ]),
    InfoCardModel("İletişim", [
      InfoCardItem("eo_Info_43","Kaynak","-İletişimi başlatan kişidir.\n-İletişimi kuvvetlidir.",),
      InfoCardItem("eo_Info_44","İleti","-Kaynak tarafından aktarılan duygu ve düşünceler.\n-Anlaşılır, net ve zamana uygun olmalıdır.",),
      InfoCardItem("eo_Info_45","Kanal","-İletiyi aktaran bağdır.\n-Kitap, öğretmen ve malzemedir.",),
      InfoCardItem("eo_Info_46","Alıcı","-İletinin ulaştığı kişidir.",),
      InfoCardItem("eo_Info_47","Dönüt","-Alıcının iletiye verdiği tepki.\n-İletinin anlaşılıp anlaşılmadığı",),
      InfoCardItem("eo_Info_48","İletişim Güçlüğü Nedenleri","-Kırgın olmak.\n-Utanmak.\n-Korkmak.\n-Hedef olmaması",),
      InfoCardItem("eo_Info_49","İletişim Engelleri","-Emretmek.\n-Uyarmak.\n-Ahkam kesmek.\n-Nasihat vermek.\n-Dalga geçmek",),
      InfoCardItem("eo_Info_50","Öğrenci Davranışlarını Etkileyen\nSosyal Faktörler","-Ailenin ekonomik ve kültürel durumu.\n-Okuldaki birey tutumları.\n-Eğitim-öğretimi teknikleri.\n-Toplumun kültürel özellikleri",),
      InfoCardItem("eo_Info_51","Öğrenci Davranışlarını Etkileyen\nPsikolojik Faktörler","-Öğrencilerin sosyal, kültürel, ekonomik özellikleri.\n-Başarı ve bilgi durumları.\n-Öğretmenin mesleki ve klasik özellikleri",),
    ]),

    InfoCardModel("Sınıf Kuralları Geliştirme", [
      InfoCardItem("eo_Info_52","Conter Modeli","-Disiplin anlayışını savunur.\n-Cezaya başvurur.\n-Öğrencilerden aynı başarı beklenir.",),
      InfoCardItem("eo_Info_53","Kounin Modeli","-Grup yönetimine dayanır.\n-Öğretmen yanlış davranışlarda etkindir.",),
      InfoCardItem("eo_Info_54","Glasser Modeli","-Öğrenciyi birey olarak görür.\n-İstenmeyen davranışların sorumlusu öğrencidir.\n-Sorunları grup toplantılarıyla çözer.",),
      InfoCardItem("eo_Info_55","Etkili Öğretmenlik Eğitimi Modeli","-Thomas Garden tarafından geliştirilmiştir.\n-Sorunun kime ait olduğu belirlenir.\n-Sorun çözümünde kazan-kazan uygulanır.\n-Süreçte öğretmen ve öğrenci kazanması beklenir.",),
      InfoCardItem("eo_Info_56","Mantıksal Sonuçlar Modeli","-İç denetimin oluşması hedeflenir.\n-Öğrenci davranışlarından sorumludur.\n-Gerçek yaşama uygun öğretim yaşantıları sunulur.",),
      InfoCardItem("eo_Info_57","Sınıf Kuralı Oluştururken\nDikkat Edilmesi Gerekenler","-Gerçekle uyumlu olmalı.\n-Az olmalı.\n-Olumlu, kısa ve net olmalı.\n-Öğrenciyle oluşturulmalı.\n-Yaptırım belirlenmeli.",),
      InfoCardItem("eo_Info_58","Sınıfta Zaman Kullanımı","-Uygun plan ve öğretim teknikleri kullanılmalı.\n-Öğretmen hazırlıklı gelmeli.\n-Sınıf kuralları önceden oluşturulmalı.",),
    ]),
    InfoCardModel("Program Geliştirme-1", [
      InfoCardItem("eo_Info_59","Temel Kavramlar","Eğitim: İstenilen davranışların oluşmasıdır.",),
      InfoCardItem("eo_Info_60","Temel Kavramlar","İnformal Eğitim: Plansız, kendiliğinden gelişir. Gözlem ve taklit yoluyla öğrenilir.",),
      InfoCardItem("eo_Info_61","Temel Kavramlar","Formal Eğitim: Amaçlı ve planlıdır. Eğitim kontrollüdür, öğretmen tarafından uygulanır ve değerlendirme yapılır.",),
      InfoCardItem("eo_Info_62","Temel Kavramlar","Öğreme: Kalıcı izli davranış değişikliğidir. Yaşantı ürünü olmalıdır.",),
      InfoCardItem("eo_Info_63","Temel Kavramlar","Eğitim Programı: Planlı etkinliklerle sağlanan öğrenme yaşantıları düzeneğidir.",),
      InfoCardItem("eo_Info_64","Temel Kavramlar","Öğretim Programı: Bir dersin öğretimi ile ilgili etkinlikleri kapsayan düzenektir.",),
      InfoCardItem("eo_Info_65","Temel Kavramlar","Ders Programı: Bir derste planlanan hedeflerin nasıl yapılacağını gösteren plandır.",),
    ]),

    InfoCardModel("Program Geliştirme-2", [
      InfoCardItem("eo_Info_66","Program Geliştirme İlkeleri","Eğitimin sosyal işlevi dikkat edilmelidir.",),
      InfoCardItem("eo_Info_67","Program Geliştirme İlkeleri","Bireylerin gelişim özelliklerine dikkat edilmelidir.",),
      InfoCardItem("eo_Info_68","Program Geliştirme İlkeleri","Amaçlar gereksinimleri karşılanmalıdır.",),
      InfoCardItem("eo_Info_69","Program Geliştirme İlkeleri","Amaçlar tutarlı olmalıdır.",),
      InfoCardItem("eo_Info_70","Program Geliştirme İlkeleri","İçerik hazırlandığında nesnel olunmalıdır.",),
      InfoCardItem("eo_Info_71","Program Geliştirme İlkeleri","Sosyal, kültürel, ekonomik koşullara uyulmalıdır.",),
      InfoCardItem("eo_Info_72","Program Geliştirme İlkeleri","İlgili herkes sürece katılmalıdır.",),
      InfoCardItem("eo_Info_73","Program Geliştirme Süreci","Planlama, uygulama ve değerlendirmeden oluşur.",),
      InfoCardItem("eo_Info_74","Program Geliştirme Süreci","Planlamada gruplar oluşturulur, gereksinimler saptanır, öğretim süreci ve değerlendirme aşamaları belirlenir.",),
      InfoCardItem("eo_Info_75","Program Geliştirme Süreci","Uygulamada plan yapılır. Öğretim süreci oluşturulur ve programın uygulanması sağlanır.",),
      InfoCardItem("eo_Info_76","Program Geliştirme Süreci","Değerlendirmede sınama yapılır.",),
      InfoCardItem("eo_Info_77","Eğitim Programı Konuları","-İşe dönük olmalı.\n-Esnek olmalı.\n-Beklenti karşılanmalı.",),
    ]),

    InfoCardModel("Program Geliştirme-3", [
      InfoCardItem("eo_Info_78","Program Hazırlama","-Gereksinim belirleme,\n-Amaç,\n-İçerik,\n-Eğitim durumları,\n-Değerlendirme",),
      InfoCardItem("eo_Info_79","Gereksinim Belirleme","-Öğrencinin gereksinimi;\n  -İnsani gereksinim,\n  -Ulusal gereksinim,\n  -Yaşadığı bölgeye ait gereksinim, \n  -Bulunduğu eğitim kademesine göre gereksinim içerir.",),
      InfoCardItem("eo_Info_80","Gereksinim Belirleme","-Toplumun gereksinimi; \n  -Toplum, \n  -Devlet, \n  -Uluslararası faktörleri ele alır.",),
      InfoCardItem("eo_Info_81","Amaç","-Kazandırılması uygun özelliktir.\n-Uzaktan, genel, özel ve davranışsal amaç olarak sınıflanır.",),
      InfoCardItem("eo_Info_82","Uzaktan Amaç","-Ülke düzeyindekli amaçlardır.\n-Soyut dil kullanılır.\n-Milli Eğitim Temel Kanundaki amaçlar örnektir.",),
      InfoCardItem("eo_Info_83","Genel Amaçlar","-Belli eğitim kademesindeki okulların amaçlarıdır.\n-İdeal insan niteliğinden meydana gelir.\n-İlköğretim kurumlarının amaçları örnektir.",),
      InfoCardItem("eo_Info_84","Özel Amaçlar","Belirli bir ders veya konuya yönelik amaçlardır.\n-6.Sınıf Türkçe dersinin amaçları örnektir.",),
      InfoCardItem("eo_Info_85","Davranışsal Amaçlar","Bir dersin bir bölümüne yönelik amaçlardır.\n-Bir ders saatinde gerçekleşen etkinlikler örnektir.",),
      InfoCardItem("eo_Info_86","Özel Amaçlar Davranışsal Davranışlara \nDönüşürken Dikkat Edilmesi Gerekenler","Davranış; gözlenebilir, ölçülebilir, kapsamlı, sınırları belli olmalıdır. Davranışlarda belli bir amaç olmalıdır. ",),
      InfoCardItem("eo_Info_87","Amaçların Yararları","-Okulun rolünü belirler.\n-Rehberlik eder.\n-Değerlendirmede temel ölçütleri belirler.\n-Programın geliştirilmesini sağlar.",),
    ]),
    InfoCardModel("Program Geliştirme-4", [
      InfoCardItem("eo_Info_88","İçerik Düzenleme Yaklaşımları","-Doğrusal,\n-Sarmal,\n-Piramitsel,\n-Konuağı-proje merkezli,\n-Sorgulama merkezli\n-Modüler,\n programlama yaklaşımları kullanılır.",),
      InfoCardItem("eo_Info_89","Doğrusal Programlama","-Birbiriyle yakın ilişkili konuların düzenlenmesinde kullanılır,\n-Aşamalılık özelliği olan derslerde kullanılır.",),
      InfoCardItem("eo_Info_90","Sarmal Programlama","-Konuların yeri geldikçe tekrar öğretilmesinde kullanılır,\n-Dil öğretiminde kullanıma elverişlidir.",),
      InfoCardItem("eo_Info_91","Piramitsel Programlama","Geniş tabanlı konulardan giderek uzmanlaşmanın daraldığı içerik düzenlemedir.(Piramit şekli)",),
      InfoCardItem("eo_Info_92","Konuağı-Proje Merkezli Programlama","-Konular harita gibi hazırlanır,\n-Ne zaman hangi konuda olacağı söylenir,\n-Tek ya da grup olarak içeriğe öğrenci karar verir.",),
      InfoCardItem("eo_Info_93","Sorgulama Merkezli Programlama","-İçeriği öğrenci soruları belirler.\n-Öğrencinin ihtiyaçlarına yanıt verir.",),
      InfoCardItem("eo_Info_94","Modüler Programlama","-Üniteler kendi içlerinde bütün oluşturduğunda kullanılır.\n-İçerik modüllere ayrılarak hazırlanır.\n-Modüler farklı yaklaşımlar oluşturulabilir.",),
    ]),
    InfoCardModel("Program Geliştirme-5", [
      InfoCardItem("eo_Info_95","","Öğrenme Öğretme Sürecinin Düzenlenmesinde Uyulması Gerekenlere Göz atalım",),
      InfoCardItem("eo_Info_96","Eğitim Durumları","-Amaçlarla uyumlu olmalı,\n-Öğrenci düzeyine uygun olmalı,\n-Öğrenciyi sürece katmaya heveslendirmeli,\n-İstenmeyen sonuçlar çıkarmamalı,\n-Ekonomik olmalı,\n-Tutarlı olmalı",),
      InfoCardItem("eo_Info_97","Değerlendirme","-İstenilen davranışların kazanılıp kazanılmadığının tespitidir.\n-Öğrencinin davranışı ne kadar kazandığı, programın başarısı ve öğretmen yeterliliği hakkında bilgi verir.",),
      InfoCardItem("eo_Info_98","Bilişsel Alan Alt Basamakları","-Bilgi,\n-Kavrama,\n-Uygulama,\n-Analiz,\n-Sentez,\n-Değerlendirme",),
      InfoCardItem("eo_Info_99","Duyuşsal Alan Alt Basamakları","-Alma,\n-Tepkide Bulunma,\n-Değer verme,\n-Örgütleme,\n-Kişilik hanile getirme",),
      InfoCardItem("eo_Info_100","Psikomotor Alan Alt Basamakları","-Algılama,\n-Kurulma,\n-Klavuzla yapma,\n-Mekanikleşme,\n-Beceri haline getirme,\n-Duruma uyma,\n-Yaratma",),
    ],
    ),
    ///ölçme değerlendirme
 /*   InfoCardModel("Ölçme ve Değerlendirme-1", [
      InfoCardItem("eo_Info_101","","Ölçme; varlıkların bir niteliğe ne derece sahip olduklarının gözlemlenip sembolleştirilmesidir. Doğrudan ölçme ve Dolaylı ölçme olarak 2 çeşittir.",),
      InfoCardItem("eo_Info_102","Doğrudan Ölçme","Ölçülecek niteliğin doğrudan gözlemlenmesidir. Örn: Deney yapan öğrenciye puan vermek",),
      InfoCardItem("eo_Info_103","Dolaylı Ölçme","Ölçülen özellik ile ölçmede kullanılan aracın özelliği birbirinden farklıdır. Örn: Termometre ile sıcaklık ölçmek",),
      InfoCardItem("eo_Info_104","Ölçek","Ölçme işleminde ölçekler kullanılır. 4 çeşittir; \n-Sınıflama,\n-Sıralama,\n-Eşit aralıklı,\n-Oranlı",),
      InfoCardItem("eo_Info_105","Sınıflama Ölçeği","Ölçülecek nesnelerin belli özelliklere göre sınıflandırılan ölçektir. Benzerlikleri ve farklılıkları gösterir. Örn: Erkekler ile kızların gruplandırılması",),
      InfoCardItem("eo_Info_106","Sıralama(Derecelendirme) Ölçeği","Nesneleri özelliklerinin miktarına göre sıralayan ölçektir. Örn: Öğrenci başarılı/başarısız deniyorsa sıralama ölçeği vardır.",),
      InfoCardItem("eo_Info_107","Eşit Aralıklı Ölçek","Nesneleri özelliklere göre sıralayan ölçektir. Sonucun 0 olması o niteliğin olmadığı anlamına gelmez. Örn: Termometre",),
      InfoCardItem("eo_Info_108","Oranlı Ölçek","-Başlangıç noktası gerçek sıfırdır.\n-En gelişmiş ölçektir.\n-Örn: Metre, Terazi",),
    ]),

    InfoCardModel("Ölçme ve Değerlendirme-2", [
      InfoCardItem("eo_Info_109","Değerlendirme","Ölçme sonuçlarının bir ölçüte göre karşılaştırılıp karara varılmasıdır.",),
      InfoCardItem("eo_Info_110","Değerlendirme-2","-Ölçmeyi içine alır.\n-Önce ölçme, sonra değerlendirme yapılır.\n-Ölçme nesneldir.\n-Değerlendrime öznel olabilir.",),
      InfoCardItem("eo_Info_111","Değerlendirme-3","Değerlendirme 3 amaçla yapılır.\n-Öğrencileri tanıma,\n-Öğrenmeyi izleme,\n-Öğrenme seviyesini belirleme",),
      InfoCardItem("eo_Info_112","Ölçüt","Bir yargıya varabilmek için kullanılan ilkedir.",),
      InfoCardItem("eo_Info_113","Mutlak Değerlendirme","Önceden karar verilen standartla öğrenci değerlendirilir.\n-Standart üstü başarılı altı başarısızdır.\n-Öğretmen fikri ve programın hedefleri ölçüttür.\n-Yeni programda kullanılması önerilmiyor.",),
      InfoCardItem("eo_Info_114","Bağıl Değerlendirme","Öğrenmeler sınıf içerisinde öğrenciler karşılaştırılarak sınıfın standartlarına göre değerlendirilir. Aritmetik ortalama, standart sapma dikkate alınır.",),
      InfoCardItem("eo_Info_115","Ölçme Hatası","Gerçek puan ile gözlenen puan arasındaki farktır. 3 çeşittir; \n-Sabir Hatalar,\n-Sistematik hatalar,\n-Rastgele hatalar.",),
      InfoCardItem("eo_Info_116","Sabit Hatalar","-Ölçmeden ölçmeye değişmez. Örn: Öğretmenin testte bir soruyu yanlış cevaplaması.",),
      InfoCardItem("eo_Info_117","Sistematik Hatalar","-Ölçmeden ölçmeye miktar değişebilir.\n-Puanlayıcı kaynaklıdır.\n Örn: Derse katılan öğrenciye daha yüksek puan verilmesi",),
      InfoCardItem("eo_Info_118","Rastgele Hatalar","Kaynağı belli olmayan hatalardır.Örn: Öğretmenin puanları yanlış toplaması.",),
    ]),
    InfoCardModel("Ölçme ve Değerlendirme-3", [
      InfoCardItem("eo_Info_119","Geçerlik","Ölçme aracının ölçtüğü özellikleri başka özelliklerle karıştırmadan ölçebilme seviyesidir. Geçerlik katsayısı -1,0-+1'dir.",),
      InfoCardItem("eo_Info_120","Geçerlik","Örneğin matematik sınavı için hazırlanan sorular sadece matematik dersinin davranışlarını ölçüyorsa sınav geçerlidir.",),
      InfoCardItem("eo_Info_121","Kapsam Geçerliği","Bir sınavda tüm konulardan orantılı şekilde soru soruluyorsa kapsam geçerliği vardır.",),
      InfoCardItem("eo_Info_122","Yordam Geçerliği","Bir testin gelecekte ne olacağını göstermesidir.(Tahmin)",),
      InfoCardItem("eo_Info_123","Yapı Geçerliği","Testte kon dışı soru yok, bölümler kendi içğinde bağlantılı ise yapı geçerliliği vardır.",),
      InfoCardItem("eo_Info_124","Geçerliliği Arttırma Yolları","-Sorular hedeflerle ilişkili olmalıdır.\n-Sorular bilenle bilmeyeni ayırt etmelidir.\n-Mutlak sınav planı olmalıdır.\n-Soruların zorluk dereceleri farklı olmalıdır.\n-Nesnel puanlama yapılmalıdır.",),
    ]), InfoCardModel("Ölçme ve Değerlendirme-4", [
      InfoCardItem("eo_Info_125","Güvenirlik","-Ölçmek istenilen özelliğin doğru olarak ölçülmesidir.\n-Ölçme aracı tekrar uygulandığında aynı sonucu veriyorsa güvenilirdir.\n-Güvenirlik 0-1 arası değer alır.\n-0'a yakınsa çok hatalı, 1'e yakınsa az hatalıdır.",),
      InfoCardItem("eo_Info_126","Güvenirlik Kestirim Yöntemleri","-Test Tekrar Test Yöntemi.\n-Eşdeğer Formlar Yöntemi.\n-İki Yarıya Bölme Yöntemi.\n-Kuder-Richardson 20-21 Formülleri",),
      InfoCardItem("eo_Info_127","Test Tekrar Test","-Test aynı gruba 2 kez uygulanır.\n-İki uygulama karşılaştırılı.\n-Güvenirlik kaysayısı belirlenir.",),
      InfoCardItem("eo_Info_128","Eşdeğer Formlar Yöntemi","-Bir teste eşdeğer en az iki test hazırlanır.\n-Her test aynı güçlükte ve aynı özellikte olmalıdır.\n-Hazırlaması zordur.",),
      InfoCardItem("eo_Info_129","İki Yargıya Bölme Yöntemi","-En çok kullanılan yöntemdir.\n-Tek numaralı sorulara verilen yanıtlarla çift numaralı sorulara verilen yanıtlardan güvenirlik katsayısı oluşturulur.",),
      InfoCardItem("eo_Info_130","Kuder-Richardson 20-21 Formülü","-Her soruyu doğru yanıtlayan öğrencilerin oranı hesaplanır.\n-İleri analiz teknikleri içerir.\n-Madde analizleri yapılır.",),
      InfoCardItem("eo_Info_131","Güvenirliği Arttırma Yöntemleri","-Çok soru olmalıdır.\n-Öğrenci seviyesine uygun olmalıdır.\n-Açık, anlaşılır, yazım kurallarına uygun olmalıdır.\n-Puanlama anahtarı kullanılmalıdır.\n-Sorular basitter zora sıralanmalıdır.",),
      InfoCardItem("eo_Info_132","Kullanışlılık","Ölçme aracının kolay kullanılmasıdır.",),
    ]),
    InfoCardModel("Ölçme ve Değerlendirme-5", [
      InfoCardItem("eo_Info_133","Sınav Türleri","-Sözlü Yoklamalar.\n-Uzun Cevaplı Yazılı.\n-Kısa Cevap Gerektiren Testler..\n-Doğru Yanlış Testler.\n-Çoktan Seçmeli Testler",),
      InfoCardItem("eo_Info_134","1-Sözlü Yoklamalar","-Sorular sözlü sorulur.\n-Öğrenci düşünüp sözlü cevap verir.\n-Geçerliliği ve güvenirliği düşüktür.",),
      InfoCardItem("eo_Info_135","Sözlü Yoklamalar Devamı","Güvenirlik ve geçerliliğini arttırmak için;\n-Basit sorulardan başlanmalı.\n-Eksikler sınav sonunda söylenmeli.\n-Her öğrenciye farklı soru sorulmalı.\n-Sorular önceden hazırlanmalıdır.",),
      InfoCardItem("eo_Info_136","2-Uzun Cevaplı Yazılı","-Sorular yazılı sorulur.\n-Cevaplar yazılı verilir.\n-Az sayıda soru sorulur.\n-Puanlama subjektiftir(kendi bakış açısıyla değerlendirilir).\n-Her konuda dengeli soru gelir.",),
      InfoCardItem("eo_Info_137","Uzun Cevaplı Yazılı Devamı","Güvenirliği ve geçerliliği arttırmak için;\n-Sınırlı cevap gerektiren sorular sorulmalı.\n-Tercihli sorular sorulmamalı.\n-Yazı güzelliğine puan verilmemeli.\n-Cevap anahtarı hazırlanmalıdır.",),
      InfoCardItem("eo_Info_138","3-Kısa Cevap Gerektiren Testler","-Cevaplar kısadır.\n-Bilgi düzeyinin üstündeki davranışları yoklayamaz.\n-Puanlama subjektiftir.\n-Öğrenci cevabı hatırlar ve yazar, şans başarısı yoktur.",),
      InfoCardItem("eo_Info_139","Kısa Cevap Test Devamı","-Yoklanacak davranış önemlidir.\n-Sadece bilenler cevaplamalıdır.\n-Gereksiz bilgiler olmamalıdır.\n-Sorunn tek cevabı olmalı ve başka soruda geçmemelidir.\n-Bilinen kaynaklardan alınmamalıdır.\n-Soru cümleleri kullanılmalıdır.",),
      InfoCardItem("eo_Info_140","4-Doğru Yanlış Testler","-Konu amacına uygun doğru-yanlış ifadeler içerir.\n-%50 cevabı bulma olasılığı vardır.\n-Güvenirliği yüksektir.\n-Geçerliği düşüktür.\n-Objektif puanlanır.",),
      InfoCardItem("eo_Info_141","5-Çoktan Seçmeli Testler","-Çok sayıda soru sorulur.\n-Kapsam geçerlipş yüksektir.\n-Objektif puanlanır.\nZayıf yanları ise şansla bulma ihtimali ve sürekli araştırma gerektirmesidir.",),
    ]),
    InfoCardModel("Ölçme ve Değerlendirme-6", [
      InfoCardItem("eo_Info_142","Öğrenci Portfolio Dosyası","-Öğrencinin ilgi duyduğu alandaki çalışmalarını topladığı dosyadır.\n-Öğrenci söz sahibidir.\n-Öğretmen rehberlik yapar.\n-Öğrenciye eksiklerini görme imkanı sağlar.\n-Değerlendirme sürecine öğrenci katılır.",),
      InfoCardItem("eo_Info_143","Rubrik(Dereceleme Ölçeği)","-Duyuşsal becerilerin ölçülmesinde kullanılır.\n-Ölçek eşit aralıklı olmalıdır.\n-Aralık geniş tutulmalıdır.\n-Aralığın geniş olması öğrenci motivasyonunu arttırır.",),
      InfoCardItem("eo_Info_144","Performans Değerlendirme","-Planlı etkinlik sonunda elde edilen değerlendirmedir.\n-Okul içinde ve dışında devam eder.\n-Arkadaşlarıyla işbirliği yapmasını sağlar.",),
      InfoCardItem("eo_Info_145","Merkez Eğilim Ölçüleri","-Aritmetik Ortalama.\n-Ortanca(Medyan).\n-Mod(Tepe Değer)",),
      InfoCardItem("eo_Info_146","Aritmetik Ortalama","Tüm verilerin toplanıp veri sayısına bölünmesiyle elde edilir.",),
      InfoCardItem("eo_Info_147","Ortanca(Medyan)","Veriler küçükten büyüğe doğru sıralanır. En ortadaki değer ortanca(medyan)dır.",),
      InfoCardItem("eo_Info_148","Mod(Tepe Değer)","En fazla tekrar eden değerdir.",),
      InfoCardItem("eo_Info_149","Merkezi Dağılım Ölçüleri","-Ranj.\n-Standart sapma.\n-Standart hata",),
      InfoCardItem("eo_Info_150","Ranj","En büyük veri ile en küçük veri arasındaki farka denir.",),
      InfoCardItem("eo_Info_151","Standart Sapma","-En güvenilir ölçüdür.\n-Ortalamada olan farkların karelerinin ortalamasının kareköküne denir.",),
      InfoCardItem("eo_Info_152","Standart Hata","Aritmatik ortalamada oluşan hatanın belirlenmesinde kullanılır.",),
    ]),
    InfoCardModel("Ölçme ve Değerlendirme-7", [
      InfoCardItem("eo_Info_153","Test Geliştirme Süreci","-İfadeler açık ve net olmalıdır.\n-Birden fazla anlam çıkarmalı.\n-Az kelime kullanılmalı.\n-Test maddeleri birbirinden bağımsız olmalı.\n-Sorular bir kaynaktan aynen alınmamalı.\n-Çeldiriciler eksik bilgisi olanları yanıltmalı.\n-Hepsi, hiçbiri keimeleri kullanılmamalı",),
      InfoCardItem("eo_Info_154","Bilişsel Öğrenmeleri Ölçme\nAraç ve Yöntemleri","-Bilişsel öğrenme; bilgiyi tanıma, hatırlama, akıl yöntemiyle ilgilidir.\n-Alt sınıfları Bilgi(hatırlama), Kavrama(Yorumlama), Uygulama(Bilgiyi kullanma), Analiz(Bütün ve parçalar arasındaki ilişkiyi belirler), Sentez(Parçaları bir araya getirir), Değerlendirme(öğrenmeyi ölöme)",),
      InfoCardItem("eo_Info_155","Madde Analizi","Maddelerin özelliklerinin belirlenmesini sağlar.",),
      InfoCardItem("eo_Info_156","Madde Analizi Basamakları","-Cevap kağıtları okunur.\n-Sonuçlar büyükten küçüğe sıralanır.\n-%27 lik bölüm alınır.\n-Her maddenin cevaplana oranı belirlenir.\n-Sonuç değerlendirilir.",),
      InfoCardItem("eo_Info_157","Test İstatistiği","Ölçümlerden elde edilen sonuçları yorumlamak için standart puanlara ihtiyaç olmuştur. Bunlar Z Puanı ve T Puanıdır.",),
      InfoCardItem("eo_Info_158","Z Puanı","-Ortalaması 0'dır.\n-Standart sapması 1'dir.\n-Bir puanın ortalamanın altında ya da üstünde olduğu hakkında bilgi verir.\n-Hem puandan ortalama çıkarılır, standart sapmaya bölünür.",),
      InfoCardItem("eo_Info_159","T Puanı","-Ortalaması 50'dir.\n-Standart sapması 10'dur.\n-T Puanı ile yorumları aynıdır.\n-Z puanında değerler negatif, sıfır veya küsüratlı çıkarsa T puanı kullanılır.",),
    ]),*/
   /* InfoCardModel("Psikolojik Danışma ve Rehberlik-1", [
      InfoCardItem("eo_Info_160","Rehberlik Hizmetlerinin İlkeleri","-Örgütlenmiştir.\n-Okul, aile ve çevreyi bilgilendirir.\n-Herkesin seçme özgürlüğü vardır.\n-İnsana saygı esastır.\n-Her okulda rehberlik hizmeti olmalıdır.\n-Koruyucudur.\n-Tüm öğrencilere açıktır.",),
      InfoCardItem("eo_Info_161","Rehberlik Hizmetlerinin İlkeleri","-Gönüllülük esastır.\n-Yaşam boyu yararlanılabilir.\n-İşbirliği gerektirir.\n-Bireye ve topluma karşı sorumludur.\n-Gizlilik esastır.\n-Eğitimin ayrılmaz parçasıdır.",),
      InfoCardItem("eo_Info_162","Yararlanılan Bilim Dalları","-Psikoloji\n-Sosyoloji\n-Sosyal Psikoloji\n-Ekonomi\n-Antropoloji\n-Eğitim Bilimi",),
      InfoCardItem("eo_Info_163","Rehberliğin Temel Taşları","-Bireye yardım etme sürecidir\n-Her öğrenci geliştirilebilir\n-Bireyin kendini gerçekleştirmesini sağlar\n-Bilimsel ve profesyoneldir.",),
      InfoCardItem("eo_Info_164","Rehberlik Hizmetinin Psikolojik Temelleri","-Bireysel farklılıklar\n-Cinsiyet farkları\n-Bireydeki nitelikler ile meslekler arası ilişkiler\n-Davranım\n-Kişilik",),
    ]),
    InfoCardModel("Psikolojik Danışma ve Rehberlik-2", [
      InfoCardItem("eo_Info_165","Hizmet Türleri","1-Hizmet verilen birey sayısına göre rehberlik\n-2-Hizmetin temel işlevine göre rehberlik\n-Hizmetin yoğunlaştığı problem alanına göre rehberlik\n-Hizmet alanına göre rehberlik\n-Öğretim basamaklarına göre rehberlik",),
      InfoCardItem("eo_Info_166","1-Hizmet Verilen Birey Sayısına Göre","-Bireysel ve grup rehberlği olarak incelenir.\n-Bireysel rehberlik 1 kişi için yapılır.\n-Grup rehberliği bir gruba aynı anda yapılır",),
      InfoCardItem("eo_Info_167","1-Hizmet Verilen Birey Sayısına Göre","-Bireysel rehberlik kişinin farkındalık düzeyini yükseltmeli.\n-Kişi sorununu kendi çözmelidir.\n-Grup rehberlikleri uzmanlık gerektirmiyorsa snıf rehber öğretmeni tarafından yapılabilir.",),
      InfoCardItem("eo_Info_168","2-Hizmetin Temel İşlevine Göre","A) Uyum Sağlayıcı Rehberlik\n-Çocukların ihtiyacına göre hazırlanır.\n-Uyum sorunlarının sebebini bulmalıdır.",),
      InfoCardItem("eo_Info_169","2-Hizmetin Temel İşlevine Göre","B) Yönetici Rehberlik\n-Öğrenciler meslek kaygısı yaşayabilir.\n-Rehberlik servisi öğrenciyi ilgisi olan alana yönlendirebilir.",),
      InfoCardItem("eo_Info_170","2-Hizmetin Temel İşlevine Göre","C) Ayarlayıcı Rehberlik\n-Öğrencinin ilgi ve gereksinimlerine göre etkinliklerin hazırlanarak eğitimcilere sunulmasıdır",),
      InfoCardItem("eo_Info_171","2-Hizmetin Temel İşlevine Göre","D) Geliştirici Rehberlik\n-Bireylerin gelişim dönemleri dikkate alınarak hazırlanır.",),
      InfoCardItem("eo_Info_172","2-Hizmetin Temel İşlevine Göre","E) Önleyici Rehberlik\n-Olumsuz durumlar ortaya çıkmadan gerekli tedbirlerin alınmasıdır.",),
      InfoCardItem("eo_Info_173","2-Hizmetin Temel İşlevine Göre","F) Tamamlayıcı Rehberlik\n-Rehberlik öğretim etkinliklerini tamamlayıcı boyuttadır.",),
      InfoCardItem("eo_Info_174","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","A)Eğitsel Rehberlik\n-Okul seçme, okula uyum, verimli ders çalışma, zamanı iyi kullanma vb. gibi konularda verilen destekleri içerir.",),
      InfoCardItem("eo_Info_175","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","B) Mesleki Rehberlik\n-Meslek tanıma, meslek seçimi, seçtiği mesleğe hazırlanma vb. gibi konularda destek verir.\n-Mesleki Seçim Devreleri\n-Fantezi Devresi(6-12 yaş. Taklit vardır sıkça tercih değişir)\n-Geçici Devre(12-17 yaş.İlgi vardır, daha bilinçlidir ama geçicidir.)\n-Gerçekçi Devre(18 yaş üstü gerçekçi seçimdir.)",),
      InfoCardItem("eo_Info_176","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","Meslek seçiminde;\n-Fiziksel ve kişisel özellikler\n-Genel ve özel yetenekler\n-İlgiler\n-Yaşantılar ve\n-Aile yapısı dikkate alınmalıdır.",),
      InfoCardItem("eo_Info_177","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","Meslek Gelişim Dönemleri;\n-Büyüme Dönemi(0-14 Yaş)\n-Araştırma Dönemi(15-24 Yaş)\n-Yerleşme Dönemi(25-44 Yaş)\n-Sürdürme Dönemi(45-64 Yaş)\n-Emeklilik Dönemi(65 yaş üstü",),
      InfoCardItem("eo_Info_178","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","C) Bireysel Rehberlik\n-Öğrencinin kişisel-sosyal gelişim ihtiyaçlarını karşılamak amacıyla yürütülür.",),
      InfoCardItem("eo_Info_179","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","D) Grup Rehberliği\n-Belli bir grupta veya sınıfta tüm öğrencilerle yürütülür.\n-Meslek tanıma, ders çalışma gibi olgusal konularda destek verilir.\n-Her öğrenciye saygı esastır.\n-Her öğrencinin katılımı sağlanır.\n-Danışman kendi fikrini yansıtmaz.",),
      InfoCardItem("eo_Info_180","4-Hizmet Alanlarına Göre","A) Eğitim Alanında\n-Öğrencileri eğitimin temel amaçlarına göre geliştirmek.\n-Doğru mesleklere yönlendirmek.\n-İlgi ve yeteneklerine göre eğitim vermek amacaıyla rehberlik yapılır.",),
      InfoCardItem("eo_Info_181","4-Hizmet Alanlarına Göre","B) Sağlık Alanında Rehberlik\n-Bireylerin ruh ve beden sağlıkları için rehberlik çalışmaları yürütür.",),
      InfoCardItem("eo_Info_182","4-Hizmet Alanlarına Göre","C) Sosyal Yardım Alanında Rehberlik\n-Huzur evleri, Çocuk Esirgeme Kurumları, Kızılay gibi kurumlarda rehberlik hizmeti verilr.",),
      InfoCardItem("eo_Info_183","4-Hizmet Alanlarına Göre","D) Endüstri Alanında Rehberlik\n-Sanayi, işçi sendikaları gibi kurumlarda da rehberlik hizmeti verilebilir.",),
      InfoCardItem("eo_Info_184","5-Öğretim Basamaklarına Göre","A) Okul Öncesi \n-Okula uyum, çocukların sağlıklı gelişimleri ve becerilerini ortaya koyabilmeleri için rehberlik çalışmaları yürütülebilir.",),
      InfoCardItem("eo_Info_185","5-Öğretim Basamaklarına Göre","B) İlköğretim \n-Çocuğun tüm yönleriyle gelişmesini amaçlar.\n-Dili etkili kullanma, okuma yazma gibi becerilerin geliştirilmesini hedefler.",),
      InfoCardItem("eo_Info_186","5-Öğretim Basamaklarına Göre","C) Orta Öğretim \n-Meslek kazandırmayı ve yksek öğretime hazırlamayı amaçlar.",),
      InfoCardItem("eo_Info_187","5-Öğretim Basamaklarına Göre","D) Yüksek Öğretim\n-Barınma, beslenme, başarı, mesleğe hazırlama vb. gibi konularda rehberlik hizmeti verilir.",),
    ]),
    InfoCardModel("Psikolojik Danışma ve Rehberlik-3", [
      InfoCardItem("eo_Info_188","Rehberlik Hizmetlerinin Amaçları","Öğrencilerin;\n-Kendilerini tanımalarını sağlar.\n-Eğitim olanakları, mesleklerin ve toplmun isteklerini tanımalarını sağlar.\n-Kendilerini uygun programı seçmelerini sağlar.\n-Problem çözme ve doğru karar verme gibi becerilerinin gelişmesini amaçlar.",),
      InfoCardItem("eo_Info_189","Rehberlik Hizmetlerinin İlkeleri","-Eğitim öğretim etkinlikleriyle bütündür.\n-Tüm öğrencilere açıktır.\n-Öğrencinin seçme özgürlüğü vardır.\n-İnsana saygı esastır.\n-Gizlilik esastır.",),
      InfoCardItem("eo_Info_190","Rehberlik Hizmetlerinin İlkeleri-2","-Öğrenci, veli, öğretmen, yönetici, uzman işbirliği ile yürütülür.\n-Bireysel farklılıklara saygı duyulur.\n-Bireye ve topluma karşı saygı esastır.\n-Bilimsellik esastır.",),
      InfoCardItem("eo_Info_191","Rehberlik Servisleri","1-Öğrenciyi Tanıma Servisi \n2-Psikolojik Danışma Servisi\n3-Grup Rehberliği\n4-Eğitsel ve Mesleki Bilgi Verme Servisi\n5-Yerleştirme ve İzleme Servisi",),
      InfoCardItem("eo_Info_192","1-Öğrenciyi Tanıma Servisi","-Öğrencilerin gizli güçlerini ortaya çıkarmayı sağlar",),
      InfoCardItem("eo_Info_193","2-Psikolojik Danışma Servisi","-Okula uyum, sorun çözme gibi konularda destek olunur.",),
      InfoCardItem("eo_Info_194","3-Grup Rehberliği","-Tüm öğrencilere yöneliktir.\n-Bilgi verme, sorun çözme, uyum sağlama vb konularda yardımcı olunur.",),
      InfoCardItem("eo_Info_195","4-Eğitsel ve Mesleki Bilgi Verme Servisi","-Eğitsel ve mesleki bilgiler grup rehberliği ile öğrencilere verilir.",),
      InfoCardItem("eo_Info_196","5-Yerleştirme ve İzleme Servisi","-Öğrencinin ders ve programlara yerleşmesini sağlar.\n-Okullara öğrenci yerleştirmeyi sağlar.",),
    ]), InfoCardModel("Psikolojik Danışma ve Rehberlik-4", [
      InfoCardItem("eo_Info_197","Rehberlik Servisinin Görevleri","-Rehberlik hizmetlerini yürütülmesini ve yaygınlaştırılmasını sağlamak.\n-Programlarda bulunması gereken etkinlikler için önerilerde bulunmak.\n-İhtiyaç duyulan araç, gereç ve kaynakların sağlanması.",),
      InfoCardItem("eo_Info_198","Rehberlik ve Psikolojik Danışma Hizmetleri Yürütme Komisyonu","-Psikolojik danışman,\n-Sınıf rehber öğretmenlerinden her sınıf seviyesinden 1 öğretmen,\n-Disiplin kurulundan 1 kişi,\n-Okul aile birliği ve okul koruma derneğinden 1 kişi,\n-Okul öğrenci temsilcisi.",),
      InfoCardItem("eo_Info_199","Yürütme Komisyonunun Görevleri","-Yıllık rehberlik planlarını inceler, uygulanmasını sağlar.\n-Rehberlik hizmetlerinde çıkan sorunları inceler ve çözüm önerilerinde bulunur.\n-Eğitim ortamındaki kişilerin işbirliğini sağlar.\n-Mesleki rehberlik çalışmalarında gerekli yönlendirmeleri yapar.",),
      InfoCardItem("eo_Info_200","Okul Müdürünün Görevleri","-Gerekli fiziksel şartları, araç ve gereçleri sağlar.\n-Yürütme komisyonunu kurar ve başkanlık eder.\n-Yıllık rehberlik plan ve programlarının hazırlanmasını ve uygulanmasını sağlar.\n-Birden fazla öğretmen varsa birini koordinatör seçer.",),
      InfoCardItem("eo_Info_201","Okul Müdürünün Görevleri","-Psikolojik danışmanlar arasında iş bölümü yapar.\n-Sınıf rehber öğretmenlerini görevlendirir.\n-Başka okuldan gelen öğrencinin gelişim dosyasını rehberlik servisine iletir.\n-Rehberlik ve Araştırma Merkezine plan ve programın örneğini ilk ay, ders yılının son ayında da yıl sonu çalışma raporını gönderir.",),
      InfoCardItem("eo_Info_202","Okul Müdür Yardımcısının Görevleri","-Sorumlu olduğu sınıflardaki öğrencilerin sorunlarını, bilgi ve belgelerini rehberlik servisine iletir.\n-Yürütme komisyonu toplantılarına katılır.\n-Okul müdürünün vereceği görevleri yapar.\n-",),
      InfoCardItem("eo_Info_203","Koordinatörün Psikolojik Danışman Görevleri","-Rehberlik servisi ile okul yönetimi arasındaki iletişimi sağlar.\n-Rehberlik programlarını okul müdürüne iletir.\n-Rehberlik programları hakkında öğretmenler kuruluna bilgi verir.\n-Rehberlik hizmetleri etkinliklerine fiilen katılır.",),
      InfoCardItem("eo_Info_204","Psikolojik Danışman Görevleri-1","-Okulun rehberlik progrmaını hazırlar.\n-Rehberlik programlarının uygulanmasında sınıf öğretmenlerine rehberlik eder.\n-Eğitsel ve mesleki rehberlik etkinliklerini planlar ve uygulanmasına rehberlik eder.\n-Bireysel rehberlik hizmetlerini yürütür.",),
      InfoCardItem("eo_Info_205","Psikolojik Danışman Görevleri-2","-Öğrencilere yönelik bireyi tanıma etkinlikleirni yürütür.\n-Sınıflarda uygulanacak rehberlik etkinliklerinde uzmanlık gerektiren etkinlikleri uygular.\n-Mezun olacak öğrencinin değerlendirme raporunu hazırlar ve raporu gelişim dosyasına koyar.",),
      InfoCardItem("eo_Info_206","Psikolojik Danışman Görevleri-3","-Seçmeli derslere ilişkin araştırma yapar.\n-Özel eğitim gerektiren öğrencilere rehberlik hizmeti verir.\n-Okula nakil gelen öğrencilerin gelişim dosyalarını inceler ve sınıf rehber öğretmenleriyle değerlendirir.",),
      InfoCardItem("eo_Info_207","Psikolojik Danışman Görevleri-4","-Öğrenciye, ailelerine ve öğretmenlere gerektiğinde toplantı, etkinlik düzenler.\n-Rehberlik hizmetine ilişkin komisyonlara katılır.\n-Milli Eğitim Bakanlığı Orta Öğretim Kurumları Ödül ve Disiplin Yönetmeliğinde belirtilen görevleri yapar.",),
      InfoCardItem("eo_Info_208","Sınıf Rehber Öğretmeninin Görevleri-1","-Rehberlik programına göre sınıfın yıllık çalışmalarını planlar.\n-Eğitsel ve mesleki rehberlik etkinliklerini yapar.\n-Öğrenci gelişim dosyarının tutulmasında rehberlik servisiyle işbirliği yapar.",),
      InfoCardItem("eo_Info_209","Sınıf Rehber Öğretmeninin Görevleri-2","-Öğrencilerin özel bilgilerinin gizliliğini korur.\n-Rehberlik raporlarını ders yılı sonundaki ilk haftada rehberlik servisine iletir.\n-Okul müdürünün vereceği sınıf rehberliğiyle ilgili diğer görevleri yapar.",),
    ]),
    InfoCardModel("Psikolojik Danışma ve Rehberlik-5", [
      InfoCardItem("eo_Info_210","Akademik ve Mesleki Rehberlik Yöntemleri","-Sosyolojik Yaklaşım,\n-Karar Verme Yaklaşımı,\n-Varoluşçu Yaklaşım,\n-Gelişimsel Yaklaşım,\n-İhtiyaçlar Yaklaşımı,\n-Psikoanalitik Yaklaşım.",),
      InfoCardItem("eo_Info_211","1-Sosyolojik Yaklaşım","Meslek seçimini sosyolojik(aile, okul, toplum) değişkenlerinin belirlediği gibi savunur.",),
      InfoCardItem("eo_Info_212","2-Karar Verme Yaklaşımı","Meslek seçiminde bilgi kavrama süreçlerinin ve ödülleri algılama biçimlerinin etkili olduğunu savunur.",),
      InfoCardItem("eo_Info_213","3-Varoluşçu Yaklaşım","Kişisel farkındalıkların geliştirilmesinin meslek seçimini etkilediğini savunur.",),
      InfoCardItem("eo_Info_214","4-Gelişimsel Yaklaşım","Meslek seçimini hayat boyu gelişimin bir parçası olarak görür.",),
      InfoCardItem("eo_Info_215","5-İhtiyaçlar Yaklaşımı","Meslek seçimini psikolojik ihtiyaçların belirlediğini savunur.",),
      InfoCardItem("eo_Info_216","6-Psikoanalitik Yaklaşım","Meslek seçimini kişisel dinamiklerin belirlediini savunur.",),
    ]),InfoCardModel("Öğrenciyi Tanıma Teknikleri (Testler)", [
      InfoCardItem("eo_Info_217","A) Maksimum Performans Testleri","a) Yetenek Testleri: Akademik yeteneklerle ilgili bilgi toplamak için hazırlanmıştır.\nb) Başarı Testleri: Kazanılmış akademik bilgileri ölçmeye yarar.",),
      InfoCardItem("eo_Info_218","B) Davranış Testleri","a) İlgi Envanterleri: Öğrencileri ilgilerinin olduğu alana yönlendirmek amacıyla hazırlanır.\nb)Kişilik Envanterleri: Öğrencilerde kişilik bozukluğunun tespiti, sorunlara çözüm üretimi ve psikolojik danışmana öğrenci hakkında doğru bilgi aktarımı için kullanılır.",),
      InfoCardItem("eo_Info_219","B) Davranış Testleri-2","c)Tutum Envanterleri: Öğrencinin aile ve öğretmenleriyle ilgili tutumlarını ölçmeyi amaçlar.",),
    ]),*/
    InfoCardModel("Öğrenciyi Tanıma Teknikleri (Test Dışı Teknikler)", [
      InfoCardItem("eo_Info_220","A) Kendini Anlatma Teknikleri","Birey kendisi ile ilgili bilgileri doğrudan verir.",),
      InfoCardItem("eo_Info_221","B) Görüşme","Belli bir amaç için yüzyüze yapılan etkileşimdir.",),
      InfoCardItem("eo_Info_222","C) Anket","Bir konu hakkında görüş toplamak için oluşturulan soru formlarıdır.",),
      InfoCardItem("eo_Info_223","D) Problem Tarama Listeleri","Öğrencilerin sorunlarını tespit edip, çözmeyi amaçlayan bilgi toplama araçlarıdır.",),
      InfoCardItem("eo_Info_224","E) Otobiyografi","Öğrencilerin özgeçmişlerini rapor eder.",),
      InfoCardItem("eo_Info_225","F) İstek Listeleri","Öğrencilerin isteklerini belirlemek için sorulan sorulardır.",),
      InfoCardItem("eo_Info_226","G) Öğrenciyi Tanıma Formu","Öğrenciyi tanıma amacıyla kullanılan formlardır.",),
      InfoCardItem("eo_Info_227","H) Gözlemsel Teknikler","Gözlem, derecelendirme ölçekleri ve anekdot",),
      InfoCardItem("eo_Info_228","I) Gözlem","Doğal ortamlarında öğrencilerin gözlenme sürecidir.",),
      InfoCardItem("eo_Info_229","J) Anektod","Gözlem sonuçlarının kaydedildiği formlardır.",),
      InfoCardItem("eo_Info_230","J) Derecelendirme Ölçekleri","Öğrencilerin davranışlarının gözlem yapan kişi tarafından bir forma göre işaretlendiği ölçeklerdir.",),
    ]),
    InfoCardModel("Öğrenciyi Tanıma Teknikleri (Sosyometrik Teknikler)", [
      InfoCardItem("eo_Info_231","A) Sosyometri","Öğrenci hakkında başka kişilerden bilgi alınan tekniktir. Öğrencinin grup içindeki rolü  hakkında bilgi verir.",),
      InfoCardItem("eo_Info_232","B) Kimdir Bu Tekniği","Öğrencinin diğer kişiler tarafından nasıl görüldüğünü gösterir.",),
    ]),
    InfoCardModel("Öğrenciyi Tanıma Teknikleri (Diğer Teknikler)", [
      InfoCardItem("eo_Info_233","A) Toplu Dosya","Öğrencinin tüm bilgilerinin toplandığı dosyadır.",),
      InfoCardItem("eo_Info_234","B) Ev Ziyaretleri","Öğrenci hakkında en doğru bilgiyi veren tekniktir. Ailenin çocuklarıyla daha çok ilgilenmesini sağlar.",),
      InfoCardItem("eo_Info_235","B) Veli Toplantıları","Öğrenci hakkında veliye bilgi aktarımıdır.",),
    ]),
    InfoCardModel("Gelişim Psikolojisi-1", [
      InfoCardItem("eo_Info_236","Temel Kavramlar","-Bireyin yaşı ile davranışı arasındaki ilişkiyi inceler.\n-Temelde belirli bir dönemde geçirdiği süreci mercek altına alır.\n-Gelişim, değişim, büyüme, olgunlaşma, öğrenme, hazırbulunuşluk ve gelişme temel kavramlar arasında yer almaktadır."),
      InfoCardItem("eo_Info_237","Gelişim-1","-Doğum öncesi süreçten başlar.\n-Duygusal, fiziksel, bedensel ve sosyal yönden ilerleme yaşanması gelişim olarak ifade edilir.\n-Gelişim için temel unsur öğrenmedir.\n-Öğrenmeler her birey için farklı olacağından bireylerin gelişimlerinin de birbirinden farklı olması beklenir."),
      InfoCardItem("eo_Info_239","Gelişim-2","-Gelişimdeki ilerleme sistematik, ardışık ve süreklidir.\n-Gelişim daima ileriye doğru gerçekleşir.\n-Değişim ile karıştırılsa da farklı kavramlar olarak ele alınırlar."),
      InfoCardItem("eo_Info_240","Değişim-1","-Bir durumun farklı duruma geçmesine değişim denir.\n-Sistematik, ardışık ve uyum sağlayıcıdır.\n-Ayrıca tesadüfi, olumsuz ve geçici de olabilir.\n-Değişim gelişimden farklı olarak geriye de gidebilir.\n-Bu yüzden gelişimi de içine alan daha kapsayıcı bir kavramdır."),
      InfoCardItem("eo_Info_241","Değişim-2","-Gelişim daima ileriye doğru, değişim hem ileriye hem geriye doğru olabilir.\n-Her ikisi de süreç içerisinde gerçekleşir.\n-Öğretmenin hastalık sonucu ders anlatamayacak hale gelmesi gelişim değil değişimdir ve geriye doğrudur.\n-Her gelişim değişimdir ama her değişim gelişim değildir."),
      InfoCardItem("eo_Info_242","Büyüme","-Vücudun değerlerinin artmasına denir.\n-Artış nicelikseldir.\n-Boy, kilo, hacim olarak artış büyümedir.\n-Sürekli aynı hızda değildir, hızlanır ve yavaşlar.\n-Tüm vücutta gerçekleşir.\n-Yaş en önemli etkendir."),
      InfoCardItem("eo_Info_243","Olgunlaşma-1","-Genetik özelliklerin çevre öğrenmeleriyle karışmasıyla oluşan değişimlerdir.\n-Yeterli olgunluk düzeyine ulaşmayan organizma öğrenmeyi gerçekleştiremez.\n-Yürüyecek seviyeye gelmiş kas yapısına sahip olmayan çocuklar yürüyemez.\n-O zaman öğrenme için gerekli koşul bedensel ve zihinsel gelişimdir."),
      InfoCardItem("eo_Info_244","Olgunlaşma-2","-Koşullar normal ise olgunlaşma çevresel faktörlerden etkilenmez.\n-Çocuğunun yürümesini isteyen aileler çocuğun yürüme davranışı için gerekli olgunluğa ulaşıp ulaşmadığını bilmelidir.\n-Yürüme davranışı kendiliğinden öğrenilebilir.\n-Öğrenmenin gerçekleşmesi için olgunlaşma gereklidir.\n-Yani çocuğun kasları gelişmeden yürüyemez."),
    ]), InfoCardModel("Gelişim Psikolojisi-2", [
      InfoCardItem("eo_Info_245","Hazırbulunuşluk-1","-Öğrenme gerçekleşmeden önce, kişinin öğrenmeyi gerçekleştirebilmek için sahip olduğu bilgi, tecrübe ve motivasyonudur.\n-Öğrenme olması için bireyin hazırbulunuşluğu şarttır.\n-Olgunlaşma öğrenmeyi getirir ve öğrenmeler hazırbulunuşluğu arttırır."),
      InfoCardItem("eo_Info_246","Hazırbulunuşluk-2","-Öğrencinin olgunlaşması konuşabilmesini sağlar.\n-Konuşma davranışını kusursuz yapan çocuklar, okumayı öğrenmek için gerekli hazırbulunuşluk düzeyine sahip olurlar.\n-Yeterli hazırbulunuşluk düzeyine sahip öğrencilerin öğrenmeleri daha kolay gerçekleşir."),
      InfoCardItem("eo_Info_247","Öğrenme","-Nispeten kalıcı değişimlerdir.\n-Çevrenin etkisi ile gerçekleşir.\n-Öğrenme olmadan gelişim veya değişim asla olmaz."),
      InfoCardItem("eo_Info_248","Gelişimi etkileyen faktörler","-Kalıtım, Çevre, zaman.\n-Kalıtım, soydan gelen özelliklerdir. Örn: Müzik kulağının olması gelişimde etkilidir.\n-Çevreden aldığı tepkiler gelişimi etkiler. Örn: Şarkı söylediğinde takdir toplaması davranışı devam ettirir.\n-Zaman ise doğru zamanda doğru işleri yapmasıdır."),
      InfoCardItem("eo_Info_249","Kritik dönem","-Davranışın kazanılması için gereken duyarlılığın en yüksek seviyeye ulaştığı dönemdir.\n-Kritik dönem doğru atlatılmazsa davranışın kazanılması zorlaşır hatta imkansız hale gelir.\n-Konuşmanın öğrenilmesi için çocuğun kritik döneminde bulunduğu ortamda konuşulması gerekir."),
      InfoCardItem("eo_Info_250","Tarihsel zaman","-Öğrenmenin gerçekleşeceği zaman diliminde varolan durumların öğrenmeye etkisine denir.\n-Savaş durumunun gerçekleştiği zamanda yetişen çocukların davranış biçimlerindeki değişimler örnek olarak verilebilir.\n-Pandemi dönemindeki çocukların davranışlarının değişmesi"),
      InfoCardItem("eo_Info_251","Kişilik-1","-Bireylerin doğuştan getirdiği özellikler ile sonradan kazandıkları arasındaki dengedir.\n-İnsan davranışlarını kapsar.\n-Bireyi diğer bireylerden ayırt eder."),
      InfoCardItem("eo_Info_252","Kişilik-2","3 adet kuram bulunur;\n- Bilişsel Gelişim Kuramı,\n-Psiko-Analitik Gelişim Kuramı,\n-Psiko-Sosyal Gelişim Kuramı"),

    ]), InfoCardModel("Gelişim Psikolojisi-3", [
      InfoCardItem("eo_Info_253","Psikoseksüel Gelişim Dönemleri","-Oral Dönem: 0-1 yaş aralığını kapsar.\n-Anal Dönem: 1-3 yaş aralığını kapsar.\n-Fallik Dönem: 3-7 yaş aralığını kapsar.\n-Latant Dönem: 7-11 yaş aralığını kapsar.\n-Genital Dönem: 11-18 yaş aralığını kapsar."),
      InfoCardItem("eo_Info_261","Bilişsel Gelişim Kuramı","-Bireyin çevresinde olup bitenleri anlamasıdır.\n-Zihinsel faaliyetlerdeki gelişimi ve etkin düşünme yollarını geliştirmeyi ifade eder.\n-Piaget olgunlaşmanın öğrenme üzerinde etkili olduğunu vurgulamıştır."),
      InfoCardItem("eo_Info_262","Bilişsel gelişim dönemleri","-Duyusal motor dönemi (0-2 yaş),\n-İşlem öncesi dönem (2-7 yaş),\n-Somut işlemler dönemi (7-12 yaş),\n-Soyut işlemler dönemi (12 ve sonrası)"),
      InfoCardItem("eo_Info_263","Duyusal Motor Dönem (0-2yaş)","-Karmaşık olmayan zihinsel işlemler gerçekleştirilebilir.\n-Basit refleksif hareketler görülür.\n-Döngüsel hareketler görülür.(el, ayak hareketleri, elini emme gibi)"),
      InfoCardItem("eo_Info_264","İşlem öncesi dönem (2-7 yaş)","-İşlem yapma kabiliyeti gelişmemiştir.\n-Dünyada varolan tek görüş çocuğun kendi görüşüdür.\n-Ben-merkezcilik zirvededir.\n-Ben-merkezci yaklaşım 7 yaşına doğru azalır ve mantıklı düşünme başlar."),
      InfoCardItem("eo_Info_265","Somut işlemler dönemi (7-12 yaş)","-İşlemleri tersten yapabilir.\n-Mantıklı düşünebilme yeterliliği kazanır.\n-Soyut düşünme tam gelişmemiştir.\n-Bir problemin birden fazla çözümü bulunması istenirse çocuk zorlanabilir.\n-Deyimleri anlamakta zorlanırlar."),
      InfoCardItem("eo_Info_266","Soyut işlemler dönemi (12 ve sonrası)","-En üst bilişsel dönemdir.\n-İdealler belirlenir.\n-Gelecekte karşılaşacağı fırsatlar düşünülür.\n-Problemler için gerçekçi çözümler üretilir."),
    ]), InfoCardModel("Gelişim Psikolojisi-4", [
      InfoCardItem("eo_Info_267","Psikoanalitik Gelişim Kuramı","-Freud kişilik gelişiminde ilk çocukluk yıllarının önemine dikkat çeker.\n-Temel ihtiyaçlar karşılanmazsa kişilik gelişimi engellenir.\n-Bilinç sınıflandırması ve kişilik yapısı kuramın temelini oluşturan iki kavramdır."),
      InfoCardItem("eo_Info_268","Bilinç sınıflandırması","-Yaşantıların farkında olunan kısmı bilinçtir.\n-Biraz düşününce bilince çıkarabildiğimiz yaşantılar bilinç öncesini oluşturur.\n-Özel teknikler haricinde ortaya çıkarılamayan ve bilinçte bulunmayan kısım da bilinç dışıdır.\n-Kişilik büyük çoğunlukla bilinç dışında bulunur."),
      InfoCardItem("eo_Info_269","Kişilik Yapısı","-Güdülerin öncelikli olduğu kısım id bölümüdür.\n-Gerçek öncelikli olan, id ile gerçeklik arasında arabuluculuk yapan kısım egodur.\n-Çevreden, toplumdan ve kültürden öğrendiği kuralları içeren kısım süper egodur."),
      InfoCardItem("eo_Info_270","Psikososyal Kişilik Gelişim Kuramı","-Erikson'un kuramıdır.\n-Psikoloji ve sosyal kelimesinin birleşimi olarak düşünülebilir.\n-Psikolojik olarak çevresel faktörlerden etkilenme anlaşılır.\n-Benlik gelişimi biyolojik temelli ve aşamalıdır."),
      InfoCardItem("eo_Info_271","Dönemler","-Güvene karşı güvensizlik (0-1 yaş)\n-Bağımsızlığa karşı utanma ve şüphecilik (2-3 yaş)\n-Girişkenliğe karşı suçluluk duyma (4-6 yaş)\n-Başarıya karşı aşağılık duygusu (7-11 yaş)\n-Kimlik kazanmaya karşı rol karmaşası (12-18 yaş)\n-Dostluk kazanmaya karşı yalnız kalma (19-26 yaş)\n-Üretkenliğe karşı duraklama(40-65 Yaş)\n-Benlik bütünlüğüne karşı umutsuzluk(65-sonrası)"),
      InfoCardItem("eo_Info_272","Gelişim İlkeleri-1","-Süreklidir.\n-Hep ileriye doğrudur.\n-Belirli aşamalarla gerçekleşir.\n-Değişken hızla devam eder.\n-Bir gelişim hızlanırken diğeri yavaşlar.\n-Kalıtım ve çevre önemli etkenlerdir.\n-Baştan ayağa, içten dışa ve genelden özeledir."),
      InfoCardItem("eo_Info_273","Gelişim İlkeleri-2","-Kritik dönemler vardır.\n-Bedensel, zihinsel, duygusal ve sosyal olarak bütündür.\n-Bireysel farklılıklar bulunur.\n-Olgunlaşmada kalıtım, öğrenmeyi çevre etkiler."),

    ]),InfoCardModel("Gelişim Psikolojisi-5", [
      InfoCardItem("eo_Info_274","Gelişim dönemleri","-Bebeklik Dönemi (0-2),\n-İlk Çocukluk Dönemi (2-6)\n-Son Çocukluk Dönemi (6-12 Yaş)\n-Ergenlik Dönemi (12-18 Yaş)\n-Orta Yetişkinlik Dönemi (35-60 Yaş)\n-Yaşlılık Dönemi (65 Yaş Üzeri)"),
      InfoCardItem("eo_Info_275","Bebeklik Dönemi (0-2)","-Bağlanma davranışı görülür.\n-Dünyaya uyum sağlama süreci gerçekleşir.\n-Duyusal, algısal ve psikomotor olgunlaşma gerçekleşir.\n-Çevre ile ilişki kurmaya başlanır."),
      InfoCardItem("eo_Info_276","İlk Çocukluk Dönemi (2-6)","-Konuşma ve yürüme dönemi başlar.\n-Oyunlar hayalidir.\n-Özbakım becerileri gelişir.\n-Mahremiyet eğitimi verilir.\n-Cinsiyeti öğrenir.\n-Cinsyet rollerini öğrenir ve özdeşim kurar.\n-Erken ahlak gelişimi görülür."),
      InfoCardItem("eo_Info_277","Son Çocukluk Dönemi (6-12 Yaş)","-Oyun becerileri gelişir.\n-Sosyalleşme gerçekleşir.\n-Cinsiyet rollerinin öğrenimi tamamlanır.\n-Okuma ve yazma becerileri gelişir.\n-Yaşıtları ile ilişki kurar.\n-Kişisel özgürlük dönemidir.\n-Tutumsal nitelikler ilk kez görülür."),
      InfoCardItem("eo_Info_278","Ergenlik Dönemi (12-18 Yaş)","-Birey kimlik kazanır.\n-Duygusal bağımsızlık gelişir.\n-Fiziksel değişimler gerçekleşir.\n-Cinsiyet rolleri ortaya konur.\n-Mesleki ilgi ve idealler ortaya konur.\n-Toplum içerisinde sorumluluk almaya başlar.\n-Kişilik gelişimleri görülür."),
      InfoCardItem("eo_Info_279","Orta Yetişkinlik Dönemi (35-60 Yaş)","-Dostluk ilişkilerinde akılcı ve yakındır.\n-Aile büyüklerinden tamamen ayrılır.\n-Ahlaki değerleri ön plandadır."),
      InfoCardItem("eo_Info_280","Yaşlılık Dönemi (65 Yaş Üzeri)","-Ölüme karşı duyarlılık beklenir.\n-Eş ölümlerini kabullenme gerçekleşir.\n-Entellektüellik ve birikim zirvededir."),

    ]),
   /* InfoCardModel("Öğrenme Psikolojisi-1", [
      InfoCardItem("eo_Info_281","Öğrenme-1","-Yaşantı veya tekrar yoluyla bireylerde meydana gelene kalıcı davranış değişikliklerine öğrenme denir.\n-Öğrenmeler kalıcıdır.\n-Çevre önemli bir etkendir.\n-Öğrenmenin unutulması veya kaybolması beklenmez.\n-Olumlu yönde olması tercih edilse de olumsuz da olabilir.\n-Davranış değişikliği gerektirir.\n-Refleksif hareketler öğrenme kabul edilmez."),
      InfoCardItem("eo_Info_281","Öğrenme-2","-Öğrenmenin kalıcı olması, gözlenebilir olması, yaşantı sonucu gerçekleşmesi ve değişimin yalnızca büyüme ve olgunlaşmaya bağlı olmaması gerekir."),
      InfoCardItem("eo_Info_282","Psikoloji","-İnsan davranışlarını ve davranışlarının altında yatan sebepleri inceler.\n-Davranışlar bilinç dışı süreçlerde kayıtlı bazı olay ve olgular sebebiyle sergileniyor olabilir.\n-Bu olay ve olgular tespit edilerek bireyin olumlu yönde gelişmesi sağlanabilir."),
      InfoCardItem("eo_Info_283","Öğrenme Psikolojisi","-Öğrenme ve psikolojide ortak unsur davranıştır.\n-Psikoloji biliminin öğrenme odaklı olması öğrenme psikolojisi kavramını ortaya çıkartır.\n-Öğrenmenin nasıl gerçekleştiğini, öğrenmeyi etkileyen faktörleri, öğrenmeler arası disiplinleri, öğrenmede bireysel farklılıkları ve öğrenmeyi oluşturan unsurları inceler."),

    ]),InfoCardModel("Öğrenme Psikolojisi-2", [
      InfoCardItem("eo_Info_284","Temel kavramlar","Davranış: Dış dünyada gözlemlenebilen her türlü etkinliğidir.\n-Bilişsel, duyuşsal, psikomotor, öğrenilmiş, istendik, istenmedik, geçici ve refleksif olabilir."),
      InfoCardItem("eo_Info_285","Bilişsel davranış","-Zihinsel süreç gerektiren davranışlardır.\n-Eylemin yapılmasında sebep sonuç ilişkisi kurma, dikkat etme, hatırlama, yorum çıkartma ve hayalgücünü kullanma gibi zihinsel süreçler etkilidir."),
      InfoCardItem("eo_Info_286","Duyuşsal davranış","-Duygular ön plandadır.\n-Sevinç, üzüntü, korku, heyecan gibi duyguların beyin süzgecinden geçerek davranışa dönüşmesidir."),
      InfoCardItem("eo_Info_287","Psikomotor davranış","-El göz koordinasyonu gerektirir.\n-Yürüme, koşma, zıplama, kaldırma gibi fiziksel aktiviteler içerir."),
      InfoCardItem("eo_Info_288","Öğrenilmiş davranış","-Davranış öğrenme ürünüdür.\n-Öğrenme ürünü olan davranışlar kalıcır olur."),
      InfoCardItem("eo_Info_289","İstendik davranış","-Öğrenme planlı bir eğitim sürecinde gerçekleşir.\n-Gelişigüzel kültürlenme sonucu da öğrenme gerçekleşebilir."),
      InfoCardItem("eo_Info_290","İstenmedik davranış","-Öğrenme hatalı eğitim sürecinde gerçekleşir.\n-Kötü kültürlenme de öğrenmeye sebep olmuş olabilir."),
      InfoCardItem("eo_Info_291","Geçici davranış","-İlaç kullanımı ve alkol gibi durumlar sebebiyle ortaya çıkan davranışlardır.\n-Davranışlar kalıcı değil kısa sürelidir."),
      InfoCardItem("eo_Info_292","Doğuştan gelen davranış","-Refleksif, içgüdüsel ve kontrol dışı ortaya çıkan davranışlardır."),

    ]),InfoCardModel("Öğrenme Psikolojisi-3", [
      InfoCardItem("eo_Info_293","Öğrenmeyi etkileyen faktörler","-Öğrenenle ilgili faktörler,\n-Öğrenme yöntemi ile ilgili faktörler,\n-Öğrenme malzemesi ile ilgili faktörler,"),
      InfoCardItem("eo_Info_294","Öğrenenle ilgili faktörler","-Türe özgü hazıroluş,\n-Olgunlaşma,\n-Genel uyarılmışlık düzeyi,\n-Güdü,\n-Eski yaşantılar,\n-Dikkat"),
      InfoCardItem("eo_Info_295","Türe özgü hazıroluş","-Bazı davranışların öğrenilebilmesi için gerekli biyolojik yeterlilikler bulunur.\n-Organizma bu donanıma sahip değilse davranış öğrenilemez."),
      InfoCardItem("eo_Info_296","Olgunlaşma","-Bazı davranışların gerçekleştirilebilmesi için fiziksel ve zihinsel yeterliliğin olması gerekir.\n-Bunlar yaş ve zeka ile ilgili olabilir.\n-Ancak bu olgunlaşma sağlanırsa öğrenme gerçekleşir."),
      InfoCardItem("eo_Info_297","Genel uyarılmışlık düzeyi","-Çevreden gelen uyarıcıların birey tarafından alınma düzeyidir.\n-Belirli bir düzeye kadar öğrenmeyi olumlu yönde etkiler.\n-Belirli bir düzey sonrası öğrenmeyi olumsuz etkiler."),
      InfoCardItem("eo_Info_298","Güdü","-İhtiyaç sonucu ortaya çıkar.\n-Organizmayı davranışa sürükler."),
      InfoCardItem("eo_Info_299","Eski yaşantılar","-Bireyin önceki öğrenmelerinin yeni öğrenmelerine olan etkisidir.\n-Öğrenmeyi olumlu veya olumsuz yönde etkileyebilir."),
      InfoCardItem("eo_Info_300","Dikkat","-Öğrenmeyi etkileyen en temel faktörlerdendir.\n-Birey kendi ihtiyaçlarından dolayı dikkatli ise istemlidir.\n-Dikkat çevresel güçlü uyarıcılar sebebiyle oluyorsa istemsiz dikkattir."),
      InfoCardItem("eo_Info_301","Öğrenme yöntemi ile ilgili faktörler","-Konunun yapısı,\n-Zaman kullanımı,\n-Dönüt,\n-Etkin katılım"),
      InfoCardItem("eo_Info_302","Konunun Yapısı","-Konunun nasıl öğrenileceğini kapsar.\n-Bütün halinde veya parçalara bölünerek çalışılabilir.\n-En etkili yöntem bütün-parça-bütün yöntemidir.\n-Bu yöntemde konu önce bütünüyle ele alınır.\n-Sonra parçalara bölünerek çalışılır.\n-Daha sonra tekrar bütün olarak ele alınır."),
      InfoCardItem("eo_Info_303","Zaman kullanımı","Konunun toplu olarak veya zamansal aralıklarla çalışılması öğrenme yöntemi ile ilgilidir."),
      InfoCardItem("eo_Info_304","Dönüt","-Öğrenmenin ne düzeyde gerçekleştiği hakkında öğrenene bilgi verme sürecidir.\n-Dönüt, öğrenene sık sık verilmelidir.\n-Dönüt hemen verilirse, öğrenmedeki aksaklıklar daha hızlı giderilebilir."),
      InfoCardItem("eo_Info_305","Etkin katılım","-Öğrenenin öğrenilecek konu için süreçte tüm dikkatiyle varolmasıdır.\n-Katılım arttıkça öğrenme artar."),
    ]),InfoCardModel("Öğrenme Psikolojisi-4", [
      InfoCardItem("eo_Info_305","Etkin katılım","-Öğrenenin öğrenilecek konu için süreçte tüm dikkatiyle varolmasıdır.\n-Katılım arttıkça öğrenme artar."),
      InfoCardItem("eo_Info_306","Öğrenme malzemesi ile ilgili faktörler","-Algısal ayırt edilebilirlik,\n-Anlamsal çağrışım,\n-Kavramsal gruplandırma,\n-Çağrışımsal gruplandırma,\n-Telaffuz edilebilirlik"),
      InfoCardItem("eo_Info_307","Algısal ayırt edilebilirlik","-Uyarıcının o an çevrede varolan tüm uyarıcılardan daha güçlü olması durumudur.\n-Bu durumda odak noktası güçlü uyarıcıdadır.\n-Öğrenmeyi direkt olarak etkiler."),
      InfoCardItem("eo_Info_308","Anlamsal çağrışım","-Öğrenme sırasında geçmiş öğrenmelerle bağ kurmaktır.\n-Yani yeni öğrenmeler önceki öğrenmelerden esinlenilerek gerçekleştirilir."),
      InfoCardItem("eo_Info_309","Kavramsal gruplandırma","-Konuların birbiri ile ilişkilerinin haritalama ile ortaya çıkarılmasıdır.\n-Hiyerarşik düzende ilişkilendirme yapılır.\n-Kavram haritası mantığı kullanılır."),
      InfoCardItem("eo_Info_310","Çağrışımsal gruplandırma","-İçeriğin deneyimlerle ve bilgilerle ilişkilendirilmesidir.\n-Çağrışım sayısı ne kadar artarsa, hatırlama düzeyi o kadar artar."),
      InfoCardItem("eo_Info_311","Telaffuz edilebilirlik","-İçeriğin dilsel gelişime uygun olarak verilmesidir.\n-Konu uygun ve anlaşılır örneklerle açıklanır."),
      //InfoCardItem("eo_Info_312","Öğrenme Kuramları","-Davranışçı Kuramlar,\n-Bilişsel Ağırlıklı Davranışsal Kuramlar,\n-Bilişsel Kuramlar"),
      //InfoCardItem("eo_Info_313","Davranışçı Kuramlar-1","-Klasik koşullanma (Pavlov),\n-Bitişiklik kuramı (Watson, Guthire),\n-Bağ kuramı (Thorndike),\n-Edimsel koşullanma (Skinner)"),
      //InfoCardItem("eo_Info_314","Davranışçı Kuramlar-2","-Somut ve gözlemlenebilir olmalıdır.\n-Araştırmalar nesnel sonuçlara ulaşmalıdır.\n-Zihin doğuşta boş bir levhadır.\n-Öğrenmelerin tamamı yaşantı içindedir.\n-Soyut kavramlar devre dışı bırakılmıştır."),
      //InfoCardItem("eo_Info_315","",""),
      //InfoCardItem("eo_Info_316","",""),
      //InfoCardItem("eo_Info_317","",""),
      //InfoCardItem("eo_Info_318","",""),
      //InfoCardItem("eo_Info_319","",""),
      //InfoCardItem("eo_Info_32","",""),
      //InfoCardItem("eo_Info_32","",""),
    ]),*/


  ];

  //Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği asdf
  InfoCardModel("Başlık", [
      InfoCardItem("ALTBAŞLIK","",),
    ]),
    */
  List<InfoCardModel> get egitimOgretimInfoCard => _egitimOgretimInfoCard;
}
