import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class EgitimKapsayiciInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _egitimKapsayiciList = [
    InfoCardModel("Eğitimde Kapsayıcılık-1", [
      InfoCardItem("egitimkapsayici_info_1", "Nedir", "Öğrencinin merkezde olduğu, öğrenci istek ve ihtiyaçlarının tespit edilmesiyle oluşturulan ve tüm öğrencileri kapsayan eğitimdir.\n-Tüm çocukların gelişimsel süreçleri dikkate alınır.\n-Eğitimde fırsat eşitliği sağlanır.\n-Öğrencinin kendi yaşantısıyla öğrenmesi esastır."),
      InfoCardItem("egitimkapsayici_info_2", "Özellikleri", "-Öğrenci odaklıdır.\n-Bireysel özellikler dikkate alınır.\n-Öğrencilerin ihtiyaçları merkezdedir.\n-Eşitlik ilkesine dayanır.\n-Eğitime ulaşma güçlüğü çeken öğrencilere de ulaştırılır.\n-Sürece ailenin de aktif katılımı beklenir."),
      InfoCardItem("egitimkapsayici_info_3", "Özellikleri", "-Öğrencilerin okula uyum sağlamalarını değil, okulun öğrencilere uyum sağlamalarını temel alır.\n-Cinsiyet, etnik köken, engel durumu gibi özellikleri varlığını yok sayarak eşit imkanlarda eğitim modelini savunur.\n-Ekonomik gelirin düşük olmasından kaynaklı eğitim ihtiyaçlarının giderilmesini hedefler."),
      InfoCardItem("egitimkapsayici_info_4", "İlkeleri", "-Tüm öğrenciler eşit imkan ve şartlarda eğitim almalıdır.\n-Engeli sebebiyle eğitimden uzak kalan bireyler sürece dahil edilmelidir.\n-Toplum tarafından veya herhangi bir sebeple dışlanma riski taşımakta olan çocukların korunması gerekir.\n-Öğrencilerin ihtiyaçlarına göre etkinlikler planlanmalıdır.\n-Öğrencilerin iyi oldukları konuları açığa çıkarmalarına müsade edilir."),

    ]),InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
    /*InfoCardModel("", [
 InfoCardItem("egitimkapsayici_info_5", "", ""),
      InfoCardItem("egitimkapsayici_info_6", "", ""),
      InfoCardItem("egitimkapsayici_info_7", "", ""),
      InfoCardItem("egitimkapsayici_info_8", "", ""),
      InfoCardItem("egitimkapsayici_info_9", "", ""),
      InfoCardItem("egitimkapsayici_info_10", "", ""),
      InfoCardItem("egitimkapsayici_info_11", "", ""),
      InfoCardItem("egitimkapsayici_info_12", "", ""),
      InfoCardItem("egitimkapsayici_info_13", "", ""),
      InfoCardItem("egitimkapsayici_info_14", "", ""),
      InfoCardItem("egitimkapsayici_info_15", "", ""),
      InfoCardItem("egitimkapsayici_info_16", "", ""),
      InfoCardItem("egitimkapsayici_info_17", "", ""),
      InfoCardItem("egitimkapsayici_info_18", "", ""),
      InfoCardItem("egitimkapsayici_info_19", "", ""),
      InfoCardItem("egitimkapsayici_info_20", "", ""),
      InfoCardItem("egitimkapsayici_info_21", "", ""),
      InfoCardItem("egitimkapsayici_info_22", "", ""),
      InfoCardItem("egitimkapsayici_info_23", "", ""),
      InfoCardItem("egitimkapsayici_info_24", "", ""),
      InfoCardItem("egitimkapsayici_info_25", "", ""),
      InfoCardItem("egitimkapsayici_info_26", "", ""),
      InfoCardItem("egitimkapsayici_info_27", "", ""),
      InfoCardItem("egitimkapsayici_info_28", "", ""),
      InfoCardItem("egitimkapsayici_info_29", "", ""),
      InfoCardItem("egitimkapsayici_info_30", "", ""),
      InfoCardItem("egitimkapsayici_info_31", "", ""),
      InfoCardItem("egitimkapsayici_info_32", "", ""),
      InfoCardItem("egitimkapsayici_info_33", "", ""),
      InfoCardItem("egitimkapsayici_info_34", "", ""),
      InfoCardItem("egitimkapsayici_info_35", "", ""),
      InfoCardItem("egitimkapsayici_info_36", "", ""),
      InfoCardItem("egitimkapsayici_info_37", "", ""),
      InfoCardItem("egitimkapsayici_info_38", "", ""),
      InfoCardItem("egitimkapsayici_info_39", "", ""),
      InfoCardItem("egitimkapsayici_info_40", "", ""),
      InfoCardItem("egitimkapsayici_info_41", "", ""),
      InfoCardItem("egitimkapsayici_info_42", "", ""),
      InfoCardItem("egitimkapsayici_info_43", "", ""),
      InfoCardItem("egitimkapsayici_info_44", "", ""),
      InfoCardItem("egitimkapsayici_info_45", "", ""),
      InfoCardItem("egitimkapsayici_info_46", "", ""),
      InfoCardItem("egitimkapsayici_info_47", "", ""),
      InfoCardItem("egitimkapsayici_info_48", "", ""),
      InfoCardItem("egitimkapsayici_info_49", "", ""),
      InfoCardItem("egitimkapsayici_info_50", "", ""),
      InfoCardItem("egitimkapsayici_info_51", "", ""),
      InfoCardItem("egitimkapsayici_info_52", "", ""),
      InfoCardItem("egitimkapsayici_info_53", "", ""),
      InfoCardItem("egitimkapsayici_info_54", "", ""),
      InfoCardItem("egitimkapsayici_info_55", "", ""),
      InfoCardItem("egitimkapsayici_info_56", "", ""),
      InfoCardItem("egitimkapsayici_info_57", "", ""),
      InfoCardItem("egitimkapsayici_info_58", "", ""),
      InfoCardItem("egitimkapsayici_info_59", "", ""),
      InfoCardItem("egitimkapsayici_info_60", "", ""),
      InfoCardItem("egitimkapsayici_info_61", "", ""),
      InfoCardItem("egitimkapsayici_info_62", "", ""),
      InfoCardItem("egitimkapsayici_info_63", "", ""),
      InfoCardItem("egitimkapsayici_info_64", "", ""),
      InfoCardItem("egitimkapsayici_info_65", "", ""),
      InfoCardItem("egitimkapsayici_info_66", "", ""),
      InfoCardItem("egitimkapsayici_info_67", "", ""),
      InfoCardItem("egitimkapsayici_info_68", "", ""),
      InfoCardItem("egitimkapsayici_info_69", "", ""),
      InfoCardItem("egitimkapsayici_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get egitimKapsayici => _egitimKapsayiciList;}