import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class GuvenliOkulInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _guvenliOkulList = [
    InfoCardModel("Genel Bakış", [
      InfoCardItem("ii_guvenliokul_info_1", "Güvenli Okul-1", "-Şiddet olgusu insanlık tarihi kadar eskidir ve bu olgu yüzyıllardır insanlığın en temel sorunlarından birisi olmuştur.\n-Bu tür sorunların okullarda yaşanmaması söz konusu değildir.\n-Güvenli okul ve okul güvenliği yaklaşımları, bu olayların okullarda yaşanma durumunu en aza indirgemek için ortaya çıkmıştır. "),
      InfoCardItem("ii_guvenliokul_info_2", "Güvenli Okul-2", "-Güvenlik tanımının yeniden yapıldığı, bireylerin kendilerini daha güvensiz hissettiği bu çağda, okullarda yaşanan şiddet olayları ve güvenlik ihlalleri, şiddetin önlenmesi ve okul paydaşları için güvenliğin sağlanmasını tüm dünya için çok önemli bir konu haline getirmiştir.\n-Okulların temel görevlerinden biri de öğrencilerin, istenmeyen davranışlardan arındırılması, kendilerini güvende hissetmeleri ve okulda güvenliklerinin sağlanmasıdır."),
      InfoCardItem("ii_guvenliokul_info_3", "Güvenli Okul-3", "-Eğitim öğretim süreçlerini, uygun bir okul ikliminde, şiddetten, endişeden ve korkudan arınmış şekilde gerçekleştiren okullar güvenli okullardır.\n-Olumlu bir okul iklimi şiddeti önleme ve güvenliği tesis etme noktasında en önemli unsurlardan biridir.\n- Okul iklimi, okul içi ve dışındaki tüm paydaşların (öğretmen, öğrenci, okul personeli, veli) ilişkilerinin toplamı olarak tanımlanabilir."),
      InfoCardItem("ii_guvenliokul_info_4", "Güvenli Okul-4", "-Bu ilişkiler tüm paydaşlar arasındaki sosyal bağlar ve ilişkiler, eğitsel ve yönetsel süreçlerdir.\n-Güven ortamı tesis edilmiş bir okul her türlü korku, zorbalık ve endişeden uzaktır. \n-Bu tür okullarda davranış beklentileri açık bir şekilde ifade edilmiştir ve okul iklimi öğrenciyi destekleyici niteliktedir. \n- Böyle bir ortam tüm paydaşlar için kabul duygusunun hüküm sürdüğü bir iklim sağlar. "),
      InfoCardItem("ii_guvenliokul_info_5", "Olumlu Okul İkliminin Faydaları", "-Öğrenciler yüksek akademik başarı gösterme eğilimindedirler. \n-Öğrencilerin okula olan bağlılıkları ve sevgileri fazladır. Okulda zaman geçirmek ve tüm aktivitelere katılmak isterler. \n-Okulda tüm paydaşlar kurallara uyarlar ve kural ihlallerini en alt düzeyde tutarlar. "),
      InfoCardItem("ii_guvenliokul_info_6", "Olumlu Okul İkliminin Faydaları", "-Öğrenciler kendi aralarındaki farklılıklara hoşgörü ile yaklaşırlar. \n-Okuldaki tüm paydaşlar olumlu davranışlar sergilerler. (Birbirine saygı duyma, yardım etme, kendi sorumluluklarını yerine getirme vb.) \n-Okulun daha etkin olmasını ve amacına uygun bir işlerlik kazanmasını sağlar. "),
      InfoCardItem("ii_guvenliokul_info_7", "Olumlu Okul İkliminin Faydaları", "-Engelleri olan ya da eğitsel olarak dezavantajlı öğrencilere karşı daha destekleyici ve özenli bir eğitim-öğretim ortamı sunulur. \n-Veliler eğitime karşı ilgilidirler ve okul ile iş birliği halindedirler."),
          ]),
    InfoCardModel("Olumlu Davranış Desteği", [
      InfoCardItem("ii_guvenliokul_info_8", "Temel Yaklaşımlar", "-Bilgiye Dayalı Yönetim Anlayışı\n-Çoklu Kurumlar ve Çoklu Disiplin Yaklaşımı\n-Bütüncül Yaklaşım\n-Gelişimsel Yaklaşım\n-Önleme Koruma ve Müdahale Yaklaşımı\n-Kapasite Artırımı\n-Sürdürülebilir Hizmet\n-İzleme ve Değerlendirme Çalışmaları"),
      InfoCardItem("ii_guvenliokul_info_9", "Bilgiye Dayalı Yönetim Anlayışı", "Güvenli okul kapsamında yapılacak uygulamalarda kullanılmak üzere bilimsel, güvenilir ve güncel verilerin toplanması.\n-Toplanan bu verilerin ilgili çalışmalarda rehberlik amacıyla kullanılması."),
      InfoCardItem("ii_guvenliokul_info_10", "Çoklu Kurumlar ve Çoklu Disiplin Yaklaşımı", "Tüm uygulamaların iş birliği içerisinde katılımcı ve çoğulcu bir anlayışa dayalı olarak farklı kurumların ve yaklaşımların ele alınarak gerçekleştirilmesi."),
      InfoCardItem("ii_guvenliokul_info_11", "Bütüncül Yaklaşım", "Tüm paydaşların (Yönetici, öğretmen, öğrenci, okul, aile ve çevre) kapsamı çok geniş olan güvenli eğitim olgusunu kapsayacak şekilde sürece dahil edilmesi.\n-Okul çalışanlarının düzenli olarak desteklenmesi ve kurumsal aidiyet duygularının kuvvetlendirilmesi."),
      InfoCardItem("ii_guvenliokul_info_12", "Gelişimsel Yaklaşım", "-Öğrencinin zihinsel, fiziksel, duygusal kapasitesine uygun gelişim gösterebilmesi için psikolojik danışma ve rehberlik hizmeti sunulması,\n-Tüm alanlarda gelişiminin sağlanması.\n-Sunulan psikolojik danışma ve rehberlik hizmetinin öğrenciyi destekler nitelikte ve planlı olması."),
      InfoCardItem("ii_guvenliokul_info_13", "Önleme Koruma ve Müdahale Yaklaşımı", "Eğitim-öğretim sürecinde olumsuz olayların henüz gerçekleşmeden önleme çalışmalarının yapılması, şiddete ya da zorbalığa maruz kalan bireyler için koruma ve müdahale çalışmalarının gerçekleştirilmesi."),
      InfoCardItem("ii_guvenliokul_info_14", "Kapasite Artırımı", "-Okulun altyapı, materyal ve kaynak kapasitelerinin arttırılması, yönetici ve öğretmenlerin kişisel gelişimlerinin desteklenerek insan kaynağının verimli ve etkili kullanılması,\n-Ailelere yönelik çalışmaların yapılması.\n-Tüm okul personelinin öğrencilere yönelik olumlu davranış kazandırma ve problemlerle başa çıkma yeterliliklerinin arttırılması."),
      InfoCardItem("ii_guvenliokul_info_15", "Sürdürülebilir Hizmet", "-Hedefe dayalı bilimsel ve gerçekçi planlar yapılması ve model geliştirilmesi,\n-Kurumsal tespit çalışmaları ile önleyici tedbirler geliştirilmesi,"),
      InfoCardItem("ii_guvenliokul_info_16", "İzleme ve Değerlendirme Çalışmaları", "-Gerçekleştirilen uygulama ve çalışmaların etkinliklerinin izlenmesi ve değerlendirmelerinin yapılması,\n-Değerlendirmeler sonucu uygulamaların sürekli olarak iyileştirilmesi ve geliştirilmesi."),
    ]),
    InfoCardModel("Okul İklimini Zayıflatan Faktörler", [
      InfoCardItem("ii_guvenliokul_info_17", "Okul İklimini Zayıflatan Faktörler", "-Adaletsiz, tutarsız ve cezalandırıcı yönetimsel uygulamalar.\n-Cezalandırıcı öğretmen uygulamaları.\n-Kuralların açık, net ve tutarlı olmaması.\n-Yanlış davranışların görmezden gelinmesi."),
      InfoCardItem("ii_guvenliokul_info_18", "Okul İklimini Zayıflatan Faktörler", "-Kuralların uygulanmasında bütüncül bir hassasiyet gösterilmemesi.\n-Öğrencilerin kuralların gerekliliğine ve meşruluğuna inanmamaları.\n-İstendik davranışlara yönelik açık ve gerçekçi olmayan beklentiler.\n-Öğretimin etkisizliği ve akademik başarı düzeyinin düşük olması."),
      InfoCardItem("ii_guvenliokul_info_19", "Okul İklimini Zayıflatan Faktörler", "-Eğitim ve öğretimin öğrencinin bireysel farklılık ya da ilgilerine göre düzenlenmemiş olması.\n-Öğretim imkanlarının yetersizliği, altyapı, kaynak ve materyal eksikliği.\n-Yönetici ve idarecilerin arasındaki bağ ve iş birliğinin zayıf olması."),
      InfoCardItem("ii_guvenliokul_info_20", "Okul İklimini Zayıflatan Faktörler", "-Kişisel ve mesleki gelişim konusunda okul çalışanlarının isteksiz olması.\n-Öğretmen ve yöneticilerin mesleki tükenmişlik yaşamaları.\n-Yöneticilerin pasifliği."),
 ]),InfoCardModel("Okullarda Karşılaşılan Davranış Problemleri-1", [
      InfoCardItem("ii_guvenliokul_info_21", "Zorbalık", "Bireyin tekrarlar nitelikte ve belirli bir süre zarfında maruz kaldığı sözel, psikolojik veya fiziksel davranışlara zorbalık adı verilir. "),
      InfoCardItem("ii_guvenliokul_info_22", "Zorbalık", "Zorbalık davranışlarının en sık görüldüğü yerlerden biri de okuldur. Okulda görülen zorbalık davranışları genellikle öğrencinin akranları tarafından gerçekleştirilmektedir. "),
      InfoCardItem("ii_guvenliokul_info_23", "Zorbalık", "Zorbalığı gerçekleştiren öğrenci ya da öğrenci gurubu isteyerek ve tekrarlar nitelikte kendilerinden daha güçsüz gördükleri öğrencilere zarar vermektedirler. "),
      InfoCardItem("ii_guvenliokul_info_24", "Zorbalık", "-Zorbalığa maruz kalan öğrenci bu saldırganlık sürecinde kendini fiziksel ve psikolojik olarak koruyamayacak bir durumdadır.\n-Akran zorbalığı okullarda çok farklı biçimlerde kendini göstermektedir. "),
      InfoCardItem("ii_guvenliokul_info_25", "Zorbalık", "Okullarda en sık görülen zorbalık davranışları tokat atma, itme, çekme, tekme atma, dalga geçme, uygun olmayan lakap takma, aşağılayıcı sözler söyleme, alay etme, sataşma, küfür, eşyalarının-parasının isteği dışında alınması, bireyi dedikodu ve söylentiler ile yalnızlığa itme, eşyalarına zarar verme olarak listelenebilir."),
      InfoCardItem("ii_guvenliokul_info_26", "Zorbalık", "Okullarda yaşanan zorbalık davranışlarından da anlaşılabileceği üzere, zorbalık sadece fiziksel olarak değil, psikolojik ve duygusal olarak da kendini gösteren bir olgudur."),
 ]),InfoCardModel("Okullarda Karşılaşılan Davranış Problemleri-2", [
      InfoCardItem("ii_guvenliokul_info_27", "Saldırganlık", "Saldırganlık öfke duygusunun yol açtığı zarar veren, başkalarını inciten ya da incitebilecek bir davranıştır.\n-Şiddet kavramı ile saldırganlık kavramı sık sık birbirine karıştırılmaktadır."),
      InfoCardItem("ii_guvenliokul_info_28", "Saldırganlık", "-Şiddet kavramına bir sonraki bölümde ayrıntılı olarak yer verilecektir.-Okullarda görülen en sık saldırganlık türleri şunlardır:\n-1.	Düşük Düzeyde Saldırganlık\n-Taşınmaz Mala Karşı Saldırganlık\n-Tehditler\n-Fiziksel Saldırganlık"),
      InfoCardItem("ii_guvenliokul_info_29", "Düşük Düzeyde Saldırganlık", "Kötü sözler söyleme, dürtme, itme, kötü ifadeler barındıran duvar yazıları yazma, başkasının eşyasını alma gibi davranışları kapsamaktadır."),
      InfoCardItem("ii_guvenliokul_info_30", "Taşınmaz Mala Karşı Saldırganlık", "Okula ait demirbaş eşyalara, öğretim materyallerine zarar verme, yangın çıkarma gibi kurumlarda ciddi sonuç ve zararlar doğurabilen eylemleri kapsamaktadır."),
      InfoCardItem("ii_guvenliokul_info_31", "Tehditler", "Öğrencinin başka bir öğrenciyi, okul çalışanını ya da farklı bir paydaşı tehdit etmesi gibi durumları kapsar."),
      InfoCardItem("ii_guvenliokul_info_32", "Fiziksel Saldırganlık", "Fiziksel temas ile dalga geçme, taciz, kavga, tartışma, silah taşıma ya da kullanma gibi davranışlar fiziksel saldırganlık kapsamına girmektedir."),

 ]),InfoCardModel("Okullarda Karşılaşılan Davranış Problemleri-3", [
      InfoCardItem("ii_guvenliokul_info_33", "Şiddet", "En temel tanımıyla şiddet, insanların bedensel bütünlüğüne karşı yapılan sert ve acı verici bir eylemdir.\n-. Öğrenci şiddeti ise okulda öğrenciler arasında yaşanan ve bir öğrencinin fiziksel, psikolojik ya da cinsel olarak zarar gördüğü eylemlerdir. "),
      InfoCardItem("ii_guvenliokul_info_34", "Şiddet", "Farklı şiddet türleri bulunmaktadır ve şiddet türleri genel olarak biçimine göre adlandırılmaktadırlar.\n- Örnek olarak fiziksel, psikolojik ve cinsel şiddet verilebilir. "),
      InfoCardItem("ii_guvenliokul_info_35", "Şiddet", "Dünya Sağlık Örgütü’nün (2002) hazırlamış olduğu raporda, şiddet üç bölümde ele alınmıştır:\n-Kendine Yöneltilmiş Şiddet\n-Kişilerarası Şiddet\n-Kolektif Şiddet"),
      InfoCardItem("ii_guvenliokul_info_36", "Kendine Yöneltilmiş Şiddet", "-Kendine zarar verme ve intihar davranışı olarak ikiye ayrılmaktadır.\n-İntihar girişimleri ve intiharlar, kendine zarar verme, kendini yaralama ya da kendini ihmal etme davranışları olarak görülebilmektedir."),
      InfoCardItem("ii_guvenliokul_info_37", "Kişilerarası Şiddet", "-Fiziksel, cinsel ve psikolojik olmak üzere iki temel kategoride incelenmektedir.\n-İlk kategorideki fiziksel şiddet aile, yakın ya da tamamen yabancı kişilerle her türlü yerde yaşanabilecek bir şiddet türüdür.\n-Cinsel ve psikolojik şiddet ise daha çok sokak, okul, iş yeri, hapishane ve yaşlı bakımevi gibi yerlerde karşılaşılan istismar ve psikolojik durumları içeren bir şiddet türüdür. "),
      InfoCardItem("ii_guvenliokul_info_38", "Kolektif Şiddet", "-Sosyal, ekonomik ve politik olarak üç bölümde incelenmiştir.\n-Sosyal şiddet, organize olarak yapılan nefret suçları, suç örgütlerince yapılan eylemler ve terörist saldırıları içermektedir."),
      InfoCardItem("ii_guvenliokul_info_39", "Kolektif Şiddet", "-Politik şiddet ile savaş ve bununla ilgili şiddet içeren anlaşmazlıklar ifade edilmiştir.\n-Ekonomik şiddet ise ekonomik kazanım amaçlı, tekel oluşturma, ekonomik etkinliği bozma, gerekli hizmetlere ulaşımı engelleme, ekonomik sorunlar çıkarma, ayrımcılık yaratma gibi büyük gruplarca yapılan saldırıları içermektedir."),

 ]),InfoCardModel("Okullarda Karşılaşılan Davranış Problemleri-4", [
      InfoCardItem("ii_guvenliokul_info_40", "", "Okul Yıllarında Risk Altındaki Çocuklarda Görünen Davranışlar;\n-Erken Çocukluk Dönemi\n-Orta Çocukluk Dönemi\n-Erken Ergenlik Dönemi"),
      InfoCardItem("ii_guvenliokul_info_41", "Erken Çocukluk Dönemi", "-6-8 yaş aralığını kapsar.\n-Düşük akademik başarı, akranlarına karşı agresif tutumlar, sınıfta davranış bozukluğu, akranlarınca dışlanma"),
      InfoCardItem("ii_guvenliokul_info_42", "Orta Çocukluk Dönemi", "-9-12 yaş aralığını kapsar.\n-Okula ve derse karşı ilgi kaybı, düşük akademik başarı, akranlarıyla zayıf ilişkiler, ani tepkiler ve agresiflik"),
      InfoCardItem("ii_guvenliokul_info_43", "Erken Ergenlik Dönemi", "-12-15 yaş aralığını kapsar.\n-Devamsızlık, düşük akademik başarı, anti sosyal davranışlar, anormal arkadaş bağlantıları, hedef ve değerlerde yaşanan erozyon"),
 ]),InfoCardModel("Okullarda Saldırganlık, Zorbalık ve Şiddeti Önleme", [
      InfoCardItem("ii_guvenliokul_info_44", "Başlıklar", "Okullarda saldırganlık, zorbalık ve şiddeti önleme çalışmaları üç başlık altında incelenir. Bunlar\n\n-Çevresel düzenlemeler,\n-Okul-Yönetim Temelli stratejiler\n-Eğitim ve Program Temelli Stratejiler olarak başlıklara bölünebilir."),
      InfoCardItem("ii_guvenliokul_info_45", "Çevresel Düzenlemeler-1", "-Gün geçtikçe ülkemizde ve dünyada maalesef şiddete olan eğilim artmaktadır. Bunun birçok farklı sebebi bulunmaktadır. Özellikle dijital içerik üreten platformlarda, şiddetin özendiren içerikler yaş grupları itibariyle öğrencileri daha çok etkilemektedir.\n-Öğrencilerin istemli veya istemsiz içine girdiği bu süreç okul çevresinde düzenlemeler yapma zorunluluğunu arttırmaktadır."),
      InfoCardItem("ii_guvenliokul_info_46", "Çevresel Düzenlemeler-2", "-Okul sadece öğrencilerin bulunduğu bir alan değildir.\n-Okul çevresi tanımında okulu etkileyen olaylar, olgular ve düşüncelerin tümü de yer almaktadır. Bu yüzden okul ve okulun bulunduğu sosyal çevre okul güvenliğini bizzat ilgilendirmektedir. "),
      InfoCardItem("ii_guvenliokul_info_36", "Çevresel Düzenlemeler-3", "-Saldırganlık ve şiddeti önlemek adına okul içinde ve çevresinde gerekli önlemleri almak gerekir.\n-Suç oranı fazla olan mahallelere kurulmuş okullarda standart önlemler dışında daha detaylı tedbirler alınması, gerekirse kolluk kuvvetlerinden yardım alınması yararlı olacaktır.\n-Bu tedbirler sadece okul dışından gelecek tedbirlerle sınırlı kalmamalıdır.\n-Okul içinde yaşanacak saldırganlık, zorbalık ve şiddet için de okul yönetiminin alması gereken tedbirler bulunmaktadır."),
      InfoCardItem("ii_guvenliokul_info_37", "Okul-Yönetim Temelli Stratejiler", "-Okul içi ve dışı yaşanacak saldırganlık, zorbalık ve şiddet olaylarından birinci derecede sorumlu olan kişiler okul yönetimidir.\n-Okul içindeki ve dışındaki şartlara göre gerekli tedbirlerin alınmasından sorumludurlar.\n-Okullardaki yönetimsel uygulamalar ve kurallar bu güvenli ortamı oluşturmayı hedeflemelidir.\n-Okul güvenliğine ilişkin detaylar daha sonra ayrıntılı olarak incelenecektir."),
      InfoCardItem("ii_guvenliokul_info_38", "Eğitim ve Program Temelli Stratejiler", "-Okul güvenliğinin sağlanması için yapılabilecek bir diğer çalışma Eğitim ve Program Temelli Stratejilerin geliştirilmesidir.\n-Yaşanabilecek olumsuz olaylarla karşılaşmadan önce eğitim programı içerisinde şiddet ve saldırganlığı azaltacak faaliyetler yürütülmelidir.\n-Bu programlar okul içi ve okul dışı faaliyetler ile desteklenmelidir."),

      ]),
    InfoCardModel("Okul Güvenliği", [
      InfoCardItem("ii_guvenliokul_info_39", "Giriş", "-Okullarda yaşanan olumsuz olaylar (şiddet, saldırganlık, hırsızlık, taciz, zorbalık gibi…) öğrenciler ve okul çalışanları için tehdit oluşturmaktadır.\n-Bu durum pek çok ailenin, çocuklarının okuldaki güvenliği ile ilgili olarak endişe duymasına neden olmaktadır.\n-Okul iklimini olumsuz olarak etkileyen, eğitim öğretim sürecine zarar veren veya engelleyen her davranış okul güvenliği kapsamında ele alınmalıdır.\n-Öncelikle Okul Güvenliği terimine daha detaylı göz atalım. "),
      InfoCardItem("ii_guvenliokul_info_39_11", "Tanım-1", "Bir okul içerisinde yer alan tüm personelin kendilerini, fiziksel, psikolojik ve duygusal bakımdan rahat hissetmelerini ve öğrenme için uygun durumun sağlanmasına Okul Güvenliği denir. "),
      InfoCardItem("ii_guvenliokul_info_39_22", "Tanım-2", "-Okul güvenliği “öğrencilerin, öğretmenlerin ve diğer personelin kendilerini fiziksel, psikolojik ve duygusal bakımdan özgür hissetmeleridir” (Dönmez, 2001, 64).\n-Okul güvenliği “okulda öğrenme için uygun bir ortam yaratılmasıdır” (Güven, 2002, 68).\n-Kendisini güvende hissetmeyen bir öğrencinin öğrenmeye güdülenebilmesi Maslow’un motivasyon teorisine göre de çok zor hatta mümkün değildir."),
      InfoCardItem("ii_guvenliokul_info_40", "Okul Güvenliği-1", "-Öğrencilerin, öğretmenlerin ve diğer okul personellerinin kendilerini fiziksel, psikolojik, duygusal bakımdan özgür ve rahat hissetmeleridir.\n-Okul güvenliği, öğrencinin ve okul personelinin okula gitmek amacıyla evinden ayrılmasından, evine dönünceye kadar geçen süre zarfında geçerli olan bir kavramdır.\n-Bu sebeple yapılacak çalışmalarda geniş bir perspektiften bakmakta fayda vardır. "),
      InfoCardItem("ii_guvenliokul_info_41", "Okul Güvenliği-2", "-Okul güvenliğinin mekan olarak ele alınılmasında 3 temel başlık öne çıkmaktadır. Bunlar;\n\n-Okul ile ev arasında güvenlik,\n-Okul içinde güvenlik,\n-Sınıfta güvenlik’tir."),
      InfoCardItem("ii_guvenliokul_info_42", "Okul Güvenliğinin Boyutları", "-Okul güvenliğinin 6 temel boyutu vardır.\n-Bu boyutlar şunlardır\n\n-Akran, arkadaşlarından gelecek şiddet olaylarına karşı güvenlik,\n-Doğal afetlere karşı güvenlik,\n-Sağlık ve temizlik ile ilgili (hijyen) ilişkin güvenlik,\n-Fiziksel, cinsel istismara karşı güvenlik,\n-Psikolojik ve duygusal güvenlik,\n-Etnik ve siyasî görüş konularındaki güvenlik."),
      ]),
    InfoCardModel("Okul Güvenliğiyle İlgili Teoriler-1 (Yeni)", [
      InfoCardItem("ii_guvenliokul_info_91", "Açıklama","-Okul güvenliğini ait çalışmalarda üç teori ön plana çıkmaktadır (Welsh, Greene, Jenkins, 1999, 74).\n-Bu teorilerin her biri okul güvenliğine ilişkin ayrı ayrı ele alınmalıdır.\n-Okul güvenliğiyle ilgili yapılan çalışmalarda bu teorilerin göz önünde bulundurulması gerekir.\n-Bu teorilerin ne olduğunu sonraki karttan itibaren göreceğiz."),
      InfoCardItem("ii_guvenliokul_info_92", "Teoriler","-Okul güvenliği ile ilgili teoriler aşağıdaki gibi sıralanabilir;\n-Kontrol teorisi,\n-Okul iklimi teorisi,\n-Sosyal ( Toplumsal) çözülme teorisidir."),
      InfoCardItem("ii_guvenliokul_info_93", "Kontrol Teorisi-1","-Kontrol teorisine göre, okullardaki şiddet olaylarının temelinde toplumsal ve kültürel değerlerin aile ve okul gibi kurumlarca çocuklara yeterince aktarılamaması söz konusudur.\n-Bu değerler zamanında aktarılmaması okulda şiddetin artmasında en temel sorundur."),
      InfoCardItem("ii_guvenliokul_info_94", "Kontrol Teorisi-2","Kontrol teorisine göre güvenli okul ancak (Welsh, Greene ve Jenkins, 1999, 75);\n-Geleneksel amaçlara bağlılık,\n-Diğer kimselerin haklarına bağlılık,\n-Toplumsal etkinliklere katılım,\n-Toplumsal normlara inanma koşullarının sağlanmasıyla gerçekleşebilir."),
      InfoCardItem("ii_guvenliokul_info_95", "Kontrol Teorisi-3","-Bu alanda akılda bulunması gereken ilk düşünce “ Her bir öğrencinin belirli bir kapasitesi” olduğunun farkında olmaktır.\n-Bu alanda akılda bulunması gereken ilk düşünce “ Her bir öğrencinin belirli bir kapasitesi” olduğunun farkında olmaktır."),
      InfoCardItem("ii_guvenliokul_info_96", "Kontrol Teorisi-4","-Becerileri  açısından yetersiz olan öğrenci okulda başarısız olabilir ve bu başarısızlık da çocuğun okula alışamamasına  neden olabilir.\n-Bu yüzden okullarda öğrencilerin becerilerini göz önüne çıkaracak çalışmalara önem verilmelidir."),
      ]),
    InfoCardModel("Okul Güvenliğiyle İlgili Teoriler-2 (Yeni)", [
      InfoCardItem("ii_guvenliokul_info_97", "Okul İklimi Teorisi-1","-Okul iklimi, okuldan okula farlılık gösteren, okul ile bağlantılı kişilerin  (öğretmen, öğrenci, okul personeli ve veli) sosyal ilişkilerini, okuldaki eğitim ve yönetim faaliyetlerine katılımlarını, fiziksel ve duygusal güvenliklerini, organizasyon yapılarının ve bu mekanizmaların nasıl çalıştığını ortaya koyan bir göstergedir."),
      InfoCardItem("ii_guvenliokul_info_98", "Okul İklimi Teorisi-2","-Kabul edilebilir öğrenci davranışlarını belirleyen en önemli unsur okul iklimidir (Welsh, 2001, 917).\n-Okul kendi bünyesinde saygı duyulan ve kabul gören  bir iklime sahipse o derece güvenli bir okuldur.\n-Okulda rahatsız edici ve okula hitap etmeyen  bir iklimin varlığı söz konusu ise, bu okulun güvenliği de o derecede zayıf olacaktır."),
      InfoCardItem("ii_guvenliokul_info_99", "Okul İklimi Teorisi-3","Sergiovanni (1991, 221)’e göre okul iklimini belirlemeye yarayan genel olarak kabul gören yedi gösterge şöyle listelenmiştir;\n-Kuralları uygulama da tutarlık (conformity),\n-Sorumluluk alma,\n-Standartlar,\n-Ödüller,\n-Örgütsel açıklık,\n-Destek ve dostça ilişkiler,\n-Liderlik."),
      InfoCardItem("ii_guvenliokul_info_100", "Okul İklimi Teorisi-4","Sağlıksız örgütsel iklimin özellikleri ise Welsh (2000, 171) tarafından aşağıdaki gibi listelenmiştir;\n-Düşük düzeyde yenilikler,\n-Yetersiz iş doyumu\n-Yabancılaşma,\n-Yaratıcılığın yokluğu,\n-İçinde bulunulan durumdan memnun olma ya da memnun görünme, daha iyiyi aramama,\n-Birbirinin kopyası olan davranışların çokluğu,\n-Çalışanların kaygı düzeyinin yüksekliği."),
      InfoCardItem("ii_guvenliokul_info_101", "Sosyal (Toplumsal) Çözülme Teorisi-1","-Toplumsal çözülme teorisine göre, eğer okulların daha güvenli yerler olmaları isteniyorsa, önce toplum ve aile güvenli olmalıdır.\n-Çünkü okul güvenliği eşittir toplum güvenliği artı aile güvenliğidir. (O’Reilly ve Verdugo, 1999, 339).\n-Okuldaki suç ve şiddet olayları okulun içinde bulunduğu çevrenin bir yansımasıdır (Verdugo, 1999, 272)."),
      InfoCardItem("ii_guvenliokul_info_102", "Sosyal (Toplumsal) Çözülme Teorisi-2","-Teoriye göre okul güvenliği, okulun içinde bulunduğu toplumun güvenliğinden ayrı olarak ele alınamayacağı varsayımına dayanmaktadır.\n-Okulun güvenli bir yer olması için toplumun ve  toplumun en küçük yapı taşı ailenin güvenli yapılması ön koşuldur."),
      InfoCardItem("ii_guvenliokul_info_103", "Sosyal (Toplumsal) Çözülme Teorisi-3","-Toplumda içinde var olan olumsuzluklar, okulu da aynı şekilde etkileyecektir.\n-Suç oranı fazla olan bir toplumda, suç oranı da aynı şekilde yüksek olan okullar olacaktır."),
      ]),
    InfoCardModel("Okul Güvenliğinin Kapsamı ve Boyutları (Yeni)", [
      InfoCardItem("ii_guvenliokul_info_104", "Kapsam","-Okul güvenliği, okul personeli ve okulda öğrenim gören öğrencilerin okula gitmek amacıyla evinden ayrılması anından başlayarak tekrar evine gelinceye kadar geçen tüm aşamaları içerir.\n-Öğrencinin evi ile okul arasındaki ulaşım güvenlik düzeyi, özellikle taşımalı eğitim yapan okullar için daha büyük önem arz etmektedir."),
      InfoCardItem("ii_guvenliokul_info_105", "Okul Güvenliğinin Boyutları-1","-Okul güvenliği mekan açısından ele alınırsa; üç temel alandaki güvenlik boyutu vardır.\n\n-Okul ile ev arasındaki güvenlik,\n-Okul içinde güvenlik,\n-Sınıfta güvenlik."),
      InfoCardItem("ii_guvenliokul_info_106", "Okul Güvenliğinin Boyutları-2","Güvenliğin alanı ile ilgili boyutlar düşünülerek ele alınabilir.\n-Arkadaşlarından gelecek şiddet olaylarına karşı güvenlik,\n-Öğretmenlerin fiziksel şiddetine maruz kalma konusunda güvenlik,\n-Doğal afetlere karşı güvenlik,\n-Sağlık ve temizliğe ilişkin güvenlik,\n-Cinsel istismara karşı güvenlik,\n-Psikolojik ve duygusal güvenlik,\n-Etnik ve siyasî görüş konularındaki güvenlik."),
      InfoCardItem("ii_guvenliokul_info_107", "Güvensiz Okul-1","Sprague ve diğerlerine göre (2001, 497) Okul ortamını güvensiz yapan faktörler şunlardır;\n\n-Öğretimin etkisizliği ve dolayısıyla öğrenci başarısızlığı,\n-Tutarsız ve cezalandırıcı yönetimsel uygulamalar,\n\ndevamı diğer kartta...."),
      InfoCardItem("ii_guvenliokul_info_108", "Güvensiz Okul-2","...devamı\n\n-Öğretim imkanlarının yetersizliği ve öğrencinin kendini kontrol etmesine yönelik imkanların yokluğu,\n-İstenen davranışlara yönelik olarak açık olmayan beklentiler,\n-Kuralların uygulanmasına gerekli hassasiyetin gösterilmemesi,\n-Öğrencilerin bireysel farklılıklarına uygun olarak öğretimin bireyselleştirilememesi okul ortamını güvensiz yapar."),
      InfoCardItem("ii_guvenliokul_info_109", "Güvensiz Okul-2","Welsh’e (2000, 94) göre okul ortamını güvensiz yapan faktörler şunlardır;\n\n-Kuralların açık, adil ve tutarlı olmaması,\n-Öğretmen ve yöneticilerin kurallara vakıf olmaması,\n-Yanlış davranışların görmezden gelinmesi,\n-Öğrencilerin kuralların meşru olduğuna inanmamaları,\n-Okulun büyüklüğü,\n\ndevamı diğer kartta..."),
      InfoCardItem("ii_guvenliokul_info_110", "Güvensiz Okul-3","...devamı\n\n-Öğretim için kaynakların yetersizliği,\n-Öğretmen yönetici iş birliğinin zayıflığı,\n-Yöneticinin pasifliği,\n-Cezalandırıcı öğretmen davranışları gibi faktörler sıralanabilir."),
      InfoCardItem("ii_guvenliokul_info_111", "Güvenliği Arttırma İlkeleri","-"),
      InfoCardItem("ii_guvenliokul_info_112", "",""),
      ]),
    InfoCardModel("Okul Güvenliğinin Hukuki Çerçevesi-1", [
      InfoCardItem("ii_guvenliokul_info_43", "Çocuk Haklarının Kullanılmasına İlişkin Avrupa Sözleşmesi", "…çocuk haklarının ve yüksek çıkarlarının geliştirilmesi, devletin çocukları koruma ve geliştirmeye katılması, çocuğun eğitimini aksatabilecek, çocuk sağlığına veya fiziksel, zihinsel, ruhsal, ahlakî ya da sosyal gelişimine zarar verebilecek herhangi bir işte çalışmaktan korunması…"),
      InfoCardItem("ii_guvenliokul_info_44", "1739 Sayılı Millî Eğitim Temel Kanunu", "… özel eğitime ve korunmaya muhtaç çocukları yetiştirmek için özel tedbirler alınması, kadın, erkek herkese fırsat ve imkan eşitliği sağlanması…"),
      InfoCardItem("ii_guvenliokul_info_45", "222 Sayılı İlköğretim ve Eğitim Kanunu", "…okul binalarının sağlık, eğitim-öğretim ve ulaşım bakımından elverişli bir mahalde olması, meyhane, kahvehane, kıraathane, bar, elektronik oyun merkezleri gibi umuma açık yerler ile açık alkollü içki satılan yerlerin, okul binalarından kapıdan kapıya en az 100 metre uzaklıkta bulunması…"),
      InfoCardItem("ii_guvenliokul_info_46", "Millî Eğitim Bakanlığı Okulöncesi Eğitim ve İlköğretim Kurumları Yönetmeliği", "…. olağanüstü durum, sel, deprem, hastalık, aşırı sıcak veya soğuk gibi durumlarda önlemler alınması, okul ve öğrenci güvenliği, öğrenci sağlığı ve sağlık hizmetleri ile ilgili yönetici, öğretmen, sağlık personeli, gece bekçisi ve diğer yardımcı personelin görevlerinin belirlenmesi…"),
      InfoCardItem("ii_guvenliokul_info_47", "Millî Eğitim Bakanlığı Ortaöğretim Kurumları Yönetmeliği", "…öğrencilerin korunmasına ilişkin hükümlere yer verilmiştir. Yönetici ve öğretmenlere öğrencilerin güvenliği için veli veya ailelerle işbirliği yapmalarının, gerekli tedbirleri almalarının istenmesi…"),
      InfoCardItem("ii_guvenliokul_info_48", "Millî Eğitim Bakanlığı İlköğretim ve Ortaöğretim Kurumları Sosyal Etkinlikler Yönetmeliği", "…Ders programlarının yanında öğrencide güven, sorumluluk duygusunun geliştirilmesi, yeni ilgi alanları oluşturulması ve beceriler kazandırılması…"),
      ]),
    InfoCardModel("Okul Güvenliğinin Hukuki Çerçevesi-2", [
      InfoCardItem("ii_guvenliokul_info_49", "Millî Eğitim Bakanlığı Taşıma Yoluyla Eğitime Erişim Yönetmeliği", "…öğrenci güvenliği ile ilgili olarak; ihtiyaç hâllerinde; emniyet müdürlüğü/jandarma komutanlığı ile iş birliği yapılarak okul servis aracı sürücülerine, uyacakları kurallar ve gösterecekleri davranışlar konusunda eğitim verilmesi…"),
      InfoCardItem("ii_guvenliokul_info_50", "Millî Eğitim Bakanlığı “Taşımalı İlköğretim” 2007/53 Nolu Genelge", "…öğrencilerin olumsuz etkilenmelerini önlemek amacıyla, araç sürücüleri, refakatçiler ile yüklenicilerin öğretim yılı başında ve ihtiyaç duyulduğunda eğitime alınmaları, servis araçlarının belirtilen özelliklere uygun olması…"),
      InfoCardItem("ii_guvenliokul_info_51", "Okul Servis Araçları Hizmet Yönetmeliği", "…okul öncesi ve diğer öğrenci taşıma hizmetlerinin düzenli ve güvenli hale getirilmesi, taşıma yapacakların yeterlilik ve çalışma şartlarının belirlenmesi…"),
      InfoCardItem("ii_guvenliokul_info_52", "Binaların Yangından Korunması Hakkında Yönetmelik", "…çıkabilecek yangınların en aza indirilmesi ve herhangi bir şekilde çıkabilecek yangının can ve mal kaybını en aza indirerek söndürülmesi, yangın öncesinde ve sırasında alınacak tedbirlerin, organizasyonun, eğitimin ve denetimin usul ve esaslarını belirlenmesi…"),
      InfoCardItem("ii_guvenliokul_info_53", "MEB Yangın Önleme ve Söndürme Yönergesi", "…Okul ve kurumlarının her türlü bina, tesis, araç, gereç, malzeme, her tip motorlu araç vb. yangına karşı korunmasından gerekli önleyici tedbirlerin alınması, yangın malzemesi ve yangın cihazlarının faal bir halde bulundurulması, yangın ekiplerinin teşkil edilip eğitilmesi, yangın planlarının yapılması…"),
      InfoCardItem("ii_guvenliokul_info_54", "Okul-Aile Birliği Yönetmeliği", "…okulda uyulması gereken kurallar, zararlı alışkanlık ve eğilimlerin önlenmesi, ailede okulda ve çevrede öğrencilerle diğer çocukların iyi alışkanlıklar kazanmalarını, iyi birer vatandaş olmalarını sağlayıcı tedbirler alınması…"),
           ]),
    InfoCardModel("Okul Güvenliğinin Hukuki Çerçevesi-3", [
      InfoCardItem("ii_guvenliokul_info_55", "Millî Eğitim Bakanlığı’nın Güvenliği Artırılmış Eğitim Ortamlarını Sağlamak İçin Çıkardığı Genelgeler", "-Öğrencilerimizin Zararlı Madde Kullanımı ve Şiddet Gibi Risklerden Korunması genelgesi\n-Okullarda Şiddetin Önlenmesi genelgesi,\n-Okullarda Güvenli Ortamın Sağlanmasına Yönelik Koruyucu ve Önleyici Tedbirlerin Artırılmasına İlişkin İşbirliği Protokolü” genelgesi\n-Okullarda Şiddetin Önlenmesi ve Azaltılması vb…"),
      InfoCardItem("ii_guvenliokul_info_56", "Okullardaki Ortak Kullanım Alanlarının Hijyeni (17 Şubat 2009/20 Nolu Genelge)", "Örgün ve yaygın eğitim kurumlarındaki öğrencilerin sağlığının korunması, geliştirilmesi, yüksek seviyede tutulması…"),
      InfoCardItem("ii_guvenliokul_info_57", "Okul Kantinlerinin Denetimi ve Uyulacak Hijyen Kuralları (17 Nisan 2007/33 Nolu Genelge)", "Öğrencilerin güvenli ve sağlıklı beslenme bilinci kazanmaları, olabilecek gıda zehirlenmeleri, bulaşıcı hastalıklar, yetersiz ve dengesiz beslenmeye bağlı hastalıklar ile şişmanlığın önlenmesi…"),
      InfoCardItem("ii_guvenliokul_info_58", "Okul Spor Faaliyetleri Yönetmeliği", "MEB’e bağlı bütün eğitim ve öğretim kurumlarının yurt içi ve yurt dışı spor faaliyetlerinin programlanması, beden eğitimi ve spor faaliyetleri esaslarının tespit edilmesi, okullar arası spor yarışmalarının yürütülmesi…"),
      InfoCardItem("ii_guvenliokul_info_59", "Koruyucu Güvenlik Özel Talimatı", "Her türlü casusluk; sabotaj vs. yıkıcı faaliyetlere, yangınlara karşı personel evrak, bina, tesis, araç ve gerecin güvenliğinin sağlanması ve gereken önlemlerin alınması…"),
    ]),
    InfoCardModel("Okul Güvenliğinin Hukuki Çerçevesi-4", [
      InfoCardItem("ii_guvenliokul_info_60", "Protokol", "19.	MEB ve Çalışma ve Sosyal Güvenli Bakanlığı Arasında “Mesleki ve Teknik Öğretim Kurumlarında İş Sağlığı ve Güvenliği Eğitimi İşbirliği Protokolü” ve “Öğrencilerde Sosyal Güvenlik Bilincini Oluşturmaya ve Geliştirmeye Yönelik İşbirliği Protokolü”\nİş sağlığı ve güvenliği bilincinin okullarda yerleşmesi ve bu alandaki boşluğun giderilmesi…"),
      InfoCardItem("ii_guvenliokul_info_61", "Eğitim Kurumlarında Hijyen Şartlarının Geliştirilmesi ve Enfeksiyonu Önleme İş Birliği Protokolü", "Okulların hijyen şartlarının geliştirilmesi, enfeksiyon önleme ve kontrol süreçlerinin tutarlı, geçerli, güvenilir, tarafsız bir anlayışla sürdürülmesi amacıyla 'Okulum Temiz' belgelendirme programı yürürlüğe alınmıştır."),
      InfoCardItem("ii_guvenliokul_info_62", "MEB ile Sağlık Bakanlığı Arasında “Okul Sağlığı Hizmetleri İşbirliği Protokolü", "Okulun çevresi dahil sağlığı olumsuz olarak etkileyen her türlü etmenin denetimi ile okulda çalışanların ve öğrencilerin sağlıklarının en üst düzeye çıkarılması…"),
      InfoCardItem("ii_guvenliokul_info_63", "Milli Eğitim Bakanlığı Sağlık Bakanlığı Arasında İmzalanan “Beslenme Dostu Okul Projesi”", "Okullarda obezite ile mücadele yeterli ve dengeli beslenme ve düzenli fiziksel aktivite alışkanlığının kazandırılması…"),
    ]),
    InfoCardModel("Okul Güvenliği Risk Alanları", [
      InfoCardItem("ii_guvenliokul_info_64", "Okul Güvenliği Risk Alanları", "-Dış tehlikeler\n-Mekânla ilgili tehlikeler \n-Hijyenle ilgili tehlikeler \n-Sağlıksız gıdalar \n-Akran Zorbalığı\n-Öğretmen – idareci şiddeti\n-Veli Şiddeti\n-Sınav Kaygısı\n-Servis Kazaları\n-Doğal Afetler "),
      InfoCardItem("ii_guvenliokul_info_65", "Dış tehlikeler", "-Okul sosyal çevrenin bizzat içerisinde olan bir yapıdır.\n-Mahalle ve yakın çevredeki her türlü sosyal, toplumsal ve kültürel olaylardan etkilenebilir.\n-Bu yüzden okula ve okuldaki öğretmen, öğrenci ve personele fiziksel veya psikolojik saldırıların olma ihtimali her zaman vardır.\n-Buna yönelik tedbirler zamanında alınmalıdır."),
      InfoCardItem("ii_guvenliokul_info_66", "Mekânla ilgili tehlikeler", "-Okul ve sınıf içerisinde bulunan yapıdan kaynaklı tehlikeler bu kapsamda ele alınır.\n-Örneğin, koridorda kaygan zemin bulunması okul içerisindeki kaza ve yaralanmaları arttırıcı bir unsurdur.\n-Ayrıca, havasız mekânlar, yetersiz oksijen, merdivenler, sert zeminler, menteşeler, aydınlatmanın yetersiz olduğu yerler de mekan ile ilgili tehlikeler kapsamındadır."),
      InfoCardItem("ii_guvenliokul_info_67", "Hijyenle ilgili tehlikeler ", "-Hijyen, toplu yaşam alanlarında en çok dikkat edilmesi gereken hususlardır.\n-Okulda kaynaklı oluşabilecek salgın hastalıklara yol açmamak için hijyene dikkat etmek önem arz etmektedir.\n-Okulda hijyenin sağlanması yardımcı personelin sorumluluğu olduğu kadar, hijyen alışkanlığını öğrencilerin kazanması için de öğretmen, öğrenci, veli ve idare birlikteliği de çok önemlidir.\n-Tehlikeler, kirli sınıf ve tuvaletler ve çöp dökme alışkanlığının kazanılmaması olabilir."),
      InfoCardItem("ii_guvenliokul_info_68", "Sağlıksız gıdalar ", "-Okul içerisinde sağlıksız sayılacak gıdaların bulundurulması, tüketilmesi veya satılması konusunda caydırıcı tedbirler alınmak zorundadır.\n-Okul kantininde bu kapsamda gerekli denetlemeler titizlikle yürütülmelidir.\n-Öğrencilerin dışarıdan sağlıksız gıdalar getirerek okul içerisinde tüketmeleri engellenmelidir.\n-Tatlandırıcı, koruyucu ve renklendirici gıdalar içeren ürünler tehlikeli ürünler kapsamındadır."),
      InfoCardItem("ii_guvenliokul_info_69", "Akran Zorbalığı", "-Okul yaşantısı içerisinde, öğrencilerin birbirlerine yaptıkları tekrarlayan ve olumsuz etkilere sebep olan her türlü fiziksel veya psikolojik eylemler olarak nitelendirilebilir.\n-Akran zorbalığı, hem uygulayan hem de uygulanan üzerinde olumsuz etkilere sebep olur.\n-Fiziksel, sözel, sosyal, eşyalara veya siber zorbalıklar akran zorbalığı kapsamında ele alınabilir. "),
      InfoCardItem("ii_guvenliokul_info_70", "Öğretmen – idareci şiddeti", "-Öğretmen veya idarecinin öğrenciye, öğretmene veya idareciye uyguladığı şiddet bu kapsamda ele alınır.\n-Şiddetin her türlüsünün reddedilmesinin gerekliliği bir yana bu durumun üzücü şekilde bazen tekrarlanması gerçeği göz ardı edilmemelidir.\n-Şiddetin okul içerisinde varlığının önüne geçebilmek için gerekli tedbirler alınmalıdır."),
      InfoCardItem("ii_guvenliokul_info_71", "Veli Şiddeti", "-Son yıllarda, velilerin okulda bulunma oranlarında artış görülmektedir.\n-Ancak unutulmamalıdır ki okula gelen her veli okul için yapıcı olmayabiliyor.\n-Maalesef son yıllarda artan veli şiddeti oranları bunun kanıtı durumundadır.\n-İdarecilerin, öğretmenlerin ve diğer öğrencilerin veli şiddetine maruz kalma olasılığına karşı gerekli tedbirler alınmalıdır."),
      InfoCardItem("ii_guvenliokul_info_72", "Sınav Kaygısı", "-Mevcut sistemde öğrencilerin başarılı sayılabilmeleri için akademik başarıları önem arz etmektedir.\n-Bu kapsamda yapılan sınavlarda başarılı olma isteği sınav kaygısına sebep olmaktadır.\n-Sınav kaygısı, sadece öğrencileri değil aileleri de etkileyen bir süreçtir.\n-Okulda şiddet eyilimlerini arttırma riski taşıdığı için, okul içi ve dışı etkinlikler ile çeşitli çalışmalar yapılmalıdır."),
      InfoCardItem("ii_guvenliokul_info_73", "Servis Kazaları", "-Şehir içi ulaşım imkanlarının artması, velilerin çalışan konumda olması veya okula gidiş geliş süresince güvenlik kaygılarının artması sebebiyle okul servisi kullanım oranları artmıştır.\n-Okul servislerinin öğrencileri bırakıp aldığı süreçlerde, okul çevresindeki güvenliklerinin sağlanması okul güvenliği kapsamında değerlendirilmektedir."),
      InfoCardItem("ii_guvenliokul_info_74", "Doğal Afetler", "-Doğal afet, tüm toplumların ansızın yaşayabilecekleri bir durumdur.\n-Afetler yaşanmadan önce gerekli tedbirlerin alınması, afet sırasında oluşabilecek zararın azaltılmasında önemli bir faktördür.\n-Öğrencilerin çeşitli çalışmalarla ve tatbikatlarla bilinçlendirilmesi, okul güvenliğini arttırıcı bir unsur olarak karşımıza çıkmaktadır."),
          ]),
    InfoCardModel("Okul Sağlığı (Yeni)", [
      InfoCardItem("ii_guvenliokul_info_75", "Tanım", "Okul bünyesinde yer alan personelin ve öğrencilerin sağlıklarının değerlendirilmesi, sağlıklı bir okul yapısının oluşturulması ve sürdürülmesi,  öğrencilere ve bulundukları sosyal ortamdaki bireylere sağlık eğitimleri verilmesi için yapılan tüm çalışmalara denir.\n-Bu kapsamda pek çok kurum ve kuruluşun yürütmekte olduğu projeler bulunmaktadır."),
      InfoCardItem("ii_guvenliokul_info_76", "Okul Sağlık Hizmeti Amaçları", "Toplum içindeki tüm öğrencileri ;\n-En iyi bedensel\n-Ruhsal sağlığa kavuşmalarını sağlamak\n-Bu çalışmaları sürdürebilmek\n-Sağlık bir çevrede gelişimlerini sürdürmelerine imkan sağlamak\n-Bulundukları aile ve toplumun sağlık düzeyini yükseltmek."),
      InfoCardItem("ii_guvenliokul_info_77", "Okul Sağlığının Önemi-1", "-Büyüme ve gelişme bozukluklarının önüne geçmek daha kolay olacaktır.\n-Alınacak koruyucu önlemler yaşam boyu fayda sağlar.\n-Kazaların gelişme sıklığı okul ortamında da daha fazladır.\n-Görme ve işitme bozuklukları başarısız öğrenciyi başarısızlığa götürebilir.\n-Okulda sağlık eğitimi her kadamede kolaylık sağlar."),
      InfoCardItem("ii_guvenliokul_info_78", "Okul Sağlığının Önemi-2", "-Bulaşıcı hastalıkların görülmesi durumunda, ani yayılma risklerine karşı gerekli tedbirler alınmalıdır.\n-Aşılama gibi koruyucu önlemler diğerlerine göre daha kolay şekilde ele alınabilir.\n-Okulun sosyal yapısı için okulun önemi büyüktür."),

           ]),
    InfoCardModel("Okul Sağlığının Boyutları (Yeni)", [
      InfoCardItem("ii_guvenliokul_info_80", "Çeşitler", "-Okul Sağlığının boyutları 4 adettir. Bunlar;\n-Okul Çevresi\n-Öğrenci Sağlığı\n-Okul Personelinin Sağlığı\n-Sağlık eğitimi gibi boyutları mevcuttur.\n-Bunlar ile ilgili detaylı açıklamalar daha sonraki kartlarda ve bölümlerde verilecektir."),
      InfoCardItem("ii_guvenliokul_info_81", "Okul Çevresi-1", "Bu boyutta anlatılmak istenen çevre;\n-Okulun Yeri\n-Okulun Binası\n-Etrafında bulunan binalar\n-Okulun bulunduğu konum\n-Okulun çevresinde bulunan oyun alanları ve parklar\n-Su alt yapısı\n-Isıtma sistemi\n-Havalandırma sistemi\n-Aydınlatma\n-Sınıfların büyüklüğü\n-Sınıf içerisindeki sıralar gibi konuları içerir."),
      InfoCardItem("ii_guvenliokul_info_82", "Okul Çevresi-2", "-İlk Olarak okul çevresinin örnek oluşturacak şekilde planlanması gerekir.\n-Temiz su ve çevreye ulaşım kolay olmalıdır.\n-Okul Binasının yeri ve konumu anayol üzerinde bulunmamalıdır.\n-Öğrencinin ulaşımının kolay olması gerekir."),
      InfoCardItem("ii_guvenliokul_info_83", "Okul Çevresi-3", "-100 metre çevresinde bağımlılık yapacak ürünlerin satıldığı alanlardan ve sosyal alanlardan (oyun salonu, kıraathane vb.) uzak olmalıdır.\n-Gürültülü, kötü koku ve duman çıkaran işletmelerden uzak olmalıdır.\n-Elektrik dağıtım şebekelerinden 25m uzakta olmalıdır."),
      InfoCardItem("ii_guvenliokul_info_79", "Okul Çevresi-4", "-Elektrik dağıtım şebekelerinden 25m uzakta olması\n-Okul Öğrenci sayısına bakılarak her öğrenci için 20-25 metrekare düşecek bir arsa içerisinde bulunmalıdır.\n-Teneffüs anında öğrencilerin kullandığı bahçe alanı en az 500 metrekare veya öğrenci başına 5 metrekare olmalıdır."),
      InfoCardItem("ii_guvenliokul_info_83", "Okul Çevresi-5", "Katlarda bulunan koridor genişliği 3metre olmalıdır.\n-Sınıf duvar boyalarının açık ve mat renklerde olması . Sınıf içerisinde zeminden itibaren yapılabiliyor ise 1,5 m yağlı boya ile diğer kısımlar plastik boya ile boyanmalıdır. Kolay temizlenebilmelidir.\n-Yazı tahtası mesafesi ön sıra ile 2 metre, sınıf içerisindeki öğrencilerin görebileceği yükseklikte ve parlama yapmasına imkan vermeyecek şekilde yerleştirilmelidir."),
      InfoCardItem("ii_guvenliokul_info_84", "Okul Çevresi-6", "Okul tuvaletlerinde aranan kriterler;\n-Her 25 kız öğrenci için 1 tuvalet\n-Her 40 erkek öğrenci için 1 tuvalet 2 pisuar\n-15-20 Erkek Öğretmen için 1 tuvalet 2 pisuar\n-5-10 Bayan öğretmen için 1 tuvalet\n-Ortamın havalandırılması dikkat edilmeli\n-Muslukların boy hizası öğrencilerin kolay ulaşabileceği şekilde olmalı\n-Temizliği düzenli bir şekilde yapılmalıdır."),
      InfoCardItem("ii_guvenliokul_info_85", "Okul Çevresi-7", "Yangından korunma önlemleri kapsamında;\n-Yangın alarm sisteminin bulunması\n-\n-Yangın tüplerinin kullanıma hazır bulunması\n-Okulun 5 derslik ten fazla olması durumdan 2 tane dışarı açılan kapısının olması,"),
      InfoCardItem("ii_guvenliokul_info_86", "Okul Çevresi-8", "Isınma;\n-Okulun her alanı eşit şekilde ısınmalıdır.\n-İdare, ortak kullanılan odalar ve koridorlar 20 derece , diğer tüm odalar 15 derece olmalıdır."),
      InfoCardItem("ii_guvenliokul_info_87", "Öğrenci Sağlığı", "-Hastalıkları önlemeyi,\n-Sağlık sorunları hakkında bilgi sahibi olmayı,\n-Gerekli durumlarda müdahale edebilme,\n-Ani gelişen durumlarda acil yardım işlemlerinin gerçekleştirilmesi\n-Eğitim ve danışmanlık olarak ele alınır."),
      InfoCardItem("ii_guvenliokul_info_88", "Okul Personeli Sağlığı", "Öğretmenler olmak üzere tüm çalışanların sağlığı bu boyutta yer almaktadır.\n-Öğretmenlerin sağlıklı, huzur ve güven dolu bir ortamda çalışmaları, öğrencilerin başarılarını dışında ruhsal ve psikolojik gelişimlerinide olumlu etkiler.\n-Okul ortamında örnek kişiler öğretmenlerdir. Bu neden sağlık açısından da öğrencilere yol gösterici olacak olanlar öğretmenlerdir. Bu nedenle öğretmenlerin eğitimlerinin eksiksiz yapılarak model kişi olarak yer almaları sağlanmalıdır."),
      InfoCardItem("ii_guvenliokul_info_89", "Sağlık Eğitimi-1", "-İstenilen hedef grupta sağlık, bilgi , tutum , davranış ve değerlerin gelişiminin sağlanmasıdır.\n-Okulda 3 hedef grup bulunmaktadır:  Öğretmen-Öğrenci-Veli\n-Sağlık çalışanları bu 3 hedef grup için gerekli eğitimlerin yapılmasını sağlarlar."),
      InfoCardItem("ii_guvenliokul_info_90", "Sağlık Eğitimi-2", "-Öğretmen ve Veli yardımı ile öğrencilerin sağlık eğitimlerinin sürdürülebilmesi için ortak hareket edilir. \n-Öğrencilere öncelikle kendi sağlıklarını koruma ve özen gösterme önceliklerinden, daha sonra ise diğer insanları korunma durumlarından gelişmelerini sağlar."),

    ]),
    /*InfoCardModel("Okul Sağlığında İzleme", [
         InfoCardItem("ii_guvenliokul_info_91", "Büyümenin İzlenmesi-1", "-Büyüme, vücutta yer alan hücre sayısı ve büyüklüğün artması ile vücut hacim ve kütlesinin artışına denir.\n-Beslenme, hormonlar, genetik aktarımlar, psiko-sosyal ortam ve kronik hastalıklardan etkilenir.\n-5 yaş ile ergenlik yaşına geçen süre arasında büyüme yılda 5-6 cm iken"),
         InfoCardItem("ii_guvenliokul_info_92", "Büyümenin İzlenmesi-2", "Ergenlik zamanına yaklaşınca bu durum yavaşlar\n-Kızlarda 10 yaş Erkeklerde 12 yaş sonrası hızlanma tekrar başlar .\n-Ergenlik süresi gelene kadar normal boyun %80 nine ulaşılır\n-Ergenlik te boy büyüme hız gerçekleşir. Bu boy büyümesine doruk büyüme denir.\n-5-19 yaş arası her yıl en az 1 kere boy ve kilo olarak ölçümlerin yapılıp , uygun standartlar ile karşılaştırılması gerekir."),
         InfoCardItem("ii_guvenliokul_info_93", "Gelişmenin izlenmesi", "-Organların biyolojik işlevlerine göre farklılaşması ve olgunlaşmasına gelişme denir.\n-2 adet gelişme bulunur. Bunlar\n-Cinsel Gelişme\n-Psikososyal "),
         InfoCardItem("ii_guvenliokul_info_94", "", ""),
         InfoCardItem("ii_guvenliokul_info_95", "", ""),
         InfoCardItem("ii_guvenliokul_info_96", "", ""),
         InfoCardItem("ii_guvenliokul_info_97", "", ""),
         InfoCardItem("ii_guvenliokul_info_98", "", ""),
         InfoCardItem("ii_guvenliokul_info_99", "", ""),
    ]),*/





   /* InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),*/

//InfoCardItem("ii_guvenliokul_info_93", "", ""),
//InfoCardItem("ii_guvenliokul_info_94", "", ""),
//InfoCardItem("ii_guvenliokul_info_95", "", ""),
//InfoCardItem("ii_guvenliokul_info_96", "", ""),
//InfoCardItem("ii_guvenliokul_info_97", "", ""),
//InfoCardItem("ii_guvenliokul_info_98", "", ""),
//InfoCardItem("ii_guvenliokul_info_99", "", ""),
//InfoCardItem("ii_guvenliokul_info_100", "", ""),
//
  ];

  List<InfoCardModel> get guvenliOkul => _guvenliOkulList;}