import 'package:flutter/material.dart';
import 'package:uzman_ogretmen/model/info_card_item.dart';

import '../../model/info_card_model.dart';

class OgrenOgrenSurecInfoViewModel extends ChangeNotifier {
  List<InfoCardModel> _ogrenmeOgretmeSurec = [
    InfoCardModel("Öğrenme ve Öğretme Süreçleri-1", [
      InfoCardItem("eo_Info_281","Öğrenme-1","-Yaşantı veya tekrar yoluyla bireylerde meydana gelene kalıcı davranış değişikliklerine öğrenme denir.\n-Öğrenmeler kalıcıdır.\n-Çevre önemli bir etkendir.\n-Öğrenmenin unutulması veya kaybolması beklenmez.\n-Olumlu yönde olması tercih edilse de olumsuz da olabilir.\n-Davranış değişikliği gerektirir.\n-Refleksif hareketler öğrenme kabul edilmez."),
      InfoCardItem("eo_Info_281","Öğrenme-2","-Öğrenmenin kalıcı olması, gözlenebilir olması, yaşantı sonucu gerçekleşmesi ve değişimin yalnızca büyüme ve olgunlaşmaya bağlı olmaması gerekir."),
      InfoCardItem("eo_Info_282","Psikoloji","-İnsan davranışlarını ve davranışlarının altında yatan sebepleri inceler.\n-Davranışlar bilinç dışı süreçlerde kayıtlı bazı olay ve olgular sebebiyle sergileniyor olabilir.\n-Bu olay ve olgular tespit edilerek bireyin olumlu yönde gelişmesi sağlanabilir."),
      InfoCardItem("eo_Info_283","Öğrenme Psikolojisi","-Öğrenme ve psikolojide ortak unsur davranıştır.\n-Psikoloji biliminin öğrenme odaklı olması öğrenme psikolojisi kavramını ortaya çıkartır.\n-Öğrenmenin nasıl gerçekleştiğini, öğrenmeyi etkileyen faktörleri, öğrenmeler arası disiplinleri, öğrenmede bireysel farklılıkları ve öğrenmeyi oluşturan unsurları inceler."),

    ]),InfoCardModel("Öğrenme ve Öğretme Süreçleri-2", [
      InfoCardItem("eo_Info_284","Temel kavramlar","Davranış: Dış dünyada gözlemlenebilen her türlü etkinliğidir.\n-Bilişsel, duyuşsal, psikomotor, öğrenilmiş, istendik, istenmedik, geçici ve refleksif olabilir."),
      InfoCardItem("eo_Info_285","Bilişsel davranış","-Zihinsel süreç gerektiren davranışlardır.\n-Eylemin yapılmasında sebep sonuç ilişkisi kurma, dikkat etme, hatırlama, yorum çıkartma ve hayalgücünü kullanma gibi zihinsel süreçler etkilidir."),
      InfoCardItem("eo_Info_286","Duyuşsal davranış","-Duygular ön plandadır.\n-Sevinç, üzüntü, korku, heyecan gibi duyguların beyin süzgecinden geçerek davranışa dönüşmesidir."),
      InfoCardItem("eo_Info_287","Psikomotor davranış","-El göz koordinasyonu gerektirir.\n-Yürüme, koşma, zıplama, kaldırma gibi fiziksel aktiviteler içerir."),
      InfoCardItem("eo_Info_288","Öğrenilmiş davranış","-Davranış öğrenme ürünüdür.\n-Öğrenme ürünü olan davranışlar kalıcır olur."),
      InfoCardItem("eo_Info_289","İstendik davranış","-Öğrenme planlı bir eğitim sürecinde gerçekleşir.\n-Gelişigüzel kültürlenme sonucu da öğrenme gerçekleşebilir."),
      InfoCardItem("eo_Info_290","İstenmedik davranış","-Öğrenme hatalı eğitim sürecinde gerçekleşir.\n-Kötü kültürlenme de öğrenmeye sebep olmuş olabilir."),
      InfoCardItem("eo_Info_291","Geçici davranış","-İlaç kullanımı ve alkol gibi durumlar sebebiyle ortaya çıkan davranışlardır.\n-Davranışlar kalıcı değil kısa sürelidir."),
      InfoCardItem("eo_Info_292","Doğuştan gelen davranış","-Refleksif, içgüdüsel ve kontrol dışı ortaya çıkan davranışlardır."),

    ]),InfoCardModel("Öğrenme ve Öğretme Süreçleri-3", [
      InfoCardItem("eo_Info_293","Öğrenmeyi etkileyen faktörler","-Öğrenenle ilgili faktörler,\n-Öğrenme yöntemi ile ilgili faktörler,\n-Öğrenme malzemesi ile ilgili faktörler,"),
      InfoCardItem("eo_Info_294","Öğrenenle ilgili faktörler","-Türe özgü hazıroluş,\n-Olgunlaşma,\n-Genel uyarılmışlık düzeyi,\n-Güdü,\n-Eski yaşantılar,\n-Dikkat"),
      InfoCardItem("eo_Info_295","Türe özgü hazıroluş","-Bazı davranışların öğrenilebilmesi için gerekli biyolojik yeterlilikler bulunur.\n-Organizma bu donanıma sahip değilse davranış öğrenilemez."),
      InfoCardItem("eo_Info_296","Olgunlaşma","-Bazı davranışların gerçekleştirilebilmesi için fiziksel ve zihinsel yeterliliğin olması gerekir.\n-Bunlar yaş ve zeka ile ilgili olabilir.\n-Ancak bu olgunlaşma sağlanırsa öğrenme gerçekleşir."),
      InfoCardItem("eo_Info_297","Genel uyarılmışlık düzeyi","-Çevreden gelen uyarıcıların birey tarafından alınma düzeyidir.\n-Belirli bir düzeye kadar öğrenmeyi olumlu yönde etkiler.\n-Belirli bir düzey sonrası öğrenmeyi olumsuz etkiler."),
      InfoCardItem("eo_Info_298","Güdü","-İhtiyaç sonucu ortaya çıkar.\n-Organizmayı davranışa sürükler."),
      InfoCardItem("eo_Info_299","Eski yaşantılar","-Bireyin önceki öğrenmelerinin yeni öğrenmelerine olan etkisidir.\n-Öğrenmeyi olumlu veya olumsuz yönde etkileyebilir."),
      InfoCardItem("eo_Info_300","Dikkat","-Öğrenmeyi etkileyen en temel faktörlerdendir.\n-Birey kendi ihtiyaçlarından dolayı dikkatli ise istemlidir.\n-Dikkat çevresel güçlü uyarıcılar sebebiyle oluyorsa istemsiz dikkattir."),
      InfoCardItem("eo_Info_301","Öğrenme yöntemi ile ilgili faktörler","-Konunun yapısı,\n-Zaman kullanımı,\n-Dönüt,\n-Etkin katılım"),
      InfoCardItem("eo_Info_302","Konunun Yapısı","-Konunun nasıl öğrenileceğini kapsar.\n-Bütün halinde veya parçalara bölünerek çalışılabilir.\n-En etkili yöntem bütün-parça-bütün yöntemidir.\n-Bu yöntemde konu önce bütünüyle ele alınır.\n-Sonra parçalara bölünerek çalışılır.\n-Daha sonra tekrar bütün olarak ele alınır."),
      InfoCardItem("eo_Info_303","Zaman kullanımı","Konunun toplu olarak veya zamansal aralıklarla çalışılması öğrenme yöntemi ile ilgilidir."),
      InfoCardItem("eo_Info_304","Dönüt","-Öğrenmenin ne düzeyde gerçekleştiği hakkında öğrenene bilgi verme sürecidir.\n-Dönüt, öğrenene sık sık verilmelidir.\n-Dönüt hemen verilirse, öğrenmedeki aksaklıklar daha hızlı giderilebilir."),
      InfoCardItem("eo_Info_305","Etkin katılım","-Öğrenenin öğrenilecek konu için süreçte tüm dikkatiyle varolmasıdır.\n-Katılım arttıkça öğrenme artar."),
    ]),InfoCardModel("Öğrenme ve Öğretme Süreçleri-4", [
    InfoCardItem("eo_Info_305","Etkin katılım","-Öğrenenin öğrenilecek konu için süreçte tüm dikkatiyle varolmasıdır.\n-Katılım arttıkça öğrenme artar."),
    InfoCardItem("eo_Info_306","Öğrenme malzemesi ile ilgili faktörler","-Algısal ayırt edilebilirlik,\n-Anlamsal çağrışım,\n-Kavramsal gruplandırma,\n-Çağrışımsal gruplandırma,\n-Telaffuz edilebilirlik"),
    InfoCardItem("eo_Info_307","Algısal ayırt edilebilirlik","-Uyarıcının o an çevrede varolan tüm uyarıcılardan daha güçlü olması durumudur.\n-Bu durumda odak noktası güçlü uyarıcıdadır.\n-Öğrenmeyi direkt olarak etkiler."),
    InfoCardItem("eo_Info_308","Anlamsal çağrışım","-Öğrenme sırasında geçmiş öğrenmelerle bağ kurmaktır.\n-Yani yeni öğrenmeler önceki öğrenmelerden esinlenilerek gerçekleştirilir."),
    InfoCardItem("eo_Info_309","Kavramsal gruplandırma","-Konuların birbiri ile ilişkilerinin haritalama ile ortaya çıkarılmasıdır.\n-Hiyerarşik düzende ilişkilendirme yapılır.\n-Kavram haritası mantığı kullanılır."),
    InfoCardItem("eo_Info_310","Çağrışımsal gruplandırma","-İçeriğin deneyimlerle ve bilgilerle ilişkilendirilmesidir.\n-Çağrışım sayısı ne kadar artarsa, hatırlama düzeyi o kadar artar."),
    InfoCardItem("eo_Info_311","Telaffuz edilebilirlik","-İçeriğin dilsel gelişime uygun olarak verilmesidir.\n-Konu uygun ve anlaşılır örneklerle açıklanır."),
]), InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
/*    InfoCardModel("", [
      InfoCardItem("ogrenogretsurec_info_1", "Öğrenme-1","-Yaşantı veya tekrar yoluyla bireylerde meydana gelene kalıcı davranış değişikliklerine öğrenme denir.\n-Öğrenmeler kalıcıdır.\n-Çevre önemli bir etkendir.\n-Öğrenmenin unutulması veya kaybolması beklenmez.\n-Olumlu yönde olması tercih edilse de olumsuz da olabilir.\n-Davranış değişikliği gerektirir.\n-Refleksif hareketler öğrenme kabul edilmez."),
      InfoCardItem("ogrenogretsurec_info_2", "Öğrenme-2","-Öğrenmenin kalıcı olması, gözlenebilir olması, yaşantı sonucu gerçekleşmesi ve değişimin yalnızca büyüme ve olgunlaşmaya bağlı olmaması gerekir."),
      InfoCardItem("ogrenogretsurec_info_3", "Öğretme","-Bireyin öğrenmesinin sağlamasına denir.\n-Öğrenende davranış değişikliği ortaya çıkarma süreci olarak da tanımlanabilir.\n-Süreçteki davranış değişikliği düşünüldüğünde öğrenme sürecinin farklı bir açıdan görünümü gibidir.\n-Öğretenin merkezde olmadığı ve öğrenme sürecine rehberlik ettiği öğrenmeler daha kalıcıdır."),
      InfoCardItem("ogrenogretsurec_info_4", "Okulda Öğrenme", "-Öğrenme süreci okulda amaçlı ve planlı olarak yürütülür.\n-Öğrencilerin uygun eğitim-öğretim ortamında öğrenmelerini gerçekleştirmeleri esastır.\n-Öğrencilerin plan doğrultusunda yaptığı çalışmalar takip edilerek öğrenme durumları gözden geçirilir."),
      InfoCardItem("ogrenogretsurec_info_5", "Öğrenme Ortamı", "-Öğrenme ortamı hazırlanırken öğrencilerin istek ve talepleri göz önünde bulundurulmalıdır.\n-Çocukların öğrenmeye istekli hale getirmelidir.\n-Gelişimlerine katkı sağlamalıdır.\n-Öğrenme türü ve içeriğe göre farklı tasarımlara açık olmalıdır.\n-Öğrenen ve öğretenin aktif katılım sağlayabileceği şekilde düzenlenmelidir."),
      InfoCardItem("ogrenogretsurec_info_6","Öğretmenin Görevleri", "-Öğrenme ortamında öğrencinin istek ve taleplerini dikkate almalıdır.\n-En iyi öğrenme ortamını oluşturmalıdır.\n-Öğrenme sürecinde, öğrenene rehberlik etmelidir.\n-Öğrencinin çalışmasını ve çabasını doğru yönde kullanabilmesini sağlamalıdır."),
      InfoCardItem("ogrenogretsurec_info_7", "Öğretim","-Öğretmen etkinliklerin belirli bir düzen içinde planlanarak yürütülmesidir.\n-Öğrenme ve öğretme sürecini kapsar.\n-Öğrenme ve öğretme etkinlikleri kontrollüdür.\n-Eğitim programı ve öğretim programı kullanılır."),
      InfoCardItem("ogrenogretsurec_info_8", "Eğitim Programı","-Öğrenme etkinliklerinin okul içi veya okul dışında, Milli Eğitimin temel amaçlarına uyarak planlı etkinlikler düzenlenmesidir.\n-Program içerisinde yer alan konu ve etkinlikler gerçek hayatta kullanılabilir olmalıdır.\n-Ayrıca öğrenenlerin yaşantılarını kolaylaştırması beklenir.\n-Öğretime yön verir.\n-Öğretim sürecinin kontrolünü sağlar."),
      InfoCardItem("ogrenogretsurec_info_9", "Öğretim Programı", "-Davranışların kazandırılması için ders düzeyinde etkinlik planlarının yapılması ve planlanan bu etkinliklerin uygulanması sürecidir.\n-Belirlenmiş programların nasıl uygulanacağı hakkında da bilgi verir.\n-Öğrencilerin iletişim becerilerini, eleştirel ve yaratıcı düşünme becerilerini geliştirmeyi hedefler."),
      InfoCardItem("ogrenogretsurec_info_10", "Eğitim", "-Belirli amaçlar için insanların yetiştirilmesi sürecidir.\n-Bedensel, zihinsel ve duygusal olarak sahip olunan yeteneklerin geliştirilmesi süreci olarak da tanımlanabilir.\n-İstenerek ve kasıtlı şekilde değişimler yaşanması süreci de eğitime dahil edilir.\n-Tüm yaşantı içerisinde eğitim yer alır."),
      InfoCardItem("ogrenogretsurec_info_11", "Eğitimin Özellikleri", "-Süreklidir.\n-Kişilik gelişimlerinin olumlu yönde etkilenmesini sağlar.\n-Kişinin topluma uyum sağlamasına katkı sağlar.\n-Kapsamı geniştir."),
      InfoCardItem("ogrenogretsurec_info_12", "", ""),
      InfoCardItem("ogrenogretsurec_info_13", "", ""),
      InfoCardItem("ogrenogretsurec_info_14", "", ""),
      InfoCardItem("ogrenogretsurec_info_15", "", ""),
      InfoCardItem("ogrenogretsurec_info_16", "", ""),
      InfoCardItem("ogrenogretsurec_info_17", "", ""),
      InfoCardItem("ogrenogretsurec_info_18", "", ""),
      InfoCardItem("ogrenogretsurec_info_19", "", ""),
      InfoCardItem("ogrenogretsurec_info_20", "", ""),
      InfoCardItem("ogrenogretsurec_info_21", "", ""),
      InfoCardItem("ogrenogretsurec_info_22", "", ""),
      InfoCardItem("ogrenogretsurec_info_23", "", ""),
      InfoCardItem("ogrenogretsurec_info_24", "", ""),
      InfoCardItem("ogrenogretsurec_info_25", "", ""),
      InfoCardItem("ogrenogretsurec_info_26", "", ""),
      InfoCardItem("ogrenogretsurec_info_27", "", ""),
      InfoCardItem("ogrenogretsurec_info_28", "", ""),
      InfoCardItem("ogrenogretsurec_info_29", "", ""),
      InfoCardItem("ogrenogretsurec_info_30", "", ""),
      InfoCardItem("ogrenogretsurec_info_31", "", ""),
      InfoCardItem("ogrenogretsurec_info_32", "", ""),
      InfoCardItem("ogrenogretsurec_info_33", "", ""),
      InfoCardItem("ogrenogretsurec_info_34", "", ""),
      InfoCardItem("ogrenogretsurec_info_35", "", ""),
      InfoCardItem("ogrenogretsurec_info_36", "", ""),
      InfoCardItem("ogrenogretsurec_info_37", "", ""),
      InfoCardItem("ogrenogretsurec_info_38", "", ""),
      InfoCardItem("ogrenogretsurec_info_39", "", ""),
      InfoCardItem("ogrenogretsurec_info_40", "", ""),
      InfoCardItem("ogrenogretsurec_info_41", "", ""),
      InfoCardItem("ogrenogretsurec_info_42", "", ""),
      InfoCardItem("ogrenogretsurec_info_43", "", ""),
      InfoCardItem("ogrenogretsurec_info_44", "", ""),
      InfoCardItem("ogrenogretsurec_info_45", "", ""),
      InfoCardItem("ogrenogretsurec_info_46", "", ""),
      InfoCardItem("ogrenogretsurec_info_47", "", ""),
      InfoCardItem("ogrenogretsurec_info_48", "", ""),
      InfoCardItem("ogrenogretsurec_info_49", "", ""),
      InfoCardItem("ogrenogretsurec_info_50", "", ""),
      InfoCardItem("ogrenogretsurec_info_51", "", ""),
      InfoCardItem("ogrenogretsurec_info_52", "", ""),
      InfoCardItem("ogrenogretsurec_info_53", "", ""),
      InfoCardItem("ogrenogretsurec_info_54", "", ""),
      InfoCardItem("ogrenogretsurec_info_55", "", ""),
      InfoCardItem("ogrenogretsurec_info_56", "", ""),
      InfoCardItem("ogrenogretsurec_info_57", "", ""),
      InfoCardItem("ogrenogretsurec_info_58", "", ""),
      InfoCardItem("ogrenogretsurec_info_59", "", ""),
      InfoCardItem("ogrenogretsurec_info_60", "", ""),
      InfoCardItem("ogrenogretsurec_info_61", "", ""),
      InfoCardItem("ogrenogretsurec_info_62", "", ""),
      InfoCardItem("ogrenogretsurec_info_63", "", ""),
      InfoCardItem("ogrenogretsurec_info_64", "", ""),
      InfoCardItem("ogrenogretsurec_info_65", "", ""),
      InfoCardItem("ogrenogretsurec_info_66", "", ""),
      InfoCardItem("ogrenogretsurec_info_67", "", ""),
      InfoCardItem("ogrenogretsurec_info_68", "", ""),
      InfoCardItem("ogrenogretsurec_info_69", "", ""),
      InfoCardItem("ogrenogretsurec_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get ogrenmeOgretmeSurec => _ogrenmeOgretmeSurec;
}
