import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class OzelEgitimInfoViewModel extends ChangeNotifier{

  ///
  List<InfoCardModel> _ozelEgitimList = [
    InfoCardModel("Özel Eğitim ve Rehberlik-1", [
      InfoCardItem("eo_Info_160","Rehberlik Hizmetlerinin İlkeleri","-Örgütlenmiştir.\n-Okul, aile ve çevreyi bilgilendirir.\n-Herkesin seçme özgürlüğü vardır.\n-İnsana saygı esastır.\n-Her okulda rehberlik hizmeti olmalıdır.\n-Koruyucudur.\n-Tüm öğrencilere açıktır.",),
      InfoCardItem("eo_Info_161","Rehberlik Hizmetlerinin İlkeleri","-Gönüllülük esastır.\n-Yaşam boyu yararlanılabilir.\n-İşbirliği gerektirir.\n-Bireye ve topluma karşı sorumludur.\n-Gizlilik esastır.\n-Eğitimin ayrılmaz parçasıdır.",),
      InfoCardItem("eo_Info_162","Yararlanılan Bilim Dalları","-Psikoloji\n-Sosyoloji\n-Sosyal Psikoloji\n-Ekonomi\n-Antropoloji\n-Eğitim Bilimi",),
      InfoCardItem("eo_Info_163","Rehberliğin Temel Taşları","-Bireye yardım etme sürecidir\n-Her öğrenci geliştirilebilir\n-Bireyin kendini gerçekleştirmesini sağlar\n-Bilimsel ve profesyoneldir.",),
      InfoCardItem("eo_Info_164","Rehberlik Hizmetinin Psikolojik Temelleri","-Bireysel farklılıklar\n-Cinsiyet farkları\n-Bireydeki nitelikler ile meslekler arası ilişkiler\n-Davranım\n-Kişilik",),
    ]),
    InfoCardModel("Özel Eğitim ve Rehberlik-2", [
      InfoCardItem("eo_Info_165","Hizmet Türleri","1-Hizmet verilen birey sayısına göre rehberlik\n-2-Hizmetin temel işlevine göre rehberlik\n-Hizmetin yoğunlaştığı problem alanına göre rehberlik\n-Hizmet alanına göre rehberlik\n-Öğretim basamaklarına göre rehberlik",),
      InfoCardItem("eo_Info_166","1-Hizmet Verilen Birey Sayısına Göre","-Bireysel ve grup rehberlği olarak incelenir.\n-Bireysel rehberlik 1 kişi için yapılır.\n-Grup rehberliği bir gruba aynı anda yapılır",),
      InfoCardItem("eo_Info_167","1-Hizmet Verilen Birey Sayısına Göre","-Bireysel rehberlik kişinin farkındalık düzeyini yükseltmeli.\n-Kişi sorununu kendi çözmelidir.\n-Grup rehberlikleri uzmanlık gerektirmiyorsa snıf rehber öğretmeni tarafından yapılabilir.",),
      InfoCardItem("eo_Info_168","2-Hizmetin Temel İşlevine Göre","A) Uyum Sağlayıcı Rehberlik\n-Çocukların ihtiyacına göre hazırlanır.\n-Uyum sorunlarının sebebini bulmalıdır.",),
      InfoCardItem("eo_Info_169","2-Hizmetin Temel İşlevine Göre","B) Yönetici Rehberlik\n-Öğrenciler meslek kaygısı yaşayabilir.\n-Rehberlik servisi öğrenciyi ilgisi olan alana yönlendirebilir.",),
      InfoCardItem("eo_Info_170","2-Hizmetin Temel İşlevine Göre","C) Ayarlayıcı Rehberlik\n-Öğrencinin ilgi ve gereksinimlerine göre etkinliklerin hazırlanarak eğitimcilere sunulmasıdır",),
      InfoCardItem("eo_Info_171","2-Hizmetin Temel İşlevine Göre","D) Geliştirici Rehberlik\n-Bireylerin gelişim dönemleri dikkate alınarak hazırlanır.",),
      InfoCardItem("eo_Info_172","2-Hizmetin Temel İşlevine Göre","E) Önleyici Rehberlik\n-Olumsuz durumlar ortaya çıkmadan gerekli tedbirlerin alınmasıdır.",),
      InfoCardItem("eo_Info_173","2-Hizmetin Temel İşlevine Göre","F) Tamamlayıcı Rehberlik\n-Rehberlik öğretim etkinliklerini tamamlayıcı boyuttadır.",),
      InfoCardItem("eo_Info_174","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","A)Eğitsel Rehberlik\n-Okul seçme, okula uyum, verimli ders çalışma, zamanı iyi kullanma vb. gibi konularda verilen destekleri içerir.",),
      InfoCardItem("eo_Info_175","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","B) Mesleki Rehberlik\n-Meslek tanıma, meslek seçimi, seçtiği mesleğe hazırlanma vb. gibi konularda destek verir.\n-Mesleki Seçim Devreleri\n-Fantezi Devresi(6-12 yaş. Taklit vardır sıkça tercih değişir)\n-Geçici Devre(12-17 yaş.İlgi vardır, daha bilinçlidir ama geçicidir.)\n-Gerçekçi Devre(18 yaş üstü gerçekçi seçimdir.)",),
      InfoCardItem("eo_Info_176","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","Meslek seçiminde;\n-Fiziksel ve kişisel özellikler\n-Genel ve özel yetenekler\n-İlgiler\n-Yaşantılar ve\n-Aile yapısı dikkate alınmalıdır.",),
      InfoCardItem("eo_Info_177","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","Meslek Gelişim Dönemleri;\n-Büyüme Dönemi(0-14 Yaş)\n-Araştırma Dönemi(15-24 Yaş)\n-Yerleşme Dönemi(25-44 Yaş)\n-Sürdürme Dönemi(45-64 Yaş)\n-Emeklilik Dönemi(65 yaş üstü",),
      InfoCardItem("eo_Info_178","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","C) Bireysel Rehberlik\n-Öğrencinin kişisel-sosyal gelişim ihtiyaçlarını karşılamak amacıyla yürütülür.",),
      InfoCardItem("eo_Info_179","3-Hizmetin Yoğunlaştığı Problem Alanlarına Göre","D) Grup Rehberliği\n-Belli bir grupta veya sınıfta tüm öğrencilerle yürütülür.\n-Meslek tanıma, ders çalışma gibi olgusal konularda destek verilir.\n-Her öğrenciye saygı esastır.\n-Her öğrencinin katılımı sağlanır.\n-Danışman kendi fikrini yansıtmaz.",),
      InfoCardItem("eo_Info_180","4-Hizmet Alanlarına Göre","A) Eğitim Alanında\n-Öğrencileri eğitimin temel amaçlarına göre geliştirmek.\n-Doğru mesleklere yönlendirmek.\n-İlgi ve yeteneklerine göre eğitim vermek amacaıyla rehberlik yapılır.",),
      InfoCardItem("eo_Info_181","4-Hizmet Alanlarına Göre","B) Sağlık Alanında Rehberlik\n-Bireylerin ruh ve beden sağlıkları için rehberlik çalışmaları yürütür.",),
      InfoCardItem("eo_Info_182","4-Hizmet Alanlarına Göre","C) Sosyal Yardım Alanında Rehberlik\n-Huzur evleri, Çocuk Esirgeme Kurumları, Kızılay gibi kurumlarda rehberlik hizmeti verilr.",),
      InfoCardItem("eo_Info_183","4-Hizmet Alanlarına Göre","D) Endüstri Alanında Rehberlik\n-Sanayi, işçi sendikaları gibi kurumlarda da rehberlik hizmeti verilebilir.",),
      InfoCardItem("eo_Info_184","5-Öğretim Basamaklarına Göre","A) Okul Öncesi \n-Okula uyum, çocukların sağlıklı gelişimleri ve becerilerini ortaya koyabilmeleri için rehberlik çalışmaları yürütülebilir.",),
      InfoCardItem("eo_Info_185","5-Öğretim Basamaklarına Göre","B) İlköğretim \n-Çocuğun tüm yönleriyle gelişmesini amaçlar.\n-Dili etkili kullanma, okuma yazma gibi becerilerin geliştirilmesini hedefler.",),
      InfoCardItem("eo_Info_186","5-Öğretim Basamaklarına Göre","C) Orta Öğretim \n-Meslek kazandırmayı ve yksek öğretime hazırlamayı amaçlar.",),
      InfoCardItem("eo_Info_187","5-Öğretim Basamaklarına Göre","D) Yüksek Öğretim\n-Barınma, beslenme, başarı, mesleğe hazırlama vb. gibi konularda rehberlik hizmeti verilir.",),
    ]),
    InfoCardModel("Özel Eğitim ve Rehberlik-3", [
      InfoCardItem("eo_Info_188","Rehberlik Hizmetlerinin Amaçları","Öğrencilerin;\n-Kendilerini tanımalarını sağlar.\n-Eğitim olanakları, mesleklerin ve toplmun isteklerini tanımalarını sağlar.\n-Kendilerini uygun programı seçmelerini sağlar.\n-Problem çözme ve doğru karar verme gibi becerilerinin gelişmesini amaçlar.",),
      InfoCardItem("eo_Info_189","Rehberlik Hizmetlerinin İlkeleri","-Eğitim öğretim etkinlikleriyle bütündür.\n-Tüm öğrencilere açıktır.\n-Öğrencinin seçme özgürlüğü vardır.\n-İnsana saygı esastır.\n-Gizlilik esastır.",),
      InfoCardItem("eo_Info_190","Rehberlik Hizmetlerinin İlkeleri-2","-Öğrenci, veli, öğretmen, yönetici, uzman işbirliği ile yürütülür.\n-Bireysel farklılıklara saygı duyulur.\n-Bireye ve topluma karşı saygı esastır.\n-Bilimsellik esastır.",),
      InfoCardItem("eo_Info_191","Rehberlik Servisleri","1-Öğrenciyi Tanıma Servisi \n2-Psikolojik Danışma Servisi\n3-Grup Rehberliği\n4-Eğitsel ve Mesleki Bilgi Verme Servisi\n5-Yerleştirme ve İzleme Servisi",),
      InfoCardItem("eo_Info_192","1-Öğrenciyi Tanıma Servisi","-Öğrencilerin gizli güçlerini ortaya çıkarmayı sağlar",),
      InfoCardItem("eo_Info_193","2-Psikolojik Danışma Servisi","-Okula uyum, sorun çözme gibi konularda destek olunur.",),
      InfoCardItem("eo_Info_194","3-Grup Rehberliği","-Tüm öğrencilere yöneliktir.\n-Bilgi verme, sorun çözme, uyum sağlama vb konularda yardımcı olunur.",),
      InfoCardItem("eo_Info_195","4-Eğitsel ve Mesleki Bilgi Verme Servisi","-Eğitsel ve mesleki bilgiler grup rehberliği ile öğrencilere verilir.",),
      InfoCardItem("eo_Info_196","5-Yerleştirme ve İzleme Servisi","-Öğrencinin ders ve programlara yerleşmesini sağlar.\n-Okullara öğrenci yerleştirmeyi sağlar.",),
    ]), InfoCardModel("Özel Eğitim ve Rehberlik-4", [
      InfoCardItem("eo_Info_197","Rehberlik Servisinin Görevleri","-Rehberlik hizmetlerini yürütülmesini ve yaygınlaştırılmasını sağlamak.\n-Programlarda bulunması gereken etkinlikler için önerilerde bulunmak.\n-İhtiyaç duyulan araç, gereç ve kaynakların sağlanması.",),
      InfoCardItem("eo_Info_198","Rehberlik ve Psikolojik Danışma Hizmetleri Yürütme Komisyonu","-Psikolojik danışman,\n-Sınıf rehber öğretmenlerinden her sınıf seviyesinden 1 öğretmen,\n-Disiplin kurulundan 1 kişi,\n-Okul aile birliği ve okul koruma derneğinden 1 kişi,\n-Okul öğrenci temsilcisi.",),
      InfoCardItem("eo_Info_199","Yürütme Komisyonunun Görevleri","-Yıllık rehberlik planlarını inceler, uygulanmasını sağlar.\n-Rehberlik hizmetlerinde çıkan sorunları inceler ve çözüm önerilerinde bulunur.\n-Eğitim ortamındaki kişilerin işbirliğini sağlar.\n-Mesleki rehberlik çalışmalarında gerekli yönlendirmeleri yapar.",),
      InfoCardItem("eo_Info_200","Okul Müdürünün Görevleri","-Gerekli fiziksel şartları, araç ve gereçleri sağlar.\n-Yürütme komisyonunu kurar ve başkanlık eder.\n-Yıllık rehberlik plan ve programlarının hazırlanmasını ve uygulanmasını sağlar.\n-Birden fazla öğretmen varsa birini koordinatör seçer.",),
      InfoCardItem("eo_Info_201","Okul Müdürünün Görevleri","-Psikolojik danışmanlar arasında iş bölümü yapar.\n-Sınıf rehber öğretmenlerini görevlendirir.\n-Başka okuldan gelen öğrencinin gelişim dosyasını rehberlik servisine iletir.\n-Rehberlik ve Araştırma Merkezine plan ve programın örneğini ilk ay, ders yılının son ayında da yıl sonu çalışma raporını gönderir.",),
      InfoCardItem("eo_Info_202","Okul Müdür Yardımcısının Görevleri","-Sorumlu olduğu sınıflardaki öğrencilerin sorunlarını, bilgi ve belgelerini rehberlik servisine iletir.\n-Yürütme komisyonu toplantılarına katılır.\n-Okul müdürünün vereceği görevleri yapar.\n-",),
      InfoCardItem("eo_Info_203","Koordinatörün Psikolojik Danışman Görevleri","-Rehberlik servisi ile okul yönetimi arasındaki iletişimi sağlar.\n-Rehberlik programlarını okul müdürüne iletir.\n-Rehberlik programları hakkında öğretmenler kuruluna bilgi verir.\n-Rehberlik hizmetleri etkinliklerine fiilen katılır.",),
      InfoCardItem("eo_Info_204","Psikolojik Danışman Görevleri-1","-Okulun rehberlik progrmaını hazırlar.\n-Rehberlik programlarının uygulanmasında sınıf öğretmenlerine rehberlik eder.\n-Eğitsel ve mesleki rehberlik etkinliklerini planlar ve uygulanmasına rehberlik eder.\n-Bireysel rehberlik hizmetlerini yürütür.",),
      InfoCardItem("eo_Info_205","Psikolojik Danışman Görevleri-2","-Öğrencilere yönelik bireyi tanıma etkinlikleirni yürütür.\n-Sınıflarda uygulanacak rehberlik etkinliklerinde uzmanlık gerektiren etkinlikleri uygular.\n-Mezun olacak öğrencinin değerlendirme raporunu hazırlar ve raporu gelişim dosyasına koyar.",),
      InfoCardItem("eo_Info_206","Psikolojik Danışman Görevleri-3","-Seçmeli derslere ilişkin araştırma yapar.\n-Özel eğitim gerektiren öğrencilere rehberlik hizmeti verir.\n-Okula nakil gelen öğrencilerin gelişim dosyalarını inceler ve sınıf rehber öğretmenleriyle değerlendirir.",),
      InfoCardItem("eo_Info_207","Psikolojik Danışman Görevleri-4","-Öğrenciye, ailelerine ve öğretmenlere gerektiğinde toplantı, etkinlik düzenler.\n-Rehberlik hizmetine ilişkin komisyonlara katılır.\n-Milli Eğitim Bakanlığı Orta Öğretim Kurumları Ödül ve Disiplin Yönetmeliğinde belirtilen görevleri yapar.",),
      InfoCardItem("eo_Info_208","Sınıf Rehber Öğretmeninin Görevleri-1","-Rehberlik programına göre sınıfın yıllık çalışmalarını planlar.\n-Eğitsel ve mesleki rehberlik etkinliklerini yapar.\n-Öğrenci gelişim dosyarının tutulmasında rehberlik servisiyle işbirliği yapar.",),
      InfoCardItem("eo_Info_209","Sınıf Rehber Öğretmeninin Görevleri-2","-Öğrencilerin özel bilgilerinin gizliliğini korur.\n-Rehberlik raporlarını ders yılı sonundaki ilk haftada rehberlik servisine iletir.\n-Okul müdürünün vereceği sınıf rehberliğiyle ilgili diğer görevleri yapar.",),
    ]),
    InfoCardModel("Özel Eğitim ve Rehberlik-5", [
      InfoCardItem("eo_Info_210","Akademik ve Mesleki Rehberlik Yöntemleri","-Sosyolojik Yaklaşım,\n-Karar Verme Yaklaşımı,\n-Varoluşçu Yaklaşım,\n-Gelişimsel Yaklaşım,\n-İhtiyaçlar Yaklaşımı,\n-Psikoanalitik Yaklaşım.",),
      InfoCardItem("eo_Info_211","1-Sosyolojik Yaklaşım","Meslek seçimini sosyolojik(aile, okul, toplum) değişkenlerinin belirlediği gibi savunur.",),
      InfoCardItem("eo_Info_212","2-Karar Verme Yaklaşımı","Meslek seçiminde bilgi kavrama süreçlerinin ve ödülleri algılama biçimlerinin etkili olduğunu savunur.",),
      InfoCardItem("eo_Info_213","3-Varoluşçu Yaklaşım","Kişisel farkındalıkların geliştirilmesinin meslek seçimini etkilediğini savunur.",),
      InfoCardItem("eo_Info_214","4-Gelişimsel Yaklaşım","Meslek seçimini hayat boyu gelişimin bir parçası olarak görür.",),
      InfoCardItem("eo_Info_215","5-İhtiyaçlar Yaklaşımı","Meslek seçimini psikolojik ihtiyaçların belirlediğini savunur.",),
      InfoCardItem("eo_Info_216","6-Psikoanalitik Yaklaşım","Meslek seçimini kişisel dinamiklerin belirlediini savunur.",),
    ]),InfoCardModel("Yönetmelik-1", [
      InfoCardItem("eo_Info_210","Temel ilkeler-1","-Bireysel farklılıkları, gelişim özellikleri ve eğitim ihtiyaçları dikkate alınarak eğitim hizmetisunulması, \n-Özel eğitimihtiyacı olan bireylerin ilgi, istek, yeterlilik ve yetenekleri doğrultusunda özel eğitim hizmetlerinden yararlandırılması, \n-Özeleğitim hizmetlerine erken dönemde başlanması (Madde5)"),
      InfoCardItem("eo_Info_211","Temel ilkeler-2","-Özel eğitimhizmetlerinin özel eğitim ihtiyacı olan bireyleri sosyal ve fiziksel çevrelerinden mümkün olduğu kadar ayırmadan, toplumla etkileşim ve karşılıklı uyum sağlama sürecini kapsayacak şekilde planlanıp yürütülmesi,\n-Özel eğitimihtiyacı olan bireylerin eğitsel performansları doğrultusunda amaç, içerik ve öğretim süreçlerinde uyarlamalar yapılarak diğer bireylerle birlikte eğitim görmelerine öncelik verilmesi (Madde5)"),
      InfoCardItem("eo_Info_212","Temel ilkeler-3","-Özel eğitimihtiyacı olan bireylerin eğitsel performansları doğrultusunda amaç, içerik ve öğretim süreçlerinde uyarlamalar yapılarak diğer bireylerle birlikte eğitim görmelerine öncelik verilmesi, \n-Özel eğitimihtiyacı olan bireylerin her tür ve kademedeki eğitimlerinisürdürebilmeleri için kurum ve kuruluşlarla iş birliği yapılması (Madde5)"),
      InfoCardItem("eo_Info_213","Temel ilkeler-4","-Özeleğitim ihtiyacı olan bireyler için BEP geliştirilmesi ve eğitim programlarının bireyselleştirilerek uygulanması, \n-Ailelerin, özeleğitim sürecinin her aşamasına aktif katılmalarının sağlanması,\n-Özel eğitim politikalarının geliştirilmesinde üniversitelerin ilgili bölümleri ve özeleğitim ihtiyacı olan bireylere yönelik  faaliyette bulunan sivil toplum kuruluşları ile iş birliği içinde çalışılması (Madde 5)"),
      InfoCardItem("eo_Info_214","Amaçlar","Türk Millî Eğitiminin genel amaç ve temel ilkeleri esas alınarak; özel eğitimihtiyacı olan bireylerin eğitim ihtiyaçları, yeterlilikleri, ilgi ve yetenekleri doğrultusunda kapasitelerinien üst düzeyde kullanmaları, üst öğrenime, meslek hayatına ve toplumsal yaşama hazırlanmalarınıamaçlar. (Madde 6)"),
    ]),InfoCardModel("Yönetmelik-2", [
      InfoCardItem("eo_Info_215","Değerlendirme ve esaslar-1","-Bireylerin eğitsel değerlendirmesi ve tanılaması ile ilgili iş ve işlemler RAM’larda oluşturulan özel eğitim değerlendirme kurulu tarafından yapılır.\n-Bireylerin eğitsel değerlendirmesi ve tanılamasıyla ilgili ilk başvuru; okul yönetimi, veli ya da zihinsel engeli olmayan 18 yaşından büyük bireyin kendisi tarafından; resmî kurumlarda bakım ve barınma hizmetinden yararlanan bireyler için kurumun resmî yazı ile görevlendireceği personel tarafından RAM’a yapılır. (Madde 7) "),
      InfoCardItem("eo_Info_216","Değerlendirme ve esaslar-2","-Uygun ortamda, bireyin özelliklerine uygun ölçme araçlarıyla yapılır, sağlık sorunu sebebiyle gelemeyenlere gidilir.\n-Özel eğitim ihytiyacı olan bireylere Özel Eğitim Değerlendirme Kurulu Raporu düzenlenir.\n-Destek eğitimi almasına karar verilenlere en fazla 1 yıllık eğitim planı hazırlanır.\n-Her tür eğitim kademesine geçişte yeniden değerlendirme yapılır.\n-Veli veya okulun yazılı talebiyle de tekrarlanabilir.  (Madde 7)"),
      InfoCardItem("eo_Info_217","Değerlendirme ve esaslar-3","-Türk okullarındaki öğrencilere RAM tarafından eğitsel değerlendirme ve tanılama hizmetisunulur.\n-Özel yetenekliolarak BİLSEM’e aday gösterilen öğrencilerin eğitsel değerlendirme vetanılaması ile ilgili iş ve işlemler Bakanlıkça yayımlanan kılavuzda açıklanan takvim doğrultusunda yapılır.  (Madde 7)"),
      InfoCardItem("eo_Info_218","Eğitsel Değerlendirmede Gerekli Belgeler-1","-Bireyin, velisinin ya da okul yönetiminin yazılı talebi, \n-Koruyucu aile yanında kalan bireyler için yapılan başvurularda koruyucu aile belgesi, \n-Okula kayıtlı olan öğrenciler için Eğitsel Değerlendirme İstek Formu (EK-3),\n-Birey için uygun eğitim ortamına yönlendirilmesiamaçlı başvurularda gerektiğinde Engelli Sağlık Kurulu Raporu,  (Madde 8)"),
      InfoCardItem("eo_Info_219","Eğitsel Değerlendirmede Gerekli Belgeler-2","-) Özel ÖğretimKurumları Kanunu kapsamında hizmet sunan kurumlarda destek eğitim hizmetialmak üzere yapılan başvurularda Engelli Sağlık Kurulu Raporu,\n- Özel ÖğretimKurumları Kanunu kapsamında hizmet sunan kurumlarda destek eğitim hizmetialan bireylerin raporlarının yenilenmesi için yapılan başvurularda ilgili kurumca düzenlenecek Dönem Sonu Bireysel Performans Değerlendirme Formu (EK-4) istenir.  (Madde 8)"),
      InfoCardItem("eo_Info_220","Kademeler Arası Geçişler-1","-Eğitimin her tür ve kademesindeki geçişlerde eğitsel değerlendirme ve tanılama yapılır.\n-İl veya ilçe özel eğitim hizmetleri kurulu tarafından yerleştirme kararı alınan öğrencilerin devam edeceği okullarda RAM’ın planlaması doğrultusunda okulrehberlik servisi ile işbirliği içerisinde öğrencinin okula uyumu ve eğitime erişimi ile ilgili gerekli tedbirler alınarak uygulama takip edilir.  (Madde 9)"),
      InfoCardItem("eo_Info_221","Kademeler Arası Geçişler-2","-RAM’ınplanlaması doğrultusunda okul rehberlik servisi ile işbirliği içerisinde öğretmenler, yöneticiler, aileler ve öğrenciler için gerekli bilgilendirme çalışmaları yapılır.\n- Özel eğitimihtiyacı olan öğrencilerden ders yılı sonunda kademeler arası geçiş yapacakların kayıtlı bulunduğu okullarda okul yönetimleri öğrencilerin RAM’a yönlendirilmesi ile ilgili iş ve işlemleri yürütür.  (Madde 9)"),
      InfoCardItem("eo_Info_222","İzleme","Özel eğitim hizmetlerinin planlanması ve eğitimde sürekliliğin sağlanmasıamacıyla erken çocukluk döneminden itibaren eğitimin her kademesinde özeleğitim ihtiyacı olan bireylerin gelişimlerinin ilgili okul ve kurumlarca takip edilerek kayıt altına alınmasıesastır.  (Madde 10)"),
    ]),InfoCardModel("Yönetmelik-3", [
      InfoCardItem("eo_Info_223","Özel Eğitim Hizmetleri-1","-0-36 aylık özeleğitim ihtiyacı olan çocuklar için erken çocukluk dönemi hizmetleri,ailenin bilgilendirilmesini ve esteklenmesini de içerecek şekilde yürütülür.\n-36 ayını tamamlayan özel eğitim ihtiyacı olan çocuklar için okul öncesi eğitim zorunludur. Çocukların gelişimi ve özellikleri dikkate alınarak okul öncesi dönemde eğitim süresi uzatılabilir. (Madde 11)"),
      InfoCardItem("eo_Info_224","Özel Eğitim Hizmetleri-2","-Özel eğitimihtiyacı olan bireylerin her tür ve kademedeki eğitimlerini kaynaştırma/bütünleştirme yoluyla sürdürmeleri esas olmakla birlikte bu bireylere yönelik özeleğitim kurumları veya özeleğitim sınıfları da açılabilir.\n-Resmî özeleğitim okullarında öğrenim gören özel eğitim ihtiyacı olan öğrenciler için örgün eğitim saatleri dışındaki zamanlarda tamamlayıcıeğitim faaliyetleri düzenlenebilir. (Madde 11)"),
      InfoCardItem("eo_Info_225","Özel Eğitim Hizmetleri-3","-İlköğretim veya ortaöğretim programlarını takip eden özel eğitim ihtiyacı olan öğrencilerden öğrenimlerini tamamlayamayanlar ya da öğrenim çağı dışına çıkanlar ile örgün eğitim kurumlarındaki öğrenim hakkını kullananların kayıtları açık öğretim okullarına yapılır.\n-Özel eğitimihtiyacı olan bireylerin mesleki, teknik, sosyal veya kültürel alanlarda bilgi ve becerilerle donatılması, onların hayata kazandırılması, üretken bireyler hâline getirilmesiamacıyla bu bireylere yaygın eğitim hizmetleri verilir. (Madde 11)"),
      InfoCardItem("eo_Info_226","Özel Eğitim Hizmetleri-4","-Örgün eğitimhizmetinden doğrudan yararlanamayacak öğrencilerin uzaktan eğitim yoluyla derslerini takip edebilmelerini sağlamak amacıyla bu öğrencilere Bakanlığın ilgili birimlerince teknolojik destek de dâhil olmak üzere gerekli hizmetler sunulur.\n- Özel yeteneklibireylere her tür ve kademede kayıtlı bulundukları okulların destek eğitim odalarında ve BİLSEM’lerde destek eğitim hizmeti verilir. (Madde 11)"),
]),InfoCardModel("Yönetmelik-4", [
      InfoCardItem("eo_Info_227","Erken çocukluk dönemi eğitimi-1","-0-36 aylık özeleğitim ihtiyacı olan çocuklar için erken çocukluk dönemieğitim hizmetleri il veya ilçe özel eğitim hizmetleri kurul kararı ile özeleğitim okulları, okul öncesi eğitim kurumları, bünyesinde ana sınıfı bulunan eğitim kurumları ile çocuk ve ailenin ihtiyaçları doğrultusunda evlerde de yürütülür.\n-Eğitim hizmetleri, velinin yazılı talebi üzerine Özel Eğitim Değerlendirme Kurulu Raporu doğrultusunda il veya ilçe özeleğitim hizmetleri kurulunca planlanır. (Madde 12)"),
      InfoCardItem("eo_Info_228","Erken çocukluk dönemi eğitimi-2","-Bakanlıkça hazırlanan eğitim programı esas alınarak özel eğitim ihtiyacı olan çocuk için BEP hazırlanarak aile eğitimi yoluyla hizmet verilir.\n-Erken çocukluk dönemi eğitim hizmetleri, ailelerin çocuklarının eğitimine katılım sağlayacakları şekilde kurumda veya evde yürütülür.(Madde 12)"),
      InfoCardItem("eo_Info_229","Erken çocukluk dönemi eğitimi-3","-Eğitimfaaliyetleri her bir çocuk için haftada 2 gün, ikişer eğitim saati olacak şekilde, okulun ders saatleri içinde veya dışında ihtiyaç halinde hafta sonu da planlanabilir. Bir eğitim saati 40 dakikadır. \n-Erken çocukluk döneminde sunulacak eğitim hizmetleri özel eğitim öğretmenleri, okul öncesi öğretmenleri, çocuk gelişimi ve eğitimi öğretmenleri tarafından yürütülür. (Madde 12)"),
      InfoCardItem("eo_Info_230","Birden Fazla Yetersizliği Olan Bireylerin Eğitimi-1","Zorunlu öğrenim çağında olup birden fazla yetersizliğinedeniyle ilköğretim veya ortaöğretim programlarına devam edemeyecek durumdaki öğrenciler için öncelikle özel eğitim okullarında; özel eğitim okulu bulunmayan yerleşim yerlerinde diğer okullar bünyesinde, il veya ilçe özel eğitim hizmetleri kurulunun teklifi doğrultusunda valilik oluru ile sınıf açılır. (Madde 13)"),
      InfoCardItem("eo_Info_231","Birden Fazla Yetersizliği Olan Bireylerin Eğitimi-2","-Sınıflarda özeleğitim programı uygulanır. Öğrencilerin başarılarının değerlendirilmesi, takip ettikleri özel eğitim programıesas alınarak hazırlanan BEP’e göre yapılır.\n-Bu sınıflarda birleştirilmiş sınıf uygulaması ile eğitim yapılır.\n-Sınıfların mevcudu en fazla 4 öğrenciden oluşur.\n-Dersler özeleğitim öğretmenleri tarafından okutulur.\n-Alan dersleri alan öğretmenleri tarafından okutulur.\n-Alan öğretmenlerinin derslerine özel eğitim öğretmenleri de katılır. (Madde 13)"),
      InfoCardItem("eo_Info_232","Birden Fazla Yetersizliği Olan Bireylerin Eğitimi-3","-Bu sınıflar ders, teneffüs, yemek ve diğer etkinlik saatleri bakımından bünyesinde açıldığı okulda uygulanan programa uyarlar.\n-Özel eğitimmeslek okulu veya özel eğitim uygulama okulu (III. kademe) programınıtamamlayan öğrencilere takip ettiklerieğitim programına uygun diploma (EK-8 veya EK-9) düzenlenir. (Madde 13)"),
  ]),
    InfoCardModel("Yönetmelik-5", [
      InfoCardItem("eo_Info_233","Evde eğitim hizmeti-1","Zorunlu öğrenim çağındaki özeleğitim ihtiyacı olan öğrencilerden sağlık problemi nedeniyle en az on iki hafta süreyle örgün eğitim kurumlarından yararlanamayacağı tespit edilirse 3 uzman tabip tarafından düzenlenen Durum Bildirir Sağlık Kurulu Raporu'nda belirtilen öğrencilere velinin yazılı talebi ve  Özel Eğitim Değerlendirme KuruluRaporu ile il veya ilçe özel eğitim hizmetleri kurulunun planlaması doğrultusunda ders yılı içinde evde eğitim hizmeti verilebilir. (Madde 14)"),
      InfoCardItem("eo_Info_234","Evde eğitim hizmeti-2","-Haftalık ders saati, ilköğretim ve ortaöğretim kademesinde okula kayıtlı olanlar için haftada 10, diğer ortaöğretim kademeleri için haftada 16 ders saatinden az olmayacak şekilde planlanır.\n-İlköğretimprogramını takip eden öğrenciler için okutulacak dersler belirlenirken merkezi sistem sınavlarında sorumlu olacakları dersler; ortaöğretim programlarını takip eden öğrenciler için okutulacak dersler belirlenirken ise öğrencinin seçtiği ders yoğunluğu dikkate alınarak planlama yapılır. (Madde 14)"),
      InfoCardItem("eo_Info_235","Evde eğitim hizmeti-3","-Özel eğitimprogramını takip eden öğrenciler için okutulacak dersler belirlenirken öğrencilerin eğitim ihtiyaçları ve özellikleri dikkate alınarak planlama yapılır.\n-Ortaöğretimkademesinde özel eğitim programından sorumlu olan öğrenciler için eğitim programında yer alan meslek dersleri dışındaki dersler için evde eğitim hizmeti planlanır. (Madde 14)"),
      InfoCardItem("eo_Info_236","Evde eğitim hizmeti-4","-Evde eğitimhizmetlerinde öğrencilerin eğitim ihtiyaçları ile takip edecekleri eğitim programı esas alınarak; özel eğitim öğretmenleri, okul öncesi öğretmenleri, sınıf ve diğer alan öğretmenleri görevlendirilir.\n-Öğretmen görevlendirmesi öncelikle öğrencinin kayıtlı olduğu yerdeki kadrolu öğretmenlerden istekli olanlardan, yoksa eğitim kurumu veya RAM'larda görevli kadrolu öğretmenlerden resen görevlendirme ile yapılır. (Madde 14)"),
      InfoCardItem("eo_Info_237","Evde eğitim hizmeti-5","-Öğrencilerin başarı durumlarının değerlendirilmesi, sorumlu olduğu eğitim programının uygulandığı okullardaki değerlendirme ölçütlerine göre yapılır.\n-Okutulan derslerin puanları e-Okul Sistemine işlenir.\n-Öğrenci okutulmayan derslerden muaf tutulur.\n-Bireylerin başarı değerlendirme sonuçları öğretmenler tarafından, öğrencinin kayıtlı bulunduğu okul yönetimine bildirilir.\n-Sınıf geçme ve diğer işlemler, kayıtlı olunan okul yönetimi tarafından yürütülür. (Madde 14)"),
      InfoCardItem("eo_Info_238","Evde eğitim hizmeti-6","-Evde eğitim hizmeti süresince bu öğrencilerin okula devam zorunluluğu aranmaz ve devam zorunluluğu aranmamasına yönelik e-Okul Sisteminde işlem yapılır.\n-Evde eğitimhizmetinden yararlanan öğrencilere verilen eğitim hizmetleri, bilişim teknolojileri de kullanılarak desteklenir.\n-Evde eğitim hizmeti hafta içi verilebileceği gibi hafta sonları da verilebilir.\n-Mesleki ve teknik eğitim okullarına kayıtlı öğrencilerde yalnızca 9.sınıflar için eğitim verilir. (Madde 14)"),
   ]),
    InfoCardModel("Yönetmelik-6", [
      InfoCardItem("eo_Info_239","Hastanede eğitim hizmeti-1","-Eğitim hizmeti, velinin yazılı talebi ve öğrencinin tedavisinden sorumlu hekimin yazılı görüşü ile sağlanır.\n-Bu sınıflarda birleştirilmiş sınıf uygulaması ile eğitim yapılır.\n-Sınıfa gelemeyecek durumda olan öğrencilere odalarında eğitim verilir.\n-İlköğretim ve özel eğitim programı uygulanan ortaöğretim kademesindeki öğrenciler için haftalık ders saati 10, diğer ortaöğretim kademesindeki öğrenciler için haftalık 16 saatten az olamaz. (Madde 15)"),
      InfoCardItem("eo_Info_240","Hastanede eğitim hizmeti-2","-Derse başlama ve bitiş saatleri ile derslerin süresi, eğitim alacak öğrencinin sağlık durumu ve hastane şartları dikkate alınarak il veya ilçe özeleğitim hizmetleri kurulu tarafından belirlenir.\n-Hastanesınıflarında eğitimlerini sürdüren öğrencilere kayıtlı bulundukları sınıfta uygulanan öğretim programları uygulanır. (Madde 15)"),
      InfoCardItem("eo_Info_241","Hastanede eğitim hizmeti-3","-Öğrencilerin başarı durumlarının değerlendirilmesi, kayıtlı bulundukları sınıftaki değerlendirme ölçütlerine göre hastane sınıfında okutulan dersler için yapılır. Okutulan bu derslerin puanları e-Okul Sistemine işlenir. Öğrenciokutulmayan derslerden muaf tutulur.\n-Hastane sınıfındaki öğrencilerin başarı değerlendirme sonuçları öğretmenler tarafından öğrencilerin kayıtlı bulundukları okul yönetimine bildirilir. Sınıf geçme, diğer iş ve işlemler kayıtlı oldukları okul yönetimi tarafından yürütülür. (Madde 15)"),
      InfoCardItem("eo_Info_242","Hastanede eğitim hizmeti-4","-Hastane sınıfındaki öğrencilerin başarı değerlendirme sonuçları öğretmenler tarafından öğrencilerin kayıtlı bulundukları okul yönetimine bildirilir. Sınıf geçme, diğer iş ve işlemler kayıtlı oldukları okul yönetimi tarafından yürütülür.\n-Bu öğrencilerin okula devam zorunluluğu aranmaz ve e-Okul Sisteminde devam zorunluluğu aranmamasına yönelik işlem yapılır. (Madde 15)"),
      InfoCardItem("eo_Info_243","Hastanede eğitim hizmeti-5","-Hastane sınıfı normunda bulunan sınıf öğretmenleri bu sınıfta eğitim alacak öğrencilerle ilgili iş ve işlemleri yürütmek üzere il veya ilçe özeleğitim hizmetleri kurulu ile iş birliği içinde çalışır.\n-Özel eğitim öğretmenleri, okul öncesi öğretmenleri, sınıf ve diğer alan öğretmenleri görevlendirilir.\n-Bölgede istekli öğretmen bulunamazsa RAM'lardaki kadrolu öğretmenlerden resen görevlendirme yapılır. (Madde 15)"),
      InfoCardItem("eo_Info_244","Hastanede eğitim hizmeti-6","-Hastanede biraydan daha az süre yatarak tedavi gören bireylerin eğitimleri takip ettikleri öğretim programları esas alınarak verilir.\n-Bu durumda hastane sınıfında verilen eğitimin başarı değerlendirmesi yapılmaz.\n-Öğrencilere verilen eğitim hizmetleri, bilişim teknolojileri de kullanılarak desteklenir.\n-İlköğretim programında merkezi sistem sınavlarında okutulacak dersler, ortaöğretim programlarında öğrencinin seçtiği ders yoğunluğu dikkate alınır. (Madde 15)"),
      InfoCardItem("eo_Info_245","Hastanede eğitim hizmeti-7","-Özel eğitimprogramını takip eden öğrenciler için okutulacak dersler belirlenirken öğrencilerin eğitim ihtiyaçları ve özellikleri dikkate alınarak planlama yapılır.\n-Ortaöğretim programında meslek dersleri dışındaki dersler için hastanede eğitim planlanır.\n-Mesleki veteknik eğitim programlarının uygulandığı okullarda kayıtlı olan öğrencilerden sadece 9 uncu sınıf öğrencileri için hastanede eğitim hizmetisunulur. (Madde 15)"),

    ]),
    InfoCardModel("Yönetmelik-7", [
      InfoCardItem("eo_Info_246","Grup eğitimine hazırlık uygulaması-1","-Uygulama, ders saatleri içerisinde okul yönetimince belirlenen uygun bir ortamda yapılır.\n-Bu eğitimialacak öğrencilerin tespiti ile öğrencilerin alacağı haftalık ders saati ve yürütülecek eğitim faaliyetlerine ilişkin planlama haftalık toplam ders saatinin %40’ınıaşmayacak şekilde BEP geliştirme birimince yapılır. (Madde 16)"),
      InfoCardItem("eo_Info_247","Grup eğitimine hazırlık uygulaması-2","-Öğrenciler bu uygulamanın dışında kalan sürelerde BEP geliştirme biriminin planlamasıdoğrultusunda eğitimlerine sınıflarında devam edebilirler.\n-Bu kapsamda grup eğitimine katılamayan öğrenciler için devam zorunluluğu aranmaz ve e-Okul Sisteminde devam zorunluluğu aranmamasına yönelik işlem yapılır.\n-Grup eğitimine hazırlık uygulamalarını özeleğitim öğretmenleri yürütür. (Madde 16)"),
      InfoCardItem("eo_Info_248","Tamamlayıcı eğitim faaliyetleri-1","-Eğitim faaliyeti, velinin yazılı talebi ve BEP geliştirme biriminin kararı doğrultusunda okul yönetimince planlanır.\n-Bire bir ya da aynı tür yetersizliğe sahip en fazla 3 öğrenci ile yürütülür.\n-Her bir öğrenci için haftalık 2 ders saati olacak şekilde planlanır. (Madde 17)"),
      InfoCardItem("eo_Info_249","Tamamlayıcı eğitim faaliyetleri-2","-Öğrencinin tüm gelişim alanlarındaki özellikleri ve eğitim ihtiyaçları ile akademik yeterlikleri doğrultusunda yürütülür.\n-Özel eğitim öğretmenleri tarafından yürütülür.\n-Eğitim faaliyetinin yürütülmesinde bir özel eğitim öğretmeni görevlendirilir.(Madde 17)"),
      InfoCardItem("eo_Info_250","Aile eğitimi hizmetleri","-Aile eğitimi, her tür ve kademedeki özel eğitim ihtiyacı olan öğrencilerin eğitimine katkı sağlamak amacıyla aileye verilecek her türlü rehberlik ve eğitim hizmetlerini içerir. Bu hizmetler Bakanlıkça hazırlanan aile eğitimi programı doğrultusunda okul ve kurumlarda yürütülür. (Madde 18)"),

    ]),
    InfoCardModel("Yönetmelik-8", [
      ///yeni alan
      InfoCardItem("eo_Info_251","Bireyselleştirilmiş eğitim programı-1","-Özel eğitim ihtiyacı olan bireyler için takip edecekleri eğitim programıtemel alınarak BEP hazırlanmasıesastır.\n\Bu programda;\n-Eğitim planında yer alan yıllık amaçlara ve kısa dönemli amaçlara,\n-Sunulacak destek eğitim hizmetinin türüne, süresine ve hizmetin kimler tarafından nasıl sağlanacağına,\n-Öğretim ve değerlendirmede kullanılacak yöntem ve teknikler ile öğretim materyallerine, (Madde 20)"),
      InfoCardItem("eo_Info_252","Bireyselleştirilmiş eğitim programı-2","-Eğitim ortamına ilişkin düzenlemelere, Davranış problemlerini önlemeye ya da azaltmaya yönelik tedbirler ile olumlu davranış kazandırmaya yönelik uygulanacak yöntem ve tekniklere, Öğrencinin kişisel bilgilerine,  yer verilir. (Madde 20)"),
      InfoCardItem("eo_Info_253","BİLSEM eğitim programları","-Uyum, \n-Destek eğitim, \n-Bireysel yetenekleri fark ettirme, \n-Özel yetenekleri geliştirme, \n-Proje üretimi ve yönetimi programına alınırlar. \n- Programlarıtamamlayan öğrencilere tamamladığı her programın sonunda bilim ve sanat merkezi müdürlüğünce “Program Tamamlama Belgesi” (EK – 10) verilir. (Madde 21)"),
      InfoCardItem("eo_Info_254","Kaynaştırma/bütünleştirme yoluyla eğitim-1","-Özel Eğitim Değerlendirme Kurulu Raporu doğrultusunda her tür kademedeki eğitimlerini kaynaştırma/bütünleştirme yoluyla sürdürebilirler.\n-Eğitimlerini akranları ile birlikte aynı sınıfta tam zamanlı veya özeleğitim sınıflarında yarızamanlı olarak sürdürebilirler.\n-BEP geliştirme birimi oluşturulması zorunludur. (Madde 22)"),
      InfoCardItem("eo_Info_255","Kaynaştırma/bütünleştirme yoluyla eğitim-2","-Okul öncesi eğitim, ilköğretim ya da mesleki ve teknik eğitim programlarının uygulandığı özel eğitim okullarında kaynaştırma/bütünleştirme yoluyla eğitim verilebilir.\n-Öğrenci Davranışlarını Değerlendirme Kurulu ile Ödül ve Disiplin Kurulu’nda kaynaştırma/bütünleştirme yoluyla eğitimlerine devam eden öğrencilerle ilgilialınacak kararlarda BEP geliştirme birimiyle iş birliği yapılır. (Madde 22)"),
      InfoCardItem("eo_Info_256","Tam zamanlı kaynaştırma eğitimi","-Okulda uygulanan eğitim programı takip edilir.\n-Öğrencilerin takip ettikleri programlar temel alınarak BEP hazırlanır.\n-Ortaöğretimi tamamlayan öğrencilere akranlarına verilen diploma düzenlenir.\n-Uygun ortam düzenlemesi yapılır ve destek eğitim odası açılır.\n-Öğrenciler sınıflara eşit sayılarda ve her sınıfta 2'yi geçmeyecek şekilde dağıtılır.\n-Özel eğitim okullarında sınıflar 5'i özel eğitim ihtiyaçlı olmak üzere okul öncesinde en fazla 14, diğer kademelerde 15 olarak belirlenir. (Madde 23)"),
      InfoCardItem("eo_Info_257","Başarının değerlendirilmesi","-BEP'e göre değerlendirilir.\n-Öğrenci özelliklerine göre düzenlemeler yapılır.\n-Merkezi sınav sistemlerinde gerekli tedbirler alınır.\n-Veli talebi ve BEP geliştirme birimi kararıyla yabancı dil dersinden muaf olabilirler.\n-İlkokulda veli talebiyle bir defaya mahsus olmak üzere sınıf tekrarı yaptırılabilir. (Madde 24)"),
      InfoCardItem("eo_Info_258","Destek eğitim odası-1","-Haftalık ders programın toplam ders saatinin %40'ını aşmayacak şekilde düzenlenir.\n-Birden fazla oda açılabilir.\n-Birebir eğitim esastır.\n-Gerektiğinde en fazla 3 öğrenci ile eğitim yapılabilir.\n-Ders saatleri içinde veya haftasonu ders verilebilir.\n-Öğrenciye ders saatleri içinde eğitim verilecekse destek eğitim alması planlanan dersin saatinde o derse ilişkin eğitim verilir. (Madde 25)"),
      InfoCardItem("eo_Info_259","Destek eğitim odası-2","-Dersler zenginleştirme ve hızlandırma yoluyla farklılaştırılarak verilir.\n-Örgün eğitim kurumlarındaki dersler ile paralellik göstererek işlenir.\n-Özel eğitim öğretmenleri, okul öncesi öğretmenleri, sınıf ve diğer alan öğretmenleri okul yönetiminin teklifi doğrultusunda il veya ilçe millîeğitim müdürlüklerince görevlendirilir.\n-İlkokul ve ortaokullarda üst kademe öğretmenleri görevlendirilebilir.\n-Okul müdürü ve müdür yardımcıları destek eğitim odalarında görevlendirilmez(Madde 25)"),
      InfoCardItem("eo_Info_260","Özel eğitim sınıflarının açılması","-Özel Eğitim Değerlendirme Kurulu Raporu doğrultusunda ayrı sınıfta öğrenim görmesine karar verilen öğrenciler için valilik oluru ile özel eğitim sınıfı açılabilir.\n-Valilik olurunda okul adı, sınıf kademesi, eğitim progrmaı ve eğitim verilecek yetersizlik türü bilgileri yer alır. (Madde 26)"),
      InfoCardItem("eo_Info_261","","(Madde )"),
      InfoCardItem("eo_Info_262","","(Madde )"),
      InfoCardItem("eo_Info_263","","(Madde )"),
      InfoCardItem("eo_Info_264","","(Madde )"),
      InfoCardItem("eo_Info_265","","(Madde )"),
      InfoCardItem("eo_Info_266","","(Madde )"),
      InfoCardItem("eo_Info_267","","(Madde )"),
      InfoCardItem("eo_Info_268","","(Madde )"),
      InfoCardItem("eo_Info_269","","(Madde )"),
      InfoCardItem("eo_Info_270","","(Madde )"),
      InfoCardItem("eo_Info_271","","(Madde )"),
      InfoCardItem("eo_Info_272","","(Madde )"),
      InfoCardItem("eo_Info_273","","(Madde )"),
      InfoCardItem("eo_Info_274","","(Madde )"),
      InfoCardItem("eo_Info_275","","(Madde )"),
      InfoCardItem("eo_Info_276","","(Madde )"),
      InfoCardItem("eo_Info_277","","(Madde )"),
      InfoCardItem("eo_Info_278","","(Madde )"),
      InfoCardItem("eo_Info_279","","(Madde )"),
      InfoCardItem("eo_Info_280","","(Madde )"),
      InfoCardItem("eo_Info_281","","(Madde )"),
      InfoCardItem("eo_Info_282","","(Madde )"),
      InfoCardItem("eo_Info_283","","(Madde )"),
      InfoCardItem("eo_Info_284","","(Madde )"),
      InfoCardItem("eo_Info_285","","(Madde )"),
      InfoCardItem("eo_Info_286","","(Madde )"),
      InfoCardItem("eo_Info_287","","(Madde )"),
      InfoCardItem("eo_Info_288","","(Madde )"),
      InfoCardItem("eo_Info_289","","(Madde )"),
      InfoCardItem("eo_Info_29","","(Madde )"),


    ]),
    InfoCardModel("Yönetmelik-9", [

        ]),
    InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
    /*InfoCardModel("", [
      InfoCardItem("ozelegitim_info_1", "", ""),
      InfoCardItem("ozelegitim_info_2", "", ""),
      InfoCardItem("ozelegitim_info_3", "", ""),
      InfoCardItem("ozelegitim_info_4", "", ""),
      InfoCardItem("ozelegitim_info_5", "", ""),
      InfoCardItem("ozelegitim_info_6", "", ""),
      InfoCardItem("ozelegitim_info_7", "", ""),
      InfoCardItem("ozelegitim_info_8", "", ""),
      InfoCardItem("ozelegitim_info_9", "", ""),
      InfoCardItem("ozelegitim_info_10", "", ""),
      InfoCardItem("ozelegitim_info_11", "", ""),
      InfoCardItem("ozelegitim_info_12", "", ""),
      InfoCardItem("ozelegitim_info_13", "", ""),
      InfoCardItem("ozelegitim_info_14", "", ""),
      InfoCardItem("ozelegitim_info_15", "", ""),
      InfoCardItem("ozelegitim_info_16", "", ""),
      InfoCardItem("ozelegitim_info_17", "", ""),
      InfoCardItem("ozelegitim_info_18", "", ""),
      InfoCardItem("ozelegitim_info_19", "", ""),
      InfoCardItem("ozelegitim_info_20", "", ""),
      InfoCardItem("ozelegitim_info_21", "", ""),
      InfoCardItem("ozelegitim_info_22", "", ""),
      InfoCardItem("ozelegitim_info_23", "", ""),
      InfoCardItem("ozelegitim_info_24", "", ""),
      InfoCardItem("ozelegitim_info_25", "", ""),
      InfoCardItem("ozelegitim_info_26", "", ""),
      InfoCardItem("ozelegitim_info_27", "", ""),
      InfoCardItem("ozelegitim_info_28", "", ""),
      InfoCardItem("ozelegitim_info_29", "", ""),
      InfoCardItem("ozelegitim_info_30", "", ""),
      InfoCardItem("ozelegitim_info_31", "", ""),
      InfoCardItem("ozelegitim_info_32", "", ""),
      InfoCardItem("ozelegitim_info_33", "", ""),
      InfoCardItem("ozelegitim_info_34", "", ""),
      InfoCardItem("ozelegitim_info_35", "", ""),
      InfoCardItem("ozelegitim_info_36", "", ""),
      InfoCardItem("ozelegitim_info_37", "", ""),
      InfoCardItem("ozelegitim_info_38", "", ""),
      InfoCardItem("ozelegitim_info_39", "", ""),
      InfoCardItem("ozelegitim_info_40", "", ""),
      InfoCardItem("ozelegitim_info_41", "", ""),
      InfoCardItem("ozelegitim_info_42", "", ""),
      InfoCardItem("ozelegitim_info_43", "", ""),
      InfoCardItem("ozelegitim_info_44", "", ""),
      InfoCardItem("ozelegitim_info_45", "", ""),
      InfoCardItem("ozelegitim_info_46", "", ""),
      InfoCardItem("ozelegitim_info_47", "", ""),
      InfoCardItem("ozelegitim_info_48", "", ""),
      InfoCardItem("ozelegitim_info_49", "", ""),
      InfoCardItem("ozelegitim_info_50", "", ""),
      InfoCardItem("ozelegitim_info_51", "", ""),
      InfoCardItem("ozelegitim_info_52", "", ""),
      InfoCardItem("ozelegitim_info_53", "", ""),
      InfoCardItem("ozelegitim_info_54", "", ""),
      InfoCardItem("ozelegitim_info_55", "", ""),
      InfoCardItem("ozelegitim_info_56", "", ""),
      InfoCardItem("ozelegitim_info_57", "", ""),
      InfoCardItem("ozelegitim_info_58", "", ""),
      InfoCardItem("ozelegitim_info_59", "", ""),
      InfoCardItem("ozelegitim_info_60", "", ""),
      InfoCardItem("ozelegitim_info_61", "", ""),
      InfoCardItem("ozelegitim_info_62", "", ""),
      InfoCardItem("ozelegitim_info_63", "", ""),
      InfoCardItem("ozelegitim_info_64", "", ""),
      InfoCardItem("ozelegitim_info_65", "", ""),
      InfoCardItem("ozelegitim_info_66", "", ""),
      InfoCardItem("ozelegitim_info_67", "", ""),
      InfoCardItem("ozelegitim_info_68", "", ""),
      InfoCardItem("ozelegitim_info_69", "", ""),
      InfoCardItem("ozelegitim_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get ozelEgitim => _ozelEgitimList;}