import 'package:flutter/material.dart';

import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class SosyalEtkilesimInfoViewModel extends ChangeNotifier{
  List<InfoCardModel> _sosyalEtkilesimList = [
    InfoCardModel("Hazırlanıyor", [
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
      InfoCardItem("Hazırlanıyor", "Hazırlanıyor", "Hazırlanıyor"),
    ]),
 /*   InfoCardModel("", [
      InfoCardItem("sosyaletkilesim_info_1", "", ""),
      InfoCardItem("sosyaletkilesim_info_2", "", ""),
      InfoCardItem("sosyaletkilesim_info_3", "", ""),
      InfoCardItem("sosyaletkilesim_info_4", "", ""),
      InfoCardItem("sosyaletkilesim_info_5", "", ""),
      InfoCardItem("sosyaletkilesim_info_6", "", ""),
      InfoCardItem("sosyaletkilesim_info_7", "", ""),
      InfoCardItem("sosyaletkilesim_info_8", "", ""),
      InfoCardItem("sosyaletkilesim_info_9", "", ""),
      InfoCardItem("sosyaletkilesim_info_10", "", ""),
      InfoCardItem("sosyaletkilesim_info_11", "", ""),
      InfoCardItem("sosyaletkilesim_info_12", "", ""),
      InfoCardItem("sosyaletkilesim_info_13", "", ""),
      InfoCardItem("sosyaletkilesim_info_14", "", ""),
      InfoCardItem("sosyaletkilesim_info_15", "", ""),
      InfoCardItem("sosyaletkilesim_info_16", "", ""),
      InfoCardItem("sosyaletkilesim_info_17", "", ""),
      InfoCardItem("sosyaletkilesim_info_18", "", ""),
      InfoCardItem("sosyaletkilesim_info_19", "", ""),
      InfoCardItem("sosyaletkilesim_info_20", "", ""),
      InfoCardItem("sosyaletkilesim_info_21", "", ""),
      InfoCardItem("sosyaletkilesim_info_22", "", ""),
      InfoCardItem("sosyaletkilesim_info_23", "", ""),
      InfoCardItem("sosyaletkilesim_info_24", "", ""),
      InfoCardItem("sosyaletkilesim_info_25", "", ""),
      InfoCardItem("sosyaletkilesim_info_26", "", ""),
      InfoCardItem("sosyaletkilesim_info_27", "", ""),
      InfoCardItem("sosyaletkilesim_info_28", "", ""),
      InfoCardItem("sosyaletkilesim_info_29", "", ""),
      InfoCardItem("sosyaletkilesim_info_30", "", ""),
      InfoCardItem("sosyaletkilesim_info_31", "", ""),
      InfoCardItem("sosyaletkilesim_info_32", "", ""),
      InfoCardItem("sosyaletkilesim_info_33", "", ""),
      InfoCardItem("sosyaletkilesim_info_34", "", ""),
      InfoCardItem("sosyaletkilesim_info_35", "", ""),
      InfoCardItem("sosyaletkilesim_info_36", "", ""),
      InfoCardItem("sosyaletkilesim_info_37", "", ""),
      InfoCardItem("sosyaletkilesim_info_38", "", ""),
      InfoCardItem("sosyaletkilesim_info_39", "", ""),
      InfoCardItem("sosyaletkilesim_info_40", "", ""),
      InfoCardItem("sosyaletkilesim_info_41", "", ""),
      InfoCardItem("sosyaletkilesim_info_42", "", ""),
      InfoCardItem("sosyaletkilesim_info_43", "", ""),
      InfoCardItem("sosyaletkilesim_info_44", "", ""),
      InfoCardItem("sosyaletkilesim_info_45", "", ""),
      InfoCardItem("sosyaletkilesim_info_46", "", ""),
      InfoCardItem("sosyaletkilesim_info_47", "", ""),
      InfoCardItem("sosyaletkilesim_info_48", "", ""),
      InfoCardItem("sosyaletkilesim_info_49", "", ""),
      InfoCardItem("sosyaletkilesim_info_50", "", ""),
      InfoCardItem("sosyaletkilesim_info_51", "", ""),
      InfoCardItem("sosyaletkilesim_info_52", "", ""),
      InfoCardItem("sosyaletkilesim_info_53", "", ""),
      InfoCardItem("sosyaletkilesim_info_54", "", ""),
      InfoCardItem("sosyaletkilesim_info_55", "", ""),
      InfoCardItem("sosyaletkilesim_info_56", "", ""),
      InfoCardItem("sosyaletkilesim_info_57", "", ""),
      InfoCardItem("sosyaletkilesim_info_58", "", ""),
      InfoCardItem("sosyaletkilesim_info_59", "", ""),
      InfoCardItem("sosyaletkilesim_info_60", "", ""),
      InfoCardItem("sosyaletkilesim_info_61", "", ""),
      InfoCardItem("sosyaletkilesim_info_62", "", ""),
      InfoCardItem("sosyaletkilesim_info_63", "", ""),
      InfoCardItem("sosyaletkilesim_info_64", "", ""),
      InfoCardItem("sosyaletkilesim_info_65", "", ""),
      InfoCardItem("sosyaletkilesim_info_66", "", ""),
      InfoCardItem("sosyaletkilesim_info_67", "", ""),
      InfoCardItem("sosyaletkilesim_info_68", "", ""),
      InfoCardItem("sosyaletkilesim_info_69", "", ""),
      InfoCardItem("sosyaletkilesim_info_7", "", ""),
    ])*/
  ];

  List<InfoCardModel> get sosyalEtkilesim => _sosyalEtkilesimList;}