import '../../model/info_card_item.dart';
import '../../model/info_card_model.dart';

class TurkceInfoViewModel {
  List<InfoCardModel> _turkceInfoCard = [
    InfoCardModel("Yazım Kuralları-1", [
      InfoCardItem("turkce_info_1","Büyük Harflerin Kullanımı-1", "-Özel isimlerin baş harfi (Ali),\n-Tırnak içine alınan cümlelerin ilk harfi,\n-Ülke, bölge, il isimleri(Ege Bölgesi),\n-Akarsu, deniz, dağ, göl, orman isimleri(Tuz Gölü),\n-Unvan sıfatları özel ismin yerini tutuyorsa(Avukat Ahmet),\n-Millet, dil, din adları(Türk Milleti)"),
      InfoCardItem("turkce_info_2","Büyük Harflerin Kullanımı-2", "-Resmi yazılarda makam, mevki bildiren kelimeler(Sayın Kaymakam),\n-Saray, köprü, kale vb. isimleri(Keçi Kalesi),\n-Kanun, tüzük, yönetmelik isimleri(Medeni Kanun),\n-Bayram isimleri(Ramazan Bayramı),\n-Savaş, dönem adları(Çanakkale Savaşı),\n-Gezegen isimleri(Terim olarak kullnaılırsa)"),
      InfoCardItem("turkce_info_3","Büyük Harflerin Kullanımı-3", "-Yer, millet adıyla kurulan kelimelerin özel ad kısmı(Aydın inciri),\n-Kurum, dernek, iş yeri adları(Kedileri Koruma Derneği),\n-Kitap, dergi, gazete isimleri,\n-Dükkan, mağaza, fabrika isimleri,\n-Saygı ifadeleri,\n-Yazı başlıklarının ilk harfi,\n-Tarihlerdeki ay/gün adları"),
      InfoCardItem("turkce_info_4","Sayıların Yazım Kuralları-1", "-Şahıs numarası, telefon, dergi, kitap sayfaları numara ile yazılır.(sayfa: 15)\n-Sayı ve ekleri arasına tırnak işareti konur.(1903'te)\n-Tahmin içeren rakamlar yazı ile yazılır.(Gelen veli üç yüz civarıydı)\n-Zamanlama bildiren ifadeler çeyrek/yarım  ifade etmiyorsa yazı ile yazılır.(Toplantı saati on iki on beş)"),
      InfoCardItem("turkce_info_5","Sayıların Yazım Kuralları-2", "-Sıfat ve zarflar derece gösteriyorsa yazıyla yazılır.(Evin ikinci katı)\n-Aydan sonra tarih belirtirsek yazı ile yazılır.(Okullar Haziran'ın yirmisinde kapanacak)\n-Bilimsel ifadelerde kesinlik varsa sayı ile yazılır.(Kilometre 1000 metredir)\n-Çok sıfır içeren sayılar(20 milyon TL)"),
      InfoCardItem("turkce_info_6","de'nin Yazımı", "-Hal eki olarak kullanılırsa bitişik yazılır.(Kamera yerinde mi?)\n-Bağlaç olan de ayrı yazılır ve ünlü uyumuna uyar.(Oğlu da gelini de)"),
      InfoCardItem("turkce_info_7","ki'nin Yazımı", "-ki ekine '-ler' ekini getirdiğimizde anlam bozulursa bağlaçtır ve ayrı yazılır. Aksi halde bitişik yazılır\n-Örn: Şimdiki nesil daha sosyal(şimdikiler)\n-Öyle zor soru ki yapamadı.(soru kiler))"),
      InfoCardItem("turkce_info_8","mi'nin Yazımı", "-Soru eki ise ayrı yazılır. \n-Örn: Toplantıya Osman geldi mi?"),
      InfoCardItem("turkce_info_9","Birleşik Kelimelerin Yazımı-1", "-Ses düşmesi varsa(kayın ana_> kaynana)\n-Kelimelerden ikincisinin veya her ikisinin anlamı değişirse(Alinazik, kuşburnu, beştaş)\n-Zarf fiil ekiyle(e,a,ı,i,u,ü) fiil birleşirse(ölmek+yazmak=öleyazmak, çıkmak+gelmek=çıkagelmek)\n-Öğelerinden bir veya ikisi emir kipi olanlar(yapboz, çekyat)"),
      InfoCardItem("turkce_info_10","Birleşik Kelimelerin Yazımı-2", "-Sıfat fiil ekleriyle(an, en, r, ar, er, ır, ir, maz, mez, miş, mış) kurulan kelimeler(kuşkonMAZ, gökdelEN)\n-İkinci kelimesinde dı, di, du, dü, tı, ti, tu, tü içeren kelimeler(fırdönDÜ, gecekonDU, külbasTI)\n-iki kelimesi dı, di, du, dü, tı, ti, tu, tü içeren kelimeler(deDİkoDU, olDU, bitTİ)"),
      InfoCardItem("turkce_info_11","Birleşik Kelimelerin Yazımı-3", "-Her iki kelimesi r, ar, er içeren kelimeler(biçERdövER,okuRyazaR)\n-Somut yer bildirmeyen alt, üst, üzeri içerenler(gözaltı, akşamüstü, akşamüzeri)\n-Ad, soyad ve lakaplar(Atatürk, Gülnihal, Abasıyanık)\n-İl, ilçe ve semt isimleri(Çanakkale, Suşehri, Batıkent)"),
      InfoCardItem("turkce_info_12","Birleşik Kelimelerin Yazımı-4", "-Ara yön belirten kelimeler(güneybatı, kuzeydoğu)\n-İki kelimenin de anlamını koruduğu gelenekselleşmiş kelimeler(başöğretmen, hanımefendi)\n-Ev, hane, name, zade, zede ile birleşenler(aşevi, dershane, kanunname, depremzede)\n-Müzikteki makam adları(acembuselik, muhayyerkürdi)"),
      InfoCardItem("turkce_info_13","Birleşik Kelimelerin Yazımı-5", "-Kanunda bitişik geçen ve tescillenmiş kelimeler(Genelkurmay, içişleri, açıköğretim)\n-Renklerle kurulan isimler(alabalık, karadut, beyazçiçek)"),
      InfoCardItem("turkce_info_14","Ayrı Yazılan Birleşik Kelimeler", "-Yardımcı fiillerle(etmek, eylemek) kurulan kelimelerde ses düşmesi yoksa(göç etmek, dans etmek)\n-İkinci kelime yada hiçbir kelime anlam değiştirmezse(dil balığı, ardıç kuşu, meyan kökü, çevre yolu, dil bilgisi)\n-Sıfat fiil(r,ar,er,maz,mez,an,en) kurulan sıfat tamlamaları(bakar kör, tükenmez kalem)"),
      InfoCardItem("turkce_info_15","Ayrı Yazılan Birleşik Kelimeler-1", "-Renk adıyla kurulmuş isim tamlamaları(limon sarısı, ateş kırmızısı)\n-Renk tonunu ifade eden kelimeler(açık mavi, koyu gri)\n-Yer bildiren ifadeler(Orta Anadolu, Aşağı Ayrancı, Orta Asya)\n-Dış, iç, sıra ile oluşturulan kelimeler(çağ dışı, ceviz içi, yanı sıra, sıra dışı )"),
      InfoCardItem("turkce_info_16","Ayrı Yazılan Birleşik Kelimeler-2", "-Somut yer belirten alt, üst kelimeleriyle birleşen(yer altı, böbrek üstü)\n- Alt, üst, ana, ön, art, arka, yan, karşı, iç, dış, orta, büyük, küçük, sağ, sol, peşin, bir, iki, tek, çok, çift kelimelerini başa getiren birleşik kelimeler ayrı yazılır(üst kat, sağ bek, dış borç)"),
    ]),
    InfoCardModel("Yazım Kuralları-2", [
      InfoCardItem("turkce_info_17","Noktalama İşaretleri","-Anlamı netleştirir,\n-Metnin düzgün okunmasını sağlar.\n-Nefes alma yerlerini gösterir.\n-Tonlamayı kolaylaştırır.",),
      InfoCardItem("turkce_info_18","Nokta", "-Cümle sonlarında kullanılır.\n-Kısaltmalarda kullanılır.(doç., cad.)\n-Aktarma cümlesi tırnak içinde değilse sonuna nokta konur.(Gelsene, dedi.)\n-Rakamlar sıra sayı sıfatı ise kullanılır.(10. oldum.)\n-Gün, ay, yıl tarih yazımında kullanılır.(15.01.2022)\n-Sayıların basamaklarını ayırmada kullanılır.(1.234.567)"),
      InfoCardItem("turkce_info_19","Nokta-2", "-Saat bildirirken kullanılır.(19.03)\n-Maddelendirmede sayı yada harflerden sonra kullanılır.(A.Nokta, B.Virgül, 1.Bölüm)\n-Künye sonlarında kullanılır.(Falanca Yayınevi, İzmir, 2022.)"),
      InfoCardItem("turkce_info_20","Virgül", "-Sıralı cümlelere konur.(Ali geldi, Mehmet de gelir.)\n-Ara cümleleri ayırmada kullanılır.(Hakem, eski öğretmendir, yanlış kararlar verdi.)\n-Ondalık sayılarda kullanılır.(5,8)\n-Yer ve tarih ayırmada kullanılır.(Adıyaman, 12 Kasım 2021)\n-Hitaptan sonra kullanılır.(Çocuklar, haydi sınıfa)\n-Resmi hitaplarda kullanılır.(Sayın Vali,)"),
      InfoCardItem("turkce_info_21","Virgül-2", "-Vurgu gerektiren sözden sonra kullanılır.(Ahmet başardı, Esra da başaracaktır.)\n-Cümledeki şart ifadesini ayırmada kullanılır.(Mesaj atarsa, söylerim.)\n-Bir durumu kabul etmek yada reddetmek için kullanılır.(Evet, söyledim. Hayır, gitmedim.)"),
      InfoCardItem("turkce_info_22","Noktalı Virgül", "-Çünkü, ama, yine de, fakat gibi kelimeler kullanılmazsa noktalı virgül eklenir.(Yazdım;okumadılar.)\n-Bu yüzden anlamı taşır.(Yalan söyledi;kızdım.)\n-Açıklama içeren cümlelerde çünkü, fakat ifadelerinden önce kullanılır.(Seni aradım; çünkü bilet bitmiş.)"),
      InfoCardItem("turkce_info_23","Noktalı Virgül-2", "-Örnek verirken farklı türden örneklere geçilirken kullanılır.(Akdeniz, karadeniz, ege; Antalya, Muğla)\n-Virgül içeren sıralı cümleleri ayırmak için kullanılır.(Heyecandan, coşkudan tüylerim diken diken oldu; zıplamak, oynamak istedim.)"),
      InfoCardItem("turkce_info_24","Üç Nokta", "-Anlatımı bitmemiş cümlelerin sonuna konur.(Bazen dersin ki...)\n-Açıkça belirtilmek istenmeyen ifadeler için kullanılır.(Bunu R... söyledi)\n-Alıntı öncesi ve sonrasında kullanılır.(...aslında burada olabilirdi...)\n-Okuyucunun hayal etmesi istenirse kullanılır.(Sözlerine devam etti ...)\n-Anlam pekiştirmede kullanılır.(Yürü...Yürü be!...)"),
      InfoCardItem("turkce_info_25","Soru İşareti", "-Soru cümlelerinde kullanılır.(Bizimle gelecek misin?)\n-Soru eki olmasa da soru bildiren cümlelerde kullanılır.(Yaşınız?)\n-Net olarak bilinmeyen tarihlerde kullanılır.(Doğum Tarihi 1678 ?)"),
      InfoCardItem("turkce_info_26","Ünlem İşareti", "-Kıvanç, şaşma, korku anlatan cümlelerin sonuna konur.(Nasıl yapmışlar böyle!)\n-Hitap ederken kullanılır.(Ey Türk Gençliği!)\n-Kinaye, alay anlamı taşır.(Gerçekten zekice(!) bir hareket)"),
      InfoCardItem("turkce_info_27","Kısa Çizgi", "-Kelime satıra sığmayıp alt satıra geçince kullanılır.\n-Ara cümleleri ayırmak için kullanılır.\n-Kelimeler ile kök, gövde ve heceleri ayırmak için kullanılır.(Ka-lem-lik)\n-Fillerin kök ve gövdelerini ayırmak için kullanılır.(ver-, al-)\n-ile, ıla, arasında ve den anlamı kazandırmak için kullanılır.(İstanbul-Ankara yolu)"),
      InfoCardItem("turkce_info_28","Kesme İşareti", "-Özel adlara gelen eklerde kullanılır.(Ahmet'in)\n-Kanun,tüzük veya yönetmelikten bahsedildiğinde kullanılır.(Bu Yönetmelik'in)\n-Kısaltmalara gelen eklerde kullanılır.(TMBB'nin)\n-Sayılara gelen eklerde kullanılır.(1985'te)"),
    ]),
    InfoCardModel("Ses Özellikleri", [
      InfoCardItem("turkce_info_29","Hece Düşmesi", "Boyun->Boyun-u->Boynu\nFikir->Fikir-i->Fikri\nAkıl->Akıl-ı->Aklı"),
      InfoCardItem("turkce_info_30","Büyük Ünlü Uyumu", "-Kelimenin ilk hecesinde kalın ünlü varsa(a,ı,o,u) diğer heceler kalın, ince ünlü varsa(e,i,ö,ü) diğer heceler de ince ünlü olur.(sanat, sözlük)\n-Birleşik kelimeler bitişik yazılıyorsa uyum aranmaz.(bilgisayar)\n-Aitlik eki olan ki uygun değildir.(soldaki)\n-Kelime yabancı ise büyük ünlü uyumu aranmaz. "),
      InfoCardItem("turkce_info_31","Küçük Ünlü Uyumu", "-Düz ünlüden(a,e,ı,i) sonra düz, yuvarlak ünlüden sonra yuvarlak dar(u,ü) veya düz geniş(a,e) ünlü gelmelidir.(Börekçi, çaycı)\n-Bu kurala uymayan bazı Türkçe kelimeler: havuç, çamur, kabuk vb.\n-"),
      InfoCardItem("turkce_info_32","Ünlü Daralması", "-a, e ile biten fiillerin şimdiki zaman çekiminde yazarken ve söylerken a ı'ya e i,ü'ye dönüşür.(başla-yor(başlıyor), izle-yor(izliyor))"),
      InfoCardItem("turkce_info_33","Ünsüz Türemesi", "His->Hissi\n Af -> Affetmek\n Zan->Zannetmek"),
      InfoCardItem("turkce_info_34","Ünlü Düşmesi", "-İki heceli bazı kelimeler ünlü ile başlayan ek alırsa ikinci hecelerindeki dar ünlüler düşer.(burun->burnu, oğul->oğlu\n-İleri, aşağı, yukarı gibi bazı kelimeler ek aldıklarında ünlü düşmesi olmaz. (ileri->ileride, aşağı->aşağıda, yukarı->yukarıda)"),
      InfoCardItem("turkce_info_35","Ses Değişikliği", "-Kelimede yer alan sesli harfin değişmesine denir.(ben-e bana, sen-e sana)\n-Bazı kelimelerde n b harfi yanyana gelince n harfi m harfine dönüşür. (menba->memba, tanbur->tambur)"),
      InfoCardItem("turkce_info_36","Sert Sessizlerin Benzeşmesi", "büyük-ce-> büyükçe\nat-gı->atkı\nyurt-dan->yurttan\nçalış-gan->çalışkan\nbeş-de->beşte"),
      InfoCardItem("turkce_info_37","Sert Sessizlerin Yumuşaması", "bayrak-ı->bayrağı\nsağlık-ı->sağlığı\nkap-ı->kabın\ngeçit-in->geçidin"),
    ]),
    InfoCardModel("Kelimede Anlam-1", [
      InfoCardItem("turkce_info_38","1-Anlam Birimi Olarak", "-Düz Anlam\n-Yan Anlam\n-Terim Anlam\n-Mecaz Anlam"),
      InfoCardItem("turkce_info_39","Düz Anlam", "-İlk anlamdır.\n-Mantıksaldır, nesnel olarak ifade edilir ve değişmez.(Örn: Elma: meyve)\n-Kelime cümleden çıkarılınca anlam değişmezse dün anlamlı kelimedir."),
      InfoCardItem("turkce_info_40","Yan Anlam", "-Kelimenin cümle içinde kazandığı öznel anlamdır.\n-Göz denildiğinde organ akla gelir. Bu temel anlamdır.\n-Masanın gözü denildiğinde ise masaya ait bölme anlaşılır ve göz ifadesi yan anlamı ile kullanılmış olur."),
      InfoCardItem("turkce_info_41","Terim Anlam", "-Bilimsel, sanatsal veya bir meslek grubuna ait ifade gücü olan kelimelerdir.\n-Örn: Üçgenin iç açılar toplamı 180 derecedir.\n-Bu cümlede matematik alanına ait terimsel ifadeler kullanılmıştır."),
      InfoCardItem("turkce_info_42","Mecaz Anlam", "-Kelime kendi anlamından çıkar ve başka bir anlam kazanır.\n-Örn: Sözlerin beni kırdı.\n-Bu cümlede kırmak sözcüğü mecaz anlamda kullanılmıştır."),
      InfoCardItem("turkce_info_43","2-Anlam İlişkilerine Göre", "-Eş Anlamlı Kelimeler\n-Yakın Anlamlı Kelimeler\n-Eş Sesli Kelimeler\n-Zıt Anlamlı Kelimeler"),
      InfoCardItem("turkce_info_44","Eş Anlamlı Kelimeler", "-Anlam olarak aynı karşılığa sahip farklı kelimeler eş anlamlıdır.\n-Örn: Numune ve örnek eş anlamlı kelimelerdir."),
      InfoCardItem("turkce_info_45","Yakın Anlamlı Kelimeler", "-Birbirine anlam bakımından çok yakın olsalar da birbirlerinin yerine kullanılamazlar.\n-Örn: Dost ve arkadaş kelimeleri yakın anlamlıdır."),
      InfoCardItem("turkce_info_46","Eş Sesli Kelimeler", "-Sesler aynı anlamlar farklıdır.\n-Örn: Bana güldü.\n-Elimde gördüğün güldü."),
      InfoCardItem("turkce_info_47","Zıt Anlamlı Kelimeler", "-Birbirinin tersi anlamları taşırlar.\n-Acı ve tatlı biber getirdi."),

    ]),
    InfoCardModel("Kelimede Anlam-2", [
      InfoCardItem("turkce_info_48","3-Kelimelerde Anlam Değişimleri", "-Anlamın Genişlemesi\n-Anlam Daralması\n-Çok Anlamlılık"),
      InfoCardItem("turkce_info_49","Anlamın Genişlemesi", "Kelimelerin kendi anlamları dışında yeni anlamlar kazanmasıdır.\n-Örn: Kol kelimesi organ iken zamanla bölüm anlamında da kullanılmaya başlanmıştır. "),
      InfoCardItem("turkce_info_50","Anlam Daralması", "-Anlamın zamanla daralmasıdır.\n-Örn: Yemiş eskiden meyve anlamında kullanılırken şimdi incir olarak kullanılır."),
      InfoCardItem("turkce_info_51","Çok Anlamlı Genişlemesi", "Sözcüğün birden fazla anlama sahip olmasıdır.\n-Örn: Soğuk su, soğuk espiri, aramız soğuk"),
      InfoCardItem("turkce_info_52","4-Kelime Grupları", "-Deyimler\n-İkilemeler\n-Yansımalar\n-İsim Tamlamaları\n-Sıfat Tamlamaları\n-Edatlarla ve Bağlaçlarla Oluşturulan Kelimeler\n-Ünlem grupları\n-Ünvan Grupları"),
      InfoCardItem("turkce_info_53","Deyimler", "-Anlatıma çekicilik katan ifadelerdir.\n-Dilimiz deyim bakımından çok zengindir.\n-Örn: Burun kıvırmak, ağız aramak, fikir yürütmek, kesenin ağzını açmak"),
      InfoCardItem("turkce_info_54","İkilemeler", "-Anlamın güçlenmesi için sözcüğün tekrarlanmasıdır.\n-Örn: Tatlı tatlı, güzel güzel, yavaş yavaş"),
      InfoCardItem("turkce_info_55","Yansımalar", "-Doğal seslerin anlamı ifade etmek için kullanılmasıdır.\n-Örn: Sular şırıl şırıl akıyor, kedi miyavlıyor, Mehmet horluyor."),
      InfoCardItem("turkce_info_56","İsim Tamlamaları-1", "BELİRTİLİ İSİM TAMLAMASI\n-Tamlayan ve tamlanan ek alır.\n-Örn: bölümÜN sonU\n\nBELİRTİSİZ İSİM TAMLAMASI\n-Yalnız tamlanan ek alır.\n-Örn: bölüm sonU"),
      InfoCardItem("turkce_info_57","İsim Tamlamaları-2", "TAKISIZ İSİM TAMLAMASI\n-Tamlayan ve tamlanan ek almaz. Sıfat tamlamasıyla karıştırmamak için tamlayanın isim olduğuna dikkat edilmelidir.\n-Örn: Demir Kapı(Takısız isim tamlamasıdır)\n-Örn: Siyah kapı(sıfat tamlamasıdır)"),
      InfoCardItem("turkce_info_58","İsim Tamlamaları-3", "ZİNCİRLEME İSİM TAMLAMASI\n-Birden fazla tamlamanın birleşmesidir.\n-Örn: Ali'nin kaleminin ucu\nÖrnekte Ali'nin kalemi ve kaleminin ucu isim tamlamasıdır.\n-Belirtili veya belirtisiz isim tamlaması olabilir.\n-Örn: Ney sesinin nağmesi, Neyin sesinin nağmesi"),
      InfoCardItem("turkce_info_59","Sıfat Tamlamaları", "-İsmi niteleyen sıfattır.\n-Örn: Güzel kalem, soğuk şehir.\n-İsmi birden fazla sıfat niteleyebilir.\n-Örn: Nazik, temiz ve tatlı bir çocuk"),
      InfoCardItem("turkce_info_60","Edatlarla ve Bağlaçlarla Oluşturlan Kelimeler", "EDAT\n-Örn: Senin gibi, pire kadar\nBAĞLAÇ\n-Örn: Hem kel Hem fodul, ne ev ne araba, ya Ali ya Osman, ha ben ha o"),
      InfoCardItem("turkce_info_61","Ünlem  Grupları", "ÖRNEKLER\n-Ay, elim\n-Ey Allah'ım\n-Ha şöyle\n-Hele şükür\n-Vay arkadaş\n-Ya Allah"),
      InfoCardItem("turkce_info_62","Ünvan Grupları", "İsim ile ünvanın birleşmesidir. Önemli nokta ek almamalarıdır.\n-Mehmet Öğretmen, Osman Paşa"),
    ]),
    InfoCardModel("Cümlede Anlam-1", [
      InfoCardItem("turkce_info_63","Cümlede Anlam","A-Anlatımına Göre Cümleler\nB-Cümlede Anlam İlişkileri\nC-Cümle Yorumlama\nD-Anlamlarına Göre Cümleler",),
      InfoCardItem("turkce_info_64","A-Anlatımına Göre Cümleler","ÖZNEL ANLATIMLI CÜMLELER\n-Doğruluğu kişiden kişiye değişir. Öznel anlatım içerir\n-Örn: Tepsi kebabı tam bir lezzet şölenidir.",),
      InfoCardItem("turkce_info_65","A-Anlatımına Göre Cümleler","NESNEL ANLATIMLI CÜMLELER\n-Herkes tarafından kabul edilecek yargı içeren cümlelerdir.\n-Örn: Türkiye'nin başkenti Ankara'dır.",),
      InfoCardItem("turkce_info_66","A-Anlatımına Göre Cümleler","İÇERİK CÜMLELERİ\n-Eserlerde işlenen konulara dikkat çekilen cümlelerdir.\n-Örn: Yazar, Mehmet'in memleket sevgisinden bahsetmiş.",),
      InfoCardItem("turkce_info_67","A-Anlatımına Göre Cümleler","TANIM CÜMLELERİ\n-Nedir, kimdir sorularının cevabını veren cümlelerdir.\n-Örn: Bireylerin bir alandaki bilgi ve becerilerini ölçmek için yapılan yoklamaya sınav denir.",),
      InfoCardItem("turkce_info_68","A-Anlatımına Göre Cümleler","ÜSLUP CÜMLELERi\n-Bir konunun, duygunun anlatılmasında seçilen yönteme üslup denir. Nasıl sorusunun cevabını verir.\n-Örn: Konularını sade cümlelerle ele alıyor.",),
      InfoCardItem("turkce_info_69","A-Anlatımına Göre Cümleler","DOĞRUDAN ANLATIMLI CÜMLELER\n-Bir kişi tarafından söylenen sözün yorum katılmadan aktarıldığı cümlelere denir.\n-Örn: Atalarımız, ağaç yaş iken eğilir, demişler.",),
      InfoCardItem("turkce_info_70","A-Anlatımına Göre Cümleler","DOLAYLI ANLATIMLI CÜMLELER\n-Başkasına ait olan düşünce ya da sözü kişinin kendi cümleleriyle ifade etmesidir.\n-Örn: Öğretmen derslerine önem vermesi gerektiğini söyledi.",),
      InfoCardItem("turkce_info_71","A-Anlatımına Göre Cümleler","KİNAYELİ ANLATIMLI CÜMLELER\n-Alaycı ifade içerir. Bazı durumlarda anlatılmak istenenin tam tersi söylenerek ifade edilir.\n-Örn: Bu atağı da gol yiyerek savuşturduk.",),
      InfoCardItem("turkce_info_72","A-Anlatımına Göre Cümleler","AŞAMALI DURUM BİLDİREN CÜMLELER\n-Bir durumun süreç içinde değiştiğini ifade eden cümlelerdir.\n-Örn: Gün geçtikçe hayallerimi gerçekleştiriyorum.",),
    ]),

    InfoCardModel("Cümlede Anlam-2", [
      InfoCardItem("turkce_info_73","B-Cümlede Anlam İlişkileri","EŞ ANLAMLI CÜMLELER\n-Aynı düşünceyi farklı cümlelerle aktarmaktır.\n-Örn: Tabağın yarısı dolu\n-Tabağın yarısı boş",),
      InfoCardItem("turkce_info_74","B-Cümlede Anlam İlişkileri","ZIT ANLAMLI CÜMLELER\n-Birbirinin karşıtı cümleler içerir.\n-Örn: Film çok eğlenceliydi\n-Film çok sıkıcıydı",),
      InfoCardItem("turkce_info_75","B-Cümlede Anlam İlişkileri","YAKIN ANLAMLI CÜMLELER\n-Aynı düşünceyi, aynı özü taşıyan cümlelerdir.\n-Örn: Yaşlandıkça daha güzel konuşmaya başladı\n-Olgunlaştıkça daha güzel konuşmaya başladı.",),
      InfoCardItem("turkce_info_76","B-Cümlede Anlam İlişkileri","AMAÇ-SONUÇ İLİŞKİLİ CÜMLELER\n-Eylemin gerçekleşme amacını içeren cümlelerdir.\n-Örn: Doktor akciğerlerinin gelişmesi için ney üflemesini söyledi.",),
      InfoCardItem("turkce_info_77","B-Cümlede Anlam İlişkileri","NEDEN-SONUÇ İLİŞKİLİ CÜMLELER\n-Neden ve niçin sorularının cevabını içeren cümlelerdir.\n-Örn: Ayağım ağrıdığı için maça çıkmadım.",),
      InfoCardItem("turkce_info_78","B-Cümlede Anlam İlişkileri","KOŞUL-SONUÇ İLİŞKİLİ CÜMLELER\n-Bir durumun gerçekleşmesi için başka bir durumun gerçekleşmesi gerektiğini bildiren cümlelerdir.\n-Örn: Ödevlerini bitirdiğinde birlikte gezintiye çıkabiliriz.",),
      InfoCardItem("turkce_info_79","B-Cümlede Anlam İlişkileri","AÇIKLAMA İLİŞKİLİ CÜMLELER\n-Önce sonuç sonra neden bildirilir.\n-Örn: Gelmeyeceğini söyledi, çünkü çok yorgunmuş.",),
      InfoCardItem("turkce_info_80","B-Cümlede Anlam İlişkileri","KARŞILAŞTIRMA CÜMLELERİ\n-Birden fazla olay ya da durumun birbiriyle kıyaslanmasını içerir.\n-Örn: Yaz aylarında Trabzon'a düşen yağış miktarı Denizli'den daha fazladır.",),
    ]), InfoCardModel("Cümlede Anlam-3", [
      InfoCardItem("turkce_info_81","C-Cümle Yorumlama","1-Cümlenin Konusu\n2-Cümlenin Ana Fikri\n3-Cümleden Çıkabilecek Yargı\n4-Cümleden Çıkamayacak Yargı\n5-Cümle Oluşturma\n6-Cümle Tamamlama",),
      InfoCardItem("turkce_info_82","C-Cümle Yorumlama","CÜMLENİN KONUSU\n-Cümlenin kapsadığı anlamdır.\n-Örn: Müzik ruhun gıdasıdır.(Müzik gıdaya benzetilerek ruha olumlu katkıda bulunduğu belirtilmiştir.)",),
      InfoCardItem("turkce_info_83","C-Cümle Yorumlama","CÜMLENİN ANA FİKRİ\n-Cümlede asıl anlatılmak istenen anafikirdir.\n-Sorularda bir metin verilir ve anafikri sorulur. ",),
      InfoCardItem("turkce_info_84","C-Cümle Yorumlama","CÜMLEDEN ÇIKABİLECEK/ÇIKAMAYACAK YARGI\n-Metin verilerek cümleden çıkarılabilecek ya da çıkarılamayacak yargı sorulur.",),
      InfoCardItem("turkce_info_85","C-Cümle Yorumlama","CÜMLE OLUŞTURMA VE TAMAMLAMA\n-Oluşturma cümlesi sorularında kelimeler maddeler halinde verilerek doğru sıralama ile anlamlı bir cümle oluşturulması istenir.\n-Tamamlamada ise cümlenin çoğunluğu verilir eksik bırakılan bölümün nasıl doldurulabileceği sorulur.",),
    ]), InfoCardModel("Cümlede Anlam-4", [
      InfoCardItem("turkce_info_86","D-ANLAMLARINA GÖRE CÜMLELER","ÖNERİ CÜMLELERİ\n-Kazanmak için çalışmalısın.",),
      InfoCardItem("turkce_info_87","D-ANLAMLARINA GÖRE CÜMLELER","ELEŞTİRİ CÜMLELERİ\n-Çok fazla ayrıntıya takılıyorsun.",),
      InfoCardItem("turkce_info_88","D-ANLAMLARINA GÖRE CÜMLELER","DAVRANIŞ CÜMLELERİ\n-İçeri girdiğimde beni dikkatlice süzdü.",),
      InfoCardItem("turkce_info_89","D-ANLAMLARINA GÖRE CÜMLELER","VARSAYIM CÜMLELERİ\n-Sınava geç kaldığını düşünelim.",),
      InfoCardItem("turkce_info_90","D-ANLAMLARINA GÖRE CÜMLELER","ÖNYARGI CÜMLELERİ\n-Bu uygulama sınavı kazanmamı sağlayacak.",),
      InfoCardItem("turkce_info_91","D-ANLAMLARINA GÖRE CÜMLELER","ÖZELEŞTİRİ CÜMLELERİ\n-Daha dikkatli davranmam gerektiğinin farkındayım.",),
      InfoCardItem("turkce_info_92","D-ANLAMLARINA GÖRE CÜMLELER","GÖRÜŞ CÜMLELERİ\n-Müzik ruha şifadır.",),
      InfoCardItem("turkce_info_93","D-ANLAMLARINA GÖRE CÜMLELER","UYARI CÜMLELERİ\n-Araç kullanırken emniyet kemerini mutlaka takın.",),
      InfoCardItem("turkce_info_94","D-ANLAMLARINA GÖRE CÜMLELER","YAKINMA CÜMLELERİ\n-Ne zaman çağırsam meşgul olduğunu söylüyor.",),
      InfoCardItem("turkce_info_95","D-ANLAMLARINA GÖRE CÜMLELER","ŞAŞIRMA CÜMLELERİ\n-Bu kadar zor sınavı nasıl kazanmış hayret ediyorum.",),
      InfoCardItem("turkce_info_96","D-ANLAMLARINA GÖRE CÜMLELER","ÇARESİZLİK CÜMLELERİ\n-Artık söyleyecek birşey bulamıyorum.",),
      InfoCardItem("turkce_info_97","D-ANLAMLARINA GÖRE CÜMLELER","ABARTMA CÜMLELERİ\n-Ege şivesi taklidi bizi gülmekten öldürdü.",),
      InfoCardItem("turkce_info_98","D-ANLAMLARINA GÖRE CÜMLELER","SİTEM CÜMLELERİ\n-Tabi biz kimiz de bize getireceksin.",),
    ]),
    InfoCardModel("Cümle Bilgisi-1", [
      InfoCardItem("turkce_info_99","Cümlenin Öğeleri-1","YÜKLEM\n-Cümlenin asıl unsurudur.\n-Yüklem ekfiil ile ya da fiil çekimi ile oluşabilir.\n-Tek kelime olabileceği gibi kelime grubundan da oluşabilir.\n-Örn: Ben GELİYORUM\n-Örn: Masadaki ARKADAŞIMIN GÖZLÜĞÜDÜR(kelime grubu)",),
      InfoCardItem("turkce_info_101","Cümlenin Öğeleri-2","ÖZNE\n-Yüklem ile cümlenin asıl unsurlarındandır.\n-Fiilden ayrılamaz.\n-Kelime grupları özne olarak bulunabilir.\n-Örn: ALİ balık tutuyor\n-AYDIN'IN OĞLU ALİ balık tutuyor.(Özne kelime grubu)\n-Bazı fiil cümlelerinde özne fiildeki kişi ekinden anlaşılabildiği için özne bulunmaz.\n-Örn: Geç kalacaksınız.)",),
      InfoCardItem("turkce_info_102","Cümlenin Öğeleri-3","NESNE\n-Nesnenin görevi yüklemi tamamlamaktır.\n-Kelimede belirtme hal eki varsa nesne görevindedir.(-ı,-i,-u,-ü)\n-Belirtili nesneyi bulmak için neyi, kimi soruları, belirtisiz nesneyi bulmak için ne sorusu sorulur.\n-Örn: Öğretmenin BİLGİSİ yeni nesilleri aydınlatacaktır.(Belirtili Nesne)\n-Örn: Öğrenciden KALEM aldım.(Belirtisiz Nesne)",),
      InfoCardItem("turkce_info_103","Cümlenin Öğeleri-4","DOLAYLI TÜMLEÇ\n-Yer tamamlayıcısı olarak geçer.\n-a,-e,-da,-de-ta,-te,-dan,-den,-tan,-ten eklerini alır.\n-Neye, nerede, nereden, kime, kimde, kimden soruları sorulur.\n-Örn: Yazının onayı VALİDEN geldi.(nereden geldi? VALİDEN)",),
      InfoCardItem("turkce_info_104","Cümlenin Öğeleri-5","ZARF TÜMLECİ\n-Cümlede zamanı, miktarı, durumu, soruyu tamamlar.\n-Zarf tümlecini bulmak için nasıl, ne zaman, niçin, ne kadar gibi sorular sorulur.\n-Örn: Öğretmen derse 11.00'da geldi.(ne zaman geldi? 11.00'da)",),
      InfoCardItem("turkce_info_105","Cümlenin Öğeleri-6","CÜMLE DIŞI ÖĞE\n-Cümle anlamına yardımcı edatlardır.\n-Cümle öğelerine ayrılırken dikkate alınmazlar.\n-Örn: AYRICA bunu birlikte başarabiliriz.",),
      ]),
    InfoCardModel("Cümle Bilgisi-2", [
      InfoCardItem("turkce_info_106","Cümle Çeşitleri","A-Yüklemine Göre Cümle Çeşitleri\nB-Yükleminin Cinsine Göre Cümle Çeşitleri\nC-Anlamlarına Göre Cümle Çeşitleri\nD-Kuruluşuna Göre Cümle Çeşitleri\n",),
      InfoCardItem("turkce_info_107","A-Yüklemine Göre Cümle Çeşitleri-1","KURALLI CÜMLE\n-Yüklem sondadır.\n-Örn:Ahmet iyi düzeyde ud çalıyordu.(Yüklem= çalıyordu)",),
      InfoCardItem("turkce_info_108","A-Yüklemine Göre Cümle Çeşitleri-2","KURALSIZ(DEVRİK) CÜMLE\n-Yüklemi sonda olmayan cümlelerdir.\n-Örn: Gördüklerimdi beni asıl mutlu eden.(Yüklem başta)",),
      InfoCardItem("turkce_info_109","B-Yükleminin Cinsine Göre Cümle Çeşitleri-1","FİİL CÜMLESİ\n-Yüklemi fiil olan cümlelerdir.\n-Örn: Okuldaki öğrencilerin başarısı bizi çok mutlu etti.(etmek fiili cümlenin yüklemidir.)",),
      InfoCardItem("turkce_info_110","B-Yükleminin Cinsine Göre Cümle Çeşitleri-2","İSİM CÜMLESİ\n-Yüklemi isim ya da isim soylu bir kelime olan cümlelerdir.\n-Örn: Arkadaşlarımla gezmek çok güzel.",),
      InfoCardItem("turkce_info_111","C-Anlamlarına Göre Cümle Çeşitleri-1","SORU CÜMLESİ\n-Cümlede soru ifadesi vardır ve cevap gerektirir.\n-Örn: Tanışıyor musunuz?\n-Genellikle -mi, -mı, -mu,- mü gibi soru ekleri alırlar.\n-Örn: Harun gelecek mi?",),
      InfoCardItem("turkce_info_112","C-Anlamlarına Göre Cümle Çeşitleri-2","OLUMLU CÜMLE\n-Cümle olumlu anlam ifade eder.\n-Örn: Devamsızlıkların tamamını sisteme işledim.",),
      InfoCardItem("turkce_info_113","C-Anlamlarına Göre Cümle Çeşitleri-3","OLUMSUZ CÜMLE\n-Cümle olumsuz anlam ifade eder.\n-Örn: Devamsızlıkların tamamını sisteme işlemedim.",),
      InfoCardItem("turkce_info_114","D-Kuruluşuna Göre Cümle Çeşitleri-1","BASİT CÜMLE\n-Tek yüklem, tek eylem ve tek hüküm bulunan cümlelerdir.\n-Örn: Arkadaşım yanıma geldi.",),
      InfoCardItem("turkce_info_115","D-Kuruluşuna Göre Cümle Çeşitleri-2","BİRLEŞİK CÜMLE\n-İçersinde birden fazla yargı bulunduran cümlelerdir.\n-4 grupta ele alınırlar. Bunlar;\n-İç içe birleşik cümle\n-Şartlı birleşik cümle\n-Ara cümleli birleşik cümle\n-Ki'li birleşik cümle",),
      InfoCardItem("turkce_info_116","D-Kuruluşuna Göre Cümle Çeşitleri-3","İÇ İÇE BİRLEŞİK CÜMLE\n-Cümle içinde cümle vardır.\n-Temel cümleyi destekleyen ve anlamı pekiştiren yapıdadır\n-Örn: Uzaklara doğru bakarak, keşke daha uzun kalabilseydin, dedi.",),
      InfoCardItem("turkce_info_117","D-Kuruluşuna Göre Cümle Çeşitleri-4","ŞARTLI BİRLEŞİK CÜMLE\n-Şarta bağlı cümle kurulur.\n-Önce şart sonra temel cümle yer alır\n-Örn: Ödevlerini yaparsan kır gezisine gidebiliriz.",),
      InfoCardItem("turkce_info_118","D-Kuruluşuna Göre Cümle Çeşitleri-5","ARA CÜMLELİ BİRLEŞİK CÜMLE\n-Cümleden çıkarıldığında anlamı değiştirmeyen birleşik cümlelerdir.\n-Örn: Seninle ilk buluşmamaızda, üzerinde mavi gömlek vardı, tanıştığımız kişileri gördüm.",),
      InfoCardItem("turkce_info_119","D-Kuruluşuna Göre Cümle Çeşitleri-6","Kİ'Lİ BİRLEŞİK CÜMLE\n-Ki edatı ortada bulunur, başta temel cümle sonda yardımcı cümle yer alır.\n-Farzet ki kaybettim sana olan güvenimi, hala sana abim diyebilir miyim?",),
    ]),
    InfoCardModel("Yapım Ekleri", [
      InfoCardItem("turkce_info_120","Tanım","4 Grupta incelenir. Bunlar;\nA-İsimden İsim yapma\nB-İsimden fiil yapma\nC-Fiilden fiil yapma\nD-Fiilden isim yapma ekleridir.",),
      InfoCardItem("turkce_info_121","İsimden İsim Yapma","-İsime gelen ek yeni isim türetir.\n-Örn:Kulak-lık, yazılım-cı, yurt-taş, av-lak, beraber-lik, bel-li baş-lı, kimse-siz, badem-cik vb.",),
      InfoCardItem("turkce_info_122","İsimden Fiil Yapma","-İsme gelen ek fiil türetir.\n-Örn: kısa-l, baş-ar, üf-le, ateş-le, yön-el, doğru-l, ütü-le vb.",),
      InfoCardItem("turkce_info_123","Fiilden Fiil Yapma","-Fiile gelen ek yeni fiil türetir.\n-Örn: bil-dir, çık-ar, sür-ün",),
      InfoCardItem("turkce_info_124","Fiilden İsim Yapma","Fiile gelen ek isim türetir.\n-beğen-i, üret-ici, sakın-ca, utan-gaç, kıskan-ç, çalış-kan, bil-gin, dile-k vb.",),
      InfoCardItem("turkce_info_125","Zarf Fiil Ekleri","-Fiile gelerek eylemin yapılma zamanını bildiren eklerdir.\n-Ekin geldiği fiile göre tarz görevi de alır\n-Örn: kazan-arak, sev-ince, gel-eli, Gül-e gül-e vb.",),
      InfoCardItem("turkce_info_126","Sıfat Fiil Ekleri","-Fiile gelerek sıfat oluşturur.\n-Örn: Yaşan-maz, geç-en, dön-er, kırıl-ası vb.",),
    ]),

    InfoCardModel("Çekim Ekleri", [
      InfoCardItem("turkce_info_127","Tanım","Aldığı ekler ile yeni türeyen kelimenin diğer kelimelerle ilişki kurmasını sağlayan eklerdir.\n-Yapım ekinde olduğu gibi kelimeye yeni anlam katmaz.\n-İsme gelen eklere İsim Çekim Ekleri, fiile gelen eklere Fiil Çekim Ekleri denir.",),
      InfoCardItem("turkce_info_128","İsim Çekim Ekleri","-İyelik Ekleri\n-Hal Ekleri\n-Çokluk Eki\n-Soru eki olmak üzere 4 çeşittir.",),
      InfoCardItem("turkce_info_129","İyelik Ekleri","-Diğer adı sahiplik ekleridir.\n-Kime ait olduğunu gösterir.\n-Örn: Bilgisayarı-n tamirde mi?, Kalem-i kaybolmuş, suyu-muzu doldurduk, Ödev-inizi vb.",),
      InfoCardItem("turkce_info_130","Hal Ekleri","-Durum ekleri de denir.\n-Cümlede ismin anlamını ve görevini belirler.\n-Yalın Hal, Belirtme Hali, Yaklaşma Hali, Bulunma Hali, İlgi Hali, ",),
      InfoCardItem("turkce_info_131","Yalın Hal","-Ek yoktur.\n-Örn: KÖPEK havlıyordu, Arkadaşıma hediye KİTAP aldım, İyi bir AYAKKABICI arıyorum vb.",),
      InfoCardItem("turkce_info_132","Belirtme Hali","-İsmin -i hali de denir.\n--ı, -i, -u, -ü eklerini alır.\n-Ek alan sözcük belirtili nesne olur.\n-Örn: ev-İ gezdirdi, tas-I tarağ-I toplayıp gitti, selam-I sabah-I kesti.",),
      InfoCardItem("turkce_info_133","Yaklaşma Hali","-İsmin -e, -a eki almasıyla oluşur.\n-Örn: ban-A, kalem-E, uyku-y-A.\n-Yaklaşma hali eki alan kelimeler yükleme sorulan neye, kime sorularının cevabı olarak cümlede dolaylı tümleç görevi görür.",),
      InfoCardItem("turkce_info_134","Bulunma Hali","-İsmin -de,-da,-te,-ta ekleri almasıyla oluşur.\n-Örn: gazete-DE yer alan bilgiye göre, Bu konu-DA yapılan açıklamada \n-Bulunma hali eki alan kelimeler yükleme sorulan nerede, kimde sorularına cevap olarak cümlede dolaylı tümleç görevi görür. ",),
      InfoCardItem("turkce_info_135","İlgi Hali","-İsmin -ın, -in, -un, -ün eki almasıyla oluşur.\n-Örn: alem-İN keyfi yerinde, soru-NUN altı çizili yeri çok önemlidir, kalem-İN ucu.",),
    ]),

    InfoCardModel("Fiil Çekim Ekleri-1", [
      InfoCardItem("turkce_info_136","Tanım","Fiiller daima çekim eki alırlar.\n2 çeşittir. Bunlar;\n-Kişi Ekleri\n-Kip Ekleri",),
      InfoCardItem("turkce_info_137","Kişi Ekleri","-Fiilde eylemi yapan kişiyi belirten eklerdir.\n-Örn: Bugün geleceğiM, bugün gelecekSİN, bugün gelecek, bugün geleceğİZ, bugün gelecekSİNİZ, bugün gelecekLER",),
      InfoCardItem("turkce_info_138","Kip Ekleri","-Biçim ve zaman bakımından fiil kökü ya da gövdesinin bildirdiği ekleri bağlar.\n-Örn: Oku-YOR, sev-MELİ, gör-ÜR",),
      InfoCardItem("turkce_info_139","Fiil Çekimi","-Fiiller her zaman çekimli halde bulunurlar.\n-Çekim eki almıyorsa 3.tekil kişiye karşılık geliyordur.\n-(O) Geldi.\n-Fiiller olumlu ya da olumsuz anlamlar içerebilir.\n-Örn: Geldim, gelMEdim. ",),
      InfoCardItem("turkce_info_140","Fiil Çekimi-2","2 tür Fiil Çekimi vardır. Bunlar;\n-Basit Fiil Çekimi\n-Birleşik Fiil Çekimi",),
      InfoCardItem("turkce_info_141","Basit Fiil Çekimi","Fiil kök yada gövdesine biçim/zaman eki eklenerek kişi ekine bağlanır.\n-Örn: GELDİM=> Gel(Fiil Kökü)+Dİ(zaman eki)+M(kişi eki)",),
      InfoCardItem("turkce_info_142","Haber Kipleri","Basit fiillerin haber kiplerine örnekler verelim.",),
      InfoCardItem("turkce_info_143","Görülen(Di'li) Geçmiş Zaman","-dı, -di, -du, dü ekleri gelir.\n-Örn: gör-DÜ-M, gör-DÜ-n, gör-DÜ, gör-DÜ-k, gör-DÜ,nüz, gör-DÜ-ler",),
      InfoCardItem("turkce_info_144","Öğrenilen(MİŞ'li) Geçmiş Zaman","-mış, -miş, -muş, -müş ekleri gelir.\n-Örn: gel-MİŞ-im, gel-MİŞ-sin, gel-MİŞ, gel-MİŞ-iz, gel-MİŞ-siniz, gel-MİŞ-ler",),
      InfoCardItem("turkce_info_145","Şimdiki Zaman","-yor, -mekte, -makta, -mada, -mede ekleri gelir.\n-Örn: soru-YOR-um, soru-YOR-sun, soru-YOR, soru-YOR-uz, soru-YOR-sunuz, soru-YOR-lar",),
      InfoCardItem("turkce_info_146","Geniş Zaman","-r, -ar, -er ekleri gelir.\n-Örn: uç-AR-ım, uç-AR-sın, uç-AR, uç-AR-ız, uç-AR-sınız, uç-AR-lar",),
      InfoCardItem("turkce_info_147","Gelecek Zaman","-ecek, -acak ekleri gelir.\n-Örn: gör-ECEK(ğ)-im, gör-ECEK-sin, gör-ECEK, gör-ECEK(ğ)-iz, gör-ECEK-siniz, gör-ECEK-ler",),
      InfoCardItem("turkce_info_148","Dilek Kipleri","4 çeşittir\n-Dilek-Şart Kipi\n-İstek Kipi\n-Gereklilik Kipi\n-Emir Kipi",),
      InfoCardItem("turkce_info_149","Dilek Şart Kipi","-se, -sa eki alır.\n-Eylemin dilek ya da şarta bağlı olduğu bildirilir.\n-Örn: Okulu bitir-SE-m İstanbul'a gideceğim.",),
      InfoCardItem("turkce_info_150","İstek Kipi","-a, -e eki alır.\n-Örn: Ben de sizinle gel-E-yim.",),
      InfoCardItem("turkce_info_151","Gereklilik Kipi","-malı, meli eki alır.\n-Örn: Sınavı kazanmak için mutlaka çalış-MALI-yım.",),
    ]),
    InfoCardModel("Fiil Çekimleri-2", [
      InfoCardItem("turkce_info_152","Ek Fiil Eki","-Aldığı ek ile isimleri yüklem yapar.\n-Fiilleri birleşik zamanlı hale getirir.\n\n-Dört farklı zamana göre çekimi vardır.",),
      InfoCardItem("turkce_info_153","Ek Fiilin Geniş Zamanı","-ım, -im, -um, -üm, -dır, -dir, -dur, -dür eklerinden birini alır.\n-Örn: adam-IM, adam-SIN, adam-(dır), adam-IZ, adam-SINIZ, adam-(DIR)LAR\n-Olumsuz anlam kazandırmak için 'yok', 'değil' kelimeleri kullanılır.",),
      InfoCardItem("turkce_info_154","Ek Fiilin Görülen Geçmiş Zamanı","-idi eki alır.\n-Örn: adam-DIM, adam-DIN, adam-(DI), adam-DIK, adam-DINIZ, adam-DILAR",),
      InfoCardItem("turkce_info_155","Ek Fiilin Duyulan Geçmiş Zamanı","-imiş eki alır.\n-Örn: adam-MIŞIM, adam-MIŞSIN, adam-MIŞ, adam-MIŞIZ, adam-MIŞSINIZ, adam-MIŞLAR",),
      InfoCardItem("turkce_info_156","Ek Fiilin Şart Kipi","-ise eki alır.\n-Örn: adam-SAM, adam-SAN, adam-SA, adam-SAK, adam-SANIZ, adam-SALAR",),
      InfoCardItem("turkce_info_157","Olumsuz Anlamı Katmak","-Ek fiilin zaman eklerinde olumsuz anlam katmak için değil kelimesi kullanılır.\n-Örn: adam değil-İM, adam değil-DİM, adam değil-MİŞİM, adam değil-SEK",),
      InfoCardItem("turkce_info_158","Soru Eki","-Soru anlamı katmak için -mı, -mi, -mu, -mü ekleri gelir.\n-Örn: adam mıyım?, adam mıydık?, adam mıymışız?",),
    ]),
    InfoCardModel("Anlatım Bozuklukları-1", [
      InfoCardItem("turkce_info_159","Tanım","-Düşüncenin ifade edilirken anlaşılır, açık ve yalın olarak aktarılamamasına ve dil kurallarına uyulmamasına anlatım bozukluğu denir.",),
      InfoCardItem("turkce_info_160","Tanım-2","İyi bir cümle açık, anlaşılır, mantık ve dilbilgisi bakımından doğru olmalıdır. Anlatım Bozuklukları anlamsal ve yapısal olabilir.",),
      InfoCardItem("turkce_info_161","Yapısal Bozukluklar","-Özne-yüklem uyumsuzluğu\n-Yüklem Eksikliği\n-Özne Eksikliği\n-Eklerle ilgili hatalar\n-Tamlama hataları\n-Bağlaç hataları",),
      InfoCardItem("turkce_info_162","Anlamsal Bozukluklar","-Sözcüklerin yanlış kullanımı\n-Anlamca çelişen sözcük kullanımı\n-Gereksiz sözcük kullanımı\n-Sözcüğün yanlış kullanımı\n-Anlam belirsizliği\n-Mantık hatası\n-Deyimin yanlış anlamda kullanılması",),
    ]),
    InfoCardModel("Anlatım Bozuklukları (YAPISAL)", [
      InfoCardItem("turkce_info_163","Yapısal Bozukluklar","-Özne-yüklem uyumsuzluğu\n-Yüklem Eksikliği\n-Öge Eksikliği\n-Eklerle ilgili hatalar\n-Tamlama hataları\n-Bağlaç hataları",),
      InfoCardItem("turkce_info_164","Özne Yüklem Uyumsuzluğu-1","ÖZNE EKSİKLİĞİ\n-Yüklemdeki eylemi karşılayan özne olmaması durumudur.\n-Örn: Ahmet'in ödevi eksikti, eksiyi hakediyordu.(Kime eksi verdi?)\n-Doğru cümle: Ahmet'in ödevi eksikti, AHMET eksiyi hakediyordu.",),
      InfoCardItem("turkce_info_165","Özne Yüklem Uyumsuzluğu-2","KİŞİ BAKIMINDAN UYUMSUZLUK\n-Özne ile yüklemin kişi bakımından uyumsuz olmasıdır.Örn: Ben ve Ali Ankara'ya gideceğim.\n-Doğru Cümle: Ben ve Ali Ankara'ya gideceğİZ.",),
      InfoCardItem("turkce_info_166","Özne Yüklem Uyumsuzluğu-3","TEKİLLİK ÇOĞULLUK BAKIMINDAN UYUMSUZLUK\n-Özne çoğul/tekil iken yüklemin tekil/çoğul olmasıdır.\n-Örn: Ördekler v şeklinde uçuyor.\n-Doğru Cümle: Ördekler v şeklinde uçuyorLAR.",),
      InfoCardItem("turkce_info_167","Yüklem Eksikliği","-Özneyi karşılayan yüklem bulunmamasıdır. Genel olarak bağlı cümlelerde görülür.\n-Örn: Daha önce de şimdi de umudumu kaybetmiyorum.\n-Doğru Cümle: Daha önce de UMUDUMU KAYBETMEDİM, şimdi de umudumu kaybetmiyorum.",),
      InfoCardItem("turkce_info_168","Öge Eksikliği","-Cümlede yer alması gereken ögenin bulunmamasıdır.\n-Örn: Sosyal medyadaki haberlere inanmıyorum, paylaşmıyorum.\n-Doğru Cümle: Sosyal medyadaki haberlere güvenmiyorum, HABERLERİ paylaşmıyorum",),
      InfoCardItem("turkce_info_169","Eklerle İlgili Hatalar","-Eklerin yanlış, eksik ve fazla kullanılması anlatım bozukluğuna sebep olur.\n-Örn: Araştırmasını bilmeyen öğrencilerimiz var.\n-Doğru Cümle: AraştırmaYI bilmeyen öğrencilerimiz var.",),
      InfoCardItem("turkce_info_170","Tamlama Hataları","-İsim ve sıfatların aynı tamlanan bağlanmasıyla oluşur.\n-Örn: Polis ve askeri araç gördüğümde cesaretlenirim.\n-Doğru Cümle: Polis ARACI ve askeri araç gördüğümde cesaretlenirim.",),
      InfoCardItem("turkce_info_171","Bağlaç Hataları","-Bağlaçların anlama uygun kullanılmaması ile oluşur.\n-Örn: Arkadaşlarını çok özlüyor fakat sürekli arıyordu.\n-Doğru Cümle: Arkadaşlarını çok seviyor AYRICA sürekli arıyordu.",),
    ]),
    InfoCardModel("Anlatım Bozuklukları (ANLAMSAL)", [
      InfoCardItem("turkce_info_172","Anlamsal Bozukluklar","-Sözcüğün yanlış yerde kullanımı\n-Anlamca çelişen sözcük kullanımı\n-Gereksiz sözcük kullanımı\n-Sözcüğün yanlış anlamda kullanımı\n-Anlam belirsizliği\n-Mantık hatası\n-Deyimin yanlış anlamda kullanılması",),
      InfoCardItem("turkce_info_173","Sözcüğün Yanlış Yerde Kullanımı","-Doğru yerde kullanılmayan sözcük anlam karmaşasına yol açar.\n-Örn: Yeni arabama binmiştim ki telefonum çaldı.\n-Doğru Cümle: Arabama YENİ binmiştim ki telefonum çaldı.",),
      InfoCardItem("turkce_info_174","Anlamca Çelişen Sözcük Kullanımı","-Cümleden çıkarılacak anlam karışıklığa yol açmamalıdır.\n-Örn: Kesinlikle bugün gelmiş olabilir.\n-Doğru Cümle: Kesinlikle bugün gelmişTİR.",),
      InfoCardItem("turkce_info_175","Gereksiz Sözcük Kullanımı","-Aynı anlama gelen sözcüklerin gereksiz şekilde kullanılmasıdır.\n-Örn: Aracın deposunu full doldurdum.\n-Doğru Cümle: Aracın deposunu DOLDURDUM.",),
      InfoCardItem("turkce_info_176","Sözcüğün Yanlış Anlamda Kullanımı","-Karşıladığı anlam itibariyle sözcüğün yanlış kullanılmasıdır.\n-Örn: Domates ücretleri artmış.\n-Doğru Cümle: Domates FİYATLARI artmış." ,),
      InfoCardItem("turkce_info_177","Anlam Belirsizliği","-Kişinin yerini tutan zamirin yanlış kullanılmasıyla oluşur.\n-Örn: Arkadaşını tanıyamadım.\n-Doğru Cümle: SENİN/ONUN/AHMET'İN arkadaşını tanıyamadım.(Kimin arkadaşı olduğu net bir şekilde ifade edilmelidir.)" ,),
      InfoCardItem("turkce_info_178","Mantık Hatası","-Mantıksal olarak cümlede hata bulunmasıdır.\n-Örn: Geleneksel 1. yaz kampımız başladı.\n-Doğru Cümle: 1.yaz kampımız başladı.(1. kez düzenlenen bir etkinlik geleneksel olamaz)" ,),
      InfoCardItem("turkce_info_179","Deyimin Yanlış Anlamda Kullanılması","-İfadeyi güçlendirmek için kullanılan deyimlerin belirtilmek istenen ifadeyi karşılamamsıdır.\n-Örn: Babası önerilerini kabul etmez, bir dediği iki olmazdı.\n-Doğru Cümle: Babası önerilerini kabul EDER, bir dediği iki olmazdı." ,),
      ]),
  ];

  //Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği
  InfoCardModel("Başlık", [
      InfoCardItem("ALTBAŞLIK","",),
    ]),
    */
  List<InfoCardModel> get turkceInfoCard => _turkceInfoCard;
}
