import '../../../model/info_card_item.dart';
import '../../../model/info_card_model.dart';

class MebTemelKanunuInfoViewModel {
  List<InfoCardModel> _mebTemelKanunuInfoCard = [
    InfoCardModel("Milli Eğitim Temel Kanunu-1", [
      InfoCardItem("mebtemelkanunu_info_1","Genellik ve Eşitlik","– Eğitim kurumları dil, ırk, cinsiyet, engellilik ve din ayırımı gözetilmeksizin herkese açıktır. Eğitimde hiçbir kişiye, aileye, zümreye veya sınıfa imtiyaz tanınamaz.(Madde 4)",),
      InfoCardItem("mebtemelkanunu_info_2","Ferdin ve Toplumun İhtiyaçları","Milli eğitim hizmeti, Türk vatandaşlarının istek ve kabiliyetleri ile Türk toplumunun ihtiyaçlarına göre düzenlenir. (Madde 5)",),
      InfoCardItem("mebtemelkanunu_info_3","Yöneltme","Fertler eğitimlerinde ilgi ve kabiliyetlerine göre yöneltilerek yetiştirilirler.\n-Sistem bu yöneltmeyi sağlayacak şekilde kurulmalıdır.\n-Bu amaçla ortaöğretimde hazırlık sınıfları oluşturulabilir.\n-Yöneltme ve başarının ölçülmesinde rehberlik hizmetlerinden ve objektif ölçme değerlendirme araçlarından faydalanılır.(Madde 6)",),
      InfoCardItem("mebtemelkanunu_info_4","Eğitim Hakkı","İlköğretim görmek her Türk vatandaşının hakkıdır.(Madde 7)",),
      InfoCardItem("mebtemelkanunu_info_5","Fırsat ve İmkan Eşitliği","-Kadın erkek herkese fırsat ve imkan eşitliği sağlanır.\n-Yoksul başarılı öğrenciler için en yüksek eğitim kademelerine kadar parasız yatılılık, burs, kredi ve başka yollarla gerekli yardımlar yapılır.\n-Özel eğitime ve korunmaya muhtaç çocuklar için özel tedbirler alınır.(Madde 8)",),
      InfoCardItem("mebtemelkanunu_info_6","Süreklilik","-Fertlerin genel ve mesleki eğitimlerinin hayat boyunca devam etmesi esastır.\n-Gençlerin eğitimi yanında, hayata ve iş alanlarına olumlu bir şekilde uymalarına yardımcı olmak üzere, yetişkinlerin sürekli eğitimini sağlamak için gerekli tedbirleri almak da bir eğitim görevidir.(Madde 9)",),
      InfoCardItem("mebtemelkanunu_info_7","Atatürk Milliyetçiliği","-Her türlü eğitim kademesinde, eğitim programında ve faliyetlerde Atatürk Milliyetçiliği temel alınır.\n-Milli ahlak ve kültür yozlaşmadan evrensel kültür içinde gelişime ve öğretilmesine önem verilir.\n-Türk dilinin öğretilmesine ve geliştirilmesine önem verilir.(Madde 10)",),
      InfoCardItem("mebtemelkanunu_info_8","Demokrasi Eğitimi","-Demokrasi bilinci, manevi değerlere saygı ve yurt yönetimine ait sorumluluk duygusunun öğrencilere kazandırılmasına çalışılır.\n-Atatürk milliyetçiliğine aykırı siyasi ve ideolojik telkinlere ve günlük siyasi olay ve tartışmalara karışılmasına kesinlikle izin verilmez.(Madde 11)",),
          ]), InfoCardModel("Milli Eğitim Temel Kanunu-2", [
         InfoCardItem("mebtemelkanunu_info_9","Laiklik","-Laiklik esastır.\n-Din kültürü ve ahlak öğretimi ilköğretim okulları ile lise ve dengi okullarda okutulan zorunlu dersler arasında yer alır.(Madde 12)",),
      InfoCardItem("mebtemelkanunu_info_10","Bilimsellilk","-Ders progrmları, eğitim metotları, ders araç-gereçleri geliştirilir.\n-Verimlilik için bilimsel araştırmaya önem verilir.\n-Eğitim kurumları donatılıp güçlendirilir, maddi ve manevi bakımdan teşvik edilir ve desteklenir.(Madde 13)",),
      InfoCardItem("mebtemelkanunu_info_11","Planlılık","-Eğitim-insangücü-istihdam ilişkisiyle sanayi ve tarımda modern seviyelere gelecek şekilde planlanır.\n-Meslek kademeleri, ünvan, yetki ve sorumluluklar kanunlarla belirlenir.\n-Yer, personel, araç-gereç, kapasite ve stantadrlar tespit edilir ve verimli olarak işletilmesi sağlanır.(Madde 14)",),
      InfoCardItem("mebtemelkanunu_info_12","Karma Eğitim","-Kız ve erkek karma eğitim esastır.\n-Eğitim türü, imkan ve zorunluluklara göre yalnızca kız veya erkek öğrencilerle eğitim sürdürülebilir.(Madde 15)",),
      InfoCardItem("mebtemelkanunu_info_13","Kampüs ve Okul-Aile İşbirliği-1","-Aynı alanda birden fazla kurum olursa kampüs kurulup kampüs yönetimi oluşturulabilir.\n-Kantin, salon vb ortak alanlar kampüs yönetimince işletilir/işlettirilir.\n-Gelirler ortak giderlere harcanabilir.\n-Kampüs oluşturma, gelir gider hesaplama ve harcama gibi konular Maliye-MEB müşterek yönetmelikle belirlenir.(Madde 16)",),
      InfoCardItem("mebtemelkanunu_info_14","Kampüs ve Okul-Aile İşbirliği-2","-Okul aile birlikleri kurum amaçlarının gerçekleştirilmesi için kurulur.\n-Verimli eğitim ve yoksul öğrenciler için etkinlik düzenleyebilir, yardım alabilir ve kantin vs. işletebilir.\n-Veli bağışa zorlanamaz.\n-Okul aile birliğinin varlığı, yapabilecekleri gibi hususlar Maliye-MEB müşterek yönetmelikle belirlenir.(Madde 16)",),
      InfoCardItem("mebtemelkanunu_info_15","Kampüs ve Okul-Aile İşbirliği-3","-İl müdürlükleri gerektiğinde eğitim kampüsleri ve okul aile birlikleri ile ilgili gerekli ihaleleri adlarına yapabilir.\n-Kampüs ve okul aile blrliği gelirleri genel bütçe ile karıştırmadan devlet bankasından açılacak hesapta tutulur.\n-Bu hesaplardaki gelirler tüm vergi ve harçlardan müstesnadır.(Madde 16)",),
      InfoCardItem("mebtemelkanunu_info_16","Her Yerde Eğitim","-Milli eğitim amaçları evde, işyerinde, okulda, özel okulda vs. her yerde geçerlidir.\n-Resmi, özel ve gönüllü her kuruluşun faliyetleri MEB denetimine tabidir.(Madde 17)",),
    ]),  InfoCardModel("Milli Eğitim Temel Kanunu-3", [
      InfoCardItem("mebtemelkanunu_info_17","Örgün ve Yaygın Eğitim","Örgün Eğitim;\n-Okul öncesi eğitim, ilköğretim, ortaöğretim ve yüksek öğretim kurumlarını kapsar.\nYaygın Eğitim;\n-Örgün eğitim yanında veya dışında düzenlenen eğitim faliyetlerinin tümünü kapsar.(Madde 18)",),
      InfoCardItem("mebtemelkanunu_info_18","Okul Öncesi(Kapsam)","-Mecburi eğitim kapsamına gelmemmiş ilkokul çocuklarının eğitimini kapsar.\n-Bu eğitim isteğe bağlıdır.(Madde 19)",),
      InfoCardItem("mebtemelkanunu_info_19","Okul Öncesi(Amaç ve Görevler)","-Beden, zihin ve duygu gelişimini ve iyi alışkanlıklar kazanmasını sağlamak;\n-İlköğretime hazırlamak;\n-İmkanı olmayan çocuklar için ortak yetiştirme ortamı sağlamak;\n-Türkçeyi doğru ve güzel kullanmalarını sağlamaktır.(Madde 20)",),
      InfoCardItem("mebtemelkanunu_info_20","Okul Öncesi(Kuruluş)","-Bağımsız anaokulu, ilköğretime bağlı anasınıfı veya öğretim kurumuna bağlı uygulama sınıfı olarak açılabilir.\n-Okulların nerelerde ve hangi özelliklerle açılacağı MEB tarafından hazırlanacak yönetmelikle belirlenir.(Madde 21)",),
      InfoCardItem("mebtemelkanunu_info_21","İlköğretim(Kapsam)","-Mecburi eğitim çağı, 6-14 yaş arasıdır.\n-1.sınıfa 31 Aralık'ta 72 ayını dolduranlar kaydolur.\n-Çocuğun gelişimine göre geç/erken başlama hakkı yönetmelikle düzenlenir.(Madde 22)",),
      InfoCardItem("mebtemelkanunu_info_22","İlköğretim(Amaç ve Görevler)","-Her Türk çocuğuna iyi vatandaş olmak için gerekli bilgi, beceri ve alışkanlıkları kazandırmak, milli ahlak anlayışı ile yetiştirmek;\n-İlgi, istidat ve kabiliyet yönünden hayata ve üst eğitim kurumuna hazırlamak;\n-Son ders yılının 2.yarısında ortaöğretim bilgilendirmesi rehberlik servisince yapılır.(Madde 23)",),
      InfoCardItem("mebtemelkanunu_info_23","İlköğretim(Kuruluş)","-İlkokul ve ortaokulların bağımsız kurulması esastır.\n-İmkan dahilinde ortaokullar ilkokul veya liselerle okutulabilir.\n-(Madde 24)",),
      ]),InfoCardModel("Milli Eğitim Temel Kanunu-4", [
        InfoCardItem("mebtemelkanunu_info_24","Ortaöğretim(Kurulu Şekilleri)-1","-4 yıllık zorunlu ilkokul, zorunlu ve farklı programlar arasında imkan veren ortaokullar ve imam-hatip ortaokullarından oluşur.\n-Lise eğitmini destekleyecek seçimlik dersler vardır.\n-Ortaokul ve liselerde Kur'an-ı Kerim ve Hz. Peygamberimizin hayatı isteğe bağlı seçmeli ders olarak okutulur.(Madde 25)",),
      InfoCardItem("mebtemelkanunu_info_25","Ortaöğretim(Kurulu Şekilleri)-2","-Okutulacak seçmeli dersler ile imamhatip ortaokulları ve diğer ortaokullar için oluşturulacak programlar Bakanlıkça belirlenir.\n-Köylerde ilköğretim bölge okulları, pansiyonlar veya yatılı bölge ortaokulları kurulur.(Madde 25)",),
      InfoCardItem("mebtemelkanunu_info_26","Ortaöğretim(Kapsam)","-İlköğretime dayalı 4 yıllık öğrenim veren genel, mesleki ve teknik ve mesleki eğitim merkezlerini kapsar.\n-Öğrenimi tamamlayanlara ilgili diploma verilir.\n-Mesleki eğitim öğrencileri diploma alabilmek için MEB'in belirlediği fark derslerini tamamlamak zorundadır.(Madde 26)",),
      InfoCardItem("mebtemelkanunu_info_27","Ortaöğretim(Yararlanma Hakkı)","İlköğretimi tamamlayan her öğrenci ortaöğretime devam etme hakkına sahiptir.(Madde 27)",),
      InfoCardItem("mebtemelkanunu_info_28","Ortaöğretim(Amaç ve Görevler)","-Öğrencilere asgari genel kültür vermek, toplum sorunlarını tanımak, çözüm yolları bulmak ve toplum kalkınmasına katkıda bulunmak;\n-Öğrencileri ilgi ve istidatları doğrultusunda yüksek öğretime ve mesleğe hazırlamak.\n-Öğrenci istekleri ve kabiliyetleri ile toplum ihtiyaçları göz önünde bulundurulur.(Madde 28)",),
      InfoCardItem("mebtemelkanunu_info_29","Ortaöğretim(Kuruluş)","-Çeşitli programlar uygulayan liseler ile mesleki eğitim merkezlerinden oluşur.\n-MEB'in takdiri ile nüfuzu az ve dağınık olan yerlere çok programlı liseler kurulabilir.\n-Öğrenim süresi, uygulanan programın özelliğine göre MEB tarafından tespit edilir.(Madde 29)",),
      InfoCardItem("mebtemelkanunu_info_30","Ortaöğretim(Yöneltme)","-Yöneltme ilköğretimde başlar, ortaöğretimde devam eder.\n-Esaslar, programlar ve yatay/dikey geçiş şartları MEB tarafından düzenlenir.(Madde 30)",),
      InfoCardItem("mebtemelkanunu_info_31","Ortaöğretim(Yükseköğretime geçiş)","-Lise veya dengi okulları bitirenler yükseköğretime girmek için aday olmaya hak kazanır.\n-Yükseköğretimde devam edilecek program ve giriş şartları MEB ve Yükseköğretim Kurulu tarafından ortaklaşa belirlenir.(Madde 31)",),
      InfoCardItem("mebtemelkanunu_info_32","Ortaöğretim(İmam-hatip)","İmamlık, hatiplik ve Kur'an kursu öğreticiliği gibi din hizmetlerine eleman yetiştirmek ve ilgili yükseköğretim kurumlarına hazırlama amacındadır.(Madde 32)",),
      InfoCardItem("mebtemelkanunu_info_33","Ortaöğretim(Güzel Sanatlar)","Özel istidat ve kabiliyetleri belirlenen çocukların küçük yaşlardan itibaren yetiştirilmesi amaçlanır.(Madde 33)",),
         ]),InfoCardModel("Milli Eğitim Temel Kanunu-5", [
          InfoCardItem("mebtemelkanunu_info_34","Yükseköğretim(Kapsam)","Orta öğretime dayalı en az iki yıllık yüksek öğrenim veren eğitim kurumlarının tümünü kapsar.(Madde 34)",),
      InfoCardItem("mebtemelkanunu_info_35","Yükseköğretim(Amaç ve Görevler)-1","-Öğrencilerin ilgi, istidat ve kabiliyetlerine göre ülkenin politikalarını ve toplum ihtiyaçlarını karşılayabilecek yüksek seviyede eleman yetiştirmek;\n-Bilimsel öğretim yapmak;\n-Bilimi genişletip derinleştirecek araştırmalar yapmak;\n-Hükümetçe istenecek konularda inceleme yaparak fikir vermek;(Madde 35)",),
      InfoCardItem("mebtemelkanunu_info_36","Yükseköğretim(Amaç ve Görevler)-2","-Ülkenin ilerleme ve gelişmesindeki sorunları incelemek;\n-Araştırma ve incelemelerin sonuçlarını gösteren, bilim ve tekniğin ilerlemesini sağlayan her türlü yayınlar yapmak;\n-Toplum seviyesini arttırıcı, kamuoyunu aydınlatıcı yazılı ve sözlü yayınlar yapmak yükseköğretimin amaçlarındandır.(Madde 35)",),
      InfoCardItem("mebtemelkanunu_info_37","Yükseköğretim(Kuruluş)-1","-Üniversite, fakülte, enstitü, yüksekokul, konservatuar, meslek yüksekokulu, uygulama ve araştırma merkezleri yükseköğretim kurumudur.\n-Yükseköğretim ile ilgili konular özel kanunlarla belirlenir.(Madde 36)",),
      InfoCardItem("mebtemelkanunu_info_38","Yükseköğretim(Kuruluş)-2","-Milli eğitim sistemi çerçevesinde lisans öncesi, lisans ve lisans üstü seviyelerinde bütünlük içinde düzenlenir.\n-Bu bütünlük içinde çeşitli görevleri yerine getiren ve farklı seviyelerde öğretim yapan kuruluşlar bulunur.\n-Kuruluşlar arasında yatay ve dikey geçiş imkanı vardır.(Madde 37)",),
      InfoCardItem("mebtemelkanunu_info_39","Yükseköğretim(Paralı Oluşu)","-Ücretlidir, ancak imkanı olmayan başarılı öğrenciler için burs, kredi ve parasız yatılı imkanları vardır.\n-Harç, burs, kredi ve bunların veriliş esasları Maliye Bakanlığı ile ortaklaşa düzenlenir.\n-Bazı alanlarda mecburi hizmet karşılığı öğrenci yetiştirilmesi esastır.(Madde 38)",),
      InfoCardItem("mebtemelkanunu_info_40","Yükseköğretim(Planlaması)","-Öğretim elemanlarının ve öğrencilerin zamandan en verimli şekilde faydalanmalarını sağlayacak tedbirler alınır.\n-Yükseköğretimin bütününü kapsayan ve ortaöğretimle ilgili sağlayan bir planlama düzenlenir.(Madde 39)",),
    ]),  InfoCardModel("Milli Eğitim Temel Kanunu-6", [
      InfoCardItem("mebtemelkanunu_info_41","Yaygın Eğitim-1","-Örgün eğitim hiç görmemiş veya eksik bırakmış kişilere uygun eğitim verir.\n-Okuma yazma öğretmek,\n-Bilimsel, teknolojik vs. gelişimlere ayak uydurmalarını sağlamak,\n-Değerlerimizi koruyucu, geliştirici ve tanıtıcı eğitim yapmak,\n-Toplu yaşama, dayanışma ve yardımlaşma vs. anlayışları kazanmak(Madde 40)",),
      InfoCardItem("mebtemelkanunu_info_42","Yaygın Eğitim-2","-İktisadi gücü arttırmak için gerekli sağlıklı yaşama ve beslenme kurallarını benimsemek,\n-Boş zamanlarını verimli değerlendirmeye alışmak,\n-Kısa sürede istihdam politikalarına uygun eleman yetiştirmek,\n-Çalışan bireylerin gelişimlerini sağlamak amaçları vardır.(Madde 40)",),
      InfoCardItem("mebtemelkanunu_info_43","Yaygın Eğitim-3","-Gerektiğinde örgün eğitim ile birbirini bütünleyici özelliktedir.\n-Gelen ve mesleki teknik eğitim olarak ikiye ayrılır.\n-Bu bölümler birbirini destekleyici niteliktedir.(Madde 41)",),
      InfoCardItem("mebtemelkanunu_info_44","Yaygın Eğitim-4","-Yaygın eğitmde görevli resmi, özel ve gönüllü kuruluşlar arası koordinasyon MEB tarafından sağlanır.\n-Programların düzenlenme şekli yönetmelikle belirlenir.\n-Yaygın eğitim faliyeti yürüten Bakanlıklar ile özerk, resmi ve özel işletmeler arası MEB tarafından sağlanacak koordinasyon esasları kanunlarla belirlenir.(Madde 42)",),
    ]),  InfoCardModel("Milli Eğitim Temel Kanunu-7", [
      InfoCardItem("mebtemelkanunu_info_45","Öğretmenlik Mesleği-1","-Devletin eğitim, öğretim ve yönetim görevlerini yerine getiren ÖZEL İHTİSAS mesleğidir.\n-Görev Türk Milli Eğitim amaçlarına uygun şekilde ifa edlmek zorundadır.\n-Mesleğe hazırlık genel kültür, özel alan eğitimi ve pedagojik formasyonla sağlanır.\n-Yüksek öğrenim görmek şarttır.\n-Yatay ve dikey geçişler yapılarak eğitim alınabilir.(Madde 43)",),
      InfoCardItem("mebtemelkanunu_info_46","Öğretmenlik Mesleği-2","-Adaylık döneminden sonra öğretmen, uzman öğretmen ve başöğretmen olarak 3'e ayrılır.\n-Aday öğretmen olmak için gerekli şartları taşımak ve sınavda başarılı olmak gerekir.\n-Aday öğretmen en az bir yıl fiilen çalışarak yazılı ve sözlü sınava girmeye hak kazanır.(Madde 43)",),
      InfoCardItem("mebtemelkanunu_info_47","Öğretmenlik Mesleği-3","SÖZLÜ SINAVDA;\n-Konuyu kavrayıp özetleme ve muhakeme gücüi\n-İletişim becerileri, öz güveni ve ikna kabiliyeti,\n-Bilimsel ve teknolojik gelişmelere açıklığı,\n-Topluluk önünde temsil yeteneği ve eğitimcilik nitelikleri yönlerinden Bakanlıkça oluşturulacak komisyon tarafından değerlendirilir.(Madde 43)",),
      InfoCardItem("mebtemelkanunu_info_48","Öğretmenlik Mesleği-4","-Sınavda başarılı olanlar öğretmen olarak atanır.\n-Başarılı olamayanlar il içinde veya dışında başka bir okulda görevlendirilerek bir yıl sonra aynı değerlendirmeye tabi tutulur.\n-Sınava girmeye hak kazanamayan veya sınavda 2 kez başarısız olanların memuriyetle ilişiği kesilir.(Madde 43)",),
      InfoCardItem("mebtemelkanunu_info_49","Öğretmenlik Mesleği-5","-Aday öğretmenlikten önce asli memurluğa atananlarda bu hükümler uygulanmaz ve uygun memur kadrolarına atanırlar.\n-Komisyon üyeleri Bakanlık personeli, kamuda çalışan personel ve öğretim elemanlarından seçilir.\n-Gerekirse illerde birden fazla komisyon oluşturulabilir.(Madde 43)",),
      InfoCardItem("mebtemelkanunu_info_51","Öğretmenlik Mesleği-6","-Kariyer basamaklarına yükselmede kıdem, eğitim, etkinlikler ve sicli puanları esas alınır.\n-%10 kıdem, %20 eğitim, %10 etkinlikler, %10 sicil, %50 de sınav puanı oluşturarak 100 puan üzerinden değerlendirilir.\n-Sınav puan üstünlüğüne göre sıralama yapılır.\n-Değerlendirme için en az %60 başarı gerekiz.(Madde 43)",),
         ]), InfoCardModel("Milli Eğitim Temel Kanunu-8", [
          InfoCardItem("mebtemelkanunu_info_52","Eğitim Yüksekokulu Açma","Öğretmenlik formasyonu veren ve öğretmen yetiştiren Milli Eğitim Bakanlığına bağlı eğitim yüksekokulları, Cumhurbaşkanı kararı ile kurulabilirler. (Madde 44)",),
      InfoCardItem("mebtemelkanunu_info_53","Öğretmen Nitelikleri","-Öğretmende aranacak nitelikler MEB tarafından belirlenir.\n-Öğretmen yetiştiren yükseköğrenim kurumları ve dengi yurtdışı yükseköğrenim kurumlarından mezun olanlar arasından MEB tarafından seçilir.\n-Yükseköğrenimde pedagojik formasyon almamış olanlar öğretmenliğe atanırsa MEB adaylık döneminde yetişmeleri için gerekli tedbirleri alır.(Madde 45)",),
      InfoCardItem("mebtemelkanunu_info_54","Öğretmenlerin Bölge Hizmetleri","-Öğretmenlikte yurdun farklı bölgelerinde görev yapmak esastır.\n-Hizmet bölgeleri ve bölgeler arası yer değiştirme esasları yönetmelikle düzenlenir.(Madde 46)",),
      InfoCardItem("mebtemelkanunu_info_55","Uzman ve Usta Öğreticiler","-Örgün ve yaygın eğitim kurumlarında, kurs, konferans ve seminerlerde uzman ve usta öğreticiler sürekli veya geçici görev alabilir.\n-Öğreticilerin seçimlerine ilişkin usül ve esaslar yönetmelikle belirlenir.(Madde 47)",),
      InfoCardItem("mebtemelkanunu_info_56","Hizmet İçi Yetiştirilme","-Öğretmenlerin daha üst öğrenim görmeleri için yaz ve akşam okulları açılır, kurslar ve seminerler düzenlenir.\n-Yaz ve akşam okulları öğretmen yetiştiren kurumlarca açılır ve kurs bitiminde yeterli krediyi dolduran öğretmenlere kurumun belge veya diploması verilir.\n-MEB tarafından açılan kurslarda başarılı olanlara da belge verilir. (Madde 48)",),
      InfoCardItem("mebtemelkanunu_info_57","Yurt İçi veya Yurt Dışı Yetişme","-Daha üst öğrenim yapmak, bilgi, görgü ve ihtisasını arttırmak isteyen öğretmenler belli şartlarla aylıklı veya aylıksız izinli sayılmaları sağlanır.\n-Bu şartlar ihtiyaçlar göz önünde tutularak hazırlanacak yönetmelikle belirtilir.(Madde 49)",),
      InfoCardItem("mebtemelkanunu_info_58","Öğretmen Konutları","-Gerek görülen yerlerde, özellikle mahrumiyet bölgelerinde konut tahsisini MEB sağlar.\n-Okul binaları ile planlanarak konutlar yapılır.\n-Eski eğitim kurumlarının ihtiyacı plana bağlanır ve yapımı için her yıl MEB bütçesine gerekli ödenek konur.(Madde 50)",),
      InfoCardItem("mebtemelkanunu_info_59","Öğrenmenlerin İzin ve Tatilleri-1","-Yaz tatili için 2 ay aralıksız izinlidir.\n-2 aylık izne dokunmadan kalan tatil zamanlarında düzenlenecek mesleki çalışmalara katılmak zorundadır.\n-Rehber öğretmenler tercih danışmanlığı, alan ve ders seçimi ve öğrenci tanılama süreci için görevlendirilebilir.\n-Bu durumda izinleri 1 aydan az olamaz.(Madde 50/A)",),
      InfoCardItem("mebtemelkanunu_info_60","Öğrenmenlerin İzin ve Tatilleri-2","-İlçe, il ve ülke genelinde salgın, doğal afet, elverişsiz hava koşulu gibi eğitime 2 hafta ara verilmesine sebep olan durumlarda telafi ders yılı içerisinde yapılamazsa yaz tatiline sarkabilir.\n-Bu durumda öğretmenlerin tatilleri 1 aydan az olamaz.\n-İdareciler tatil aylarında işleri ayarlamak suretiyle sırayla izin kullanabilirler.(Madde 50/A)",),
    ]),  InfoCardModel("Milli Eğitim Temel Kanunu-9", [
      InfoCardItem("mebtemelkanunu_info_61","Okul Yapıları ve Taşınmazları-1","-Her tür ve derecedeki bina ve tesis MEB tarafından planlanır ve yapılır.\n-Her yıl gerekli ödenek bütçeye konur.\n-Bütçede Devlet imkanları yanında vatandaş yardımları kullanılır ve teşvik edilir. (Madde 51)",),
      InfoCardItem("mebtemelkanunu_info_62","Okul Yapıları ve Taşınmazları-1","-MEB kullanımındaki taşınmazlar gerek görülürse MEB onayı ile Maliye Bakanlığı ve Özelleştirme İdaresi Başkanlığı ile kanunlara sadık kalarak özelleştirilebilir.\n-Elde edilen gelirler Hazineye aktarılır.\n-Gelirlerin MEB bütçesine ödenek olarak aktarılması için Maliye Bakanı yetkilidir.(Madde 51)",),
      InfoCardItem("mebtemelkanunu_info_63","Eğitim Araç Gereçleri","Ders kitapları, yardımcı kitaplar, yazılı/basılı eserler ve milli eğitimin genel amaçlarının gerçekleşmesine yararlı olacak diğer eserleri ve eğitim araç ve gereçlerini kapsar.(Madde 52)",),
      InfoCardItem("mebtemelkanunu_info_64","Görev","Eğitim araç gereçlerini gelişen teknoloji ve metotlara göre geliştirmek, değiştirmek, kullanım sürelerini ve telif hakları ve fiyatlarını belirlemek, paralı veya parasız ilgililerin hizmetine sunmak MEB'in görevidir.(Madde 53)",),
      InfoCardItem("mebtemelkanunu_info_65","Görevin Yerine Getirilmesi","ARAÇ GEREÇLERİ;\n-Hazırlamak, imal etmek ve satın almak,\n-Kişilere veya kuracağı komisyonlara veya yarışmalar düzenleyerek hazırlatmak,\n-Özel kesimce hazırlanan veya imal edilenler arasından seçmek suretiyle 53. maddedeki görevini yerine getirir. (Madde 54)",),
      InfoCardItem("mebtemelkanunu_info_66","Kitapların Tespiti ve Ücret Ödemesi","-MEB tarafından hazırlanacak/hazırlatılacak kitaplar ile eğitim araç ve gereçlerini hazırlama, inceleme ve redaksiyonunda görev alanlara ücret ödenir.\n-Özel kesimin hazırladığı ve okullarda ders kitabı olarak okutulmak istenip MEB'e gönderilen eserler ücret karşılığı incelenir. (Madde 55)",),
    ]),InfoCardModel("Milli Eğitim Temel Kanunu-10", [
      InfoCardItem("mebtemelkanunu_info_67","Yürütme, Gözetim ve Denetim","Eğitim ve öğretim hizmetinin, bu kanun hükümlerine göre Devlet adına yürütülmesinden, gözetim ve denetiminden MEB sorumludur.(Madde 56)",),
      InfoCardItem("mebtemelkanunu_info_68","Yasaklık","Askeri maksatlarla açılacak okullar hariç, bu kanun hükümlerine aykırı hiç bir eğitim faaliyetinde bulunulamaz. (Madde 57)",),
      InfoCardItem("mebtemelkanunu_info_69","Okul Açma Yetkisi","-MEB izni olmadan hiçbir okul açılamaz.\n-Okul derecelerinin tayini MEB'e aittir.\n-Askeri okulların derece ve müfredatında Milli Savunma Bakanlığı ile birlikte tespit edilir.\n-Diğer bakanlıklara bağlı okullar MEB ile ortak çalışır.\n-Gözetim ve denetim MEB'e aittir.\n-Denetimde eksiklikler tespit edilirse kurum denklikleri MEB tarafından iptal edilir. (Madde 58)",),
      InfoCardItem("mebtemelkanunu_info_70","Yurt Dışı Eğitim","Türk vatandaşlarının yurt dışında eğitim, öğrenim ve ihtisas görmeleri ile ilgili Devlet hizmetlerinin düzenlenmesinden (askeri öğrenciler hariç), Milli Eğitim Bakanlığı sorumludur.(Madde 59)",),
    ]),

  ];

  //Maddelemede kullan   =>  .\n-
  /*Öğe ekleme örneği
  InfoCardModel("Başlık", [
      InfoCardItem("ALTBAŞLIK","",),
    ]),
    */


  List<InfoCardModel> get mebTemelKanunuInfoCard => _mebTemelKanunuInfoCard;
}
